import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalPlaceholder } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of Compile Ready, an educational interview-preparation platform for software engineers.",
  alternates: { canonical: "/terms" },
};

const EMAIL = "hello@compileready.com";

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="August 4, 2026"
      intro="These Terms of Service govern your access to and use of Compile Ready. By using the site, you agree to these terms. Please read them carefully. This is not legal advice."
    >
      <h2>Acceptance of terms</h2>
      <p>
        By accessing or using Compile Ready, you agree to be bound by these
        terms. If you do not agree, please do not use the site. The service is
        operated by{" "}
        <LegalPlaceholder>[COMPANY LEGAL NAME]</LegalPlaceholder>.
      </p>

      <h2>The service</h2>
      <p>
        Compile Ready provides educational content and tools for technical
        interview preparation, including learning material, coding practice, and
        AI-assisted features. The service is provided for personal,
        non-commercial educational use.
      </p>

      <h2>Accounts</h2>
      <ul>
        <li>
          You are responsible for the information you provide and for activity
          under your account.
        </li>
        <li>
          You agree to provide accurate information and to keep your credentials
          secure.
        </li>
        <li>
          You must be at least 16 years old to create an account.
        </li>
      </ul>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Scrape, copy, resell, or redistribute the content except as expressly
          permitted.
        </li>
        <li>
          Abuse, overload, or attempt to disrupt the service or its
          infrastructure.
        </li>
        <li>Use the service for any unlawful purpose or to infringe others&apos; rights.</li>
        <li>Reverse engineer or attempt to extract source code except as allowed by law.</li>
      </ul>

      <h2>Intellectual property</h2>
      <p>
        The Compile Ready name, logo, original content, and software are owned by
        us or our licensors and are protected by intellectual-property laws.
        Company names, product names, and trademarks referenced in interview
        content belong to their respective owners and are used for
        identification and educational purposes only — see our{" "}
        <Link href="/disclaimer">Disclaimer</Link>.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Some content and feedback is generated by artificial intelligence and
        may be inaccurate or incomplete. It is provided &quot;as is&quot; for
        educational purposes and should be independently verified. See our{" "}
        <Link href="/disclaimer">Disclaimer</Link> for details.
      </p>

      <h2>No guarantees</h2>
      <p>
        The service is provided on an &quot;as is&quot; and &quot;as
        available&quot; basis without warranties of any kind. We do not guarantee
        any particular interview outcome, job offer, or result from using the
        platform.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Compile Ready and its operators
        will not be liable for any indirect, incidental, or consequential
        damages arising from your use of the service.
      </p>

      <h2>Termination</h2>
      <p>
        We may suspend or terminate access to the service at any time for
        conduct that violates these terms or is harmful to other users or the
        service.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of{" "}
        <LegalPlaceholder>[GOVERNING JURISDICTION]</LegalPlaceholder>, without
        regard to conflict-of-laws principles.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the service
        after changes take effect constitutes acceptance of the revised terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Email{" "}
        <a href={`mailto:${EMAIL}`}>{EMAIL}</a> or visit our{" "}
        <Link href="/contact">contact page</Link>.
      </p>
    </LegalPage>
  );
}
