import type {
  LLDCategory,
  LLDCompany,
  LLDDifficulty,
  LLDPattern,
  LLDProblemMeta,
  LLDTierMeta,
} from "./types";

/**
 * The Low Level Design (LLD) registry — the single source of truth for the
 * dashboard. Adding an entry to the catalog makes it appear on the dashboard,
 * roadmap, and filters automatically; authoring its content file (and flipping
 * `status` to "published") makes its page render. No UI/route changes.
 *
 * The catalog spans two kinds of entry (see `LLDProblemMeta.kind`):
 *   - `concept` — theory lessons (OOP, SOLID, patterns, UML, concurrency, …)
 *   - `problem` — full design problems across five domain categories
 */

// ---- Learning-path tiers (the Beginner → Expert roadmap) -------------------

export const LLD_TIERS: LLDTierMeta[] = [
  {
    id: "concepts",
    label: "Concepts & Foundations",
    emoji: "📚",
    accent: "emerald",
    description:
      "The vocabulary of object-oriented design — OOP, SOLID, design principles, UML, the pattern families, and concurrency. Master these before touching a problem.",
    order: 1,
  },
  {
    id: "beginner",
    label: "Beginner",
    emoji: "🟢",
    accent: "blue",
    description:
      "Your first machine-coding rounds — small, self-contained systems (parking lot, ATM, vending machine, tic-tac-toe) that teach the design loop end to end.",
    order: 2,
  },
  {
    id: "intermediate",
    label: "Intermediate",
    emoji: "🔵",
    accent: "violet",
    description:
      "Richer domains with more entities, state, and edge cases — elevators, caches, carts, and multiplayer games where patterns start to earn their keep.",
    order: 3,
  },
  {
    id: "advanced",
    label: "Advanced",
    emoji: "🟠",
    accent: "orange",
    description:
      "Systems with real concurrency, pluggable strategies, and non-trivial invariants — schedulers, message queues, file systems, and booking platforms.",
    order: 4,
  },
  {
    id: "expert",
    label: "Expert",
    emoji: "🔴",
    accent: "rose",
    description:
      "Staff-level object modelling for products at scale — payments, collaboration suites, chat platforms, drives, and AI systems, where extensibility is the whole point.",
    order: 5,
  },
];

// ---- Filter vocabularies ---------------------------------------------------

export const LLD_DIFFICULTIES: LLDDifficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
  "Expert",
];

export const LLD_CATEGORIES: LLDCategory[] = [
  "Concepts",
  "Core Systems",
  "Games",
  "Real-world Systems",
  "Advanced Systems",
  "Expert Systems",
];

export const LLD_COMPANIES: LLDCompany[] = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Netflix",
  "Uber",
  "Airbnb",
  "Atlassian",
  "Flipkart",
  "Swiggy",
  "Oracle",
  "Adobe",
  "PayPal",
  "LinkedIn",
];

export const LLD_PATTERNS: LLDPattern[] = [
  "Singleton",
  "Factory Method",
  "Abstract Factory",
  "Builder",
  "Prototype",
  "Adapter",
  "Bridge",
  "Composite",
  "Decorator",
  "Facade",
  "Flyweight",
  "Proxy",
  "Chain of Responsibility",
  "Command",
  "Iterator",
  "Mediator",
  "Memento",
  "Observer",
  "State",
  "Strategy",
  "Template Method",
  "Visitor",
  "Producer-Consumer",
  "Object Pool",
  "Dependency Injection",
  "Repository",
];

// ---- Catalog ---------------------------------------------------------------

/**
 * Raw catalog in reading order (Concepts → Expert). `addedOrder` is derived
 * below so items listed earlier are treated as "newer" for the Newest sort.
 * Published exemplars are listed at the top of their tier so they surface first.
 */
type RawMeta = Omit<LLDProblemMeta, "addedOrder">;

const RAW_CATALOG: RawMeta[] = [
  // ── 📚 Concepts & Foundations ─────────────────────────────────────────────
  {
    slug: "oop-fundamentals",
    title: "OOP Fundamentals",
    summary:
      "Encapsulation, abstraction, inheritance, and polymorphism — the four pillars every LLD answer is built on.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Beginner",
    companies: ["Amazon", "Microsoft", "Google", "Adobe"],
    patterns: [],
    tags: ["OOP", "Encapsulation", "Abstraction", "Inheritance", "Polymorphism"],
    popularity: 99,
    frequency: "Very High",
    estimatedMinutes: 30,
    status: "published",
  },
  {
    slug: "solid-principles",
    title: "SOLID Principles",
    summary:
      "The five principles (SRP, OCP, LSP, ISP, DIP) that separate a maintainable design from a brittle one.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Beginner",
    companies: ["Amazon", "Microsoft", "Google", "Oracle"],
    patterns: [],
    tags: ["SOLID", "SRP", "OCP", "LSP", "ISP", "DIP", "Clean Code"],
    popularity: 98,
    frequency: "Very High",
    estimatedMinutes: 35,
    status: "published",
  },
  {
    slug: "design-principles",
    title: "Design Principles (DRY, KISS, YAGNI)",
    summary:
      "The pragmatic heuristics — DRY, KISS, YAGNI, composition over inheritance, and law of Demeter — that keep code lean.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Beginner",
    companies: ["Amazon", "Google", "Atlassian"],
    patterns: [],
    tags: ["DRY", "KISS", "YAGNI", "Composition", "Coupling", "Cohesion"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 25,
    status: "published",
  },
  {
    slug: "uml-diagrams",
    title: "UML for Interviews",
    summary:
      "Read and draw class, sequence, and state diagrams fast — the notation interviewers expect on the whiteboard.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Beginner",
    companies: ["Microsoft", "Oracle", "Adobe"],
    patterns: [],
    tags: ["UML", "Class Diagram", "Sequence Diagram", "State Diagram"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 30,
    status: "published",
  },
  {
    slug: "creational-patterns",
    title: "Creational Patterns",
    summary:
      "Singleton, Factory, Abstract Factory, Builder, and Prototype — how to control object creation cleanly.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Intermediate",
    companies: ["Amazon", "Microsoft", "Google"],
    patterns: ["Singleton", "Factory Method", "Abstract Factory", "Builder", "Prototype"],
    tags: ["Patterns", "Creational", "Factory", "Builder", "Singleton"],
    popularity: 92,
    frequency: "Very High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "structural-patterns",
    title: "Structural Patterns",
    summary:
      "Adapter, Decorator, Facade, Composite, Proxy, Bridge, and Flyweight — how to compose objects into larger structures.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Intermediate",
    companies: ["Amazon", "Microsoft", "Netflix"],
    patterns: ["Adapter", "Decorator", "Facade", "Composite", "Proxy", "Bridge", "Flyweight"],
    tags: ["Patterns", "Structural", "Decorator", "Adapter", "Proxy"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "behavioral-patterns",
    title: "Behavioral Patterns",
    summary:
      "Strategy, Observer, State, Command, Chain of Responsibility, and more — how objects collaborate and share responsibility.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Intermediate",
    companies: ["Amazon", "Google", "Uber"],
    patterns: ["Strategy", "Observer", "State", "Command", "Chain of Responsibility", "Template Method", "Iterator", "Mediator"],
    tags: ["Patterns", "Behavioral", "Strategy", "Observer", "State"],
    popularity: 91,
    frequency: "Very High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "concurrency-and-multithreading",
    title: "Concurrency & Multithreading",
    summary:
      "Threads, locks, atomics, thread-safe collections, and producer-consumer — making an LLD design safe under load.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Oracle", "Microsoft"],
    patterns: ["Producer-Consumer", "Object Pool"],
    tags: ["Concurrency", "Threads", "Locks", "Atomics", "Thread Safety"],
    popularity: 87,
    frequency: "High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "java-collections-for-lld",
    title: "Java Collections for LLD",
    summary:
      "Pick the right List, Map, Set, Queue, or concurrent collection — and know the tradeoffs cold.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Intermediate",
    companies: ["Amazon", "Oracle", "Flipkart"],
    patterns: ["Iterator"],
    tags: ["Java", "Collections", "HashMap", "TreeMap", "Queue", "Data Structures"],
    popularity: 82,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "published",
  },
  {
    slug: "lld-best-practices",
    title: "LLD Best Practices",
    summary:
      "A pragmatic checklist for machine-coding rounds — naming, immutability, error handling, testing, and time management.",
    kind: "concept",
    tier: "concepts",
    category: "Concepts",
    difficulty: "Intermediate",
    companies: ["Amazon", "Atlassian", "Google"],
    patterns: [],
    tags: ["Best Practices", "Clean Code", "Testing", "Machine Coding"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 25,
    status: "published",
  },

  // ── 🟢 Beginner ───────────────────────────────────────────────────────────
  {
    slug: "parking-lot",
    title: "Design a Parking Lot",
    summary:
      "The canonical LLD warm-up — multi-level lots, vehicle/spot types, ticketing, and pluggable pricing.",
    kind: "problem",
    tier: "beginner",
    category: "Core Systems",
    difficulty: "Beginner",
    companies: ["Amazon", "Google", "Microsoft", "Flipkart"],
    patterns: ["Strategy", "Factory Method", "Singleton"],
    tags: ["Parking", "Strategy", "Factory", "Ticketing", "Pricing"],
    popularity: 99,
    frequency: "Very High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "vending-machine",
    title: "Design a Vending Machine",
    summary:
      "A finite-state machine done right — idle, selecting, dispensing, and refunding, with inventory and change.",
    kind: "problem",
    tier: "beginner",
    category: "Real-world Systems",
    difficulty: "Beginner",
    companies: ["Amazon", "Microsoft", "Adobe", "Oracle"],
    patterns: ["State", "Singleton", "Strategy"],
    tags: ["Vending", "State Machine", "Inventory", "Payments"],
    popularity: 96,
    frequency: "Very High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "coffee-machine",
    title: "Design a Coffee Machine",
    summary:
      "Recipes, shared ingredients, and concurrent dispensing — a compact study in Builder + resource contention.",
    kind: "problem",
    tier: "beginner",
    category: "Real-world Systems",
    difficulty: "Beginner",
    companies: ["Amazon", "Swiggy", "Oracle"],
    patterns: ["Builder", "Factory Method", "Singleton"],
    tags: ["Coffee", "Builder", "Ingredients", "Concurrency"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "atm",
    title: "Design an ATM",
    summary:
      "A textbook State-pattern problem — card, PIN, selection, and dispense states with a cash-management backend.",
    kind: "problem",
    tier: "beginner",
    category: "Core Systems",
    difficulty: "Beginner",
    companies: ["Amazon", "PayPal", "Oracle", "Microsoft"],
    patterns: ["State", "Chain of Responsibility", "Singleton"],
    tags: ["ATM", "State Machine", "Banking", "Cash Dispense"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "tic-tac-toe",
    title: "Design Tic-Tac-Toe",
    summary:
      "A clean two-player game engine — board, moves, win detection, and an extensible rules/strategy seam.",
    kind: "problem",
    tier: "beginner",
    category: "Games",
    difficulty: "Beginner",
    companies: ["Amazon", "Google", "Adobe"],
    patterns: ["Strategy", "State", "Factory Method"],
    tags: ["Game", "Board", "Win Detection", "Strategy"],
    popularity: 89,
    frequency: "High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "snake-and-ladder",
    title: "Design Snake & Ladder",
    summary:
      "Board, dice, snakes, ladders, and turn management — small surface, plenty of clean-modelling opportunities.",
    kind: "problem",
    tier: "beginner",
    category: "Games",
    difficulty: "Beginner",
    companies: ["Amazon", "Flipkart", "Microsoft"],
    patterns: ["Strategy", "Factory Method", "Observer"],
    tags: ["Game", "Board", "Dice", "Turns"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "library-management",
    title: "Design a Library Management System",
    summary:
      "Members, books, copies, holds, and fines — the classic CRUD-heavy modelling exercise done cleanly.",
    kind: "problem",
    tier: "beginner",
    category: "Core Systems",
    difficulty: "Beginner",
    companies: ["Amazon", "Oracle", "Microsoft"],
    patterns: ["Repository", "Strategy", "Observer"],
    tags: ["Library", "Catalog", "Membership", "Fines"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },

  // ── 🔵 Intermediate ───────────────────────────────────────────────────────
  {
    slug: "elevator-system",
    title: "Design an Elevator System",
    summary:
      "Multi-car scheduling, direction/state machines, and pluggable dispatch strategies under concurrent requests.",
    kind: "problem",
    tier: "intermediate",
    category: "Core Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Google", "Uber", "Microsoft"],
    patterns: ["State", "Strategy", "Singleton", "Observer"],
    tags: ["Elevator", "Scheduling", "State Machine", "Concurrency"],
    popularity: 94,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "lru-cache",
    title: "Design an LRU Cache",
    summary:
      "O(1) get/put with a hashmap + doubly-linked list — the most-asked data-structure design in machine coding.",
    kind: "problem",
    tier: "intermediate",
    category: "Advanced Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Google", "Meta", "Microsoft"],
    patterns: ["Strategy", "Facade"],
    tags: ["Cache", "LRU", "HashMap", "Doubly Linked List", "Eviction"],
    popularity: 97,
    frequency: "Very High",
    estimatedMinutes: 40,
    status: "published",
  },
  {
    slug: "splitwise",
    title: "Design Splitwise",
    summary:
      "Groups, expenses, and split strategies (equal/exact/percent) with a balance-simplification engine.",
    kind: "problem",
    tier: "intermediate",
    category: "Core Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Uber", "Flipkart", "PayPal"],
    patterns: ["Strategy", "Observer", "Factory Method"],
    tags: ["Expenses", "Splitting", "Balances", "Strategy"],
    popularity: 91,
    frequency: "High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "logging-framework",
    title: "Design a Logging Framework",
    summary:
      "Levels, appenders, and a handler chain — a Chain-of-Responsibility showcase with async, thread-safe sinks.",
    kind: "problem",
    tier: "intermediate",
    category: "Advanced Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Microsoft", "Oracle"],
    patterns: ["Chain of Responsibility", "Singleton", "Strategy", "Observer"],
    tags: ["Logging", "Chain of Responsibility", "Appenders", "Levels"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "rate-limiter",
    title: "Design a Rate Limiter (LLD)",
    summary:
      "Token bucket, leaky bucket, and sliding window as interchangeable strategies behind one thread-safe interface.",
    kind: "problem",
    tier: "intermediate",
    category: "Advanced Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Google", "Uber", "Atlassian"],
    patterns: ["Strategy", "Factory Method", "Singleton"],
    tags: ["Rate Limiter", "Token Bucket", "Sliding Window", "Concurrency"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "url-shortener",
    title: "Design a URL Shortener (LLD)",
    summary:
      "The object model behind TinyURL — encoders, repositories, and expiry, without the distributed-systems layer.",
    kind: "problem",
    tier: "intermediate",
    category: "Advanced Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Microsoft", "Flipkart"],
    patterns: ["Strategy", "Repository", "Factory Method"],
    tags: ["URL Shortener", "Encoding", "Repository", "Expiry"],
    popularity: 82,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "movie-booking",
    title: "Design a Movie Ticket Booking System",
    summary:
      "BookMyShow — theatres, shows, seat maps, and concurrent seat locking with a payment workflow.",
    kind: "problem",
    tier: "intermediate",
    category: "Core Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Flipkart", "Swiggy", "Uber"],
    patterns: ["State", "Strategy", "Observer", "Singleton"],
    tags: ["Booking", "Seat Locking", "Concurrency", "Payments"],
    popularity: 89,
    frequency: "High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "hotel-management",
    title: "Design a Hotel Management System",
    summary:
      "Rooms, rates, reservations, check-in/out, and housekeeping — a broad domain-modelling exercise.",
    kind: "problem",
    tier: "intermediate",
    category: "Core Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Airbnb", "Oracle"],
    patterns: ["State", "Strategy", "Factory Method", "Observer"],
    tags: ["Hotel", "Reservations", "Rooms", "Billing"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "shopping-cart",
    title: "Design a Shopping Cart",
    summary:
      "Cart items, pluggable discount/pricing rules, and a checkout pipeline with tax and coupons.",
    kind: "problem",
    tier: "intermediate",
    category: "Real-world Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Flipkart", "Adobe"],
    patterns: ["Strategy", "Decorator", "Composite", "Observer"],
    tags: ["E-Commerce", "Cart", "Discounts", "Checkout"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "digital-wallet",
    title: "Design a Digital Wallet",
    summary:
      "Accounts, balances, transfers, and a double-entry ledger with idempotent, atomic transactions.",
    kind: "problem",
    tier: "intermediate",
    category: "Real-world Systems",
    difficulty: "Intermediate",
    companies: ["PayPal", "Amazon", "Flipkart", "Uber"],
    patterns: ["State", "Command", "Strategy", "Repository"],
    tags: ["Wallet", "Ledger", "Transactions", "Idempotency"],
    popularity: 83,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "inventory-management",
    title: "Design an Inventory Management System",
    summary:
      "SKUs, warehouses, stock movements, and reorder rules with an event-driven low-stock notifier.",
    kind: "problem",
    tier: "intermediate",
    category: "Real-world Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Flipkart", "Swiggy"],
    patterns: ["Observer", "Strategy", "Repository", "State"],
    tags: ["Inventory", "Warehouse", "Stock", "Reorder"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "minesweeper",
    title: "Design Minesweeper",
    summary:
      "Grid generation, flood-fill reveal, flagging, and win/lose detection — a tidy board-game engine.",
    kind: "problem",
    tier: "intermediate",
    category: "Games",
    difficulty: "Intermediate",
    companies: ["Amazon", "Google", "Adobe"],
    patterns: ["State", "Strategy", "Factory Method"],
    tags: ["Game", "Grid", "Flood Fill", "State"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "ludo",
    title: "Design Ludo",
    summary:
      "Multiple players, tokens, dice, home paths, and turn/capture rules — multiplayer state modelled cleanly.",
    kind: "problem",
    tier: "intermediate",
    category: "Games",
    difficulty: "Intermediate",
    companies: ["Amazon", "Flipkart"],
    patterns: ["State", "Strategy", "Observer", "Factory Method"],
    tags: ["Game", "Multiplayer", "Dice", "Turns"],
    popularity: 68,
    frequency: "Low",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "notification-system",
    title: "Design a Notification System",
    summary:
      "Multi-channel (email/SMS/push) delivery with templates, preferences, retries, and pluggable providers.",
    kind: "problem",
    tier: "intermediate",
    category: "Advanced Systems",
    difficulty: "Intermediate",
    companies: ["Amazon", "Uber", "Swiggy", "Atlassian"],
    patterns: ["Observer", "Strategy", "Factory Method", "Adapter", "Decorator"],
    tags: ["Notifications", "Channels", "Templates", "Retries"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },

  // ── 🟠 Advanced ───────────────────────────────────────────────────────────
  {
    slug: "chess",
    title: "Design Chess",
    summary:
      "Pieces, moves, check/checkmate, and rules — a polymorphism-heavy engine with per-piece move strategies.",
    kind: "problem",
    tier: "advanced",
    category: "Games",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Microsoft"],
    patterns: ["Strategy", "Factory Method", "State", "Command"],
    tags: ["Game", "Chess", "Moves", "Polymorphism"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "lfu-cache",
    title: "Design an LFU Cache",
    summary:
      "Least-Frequently-Used eviction in O(1) with frequency buckets — the harder cousin of LRU.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Meta"],
    patterns: ["Strategy", "Facade"],
    tags: ["Cache", "LFU", "Frequency", "Eviction"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "task-scheduler",
    title: "Design a Task Scheduler",
    summary:
      "Cron-like scheduling, priority queues, worker pools, and retry/backoff under concurrency.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Uber", "Atlassian"],
    patterns: ["Command", "Strategy", "Producer-Consumer", "Observer"],
    tags: ["Scheduler", "Priority Queue", "Workers", "Retry"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "message-queue",
    title: "Design an In-Memory Message Queue",
    summary:
      "Topics, producers, consumers, offsets, and delivery guarantees — Kafka's object model in miniature.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "LinkedIn", "Uber"],
    patterns: ["Producer-Consumer", "Observer", "Strategy", "Singleton"],
    tags: ["Queue", "Pub/Sub", "Offsets", "Concurrency"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "file-system",
    title: "Design an In-Memory File System",
    summary:
      "Directories, files, paths, and a Composite tree with ls/mkdir/read/write operations.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Microsoft"],
    patterns: ["Composite", "Iterator", "Strategy"],
    tags: ["File System", "Composite", "Tree", "Paths"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "linux-find",
    title: "Design the Linux 'find' Command",
    summary:
      "Composable filters (name/size/type) combined with And/Or/Not — a Specification + Composite exercise.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Google", "Adobe"],
    patterns: ["Composite", "Strategy", "Chain of Responsibility"],
    tags: ["Find", "Filters", "Specification", "Composite"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "text-editor",
    title: "Design a Text Editor",
    summary:
      "Insert/delete, cursor movement, and undo/redo via Command + Memento, with a gap-buffer document model.",
    kind: "problem",
    tier: "advanced",
    category: "Advanced Systems",
    difficulty: "Advanced",
    companies: ["Google", "Microsoft", "Adobe"],
    patterns: ["Command", "Memento", "Strategy"],
    tags: ["Editor", "Undo/Redo", "Command", "Memento"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "airline-reservation",
    title: "Design an Airline Reservation System",
    summary:
      "Flights, fares, seat inventory, PNRs, and a booking/cancellation workflow with concurrency control.",
    kind: "problem",
    tier: "advanced",
    category: "Core Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Oracle", "Airbnb"],
    patterns: ["State", "Strategy", "Observer", "Repository"],
    tags: ["Airline", "Reservations", "Seats", "Fares"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "food-delivery",
    title: "Design a Food Delivery System",
    summary:
      "Restaurants, menus, carts, orders, and delivery-partner matching — Swiggy/DoorDash object modelling.",
    kind: "problem",
    tier: "advanced",
    category: "Core Systems",
    difficulty: "Advanced",
    companies: ["Swiggy", "Amazon", "Uber", "Flipkart"],
    patterns: ["State", "Strategy", "Observer", "Factory Method"],
    tags: ["Food Delivery", "Orders", "Matching", "State Machine"],
    popularity: 87,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "cab-booking",
    title: "Design a Cab Booking System",
    summary:
      "Riders, drivers, trip lifecycle, surge pricing, and nearest-driver matching — Uber/Ola in objects.",
    kind: "problem",
    tier: "advanced",
    category: "Core Systems",
    difficulty: "Advanced",
    companies: ["Uber", "Amazon", "Swiggy"],
    patterns: ["State", "Strategy", "Observer", "Singleton"],
    tags: ["Cab", "Matching", "Surge", "Trip Lifecycle"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "feature-flag-service",
    title: "Design a Feature Flag Service",
    summary:
      "Flags, targeting rules, rollout percentages, and evaluation — a rules-engine + strategy design.",
    kind: "problem",
    tier: "advanced",
    category: "Expert Systems",
    difficulty: "Advanced",
    companies: ["Atlassian", "Amazon", "LinkedIn"],
    patterns: ["Strategy", "Chain of Responsibility", "Observer", "Singleton"],
    tags: ["Feature Flags", "Targeting", "Rollout", "Rules Engine"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "authentication-service",
    title: "Design an Authentication Service",
    summary:
      "Signup/login, password hashing, sessions/tokens, and pluggable providers (password, OTP, OAuth).",
    kind: "problem",
    tier: "advanced",
    category: "Expert Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Microsoft", "Google", "Oracle"],
    patterns: ["Strategy", "Factory Method", "Chain of Responsibility"],
    tags: ["Auth", "Sessions", "Tokens", "OAuth"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "rbac-system",
    title: "Design a Role-Based Access Control (RBAC) System",
    summary:
      "Users, roles, permissions, and resource-level checks with hierarchical roles and policy evaluation.",
    kind: "problem",
    tier: "advanced",
    category: "Expert Systems",
    difficulty: "Advanced",
    companies: ["Amazon", "Microsoft", "Atlassian", "Oracle"],
    patterns: ["Composite", "Strategy", "Chain of Responsibility"],
    tags: ["RBAC", "Permissions", "Roles", "Authorization"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "published",
  },

  // ── 🔴 Expert ─────────────────────────────────────────────────────────────
  {
    slug: "payment-gateway",
    title: "Design a Payment Gateway",
    summary:
      "Payment intents, provider adapters, idempotency, webhooks, and a saga for capture/refund flows.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["PayPal", "Amazon", "Uber", "Adobe"],
    patterns: ["Adapter", "State", "Strategy", "Command", "Facade"],
    tags: ["Payments", "Adapters", "Idempotency", "Webhooks", "Saga"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 70,
    status: "published",
  },
  {
    slug: "banking-system",
    title: "Design a Banking System",
    summary:
      "Accounts, transactions, a double-entry ledger, interest, and statements with strong consistency.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["PayPal", "Amazon", "Oracle"],
    patterns: ["State", "Command", "Strategy", "Repository", "Observer"],
    tags: ["Banking", "Ledger", "Transactions", "Consistency"],
    popularity: 82,
    frequency: "Medium",
    estimatedMinutes: 70,
    status: "published",
  },
  {
    slug: "whatsapp",
    title: "Design WhatsApp (LLD)",
    summary:
      "Users, chats, messages, delivery/read receipts, and group management — the messaging object model.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Meta", "Amazon", "Google"],
    patterns: ["Observer", "Mediator", "State", "Strategy"],
    tags: ["Messaging", "Chat", "Receipts", "Groups"],
    popularity: 89,
    frequency: "High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "slack",
    title: "Design Slack (LLD)",
    summary:
      "Workspaces, channels, threads, mentions, and notifications — team-chat modelled with clean boundaries.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Atlassian", "Amazon", "Meta"],
    patterns: ["Observer", "Mediator", "Composite", "Strategy"],
    tags: ["Chat", "Channels", "Threads", "Notifications"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "google-docs",
    title: "Design Google Docs (LLD)",
    summary:
      "Documents, collaborative editing, operational transforms/CRDTs, and version history modelled in objects.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Google", "Microsoft", "Adobe"],
    patterns: ["Command", "Memento", "Observer", "Strategy"],
    tags: ["Collaboration", "OT", "CRDT", "Versioning"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 70,
    status: "published",
  },
  {
    slug: "trello",
    title: "Design Trello (LLD)",
    summary:
      "Boards, lists, cards, labels, and drag-drop ordering with activity feeds — Kanban in objects.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Atlassian", "Amazon"],
    patterns: ["Composite", "Observer", "Command", "Strategy"],
    tags: ["Kanban", "Boards", "Cards", "Ordering"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "jira",
    title: "Design Jira (LLD)",
    summary:
      "Issues, workflows/state machines, sprints, and a flexible custom-field model with audit history.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Atlassian", "Amazon", "Oracle"],
    patterns: ["State", "Observer", "Strategy", "Command"],
    tags: ["Issue Tracking", "Workflow", "Sprints", "Audit"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "dropbox",
    title: "Design Dropbox (LLD)",
    summary:
      "Files, folders, versioning, chunking, and sync-state modelling for a file-hosting client.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Amazon", "Google", "Microsoft"],
    patterns: ["Composite", "Observer", "Strategy", "Memento"],
    tags: ["File Sync", "Versioning", "Chunking", "Composite"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "google-drive",
    title: "Design Google Drive (LLD)",
    summary:
      "Files, folders, sharing/permissions, and search — a hierarchical storage model with ACLs.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Google", "Amazon", "Microsoft"],
    patterns: ["Composite", "Strategy", "Proxy", "Observer"],
    tags: ["Storage", "Sharing", "Permissions", "Composite"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "api-gateway",
    title: "Design an API Gateway (LLD)",
    summary:
      "Routing, middleware chains (auth/rate-limit/logging), and pluggable filters behind one entry point.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Amazon", "Netflix", "Atlassian"],
    patterns: ["Chain of Responsibility", "Strategy", "Decorator", "Facade", "Proxy"],
    tags: ["Gateway", "Middleware", "Routing", "Filters"],
    popularity: 83,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "ai-chat-platform",
    title: "Design an AI Chat Platform (LLD)",
    summary:
      "Conversations, messages, model providers, streaming, tools, and context windows modelled in objects.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Microsoft", "Google", "Amazon"],
    patterns: ["Strategy", "Adapter", "Observer", "Command", "Decorator"],
    tags: ["AI", "Chat", "Streaming", "Tools", "Providers"],
    popularity: 85,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "rag-pipeline",
    title: "Design a RAG Pipeline (LLD)",
    summary:
      "Loaders, chunkers, embedders, a vector store, retrievers, and a generation step composed as a pipeline.",
    kind: "problem",
    tier: "expert",
    category: "Expert Systems",
    difficulty: "Expert",
    companies: ["Microsoft", "Google", "Amazon"],
    patterns: ["Strategy", "Template Method", "Adapter", "Builder", "Facade"],
    tags: ["AI", "RAG", "Embeddings", "Vector Store", "Pipeline"],
    popularity: 84,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "published",
  },
];

/** The full LLD catalog, with `addedOrder` derived (earlier = newer). */
export const LLD_CATALOG: LLDProblemMeta[] = RAW_CATALOG.map((q, i) => ({
  ...q,
  addedOrder: RAW_CATALOG.length - i,
}));
