import type {
  GenAICompany,
  GenAIDifficulty,
  GenAILessonMeta,
  GenAITierMeta,
  GenAITopic,
} from "./types";

/**
 * The Generative AI registry — the single source of truth for the dashboard.
 * Adding a lesson to the catalog makes it appear on the dashboard and in the
 * learning path automatically; authoring its content file (and flipping
 * `status` to "published") makes its page render. No UI/route changes.
 */

// ---- Learning-path tiers ---------------------------------------------------

export const GENAI_TIERS: GenAITierMeta[] = [
  {
    id: "l1-foundations",
    label: "Level 1 · AI Foundations",
    emoji: "🟢",
    accent: "emerald",
    description:
      "The mental models every AI interview assumes you already have — transformers, attention, tokenization, inference, and decoding.",
    order: 1,
  },
  {
    id: "l2-working-with-llms",
    label: "Level 2 · Working with LLMs",
    emoji: "🔵",
    accent: "blue",
    description:
      "Building on model APIs day to day — provider SDKs, structured outputs, JSON mode, streaming, function/tool calling, prompt templates, and guardrails.",
    order: 2,
  },
  {
    id: "l3-rag",
    label: "Level 3 · Retrieval-Augmented Generation",
    emoji: "🟣",
    accent: "violet",
    description:
      "Grounding LLMs in your own data — chunking, hybrid retrieval, reranking, evaluation, and cost control.",
    order: 3,
  },
  {
    id: "l4-vector-databases",
    label: "Level 4 · Vector Databases & Search",
    emoji: "🟦",
    accent: "cyan",
    description:
      "The retrieval substrate behind RAG — embeddings, ANN indexes (HNSW, IVF-PQ), sharding, and filtered search at billion scale.",
    order: 4,
  },
  {
    id: "l5-agents",
    label: "Level 5 · AI Agents & Orchestration",
    emoji: "🟠",
    accent: "orange",
    description:
      "Systems that plan and act — tool calling, memory, guardrails, and multi-agent orchestration.",
    order: 5,
  },
  {
    id: "l6-ai-system-design",
    label: "Level 6 · AI System Design",
    emoji: "🔴",
    accent: "rose",
    description:
      "End-to-end product systems built on top of LLMs — ChatGPT, coding assistants, answer engines, content moderation, and streaming UX.",
    order: 6,
  },
  {
    id: "l7-production-ai",
    label: "Level 7 · Production AI",
    emoji: "🟩",
    accent: "emerald",
    description:
      "Running AI in production — model serving, KV cache, batching, quantization, observability, evaluation, semantic caching, and cost optimization.",
    order: 7,
  },
  {
    id: "l8-advanced-ai",
    label: "Level 8 · Advanced AI",
    emoji: "🟤",
    accent: "slate",
    description:
      "The platforms and hard problems behind the models — distributed training, fine-tuning, RLHF, feature stores, safety, security, and governance.",
    order: 8,
  },
  {
    id: "l9-interview-prep",
    label: "Level 9 · Interview Preparation",
    emoji: "⭐",
    accent: "violet",
    description:
      "Full mock-interview problems that combine everything — recommendations, image generation, voice, translation, and more.",
    order: 9,
  },
  {
    id: "l10-projects",
    label: "Level 10 · Hands-On Projects",
    emoji: "🚀",
    accent: "orange",
    description:
      "Capstone builds that turn the roadmap into portfolio projects — build ChatGPT, a coding copilot, a RAG system, an agent, and an AI search engine.",
    order: 10,
  },
];

// ---- Filter vocabularies ---------------------------------------------------

export const GENAI_DIFFICULTIES: GenAIDifficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
];

export const GENAI_TOPICS: GenAITopic[] = [
  "LLM Fundamentals",
  "Prompt Engineering",
  "RAG",
  "Embeddings",
  "Vector Databases",
  "AI Agents",
  "Model Serving",
  "Fine-Tuning",
  "AI Infrastructure",
  "AI Evaluation",
  "AI Security",
  "AI Observability",
  "Multi-Agent Systems",
];

export const GENAI_COMPANIES: GenAICompany[] = [
  "OpenAI",
  "Anthropic",
  "Google DeepMind",
  "Meta",
  "Microsoft",
  "Amazon",
  "NVIDIA",
  "Databricks",
  "Cohere",
  "Perplexity",
];

// ---- Catalog ---------------------------------------------------------------

/**
 * Raw catalog in reading order (Foundations → Interview Problems). `addedOrder`
 * is derived below so items listed earlier are treated as "newer" for the
 * Newest sort; the three published exemplars sit at the top and therefore sort
 * first.
 */
type RawMeta = Omit<GenAILessonMeta, "addedOrder">;

const RAW_CATALOG: RawMeta[] = [
  // 🟢 Level 1 · AI Foundations
  {
    slug: "transformer-architecture",
    title: "Transformer Architecture",
    summary:
      "How the transformer block works end-to-end — embeddings, self-attention, feed-forward layers, and residual streams.",
    tier: "l1-foundations",
    difficulty: "Beginner",
    topics: ["LLM Fundamentals"],
    companies: ["OpenAI", "Google DeepMind", "Meta"],
    tags: ["Transformer", "Attention", "Embeddings", "Architecture"],
    popularity: 90,
    frequency: "Very High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "attention-mechanism",
    title: "Attention Mechanism",
    summary:
      "Scaled dot-product and multi-head attention — the intuition, the math, and why it scales to long context.",
    tier: "l1-foundations",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals"],
    companies: ["OpenAI", "Google DeepMind", "NVIDIA"],
    tags: ["Attention", "Multi-Head", "Softmax", "QKV"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "tokenization-and-embeddings",
    title: "Tokenization & Embeddings",
    summary:
      "BPE, subword vocabularies, and how tokens become vectors — the input side of every LLM.",
    tier: "l1-foundations",
    difficulty: "Beginner",
    topics: ["LLM Fundamentals", "Embeddings"],
    companies: ["OpenAI", "Cohere", "Meta"],
    tags: ["Tokenization", "BPE", "Embeddings", "Vocabulary"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "how-llm-inference-works",
    title: "How LLM Inference Works",
    summary:
      "Prefill vs decode, the KV cache, and why the first token is slow but the rest are fast.",
    tier: "l1-foundations",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "Model Serving"],
    companies: ["OpenAI", "NVIDIA", "Databricks"],
    tags: ["Inference", "Prefill", "Decode", "KV Cache"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "sampling-and-decoding",
    title: "Sampling & Decoding Strategies",
    summary:
      "Temperature, top-k, top-p, and beam search — how token probabilities become text, and when to use each.",
    tier: "l1-foundations",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "Prompt Engineering"],
    companies: ["OpenAI", "Anthropic", "Cohere"],
    tags: ["Sampling", "Temperature", "Top-p", "Decoding"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "context-windows-and-kv-cache",
    title: "Context Windows & KV Cache",
    summary:
      "Why context is expensive, how the KV cache grows, and the tricks that push context from 4K to 1M tokens.",
    tier: "l1-foundations",
    difficulty: "Advanced",
    topics: ["LLM Fundamentals", "Model Serving"],
    companies: ["Anthropic", "Google DeepMind", "NVIDIA"],
    tags: ["Context Window", "KV Cache", "Long Context", "Memory"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "hallucinations-and-limitations",
    title: "Hallucinations & LLM Limitations",
    summary:
      "Why LLMs make things up, how to measure it, and the system-level mitigations interviewers expect you to know.",
    tier: "l1-foundations",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "AI Evaluation"],
    companies: ["Anthropic", "OpenAI", "Microsoft"],
    tags: ["Hallucination", "Grounding", "Reliability"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "prompt-engineering-foundations",
    title: "Prompt Engineering Foundations",
    summary:
      "System vs user prompts, few-shot, chain-of-thought, and structured output — the reliable building blocks.",
    tier: "l1-foundations",
    difficulty: "Beginner",
    topics: ["Prompt Engineering", "LLM Fundamentals"],
    companies: ["OpenAI", "Anthropic", "Microsoft"],
    tags: ["Prompting", "Few-Shot", "Chain of Thought", "Structured Output"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "choosing-the-right-model",
    title: "Choosing the Right Model",
    summary:
      "Open vs closed, size vs latency vs cost, and how to pick a model (or a cascade) for a given workload.",
    tier: "l1-foundations",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "Model Serving"],
    companies: ["Databricks", "Microsoft", "Amazon"],
    tags: ["Model Selection", "Cost", "Latency", "Tradeoffs"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },

  // 🔴 Level 6 · AI System Design
  {
    slug: "design-chatgpt",
    title: "Design ChatGPT",
    summary:
      "Design a multi-turn conversational AI product — streaming responses, conversation memory, moderation, and scale to millions of users.",
    tier: "l6-ai-system-design",
    difficulty: "Advanced",
    topics: ["Model Serving", "Prompt Engineering", "AI Security"],
    companies: ["OpenAI", "Microsoft", "Anthropic", "Google DeepMind"],
    tags: ["Chat", "Streaming", "Conversation Memory", "Moderation", "Scale"],
    popularity: 99,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "design-ai-coding-assistant",
    title: "Design an AI Coding Assistant",
    summary:
      "Design a Copilot-style assistant — repo context, fill-in-the-middle completion, low latency, and privacy.",
    tier: "l6-ai-system-design",
    difficulty: "Advanced",
    topics: ["Model Serving", "RAG", "Prompt Engineering"],
    companies: ["Microsoft", "OpenAI", "Amazon"],
    tags: ["Copilot", "Code Completion", "FIM", "Latency", "Context"],
    popularity: 92,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-ai-customer-support",
    title: "Design an AI Customer Support System",
    summary:
      "Design an LLM support agent grounded in help-center docs with escalation, tools, and deflection metrics.",
    tier: "l6-ai-system-design",
    difficulty: "Intermediate",
    topics: ["RAG", "AI Agents", "AI Evaluation"],
    companies: ["Amazon", "Microsoft", "Anthropic"],
    tags: ["Support", "RAG", "Escalation", "Tools", "Deflection"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-ai-writing-assistant",
    title: "Design an AI Writing Assistant",
    summary:
      "Design a Grammarly/Notion-AI-style assistant — inline suggestions, tone control, and multi-tenant data isolation.",
    tier: "l6-ai-system-design",
    difficulty: "Intermediate",
    topics: ["Prompt Engineering", "Model Serving"],
    companies: ["Microsoft", "Google DeepMind", "OpenAI"],
    tags: ["Writing", "Suggestions", "Tone", "Multi-Tenant"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-multi-user-chat",
    title: "Design a Multi-User LLM Chat Platform",
    summary:
      "Design the backend for a team chat product with shared threads, per-user quotas, and provider fallback.",
    tier: "l6-ai-system-design",
    difficulty: "Advanced",
    topics: ["Model Serving", "AI Observability"],
    companies: ["OpenAI", "Microsoft", "Databricks"],
    tags: ["Multi-User", "Quotas", "Fallback", "Threads"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-answer-engine",
    title: "Design an AI Answer Engine",
    summary:
      "Design a Perplexity-style answer engine — live web retrieval, citation grounding, and streamed synthesis.",
    tier: "l6-ai-system-design",
    difficulty: "Advanced",
    topics: ["RAG", "AI Agents"],
    companies: ["Perplexity", "Google DeepMind", "Microsoft"],
    tags: ["Search", "Citations", "Web Retrieval", "Synthesis"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-content-moderation",
    title: "Design an LLM Content Moderation System",
    summary:
      "Design a real-time safety classifier pipeline — policy taxonomy, latency budget, and human review loop.",
    tier: "l6-ai-system-design",
    difficulty: "Intermediate",
    topics: ["AI Security", "AI Evaluation"],
    companies: ["Meta", "OpenAI", "Microsoft"],
    tags: ["Moderation", "Safety", "Classification", "Human Review"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-streaming-token-delivery",
    title: "Design Streaming Token Delivery",
    summary:
      "Design the transport for token-by-token responses — SSE vs WebSockets, backpressure, and cancellation.",
    tier: "l6-ai-system-design",
    difficulty: "Intermediate",
    topics: ["Model Serving"],
    companies: ["OpenAI", "Anthropic", "Amazon"],
    tags: ["Streaming", "SSE", "WebSockets", "Backpressure"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },

  // 🟣 Level 3 · Retrieval-Augmented Generation
  {
    slug: "design-rag-pipeline",
    title: "Design a Production RAG System",
    summary:
      "Design an end-to-end retrieval-augmented generation system — ingestion, chunking, embedding, hybrid retrieval, reranking, and grounded generation at scale.",
    tier: "l3-rag",
    difficulty: "Advanced",
    topics: ["RAG", "Vector Databases", "Embeddings"],
    companies: ["OpenAI", "Databricks", "Cohere", "Microsoft"],
    tags: ["RAG", "Chunking", "Hybrid Search", "Reranking", "Grounding"],
    popularity: 98,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "document-chunking-strategies",
    title: "Document Chunking Strategies",
    summary:
      "Fixed, recursive, semantic, and structure-aware chunking — how splitting decisions make or break retrieval quality.",
    tier: "l3-rag",
    difficulty: "Intermediate",
    topics: ["RAG", "Embeddings"],
    companies: ["Cohere", "Databricks", "Microsoft"],
    tags: ["Chunking", "Overlap", "Semantic Splitting"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "hybrid-search-for-rag",
    title: "Hybrid Search for RAG",
    summary:
      "Combine BM25 keyword search with dense vectors and fuse the results — the retrieval backbone of strong RAG.",
    tier: "l3-rag",
    difficulty: "Advanced",
    topics: ["RAG", "Vector Databases"],
    companies: ["Cohere", "Microsoft", "Databricks"],
    tags: ["Hybrid Search", "BM25", "Dense Retrieval", "RRF"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "reranking-in-rag",
    title: "Reranking in RAG Pipelines",
    summary:
      "Cross-encoder rerankers — why a second stage dramatically lifts precision, and how to keep it cheap.",
    tier: "l3-rag",
    difficulty: "Intermediate",
    topics: ["RAG", "AI Evaluation"],
    companies: ["Cohere", "OpenAI", "Google DeepMind"],
    tags: ["Reranking", "Cross-Encoder", "Precision"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "evaluating-rag-quality",
    title: "Evaluating RAG Quality",
    summary:
      "Retrieval and generation metrics — recall@k, faithfulness, answer relevance, and LLM-as-judge pipelines.",
    tier: "l3-rag",
    difficulty: "Advanced",
    topics: ["AI Evaluation", "RAG"],
    companies: ["Databricks", "Anthropic", "Microsoft"],
    tags: ["Evaluation", "Faithfulness", "Recall", "LLM-as-Judge"],
    popularity: 81,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "multimodal-rag",
    title: "Multimodal RAG",
    summary:
      "Retrieve over text, tables, and images — unified embeddings, layout parsing, and grounded multimodal answers.",
    tier: "l3-rag",
    difficulty: "Advanced",
    topics: ["RAG", "Embeddings"],
    companies: ["Google DeepMind", "OpenAI", "Cohere"],
    tags: ["Multimodal", "Images", "Tables", "Layout"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "agentic-rag",
    title: "Agentic RAG",
    summary:
      "Let the model decide when and what to retrieve — query planning, multi-hop retrieval, and self-correction.",
    tier: "l3-rag",
    difficulty: "Advanced",
    topics: ["RAG", "AI Agents"],
    companies: ["Anthropic", "OpenAI", "Perplexity"],
    tags: ["Agentic", "Multi-Hop", "Query Planning"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "rag-cost-and-caching",
    title: "Cost & Caching for RAG",
    summary:
      "Semantic caching, embedding reuse, and context trimming — how to cut RAG bills without hurting quality.",
    tier: "l3-rag",
    difficulty: "Intermediate",
    topics: ["RAG", "AI Observability"],
    companies: ["Databricks", "Amazon", "Microsoft"],
    tags: ["Cost", "Semantic Cache", "Context Trimming"],
    popularity: 75,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },

  // 🟦 Level 4 · Vector Databases & Search
  {
    slug: "design-vector-database",
    title: "Design a Vector Database",
    summary:
      "Design a vector database that indexes billions of embeddings for millisecond similarity search — ANN indexing, sharding, filtering, and persistence.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases", "Embeddings"],
    companies: ["Databricks", "NVIDIA", "Microsoft", "Cohere"],
    tags: ["Vector DB", "ANN", "HNSW", "Sharding", "Filtering"],
    popularity: 95,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "ann-algorithms",
    title: "Approximate Nearest Neighbor Algorithms",
    summary:
      "The ANN landscape — trees, LSH, graphs, and quantization — and the recall/latency/memory tradeoffs between them.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases"],
    companies: ["NVIDIA", "Google DeepMind", "Databricks"],
    tags: ["ANN", "LSH", "Recall", "Latency"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "hnsw-index-deep-dive",
    title: "HNSW Index Deep Dive",
    summary:
      "Hierarchical navigable small worlds — how the graph is built and searched, and how to tune ef and M.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases"],
    companies: ["NVIDIA", "Databricks", "Cohere"],
    tags: ["HNSW", "Graph Index", "ef", "M"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "ivf-and-product-quantization",
    title: "IVF & Product Quantization",
    summary:
      "Inverted-file indexing and PQ compression — the technique that makes billion-vector search fit in RAM.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases", "Embeddings"],
    companies: ["Meta", "NVIDIA", "Databricks"],
    tags: ["IVF", "Product Quantization", "Compression"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "storing-billions-of-embeddings",
    title: "Storing Billions of Embeddings",
    summary:
      "Memory vs disk (DiskANN), tiered storage, and the cost model behind large-scale vector storage.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases", "AI Infrastructure"],
    companies: ["Microsoft", "Amazon", "Databricks"],
    tags: ["DiskANN", "Tiered Storage", "Cost"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "vector-db-sharding-replication",
    title: "Sharding & Replication for Vector DBs",
    summary:
      "Partition billions of vectors across nodes, replicate for availability, and scatter-gather queries with low tail latency.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases", "AI Infrastructure"],
    companies: ["Databricks", "Amazon", "NVIDIA"],
    tags: ["Sharding", "Replication", "Scatter-Gather", "Tail Latency"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "filtered-vector-search",
    title: "Filtered Vector Search",
    summary:
      "Combine metadata predicates with similarity — pre-, post-, and single-stage filtering, and why it is surprisingly hard.",
    tier: "l4-vector-databases",
    difficulty: "Advanced",
    topics: ["Vector Databases"],
    companies: ["Microsoft", "Cohere", "Databricks"],
    tags: ["Metadata Filter", "Pre-Filter", "Post-Filter"],
    popularity: 70,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "choosing-an-embedding-model",
    title: "Choosing an Embedding Model",
    summary:
      "Dimensionality, domain fit, MTEB benchmarks, and cost — how to pick and evaluate an embedding model.",
    tier: "l4-vector-databases",
    difficulty: "Intermediate",
    topics: ["Embeddings", "AI Evaluation"],
    companies: ["Cohere", "OpenAI", "Databricks"],
    tags: ["Embeddings", "MTEB", "Dimensionality"],
    popularity: 71,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },

  // 🟠 Level 5 · AI Agents & Orchestration
  {
    slug: "design-ai-agent",
    title: "Design an AI Agent",
    summary:
      "Design a single tool-using agent — the reasoning loop, tool schema, memory, and error recovery.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Agents", "Prompt Engineering"],
    companies: ["Anthropic", "OpenAI", "Microsoft"],
    tags: ["Agent", "Tool Use", "Reasoning Loop", "Memory"],
    popularity: 90,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "tool-calling-and-function-calling",
    title: "Tool Calling & Function Calling",
    summary:
      "How models call functions — schema design, argument validation, parallel calls, and safe execution.",
    tier: "l5-agents",
    difficulty: "Intermediate",
    topics: ["AI Agents", "Prompt Engineering"],
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    tags: ["Function Calling", "Tools", "JSON Schema", "Validation"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "agent-memory-systems",
    title: "Agent Memory Systems",
    summary:
      "Short-term, long-term, and episodic memory — summarization, vector recall, and context management for agents.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Agents", "RAG"],
    companies: ["Anthropic", "OpenAI", "Microsoft"],
    tags: ["Memory", "Summarization", "Episodic", "Recall"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "react-and-planning-loops",
    title: "ReAct & Planning Loops",
    summary:
      "Reason-act-observe loops, plan-and-execute, and reflection — the control structures behind capable agents.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Agents"],
    companies: ["Google DeepMind", "Anthropic", "OpenAI"],
    tags: ["ReAct", "Planning", "Reflection"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-autonomous-task-agent",
    title: "Design an Autonomous Task Agent",
    summary:
      "Design a long-running agent that decomposes goals, runs tools, and checkpoints progress with human approval gates.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Agents", "AI Security"],
    companies: ["OpenAI", "Anthropic", "Amazon"],
    tags: ["Autonomous", "Task Decomposition", "Checkpointing", "Approval"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "agent-guardrails-and-safety",
    title: "Agent Guardrails & Safety",
    summary:
      "Sandboxing tools, permission scopes, and output validation — keeping autonomous agents from doing damage.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Security", "AI Agents"],
    companies: ["Anthropic", "Microsoft", "OpenAI"],
    tags: ["Guardrails", "Sandbox", "Permissions", "Validation"],
    popularity: 75,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-multi-agent-system",
    title: "Design a Multi-Agent System",
    summary:
      "Design an orchestrator-worker multi-agent system — role decomposition, shared state, and conflict resolution.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["Multi-Agent Systems", "AI Agents"],
    companies: ["Microsoft", "OpenAI", "Google DeepMind"],
    tags: ["Multi-Agent", "Orchestrator", "Shared State", "Roles"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-web-browsing-agent",
    title: "Design a Web-Browsing Agent",
    summary:
      "Design an agent that navigates real web pages — DOM grounding, action space, safety, and rate limiting.",
    tier: "l5-agents",
    difficulty: "Advanced",
    topics: ["AI Agents", "AI Security"],
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    tags: ["Browser", "DOM", "Actions", "Rate Limiting"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },

  // 🟩 Level 7 · Production AI — Model Serving & Inference
  {
    slug: "design-llm-inference-service",
    title: "Design an LLM Inference Service",
    summary:
      "Design a high-throughput inference service — request queue, batching, KV cache, GPU pooling, and autoscaling.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving", "AI Infrastructure"],
    companies: ["NVIDIA", "OpenAI", "Databricks", "Amazon"],
    tags: ["Inference", "Batching", "GPU", "Autoscaling", "Throughput"],
    popularity: 93,
    frequency: "Very High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "kv-cache-optimization",
    title: "KV Cache Optimization",
    summary:
      "PagedAttention, cache eviction, and prefix sharing — the memory tricks that multiply inference throughput.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving"],
    companies: ["NVIDIA", "OpenAI", "Anthropic"],
    tags: ["KV Cache", "PagedAttention", "Prefix Sharing"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "continuous-batching",
    title: "Continuous Batching",
    summary:
      "Iteration-level scheduling that keeps GPUs saturated — why it beats static batching for LLM serving.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving"],
    companies: ["NVIDIA", "Databricks", "OpenAI"],
    tags: ["Continuous Batching", "Scheduling", "Throughput"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "speculative-decoding",
    title: "Speculative Decoding",
    summary:
      "Draft-and-verify decoding — use a small model to propose tokens a big model checks, cutting latency.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving"],
    companies: ["NVIDIA", "Google DeepMind", "Anthropic"],
    tags: ["Speculative Decoding", "Draft Model", "Latency"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "gpu-scheduling-and-autoscaling",
    title: "GPU Scheduling & Autoscaling",
    summary:
      "Bin-packing GPUs, cold-start mitigation, and scaling on queue depth — the ops side of inference at scale.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving", "AI Infrastructure"],
    companies: ["Amazon", "NVIDIA", "Databricks"],
    tags: ["GPU", "Autoscaling", "Cold Start", "Bin Packing"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "quantization-for-inference",
    title: "Quantization for Inference",
    summary:
      "INT8, FP8, and 4-bit weights — how quantization shrinks models and the accuracy tradeoffs to defend.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving", "Fine-Tuning"],
    companies: ["NVIDIA", "Meta", "Databricks"],
    tags: ["Quantization", "INT8", "FP8", "GPTQ"],
    popularity: 75,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "multi-model-and-lora-serving",
    title: "Multi-Model & LoRA Serving",
    summary:
      "Serve hundreds of fine-tuned adapters from one base model — LoRA swapping, routing, and memory sharing.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["Model Serving", "Fine-Tuning"],
    companies: ["Databricks", "NVIDIA", "Amazon"],
    tags: ["LoRA", "Multi-Model", "Adapters", "Routing"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-llm-gateway",
    title: "Design an LLM Gateway",
    summary:
      "Design a unified gateway across providers — routing, rate limits, key management, caching, and fallbacks.",
    tier: "l7-production-ai",
    difficulty: "Intermediate",
    topics: ["Model Serving", "AI Observability"],
    companies: ["Microsoft", "Amazon", "Databricks"],
    tags: ["Gateway", "Routing", "Rate Limits", "Fallback"],
    popularity: 79,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },

  // 🟤 Level 8 · Advanced AI — Infrastructure & Training
  {
    slug: "design-training-platform",
    title: "Design a Distributed Training Platform",
    summary:
      "Design a platform to train large models — job scheduling, data/model/pipeline parallelism, and checkpointing.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Infrastructure", "Fine-Tuning"],
    companies: ["NVIDIA", "Google DeepMind", "Meta", "Databricks"],
    tags: ["Training", "Parallelism", "Scheduling", "Checkpointing"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-llm-data-pipeline",
    title: "Design an LLM Data Pipeline",
    summary:
      "Design a pretraining/fine-tuning data pipeline — crawling, dedup, filtering, tokenization, and lineage.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Infrastructure", "Fine-Tuning"],
    companies: ["Meta", "Databricks", "Google DeepMind"],
    tags: ["Data Pipeline", "Dedup", "Filtering", "Lineage"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "distributed-training-strategies",
    title: "Distributed Training Strategies",
    summary:
      "Data, tensor, pipeline, and FSDP parallelism — how huge models are split across thousands of GPUs.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Infrastructure"],
    companies: ["NVIDIA", "Meta", "Google DeepMind"],
    tags: ["FSDP", "Tensor Parallel", "Pipeline Parallel", "ZeRO"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-feature-store",
    title: "Design a Feature Store",
    summary:
      "Design online/offline feature storage — consistency, point-in-time correctness, and low-latency serving.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Infrastructure"],
    companies: ["Databricks", "Amazon", "Meta"],
    tags: ["Feature Store", "Online/Offline", "Point-in-Time"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "experiment-tracking-and-registry",
    title: "Experiment Tracking & Model Registry",
    summary:
      "Track runs, version datasets and models, and gate promotions — the reproducibility backbone of ML.",
    tier: "l8-advanced-ai",
    difficulty: "Intermediate",
    topics: ["AI Infrastructure", "AI Observability"],
    companies: ["Databricks", "Microsoft", "Amazon"],
    tags: ["Experiment Tracking", "Model Registry", "Versioning"],
    popularity: 70,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "design-fine-tuning-pipeline",
    title: "Design a Fine-Tuning Pipeline",
    summary:
      "Design a pipeline for supervised fine-tuning and LoRA — data curation, training, eval gates, and rollout.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["Fine-Tuning", "AI Infrastructure"],
    companies: ["Databricks", "OpenAI", "Meta"],
    tags: ["Fine-Tuning", "LoRA", "SFT", "Eval Gates"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-rlhf-pipeline",
    title: "Design an RLHF Pipeline",
    summary:
      "Design reinforcement learning from human feedback — preference data, reward modeling, and PPO/DPO training.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["Fine-Tuning", "AI Infrastructure"],
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    tags: ["RLHF", "Reward Model", "PPO", "DPO", "Preferences"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "gpu-cluster-management",
    title: "GPU Cluster Management",
    summary:
      "Fair-share scheduling, gang scheduling, and fault recovery for large GPU clusters running mixed workloads.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Infrastructure"],
    companies: ["NVIDIA", "Meta", "Amazon"],
    tags: ["GPU Cluster", "Gang Scheduling", "Fault Recovery"],
    popularity: 71,
    frequency: "Low",
    estimatedMinutes: 45,
    status: "coming-soon",
  },

  // 🟤 Level 8 · Advanced AI — Safety, Security & Governance
  {
    slug: "defending-against-prompt-injection",
    title: "Defending Against Prompt Injection",
    summary:
      "Direct and indirect prompt injection — the threat model, and layered defenses interviewers want to hear.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Security", "AI Agents"],
    companies: ["Anthropic", "Microsoft", "OpenAI"],
    tags: ["Prompt Injection", "Threat Model", "Defense in Depth"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-llm-guardrail-system",
    title: "Design an LLM Guardrail System",
    summary:
      "Design input/output guardrails — policy checks, schema validation, PII filters, and safe-completion routing.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Security", "AI Evaluation"],
    companies: ["Microsoft", "OpenAI", "Anthropic"],
    tags: ["Guardrails", "Policy", "PII", "Validation"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "pii-detection-and-redaction",
    title: "PII Detection & Redaction",
    summary:
      "Detect and redact sensitive data before it reaches a model — classifiers, tokenization, and reversible masking.",
    tier: "l8-advanced-ai",
    difficulty: "Intermediate",
    topics: ["AI Security"],
    companies: ["Microsoft", "Amazon", "Databricks"],
    tags: ["PII", "Redaction", "Masking", "Compliance"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "hallucination-mitigation",
    title: "Hallucination Mitigation",
    summary:
      "System-level mitigations — grounding, citations, self-consistency, and abstention — with measurable guarantees.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Evaluation", "RAG"],
    companies: ["Anthropic", "Google DeepMind", "OpenAI"],
    tags: ["Hallucination", "Grounding", "Abstention", "Citations"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "design-content-safety-pipeline",
    title: "Design an AI Content Safety Pipeline",
    summary:
      "Design a safety pipeline for generated text and images — classifiers, thresholds, appeals, and audit trails.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Security", "AI Evaluation"],
    companies: ["Meta", "Microsoft", "OpenAI"],
    tags: ["Content Safety", "Classifiers", "Appeals", "Audit"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "model-access-control-and-rate-limiting",
    title: "Model Access Control & Rate Limiting",
    summary:
      "Per-tenant quotas, token budgets, and abuse detection — protecting expensive model endpoints.",
    tier: "l8-advanced-ai",
    difficulty: "Intermediate",
    topics: ["AI Security", "Model Serving"],
    companies: ["OpenAI", "Amazon", "Microsoft"],
    tags: ["Access Control", "Rate Limiting", "Quotas", "Abuse"],
    popularity: 71,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "ai-governance-and-audit-logging",
    title: "AI Governance & Audit Logging",
    summary:
      "Model cards, data lineage, approval workflows, and immutable audit logs — the compliance layer for AI.",
    tier: "l8-advanced-ai",
    difficulty: "Intermediate",
    topics: ["AI Security", "AI Observability"],
    companies: ["Microsoft", "Databricks", "Amazon"],
    tags: ["Governance", "Audit", "Lineage", "Compliance"],
    popularity: 68,
    frequency: "Low",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "jailbreak-detection",
    title: "Jailbreak Detection",
    summary:
      "Detect adversarial prompts that bypass safety — classifiers, canaries, and red-teaming feedback loops.",
    tier: "l8-advanced-ai",
    difficulty: "Advanced",
    topics: ["AI Security", "AI Evaluation"],
    companies: ["Anthropic", "OpenAI", "Google DeepMind"],
    tags: ["Jailbreak", "Adversarial", "Red Team"],
    popularity: 70,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },

  // 🟩 Level 7 · Production AI — LLMOps
  {
    slug: "design-llm-observability",
    title: "Design LLM Observability",
    summary:
      "Design tracing for LLM apps — spans across retrieval and generation, token/cost metrics, and quality signals.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["AI Observability", "AI Evaluation"],
    companies: ["Databricks", "Microsoft", "Amazon"],
    tags: ["Observability", "Tracing", "Spans", "Cost Metrics"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-llm-evaluation-platform",
    title: "Design an LLM Evaluation Platform",
    summary:
      "Design an offline+online eval platform — golden sets, LLM-as-judge, human review, and regression gates.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["AI Evaluation", "AI Observability"],
    companies: ["OpenAI", "Databricks", "Anthropic"],
    tags: ["Evaluation", "Golden Set", "LLM-as-Judge", "Regression"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "ab-testing-llm-features",
    title: "A/B Testing LLM Features",
    summary:
      "Experiment on prompts and models — metrics, guardrail metrics, and why LLM experiments are noisy.",
    tier: "l7-production-ai",
    difficulty: "Intermediate",
    topics: ["AI Evaluation", "AI Observability"],
    companies: ["Meta", "Microsoft", "Amazon"],
    tags: ["A/B Testing", "Experiments", "Metrics"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "llm-cost-optimization",
    title: "LLM Cost Optimization",
    summary:
      "Model cascades, caching, batching, and prompt compression — a systematic playbook for cutting inference cost.",
    tier: "l7-production-ai",
    difficulty: "Intermediate",
    topics: ["AI Observability", "Model Serving"],
    companies: ["Databricks", "Amazon", "Microsoft"],
    tags: ["Cost", "Cascade", "Caching", "Compression"],
    popularity: 81,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "design-prompt-management-system",
    title: "Design a Prompt Management System",
    summary:
      "Design versioned prompt storage — templates, variables, staged rollout, and rollback tied to evals.",
    tier: "l7-production-ai",
    difficulty: "Intermediate",
    topics: ["Prompt Engineering", "AI Observability"],
    companies: ["Microsoft", "Databricks", "OpenAI"],
    tags: ["Prompt Management", "Versioning", "Rollout"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "design-semantic-cache",
    title: "Design a Semantic Cache",
    summary:
      "Design an embedding-based cache for LLM responses — similarity thresholds, staleness, and correctness risks.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["AI Observability", "Vector Databases"],
    companies: ["Databricks", "Amazon", "Cohere"],
    tags: ["Semantic Cache", "Similarity", "Staleness", "Cost"],
    popularity: 75,
    frequency: "Medium",
    estimatedMinutes: 45,
    status: "coming-soon",
  },
  {
    slug: "model-monitoring-and-drift",
    title: "Model Monitoring & Drift Detection",
    summary:
      "Detect data and quality drift in production — distribution monitors, canaries, and automated rollback.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["AI Observability", "AI Evaluation"],
    companies: ["Databricks", "Amazon", "Microsoft"],
    tags: ["Monitoring", "Drift", "Canary", "Rollback"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "design-llmops-pipeline",
    title: "Design an LLMOps CI/CD Pipeline",
    summary:
      "Design CI/CD for prompts, models, and RAG indexes — eval gates, staged rollout, and automated rollback.",
    tier: "l7-production-ai",
    difficulty: "Advanced",
    topics: ["AI Observability", "AI Infrastructure"],
    companies: ["Databricks", "Microsoft", "Amazon"],
    tags: ["LLMOps", "CI/CD", "Eval Gates", "Rollout"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },

  // ⭐ Level 9 · Interview Preparation
  {
    slug: "design-ai-recommendations",
    title: "Design AI-Powered Recommendations",
    summary:
      "Design a recommendation system with embeddings and LLM re-ranking — candidate generation, ranking, and freshness.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["Embeddings", "Vector Databases", "Model Serving"],
    companies: ["Meta", "Amazon", "Google DeepMind"],
    tags: ["Recommendations", "Embeddings", "Ranking", "Freshness"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-image-generation-service",
    title: "Design an Image Generation Service",
    summary:
      "Design a text-to-image service — diffusion inference, GPU queueing, safety filters, and asset storage.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["Model Serving", "AI Infrastructure", "AI Security"],
    companies: ["OpenAI", "NVIDIA", "Google DeepMind"],
    tags: ["Diffusion", "Text-to-Image", "GPU Queue", "Safety"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-voice-assistant",
    title: "Design a Voice Assistant",
    summary:
      "Design a real-time voice assistant — streaming ASR, LLM reasoning, TTS, and end-to-end latency budgets.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["Model Serving", "AI Agents"],
    companies: ["Amazon", "Google DeepMind", "OpenAI"],
    tags: ["Voice", "ASR", "TTS", "Latency", "Streaming"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-ai-code-review",
    title: "Design an AI Code Review System",
    summary:
      "Design an AI reviewer for pull requests — repo context, diff analysis, false-positive control, and CI integration.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["RAG", "AI Agents", "AI Evaluation"],
    companies: ["Microsoft", "OpenAI", "Amazon"],
    tags: ["Code Review", "Diff", "Repo Context", "CI"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-ai-fraud-detection",
    title: "Design an AI Fraud Detection System",
    summary:
      "Design a hybrid ML + LLM fraud system — features, real-time scoring, explanations, and analyst tooling.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["AI Infrastructure", "Model Serving"],
    companies: ["Amazon", "Microsoft", "Meta"],
    tags: ["Fraud", "Real-Time Scoring", "Explanations"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "design-ai-meeting-notetaker",
    title: "Design an AI Meeting Notetaker",
    summary:
      "Design a meeting assistant — diarized transcription, summarization, action items, and searchable history.",
    tier: "l9-interview-prep",
    difficulty: "Intermediate",
    topics: ["Model Serving", "RAG"],
    companies: ["Microsoft", "Google DeepMind", "Amazon"],
    tags: ["Transcription", "Diarization", "Summarization", "Search"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-realtime-translation",
    title: "Design Real-Time AI Translation",
    summary:
      "Design streaming speech-to-speech translation — incremental decoding, latency, and quality/latency tradeoffs.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["Model Serving"],
    companies: ["Meta", "Google DeepMind", "Microsoft"],
    tags: ["Translation", "Streaming", "Speech-to-Speech", "Latency"],
    popularity: 71,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-ai-tutor",
    title: "Design an AI Tutor",
    summary:
      "Design a personalized tutoring system — knowledge modeling, adaptive prompts, grounding, and safety for minors.",
    tier: "l9-interview-prep",
    difficulty: "Intermediate",
    topics: ["RAG", "Prompt Engineering", "AI Security"],
    companies: ["Microsoft", "OpenAI", "Google DeepMind"],
    tags: ["Tutoring", "Personalization", "Knowledge Model", "Safety"],
    popularity: 70,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "design-personalization-engine",
    title: "Design an LLM Personalization Engine",
    summary:
      "Design a system that personalizes LLM outputs per user — profile memory, retrieval, and privacy controls.",
    tier: "l9-interview-prep",
    difficulty: "Advanced",
    topics: ["RAG", "Embeddings", "AI Security"],
    companies: ["Meta", "Amazon", "Microsoft"],
    tags: ["Personalization", "Profile Memory", "Privacy"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  // 🔵 Level 2 · Working with LLMs
  {
    slug: "calling-the-openai-api",
    title: "Calling the OpenAI API",
    summary:
      "The Chat Completions and Responses APIs end-to-end — messages, roles, parameters, token accounting, and error handling.",
    tier: "l2-working-with-llms",
    difficulty: "Beginner",
    topics: ["LLM Fundamentals", "Prompt Engineering"],
    companies: ["OpenAI", "Microsoft"],
    tags: ["OpenAI", "Chat Completions", "SDK", "API"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "calling-the-anthropic-api",
    title: "Calling the Anthropic (Claude) API",
    summary:
      "Claude's Messages API — system prompts, content blocks, stop reasons, and prompt-caching for cheaper long context.",
    tier: "l2-working-with-llms",
    difficulty: "Beginner",
    topics: ["LLM Fundamentals", "Prompt Engineering"],
    companies: ["Anthropic"],
    tags: ["Anthropic", "Claude", "Messages API", "Prompt Caching"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "calling-the-gemini-api",
    title: "Calling the Google Gemini API",
    summary:
      "Gemini's generateContent API — multimodal inputs, safety settings, and grounding with Google Search.",
    tier: "l2-working-with-llms",
    difficulty: "Beginner",
    topics: ["LLM Fundamentals", "Prompt Engineering"],
    companies: ["Google DeepMind"],
    tags: ["Gemini", "Multimodal", "generateContent", "Grounding"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "azure-openai-service",
    title: "Azure OpenAI Service",
    summary:
      "Running OpenAI models on Azure — deployments, regional data residency, private networking, and enterprise auth.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "AI Infrastructure"],
    companies: ["Microsoft", "OpenAI"],
    tags: ["Azure", "Deployments", "Enterprise", "Networking"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "structured-outputs",
    title: "Structured Outputs",
    summary:
      "Guaranteeing schema-valid responses — JSON Schema, response formats, and refusal handling for reliable pipelines.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["Prompt Engineering", "AI Evaluation"],
    companies: ["OpenAI", "Anthropic"],
    tags: ["Structured Outputs", "JSON Schema", "Validation"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "json-mode",
    title: "JSON Mode",
    summary:
      "Forcing valid JSON from any model — when to use JSON mode vs structured outputs, and how to recover from partial output.",
    tier: "l2-working-with-llms",
    difficulty: "Beginner",
    topics: ["Prompt Engineering"],
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    tags: ["JSON Mode", "Parsing", "Reliability"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 30,
    status: "coming-soon",
  },
  {
    slug: "streaming-responses",
    title: "Streaming Responses",
    summary:
      "Server-sent events and token streaming — delta parsing, backpressure, cancellation, and rendering partial tokens in the UI.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "Model Serving"],
    companies: ["OpenAI", "Anthropic"],
    tags: ["Streaming", "SSE", "Tokens", "UX"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "function-and-tool-calling",
    title: "Function & Tool Calling",
    summary:
      "Letting the model call your code — tool schemas, argument validation, parallel tool calls, and the tool-result loop.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["AI Agents", "Prompt Engineering"],
    companies: ["OpenAI", "Anthropic", "Google DeepMind"],
    tags: ["Tool Calling", "Function Calling", "Schemas", "Agents"],
    popularity: 89,
    frequency: "Very High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "model-context-protocol",
    title: "Model Context Protocol (MCP)",
    summary:
      "The open standard for connecting models to tools and data — servers, resources, tools, and transport, and why it matters.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["AI Agents", "AI Infrastructure"],
    companies: ["Anthropic", "OpenAI"],
    tags: ["MCP", "Tools", "Integration", "Standard"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "coming-soon",
  },
  {
    slug: "prompt-templates-and-chaining",
    title: "Prompt Templates & Chaining",
    summary:
      "Reusable, versioned prompts and multi-step chains — variables, few-shot templates, and composing calls into workflows.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["Prompt Engineering"],
    companies: ["OpenAI", "Databricks"],
    tags: ["Prompt Templates", "Chaining", "Versioning", "Few-Shot"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 35,
    status: "coming-soon",
  },
  {
    slug: "output-guardrails-and-validation",
    title: "Output Guardrails & Validation",
    summary:
      "Keeping model output safe and correct — content filters, schema validation, retries, and fallbacks before you trust a response.",
    tier: "l2-working-with-llms",
    difficulty: "Intermediate",
    topics: ["AI Security", "AI Evaluation"],
    companies: ["OpenAI", "Anthropic", "Microsoft"],
    tags: ["Guardrails", "Validation", "Safety", "Retries"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 40,
    status: "coming-soon",
  },

  // 🚀 Level 10 · Hands-On Projects
  {
    slug: "build-chatgpt-from-scratch",
    title: "Build ChatGPT from Scratch",
    summary:
      "A capstone build of a streaming chat app — conversation state, streaming responses, message history, and persistence.",
    tier: "l10-projects",
    difficulty: "Intermediate",
    topics: ["LLM Fundamentals", "Model Serving"],
    companies: ["OpenAI"],
    tags: ["Project", "Chat", "Streaming", "Capstone"],
    popularity: 86,
    frequency: "Medium",
    estimatedMinutes: 90,
    status: "coming-soon",
  },
  {
    slug: "build-an-ai-coding-copilot",
    title: "Build an AI Coding Copilot",
    summary:
      "A capstone build of an inline code assistant — repo context, fill-in-the-middle, tool calling, and diff application.",
    tier: "l10-projects",
    difficulty: "Advanced",
    topics: ["RAG", "AI Agents"],
    companies: ["Microsoft", "OpenAI"],
    tags: ["Project", "Copilot", "Code", "Capstone"],
    popularity: 84,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-a-rag-system",
    title: "Build a RAG System",
    summary:
      "A capstone build of an end-to-end RAG app — ingestion, chunking, embeddings, a vector store, retrieval, and grounded answers.",
    tier: "l10-projects",
    difficulty: "Intermediate",
    topics: ["RAG", "Vector Databases", "Embeddings"],
    companies: ["Cohere", "Databricks"],
    tags: ["Project", "RAG", "Retrieval", "Capstone"],
    popularity: 85,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-an-ai-agent",
    title: "Build an AI Agent",
    summary:
      "A capstone build of a tool-using agent — planning loop, tool execution, memory, and guardrails against runaway loops.",
    tier: "l10-projects",
    difficulty: "Advanced",
    topics: ["AI Agents", "Multi-Agent Systems"],
    companies: ["Anthropic", "OpenAI"],
    tags: ["Project", "Agent", "Tools", "Capstone"],
    popularity: 83,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-an-ai-coding-assistant",
    title: "Build an AI Coding Assistant",
    summary:
      "A capstone build of a chat-based coding assistant — codebase indexing, retrieval over source, and multi-file edits.",
    tier: "l10-projects",
    difficulty: "Advanced",
    topics: ["RAG", "AI Agents", "Vector Databases"],
    companies: ["Microsoft", "OpenAI"],
    tags: ["Project", "Coding Assistant", "Codebase", "Capstone"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-an-ai-search-engine",
    title: "Build an AI Search Engine",
    summary:
      "A capstone build of an answer engine — query understanding, retrieval, reranking, cited synthesis, and follow-ups.",
    tier: "l10-projects",
    difficulty: "Advanced",
    topics: ["RAG", "Vector Databases", "AI Evaluation"],
    companies: ["Perplexity", "OpenAI"],
    tags: ["Project", "Search", "Answer Engine", "Capstone"],
    popularity: 82,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-an-ai-workflow-platform",
    title: "Build an AI Workflow Platform",
    summary:
      "A capstone build of a node-based workflow runner — chaining prompts and tools, branching, retries, and observability.",
    tier: "l10-projects",
    difficulty: "Advanced",
    topics: ["AI Agents", "AI Observability", "AI Infrastructure"],
    companies: ["Databricks", "Microsoft"],
    tags: ["Project", "Workflow", "Orchestration", "Capstone"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 120,
    status: "coming-soon",
  },
  {
    slug: "build-a-document-chat-app",
    title: "Build a Document Chat App",
    summary:
      "A capstone build of chat-with-your-PDF — upload, parsing, chunking, retrieval, and grounded answers with citations.",
    tier: "l10-projects",
    difficulty: "Intermediate",
    topics: ["RAG", "Vector Databases", "Embeddings"],
    companies: ["Cohere", "OpenAI"],
    tags: ["Project", "Document Chat", "PDF", "Capstone"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 90,
    status: "coming-soon",
  },
];

/** The full lesson catalog, with `addedOrder` derived (earlier = newer). */
export const GENAI_CATALOG: GenAILessonMeta[] = RAW_CATALOG.map((q, i) => ({
  ...q,
  addedOrder: RAW_CATALOG.length - i,
}));
