import type { LLDProblemContent } from "../types";

export const aiChatPlatform: LLDProblemContent = {
  slug: "ai-chat-platform",

  statementMD: [
    "Design the low-level object model for a **ChatGPT-style AI chat platform**.",
    "Users create conversations, send messages, receive streamed assistant tokens,",
    "switch between model providers such as OpenAI, Anthropic, and a local model,",
    "and allow the assistant to call registered tools when the model asks for",
    "external data or actions.",
    "",
    "The focus is the **LLD boundary**: conversation/message ownership, a provider",
    "interface that hides vendor APIs, streaming delivery through observers,",
    "context-window trimming, and a safe dispatch path for function calls.",
  ].join("\n"),

  businessContextMD: [
    "AI chat products need to move quickly across providers because cost, quality,",
    "latency, and model availability change constantly. A poor design leaks vendor",
    "request shapes into the service layer and makes every streaming or tool-calling",
    "change risky. A strong LLD keeps the chat domain stable while adapters absorb",
    "provider differences and observers make token streaming independent of the UI.",
  ].join("\n"),

  functionalRequirements: [
    "Create and maintain conversations with ordered system, user, assistant, and tool messages.",
    "Send a user message and stream the assistant response token by token.",
    "Support multiple model providers behind one **ModelProvider** abstraction.",
    "Allow provider-specific adapters for OpenAI, Anthropic, and local inference.",
    "Trim conversation history to a configurable context window before each model call.",
    "Register named tools and dispatch function calls requested by a provider.",
    "Broadcast streaming events to request-scoped and conversation-level observers.",
    "Persist the final assistant message after streaming completes successfully.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Provider isolation",
      detailMD:
        "Chat orchestration must not depend on OpenAI, Anthropic, or local request formats. Provider changes stay inside adapters.",
    },
    {
      label: "Low-latency streaming",
      detailMD:
        "The first token should reach observers as soon as the provider emits it; the service must not wait for the full answer.",
    },
    {
      label: "Context safety",
      detailMD:
        "Every provider call uses a bounded context window so old messages cannot blow past token limits.",
    },
    {
      label: "Tool-call containment",
      detailMD:
        "Tools are registered by name and invoked through a narrow dispatch interface; provider adapters never call arbitrary application methods.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New providers, tools, observers, and memory policies should be additive changes rather than edits to the chat flow.",
    },
  ],

  requirementClarification: [
    {
      question: "Are we designing the full distributed backend?",
      answerMD:
        "No. Keep the base design in-memory and class-focused. Persistence, queues, auth, billing, and horizontal scaling are production extensions.",
    },
    {
      question: "Do model providers return identical response shapes?",
      answerMD:
        "No. That is the reason for adapters. The service only sees **ModelProvider.streamChat** and **ToolCallHandler.call**.",
    },
    {
      question: "How accurate does token counting need to be?",
      answerMD:
        "For the interview model use a simple estimate on **Message**. In production, swap in a tokenizer-aware context policy.",
    },
    {
      question: "Can tools be called while streaming?",
      answerMD:
        "Yes. The provider adapter may request a tool through the handler, receive a string result, and continue emitting tokens.",
    },
    {
      question: "Do observers represent WebSockets, SSE, logs, or tests?",
      answerMD:
        "All of them. **StreamObserver** is intentionally transport-neutral; UI delivery is a boundary adapter outside this core model.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class ChatService {",
    "        -ModelProvider provider",
    "        -Conversation conversation",
    "        -Map~String,ChatTool~ tools",
    "        -List~StreamObserver~ observers",
    "        +create(String,int) ChatService",
    "        +registerTool(String,ChatTool) void",
    "        +addObserver(StreamObserver) void",
    "        +sendUserMessage(String,StreamObserver) void",
    "        +call(String,Map) String",
    "    }",
    "    class Conversation {",
    "        -String id",
    "        -List~Message~ messages",
    "        -int maxContextTokens",
    "        +add(Message) void",
    "        +messages() List~Message~",
    "        +contextWindow() List~Message~",
    "    }",
    "    class Message {",
    "        -Role role",
    "        -String content",
    "        -String toolName",
    "        -Instant createdAt",
    "        +estimatedTokens() int",
    "        +toPromptLine() String",
    "    }",
    "    class ModelProvider {",
    "        <<interface>>",
    "        +name() String",
    "        +streamChat(List,ToolCallHandler,StreamObserver) void",
    "        +create(String) ModelProvider",
    "    }",
    "    class OpenAiProvider",
    "    class AnthropicProvider",
    "    class LocalProvider",
    "    class StreamObserver {",
    "        <<interface>>",
    "        +onToken(String) void",
    "        +onComplete(Message) void",
    "        +onError(Throwable) void",
    "    }",
    "    class ChatTool {",
    "        <<interface>>",
    "        +execute(Map) String",
    "    }",
    "    ChatService o-- Conversation",
    "    Conversation o-- Message",
    "    ChatService ..> ModelProvider",
    "    ChatService ..> StreamObserver",
    "    ChatService ..> ChatTool",
    "    ModelProvider <|.. OpenAiProvider",
    "    ModelProvider <|.. AnthropicProvider",
    "    ModelProvider <|.. LocalProvider",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service owns conversation state and tool dispatch; provider adapters implement the strategy interface; observers receive streaming events without knowing which vendor produced them.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Service as ChatService",
    "    participant Conv as Conversation",
    "    participant Provider as ModelProvider",
    "    participant Tools as ChatTool",
    "    participant Observer as StreamObserver",
    "    User->>Service: sendUserMessage(text, observer)",
    "    Service->>Conv: add(user message)",
    "    Service->>Conv: contextWindow()",
    "    Conv-->>Service: bounded messages",
    "    Service->>Provider: streamChat(context, handler, observer)",
    "    Provider->>Service: call(toolName, args)",
    "    Service->>Tools: execute(args)",
    "    Tools-->>Service: result",
    "    Service-->>Provider: tool result",
    "    loop token stream",
    "        Provider->>Observer: onToken(token)",
    "    end",
    "    Provider->>Observer: onComplete(message)",
    "    Service->>Conv: add(assistant message)",
    "    Service-->>User: streamed answer",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The provider can request tools during generation, but all application access flows through ChatService; streaming tokens are pushed immediately to observers.",

  entities: [
    {
      name: "Conversation",
      responsibilityMD:
        "Aggregate for ordered chat history. It owns messages and returns a bounded context window for provider calls.",
      attributes: ["id", "messages", "maxContextTokens"],
    },
    {
      name: "Message",
      responsibilityMD:
        "Immutable chat item with a role, content, optional tool name, timestamp, and rough token estimate.",
      attributes: ["role", "content", "toolName", "createdAt"],
    },
    {
      name: "ModelProvider",
      responsibilityMD:
        "Strategy interface for model execution. It hides provider choice behind **streamChat** and exposes a factory method for demos and tests.",
      attributes: ["name", "streamChat", "create"],
    },
    {
      name: "OpenAiProvider",
      responsibilityMD:
        "Adapter from the platform model interface to an OpenAI-shaped client. It translates context and streams normalized tokens.",
      attributes: ["OpenAiClient"],
    },
    {
      name: "AnthropicProvider",
      responsibilityMD:
        "Adapter from the platform model interface to an Anthropic-shaped client, including its own prompt composition.",
      attributes: ["AnthropicClient"],
    },
    {
      name: "LocalProvider",
      responsibilityMD:
        "In-process provider strategy used for offline development, tests, and low-cost fallback behavior.",
      attributes: ["name", "streamChat"],
    },
    {
      name: "StreamObserver",
      responsibilityMD:
        "Observer contract for token, completion, and error events. WebSocket, SSE, logging, and tests can all implement it.",
      attributes: ["onToken", "onComplete", "onError"],
    },
    {
      name: "ChatService",
      responsibilityMD:
        "Facade-like orchestrator for the use case. It appends user messages, builds context, invokes the provider, dispatches tools, broadcasts tokens, and stores the final answer.",
      attributes: ["provider", "conversation", "tools", "observers"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**ModelProvider** is the strategy. **ChatService** can run against OpenAI, Anthropic, or local inference without branching on provider type.",
    },
    {
      name: "Adapter",
      whyMD:
        "**OpenAiProvider** and **AnthropicProvider** translate vendor-specific client behavior into the common **ModelProvider** contract.",
    },
    {
      name: "Observer",
      whyMD:
        "**StreamObserver** decouples token production from delivery. A CLI, browser stream, audit logger, or test spy can subscribe to the same events.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**ModelProvider.create** and **ChatService.create** centralize provider construction so callers ask for a named provider instead of knowing concrete classes.",
    },
  ],

  designSteps: [
    {
      title: "Represent the conversation as an ordered aggregate",
      detailMD:
        "Keep history inside **Conversation** and make **Message** immutable. Roles let the same list hold system prompts, user text, assistant output, and tool results.",
      code: [
        "public final class Message {",
        "    public enum Role { SYSTEM, USER, ASSISTANT, TOOL }",
        "    private final Role role;",
        "    private final String content;",
        "    public int estimatedTokens() {",
        "        return Math.max(1, content.length() / 4);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Build a bounded context window before every call",
      detailMD:
        "A chat platform cannot send unlimited history. Walk backward through messages until the token budget is reached, while preserving message order.",
      code: [
        "public synchronized List<Message> contextWindow() {",
        "    List<Message> selected = new ArrayList<>();",
        "    int used = 0;",
        "    for (int i = messages.size() - 1; i >= 0; i--) {",
        "        int cost = messages.get(i).estimatedTokens();",
        "        if (!selected.isEmpty() && used + cost > maxContextTokens) break;",
        "        selected.add(0, messages.get(i));",
        "        used += cost;",
        "    }",
        "    return Collections.unmodifiableList(selected);",
        "}",
      ].join("\n"),
    },
    {
      title: "Make provider choice a strategy",
      detailMD:
        "The service depends on **ModelProvider**, not on vendor SDK classes. Adapters handle prompt formatting, vendor clients, and response normalization.",
      code: [
        "public interface ModelProvider {",
        "    String name();",
        "    void streamChat(List<Message> context,",
        "                    ToolCallHandler tools,",
        "                    StreamObserver observer);",
        "}",
      ].join("\n"),
    },
    {
      title: "Create providers through a factory method",
      detailMD:
        "Central construction keeps command-line demos, tests, and dependency wiring from scattering provider-specific constructors.",
      code: [
        "public static ModelProvider create(String providerName) {",
        "    switch (providerName.toLowerCase(Locale.ROOT)) {",
        "        case \"openai\": return new OpenAiProvider(new OpenAiProvider.OpenAiClient());",
        "        case \"anthropic\": return new AnthropicProvider(new AnthropicProvider.AnthropicClient());",
        "        case \"local\": return new LocalProvider();",
        "        default: throw new IllegalArgumentException(\"Unknown provider\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Stream tokens through observers",
      detailMD:
        "Providers push each token to **StreamObserver.onToken**. **ChatService** wraps observers so it can multicast events and persist the final assistant message.",
    },
    {
      title: "Dispatch tool calls through the service",
      detailMD:
        "Adapters ask **ToolCallHandler.call** for named functions. The service looks up registered **ChatTool** instances, executes them with validated arguments, records the tool result, and returns plain text to the provider.",
    },
    {
      title: "Keep provider adapters thin",
      detailMD:
        "**OpenAiProvider** and **AnthropicProvider** should translate data and stream normalized tokens, not own conversation memory, business rules, or tool registration.",
    },
  ],

  implementation: [
    {
      filename: "Message.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "",
        "public final class Message {",
        "    public enum Role {",
        "        SYSTEM, USER, ASSISTANT, TOOL",
        "    }",
        "",
        "    private final Role role;",
        "    private final String content;",
        "    private final String toolName;",
        "    private final Instant createdAt;",
        "",
        "    private Message(Role role, String content, String toolName) {",
        "        if (role == null) {",
        "            throw new IllegalArgumentException(\"role is required\");",
        "        }",
        "        if (content == null || content.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(\"content is required\");",
        "        }",
        "        if (role == Role.TOOL && (toolName == null || toolName.trim().isEmpty())) {",
        "            throw new IllegalArgumentException(\"toolName is required for tool messages\");",
        "        }",
        "        this.role = role;",
        "        this.content = content;",
        "        this.toolName = toolName;",
        "        this.createdAt = Instant.now();",
        "    }",
        "",
        "    public static Message system(String content) {",
        "        return new Message(Role.SYSTEM, content, null);",
        "    }",
        "",
        "    public static Message user(String content) {",
        "        return new Message(Role.USER, content, null);",
        "    }",
        "",
        "    public static Message assistant(String content) {",
        "        return new Message(Role.ASSISTANT, content, null);",
        "    }",
        "",
        "    public static Message tool(String toolName, String content) {",
        "        return new Message(Role.TOOL, content, toolName);",
        "    }",
        "",
        "    public Role role() {",
        "        return role;",
        "    }",
        "",
        "    public String content() {",
        "        return content;",
        "    }",
        "",
        "    public String toolName() {",
        "        return toolName;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public int estimatedTokens() {",
        "        return Math.max(1, content.length() / 4);",
        "    }",
        "",
        "    public String toPromptLine() {",
        "        if (role == Role.TOOL) {",
        "            return \"TOOL \" + toolName + \": \" + content;",
        "        }",
        "        return role.name() + \": \" + content;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Conversation.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.UUID;",
        "",
        "public final class Conversation {",
        "    private final String id;",
        "    private final List<Message> messages = new ArrayList<>();",
        "    private final int maxContextTokens;",
        "",
        "    public Conversation(int maxContextTokens) {",
        "        this(UUID.randomUUID().toString(), maxContextTokens);",
        "    }",
        "",
        "    public Conversation(String id, int maxContextTokens) {",
        "        if (id == null || id.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(\"id is required\");",
        "        }",
        "        if (maxContextTokens <= 0) {",
        "            throw new IllegalArgumentException(\"maxContextTokens must be positive\");",
        "        }",
        "        this.id = id;",
        "        this.maxContextTokens = maxContextTokens;",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public synchronized void add(Message message) {",
        "        if (message == null) {",
        "            throw new IllegalArgumentException(\"message is required\");",
        "        }",
        "        messages.add(message);",
        "    }",
        "",
        "    public synchronized List<Message> messages() {",
        "        return Collections.unmodifiableList(new ArrayList<>(messages));",
        "    }",
        "",
        "    public synchronized List<Message> contextWindow() {",
        "        List<Message> selected = new ArrayList<>();",
        "        int used = 0;",
        "        for (int i = messages.size() - 1; i >= 0; i--) {",
        "            Message message = messages.get(i);",
        "            int cost = message.estimatedTokens();",
        "            if (!selected.isEmpty() && used + cost > maxContextTokens) {",
        "                break;",
        "            }",
        "            selected.add(0, message);",
        "            used += cost;",
        "        }",
        "        if (!messages.isEmpty() && messages.get(0).role() == Message.Role.SYSTEM && !selected.contains(messages.get(0))) {",
        "            Message system = messages.get(0);",
        "            if (used + system.estimatedTokens() <= maxContextTokens || selected.isEmpty()) {",
        "                selected.add(0, system);",
        "            }",
        "        }",
        "        return Collections.unmodifiableList(selected);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ModelProvider.java",
      language: "java",
      content: [
        "import java.util.List;",
        "import java.util.Locale;",
        "import java.util.Map;",
        "",
        "public interface ModelProvider {",
        "    String name();",
        "",
        "    void streamChat(List<Message> context, ToolCallHandler tools, StreamObserver observer);",
        "",
        "    interface ToolCallHandler {",
        "        String call(String name, Map<String, String> arguments);",
        "    }",
        "",
        "    static ModelProvider create(String providerName) {",
        "        String normalized = providerName == null ? \"\" : providerName.trim().toLowerCase(Locale.ROOT);",
        "        switch (normalized) {",
        "            case \"openai\":",
        "                return new OpenAiProvider(new OpenAiProvider.OpenAiClient());",
        "            case \"anthropic\":",
        "                return new AnthropicProvider(new AnthropicProvider.AnthropicClient());",
        "            case \"local\":",
        "                return new LocalProvider();",
        "            default:",
        "                throw new IllegalArgumentException(\"Unknown provider: \" + providerName);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "OpenAiProvider.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "",
        "public final class OpenAiProvider implements ModelProvider {",
        "    private final OpenAiClient client;",
        "",
        "    public OpenAiProvider(OpenAiClient client) {",
        "        if (client == null) {",
        "            throw new IllegalArgumentException(\"client is required\");",
        "        }",
        "        this.client = client;",
        "    }",
        "",
        "    @Override",
        "    public String name() {",
        "        return \"openai\";",
        "    }",
        "",
        "    @Override",
        "    public void streamChat(List<Message> context, ToolCallHandler tools, StreamObserver observer) {",
        "        try {",
        "            String prompt = client.toPrompt(context);",
        "            if (prompt.toLowerCase().contains(\"weather\")) {",
        "                Map<String, String> args = new HashMap<>();",
        "                args.put(\"city\", \"Bengaluru\");",
        "                prompt = prompt + \"\\nTOOL weather: \" + tools.call(\"weather\", args);",
        "            }",
        "            for (String token : client.stream(prompt)) {",
        "                observer.onToken(token);",
        "            }",
        "            observer.onComplete(Message.assistant(client.summary(prompt)));",
        "        } catch (RuntimeException error) {",
        "            observer.onError(error);",
        "        }",
        "    }",
        "",
        "    public static final class OpenAiClient {",
        "        String toPrompt(List<Message> context) {",
        "            StringBuilder prompt = new StringBuilder();",
        "            for (Message message : context) {",
        "                prompt.append(message.toPromptLine()).append(\"\\n\");",
        "            }",
        "            return prompt.toString();",
        "        }",
        "",
        "        List<String> stream(String prompt) {",
        "            List<String> tokens = new ArrayList<>();",
        "            tokens.add(\"OpenAI \");",
        "            tokens.add(\"adapter \");",
        "            tokens.add(\"streams \");",
        "            tokens.add(\"with \");",
        "            tokens.add(\"normalized \");",
        "            tokens.add(\"tokens.\");",
        "            return tokens;",
        "        }",
        "",
        "        String summary(String prompt) {",
        "            return \"OpenAI adapter completed a response for \" + prompt.length() + \" prompt characters.\";",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "AnthropicProvider.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "",
        "public final class AnthropicProvider implements ModelProvider {",
        "    private final AnthropicClient client;",
        "",
        "    public AnthropicProvider(AnthropicClient client) {",
        "        if (client == null) {",
        "            throw new IllegalArgumentException(\"client is required\");",
        "        }",
        "        this.client = client;",
        "    }",
        "",
        "    @Override",
        "    public String name() {",
        "        return \"anthropic\";",
        "    }",
        "",
        "    @Override",
        "    public void streamChat(List<Message> context, ToolCallHandler tools, StreamObserver observer) {",
        "        try {",
        "            String prompt = client.composeMessages(context);",
        "            if (prompt.toLowerCase().contains(\"ticket\")) {",
        "                Map<String, String> args = new HashMap<>();",
        "                args.put(\"id\", \"IQ-42\");",
        "                prompt = prompt + \"\\nTOOL ticketLookup: \" + tools.call(\"ticketLookup\", args);",
        "            }",
        "            for (String token : client.deltaStream(prompt)) {",
        "                observer.onToken(token);",
        "            }",
        "            observer.onComplete(Message.assistant(client.summary(prompt)));",
        "        } catch (RuntimeException error) {",
        "            observer.onError(error);",
        "        }",
        "    }",
        "",
        "    public static final class AnthropicClient {",
        "        String composeMessages(List<Message> context) {",
        "            StringBuilder prompt = new StringBuilder(\"Human and assistant transcript\\n\");",
        "            for (Message message : context) {",
        "                prompt.append(message.toPromptLine()).append(\"\\n\");",
        "            }",
        "            return prompt.toString();",
        "        }",
        "",
        "        List<String> deltaStream(String prompt) {",
        "            List<String> tokens = new ArrayList<>();",
        "            tokens.add(\"Anthropic \");",
        "            tokens.add(\"adapter \");",
        "            tokens.add(\"maps \");",
        "            tokens.add(\"deltas \");",
        "            tokens.add(\"to \");",
        "            tokens.add(\"tokens.\");",
        "            return tokens;",
        "        }",
        "",
        "        String summary(String prompt) {",
        "            return \"Anthropic adapter completed a response for \" + prompt.length() + \" prompt characters.\";",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "LocalProvider.java",
      language: "java",
      content: [
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "",
        "public final class LocalProvider implements ModelProvider {",
        "    @Override",
        "    public String name() {",
        "        return \"local\";",
        "    }",
        "",
        "    @Override",
        "    public void streamChat(List<Message> context, ToolCallHandler tools, StreamObserver observer) {",
        "        try {",
        "            String lastUser = lastUserMessage(context);",
        "            String toolResult = \"\";",
        "            if (lastUser.toLowerCase().contains(\"calculate\")) {",
        "                Map<String, String> args = new HashMap<>();",
        "                args.put(\"expression\", \"2+2\");",
        "                toolResult = \" Tool result: \" + tools.call(\"calculator\", args);",
        "            }",
        "            String response = \"Local model used \" + context.size() + \" context messages.\" + toolResult;",
        "            for (String token : response.split(\" \")) {",
        "                observer.onToken(token + \" \");",
        "            }",
        "            observer.onComplete(Message.assistant(response));",
        "        } catch (RuntimeException error) {",
        "            observer.onError(error);",
        "        }",
        "    }",
        "",
        "    private String lastUserMessage(List<Message> context) {",
        "        for (int i = context.size() - 1; i >= 0; i--) {",
        "            Message message = context.get(i);",
        "            if (message.role() == Message.Role.USER) {",
        "                return message.content();",
        "            }",
        "        }",
        "        return \"\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "StreamObserver.java",
      language: "java",
      content: [
        "public interface StreamObserver {",
        "    void onToken(String token);",
        "",
        "    void onComplete(Message finalMessage);",
        "",
        "    void onError(Throwable error);",
        "}",
      ].join("\n"),
    },
    {
      filename: "ChatService.java",
      language: "java",
      content: [
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.concurrent.CopyOnWriteArrayList;",
        "",
        "public final class ChatService implements ModelProvider.ToolCallHandler {",
        "    public interface ChatTool {",
        "        String execute(Map<String, String> arguments);",
        "    }",
        "",
        "    private final ModelProvider provider;",
        "    private final Conversation conversation;",
        "    private final Map<String, ChatTool> tools = new HashMap<>();",
        "    private final List<StreamObserver> observers = new CopyOnWriteArrayList<>();",
        "",
        "    private ChatService(ModelProvider provider, Conversation conversation) {",
        "        if (provider == null || conversation == null) {",
        "            throw new IllegalArgumentException(\"provider and conversation are required\");",
        "        }",
        "        this.provider = provider;",
        "        this.conversation = conversation;",
        "    }",
        "",
        "    public static ChatService create(String providerName, int contextTokens) {",
        "        return new ChatService(ModelProvider.create(providerName), new Conversation(contextTokens));",
        "    }",
        "",
        "    public Conversation conversation() {",
        "        return conversation;",
        "    }",
        "",
        "    public void registerTool(String name, ChatTool tool) {",
        "        if (name == null || name.trim().isEmpty() || tool == null) {",
        "            throw new IllegalArgumentException(\"valid name and tool are required\");",
        "        }",
        "        tools.put(name, tool);",
        "    }",
        "",
        "    public void addObserver(StreamObserver observer) {",
        "        if (observer == null) {",
        "            throw new IllegalArgumentException(\"observer is required\");",
        "        }",
        "        observers.add(observer);",
        "    }",
        "",
        "    public void sendUserMessage(String text, StreamObserver requestObserver) {",
        "        conversation.add(Message.user(text));",
        "        List<Message> context = conversation.contextWindow();",
        "        StreamObserver multicast = new MulticastObserver(requestObserver);",
        "        provider.streamChat(context, this, new PersistingObserver(multicast));",
        "    }",
        "",
        "    @Override",
        "    public String call(String name, Map<String, String> arguments) {",
        "        ChatTool tool = tools.get(name);",
        "        if (tool == null) {",
        "            throw new IllegalArgumentException(\"Unknown tool: \" + name);",
        "        }",
        "        Map<String, String> safeArguments = arguments == null ? new HashMap<String, String>() : new HashMap<>(arguments);",
        "        String result = tool.execute(safeArguments);",
        "        conversation.add(Message.tool(name, result));",
        "        return result;",
        "    }",
        "",
        "    private final class PersistingObserver implements StreamObserver {",
        "        private final StreamObserver delegate;",
        "        private final StringBuilder assistant = new StringBuilder();",
        "",
        "        private PersistingObserver(StreamObserver delegate) {",
        "            this.delegate = delegate;",
        "        }",
        "",
        "        @Override",
        "        public void onToken(String token) {",
        "            assistant.append(token);",
        "            delegate.onToken(token);",
        "        }",
        "",
        "        @Override",
        "        public void onComplete(Message ignored) {",
        "            String content = assistant.toString().trim();",
        "            Message finalMessage = content.isEmpty() ? ignored : Message.assistant(content);",
        "            conversation.add(finalMessage);",
        "            delegate.onComplete(finalMessage);",
        "        }",
        "",
        "        @Override",
        "        public void onError(Throwable error) {",
        "            delegate.onError(error);",
        "        }",
        "    }",
        "",
        "    private final class MulticastObserver implements StreamObserver {",
        "        private final StreamObserver requestObserver;",
        "",
        "        private MulticastObserver(StreamObserver requestObserver) {",
        "            this.requestObserver = requestObserver;",
        "        }",
        "",
        "        @Override",
        "        public void onToken(String token) {",
        "            if (requestObserver != null) {",
        "                requestObserver.onToken(token);",
        "            }",
        "            for (StreamObserver observer : observers) {",
        "                observer.onToken(token);",
        "            }",
        "        }",
        "",
        "        @Override",
        "        public void onComplete(Message finalMessage) {",
        "            if (requestObserver != null) {",
        "                requestObserver.onComplete(finalMessage);",
        "            }",
        "            for (StreamObserver observer : observers) {",
        "                observer.onComplete(finalMessage);",
        "            }",
        "        }",
        "",
        "        @Override",
        "        public void onError(Throwable error) {",
        "            if (requestObserver != null) {",
        "                requestObserver.onError(error);",
        "            }",
        "            for (StreamObserver observer : observers) {",
        "                observer.onError(error);",
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Message",
      detailMD:
        "Immutable value object for a chat entry. Static constructors make valid roles explicit, and **estimatedTokens** supports context-window trimming.",
    },
    {
      className: "Conversation",
      detailMD:
        "Owns ordered messages and exposes snapshots. **contextWindow** walks backward from the latest message to keep provider prompts under budget.",
    },
    {
      className: "ModelProvider",
      detailMD:
        "Provider strategy interface. The nested **ToolCallHandler** is the safe callback into application tools, and **create** is the factory method for named providers.",
    },
    {
      className: "OpenAiProvider",
      detailMD:
        "Adapter for an OpenAI-shaped client. It converts messages into a prompt, optionally requests the weather tool, and normalizes streamed chunks as observer tokens.",
    },
    {
      className: "AnthropicProvider",
      detailMD:
        "Adapter for an Anthropic-shaped client. It has different prompt composition and delta streaming, but still satisfies **ModelProvider**.",
    },
    {
      className: "LocalProvider",
      detailMD:
        "Lightweight provider strategy for development and tests. It uses the same streaming and tool-calling contract without any vendor client.",
    },
    {
      className: "StreamObserver",
      detailMD:
        "Observer interface for token streaming, completion, and failure. Transport adapters implement this outside the core chat model.",
    },
    {
      className: "ChatService",
      detailMD:
        "Use-case orchestrator. It appends user messages, obtains bounded context, invokes the provider, dispatches tools, multicasts stream events, and stores the final assistant message.",
    },
  ],

  dryRun: {
    inputMD:
      "Conversation has a system prompt and two old turns. Context limit is 60 estimated tokens. User asks: **What is the weather in Bengaluru and summarize it?** Provider is OpenAI; registered tool **weather** returns **24C, light rain**.",
    columns: ["Step", "Input/Event", "Context window", "Provider/tool action", "Streamed output", "Stored messages"],
    rows: [
      [
        "1",
        "sendUserMessage",
        "System + recent turns + new user message",
        "OpenAiProvider receives bounded context",
        "No tokens yet",
        "User message appended",
      ],
      [
        "2",
        "Provider detects weather intent",
        "Same bounded context",
        "ChatService.call(weather, city=Bengaluru)",
        "No tokens yet",
        "Tool message stored",
      ],
      [
        "3",
        "Tool result returned",
        "Prompt now includes tool result",
        "Provider resumes generation",
        "OpenAI adapter streams",
        "Assistant draft not stored yet",
      ],
      [
        "4",
        "Provider completes",
        "Unchanged",
        "PersistingObserver builds final message",
        "onComplete(finalMessage)",
        "Assistant message appended",
      ],
    ],
    narrativeMD:
      "The important separation is visible in step 2: the adapter can ask for a function, but only the service can dispatch the named tool and record the tool result.",
  },

  complexity: [
    {
      operation: "sendUserMessage",
      time: "O(M + T)",
      space: "O(M)",
      note: "M messages are scanned only until the context budget is filled; T streamed tokens are forwarded.",
    },
    {
      operation: "contextWindow",
      time: "O(M)",
      space: "O(K)",
      note: "Worst case scans all messages; K selected messages are copied into the bounded prompt.",
    },
    {
      operation: "tool dispatch",
      time: "O(1) average",
      space: "O(A)",
      note: "Hash-map lookup by tool name plus a defensive copy of A arguments.",
    },
    {
      operation: "observer broadcast",
      time: "O(O × T)",
      space: "O(1)",
      note: "Each of T tokens is sent to O registered observers plus the request observer.",
    },
  ],
  complexityNotesMD:
    "In real systems provider latency dominates CPU work, but interviewers still expect you to call out context-window cost and observer fan-out. A production memory policy can replace the linear scan with summarized checkpoints or token-indexed history.",

  extensibility: [
    {
      label: "New model provider",
      detailMD:
        "Implement **ModelProvider** in a new adapter, translate provider-specific streaming into **StreamObserver**, and add one branch to the factory method or dependency injection wiring.",
    },
    {
      label: "New tool",
      detailMD:
        "Register another **ChatTool** under a safe name. Provider adapters can call it without importing tool classes.",
    },
    {
      label: "Different memory policy",
      detailMD:
        "Replace **Conversation.contextWindow** with a tokenizer-aware policy, summarization, vector recall, or pinned system messages without changing providers.",
    },
    {
      label: "Multiple transports",
      detailMD:
        "Add **StreamObserver** implementations for WebSocket, server-sent events, mobile push, audit logging, or tests.",
    },
    {
      label: "Provider failover",
      detailMD:
        "Wrap **ModelProvider** with a retrying or fallback provider that delegates to OpenAI first, then Anthropic or local inference.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Provider-specific services",
      detailMD:
        "Create **OpenAiChatService**, **AnthropicChatService**, and **LocalChatService**, each owning its own flow.",
      tradeoffsMD:
        "Initially simple, but conversation memory, tool dispatch, and streaming persistence get duplicated and drift across providers.",
    },
    {
      name: "Event bus for streaming",
      detailMD:
        "Publish token events to an internal event bus instead of calling observers directly.",
      tradeoffsMD:
        "Useful for distributed fan-out and replay, but overkill for the LLD core and harder to reason about in an interview.",
    },
    {
      name: "Command objects for tools",
      detailMD:
        "Represent every function call as a **Command** with validation, authorization, and execution phases.",
      tradeoffsMD:
        "Great when tools become complex workflows, but a named **ChatTool** map is clearer for the base design.",
    },
  ],

  commonMistakes: [
    "Letting **ChatService** build OpenAI and Anthropic JSON directly, which destroys provider abstraction.",
    "Waiting for the full provider response before notifying clients, so the design is not truly streaming.",
    "Forgetting to persist the final assistant message after streaming, causing conversation memory to lose answers.",
    "Sending the full conversation forever instead of enforcing a context window.",
    "Allowing providers to execute arbitrary methods instead of using a named tool registry.",
    "Mixing UI transport concerns such as WebSocket sessions into provider adapters.",
    "Treating OpenAI, Anthropic, and local models as subclasses of Conversation instead of interchangeable strategies.",
  ],

  followUps: [
    {
      question: "How would you support retries without duplicating streamed tokens?",
      answerMD:
        "Track a provider attempt id and only persist the final assistant message for the successful attempt. For clients, emit retry metadata or restart the stream with a clear boundary.",
    },
    {
      question: "How would you add retrieval-augmented generation?",
      answerMD:
        "Insert a memory or retrieval step before **ModelProvider.streamChat** that adds retrieved snippets as system or tool messages. Keep providers unchanged.",
    },
    {
      question: "How do you prevent unsafe tool execution?",
      answerMD:
        "Use an allow-list registry, validate arguments per tool, apply authorization before execution, add timeouts, and record tool results as messages for auditability.",
    },
    {
      question: "How would you stream to both browser and logs?",
      answerMD:
        "Register two **StreamObserver** implementations. The service multicasts token, completion, and error events to both.",
    },
    {
      question: "How would you handle provider-specific features like image input?",
      answerMD:
        "Add capability metadata or a richer request object while preserving the **ModelProvider** boundary. Unsupported providers can reject with a typed error.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable storage",
      detailMD:
        "Persist conversations, messages, tool calls, provider attempt metadata, and final assistant responses in a repository or event log.",
    },
    {
      label: "Backpressure and cancellation",
      detailMD:
        "Observers should support cancellation and slow-client handling so one browser connection cannot block provider streaming.",
    },
    {
      label: "Provider credentials and quotas",
      detailMD:
        "Keep API keys outside adapters, route through a credential provider, enforce per-user quotas, and expose cost metrics by provider.",
    },
    {
      label: "Safety and moderation",
      detailMD:
        "Add moderation, tool authorization, prompt-injection checks, and audit logs around user input and tool output.",
    },
    {
      label: "Observability",
      detailMD:
        "Measure first-token latency, total latency, streamed token count, context size, tool-call count, errors, and provider fallback rate.",
    },
  ],

  interviewNotes: [
    "Did the candidate keep provider APIs behind **ModelProvider** and concrete adapters?",
    "Can they explain why streaming is an Observer use case rather than a return string?",
    "Did they bound conversation memory before provider calls?",
    "Is tool dispatch safe, named, and owned by the service rather than by provider code?",
    "Can they add a new provider or transport by adding classes, not rewriting the flow?",
  ],

  quiz: [
    {
      question: "Why should **ChatService** depend on **ModelProvider** instead of **OpenAiProvider** directly?",
      options: [
        "So provider choice can vary without changing chat orchestration",
        "So messages no longer need roles",
        "So token streaming becomes synchronous",
        "So tool calls can bypass validation",
      ],
      answerIndex: 0,
      explanationMD:
        "That is the Strategy seam: OpenAI, Anthropic, and local inference are interchangeable from the service perspective.",
    },
    {
      question: "What does **StreamObserver** primarily decouple?",
      options: [
        "Conversation id generation from message storage",
        "Token production from token delivery",
        "Tool registration from authorization",
        "Provider selection from factory construction",
      ],
      answerIndex: 1,
      explanationMD:
        "Providers emit tokens, while observers decide whether those tokens go to a browser, CLI, log, or test assertion.",
    },
    {
      question: "Where should OpenAI-specific request formatting live?",
      options: [
        "Inside **Conversation**",
        "Inside **ChatService**",
        "Inside **OpenAiProvider**",
        "Inside **StreamObserver**",
      ],
      answerIndex: 2,
      explanationMD:
        "The adapter owns vendor translation. The domain and service stay provider-neutral.",
    },
    {
      question: "Why does the design record tool results as messages?",
      options: [
        "To make future prompts and audits reflect what the model saw",
        "To reduce the number of observers",
        "To avoid creating provider adapters",
        "To make every tool call asynchronous",
      ],
      answerIndex: 0,
      explanationMD:
        "Tool output becomes part of the conversation trace, so later context and debugging are consistent.",
    },
    {
      question: "What problem does **Conversation.contextWindow** solve?",
      options: [
        "It chooses the cheapest model provider",
        "It prevents unbounded history from exceeding provider token limits",
        "It encrypts messages before storage",
        "It replaces the need for tool calls",
      ],
      answerIndex: 1,
      explanationMD:
        "A bounded context window is the basic memory control before more advanced summarization or retrieval is introduced.",
    },
  ],

  practiceVariants: [
    {
      title: "Add summarizing memory",
      detailMD:
        "When history exceeds the token budget, summarize older turns into a pinned system memory message instead of dropping them entirely.",
      difficulty: "Intermediate",
    },
    {
      title: "Add provider fallback",
      detailMD:
        "Create a provider wrapper that retries on transient errors and falls back from OpenAI to Anthropic or local inference.",
      difficulty: "Advanced",
    },
    {
      title: "Add typed tool schemas",
      detailMD:
        "Extend **ChatTool** with a JSON-schema-like argument contract, validation errors, and per-tool authorization.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "Which class owns conversation memory?",
      back: "**Conversation** owns ordered messages and builds the bounded context window.",
    },
    {
      front: "Which pattern makes OpenAI, Anthropic, and local models interchangeable?",
      back: "Strategy, implemented by the **ModelProvider** interface.",
    },
    {
      front: "Why are provider classes also adapters?",
      back: "They translate vendor-specific prompt and stream formats into the common **ModelProvider** and **StreamObserver** contracts.",
    },
    {
      front: "What does **StreamObserver.onToken** represent?",
      back: "One streamed token or chunk becoming available to a UI, log, test, or any other subscriber.",
    },
    {
      front: "Where should a weather or calculator tool be invoked?",
      back: "Through **ChatService.call**, which looks up a registered **ChatTool** by name and records the tool result.",
    },
    {
      front: "What is the hot extensibility point for adding a new vendor?",
      back: "Implement **ModelProvider**, then wire it through the factory or dependency injection configuration.",
    },
  ],

  cheatSheetMD: [
    "**Core model:** Conversation owns ordered Message objects; roles are SYSTEM, USER, ASSISTANT, and TOOL.",
    "",
    "**Provider seam:** ChatService depends on ModelProvider. OpenAiProvider, AnthropicProvider, and LocalProvider are interchangeable strategies and vendor adapters.",
    "",
    "**Streaming seam:** Providers push tokens to StreamObserver. ChatService wraps observers to multicast tokens and persist the final assistant message.",
    "",
    "**Memory:** Before every provider call, build a bounded context window. Production systems can replace the simple token estimate with a tokenizer, summarizer, or retrieval step.",
    "",
    "**Tools:** Providers ask ToolCallHandler.call(name, args). ChatService dispatches to registered ChatTool instances and records tool output as a message.",
    "",
    "**Patterns:** Strategy for providers, Adapter for vendor clients, Observer for streaming, Factory Method for provider creation.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Refactoring Guru — Strategy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/strategy",
    },
    {
      title: "OpenAI Function Calling Guide",
      kind: "Docs",
      url: "https://platform.openai.com/docs/guides/function-calling",
    },
    {
      title: "Anthropic Messages API Documentation",
      kind: "Docs",
      url: "https://docs.anthropic.com/en/api/messages",
    },
  ],

  relatedProblems: [
    { slug: "rag-pipeline", note: "Adds retrieval and memory enrichment before model generation." },
    { slug: "whatsapp", note: "Another conversation-centric system with message ordering and delivery semantics." },
    { slug: "api-gateway", note: "Useful for thinking about provider routing, rate limits, and adapters." },
  ],
};
