import type { LLDProblemContent } from "../types";

/**
 * Exemplar LLD problem — Design an Airline Reservation System.
 *
 * Fresh inline Java implementation focused on flight search, seat inventory,
 * timed holds, PNR lifecycle, and class-based pricing.
 */
export const airlineReservation: LLDProblemContent = {
  slug: "airline-reservation",

  statementMD: [
    "Design the object model for an **airline reservation system** where travelers",
    "can search flights, inspect available seats by cabin class, place a temporary",
    "seat hold, confirm the booking into a PNR, and cancel or expire the booking",
    "when the lifecycle demands it.",
    "",
    "The core interview challenge is not a full airline GDS. It is the **seat",
    "inventory and booking lifecycle**: one seat must never be sold twice, a held",
    "seat must be locked for one booking for a bounded time, pricing should vary",
    "by cabin class, and every booking should move through an explicit state",
    "machine.",
  ].join("\n"),

  businessContextMD: [
    "Airline Reservation is a high-signal LLD question because the domain has",
    "real business pressure: inventory is scarce, demand changes quickly, and a",
    "bad concurrency decision directly causes overbooking. Interviewers use it",
    "to test whether a candidate can separate search from reservation, model a",
    "PNR as a lifecycle object, isolate pricing policy, and explain the critical",
    "section around seat holds and confirmation.",
  ].join("\n"),

  functionalRequirements: [
    "Represent flights with origin, destination, departure time, and a finite set of seats.",
    "Represent seats with a seat number, cabin class, and inventory status such as available, held, or booked.",
    "Search flights by route, travel date, and requested cabin class while showing only flights with matching availability.",
    "Allow a traveler to select a concrete seat and place a time-bound hold on it.",
    "Create an itinerary/PNR for the held seat, passenger, flight, and lifecycle status.",
    "Confirm a held booking by pricing the selected seat and converting the hold into a booked seat.",
    "Cancel confirmed or held bookings and release the seat back to inventory when appropriate.",
    "Expire stale holds so seats do not remain blocked forever.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Inventory correctness",
      detailMD:
        "A seat can be owned by at most one active booking. Hold and confirm are the critical operations and must be guarded atomically.",
    },
    {
      label: "Low-latency search",
      detailMD:
        "Search should scan indexed flight data and read current inventory quickly; it must not take locks longer than needed for a consistent seat snapshot.",
    },
    {
      label: "Explicit lifecycle",
      detailMD:
        "Booking transitions must be visible and constrained. Draft, held, confirmed, cancelled, and expired states should not be represented by scattered booleans.",
    },
    {
      label: "Extensible pricing",
      detailMD:
        "Cabin-class fares, demand adjustments, loyalty discounts, and promotions should vary independently from the reservation flow.",
    },
    {
      label: "Observable events",
      detailMD:
        "Hold, confirm, cancel, and expire events should be publishable to email, SMS, analytics, and downstream inventory systems.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need to integrate with external airline inventory providers?",
      answerMD:
        "No for the base design. Treat flights and seats as in-memory domain objects. A repository or adapter can later replace the in-memory list.",
    },
    {
      question: "Can a user book multiple passengers or multiple flight legs in one PNR?",
      answerMD:
        "The base model books one passenger on one flight and one selected seat. Multi-passenger and multi-leg PNRs are extensions that wrap several seat allocations in one itinerary.",
    },
    {
      question: "Should a hold reserve a cabin class or a specific seat?",
      answerMD:
        "Use specific seat selection because the prompt emphasizes seat inventory management. Holding a class-level quota is a useful alternative design but less concrete for LLD.",
    },
    {
      question: "How long does a seat hold last?",
      answerMD:
        "Assume a configurable hold duration, such as ten minutes. Confirmation must reject expired holds and release their seats.",
    },
    {
      question: "Is payment processing in scope?",
      answerMD:
        "Only the pricing and confirmation boundary are in scope. A real payment gateway would be an adapter called before the booking is marked confirmed.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Flight {",
    "        -String flightNumber",
    "        -String origin",
    "        -String destination",
    "        -LocalDateTime departureTime",
    "        -Map~String,Seat~ seats",
    "        +availableSeats(CabinClass, Instant) List~Seat~",
    "        +holdSeat(String, String, Duration, Instant) boolean",
    "        +confirmSeat(String, String, Instant) boolean",
    "        +releaseSeat(String, String) boolean",
    "    }",
    "    class Seat {",
    "        -String seatNumber",
    "        -CabinClass cabinClass",
    "        -SeatStatus status",
    "        -String heldByBookingId",
    "        -Instant holdExpiresAt",
    "        +hold(String, Instant, Instant) boolean",
    "        +book(String, Instant) boolean",
    "        +release(String) boolean",
    "    }",
    "    class Booking {",
    "        -String id",
    "        -String passengerName",
    "        -Flight flight",
    "        -Seat seat",
    "        -BookingState state",
    "        +hold(Duration, Instant) void",
    "        +confirm(long, Instant) void",
    "        +cancel(Instant) void",
    "        +getStatus() BookingStatus",
    "    }",
    "    class BookingState {",
    "        <<interface>>",
    "        +hold(Booking, Duration, Instant) void",
    "        +confirm(Booking, long, Instant) void",
    "        +cancel(Booking, Instant) void",
    "    }",
    "    class PricingStrategy {",
    "        <<interface>>",
    "        +price(Flight, Seat) Money",
    "    }",
    "    class ClassBasedPricingStrategy",
    "    class SearchService {",
    "        +search(List~Flight~, String, String, LocalDate, CabinClass, Instant) List~Flight~",
    "    }",
    "    class ReservationService {",
    "        -Map~String,Booking~ bookings",
    "        -PricingStrategy pricingStrategy",
    "        -List~BookingObserver~ observers",
    "        +holdSeat(String, String, String) Booking",
    "        +confirm(String) Money",
    "        +cancel(String) void",
    "    }",
    "    class BookingObserver {",
    "        <<interface>>",
    "        +onBookingEvent(Booking, String) void",
    "    }",
    "    class CabinClass {",
    "        <<enumeration>>",
    "        ECONOMY",
    "        PREMIUM_ECONOMY",
    "        BUSINESS",
    "        FIRST",
    "    }",
    "    class BookingStatus {",
    "        <<enumeration>>",
    "        DRAFT",
    "        HELD",
    "        CONFIRMED",
    "        CANCELLED",
    "        EXPIRED",
    "    }",
    "    Flight o-- Seat",
    "    Booking --> Flight",
    "    Booking --> Seat",
    "    Booking --> BookingState",
    "    BookingState <|.. DraftState",
    "    BookingState <|.. HeldState",
    "    BookingState <|.. ConfirmedState",
    "    PricingStrategy <|.. ClassBasedPricingStrategy",
    "    ReservationService ..> PricingStrategy",
    "    ReservationService ..> BookingObserver",
    "    ReservationService ..> Booking",
    "    SearchService ..> Flight",
    "    Seat --> CabinClass",
    "    Booking --> BookingStatus",
  ].join("\n"),
  classDiagramCaptionMD:
    "Flight owns seat inventory, Booking owns lifecycle, ReservationService orchestrates the booking boundary, and PricingStrategy plus BookingObserver provide policy and event seams.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Passenger",
    "    participant Search as SearchService",
    "    participant Reservations as ReservationService",
    "    participant Flight as Flight",
    "    participant Seat as Seat",
    "    participant Booking as Booking",
    "    participant Pricing as PricingStrategy",
    "    participant Observer as BookingObserver",
    "    Passenger->>Search: search(route, date, cabin)",
    "    Search->>Flight: availableSeats(cabin, now)",
    "    Flight-->>Search: matching seats",
    "    Search-->>Passenger: flights with inventory",
    "    Passenger->>Reservations: holdSeat(flight, seat, passenger)",
    "    Reservations->>Booking: create draft PNR",
    "    Booking->>Flight: holdSeat(seat, pnr, ttl, now)",
    "    Flight->>Seat: hold(pnr, expiresAt, now)",
    "    Seat-->>Flight: held",
    "    Booking-->>Reservations: status HELD",
    "    Reservations->>Observer: onBookingEvent(HELD)",
    "    Passenger->>Reservations: confirm(pnr)",
    "    Reservations->>Pricing: price(flight, seat)",
    "    Pricing-->>Reservations: fare",
    "    Reservations->>Booking: confirm(fare, now)",
    "    Booking->>Flight: confirmSeat(seat, pnr, now)",
    "    Flight->>Seat: book(pnr, now)",
    "    Reservations->>Observer: onBookingEvent(CONFIRMED)",
    "    Reservations-->>Passenger: PNR confirmed",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Search reads inventory, hold locks a specific seat for one PNR, confirmation prices and books the same held seat, and observers receive lifecycle events.",

  entities: [
    {
      name: "Flight",
      responsibilityMD:
        "Aggregate for one scheduled flight. It owns the seat map and exposes inventory operations such as available seats, hold, confirm, and release.",
      attributes: ["flightNumber", "origin", "destination", "departureTime", "seats"],
    },
    {
      name: "Seat",
      responsibilityMD:
        "Represents a concrete seat such as 2A. It carries cabin class and guarded inventory state, including which booking owns a hold and when that hold expires.",
      attributes: ["seatNumber", "cabinClass", "status", "heldByBookingId", "holdExpiresAt"],
    },
    {
      name: "Booking",
      responsibilityMD:
        "The PNR/itinerary object. It links passenger, flight, seat, charged amount, and the current state object that controls lifecycle transitions.",
      attributes: ["id", "passengerName", "flight", "seat", "state", "chargedAmountCents"],
    },
    {
      name: "BookingState",
      responsibilityMD:
        "State interface implemented by draft, held, confirmed, cancelled, and expired states. Each state decides which transitions are legal.",
      attributes: ["status", "hold", "confirm", "cancel", "expireIfNeeded"],
    },
    {
      name: "PricingStrategy",
      responsibilityMD:
        "Policy seam for computing fares. The sample class-based strategy uses cabin multipliers and a small demand adjustment.",
      attributes: ["price(flight, seat)"],
    },
    {
      name: "SearchService",
      responsibilityMD:
        "Read-side service that filters flights by route, date, cabin class, and current availability without creating bookings.",
      attributes: ["search"],
    },
    {
      name: "ReservationService",
      responsibilityMD:
        "Application boundary for holds, confirmations, cancellations, expiry sweeps, PNR storage, and observer notification.",
      attributes: ["bookings", "pricingStrategy", "observers", "holdDuration"],
    },
    {
      name: "BookingObserver",
      responsibilityMD:
        "Event listener interface for side effects such as emails, SMS, analytics, and inventory feeds.",
      attributes: ["onBookingEvent"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**BookingState** prevents illegal lifecycle jumps. A cancelled booking cannot be confirmed, an expired hold cannot be booked, and the rules live in state classes rather than scattered conditionals.",
    },
    {
      name: "Strategy",
      whyMD:
        "**PricingStrategy** makes fare calculation swappable. Cabin multipliers, demand adjustments, loyalty pricing, and promotions can be added without changing reservation orchestration.",
    },
    {
      name: "Observer",
      whyMD:
        "**BookingObserver** lets confirmation emails, SMS, analytics, and downstream inventory systems subscribe to booking events without coupling those systems to the domain model.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**ReservationService.createBooking** centralizes PNR creation. Subclasses can create specialized bookings for loyalty, corporate travel, or multi-leg itineraries while keeping the reservation workflow stable.",
    },
  ],

  designSteps: [
    {
      title: "Separate search from reservation",
      detailMD:
        "Search is a read path over flights and current cabin availability. It should never create a PNR or mutate seat state; mutation starts only when the traveler selects a concrete seat.",
    },
    {
      title: "Make Seat the inventory lock owner",
      detailMD:
        "The seat object owns available, held, and booked transitions. Hold and book are synchronized so the check-and-change sequence is atomic for one seat.",
      code: [
        "public synchronized boolean hold(String bookingId, Instant expiresAt, Instant now) {",
        "    expireHoldIfNeeded(now);",
        "    if (status != SeatStatus.AVAILABLE) {",
        "        return false;",
        "    }",
        "    status = SeatStatus.HELD;",
        "    heldByBookingId = bookingId;",
        "    holdExpiresAt = expiresAt;",
        "    return true;",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent the PNR as a Booking state machine",
      detailMD:
        "A booking starts in draft, then moves to held after the seat lock succeeds, confirmed after payment/pricing succeeds, or cancelled/expired when the lifecycle ends.",
      code: [
        "enum BookingStatus {",
        "    DRAFT, HELD, CONFIRMED, CANCELLED, EXPIRED",
        "}",
        "",
        "interface BookingState {",
        "    BookingStatus status();",
        "    void confirm(Booking booking, long chargedAmountCents, Instant now);",
        "}",
      ].join("\n"),
    },
    {
      title: "Price by cabin class behind a strategy",
      detailMD:
        "ReservationService asks a strategy for the final fare. The sample strategy uses a base economy fare, class multipliers, and a simple demand bump based on remaining seats.",
      code: [
        "public interface PricingStrategy {",
        "    Money price(Flight flight, Seat seat);",
        "}",
      ].join("\n"),
    },
    {
      title: "Use the service boundary as the transaction boundary",
      detailMD:
        "**ReservationService.holdSeat** finds the flight and seat, creates the PNR, asks Booking to hold the seat, stores the booking, and emits an event. In production this method maps to a database transaction.",
    },
    {
      title: "Notify observers after durable lifecycle changes",
      detailMD:
        "Observers are called only after a booking reaches held, confirmed, cancelled, or expired. Side effects are outside the core model, so a notification failure should not corrupt inventory.",
    },
  ],

  implementation: [
    {
      filename: "Flight.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.time.LocalDate;",
        "import java.time.LocalDateTime;",
        "import java.util.ArrayList;",
        "import java.util.EnumMap;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Optional;",
        "",
        "public class Flight {",
        "    private final String flightNumber;",
        "    private final String origin;",
        "    private final String destination;",
        "    private final LocalDateTime departureTime;",
        "    private final Map<String, Seat> seats = new LinkedHashMap<>();",
        "",
        "    public Flight(String flightNumber, String origin, String destination, LocalDateTime departureTime) {",
        "        this.flightNumber = flightNumber;",
        "        this.origin = origin;",
        "        this.destination = destination;",
        "        this.departureTime = departureTime;",
        "    }",
        "",
        "    public String getFlightNumber() {",
        "        return flightNumber;",
        "    }",
        "",
        "    public String getOrigin() {",
        "        return origin;",
        "    }",
        "",
        "    public String getDestination() {",
        "        return destination;",
        "    }",
        "",
        "    public LocalDateTime getDepartureTime() {",
        "        return departureTime;",
        "    }",
        "",
        "    public synchronized void addSeat(String seatNumber, CabinClass cabinClass) {",
        "        if (seats.containsKey(seatNumber)) {",
        "            throw new IllegalArgumentException(\"Duplicate seat \" + seatNumber);",
        "        }",
        "        seats.put(seatNumber, new Seat(seatNumber, cabinClass));",
        "    }",
        "",
        "    public boolean matches(String origin, String destination, LocalDate travelDate) {",
        "        return this.origin.equalsIgnoreCase(origin)",
        "                && this.destination.equalsIgnoreCase(destination)",
        "                && departureTime.toLocalDate().equals(travelDate);",
        "    }",
        "",
        "    public synchronized List<Seat> availableSeats(CabinClass cabinClass, Instant now) {",
        "        List<Seat> result = new ArrayList<>();",
        "        for (Seat seat : seats.values()) {",
        "            if (seat.getCabinClass() == cabinClass && seat.isAvailable(now)) {",
        "                result.add(seat);",
        "            }",
        "        }",
        "        return result;",
        "    }",
        "",
        "    public synchronized Optional<Seat> findSeat(String seatNumber) {",
        "        return Optional.ofNullable(seats.get(seatNumber));",
        "    }",
        "",
        "    public synchronized boolean holdSeat(String seatNumber, String bookingId, Duration holdFor, Instant now) {",
        "        Seat seat = seats.get(seatNumber);",
        "        return seat != null && seat.hold(bookingId, now.plus(holdFor), now);",
        "    }",
        "",
        "    public synchronized boolean confirmSeat(String seatNumber, String bookingId, Instant now) {",
        "        Seat seat = seats.get(seatNumber);",
        "        return seat != null && seat.book(bookingId, now);",
        "    }",
        "",
        "    public synchronized boolean releaseSeat(String seatNumber, String bookingId) {",
        "        Seat seat = seats.get(seatNumber);",
        "        return seat != null && seat.release(bookingId);",
        "    }",
        "",
        "    public synchronized Map<CabinClass, Integer> remainingByClass(Instant now) {",
        "        Map<CabinClass, Integer> remaining = new EnumMap<>(CabinClass.class);",
        "        for (CabinClass cabinClass : CabinClass.values()) {",
        "            remaining.put(cabinClass, 0);",
        "        }",
        "        for (Seat seat : seats.values()) {",
        "            if (seat.isAvailable(now)) {",
        "                remaining.put(seat.getCabinClass(), remaining.get(seat.getCabinClass()) + 1);",
        "            }",
        "        }",
        "        return remaining;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Seat.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "",
        "enum CabinClass {",
        "    ECONOMY,",
        "    PREMIUM_ECONOMY,",
        "    BUSINESS,",
        "    FIRST",
        "}",
        "",
        "enum SeatStatus {",
        "    AVAILABLE,",
        "    HELD,",
        "    BOOKED",
        "}",
        "",
        "public class Seat {",
        "    private final String seatNumber;",
        "    private final CabinClass cabinClass;",
        "    private SeatStatus status = SeatStatus.AVAILABLE;",
        "    private String heldByBookingId;",
        "    private Instant holdExpiresAt;",
        "",
        "    public Seat(String seatNumber, CabinClass cabinClass) {",
        "        this.seatNumber = seatNumber;",
        "        this.cabinClass = cabinClass;",
        "    }",
        "",
        "    public String getSeatNumber() {",
        "        return seatNumber;",
        "    }",
        "",
        "    public CabinClass getCabinClass() {",
        "        return cabinClass;",
        "    }",
        "",
        "    public synchronized SeatStatus getStatus(Instant now) {",
        "        expireHoldIfNeeded(now);",
        "        return status;",
        "    }",
        "",
        "    public synchronized boolean isAvailable(Instant now) {",
        "        expireHoldIfNeeded(now);",
        "        return status == SeatStatus.AVAILABLE;",
        "    }",
        "",
        "    public synchronized boolean hold(String bookingId, Instant expiresAt, Instant now) {",
        "        expireHoldIfNeeded(now);",
        "        if (status != SeatStatus.AVAILABLE) {",
        "            return false;",
        "        }",
        "        status = SeatStatus.HELD;",
        "        heldByBookingId = bookingId;",
        "        holdExpiresAt = expiresAt;",
        "        return true;",
        "    }",
        "",
        "    public synchronized boolean book(String bookingId, Instant now) {",
        "        expireHoldIfNeeded(now);",
        "        if (status == SeatStatus.HELD && bookingId.equals(heldByBookingId)) {",
        "            status = SeatStatus.BOOKED;",
        "            holdExpiresAt = null;",
        "            return true;",
        "        }",
        "        return false;",
        "    }",
        "",
        "    public synchronized boolean release(String bookingId) {",
        "        if (status == SeatStatus.AVAILABLE) {",
        "            return false;",
        "        }",
        "        if (heldByBookingId != null && !heldByBookingId.equals(bookingId)) {",
        "            return false;",
        "        }",
        "        status = SeatStatus.AVAILABLE;",
        "        heldByBookingId = null;",
        "        holdExpiresAt = null;",
        "        return true;",
        "    }",
        "",
        "    private void expireHoldIfNeeded(Instant now) {",
        "        if (status == SeatStatus.HELD && holdExpiresAt != null && !now.isBefore(holdExpiresAt)) {",
        "            status = SeatStatus.AVAILABLE;",
        "            heldByBookingId = null;",
        "            holdExpiresAt = null;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Booking.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.time.Instant;",
        "",
        "enum BookingStatus {",
        "    DRAFT,",
        "    HELD,",
        "    CONFIRMED,",
        "    CANCELLED,",
        "    EXPIRED",
        "}",
        "",
        "public class Booking {",
        "    private final String id;",
        "    private final String passengerName;",
        "    private final Flight flight;",
        "    private final Seat seat;",
        "    private final Instant createdAt;",
        "    private Instant holdExpiresAt;",
        "    private long chargedAmountCents;",
        "    private BookingState state = new DraftState();",
        "",
        "    public Booking(String id, String passengerName, Flight flight, Seat seat, Instant createdAt) {",
        "        this.id = id;",
        "        this.passengerName = passengerName;",
        "        this.flight = flight;",
        "        this.seat = seat;",
        "        this.createdAt = createdAt;",
        "    }",
        "",
        "    public synchronized void hold(Duration holdFor, Instant now) {",
        "        state.hold(this, holdFor, now);",
        "    }",
        "",
        "    public synchronized void confirm(long chargedAmountCents, Instant now) {",
        "        state.confirm(this, chargedAmountCents, now);",
        "    }",
        "",
        "    public synchronized void cancel(Instant now) {",
        "        state.cancel(this, now);",
        "    }",
        "",
        "    public synchronized void expireIfNeeded(Instant now) {",
        "        state.expireIfNeeded(this, now);",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getPassengerName() {",
        "        return passengerName;",
        "    }",
        "",
        "    public Flight getFlight() {",
        "        return flight;",
        "    }",
        "",
        "    public Seat getSeat() {",
        "        return seat;",
        "    }",
        "",
        "    public Instant getCreatedAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public synchronized BookingStatus getStatus() {",
        "        return state.status();",
        "    }",
        "",
        "    public synchronized long getChargedAmountCents() {",
        "        return chargedAmountCents;",
        "    }",
        "",
        "    public synchronized String itinerarySummary() {",
        "        return id + \" \" + passengerName + \" \" + flight.getFlightNumber()",
        "                + \" \" + flight.getOrigin() + \"-\" + flight.getDestination()",
        "                + \" seat \" + seat.getSeatNumber() + \" status \" + getStatus();",
        "    }",
        "",
        "    void markHeld(Instant holdExpiresAt) {",
        "        this.holdExpiresAt = holdExpiresAt;",
        "        this.state = new HeldState();",
        "    }",
        "",
        "    void markConfirmed(long chargedAmountCents) {",
        "        this.chargedAmountCents = chargedAmountCents;",
        "        this.holdExpiresAt = null;",
        "        this.state = new ConfirmedState();",
        "    }",
        "",
        "    void markCancelled() {",
        "        this.holdExpiresAt = null;",
        "        this.state = new CancelledState();",
        "    }",
        "",
        "    void markExpired() {",
        "        this.holdExpiresAt = null;",
        "        this.state = new ExpiredState();",
        "    }",
        "",
        "    boolean isHoldExpired(Instant now) {",
        "        return holdExpiresAt != null && !now.isBefore(holdExpiresAt);",
        "    }",
        "",
        "    boolean holdSeat(Duration holdFor, Instant now) {",
        "        return flight.holdSeat(seat.getSeatNumber(), id, holdFor, now);",
        "    }",
        "",
        "    boolean confirmSeat(Instant now) {",
        "        return flight.confirmSeat(seat.getSeatNumber(), id, now);",
        "    }",
        "",
        "    void releaseSeat() {",
        "        flight.releaseSeat(seat.getSeatNumber(), id);",
        "    }",
        "}",
        "",
        "interface BookingState {",
        "    BookingStatus status();",
        "",
        "    default void hold(Booking booking, Duration holdFor, Instant now) {",
        "        throw new IllegalStateException(\"Cannot hold from \" + status());",
        "    }",
        "",
        "    default void confirm(Booking booking, long chargedAmountCents, Instant now) {",
        "        throw new IllegalStateException(\"Cannot confirm from \" + status());",
        "    }",
        "",
        "    default void cancel(Booking booking, Instant now) {",
        "        throw new IllegalStateException(\"Cannot cancel from \" + status());",
        "    }",
        "",
        "    default void expireIfNeeded(Booking booking, Instant now) {",
        "    }",
        "}",
        "",
        "class DraftState implements BookingState {",
        "    public BookingStatus status() {",
        "        return BookingStatus.DRAFT;",
        "    }",
        "",
        "    public void hold(Booking booking, Duration holdFor, Instant now) {",
        "        if (!booking.holdSeat(holdFor, now)) {",
        "            throw new IllegalStateException(\"Seat is not available\");",
        "        }",
        "        booking.markHeld(now.plus(holdFor));",
        "    }",
        "}",
        "",
        "class HeldState implements BookingState {",
        "    public BookingStatus status() {",
        "        return BookingStatus.HELD;",
        "    }",
        "",
        "    public void confirm(Booking booking, long chargedAmountCents, Instant now) {",
        "        if (booking.isHoldExpired(now)) {",
        "            booking.releaseSeat();",
        "            booking.markExpired();",
        "            throw new IllegalStateException(\"Hold expired\");",
        "        }",
        "        if (!booking.confirmSeat(now)) {",
        "            throw new IllegalStateException(\"Seat could not be confirmed\");",
        "        }",
        "        booking.markConfirmed(chargedAmountCents);",
        "    }",
        "",
        "    public void cancel(Booking booking, Instant now) {",
        "        booking.releaseSeat();",
        "        booking.markCancelled();",
        "    }",
        "",
        "    public void expireIfNeeded(Booking booking, Instant now) {",
        "        if (booking.isHoldExpired(now)) {",
        "            booking.releaseSeat();",
        "            booking.markExpired();",
        "        }",
        "    }",
        "}",
        "",
        "class ConfirmedState implements BookingState {",
        "    public BookingStatus status() {",
        "        return BookingStatus.CONFIRMED;",
        "    }",
        "",
        "    public void cancel(Booking booking, Instant now) {",
        "        booking.releaseSeat();",
        "        booking.markCancelled();",
        "    }",
        "}",
        "",
        "class CancelledState implements BookingState {",
        "    public BookingStatus status() {",
        "        return BookingStatus.CANCELLED;",
        "    }",
        "",
        "    public void cancel(Booking booking, Instant now) {",
        "    }",
        "}",
        "",
        "class ExpiredState implements BookingState {",
        "    public BookingStatus status() {",
        "        return BookingStatus.EXPIRED;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PricingStrategy.java",
      language: "java",
      content: [
        "import java.util.EnumMap;",
        "import java.util.Map;",
        "",
        "public interface PricingStrategy {",
        "    Money price(Flight flight, Seat seat);",
        "}",
        "",
        "class ClassBasedPricingStrategy implements PricingStrategy {",
        "    private final Map<CabinClass, Long> baseFareCents = new EnumMap<>(CabinClass.class);",
        "",
        "    public ClassBasedPricingStrategy(long economyFareCents) {",
        "        baseFareCents.put(CabinClass.ECONOMY, economyFareCents);",
        "        baseFareCents.put(CabinClass.PREMIUM_ECONOMY, economyFareCents * 3 / 2);",
        "        baseFareCents.put(CabinClass.BUSINESS, economyFareCents * 3);",
        "        baseFareCents.put(CabinClass.FIRST, economyFareCents * 5);",
        "    }",
        "",
        "    public Money price(Flight flight, Seat seat) {",
        "        long base = baseFareCents.get(seat.getCabinClass());",
        "        int remaining = flight.availableSeats(seat.getCabinClass(), java.time.Instant.now()).size();",
        "        long demandAdjustment = Math.max(0, 5 - remaining) * 500L;",
        "        return Money.ofCents(base + demandAdjustment);",
        "    }",
        "}",
        "",
        "final class Money {",
        "    private final long cents;",
        "",
        "    private Money(long cents) {",
        "        if (cents < 0) {",
        "            throw new IllegalArgumentException(\"Money cannot be negative\");",
        "        }",
        "        this.cents = cents;",
        "    }",
        "",
        "    public static Money ofCents(long cents) {",
        "        return new Money(cents);",
        "    }",
        "",
        "    public long getCents() {",
        "        return cents;",
        "    }",
        "",
        "    public String toString() {",
        "        return String.format(\"$%.2f\", cents / 100.0);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "SearchService.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.time.LocalDate;",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "",
        "public class SearchService {",
        "    public List<Flight> search(",
        "            List<Flight> flights,",
        "            String origin,",
        "            String destination,",
        "            LocalDate travelDate,",
        "            CabinClass cabinClass,",
        "            Instant now) {",
        "        List<Flight> result = new ArrayList<>();",
        "        for (Flight flight : flights) {",
        "            if (flight.matches(origin, destination, travelDate)",
        "                    && !flight.availableSeats(cabinClass, now).isEmpty()) {",
        "                result.add(flight);",
        "            }",
        "        }",
        "        return result;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ReservationService.java",
      language: "java",
      content: [
        "import java.time.Clock;",
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.concurrent.atomic.AtomicLong;",
        "",
        "public class ReservationService {",
        "    private final List<Flight> flights;",
        "    private final PricingStrategy pricingStrategy;",
        "    private final Duration holdDuration;",
        "    private final Clock clock;",
        "    private final Map<String, Booking> bookings = new LinkedHashMap<>();",
        "    private final List<BookingObserver> observers = new ArrayList<>();",
        "    private final AtomicLong sequence = new AtomicLong(1000);",
        "",
        "    public ReservationService(",
        "            List<Flight> flights,",
        "            PricingStrategy pricingStrategy,",
        "            Duration holdDuration,",
        "            Clock clock) {",
        "        this.flights = new ArrayList<>(flights);",
        "        this.pricingStrategy = pricingStrategy;",
        "        this.holdDuration = holdDuration;",
        "        this.clock = clock;",
        "    }",
        "",
        "    public synchronized void addObserver(BookingObserver observer) {",
        "        observers.add(observer);",
        "    }",
        "",
        "    public synchronized Booking holdSeat(String flightNumber, String seatNumber, String passengerName) {",
        "        Flight flight = findFlight(flightNumber);",
        "        Seat seat = flight.findSeat(seatNumber)",
        "                .orElseThrow(() -> new IllegalArgumentException(\"Unknown seat \" + seatNumber));",
        "        String pnr = \"PNR\" + sequence.incrementAndGet();",
        "        Booking booking = createBooking(pnr, passengerName, flight, seat, clock.instant());",
        "        booking.hold(holdDuration, clock.instant());",
        "        bookings.put(booking.getId(), booking);",
        "        notifyObservers(booking, \"HELD\");",
        "        return booking;",
        "    }",
        "",
        "    protected Booking createBooking(String pnr, String passengerName, Flight flight, Seat seat, Instant now) {",
        "        return new Booking(pnr, passengerName, flight, seat, now);",
        "    }",
        "",
        "    public synchronized Money confirm(String pnr) {",
        "        Booking booking = getBooking(pnr);",
        "        Instant now = clock.instant();",
        "        booking.expireIfNeeded(now);",
        "        if (booking.getStatus() != BookingStatus.HELD) {",
        "            throw new IllegalStateException(\"Only held bookings can be confirmed\");",
        "        }",
        "        Money fare = pricingStrategy.price(booking.getFlight(), booking.getSeat());",
        "        booking.confirm(fare.getCents(), now);",
        "        notifyObservers(booking, \"CONFIRMED\");",
        "        return fare;",
        "    }",
        "",
        "    public synchronized void cancel(String pnr) {",
        "        Booking booking = getBooking(pnr);",
        "        booking.cancel(clock.instant());",
        "        notifyObservers(booking, \"CANCELLED\");",
        "    }",
        "",
        "    public synchronized void expireHeldBookings() {",
        "        Instant now = clock.instant();",
        "        for (Booking booking : bookings.values()) {",
        "            BookingStatus before = booking.getStatus();",
        "            booking.expireIfNeeded(now);",
        "            if (before != booking.getStatus() && booking.getStatus() == BookingStatus.EXPIRED) {",
        "                notifyObservers(booking, \"EXPIRED\");",
        "            }",
        "        }",
        "    }",
        "",
        "    private Booking getBooking(String pnr) {",
        "        Booking booking = bookings.get(pnr);",
        "        if (booking == null) {",
        "            throw new IllegalArgumentException(\"Unknown PNR \" + pnr);",
        "        }",
        "        return booking;",
        "    }",
        "",
        "    private Flight findFlight(String flightNumber) {",
        "        for (Flight flight : flights) {",
        "            if (flight.getFlightNumber().equalsIgnoreCase(flightNumber)) {",
        "                return flight;",
        "            }",
        "        }",
        "        throw new IllegalArgumentException(\"Unknown flight \" + flightNumber);",
        "    }",
        "",
        "    private void notifyObservers(Booking booking, String eventName) {",
        "        for (BookingObserver observer : observers) {",
        "            observer.onBookingEvent(booking, eventName);",
        "        }",
        "    }",
        "}",
        "",
        "interface BookingObserver {",
        "    void onBookingEvent(Booking booking, String eventName);",
        "}",
        "",
        "class ConsoleBookingObserver implements BookingObserver {",
        "    public void onBookingEvent(Booking booking, String eventName) {",
        "        System.out.println(eventName + \" \" + booking.itinerarySummary());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.time.Clock;",
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.time.LocalDate;",
        "import java.time.LocalDateTime;",
        "import java.util.Arrays;",
        "import java.util.List;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Flight flight = new Flight(",
        "                \"AI101\",",
        "                \"DEL\",",
        "                \"BLR\",",
        "                LocalDateTime.of(2026, 8, 10, 9, 30));",
        "        flight.addSeat(\"1A\", CabinClass.FIRST);",
        "        flight.addSeat(\"2A\", CabinClass.BUSINESS);",
        "        flight.addSeat(\"2B\", CabinClass.BUSINESS);",
        "        flight.addSeat(\"10A\", CabinClass.ECONOMY);",
        "        flight.addSeat(\"10B\", CabinClass.ECONOMY);",
        "",
        "        List<Flight> flights = Arrays.asList(flight);",
        "        SearchService searchService = new SearchService();",
        "        List<Flight> matches = searchService.search(",
        "                flights,",
        "                \"DEL\",",
        "                \"BLR\",",
        "                LocalDate.of(2026, 8, 10),",
        "                CabinClass.BUSINESS,",
        "                Instant.now());",
        "        System.out.println(\"Flights with business seats: \" + matches.size());",
        "",
        "        ReservationService reservationService = new ReservationService(",
        "                flights,",
        "                new ClassBasedPricingStrategy(6000),",
        "                Duration.ofMinutes(10),",
        "                Clock.systemUTC());",
        "        reservationService.addObserver(new ConsoleBookingObserver());",
        "",
        "        Booking booking = reservationService.holdSeat(\"AI101\", \"2A\", \"Maya Rao\");",
        "        Money charged = reservationService.confirm(booking.getId());",
        "        System.out.println(\"Charged \" + charged + \" for \" + booking.getId());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Flight",
      detailMD:
        "Owns the seat map for one scheduled flight. Its synchronized methods give the reservation flow a safe boundary for finding available seats, placing holds, confirming holds, releasing seats, and reporting remaining inventory by cabin class.",
    },
    {
      className: "Seat",
      detailMD:
        "The smallest inventory unit. It knows its cabin class and state, stores the PNR that owns a hold, expires stale holds on access, and synchronizes hold/book/release so one seat cannot be sold twice.",
    },
    {
      className: "Booking",
      detailMD:
        "The PNR and itinerary object. It delegates lifecycle behavior to **BookingState** implementations, ties passenger to flight and seat, records the charged fare, and exposes a concise itinerary summary.",
    },
    {
      className: "PricingStrategy",
      detailMD:
        "The fare policy seam. **ClassBasedPricingStrategy** calculates cabin-class fares and a simple demand adjustment, while **Money** keeps fare values explicit in cents.",
    },
    {
      className: "SearchService",
      detailMD:
        "The read-side service. It filters candidate flights by route, date, cabin class, and current availability without creating holds or changing booking state.",
    },
    {
      className: "ReservationService",
      detailMD:
        "The application boundary for lifecycle operations. It creates PNRs via a factory method, stores bookings, confirms prices through the strategy, expires holds, and notifies observers after state changes.",
    },
    {
      className: "Main",
      detailMD:
        "A small executable demo that builds a flight, searches business-class inventory, holds a selected seat, confirms the PNR, and prints observer notifications plus the charged fare.",
    },
  ],

  dryRun: {
    inputMD:
      "Flight **AI101 DEL to BLR** has seats **2A BUSINESS**, **2B BUSINESS**, and **10A ECONOMY**. Hold duration is 10 minutes. Passenger Maya selects seat **2A** and confirms before the hold expires.",
    columns: ["Step", "Action", "Seat 2A state", "Booking status", "Result"],
    rows: [
      ["1", "search DEL to BLR for BUSINESS", "AVAILABLE", "none", "AI101 returned because 2A and 2B are available"],
      ["2", "holdSeat AI101 2A Maya", "HELD by PNR1001", "HELD", "PNR1001 created with expiry at now plus 10 minutes"],
      ["3", "second passenger tries holdSeat AI101 2A", "HELD by PNR1001", "none", "Rejected because the seat is not available"],
      ["4", "confirm PNR1001", "BOOKED by PNR1001", "CONFIRMED", "Pricing strategy charges business fare and observers are notified"],
      ["5", "search BUSINESS again", "BOOKED", "CONFIRMED", "AI101 still has 2B, but 2A is no longer counted as available"],
    ],
    narrativeMD:
      "The key moment is step 2: the seat and PNR become linked by the same id. Step 3 proves the lock works, and step 4 proves confirmation books only the seat held by that PNR.",
  },

  complexity: [
    {
      operation: "search flights",
      time: "O(F × S)",
      space: "O(R)",
      note: "F flights scanned, S seats checked per matching flight, R returned flights.",
    },
    {
      operation: "hold selected seat",
      time: "O(1)",
      space: "O(1)",
      note: "A seat lookup by seat number followed by a synchronized state change.",
    },
    {
      operation: "confirm booking",
      time: "O(S)",
      space: "O(1)",
      note: "The sample pricing strategy reads remaining seats in the cabin. With cached counts this becomes O(1).",
    },
    {
      operation: "cancel booking",
      time: "O(1)",
      space: "O(1)",
      note: "Map lookup, state transition, and seat release.",
    },
    {
      operation: "expire held bookings",
      time: "O(B)",
      space: "O(1)",
      note: "B active bookings scanned by a scheduled sweeper.",
    },
  ],
  complexityNotesMD:
    "The base design favors clarity over indexing. Production search usually indexes flights by route/date and keeps per-cabin available-seat counts so search and pricing do not scan every seat.",

  extensibility: [
    {
      label: "Multi-passenger PNR",
      detailMD:
        "Replace the single seat on **Booking** with a list of passenger-seat allocations, and make hold/confirm operate atomically across all selected seats.",
    },
    {
      label: "Multi-leg itinerary",
      detailMD:
        "Introduce an **Itinerary** aggregate containing multiple bookings or flight segments. Confirmation should use a saga or transaction that either confirms every segment or releases all holds.",
    },
    {
      label: "Advanced pricing",
      detailMD:
        "Add strategies for fare families, loyalty discounts, corporate fares, taxes, and promotional codes. ReservationService still asks only for **price**.",
    },
    {
      label: "External notifications",
      detailMD:
        "Implement **BookingObserver** with email, SMS, and event-stream publishers. Keep failures retriable outside the inventory lock.",
    },
    {
      label: "Durable inventory",
      detailMD:
        "Move flights, seats, and bookings behind repositories using database row locks or optimistic versions on seats to preserve hold correctness across app instances.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Class-level inventory hold",
      detailMD:
        "Instead of holding a concrete seat, hold one unit of BUSINESS or ECONOMY inventory and assign the exact seat during check-in.",
      tradeoffsMD:
        "Simplifies seat-map contention and supports airlines that assign later, but it does not satisfy experiences where customers pay for specific seats.",
    },
    {
      name: "Repository-first domain model",
      detailMD:
        "Put **FlightRepository**, **SeatRepository**, and **BookingRepository** at the center and let services load and save aggregates per transaction.",
      tradeoffsMD:
        "More realistic for production and multiple app nodes, but it adds persistence noise to an interview focused on object boundaries.",
    },
    {
      name: "Event-sourced booking lifecycle",
      detailMD:
        "Store events such as SeatHeld, BookingConfirmed, BookingCancelled, and HoldExpired, then rebuild current state from the event stream.",
      tradeoffsMD:
        "Excellent auditability for a regulated travel domain, but more complex than needed for a core LLD answer.",
    },
  ],

  commonMistakes: [
    "Treating a seat hold as a UI flag rather than a domain state protected by the seat object.",
    "Confirming a booking without verifying that the same PNR still owns the held seat.",
    "Representing booking lifecycle with multiple booleans such as paid, cancelled, and expired instead of a state machine.",
    "Hard-coding business and economy prices inside ReservationService instead of using a pricing strategy.",
    "Letting search mutate inventory or create PNRs, which couples the read path to the write path.",
    "Forgetting hold expiry, causing seats to stay blocked after users abandon checkout.",
    "Sending notifications before the state change succeeds, creating false confirmation messages.",
  ],

  followUps: [
    {
      question: "How would you prevent overbooking across multiple application servers?",
      answerMD:
        "Persist each seat with a version or use a database row lock during hold and confirm. The invariant is still one active owner per seat, but the lock moves from the Java object to durable storage.",
    },
    {
      question: "How do you support a passenger booking three seats at once?",
      answerMD:
        "Create an itinerary-level operation that attempts to hold all three seats in a deterministic order. If any hold fails, release the seats already held and fail the whole request.",
    },
    {
      question: "What happens if payment succeeds but confirmation fails?",
      answerMD:
        "Use an idempotent payment authorization followed by confirmation in a transaction or saga. If confirmation cannot book the seat, void or refund the authorization and notify the passenger.",
    },
    {
      question: "Where should waitlisting fit?",
      answerMD:
        "Add a waitlist per flight and cabin class. When a booking cancels or expires, publish an inventory event and let a waitlist service offer the seat to the next eligible traveler.",
    },
    {
      question: "How would dynamic pricing be added?",
      answerMD:
        "Introduce another **PricingStrategy** that uses demand, time-to-departure, fare buckets, and loyalty context. The reservation flow still depends only on the strategy interface.",
    },
  ],

  productionConsiderations: [
    {
      label: "Database locking",
      detailMD:
        "Use row-level locks, compare-and-swap versions, or a strongly consistent inventory service for seat hold and confirm. In-memory synchronization is only correct within one process.",
    },
    {
      label: "Hold expiry worker",
      detailMD:
        "Run a scheduled job that expires stale holds, releases seats, and emits events. The job must be idempotent because retries are normal.",
    },
    {
      label: "Idempotency",
      detailMD:
        "Hold, confirm, cancel, and payment callbacks need idempotency keys so browser retries and webhook retries do not duplicate PNRs or charges.",
    },
    {
      label: "Auditability",
      detailMD:
        "Record who held, confirmed, cancelled, or expired a seat and which fare was applied. Travel systems need a clear audit trail for disputes and support.",
    },
    {
      label: "Operational metrics",
      detailMD:
        "Track hold success rate, expired holds, confirm latency, overbooking prevention failures, notification lag, and inventory mismatch counts.",
    },
  ],

  interviewNotes: [
    "Did the candidate make a concrete seat the unit of inventory and guard its state transitions?",
    "Did they separate read-only search from mutating reservation operations?",
    "Can they explain why a booking state machine is safer than lifecycle booleans?",
    "Did they isolate pricing policy behind Strategy and event side effects behind Observer?",
    "Can they discuss how the in-memory lock maps to database locks or optimistic versions in production?",
  ],

  quiz: [
    {
      question: "Why should a seat hold store the owning PNR id?",
      options: [
        "So confirmation can verify that the same booking owns the held seat",
        "So search results can be sorted alphabetically",
        "So pricing can ignore cabin class",
        "So cancellation can skip state validation",
      ],
      answerIndex: 0,
      explanationMD:
        "The PNR id connects the booking to the seat lock. Confirmation must book only the seat currently held by that same PNR.",
    },
    {
      question: "Which pattern best models Draft, Held, Confirmed, Cancelled, and Expired booking behavior?",
      options: [
        "Factory Method",
        "State",
        "Observer",
        "Adapter",
      ],
      answerIndex: 1,
      explanationMD:
        "State puts lifecycle-specific behavior in separate classes and prevents illegal transitions from being scattered across the service.",
    },
    {
      question: "Why is pricing kept out of ReservationService?",
      options: [
        "Because reservations should never return a fare",
        "Because Java interfaces are required for all services",
        "Because fare policy changes independently from the booking workflow",
        "Because seat inventory cannot be synchronized otherwise",
      ],
      answerIndex: 2,
      explanationMD:
        "That is the Strategy pattern. ReservationService orchestrates lifecycle; PricingStrategy decides the fare.",
    },
    {
      question: "What should happen when a held booking expires before confirmation?",
      options: [
        "The booking should become confirmed automatically",
        "The seat should remain held until an admin releases it",
        "The booking should become expired and the seat should become available",
        "Search should hide the entire flight forever",
      ],
      answerIndex: 2,
      explanationMD:
        "Expired holds must release inventory, otherwise abandoned checkouts permanently reduce sellable seats.",
    },
    {
      question: "Why notify observers after the booking state change succeeds?",
      options: [
        "To make observer code run faster",
        "To avoid sending emails or events for changes that did not actually happen",
        "To let observers mutate the seat before confirmation",
        "To remove the need for a booking repository",
      ],
      answerIndex: 1,
      explanationMD:
        "Observers are side effects. They should see committed domain events, not attempted transitions that may fail.",
    },
  ],

  practiceVariants: [
    {
      title: "Add multi-passenger PNRs",
      detailMD:
        "Let one PNR hold and confirm multiple seats for multiple passengers. Ensure partial failures release every seat already held.",
      difficulty: "Advanced",
    },
    {
      title: "Add fare buckets",
      detailMD:
        "Model limited fare buckets within each cabin class and have the pricing strategy consume the lowest available bucket first.",
      difficulty: "Advanced",
    },
    {
      title: "Add waitlisting",
      detailMD:
        "When a cabin is full, let passengers join a waitlist and receive an observer event when cancellation or expiry releases a seat.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "What is the core inventory invariant?",
      back: "A concrete seat can have at most one active owner: none when available, one PNR while held, and one PNR when booked.",
    },
    {
      front: "Why use State for Booking?",
      back: "It localizes legal lifecycle transitions and prevents invalid jumps such as confirming an expired or cancelled PNR.",
    },
    {
      front: "What does PricingStrategy isolate?",
      back: "Fare calculation by cabin class, demand, promotions, or loyalty rules, independent of reservation orchestration.",
    },
    {
      front: "When should observers be notified?",
      back: "After a durable lifecycle change such as held, confirmed, cancelled, or expired, not before the transition succeeds.",
    },
    {
      front: "What is the interview-critical race condition?",
      back: "Two travelers trying to hold or confirm the same last seat. The hold/book transition must be atomic.",
    },
    {
      front: "How does search differ from reservation?",
      back: "Search reads route/date/cabin availability; reservation mutates seat and booking state by creating holds and confirmations.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Flight owns Seats; Seat owns inventory state; Booking is the PNR; ReservationService orchestrates; SearchService reads; PricingStrategy prices; BookingObserver emits side effects.",
    "",
    "**Patterns:** State for booking lifecycle, Strategy for fares, Observer for booking events, Factory Method for PNR creation.",
    "",
    "**Flow:** search route/date/cabin → select seat → hold seat with PNR and expiry → price selected seat → confirm same PNR → book seat → notify observers.",
    "",
    "**Invariants:** no double booking, confirmation only for the PNR that owns the hold, expired holds release seats, cancelled bookings release seats when allowed.",
    "",
    "**Complexity:** basic search O(F×S), selected-seat hold O(1), cancellation O(1), expiry sweep O(B).",
    "",
    "**Production:** move locks to the database or inventory service, make operations idempotent, expire holds with a worker, and audit every fare and state change.",
  ].join("\n"),

  references: [
    {
      title: "Head First Design Patterns (State, Strategy, Observer, Factory Method)",
      kind: "Book",
      author: "Freeman & Robson",
    },
    {
      title: "Patterns of Enterprise Application Architecture",
      kind: "Book",
      author: "Martin Fowler",
    },
    {
      title: "Effective Java — Item 34 (enums) and Item 78 (synchronize access to shared mutable data)",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
  ],

  relatedProblems: [
    { slug: "movie-booking", note: "The closest sibling: concrete seat selection, temporary holds, and confirmation." },
    { slug: "hotel-management", note: "Another reservation lifecycle with availability, pricing, and cancellation." },
    { slug: "food-delivery", note: "Useful contrast for order lifecycle, status observers, and service orchestration." },
  ],
};
