import type { LLDProblemContent } from "../types";

export const authenticationService: LLDProblemContent = {
  slug: "authentication-service",

  statementMD: [
    "Design the object model for an **Authentication Service** that supports users, credentials, password login, OAuth login, OTP or MFA login, session creation, token validation, and logout.",
    "",
    "The core interview challenge is not a full identity provider or OAuth server. It is the low-level design of a secure, extensible login pipeline where every authentication method plugs into the same flow and tokens are issued, stored, validated, and revoked behind a clean boundary.",
    "",
    "A strong answer separates **credential verification** from **session issuance**, keeps password hashing out of controllers, avoids storing raw tokens, and makes new auth methods additive instead of forcing a risky switch statement through the login path.",
  ].join("\n"),

  businessContextMD: [
    "Authentication sits on the hot path of almost every product. A small design mistake can lock out users, leak credentials, or make future auth methods expensive to add.",
    "",
    "Interviewers use this problem to test whether you can balance product flexibility with security discipline: password auth needs slow salted hashing, OAuth needs provider proof validation, OTP needs short-lived second factors, and every successful login must produce a token that can be validated without exposing raw secrets at rest.",
    "",
    "The design below models the in-memory LLD shape. Production would replace repositories, verifiers, and secret storage with durable and audited integrations, but the boundaries stay the same.",
  ].join("\n"),

  functionalRequirements: [
    "Register and look up users by username or email.",
    "Store password hashes, not plaintext passwords.",
    "Verify password credentials using a dedicated hashing and verification component.",
    "Support pluggable auth strategies for password, OAuth, and OTP or MFA.",
    "Run every login through a consistent pipeline: lookup, account checks, strategy selection, credential verification, and session issuance.",
    "Issue opaque session tokens after successful login.",
    "Validate tokens and reject expired, revoked, or unknown tokens.",
    "Support logout by revoking the active session token.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Security first",
      detailMD:
        "Passwords are handled as character arrays, hashed with per-password salt, and verified with constant-time hash comparison. Raw bearer tokens are returned once and only token hashes are stored.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Adding WebAuthn, SAML, magic links, or device approval should mean adding an **AuthStrategy**, not editing the orchestration flow.",
    },
    {
      label: "Low latency",
      detailMD:
        "User lookup, strategy lookup, and token validation are O(1) map operations in the interview model. Password hashing is intentionally CPU-expensive but bounded.",
    },
    {
      label: "Auditability",
      detailMD:
        "The login pipeline has clear stages where production code can emit structured audit events for success, failure reason class, account lock, token issue, and revoke.",
    },
    {
      label: "Least privilege",
      detailMD:
        "The token service owns token hashing, expiry, validation, and revocation. Login orchestration never reaches into session storage directly.",
    },
  ],

  requirementClarification: [
    {
      question: "Are we designing authorization too?",
      answerMD:
        "No. This design authenticates identity and issues a session. Role checks, permissions, and policy evaluation belong to an RBAC or authorization service layered after token validation.",
    },
    {
      question: "Should OAuth tokens be issued by our service?",
      answerMD:
        "No for the base LLD. We verify a provider proof and link it to a known user identity. Issuing OAuth access tokens to third-party clients is a separate authorization-server design.",
    },
    {
      question: "Do we need persistent storage?",
      answerMD:
        "Use in-memory maps for the interview implementation. Call out where **UserRepository**, **SessionRepository**, and external secret stores would replace them in production.",
    },
    {
      question: "How should MFA interact with password login?",
      answerMD:
        "The base design treats OTP as a separate strategy to show pluggability. In production, it often becomes a second stage after password success, still using the same pipeline and strategy seam.",
    },
    {
      question: "Are tokens JWTs or opaque tokens?",
      answerMD:
        "Use opaque tokens here because secure revocation is simpler. JWTs are a valid alternative when stateless validation is required, but revocation and key rotation become first-class concerns.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class AuthService {",
    "        -Map usersByLogin",
    "        -Map strategies",
    "        -TokenService tokenService",
    "        -LoginHandler pipeline",
    "        +login(Credentials) LoginResponse",
    "        +validate(String) Optional",
    "        +logout(String) void",
    "    }",
    "    class LoginHandler {",
    "        <<abstract>>",
    "        -LoginHandler next",
    "        +handle(LoginContext) void",
    "    }",
    "    class AuthStrategy {",
    "        <<interface>>",
    "        +method() Method",
    "        +authenticate(Credentials, User) AuthResult",
    "    }",
    "    class PasswordAuthStrategy {",
    "        +hashPassword(charArray) String",
    "        +verifyPassword(charArray, String) boolean",
    "    }",
    "    class Credentials {",
    "        +password(String, charArray) Credentials",
    "        +oauth(String, String, String, charArray) Credentials",
    "        +otp(String, charArray) Credentials",
    "    }",
    "    class User {",
    "        -String id",
    "        -String username",
    "        -String email",
    "        -String passwordHash",
    "        -String oauthSubject",
    "        -String mfaSecret",
    "    }",
    "    class TokenService {",
    "        <<singleton>>",
    "        -Map sessionsByTokenHash",
    "        +getInstance() TokenService",
    "        +issue(String) TokenBundle",
    "        +validate(String) Optional",
    "        +revoke(String) void",
    "    }",
    "    class Session {",
    "        -String id",
    "        -String userId",
    "        -String tokenHash",
    "        -Instant expiresAt",
    "        +isValidAt(Instant) boolean",
    "        +revoke() void",
    "    }",
    "    AuthService o-- LoginHandler",
    "    AuthService ..> AuthStrategy",
    "    AuthService ..> TokenService",
    "    AuthService ..> Credentials",
    "    AuthService ..> User",
    "    AuthStrategy <|.. PasswordAuthStrategy",
    "    TokenService --> Session",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service coordinates a chain of login handlers, delegates credential proof to an **AuthStrategy**, and delegates token lifecycle to the singleton **TokenService**.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Client",
    "    participant Service as AuthService",
    "    participant Lookup as UserLookupHandler",
    "    participant Select as StrategySelectionHandler",
    "    participant Strategy as AuthStrategy",
    "    participant Tokens as TokenService",
    "    Client->>Service: login(credentials)",
    "    Service->>Lookup: find user by login id",
    "    Lookup-->>Service: User",
    "    Service->>Select: choose strategy by method",
    "    Select-->>Service: AuthStrategy",
    "    Service->>Strategy: authenticate(credentials, user)",
    "    Strategy-->>Service: success",
    "    Service->>Tokens: issue(userId)",
    "    Tokens-->>Service: raw token plus Session",
    "    Service-->>Client: LoginResponse",
    "    Note over Client,Tokens: later request",
    "    Client->>Service: validate(raw token)",
    "    Service->>Tokens: validate(raw token hash)",
    "    Tokens-->>Service: Optional session",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Every auth method flows through the same stages. Only the strategy changes, while session creation and validation remain centralized.",

  entities: [
    {
      name: "User",
      responsibilityMD:
        "Represents an account identity and the authentication material linked to it: password hash, OAuth provider identity, MFA secret, and account lock state.",
      attributes: ["id", "username", "email", "passwordHash", "oauthProvider", "oauthSubject", "mfaSecret", "locked"],
    },
    {
      name: "Credentials",
      responsibilityMD:
        "Immutable login evidence supplied by the client. Static factory methods construct password, OAuth, or OTP credentials while keeping secrets as character arrays.",
      attributes: ["method", "loginId", "secret", "provider", "externalSubject"],
    },
    {
      name: "AuthStrategy",
      responsibilityMD:
        "Strategy interface for credential verification. Password, OAuth, and OTP implementations expose the same **authenticate** contract.",
      attributes: ["method()", "authenticate(credentials, user)"],
    },
    {
      name: "PasswordAuthStrategy",
      responsibilityMD:
        "Owns password hashing and verification using salted PBKDF2. It never returns the stored hash and compares derived hashes in constant time.",
      attributes: ["hashPassword", "verifyPassword", "authenticate"],
    },
    {
      name: "Session",
      responsibilityMD:
        "Represents an issued login session with a token hash, issued time, expiry time, and revocation flag.",
      attributes: ["id", "userId", "tokenHash", "issuedAt", "expiresAt", "revoked"],
    },
    {
      name: "TokenService",
      responsibilityMD:
        "Singleton boundary for token generation, token hashing, validation, expiry checks, and revocation. It stores token hashes instead of raw bearer tokens.",
      attributes: ["sessionsByTokenHash", "issue", "validate", "revoke"],
    },
    {
      name: "AuthService",
      responsibilityMD:
        "Facade over the login pipeline. It indexes users, registers strategies, runs chain handlers, issues sessions, validates tokens, and logs users out.",
      attributes: ["usersByLogin", "strategies", "pipeline", "tokenService"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**AuthStrategy** makes password, OAuth, and OTP verification interchangeable. A new method such as WebAuthn adds a class implementing **authenticate** and registers it by method.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**Credentials.password**, **Credentials.oauth**, **Credentials.otp**, and **AuthService.withDefaultStrategies** hide construction details and produce valid objects for common login flows.",
    },
    {
      name: "Chain of Responsibility",
      whyMD:
        "The login flow is modeled as handlers for lookup, account status, strategy selection, credential verification, and session issue. Each stage does one job and passes the context forward.",
    },
    {
      name: "Singleton",
      whyMD:
        "**TokenService.getInstance** provides one process-wide token authority for issuing, validating, and revoking opaque session tokens in the demo design.",
    },
  ],

  designSteps: [
    {
      title: "Separate identity from proof",
      detailMD:
        "**User** stores account identity and linked auth material, while **Credentials** represents one login attempt. This prevents password, OAuth, and OTP data from leaking into unrelated service methods.",
      code: [
        "public static Credentials password(String username, char[] password) {",
        "    return new Credentials(Method.PASSWORD, username, password, null, null);",
        "}",
        "",
        "public static Credentials oauth(String email, String provider, String subject, char[] proof) {",
        "    return new Credentials(Method.OAUTH, email, proof, provider, subject);",
        "}",
      ].join("\n"),
    },
    {
      title: "Put auth method variability behind a strategy",
      detailMD:
        "The login pipeline asks a strategy to authenticate a credential against a user. It does not know whether the proof is a password, provider token, or one-time code.",
      code: [
        "public interface AuthStrategy {",
        "    Credentials.Method method();",
        "    AuthResult authenticate(Credentials credentials, User user);",
        "}",
      ].join("\n"),
    },
    {
      title: "Hash passwords in the password strategy only",
      detailMD:
        "**PasswordAuthStrategy** owns salt generation, PBKDF2 derivation, encoded hash format, and constant-time verification. Controllers and services never manipulate password hashes directly.",
      code: [
        "public AuthResult authenticate(Credentials credentials, User user) {",
        "    String storedHash = user.getPasswordHash().orElse(null);",
        "    if (storedHash == null) {",
        "        return AuthResult.failure(\"password not configured\");",
        "    }",
        "    return verifyPassword(credentials.copySecret(), storedHash)",
        "        ? AuthResult.success()",
        "        : AuthResult.failure(\"password rejected\");",
        "}",
      ].join("\n"),
    },
    {
      title: "Run login as a chain of small handlers",
      detailMD:
        "Lookup, account status, strategy selection, verification, and session issue are separate chain stages. This makes rate limiting, risk scoring, device checks, and audit events easy to insert.",
    },
    {
      title: "Issue opaque tokens and store only token hashes",
      detailMD:
        "**TokenService.issue** returns the raw token once, stores its SHA-256 hash with the session, and validates future requests by hashing the presented token. Expiry and revocation stay inside the token boundary.",
      code: [
        "String rawToken = randomToken();",
        "String tokenHash = hashToken(rawToken);",
        "Session session = new Session(sessionId, userId, tokenHash, now, now.plus(sessionTtl));",
        "sessionsByTokenHash.put(tokenHash, session);",
      ].join("\n"),
    },
    {
      title: "Keep production integrations replaceable",
      detailMD:
        "The in-memory maps demonstrate ownership. In production, swap in repositories, provider SDK adapters, a KMS-backed secret store, and distributed session storage without changing **AuthStrategy** or **AuthService.login**.",
    },
  ],

  implementation: [
    {
      filename: "User.java",
      language: "java",
      content: [
        "import java.util.Locale;",
        "import java.util.Optional;",
        "",
        "public final class User {",
        "    private final String id;",
        "    private final String username;",
        "    private final String email;",
        "    private final String passwordHash;",
        "    private final String oauthProvider;",
        "    private final String oauthSubject;",
        "    private final String mfaSecret;",
        "    private final boolean locked;",
        "",
        "    private User(String id, String username, String email, String passwordHash, String oauthProvider, String oauthSubject, String mfaSecret, boolean locked) {",
        "        this.id = requireText(id, \"id\");",
        "        this.username = requireText(username, \"username\");",
        "        this.email = normalizeEmail(email);",
        "        this.passwordHash = optionalText(passwordHash);",
        "        this.oauthProvider = optionalText(oauthProvider);",
        "        this.oauthSubject = optionalText(oauthSubject);",
        "        this.mfaSecret = optionalText(mfaSecret);",
        "        this.locked = locked;",
        "    }",
        "",
        "    public static User passwordUser(String id, String username, String email, String passwordHash) {",
        "        return new User(id, username, email, requireText(passwordHash, \"passwordHash\"), null, null, null, false);",
        "    }",
        "",
        "    public static User oauthUser(String id, String username, String email, String provider, String subject) {",
        "        return new User(id, username, email, null, requireText(provider, \"provider\"), requireText(subject, \"subject\"), null, false);",
        "    }",
        "",
        "    public User withOAuth(String provider, String subject) {",
        "        return new User(id, username, email, passwordHash, requireText(provider, \"provider\"), requireText(subject, \"subject\"), mfaSecret, locked);",
        "    }",
        "",
        "    public User withMfa(String seed) {",
        "        return new User(id, username, email, passwordHash, oauthProvider, oauthSubject, requireText(seed, \"seed\"), locked);",
        "    }",
        "",
        "    public User locked() {",
        "        return new User(id, username, email, passwordHash, oauthProvider, oauthSubject, mfaSecret, true);",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getUsername() {",
        "        return username;",
        "    }",
        "",
        "    public String getEmail() {",
        "        return email;",
        "    }",
        "",
        "    public Optional<String> getPasswordHash() {",
        "        return Optional.ofNullable(passwordHash);",
        "    }",
        "",
        "    public Optional<String> getMfaSecret() {",
        "        return Optional.ofNullable(mfaSecret);",
        "    }",
        "",
        "    public boolean isLocked() {",
        "        return locked;",
        "    }",
        "",
        "    public boolean hasOauthIdentity(String provider, String subject) {",
        "        return oauthProvider != null",
        "            && oauthSubject != null",
        "            && oauthProvider.equalsIgnoreCase(provider)",
        "            && oauthSubject.equals(subject);",
        "    }",
        "",
        "    private static String normalizeEmail(String email) {",
        "        return requireText(email, \"email\").toLowerCase(Locale.ROOT);",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "",
        "    private static String optionalText(String value) {",
        "        if (value == null || value.isBlank()) {",
        "            return null;",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Credentials.java",
      language: "java",
      content: [
        "import java.util.Arrays;",
        "import java.util.Locale;",
        "import java.util.Objects;",
        "",
        "public final class Credentials {",
        "    public enum Method {",
        "        PASSWORD,",
        "        OAUTH,",
        "        OTP",
        "    }",
        "",
        "    private final Method method;",
        "    private final String loginId;",
        "    private final char[] secret;",
        "    private final String provider;",
        "    private final String externalSubject;",
        "",
        "    private Credentials(Method method, String loginId, char[] secret, String provider, String externalSubject) {",
        "        this.method = Objects.requireNonNull(method, \"method\");",
        "        this.loginId = normalizeLogin(loginId);",
        "        this.secret = requireSecret(secret, \"secret\");",
        "        this.provider = optionalText(provider);",
        "        this.externalSubject = optionalText(externalSubject);",
        "    }",
        "",
        "    public static Credentials password(String username, char[] password) {",
        "        return new Credentials(Method.PASSWORD, username, password, null, null);",
        "    }",
        "",
        "    public static Credentials oauth(String email, String provider, String externalSubject, char[] providerProof) {",
        "        return new Credentials(Method.OAUTH, email, providerProof, provider, externalSubject);",
        "    }",
        "",
        "    public static Credentials otp(String username, char[] oneTimeCode) {",
        "        return new Credentials(Method.OTP, username, oneTimeCode, null, null);",
        "    }",
        "",
        "    public Method getMethod() {",
        "        return method;",
        "    }",
        "",
        "    public String getLoginId() {",
        "        return loginId;",
        "    }",
        "",
        "    public String getProvider() {",
        "        return provider;",
        "    }",
        "",
        "    public String getExternalSubject() {",
        "        return externalSubject;",
        "    }",
        "",
        "    public char[] copySecret() {",
        "        return secret.clone();",
        "    }",
        "",
        "    public void clear() {",
        "        Arrays.fill(secret, '\\0');",
        "    }",
        "",
        "    private static char[] requireSecret(char[] secret, String fieldName) {",
        "        if (secret == null || secret.length == 0) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return secret.clone();",
        "    }",
        "",
        "    private static String normalizeLogin(String value) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(\"login id is required\");",
        "        }",
        "        return value.trim().toLowerCase(Locale.ROOT);",
        "    }",
        "",
        "    private static String optionalText(String value) {",
        "        if (value == null || value.isBlank()) {",
        "            return null;",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "AuthStrategy.java",
      language: "java",
      content: [
        "import java.util.Arrays;",
        "import java.util.Objects;",
        "",
        "public interface AuthStrategy {",
        "    Credentials.Method method();",
        "",
        "    AuthResult authenticate(Credentials credentials, User user);",
        "",
        "    static AuthStrategy oauth(OAuthVerifier verifier) {",
        "        return new OAuthAuthStrategy(verifier);",
        "    }",
        "",
        "    static AuthStrategy otp(OtpVerifier verifier) {",
        "        return new OtpAuthStrategy(verifier);",
        "    }",
        "",
        "    interface OAuthVerifier {",
        "        boolean verify(String provider, String externalSubject, char[] proof);",
        "    }",
        "",
        "    interface OtpVerifier {",
        "        boolean verify(String seed, char[] code);",
        "    }",
        "",
        "    final class AuthResult {",
        "        private final boolean success;",
        "        private final String reason;",
        "",
        "        private AuthResult(boolean success, String reason) {",
        "            this.success = success;",
        "            this.reason = reason;",
        "        }",
        "",
        "        public static AuthResult success() {",
        "            return new AuthResult(true, \"authenticated\");",
        "        }",
        "",
        "        public static AuthResult failure(String reason) {",
        "            return new AuthResult(false, reason == null || reason.isBlank() ? \"rejected\" : reason);",
        "        }",
        "",
        "        public boolean isSuccess() {",
        "            return success;",
        "        }",
        "",
        "        public String getReason() {",
        "            return reason;",
        "        }",
        "    }",
        "",
        "    final class OAuthAuthStrategy implements AuthStrategy {",
        "        private final OAuthVerifier verifier;",
        "",
        "        private OAuthAuthStrategy(OAuthVerifier verifier) {",
        "            this.verifier = Objects.requireNonNull(verifier, \"verifier\");",
        "        }",
        "",
        "        @Override",
        "        public Credentials.Method method() {",
        "            return Credentials.Method.OAUTH;",
        "        }",
        "",
        "        @Override",
        "        public AuthResult authenticate(Credentials credentials, User user) {",
        "            Objects.requireNonNull(credentials, \"credentials\");",
        "            Objects.requireNonNull(user, \"user\");",
        "            char[] proof = credentials.copySecret();",
        "            try {",
        "                boolean linked = user.hasOauthIdentity(credentials.getProvider(), credentials.getExternalSubject());",
        "                boolean verified = verifier.verify(credentials.getProvider(), credentials.getExternalSubject(), proof);",
        "                return linked && verified ? AuthResult.success() : AuthResult.failure(\"oauth proof rejected\");",
        "            } finally {",
        "                Arrays.fill(proof, '\\0');",
        "            }",
        "        }",
        "    }",
        "",
        "    final class OtpAuthStrategy implements AuthStrategy {",
        "        private final OtpVerifier verifier;",
        "",
        "        private OtpAuthStrategy(OtpVerifier verifier) {",
        "            this.verifier = Objects.requireNonNull(verifier, \"verifier\");",
        "        }",
        "",
        "        @Override",
        "        public Credentials.Method method() {",
        "            return Credentials.Method.OTP;",
        "        }",
        "",
        "        @Override",
        "        public AuthResult authenticate(Credentials credentials, User user) {",
        "            Objects.requireNonNull(credentials, \"credentials\");",
        "            Objects.requireNonNull(user, \"user\");",
        "            String seed = user.getMfaSecret().orElse(null);",
        "            if (seed == null) {",
        "                return AuthResult.failure(\"mfa not configured\");",
        "            }",
        "            char[] code = credentials.copySecret();",
        "            try {",
        "                return verifier.verify(seed, code) ? AuthResult.success() : AuthResult.failure(\"otp rejected\");",
        "            } finally {",
        "                Arrays.fill(code, '\\0');",
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PasswordAuthStrategy.java",
      language: "java",
      content: [
        "import java.security.MessageDigest;",
        "import java.security.NoSuchAlgorithmException;",
        "import java.security.SecureRandom;",
        "import java.security.spec.InvalidKeySpecException;",
        "import java.util.Arrays;",
        "import java.util.Base64;",
        "import java.util.Objects;",
        "import javax.crypto.SecretKeyFactory;",
        "import javax.crypto.spec.PBEKeySpec;",
        "",
        "public final class PasswordAuthStrategy implements AuthStrategy {",
        "    private static final int ITERATIONS = 120_000;",
        "    private static final int KEY_LENGTH = 256;",
        "    private static final int SALT_BYTES = 16;",
        "    private static final SecureRandom RANDOM = new SecureRandom();",
        "",
        "    @Override",
        "    public Credentials.Method method() {",
        "        return Credentials.Method.PASSWORD;",
        "    }",
        "",
        "    @Override",
        "    public AuthStrategy.AuthResult authenticate(Credentials credentials, User user) {",
        "        Objects.requireNonNull(credentials, \"credentials\");",
        "        Objects.requireNonNull(user, \"user\");",
        "        String storedHash = user.getPasswordHash().orElse(null);",
        "        if (storedHash == null) {",
        "            return AuthStrategy.AuthResult.failure(\"password not configured\");",
        "        }",
        "        char[] password = credentials.copySecret();",
        "        try {",
        "            return verifyPassword(password, storedHash) ? AuthStrategy.AuthResult.success() : AuthStrategy.AuthResult.failure(\"password rejected\");",
        "        } finally {",
        "            Arrays.fill(password, '\\0');",
        "        }",
        "    }",
        "",
        "    public static String hashPassword(char[] password) {",
        "        Objects.requireNonNull(password, \"password\");",
        "        byte[] salt = new byte[SALT_BYTES];",
        "        RANDOM.nextBytes(salt);",
        "        byte[] hash = pbkdf2(password, salt, ITERATIONS);",
        "        return ITERATIONS + \":\"",
        "            + Base64.getEncoder().encodeToString(salt) + \":\"",
        "            + Base64.getEncoder().encodeToString(hash);",
        "    }",
        "",
        "    public static boolean verifyPassword(char[] password, String encodedHash) {",
        "        Objects.requireNonNull(password, \"password\");",
        "        if (encodedHash == null || encodedHash.isBlank()) {",
        "            return false;",
        "        }",
        "        byte[] actual = null;",
        "        try {",
        "            String[] parts = encodedHash.split(\":\");",
        "            if (parts.length != 3) {",
        "                return false;",
        "            }",
        "            int iterations = Integer.parseInt(parts[0]);",
        "            byte[] salt = Base64.getDecoder().decode(parts[1]);",
        "            byte[] expected = Base64.getDecoder().decode(parts[2]);",
        "            actual = pbkdf2(password, salt, iterations);",
        "            return MessageDigest.isEqual(expected, actual);",
        "        } catch (IllegalArgumentException ex) {",
        "            return false;",
        "        } finally {",
        "            if (actual != null) {",
        "                Arrays.fill(actual, (byte) 0);",
        "            }",
        "        }",
        "    }",
        "",
        "    private static byte[] pbkdf2(char[] password, byte[] salt, int iterations) {",
        "        PBEKeySpec spec = new PBEKeySpec(password, salt, iterations, KEY_LENGTH);",
        "        try {",
        "            return SecretKeyFactory.getInstance(\"PBKDF2WithHmacSHA256\").generateSecret(spec).getEncoded();",
        "        } catch (NoSuchAlgorithmException | InvalidKeySpecException ex) {",
        "            throw new IllegalStateException(\"password hashing unavailable\", ex);",
        "        } finally {",
        "            spec.clearPassword();",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Session.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.Objects;",
        "",
        "public final class Session {",
        "    private final String id;",
        "    private final String userId;",
        "    private final String tokenHash;",
        "    private final Instant issuedAt;",
        "    private final Instant expiresAt;",
        "    private volatile boolean revoked;",
        "",
        "    public Session(String id, String userId, String tokenHash, Instant issuedAt, Instant expiresAt) {",
        "        this.id = requireText(id, \"id\");",
        "        this.userId = requireText(userId, \"userId\");",
        "        this.tokenHash = requireText(tokenHash, \"tokenHash\");",
        "        this.issuedAt = Objects.requireNonNull(issuedAt, \"issuedAt\");",
        "        this.expiresAt = Objects.requireNonNull(expiresAt, \"expiresAt\");",
        "        if (!expiresAt.isAfter(issuedAt)) {",
        "            throw new IllegalArgumentException(\"expiresAt must be after issuedAt\");",
        "        }",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getUserId() {",
        "        return userId;",
        "    }",
        "",
        "    public String getTokenHash() {",
        "        return tokenHash;",
        "    }",
        "",
        "    public Instant getIssuedAt() {",
        "        return issuedAt;",
        "    }",
        "",
        "    public Instant getExpiresAt() {",
        "        return expiresAt;",
        "    }",
        "",
        "    public boolean isRevoked() {",
        "        return revoked;",
        "    }",
        "",
        "    public boolean isValidAt(Instant now) {",
        "        Objects.requireNonNull(now, \"now\");",
        "        return !revoked && now.isBefore(expiresAt);",
        "    }",
        "",
        "    public void revoke() {",
        "        revoked = true;",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "TokenService.java",
      language: "java",
      content: [
        "import java.nio.charset.StandardCharsets;",
        "import java.security.MessageDigest;",
        "import java.security.NoSuchAlgorithmException;",
        "import java.security.SecureRandom;",
        "import java.time.Clock;",
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.Base64;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "import java.util.UUID;",
        "import java.util.concurrent.ConcurrentHashMap;",
        "import java.util.concurrent.ConcurrentMap;",
        "",
        "public final class TokenService {",
        "    private static final TokenService INSTANCE = new TokenService(Clock.systemUTC(), Duration.ofMinutes(30));",
        "",
        "    private final Clock clock;",
        "    private final Duration sessionTtl;",
        "    private final SecureRandom random = new SecureRandom();",
        "    private final ConcurrentMap<String, Session> sessionsByTokenHash = new ConcurrentHashMap<>();",
        "",
        "    private TokenService(Clock clock, Duration sessionTtl) {",
        "        this.clock = Objects.requireNonNull(clock, \"clock\");",
        "        this.sessionTtl = Objects.requireNonNull(sessionTtl, \"sessionTtl\");",
        "        if (sessionTtl.isZero() || sessionTtl.isNegative()) {",
        "            throw new IllegalArgumentException(\"sessionTtl must be positive\");",
        "        }",
        "    }",
        "",
        "    public static TokenService getInstance() {",
        "        return INSTANCE;",
        "    }",
        "",
        "    public static TokenService newIsolatedForTests(Clock clock, Duration sessionTtl) {",
        "        return new TokenService(clock, sessionTtl);",
        "    }",
        "",
        "    public TokenBundle issue(String userId) {",
        "        if (userId == null || userId.isBlank()) {",
        "            throw new IllegalArgumentException(\"userId is required\");",
        "        }",
        "        Instant now = clock.instant();",
        "        String rawToken = randomToken();",
        "        String tokenHash = hashToken(rawToken);",
        "        Session session = new Session(UUID.randomUUID().toString(), userId.trim(), tokenHash, now, now.plus(sessionTtl));",
        "        sessionsByTokenHash.put(tokenHash, session);",
        "        return new TokenBundle(rawToken, session);",
        "    }",
        "",
        "    public Optional<Session> validate(String rawToken) {",
        "        if (rawToken == null || rawToken.isBlank()) {",
        "            return Optional.empty();",
        "        }",
        "        String tokenHash = hashToken(rawToken);",
        "        Session session = sessionsByTokenHash.get(tokenHash);",
        "        if (session == null) {",
        "            return Optional.empty();",
        "        }",
        "        if (!constantTimeEquals(session.getTokenHash(), tokenHash) || !session.isValidAt(clock.instant())) {",
        "            sessionsByTokenHash.remove(tokenHash);",
        "            return Optional.empty();",
        "        }",
        "        return Optional.of(session);",
        "    }",
        "",
        "    public void revoke(String rawToken) {",
        "        if (rawToken == null || rawToken.isBlank()) {",
        "            return;",
        "        }",
        "        String tokenHash = hashToken(rawToken);",
        "        Session session = sessionsByTokenHash.remove(tokenHash);",
        "        if (session != null) {",
        "            session.revoke();",
        "        }",
        "    }",
        "",
        "    private String randomToken() {",
        "        byte[] bytes = new byte[32];",
        "        random.nextBytes(bytes);",
        "        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);",
        "    }",
        "",
        "    private static String hashToken(String rawToken) {",
        "        try {",
        "            byte[] digest = MessageDigest.getInstance(\"SHA-256\").digest(rawToken.getBytes(StandardCharsets.UTF_8));",
        "            return Base64.getEncoder().encodeToString(digest);",
        "        } catch (NoSuchAlgorithmException ex) {",
        "            throw new IllegalStateException(\"token hashing unavailable\", ex);",
        "        }",
        "    }",
        "",
        "    private static boolean constantTimeEquals(String left, String right) {",
        "        return MessageDigest.isEqual(left.getBytes(StandardCharsets.UTF_8), right.getBytes(StandardCharsets.UTF_8));",
        "    }",
        "",
        "    public static final class TokenBundle {",
        "        private final String rawToken;",
        "        private final Session session;",
        "",
        "        private TokenBundle(String rawToken, Session session) {",
        "            this.rawToken = rawToken;",
        "            this.session = session;",
        "        }",
        "",
        "        public String getRawToken() {",
        "            return rawToken;",
        "        }",
        "",
        "        public Session getSession() {",
        "            return session;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "AuthService.java",
      language: "java",
      content: [
        "import java.util.Collection;",
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Locale;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "",
        "public final class AuthService {",
        "    private final Map<String, User> usersByLogin;",
        "    private final Map<Credentials.Method, AuthStrategy> strategies;",
        "    private final TokenService tokenService;",
        "    private final LoginHandler pipeline;",
        "",
        "    public AuthService(Collection<User> users, Collection<AuthStrategy> strategies, TokenService tokenService) {",
        "        this.usersByLogin = indexUsers(users);",
        "        this.strategies = indexStrategies(strategies);",
        "        this.tokenService = Objects.requireNonNull(tokenService, \"tokenService\");",
        "        this.pipeline = new UserLookupHandler(",
        "            new AccountStatusHandler(",
        "                new StrategySelectionHandler(",
        "                    new CredentialVerificationHandler(",
        "                        new SessionIssuingHandler(null)))));",
        "    }",
        "",
        "    public static AuthService withDefaultStrategies(Collection<User> users) {",
        "        return new AuthService(",
        "            users,",
        "            List.of(",
        "                new PasswordAuthStrategy(),",
        "                AuthStrategy.oauth((provider, subject, proof) -> provider != null && subject != null && proof.length > 0),",
        "                AuthStrategy.otp((seed, code) -> seed != null && seed.equals(new String(code)))",
        "            ),",
        "            TokenService.getInstance()",
        "        );",
        "    }",
        "",
        "    public LoginResponse login(Credentials credentials) {",
        "        Objects.requireNonNull(credentials, \"credentials\");",
        "        LoginContext context = new LoginContext(credentials);",
        "        try {",
        "            pipeline.handle(context);",
        "            return new LoginResponse(context.rawToken, context.session);",
        "        } finally {",
        "            credentials.clear();",
        "        }",
        "    }",
        "",
        "    public Optional<Session> validate(String rawToken) {",
        "        return tokenService.validate(rawToken);",
        "    }",
        "",
        "    public void logout(String rawToken) {",
        "        tokenService.revoke(rawToken);",
        "    }",
        "",
        "    private static Map<String, User> indexUsers(Collection<User> users) {",
        "        Objects.requireNonNull(users, \"users\");",
        "        Map<String, User> index = new HashMap<>();",
        "        for (User user : users) {",
        "            putUnique(index, user.getUsername(), user);",
        "            putUnique(index, user.getEmail(), user);",
        "        }",
        "        return Map.copyOf(index);",
        "    }",
        "",
        "    private static void putUnique(Map<String, User> index, String loginId, User user) {",
        "        User previous = index.put(normalize(loginId), user);",
        "        if (previous != null && !previous.getId().equals(user.getId())) {",
        "            throw new IllegalArgumentException(\"duplicate login id: \" + loginId);",
        "        }",
        "    }",
        "",
        "    private static Map<Credentials.Method, AuthStrategy> indexStrategies(Collection<AuthStrategy> strategies) {",
        "        Objects.requireNonNull(strategies, \"strategies\");",
        "        Map<Credentials.Method, AuthStrategy> index = new HashMap<>();",
        "        for (AuthStrategy strategy : strategies) {",
        "            AuthStrategy previous = index.put(strategy.method(), strategy);",
        "            if (previous != null) {",
        "                throw new IllegalArgumentException(\"duplicate strategy: \" + strategy.method());",
        "            }",
        "        }",
        "        return Map.copyOf(index);",
        "    }",
        "",
        "    private static String normalize(String value) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(\"login id is required\");",
        "        }",
        "        return value.trim().toLowerCase(Locale.ROOT);",
        "    }",
        "",
        "    private abstract class LoginHandler {",
        "        private final LoginHandler next;",
        "",
        "        LoginHandler(LoginHandler next) {",
        "            this.next = next;",
        "        }",
        "",
        "        final void handle(LoginContext context) {",
        "            apply(context);",
        "            if (next != null) {",
        "                next.handle(context);",
        "            }",
        "        }",
        "",
        "        abstract void apply(LoginContext context);",
        "    }",
        "",
        "    private final class UserLookupHandler extends LoginHandler {",
        "        UserLookupHandler(LoginHandler next) {",
        "            super(next);",
        "        }",
        "",
        "        @Override",
        "        void apply(LoginContext context) {",
        "            context.user = usersByLogin.get(normalize(context.credentials.getLoginId()));",
        "            if (context.user == null) {",
        "                throw new SecurityException(\"invalid credentials\");",
        "            }",
        "        }",
        "    }",
        "",
        "    private final class AccountStatusHandler extends LoginHandler {",
        "        AccountStatusHandler(LoginHandler next) {",
        "            super(next);",
        "        }",
        "",
        "        @Override",
        "        void apply(LoginContext context) {",
        "            if (context.user.isLocked()) {",
        "                throw new SecurityException(\"account locked\");",
        "            }",
        "        }",
        "    }",
        "",
        "    private final class StrategySelectionHandler extends LoginHandler {",
        "        StrategySelectionHandler(LoginHandler next) {",
        "            super(next);",
        "        }",
        "",
        "        @Override",
        "        void apply(LoginContext context) {",
        "            context.strategy = strategies.get(context.credentials.getMethod());",
        "            if (context.strategy == null) {",
        "                throw new IllegalArgumentException(\"unsupported auth method: \" + context.credentials.getMethod());",
        "            }",
        "        }",
        "    }",
        "",
        "    private final class CredentialVerificationHandler extends LoginHandler {",
        "        CredentialVerificationHandler(LoginHandler next) {",
        "            super(next);",
        "        }",
        "",
        "        @Override",
        "        void apply(LoginContext context) {",
        "            AuthStrategy.AuthResult result = context.strategy.authenticate(context.credentials, context.user);",
        "            if (!result.isSuccess()) {",
        "                throw new SecurityException(\"invalid credentials\");",
        "            }",
        "        }",
        "    }",
        "",
        "    private final class SessionIssuingHandler extends LoginHandler {",
        "        SessionIssuingHandler(LoginHandler next) {",
        "            super(next);",
        "        }",
        "",
        "        @Override",
        "        void apply(LoginContext context) {",
        "            TokenService.TokenBundle bundle = tokenService.issue(context.user.getId());",
        "            context.rawToken = bundle.getRawToken();",
        "            context.session = bundle.getSession();",
        "        }",
        "    }",
        "",
        "    private static final class LoginContext {",
        "        private final Credentials credentials;",
        "        private User user;",
        "        private AuthStrategy strategy;",
        "        private String rawToken;",
        "        private Session session;",
        "",
        "        private LoginContext(Credentials credentials) {",
        "            this.credentials = credentials;",
        "        }",
        "    }",
        "",
        "    public static final class LoginResponse {",
        "        private final String rawToken;",
        "        private final Session session;",
        "",
        "        private LoginResponse(String rawToken, Session session) {",
        "            this.rawToken = rawToken;",
        "            this.session = session;",
        "        }",
        "",
        "        public String getRawToken() {",
        "            return rawToken;",
        "        }",
        "",
        "        public Session getSession() {",
        "            return session;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "User",
      detailMD:
        "Immutable account model. It stores normalized login identifiers and optional auth material for password, OAuth, and MFA, plus lock state for account-level checks.",
    },
    {
      className: "Credentials",
      detailMD:
        "Represents one login attempt. Factory methods create password, OAuth, or OTP credentials and keep the secret in a character array that can be cleared after login.",
    },
    {
      className: "AuthStrategy",
      detailMD:
        "The extension seam for auth methods. The interface defines **method** and **authenticate**, while nested OAuth and OTP strategies demonstrate provider-proof and one-time-code verification.",
    },
    {
      className: "PasswordAuthStrategy",
      detailMD:
        "Password-specific strategy. It creates salted PBKDF2 hashes, verifies presented passwords, clears copied secrets, and keeps password logic out of **AuthService**.",
    },
    {
      className: "Session",
      detailMD:
        "Session record tied to a user and a token hash. It knows whether it is valid at an instant and can be revoked without exposing the raw token.",
    },
    {
      className: "TokenService",
      detailMD:
        "Singleton token authority. It generates high-entropy opaque tokens, stores SHA-256 token hashes, validates expiry and revocation, and removes invalid sessions.",
    },
    {
      className: "AuthService",
      detailMD:
        "Orchestrates the login chain. It indexes users and strategies, executes lookup and checks in order, issues sessions, and exposes validate/logout as the service facade.",
    },
  ],

  dryRun: {
    inputMD:
      "Users: Alice has a password hash, OAuth link **google:alice-123**, MFA seed **246810**. Token TTL is 30 minutes. Actions: password login, token validation, OTP login with wrong code, logout.",
    columns: ["Step", "Input", "Handler or component", "State change", "Result"],
    rows: [
      ["1", "password credentials for Alice", "PasswordAuthStrategy", "No session yet", "PBKDF2 verification succeeds"],
      ["2", "successful auth result", "SessionIssuingHandler", "Session S1 stored by token hash H1", "Raw token T1 returned once"],
      ["3", "validate T1 at +5 minutes", "TokenService", "No mutation", "Optional session S1"],
      ["4", "OTP credentials with code 111111", "OtpAuthStrategy", "No session created", "SecurityException invalid credentials"],
      ["5", "logout T1", "TokenService", "Remove H1 and mark S1 revoked", "Future validate T1 returns empty"],
    ],
    narrativeMD:
      "The important moment is step 2: the raw bearer token leaves the service once, while only H1 is stored. Step 4 proves failed strategies stop before session issuance.",
  },

  complexity: [
    {
      operation: "login user lookup",
      time: "O(1)",
      space: "O(1)",
      note: "Username and email are indexed in a map.",
    },
    {
      operation: "strategy selection",
      time: "O(1)",
      space: "O(1)",
      note: "Auth method maps directly to one strategy.",
    },
    {
      operation: "password verification",
      time: "O(I)",
      space: "O(1)",
      note: "I is the configured PBKDF2 iteration count; intentionally slower than a normal hash.",
    },
    {
      operation: "issue token",
      time: "O(1)",
      space: "O(1)",
      note: "Generate random bytes, hash the token, and insert one session.",
    },
    {
      operation: "validate token",
      time: "O(1)",
      space: "O(1)",
      note: "Hash presented token, map lookup by token hash, expiry and revocation checks.",
    },
  ],
  complexityNotesMD:
    "The only intentionally expensive operation is password verification. That cost is a security feature. Token validation remains constant time in the in-memory model and should stay cheap in production via indexed session storage or signed-token verification.",

  extensibility: [
    {
      label: "Add WebAuthn or passkeys",
      detailMD:
        "Implement **AuthStrategy** for WebAuthn, verify the challenge with a WebAuthn adapter, and register it under a new method. The pipeline remains unchanged.",
    },
    {
      label: "Add risk-based MFA",
      detailMD:
        "Insert a risk-score handler before credential verification or a second-factor handler after password success. The chain structure makes this a local addition.",
    },
    {
      label: "Persist sessions",
      detailMD:
        "Replace the in-memory map inside **TokenService** with a **SessionRepository** backed by Redis or SQL. Continue storing token hashes, expiry, and revoked state.",
    },
    {
      label: "Support device sessions",
      detailMD:
        "Add device id, IP range, and user-agent metadata to **Session** and enforce device-level revocation without changing credential strategies.",
    },
    {
      label: "Use JWTs",
      detailMD:
        "Swap opaque-token storage for signed JWT validation inside **TokenService**. Keep key rotation, short TTLs, and revocation lists behind the same service boundary.",
    },
  ],

  alternativeDesigns: [
    {
      name: "JWT-first stateless sessions",
      detailMD:
        "Issue signed JWTs with user id, expiry, issuer, and audience. Validation becomes signature verification and claim checks without a session lookup.",
      tradeoffsMD:
        "Great for distributed read-heavy systems, but logout, token theft response, and permission changes need short TTLs, revocation lists, or token versioning.",
    },
    {
      name: "Two-phase MFA pipeline",
      detailMD:
        "After password success, return a pending challenge id instead of a session. A second login call verifies OTP or push approval and then issues the token.",
      tradeoffsMD:
        "Closer to production MFA and better UX control, but adds challenge state, retries, expiry, and more failure modes to explain.",
    },
    {
      name: "External identity provider adapter",
      detailMD:
        "Delegate all credential verification to an IdP such as Okta, Entra ID, or Cognito and keep only local session issuance plus user mapping.",
      tradeoffsMD:
        "Reduces credential risk, but the local service still needs clean token handling, account linking, downtime behavior, and audit boundaries.",
    },
  ],

  commonMistakes: [
    "Storing plaintext passwords or using a fast general hash instead of a slow salted password hash.",
    "Returning different error messages for unknown user and wrong password, which enables user enumeration.",
    "Hard-coding password, OAuth, and OTP branches directly inside **AuthService.login** instead of using strategies.",
    "Storing raw bearer tokens in memory or a database instead of token hashes.",
    "Issuing a session before all credential checks and account-state checks finish.",
    "Treating OAuth login as only matching an email without verifying the provider proof and linked subject.",
    "Forgetting token revocation, expiry checks, and logout behavior.",
  ],

  followUps: [
    {
      question: "How would you prevent brute-force password attempts?",
      answerMD:
        "Add a rate-limit or risk handler early in the chain, keyed by user id, IP, device, and method. Store counters outside the process and emit audit events for lockout decisions.",
    },
    {
      question: "How do you rotate token signing keys or token hashes?",
      answerMD:
        "For opaque tokens, rotate hashing pepper or storage keys with versioned hashes. For JWTs, keep a key id, publish active public keys, and validate old keys until their tokens expire.",
    },
    {
      question: "Where does account lockout belong?",
      answerMD:
        "In a chain handler after user lookup and before credential verification. It is account policy, not password strategy logic.",
    },
    {
      question: "How would OAuth account linking be secured?",
      answerMD:
        "Store provider plus immutable subject id, not only email. Require proof from the provider adapter and avoid auto-linking by mutable email alone.",
    },
    {
      question: "How do you support logout from all devices?",
      answerMD:
        "Store sessions by user id as well as token hash, then revoke every active session for that user. JWT designs need token versioning or a revocation list.",
    },
  ],

  productionConsiderations: [
    {
      label: "Secret storage",
      detailMD:
        "Keep password hashes, MFA seeds, OAuth client secrets, and token peppers in appropriate stores. MFA seeds and provider secrets should be encrypted with managed keys.",
    },
    {
      label: "Password policy and migration",
      detailMD:
        "Version password hash formats so you can migrate from PBKDF2 to Argon2 or stronger parameters on next successful login without forcing a reset.",
    },
    {
      label: "Distributed sessions",
      detailMD:
        "Use Redis or a database with TTL indexes for opaque sessions. Keep token hash as the lookup key and avoid logging raw tokens.",
    },
    {
      label: "Observability",
      detailMD:
        "Measure login success rate, failure reason classes, password hash latency, token validation latency, lockouts, and suspicious IP or device patterns.",
    },
    {
      label: "Audit and compliance",
      detailMD:
        "Record who logged in, method used, when tokens were issued or revoked, and admin-driven account changes. Keep audit logs append-only and privacy-aware.",
    },
    {
      label: "Transport security",
      detailMD:
        "Require TLS, secure cookies or authorization headers, SameSite protections for browser sessions, CSRF defenses where cookies are used, and strict token redaction in logs.",
    },
  ],

  interviewNotes: [
    "Did the candidate separate authentication from authorization?",
    "Did they use Strategy for password, OAuth, and OTP instead of a brittle switch statement?",
    "Did they mention salted slow password hashing and constant-time verification?",
    "Did they avoid storing raw tokens and define expiry plus revocation?",
    "Did they model the login flow as ordered steps with clear failure boundaries?",
    "Can they explain how a new auth method is added without changing existing method logic?",
  ],

  quiz: [
    {
      question: "Why should **AuthService.login** not contain all password, OAuth, and OTP checks inline?",
      options: [
        "Because each auth method should vary behind **AuthStrategy** while the pipeline stays stable",
        "Because Java does not allow conditional logic in services",
        "Because token validation must run before user lookup",
        "Because OAuth always replaces password auth",
      ],
      answerIndex: 0,
      explanationMD:
        "Strategy keeps method-specific proof logic additive and prevents the login orchestrator from becoming a high-risk branch pile.",
    },
    {
      question: "What should be stored for an opaque session token?",
      options: [
        "The raw token so it can be returned later",
        "Only the token hash plus session metadata such as user id, expiry, and revoked state",
        "The user's plaintext password",
        "Only the username because tokens are stateless",
      ],
      answerIndex: 1,
      explanationMD:
        "The bearer token is a secret. Store a one-way hash so a storage leak does not immediately expose usable tokens.",
    },
    {
      question: "Which pipeline stage should reject a locked account?",
      options: [
        "After token issue",
        "Inside the password hashing function",
        "After user lookup and before credential verification",
        "Only during logout",
      ],
      answerIndex: 2,
      explanationMD:
        "Account lock is account policy. It should stop the login before any expensive or method-specific verification work.",
    },
    {
      question: "What makes PBKDF2, bcrypt, scrypt, or Argon2 better for passwords than SHA-256 alone?",
      options: [
        "They produce shorter strings",
        "They remove the need for a salt",
        "They can be reversed when a user forgets a password",
        "They are intentionally slow and salted, making offline guessing more expensive",
      ],
      answerIndex: 3,
      explanationMD:
        "Password hashing should slow attackers down. A fast general-purpose hash is the wrong primitive for stored passwords.",
    },
    {
      question: "Why store OAuth provider plus subject id instead of only provider email?",
      options: [
        "Subject id is the stable identity claim; email can change or be reused",
        "Emails cannot be stored in Java strings",
        "Provider subject id is always shorter",
        "It avoids the need to verify the provider proof",
      ],
      answerIndex: 0,
      explanationMD:
        "Account linking should use the provider's stable subject identifier after verifying the provider proof.",
    },
  ],

  practiceVariants: [
    {
      title: "Add WebAuthn passkey login",
      detailMD:
        "Create a new **AuthStrategy** that verifies a WebAuthn assertion using a challenge store and public key. Register it without editing the existing strategies.",
      difficulty: "Advanced",
    },
    {
      title: "Implement two-step MFA",
      detailMD:
        "Change password success to return a pending challenge, then issue the session only after OTP verification. Keep challenge expiry and retry limits explicit.",
      difficulty: "Advanced",
    },
    {
      title: "Add login rate limiting",
      detailMD:
        "Insert a chain handler that checks attempts per user and IP before credential verification. Decide what state must be distributed across app instances.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "Which pattern makes auth methods pluggable?",
      back: "Strategy. **AuthStrategy** hides password, OAuth, OTP, and future verification methods behind the same **authenticate** contract.",
    },
    {
      front: "What does the token service store?",
      back: "A hash of the raw opaque token plus session metadata such as user id, issued time, expiry, and revoked state.",
    },
    {
      front: "Why use a login chain?",
      back: "It keeps lookup, account checks, strategy selection, credential verification, and session issuance as ordered, testable stages.",
    },
    {
      front: "Where should password hashing live?",
      back: "Inside **PasswordAuthStrategy** or a dedicated hasher it owns, never in controllers or generic login orchestration.",
    },
    {
      front: "How should OAuth account linking identify a user?",
      back: "By provider plus stable subject id after verifying provider proof, not by email alone.",
    },
    {
      front: "How do you add logout from all devices?",
      back: "Index sessions by user id and revoke every active session for that user; for JWTs use token versions or revocation lists.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** User, Credentials, AuthStrategy, PasswordAuthStrategy, Session, TokenService, AuthService.",
    "",
    "**Patterns:** Strategy for auth methods, Factory Method for credential/service creation, Chain of Responsibility for login stages, Singleton for token authority.",
    "",
    "**Login flow:** normalize credentials → lookup user → check account status → select strategy → verify proof → issue token.",
    "",
    "**Token flow:** generate opaque token → hash token → store session by hash → return raw token once → validate by hashing presented token.",
    "",
    "**Security rules:** never store plaintext passwords, never store raw bearer tokens, avoid user enumeration, enforce expiry and revocation, audit every sensitive transition.",
    "",
    "**Extensibility:** add a method by implementing **AuthStrategy** and registering it; add policy by inserting a chain handler.",
  ].join("\n"),

  references: [
    {
      title: "OWASP Authentication Cheat Sheet",
      kind: "Docs",
      url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html",
    },
    {
      title: "OWASP Password Storage Cheat Sheet",
      kind: "Docs",
      url: "https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html",
    },
    {
      title: "RFC 6749: The OAuth 2.0 Authorization Framework",
      kind: "Paper",
      author: "IETF",
      url: "https://www.rfc-editor.org/rfc/rfc6749",
    },
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, Vlissides",
    },
  ],

  relatedProblems: [
    { slug: "rbac-system", note: "Authorization usually follows authentication and consumes the validated identity." },
    { slug: "api-gateway", note: "Gateways validate tokens at the edge before routing requests to backend services." },
    { slug: "banking-system", note: "Banking flows depend on strong authentication, session security, and auditability." },
  ],
};
