import type { LLDProblemContent } from "../types";

export const bankingSystem: LLDProblemContent = {
  slug: "banking-system",

  statementMD: [
    "Design the object model for a **core banking system** that supports customers, savings and current accounts, deposits, withdrawals, account-to-account transfers, a transaction ledger, interest accrual, overdraft rules, and account statements.",
    "",
    "The focus is a clean domain model, not a full internet banking product. A strong answer shows how money-moving operations remain atomic, how account types vary without scattered conditionals, and how a ledger provides an auditable history of every balance change.",
  ].join("\n"),

  businessContextMD: [
    "Banking LLD questions are expert-level because the obvious API hides hard constraints: money cannot disappear during a transfer, overdraft rules differ by account type, interest calculation changes by product, and every mutation needs an audit trail.",
    "",
    "Interviewers use this problem to test whether you can combine object-oriented modeling with concurrency boundaries. The model should make simple operations easy, but it must also make illegal states hard: no negative savings balance, no half-completed transfer, no statement reading a corrupted ledger, and no new account type requiring edits across the service.",
  ].join("\n"),

  functionalRequirements: [
    "Create customers and attach multiple accounts to each customer.",
    "Support savings and current accounts through a shared account abstraction.",
    "Allow deposits and withdrawals with account-specific validation rules.",
    "Transfer money between two accounts atomically, with mirrored ledger entries.",
    "Keep a transaction ledger per account for deposits, withdrawals, transfers, and interest credits.",
    "Calculate interest through a pluggable strategy so products can use different formulas.",
    "Enforce overdraft rules for current accounts while savings accounts cannot go below zero.",
    "Generate account statements for a requested time window.",
    "Notify interested observers whenever a transaction is committed.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Atomicity",
      detailMD:
        "A transfer must either debit the source and credit the destination, or do neither. The command holds both account locks during the mutation and records both ledger entries in the same critical section.",
    },
    {
      label: "Thread-safety",
      detailMD:
        "Multiple tellers, ATMs, and scheduled jobs may operate at once. Mutable account state is protected by per-account locks, and transfers acquire locks in deterministic account-id order to avoid deadlocks.",
    },
    {
      label: "Auditability",
      detailMD:
        "Every balance-changing operation appends immutable transaction entries with timestamp, amount, type, resulting balance, and counterparty when applicable.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New account products should arrive as new subclasses and strategies. The service flow should not grow account-type switch statements for every rule.",
    },
    {
      label: "Precision",
      detailMD:
        "Use decimal money values and explicit rounding for interest. Avoid floating point for balance and interest calculations.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need double-entry accounting across general ledger accounts?",
      answerMD:
        "For the interview model, keep per-account ledger entries and mirror transfer entries for both accounts. A production core banking system would add a full general ledger as a separate bounded context.",
    },
    {
      question: "Are deposits and withdrawals cash-only or can they come from external systems?",
      answerMD:
        "Treat them as domain commands that change an account balance. External payment rails, cash machines, and teller terminals are adapters that call these commands.",
    },
    {
      question: "Can a savings account be overdrawn?",
      answerMD:
        "No. Savings accounts reject withdrawals that would make the balance negative. Current accounts may go negative up to a configured overdraft limit.",
    },
    {
      question: "How is interest calculated?",
      answerMD:
        "Interest is delegated to an **InterestStrategy**. The sample uses an annual-rate strategy that computes monthly interest, but tiered, promotional, or zero-interest strategies can be injected.",
    },
    {
      question: "Do statements have to include pending transactions?",
      answerMD:
        "No. The statement reads the committed ledger only. Pending authorization, reconciliation, and reversal workflows are advanced extensions.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Customer {",
    "        -String id",
    "        -String name",
    "        -Set~String~ accountIds",
    "        +addAccount(String) void",
    "        +getAccountIds() Set",
    "    }",
    "    class Account {",
    "        <<abstract>>",
    "        -String id",
    "        -String customerId",
    "        -BigDecimal balance",
    "        -List~Transaction~ ledger",
    "        -ReentrantLock lock",
    "        +getBalance() BigDecimal",
    "        +statement(Instant, Instant) List~Transaction~",
    "        +calculateInterest() BigDecimal",
    "        #validateWithdrawal(BigDecimal) void",
    "    }",
    "    class SavingsAccount {",
    "        -InterestStrategy interestStrategy",
    "        +calculateInterest() BigDecimal",
    "    }",
    "    class CurrentAccount {",
    "        -BigDecimal overdraftLimit",
    "        +calculateInterest() BigDecimal",
    "    }",
    "    class Transaction {",
    "        -String id",
    "        -Type type",
    "        -String accountId",
    "        -String counterpartyAccountId",
    "        -BigDecimal amount",
    "        -BigDecimal resultingBalance",
    "        -Instant timestamp",
    "    }",
    "    class InterestStrategy {",
    "        <<interface>>",
    "        +calculateMonthlyInterest(BigDecimal) BigDecimal",
    "    }",
    "    class BankService {",
    "        -Map~String,Customer~ customers",
    "        -Map~String,Account~ accounts",
    "        -List~TransactionObserver~ observers",
    "        +createCustomer(String) Customer",
    "        +openAccount(String, AccountType, BigDecimal, BigDecimal) Account",
    "        +deposit(String, BigDecimal) Transaction",
    "        +withdraw(String, BigDecimal) Transaction",
    "        +transfer(String, String, BigDecimal) List~Transaction~",
    "        +statement(String, Instant, Instant) List~Transaction~",
    "    }",
    "    class TransactionObserver {",
    "        <<interface>>",
    "        +onTransaction(Transaction) void",
    "    }",
    "    class AccountCommand {",
    "        <<interface>>",
    "        +execute() List~Transaction~",
    "    }",
    "    class Main",
    "    Account <|-- SavingsAccount",
    "    Account <|-- CurrentAccount",
    "    SavingsAccount ..> InterestStrategy",
    "    Account o-- Transaction",
    "    Customer --> Account",
    "    BankService --> Customer",
    "    BankService --> Account",
    "    BankService --> Transaction",
    "    BankService ..> TransactionObserver",
    "    BankService ..> AccountCommand",
    "    Main ..> BankService",
  ].join("\n"),
  classDiagramCaptionMD:
    "The shared **Account** abstraction owns balance and ledger state, subclasses enforce product rules, **InterestStrategy** handles interest variability, and **BankService** is the facade that executes commands under locks.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Teller",
    "    participant Bank as BankService",
    "    participant Cmd as TransferCommand",
    "    participant Src as SourceAccount",
    "    participant Dst as TargetAccount",
    "    participant Obs as TransactionObserver",
    "    Teller->>Bank: transfer(sourceId, targetId, amount)",
    "    Bank->>Bank: load accounts and create command",
    "    Bank->>Cmd: execute()",
    "    Cmd->>Src: lock in account-id order",
    "    Cmd->>Dst: lock in account-id order",
    "    Cmd->>Src: debit(amount)",
    "    Cmd->>Dst: credit(amount)",
    "    Cmd->>Src: append TRANSFER_OUT",
    "    Cmd->>Dst: append TRANSFER_IN",
    "    Cmd-->>Bank: committed ledger entries",
    "    Bank->>Obs: onTransaction(out)",
    "    Bank->>Obs: onTransaction(in)",
    "    Bank-->>Teller: transfer entries",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The transfer command owns the critical section. Observers are notified after the ledger entries are committed so observer failures cannot create a half-transfer.",

  entities: [
    {
      name: "Customer",
      responsibilityMD:
        "Represents the account holder and stores the set of account ids owned by the customer. It does not own balances or ledger entries.",
      attributes: ["id", "name", "accountIds"],
    },
    {
      name: "Account",
      responsibilityMD:
        "Abstract aggregate for balance, ledger, and locking. It exposes safe reads and package-level mutation methods used only by service commands.",
      attributes: ["id", "customerId", "balance", "ledger", "lock"],
    },
    {
      name: "SavingsAccount",
      responsibilityMD:
        "Account product that rejects overdrafts and delegates interest calculation to the injected **InterestStrategy**.",
      attributes: ["interestStrategy"],
    },
    {
      name: "CurrentAccount",
      responsibilityMD:
        "Account product that allows the balance to go negative up to a configured overdraft limit, and returns zero interest in the sample implementation.",
      attributes: ["overdraftLimit"],
    },
    {
      name: "Transaction",
      responsibilityMD:
        "Immutable ledger entry for one account. A transfer creates two entries that share intent but show each account's own resulting balance.",
      attributes: ["id", "type", "accountId", "counterpartyAccountId", "amount", "resultingBalance", "timestamp"],
    },
    {
      name: "InterestStrategy",
      responsibilityMD:
        "Strategy interface for monthly interest. It keeps rate formulas out of account mutation and enables product-specific calculations.",
      attributes: ["calculateMonthlyInterest(balance)"],
    },
    {
      name: "BankService",
      responsibilityMD:
        "Application facade and transaction boundary. It creates accounts, executes commands, coordinates locks, stores aggregates, and publishes ledger notifications.",
      attributes: ["customers", "accounts", "observers", "sequences"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**InterestStrategy** isolates interest formulas from account mutation. A new promotional or slab-based formula is a new strategy, not a rewrite of **SavingsAccount** or **BankService**.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**BankService.createAccount** is the factory method behind **openAccount**. It centralises construction for savings and current products and is the only place that knows which concrete account class to instantiate.",
    },
    {
      name: "Command",
      whyMD:
        "Deposits, withdrawals, transfers, and interest accrual are modeled as command objects. Each command owns validation, locking, mutation, and ledger entry creation for one atomic operation.",
    },
    {
      name: "Observer",
      whyMD:
        "Registered **TransactionObserver** instances receive committed transactions for notifications, fraud scoring, analytics, or audit streaming without coupling those systems to the core mutation flow.",
    },
  ],

  designSteps: [
    {
      title: "Start with account as the concurrency aggregate",
      detailMD:
        "The account owns balance and ledger state, so it also owns the lock protecting them. Single-account commands take one lock; transfer commands take two locks in account-id order to avoid deadlock.",
      code: [
        "Account first = source.getId().compareTo(target.getId()) < 0 ? source : target;",
        "Account second = first == source ? target : source;",
        "first.lock().lock();",
        "second.lock().lock();",
        "try {",
        "    source.debit(amount);",
        "    target.credit(amount);",
        "} finally {",
        "    second.lock().unlock();",
        "    first.lock().unlock();",
        "}",
      ].join("\n"),
    },
    {
      title: "Use a hierarchy for account product rules",
      detailMD:
        "Common behavior lives in **Account**. Savings and current accounts only override the withdrawal rule and interest behavior, so new products stay localized.",
      code: [
        "protected abstract void validateWithdrawal(BigDecimal amount);",
        "",
        "@Override",
        "protected void validateWithdrawal(BigDecimal amount) {",
        "    if (unsafeBalance().compareTo(amount) < 0) {",
        "        throw new IllegalStateException(\"Insufficient funds for savings account\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Make interest a strategy, not an account switch",
      detailMD:
        "Interest formulas vary more frequently than account identity. The account delegates to an injected strategy, and the service can choose the strategy during account creation.",
      code: [
        "public interface InterestStrategy {",
        "    BigDecimal calculateMonthlyInterest(BigDecimal balance);",
        "}",
        "",
        "public BigDecimal calculateInterest() {",
        "    return interestStrategy.calculateMonthlyInterest(getBalance());",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent money movement as commands",
      detailMD:
        "Each operation becomes a command with one **execute** method. This keeps validation, mutation, and ledger creation together and makes it easier to add reversal or retry metadata later.",
    },
    {
      title: "Record the ledger inside the critical section",
      detailMD:
        "The balance change and ledger append belong together. For a transfer, both account entries are appended while both locks are still held, so statements never see only half of a transfer.",
    },
    {
      title: "Publish observers only after commit",
      detailMD:
        "Observers are useful for email alerts and fraud systems, but they are outside the balance invariant. Notify them after the command returns committed entries so a slow observer does not hold account locks.",
    },
  ],

  implementation: [
    {
      filename: "Customer.java",
      language: "java",
      content: [
        'import java.util.Collections;',
        'import java.util.LinkedHashSet;',
        'import java.util.Objects;',
        'import java.util.Set;',
        '',
        'public final class Customer {',
        '    private final String id;',
        '    private final String name;',
        '    private final Set<String> accountIds = new LinkedHashSet<>();',
        '',
        '    public Customer(String id, String name) {',
        '        this.id = requireText(id, "Customer id");',
        '        this.name = requireText(name, "Customer name");',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getName() {',
        '        return name;',
        '    }',
        '',
        '    public synchronized void addAccount(String accountId) {',
        '        accountIds.add(requireText(accountId, "Account id"));',
        '    }',
        '',
        '    public synchronized Set<String> getAccountIds() {',
        '        return Collections.unmodifiableSet(new LinkedHashSet<>(accountIds));',
        '    }',
        '',
        '    private static String requireText(String value, String field) {',
        '        String text = Objects.requireNonNull(value, field + " is required").trim();',
        '        if (text.isEmpty()) {',
        '            throw new IllegalArgumentException(field + " is required");',
        '        }',
        '        return text;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Account.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.time.Instant;',
        'import java.util.ArrayList;',
        'import java.util.List;',
        'import java.util.Objects;',
        'import java.util.concurrent.locks.ReentrantLock;',
        'import java.util.stream.Collectors;',
        '',
        'public abstract class Account {',
        '    private final String id;',
        '    private final String customerId;',
        '    private BigDecimal balance;',
        '    private final List<Transaction> ledger = new ArrayList<>();',
        '    private final ReentrantLock lock = new ReentrantLock();',
        '',
        '    protected Account(String id, String customerId, BigDecimal openingBalance) {',
        '        this.id = requireText(id, "Account id");',
        '        this.customerId = requireText(customerId, "Customer id");',
        '        this.balance = requireNonNegative(openingBalance, "Opening balance");',
        '    }',
        '',
        '    public final String getId() {',
        '        return id;',
        '    }',
        '',
        '    public final String getCustomerId() {',
        '        return customerId;',
        '    }',
        '',
        '    final ReentrantLock lock() {',
        '        return lock;',
        '    }',
        '',
        '    final BigDecimal unsafeBalance() {',
        '        return balance;',
        '    }',
        '',
        '    final BigDecimal credit(BigDecimal amount) {',
        '        BigDecimal value = requirePositive(amount, "Amount");',
        '        balance = balance.add(value);',
        '        return balance;',
        '    }',
        '',
        '    final BigDecimal debit(BigDecimal amount) {',
        '        BigDecimal value = requirePositive(amount, "Amount");',
        '        validateWithdrawal(value);',
        '        balance = balance.subtract(value);',
        '        return balance;',
        '    }',
        '',
        '    final void append(Transaction transaction) {',
        '        ledger.add(Objects.requireNonNull(transaction, "transaction"));',
        '    }',
        '',
        '    public final BigDecimal getBalance() {',
        '        lock.lock();',
        '        try {',
        '            return balance;',
        '        } finally {',
        '            lock.unlock();',
        '        }',
        '    }',
        '',
        '    public final List<Transaction> statement(Instant fromInclusive, Instant toInclusive) {',
        '        Objects.requireNonNull(fromInclusive, "fromInclusive");',
        '        Objects.requireNonNull(toInclusive, "toInclusive");',
        '        if (fromInclusive.isAfter(toInclusive)) {',
        '            throw new IllegalArgumentException("Statement start must be before end");',
        '        }',
        '',
        '        lock.lock();',
        '        try {',
        '            return ledger.stream()',
        '                    .filter(tx -> !tx.getTimestamp().isBefore(fromInclusive))',
        '                    .filter(tx -> !tx.getTimestamp().isAfter(toInclusive))',
        '                    .collect(Collectors.toUnmodifiableList());',
        '        } finally {',
        '            lock.unlock();',
        '        }',
        '    }',
        '',
        '    public abstract BigDecimal calculateInterest();',
        '',
        '    protected abstract void validateWithdrawal(BigDecimal amount);',
        '',
        '    protected static BigDecimal requirePositive(BigDecimal amount, String field) {',
        '        BigDecimal value = Objects.requireNonNull(amount, field + " is required");',
        '        if (value.compareTo(BigDecimal.ZERO) <= 0) {',
        '            throw new IllegalArgumentException(field + " must be positive");',
        '        }',
        '        return value;',
        '    }',
        '',
        '    protected static BigDecimal requireNonNegative(BigDecimal amount, String field) {',
        '        BigDecimal value = Objects.requireNonNull(amount, field + " is required");',
        '        if (value.compareTo(BigDecimal.ZERO) < 0) {',
        '            throw new IllegalArgumentException(field + " cannot be negative");',
        '        }',
        '        return value;',
        '    }',
        '',
        '    private static String requireText(String value, String field) {',
        '        String text = Objects.requireNonNull(value, field + " is required").trim();',
        '        if (text.isEmpty()) {',
        '            throw new IllegalArgumentException(field + " is required");',
        '        }',
        '        return text;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "SavingsAccount.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.util.Objects;',
        '',
        'public class SavingsAccount extends Account {',
        '    private final InterestStrategy interestStrategy;',
        '',
        '    public SavingsAccount(String id, String customerId, BigDecimal openingBalance, InterestStrategy interestStrategy) {',
        '        super(id, customerId, openingBalance);',
        '        this.interestStrategy = Objects.requireNonNull(interestStrategy, "interestStrategy");',
        '    }',
        '',
        '    @Override',
        '    protected void validateWithdrawal(BigDecimal amount) {',
        '        if (unsafeBalance().compareTo(amount) < 0) {',
        '            throw new IllegalStateException("Insufficient funds for savings account");',
        '        }',
        '    }',
        '',
        '    @Override',
        '    public BigDecimal calculateInterest() {',
        '        lock().lock();',
        '        try {',
        '            return interestStrategy.calculateMonthlyInterest(unsafeBalance());',
        '        } finally {',
        '            lock().unlock();',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "CurrentAccount.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        '',
        'public class CurrentAccount extends Account {',
        '    private final BigDecimal overdraftLimit;',
        '',
        '    public CurrentAccount(String id, String customerId, BigDecimal openingBalance, BigDecimal overdraftLimit) {',
        '        super(id, customerId, openingBalance);',
        '        this.overdraftLimit = requireNonNegative(overdraftLimit, "Overdraft limit");',
        '    }',
        '',
        '    public BigDecimal getOverdraftLimit() {',
        '        return overdraftLimit;',
        '    }',
        '',
        '    @Override',
        '    protected void validateWithdrawal(BigDecimal amount) {',
        '        BigDecimal projectedBalance = unsafeBalance().subtract(amount);',
        '        if (projectedBalance.compareTo(overdraftLimit.negate()) < 0) {',
        '            throw new IllegalStateException("Overdraft limit exceeded");',
        '        }',
        '    }',
        '',
        '    @Override',
        '    public BigDecimal calculateInterest() {',
        '        return BigDecimal.ZERO;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Transaction.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.time.Instant;',
        'import java.util.Objects;',
        '',
        'public final class Transaction {',
        '    public enum Type {',
        '        DEPOSIT,',
        '        WITHDRAWAL,',
        '        TRANSFER_OUT,',
        '        TRANSFER_IN,',
        '        INTEREST',
        '    }',
        '',
        '    private final String id;',
        '    private final Type type;',
        '    private final String accountId;',
        '    private final String counterpartyAccountId;',
        '    private final BigDecimal amount;',
        '    private final BigDecimal resultingBalance;',
        '    private final Instant timestamp;',
        '    private final String description;',
        '',
        '    private Transaction(',
        '            String id,',
        '            Type type,',
        '            String accountId,',
        '            String counterpartyAccountId,',
        '            BigDecimal amount,',
        '            BigDecimal resultingBalance,',
        '            Instant timestamp,',
        '            String description) {',
        '        this.id = requireText(id, "Transaction id");',
        '        this.type = Objects.requireNonNull(type, "type");',
        '        this.accountId = requireText(accountId, "Account id");',
        '        this.counterpartyAccountId = counterpartyAccountId;',
        '        this.amount = requirePositive(amount, "Amount");',
        '        this.resultingBalance = Objects.requireNonNull(resultingBalance, "resultingBalance");',
        '        this.timestamp = Objects.requireNonNull(timestamp, "timestamp");',
        '        this.description = requireText(description, "Description");',
        '    }',
        '',
        '    public static Transaction of(',
        '            String id,',
        '            Type type,',
        '            String accountId,',
        '            String counterpartyAccountId,',
        '            BigDecimal amount,',
        '            BigDecimal resultingBalance,',
        '            Instant timestamp,',
        '            String description) {',
        '        return new Transaction(id, type, accountId, counterpartyAccountId, amount, resultingBalance, timestamp, description);',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public Type getType() {',
        '        return type;',
        '    }',
        '',
        '    public String getAccountId() {',
        '        return accountId;',
        '    }',
        '',
        '    public String getCounterpartyAccountId() {',
        '        return counterpartyAccountId;',
        '    }',
        '',
        '    public BigDecimal getAmount() {',
        '        return amount;',
        '    }',
        '',
        '    public BigDecimal getResultingBalance() {',
        '        return resultingBalance;',
        '    }',
        '',
        '    public Instant getTimestamp() {',
        '        return timestamp;',
        '    }',
        '',
        '    public String getDescription() {',
        '        return description;',
        '    }',
        '',
        '    @Override',
        '    public String toString() {',
        '        return timestamp + " " + type + " account=" + accountId + " amount=" + amount + " balance=" + resultingBalance;',
        '    }',
        '',
        '    private static BigDecimal requirePositive(BigDecimal amount, String field) {',
        '        BigDecimal value = Objects.requireNonNull(amount, field + " is required");',
        '        if (value.compareTo(BigDecimal.ZERO) <= 0) {',
        '            throw new IllegalArgumentException(field + " must be positive");',
        '        }',
        '        return value;',
        '    }',
        '',
        '    private static String requireText(String value, String field) {',
        '        String text = Objects.requireNonNull(value, field + " is required").trim();',
        '        if (text.isEmpty()) {',
        '            throw new IllegalArgumentException(field + " is required");',
        '        }',
        '        return text;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "InterestStrategy.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.math.RoundingMode;',
        'import java.util.Objects;',
        '',
        'public interface InterestStrategy {',
        '    BigDecimal calculateMonthlyInterest(BigDecimal balance);',
        '}',
        '',
        'final class AnnualRateInterestStrategy implements InterestStrategy {',
        '    private static final BigDecimal MONTHS_IN_YEAR = BigDecimal.valueOf(12);',
        '    private final BigDecimal annualRate;',
        '',
        '    AnnualRateInterestStrategy(BigDecimal annualRate) {',
        '        BigDecimal rate = Objects.requireNonNull(annualRate, "annualRate");',
        '        if (rate.compareTo(BigDecimal.ZERO) < 0) {',
        '            throw new IllegalArgumentException("Annual rate cannot be negative");',
        '        }',
        '        this.annualRate = rate;',
        '    }',
        '',
        '    @Override',
        '    public BigDecimal calculateMonthlyInterest(BigDecimal balance) {',
        '        Objects.requireNonNull(balance, "balance");',
        '        if (balance.compareTo(BigDecimal.ZERO) <= 0) {',
        '            return BigDecimal.ZERO;',
        '        }',
        '        return balance.multiply(annualRate).divide(MONTHS_IN_YEAR, 2, RoundingMode.HALF_UP);',
        '    }',
        '}',
        '',
        'final class NoInterestStrategy implements InterestStrategy {',
        '    @Override',
        '    public BigDecimal calculateMonthlyInterest(BigDecimal balance) {',
        '        return BigDecimal.ZERO;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "BankService.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.time.Instant;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        'import java.util.concurrent.ConcurrentHashMap;',
        'import java.util.concurrent.CopyOnWriteArrayList;',
        'import java.util.concurrent.atomic.AtomicLong;',
        'import java.util.concurrent.locks.ReentrantLock;',
        '',
        'public class BankService {',
        '    public enum AccountType {',
        '        SAVINGS,',
        '        CURRENT',
        '    }',
        '',
        '    public interface TransactionObserver {',
        '        void onTransaction(Transaction transaction);',
        '    }',
        '',
        '    private final Map<String, Customer> customers = new ConcurrentHashMap<>();',
        '    private final Map<String, Account> accounts = new ConcurrentHashMap<>();',
        '    private final List<TransactionObserver> observers = new CopyOnWriteArrayList<>();',
        '    private final AtomicLong customerSequence = new AtomicLong();',
        '    private final AtomicLong accountSequence = new AtomicLong();',
        '    private final AtomicLong transactionSequence = new AtomicLong();',
        '',
        '    public Customer createCustomer(String name) {',
        '        String customerId = "CUST-" + customerSequence.incrementAndGet();',
        '        Customer customer = new Customer(customerId, name);',
        '        customers.put(customerId, customer);',
        '        return customer;',
        '    }',
        '',
        '    public Account openAccount(String customerId, AccountType type, BigDecimal openingBalance, BigDecimal policyValue) {',
        '        Customer customer = findCustomer(customerId);',
        '        String accountId = "ACC-" + accountSequence.incrementAndGet();',
        '        Account account = createAccount(accountId, customer, type, openingBalance, policyValue);',
        '        accounts.put(accountId, account);',
        '        customer.addAccount(accountId);',
        '        return account;',
        '    }',
        '',
        '    protected Account createAccount(',
        '            String accountId,',
        '            Customer customer,',
        '            AccountType type,',
        '            BigDecimal openingBalance,',
        '            BigDecimal policyValue) {',
        '        Objects.requireNonNull(type, "type");',
        '        switch (type) {',
        '            case SAVINGS:',
        '                return new SavingsAccount(accountId, customer.getId(), openingBalance, new AnnualRateInterestStrategy(policyValue));',
        '            case CURRENT:',
        '                return new CurrentAccount(accountId, customer.getId(), openingBalance, policyValue);',
        '            default:',
        '                throw new IllegalArgumentException("Unsupported account type");',
        '        }',
        '    }',
        '',
        '    public void registerObserver(TransactionObserver observer) {',
        '        observers.add(Objects.requireNonNull(observer, "observer"));',
        '    }',
        '',
        '    public Transaction deposit(String accountId, BigDecimal amount) {',
        '        List<Transaction> entries = execute(new DepositCommand(findAccount(accountId), amount, nextTransactionId()));',
        '        return entries.get(0);',
        '    }',
        '',
        '    public Transaction withdraw(String accountId, BigDecimal amount) {',
        '        List<Transaction> entries = execute(new WithdrawCommand(findAccount(accountId), amount, nextTransactionId()));',
        '        return entries.get(0);',
        '    }',
        '',
        '    public List<Transaction> transfer(String fromAccountId, String toAccountId, BigDecimal amount) {',
        '        if (Objects.equals(fromAccountId, toAccountId)) {',
        '            throw new IllegalArgumentException("Source and target accounts must differ");',
        '        }',
        '        return execute(new TransferCommand(findAccount(fromAccountId), findAccount(toAccountId), amount, nextTransactionId()));',
        '    }',
        '',
        '    public List<Transaction> applyMonthlyInterest(String accountId) {',
        '        return execute(new InterestCommand(findAccount(accountId), nextTransactionId()));',
        '    }',
        '',
        '    public List<Transaction> statement(String accountId, Instant fromInclusive, Instant toInclusive) {',
        '        return findAccount(accountId).statement(fromInclusive, toInclusive);',
        '    }',
        '',
        '    private List<Transaction> execute(AccountCommand command) {',
        '        List<Transaction> entries = command.execute();',
        '        for (Transaction transaction : entries) {',
        '            publish(transaction);',
        '        }',
        '        return entries;',
        '    }',
        '',
        '    private void publish(Transaction transaction) {',
        '        for (TransactionObserver observer : observers) {',
        '            observer.onTransaction(transaction);',
        '        }',
        '    }',
        '',
        '    private Customer findCustomer(String customerId) {',
        '        Customer customer = customers.get(customerId);',
        '        if (customer == null) {',
        '            throw new IllegalArgumentException("Unknown customer: " + customerId);',
        '        }',
        '        return customer;',
        '    }',
        '',
        '    private Account findAccount(String accountId) {',
        '        Account account = accounts.get(accountId);',
        '        if (account == null) {',
        '            throw new IllegalArgumentException("Unknown account: " + accountId);',
        '        }',
        '        return account;',
        '    }',
        '',
        '    private String nextTransactionId() {',
        '        return "TX-" + transactionSequence.incrementAndGet();',
        '    }',
        '',
        '    private interface AccountCommand {',
        '        List<Transaction> execute();',
        '    }',
        '',
        '    private static final class DepositCommand implements AccountCommand {',
        '        private final Account account;',
        '        private final BigDecimal amount;',
        '        private final String transactionId;',
        '',
        '        private DepositCommand(Account account, BigDecimal amount, String transactionId) {',
        '            this.account = account;',
        '            this.amount = amount;',
        '            this.transactionId = transactionId;',
        '        }',
        '',
        '        @Override',
        '        public List<Transaction> execute() {',
        '            ReentrantLock lock = account.lock();',
        '            lock.lock();',
        '            try {',
        '                BigDecimal resultingBalance = account.credit(amount);',
        '                Transaction entry = Transaction.of(transactionId, Transaction.Type.DEPOSIT, account.getId(), null, amount, resultingBalance, Instant.now(), "Deposit");',
        '                account.append(entry);',
        '                return List.of(entry);',
        '            } finally {',
        '                lock.unlock();',
        '            }',
        '        }',
        '    }',
        '',
        '    private static final class WithdrawCommand implements AccountCommand {',
        '        private final Account account;',
        '        private final BigDecimal amount;',
        '        private final String transactionId;',
        '',
        '        private WithdrawCommand(Account account, BigDecimal amount, String transactionId) {',
        '            this.account = account;',
        '            this.amount = amount;',
        '            this.transactionId = transactionId;',
        '        }',
        '',
        '        @Override',
        '        public List<Transaction> execute() {',
        '            ReentrantLock lock = account.lock();',
        '            lock.lock();',
        '            try {',
        '                BigDecimal resultingBalance = account.debit(amount);',
        '                Transaction entry = Transaction.of(transactionId, Transaction.Type.WITHDRAWAL, account.getId(), null, amount, resultingBalance, Instant.now(), "Withdrawal");',
        '                account.append(entry);',
        '                return List.of(entry);',
        '            } finally {',
        '                lock.unlock();',
        '            }',
        '        }',
        '    }',
        '',
        '    private static final class TransferCommand implements AccountCommand {',
        '        private final Account source;',
        '        private final Account target;',
        '        private final BigDecimal amount;',
        '        private final String transactionId;',
        '',
        '        private TransferCommand(Account source, Account target, BigDecimal amount, String transactionId) {',
        '            this.source = source;',
        '            this.target = target;',
        '            this.amount = amount;',
        '            this.transactionId = transactionId;',
        '        }',
        '',
        '        @Override',
        '        public List<Transaction> execute() {',
        '            Account first = source.getId().compareTo(target.getId()) < 0 ? source : target;',
        '            Account second = first == source ? target : source;',
        '            ReentrantLock firstLock = first.lock();',
        '            ReentrantLock secondLock = second.lock();',
        '            firstLock.lock();',
        '            secondLock.lock();',
        '            try {',
        '                BigDecimal sourceBalance = source.debit(amount);',
        '                BigDecimal targetBalance = target.credit(amount);',
        '                Instant now = Instant.now();',
        '                Transaction debit = Transaction.of(transactionId + "-OUT", Transaction.Type.TRANSFER_OUT, source.getId(), target.getId(), amount, sourceBalance, now, "Transfer to " + target.getId());',
        '                Transaction credit = Transaction.of(transactionId + "-IN", Transaction.Type.TRANSFER_IN, target.getId(), source.getId(), amount, targetBalance, now, "Transfer from " + source.getId());',
        '                source.append(debit);',
        '                target.append(credit);',
        '                return List.of(debit, credit);',
        '            } finally {',
        '                secondLock.unlock();',
        '                firstLock.unlock();',
        '            }',
        '        }',
        '    }',
        '',
        '    private static final class InterestCommand implements AccountCommand {',
        '        private final Account account;',
        '        private final String transactionId;',
        '',
        '        private InterestCommand(Account account, String transactionId) {',
        '            this.account = account;',
        '            this.transactionId = transactionId;',
        '        }',
        '',
        '        @Override',
        '        public List<Transaction> execute() {',
        '            ReentrantLock lock = account.lock();',
        '            lock.lock();',
        '            try {',
        '                BigDecimal interest = account.calculateInterest();',
        '                if (interest.compareTo(BigDecimal.ZERO) <= 0) {',
        '                    return List.of();',
        '                }',
        '                BigDecimal resultingBalance = account.credit(interest);',
        '                Transaction entry = Transaction.of(transactionId, Transaction.Type.INTEREST, account.getId(), null, interest, resultingBalance, Instant.now(), "Monthly interest");',
        '                account.append(entry);',
        '                return List.of(entry);',
        '            } finally {',
        '                lock.unlock();',
        '            }',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        'import java.math.BigDecimal;',
        'import java.time.Instant;',
        'import java.time.temporal.ChronoUnit;',
        'import java.util.List;',
        '',
        'public class Main {',
        '    public static void main(String[] args) {',
        '        BankService bank = new BankService();',
        '        bank.registerObserver(transaction -> System.out.println("LEDGER " + transaction));',
        '',
        '        Customer customer = bank.createCustomer("Asha Rao");',
        '        Account savings = bank.openAccount(customer.getId(), BankService.AccountType.SAVINGS, new BigDecimal("1000.00"), new BigDecimal("0.036"));',
        '        Account current = bank.openAccount(customer.getId(), BankService.AccountType.CURRENT, new BigDecimal("500.00"), new BigDecimal("2000.00"));',
        '',
        '        bank.deposit(savings.getId(), new BigDecimal("250.00"));',
        '        bank.transfer(savings.getId(), current.getId(), new BigDecimal("300.00"));',
        '        bank.withdraw(current.getId(), new BigDecimal("700.00"));',
        '        bank.applyMonthlyInterest(savings.getId());',
        '',
        '        List<Transaction> statement = bank.statement(',
        '                savings.getId(),',
        '                Instant.now().minus(1, ChronoUnit.DAYS),',
        '                Instant.now().plus(1, ChronoUnit.DAYS));',
        '        statement.forEach(System.out::println);',
        '    }',
        '}',
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Customer",
      detailMD:
        "Customer is a small identity object with synchronized account-id membership. It keeps ownership visible without mixing customer data into balance mutation.",
    },
    {
      className: "Account",
      detailMD:
        "Account is the abstract aggregate for balance, ledger, and lock. Its package-level **credit**, **debit**, and **append** methods keep all mutation inside command execution.",
    },
    {
      className: "SavingsAccount",
      detailMD:
        "SavingsAccount rejects withdrawals beyond available balance and delegates monthly interest to **InterestStrategy**, making new rate formulas additive.",
    },
    {
      className: "CurrentAccount",
      detailMD:
        "CurrentAccount adds an overdraft limit. Its withdrawal rule allows projected balance down to negative overdraft limit and rejects anything beyond that boundary.",
    },
    {
      className: "Transaction",
      detailMD:
        "Transaction is immutable ledger data: type, amount, account, optional counterparty, timestamp, resulting balance, and description. Statements are filtered views over these entries.",
    },
    {
      className: "InterestStrategy",
      detailMD:
        "InterestStrategy is the pluggable rate seam. The file includes annual-rate and no-interest implementations to demonstrate product-specific interest without service changes.",
    },
    {
      className: "BankService",
      detailMD:
        "BankService is the facade, factory, command dispatcher, and observer publisher. It stores customers/accounts, creates account subclasses, executes atomic operations, and publishes committed ledger entries.",
    },
    {
      className: "Main",
      detailMD:
        "Main wires the demo: creates a customer, opens savings and current accounts, performs deposit, transfer, withdrawal, interest accrual, and prints a statement.",
    },
  ],

  dryRun: {
    inputMD:
      "Customer **Asha** has Savings S with 1000.00 at 3.6% annual interest and Current C with 500.00 plus 2000.00 overdraft. Actions: deposit 250.00 into S, transfer 300.00 from S to C, withdraw 700.00 from C, apply monthly interest to S.",
    columns: ["Step", "Command", "Locks held", "Savings balance", "Current balance", "Ledger effect"],
    rows: [
      ["1", "deposit(S, 250.00)", "S", "1250.00", "500.00", "DEPOSIT entry on S"],
      ["2", "transfer(S, C, 300.00)", "C then S by id order", "950.00", "800.00", "TRANSFER_OUT on S and TRANSFER_IN on C"],
      ["3", "withdraw(C, 700.00)", "C", "950.00", "100.00", "WITHDRAWAL entry on C"],
      ["4", "applyMonthlyInterest(S)", "S", "952.85", "100.00", "INTEREST entry on S"],
      ["5", "statement(S, today)", "S read lock", "952.85", "100.00", "Returns S deposit, transfer out, interest"],
    ],
    narrativeMD:
      "Step 2 is the important correctness point: both accounts are locked before either balance changes, so no reader can observe a debit without the matching credit. Step 4 computes 950.00 × 0.036 ÷ 12 = 2.85.",
  },

  complexity: [
    {
      operation: "createCustomer / openAccount",
      time: "O(1)",
      space: "O(1)",
      note: "Hash-map insert plus object construction.",
    },
    {
      operation: "deposit / withdraw",
      time: "O(1)",
      space: "O(1)",
      note: "One lock, one balance mutation, one ledger append.",
    },
    {
      operation: "transfer",
      time: "O(1)",
      space: "O(1)",
      note: "Two locks acquired in deterministic order, two balance mutations, two ledger appends.",
    },
    {
      operation: "applyMonthlyInterest",
      time: "O(1)",
      space: "O(1)",
      note: "One strategy call and an optional ledger append.",
    },
    {
      operation: "statement",
      time: "O(T)",
      space: "O(R)",
      note: "T ledger entries scanned for the account, R entries returned in the requested window.",
    },
  ],
  complexityNotesMD:
    "The in-memory model keeps mutations constant-time because each account owns its own ledger list. At production scale, statement queries usually move to an indexed ledger repository while the same command boundary remains.",

  extensibility: [
    {
      label: "New account product",
      detailMD:
        "Add a subclass of **Account** and extend the factory method. For example, a salary account can override withdrawal limits and inject a different interest strategy.",
    },
    {
      label: "New interest formula",
      detailMD:
        "Implement **InterestStrategy** for slab rates, daily balance interest, senior-citizen rates, or promotional periods. Existing account commands stay unchanged.",
    },
    {
      label: "Ledger persistence",
      detailMD:
        "Replace the in-memory ledger list with a repository that appends transaction rows inside a database transaction. The command remains the domain-level transaction boundary.",
    },
    {
      label: "Alerts and fraud checks",
      detailMD:
        "Add observers for SMS, email, suspicious-transfer detection, and analytics. Observers subscribe to committed ledger entries without changing account code.",
    },
    {
      label: "Reversals and holds",
      detailMD:
        "Introduce reversal commands and pending-hold entries. The Command pattern gives a natural place to store reversal metadata and idempotency keys.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Central ledger as the source of truth",
      detailMD:
        "Store all transactions in a central append-only ledger and derive balances by folding ledger entries or reading a materialized balance table.",
      tradeoffsMD:
        "Excellent auditability and reconciliation, but more infrastructure and careful snapshotting are needed to keep reads fast.",
    },
    {
      name: "Strategy-only account type",
      detailMD:
        "Use one concrete **Account** class with injected withdrawal, interest, and fee strategies instead of subclasses.",
      tradeoffsMD:
        "More composable for many product variations, but can become harder to reason about when too many policies combine at runtime.",
    },
    {
      name: "Database transaction boundary",
      detailMD:
        "Move atomicity to row-level locks and database transactions over account and ledger tables.",
      tradeoffsMD:
        "Required for multi-instance production deployments, but it makes the interview model heavier and hides useful object responsibilities.",
    },
  ],

  commonMistakes: [
    "Implementing transfer as withdraw followed by deposit without a shared atomic boundary.",
    "Using floating-point values for balances and interest calculations.",
    "Putting savings/current rules in scattered **if accountType** checks instead of account subclasses or strategies.",
    "Appending ledger entries after releasing locks, allowing statements to miss committed balance changes.",
    "Locking source then target without a deterministic order, creating deadlock risk for opposite-direction transfers.",
    "Letting observers run inside account locks, making notifications part of the critical path.",
    "Returning the mutable ledger list directly from the account.",
  ],

  followUps: [
    {
      question: "How would you make the transfer safe across multiple application instances?",
      answerMD:
        "Use a database transaction with row locks on both accounts, acquired in deterministic order, and append both ledger entries in the same transaction. The in-memory locks then become local optimization, not the source of truth.",
    },
    {
      question: "How do you prevent duplicate retries from applying the same transfer twice?",
      answerMD:
        "Add an idempotency key to commands and store it with the ledger transaction group. A retry checks the key and returns the prior result instead of mutating balances again.",
    },
    {
      question: "Where would fees fit?",
      answerMD:
        "Fees can be another strategy or command decoration. A withdrawal command could append a WITHDRAWAL entry and a FEE entry in the same critical section if the policy says fees apply.",
    },
    {
      question: "How would you support account freeze or closed states?",
      answerMD:
        "Add a state field or State pattern to **Account** so commands ask whether a mutation is allowed before debit or credit. Closed accounts can reject all balance-changing commands.",
    },
    {
      question: "Why not notify observers before committing?",
      answerMD:
        "Observers are side effects. If they run before commit, users or fraud systems can see transactions that later fail. Publish after ledger append and make observer delivery retryable.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable ledger",
      detailMD:
        "Use an append-only ledger table with transaction group id, account id, direction, amount, resulting balance, and idempotency key. Never update historical entries.",
    },
    {
      label: "Database isolation",
      detailMD:
        "For transfers, acquire account rows in sorted order and commit both balance updates plus ledger rows in one serializable or repeatable-read transaction.",
    },
    {
      label: "Money representation",
      detailMD:
        "Use minor units or decimal types with currency codes and rounding policies. Do not mix currencies in one account unless an FX workflow is modeled explicitly.",
    },
    {
      label: "Observability and audit",
      detailMD:
        "Emit metrics for failed withdrawals, overdraft usage, transfer latency, observer failures, and ledger append errors. Audit every administrative policy change.",
    },
    {
      label: "Security",
      detailMD:
        "Authorization belongs before command execution. The service should verify the actor may operate on the customer/account before any lock or mutation happens.",
    },
  ],

  interviewNotes: [
    "Did the candidate identify transfer atomicity as the core risk?",
    "Are account-specific rules localized in subclasses or strategies rather than conditionals everywhere?",
    "Is thread-safety explicit, including deterministic lock ordering for transfers?",
    "Does every money movement create an auditable transaction entry?",
    "Can new account products, interest formulas, and observers be added without rewriting the service flow?",
    "Does the design separate committed ledger state from external notifications and adapters?",
  ],

  quiz: [
    {
      question: "What is the main reason transfer locks both accounts before changing either balance?",
      options: [
        "To make interest calculation faster",
        "To ensure debit and credit are committed as one atomic operation",
        "To avoid storing transaction ids",
        "To let observers run in parallel",
      ],
      answerIndex: 1,
      explanationMD:
        "The invariant is that a transfer cannot be half-visible. Holding both locks covers source debit, target credit, and mirrored ledger appends.",
    },
    {
      question: "Why does the design use **InterestStrategy**?",
      options: [
        "To replace all account subclasses",
        "To make statements O(1)",
        "To vary interest formulas without changing account mutation flow",
        "To lock both transfer accounts",
      ],
      answerIndex: 2,
      explanationMD:
        "Interest formulas are policy. Strategy keeps that policy pluggable while account commands remain stable.",
    },
    {
      question: "Which bug is most likely if transfers lock source first and target second without sorting?",
      options: [
        "Duplicate customer ids",
        "Deadlock when opposite transfers run concurrently",
        "Wrong annual interest rounding",
        "Statements returning too many rows",
      ],
      answerIndex: 1,
      explanationMD:
        "Transfer A can hold account 1 and wait for account 2 while transfer B holds account 2 and waits for account 1. Sorting lock order prevents that cycle.",
    },
    {
      question: "Why should observers be notified after the command commits ledger entries?",
      options: [
        "So observer latency does not hold account locks or publish failed transactions",
        "Because observers need write access to account balance",
        "So the account can skip validation",
        "Because Java lambdas require committed data",
      ],
      answerIndex: 0,
      explanationMD:
        "Observers are external side effects. Publishing after commit keeps the balance invariant independent of notification reliability.",
    },
    {
      question: "Where should current-account overdraft validation live?",
      options: [
        "In every caller before withdrawal",
        "In **CurrentAccount.validateWithdrawal**",
        "In **Transaction.toString**",
        "Only in the statement generator",
      ],
      answerIndex: 1,
      explanationMD:
        "The product rule belongs with the account product. Callers should execute commands, not duplicate overdraft logic.",
    },
  ],

  practiceVariants: [
    {
      title: "Add idempotent transfer requests",
      detailMD:
        "Add a request id to every command and store it with a transaction group so retries return the original ledger entries instead of applying twice.",
      difficulty: "Advanced",
    },
    {
      title: "Add fixed deposit accounts",
      detailMD:
        "Create a new account product with maturity date, early-withdrawal penalty, and a different interest strategy. Keep service changes limited to the factory method.",
      difficulty: "Intermediate",
    },
    {
      title: "Persist the ledger",
      detailMD:
        "Replace account-local ledger lists with a repository and implement transfer using a database transaction. Preserve the same domain commands.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "What is the core invariant of transfer?",
      back: "The source debit, target credit, and both ledger entries must commit together or not at all.",
    },
    {
      front: "Which pattern makes interest formulas pluggable?",
      back: "Strategy, via **InterestStrategy**.",
    },
    {
      front: "Why acquire transfer locks in sorted account-id order?",
      back: "To prevent deadlocks when two opposite-direction transfers run concurrently.",
    },
    {
      front: "Where does overdraft validation belong?",
      back: "In the account product rule, such as **CurrentAccount.validateWithdrawal**.",
    },
    {
      front: "What does a transaction ledger entry capture?",
      back: "Type, account, counterparty when relevant, amount, timestamp, resulting balance, and description.",
    },
    {
      front: "Why publish observers after commit?",
      back: "Observers are side effects and should not hold locks or see transactions that later fail.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Customer, Account, SavingsAccount, CurrentAccount, Transaction, InterestStrategy, BankService.",
    "",
    "**Patterns:** Strategy for interest, Factory Method for account creation, Command for money movement, Observer for transaction notifications.",
    "",
    "**Flows:** deposit = lock account → credit → append ledger; withdraw = lock account → validate product rule → debit → append ledger; transfer = lock both accounts in sorted order → debit source → credit target → append mirrored entries.",
    "",
    "**Invariants:** no negative savings balance; current balance cannot go below negative overdraft limit; transfer never half-commits; statements read committed ledger entries only.",
    "",
    "**Thread-safety:** per-account locks for mutable balance and ledger; deterministic lock ordering for two-account operations; observers run after locks are released.",
    "",
    "**Extend:** add account subclass for a new product, add interest strategy for a new formula, add command for reversals, add observer for alerts and analytics.",
  ].join("\n"),

  references: [
    {
      title: "Patterns of Enterprise Application Architecture",
      kind: "Book",
      author: "Martin Fowler",
    },
    {
      title: "Effective Java — Item 60: Avoid float and double if exact answers are required",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — Command Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/command",
    },
    {
      title: "Oracle Java Docs — ReentrantLock",
      kind: "Docs",
      url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html",
    },
  ],

  relatedProblems: [
    { slug: "digital-wallet", note: "Similar money movement and ledger concerns with wallet-specific limits." },
    { slug: "payment-gateway", note: "External payment orchestration builds on idempotent money commands and audit trails." },
    { slug: "splitwise", note: "Balances and transaction history appear in a simpler expense-sharing domain." },
  ],
};
