import type { LLDProblemContent } from "../types";

export const cabBooking: LLDProblemContent = {
  slug: "cab-booking",

  statementMD: [
    "Design the object model for a **cab booking system** like Uber or Ola.",
    "Riders request trips from pickup to drop, nearby available drivers are matched,",
    "the fare is estimated with surge, the trip moves through Requested -> Assigned",
    "-> Started -> Completed / Cancelled, and rider plus driver receive lifecycle notifications.",
    "",
    "The focus is matching and trip lifecycle: who owns live location, who reserves",
    "a driver, who computes price, and who prevents invalid state transitions.",
  ].join("\n"),

  businessContextMD: [
    "Cab booking is a high-signal marketplace LLD problem because it combines live",
    "actors, location-aware dispatch, dynamic pricing, explicit state transitions,",
    "and notification side effects. Weak answers become a giant service full of",
    "if-else blocks. Strong answers separate policies from orchestration and make",
    "the trip aggregate protect its own lifecycle.",
    "",
    "Interviewers usually probe the exact request path: filter available drivers,",
    "choose the nearest one, quote fare with surge, mark that driver unavailable,",
    "assign the trip, then move safely through start, completion, or cancellation.",
  ].join("\n"),

  functionalRequirements: [
    "Register riders and drivers with identity and current live location.",
    "Let drivers update location and toggle availability.",
    "Allow a rider to request a trip with pickup and drop locations.",
    "Match a request to the nearest available driver through a pluggable strategy.",
    "Estimate fare through a pricing strategy that can apply surge using demand and supply.",
    "Create a trip and move it through Requested, Assigned, Started, Completed, and Cancelled states.",
    "Reject invalid transitions such as completing a trip before it starts.",
    "Notify rider and driver on assignment, start, completion, and cancellation.",
    "Release the driver back to available after completion or eligible cancellation.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Low-latency matching",
      detailMD:
        "A ride request should find a nearby driver quickly. The interview version can scan in memory; production can replace that with a geospatial index behind the same strategy.",
    },
    {
      label: "Lifecycle correctness",
      detailMD:
        "The trip must reject impossible transitions instead of letting any caller assign an arbitrary status.",
    },
    {
      label: "Extensible policies",
      detailMD:
        "Matching and pricing change by city, vehicle type, and experiment. They should be interfaces, not hard-coded branches in the service.",
    },
    {
      label: "Timely notifications",
      detailMD:
        "Rider and driver apps need prompt lifecycle updates. The domain should publish events through observers and keep push or SMS delivery outside the trip entity.",
    },
    {
      label: "Concurrency safety",
      detailMD:
        "Two riders must not receive the same driver. Driver selection and marking unavailable form one critical section.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need real road routing and ETA?",
      answerMD:
        "No. Use a simple **Location.distanceTo** estimate. Real maps, traffic, and ETA providers are adapters that can feed matching and pricing later.",
    },
    {
      question: "Can a driver reject an assigned ride?",
      answerMD:
        "Not in the base flow. Driver acceptance can be added as an Offered state before Assigned, with timeout and retry matching.",
    },
    {
      question: "When is a driver made unavailable?",
      answerMD:
        "Immediately after the service chooses the driver and before returning the assigned trip, inside the same synchronized request flow.",
    },
    {
      question: "Which cancellations are supported?",
      answerMD:
        "Requested, Assigned, and Started trips can cancel in the base model. Completed and Cancelled are terminal.",
    },
    {
      question: "Who sends notifications?",
      answerMD:
        "The **Trip** emits lifecycle messages to **TripObserver** instances. Concrete push, SMS, or email adapters can subscribe outside the core model.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class RideService {",
    "        -MatchingStrategy matchingStrategy",
    "        -PricingStrategy pricingStrategy",
    "        -Map~String,Rider~ riders",
    "        -Map~String,Driver~ drivers",
    "        -Map~String,Trip~ trips",
    "        +getInstance() RideService",
    "        +requestTrip(String, Location, Location) Trip",
    "        +startTrip(String) void",
    "        +completeTrip(String) void",
    "        +cancelTrip(String, String) void",
    "    }",
    "    class Rider {",
    "        -String id",
    "        -String name",
    "        -Location currentLocation",
    "        +onTripUpdate(Trip, String) void",
    "    }",
    "    class Driver {",
    "        -String id",
    "        -String name",
    "        -Location currentLocation",
    "        -boolean available",
    "        +setAvailable(boolean) void",
    "        +onTripUpdate(Trip, String) void",
    "    }",
    "    class Location {",
    "        -double latitude",
    "        -double longitude",
    "        +distanceTo(Location) double",
    "    }",
    "    class Trip {",
    "        -Rider rider",
    "        -Driver driver",
    "        -TripStatus status",
    "        -TripState state",
    "        +assign(Driver, BigDecimal) void",
    "        +start() void",
    "        +complete() void",
    "        +cancel(String) void",
    "    }",
    "    class TripStatus {",
    "        <<enumeration>>",
    "        REQUESTED",
    "        ASSIGNED",
    "        STARTED",
    "        COMPLETED",
    "        CANCELLED",
    "    }",
    "    class TripState {",
    "        <<interface>>",
    "        +assign(Trip, Driver, BigDecimal) void",
    "        +start(Trip) void",
    "        +complete(Trip) void",
    "        +cancel(Trip, String) void",
    "    }",
    "    class MatchingStrategy {",
    "        <<interface>>",
    "        +match(Rider, Location, Collection~Driver~) Optional~Driver~",
    "    }",
    "    class PricingStrategy {",
    "        <<interface>>",
    "        +estimateFare(Location, Location, int, int) BigDecimal",
    "    }",
    "    class TripObserver {",
    "        <<interface>>",
    "        +onTripUpdate(Trip, String) void",
    "    }",
    "    RideService ..> MatchingStrategy",
    "    RideService ..> PricingStrategy",
    "    RideService o-- Trip",
    "    RideService o-- Rider",
    "    RideService o-- Driver",
    "    Rider ..|> TripObserver",
    "    Driver ..|> TripObserver",
    "    Rider --> Location",
    "    Driver --> Location",
    "    Trip --> Rider",
    "    Trip --> Driver",
    "    Trip --> Location",
    "    Trip --> TripStatus",
    "    Trip --> TripState",
    "    Trip --> TripObserver",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service coordinates requests; matching and pricing are strategies; the trip owns its state machine and notifies rider and driver observers.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor RiderApp",
    "    participant Service as RideService",
    "    participant Match as MatchingStrategy",
    "    participant Price as PricingStrategy",
    "    participant Trip",
    "    participant DriverApp",
    "    RiderApp->>Service: requestTrip(riderId, pickup, dropoff)",
    "    Service->>Match: match(rider, pickup, drivers)",
    "    Match-->>Service: nearest available driver",
    "    Service->>Price: estimateFare(pickup, dropoff, supply, demand)",
    "    Price-->>Service: fare",
    "    Service->>Trip: create and assign(driver, fare)",
    "    Trip-->>RiderApp: assigned notification",
    "    Trip-->>DriverApp: assigned notification",
    "    DriverApp->>Service: startTrip(tripId)",
    "    Service->>Trip: start()",
    "    Trip-->>RiderApp: started notification",
    "    Trip-->>DriverApp: started notification",
    "    DriverApp->>Service: completeTrip(tripId)",
    "    Service->>Trip: complete()",
    "    Trip-->>RiderApp: completed notification",
    "    Trip-->>DriverApp: completed notification",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The request path decides matching and pricing before creating one trip; after that, state transitions drive notifications.",

  entities: [
    {
      name: "Rider",
      responsibilityMD:
        "Customer actor with current location. It requests trips and receives lifecycle messages as an observer.",
      attributes: ["id", "name", "currentLocation", "notifications"],
    },
    {
      name: "Driver",
      responsibilityMD:
        "Supply actor with live location and availability. The service reserves the driver by flipping availability during assignment.",
      attributes: ["id", "name", "currentLocation", "available"],
    },
    {
      name: "Location",
      responsibilityMD:
        "Immutable latitude-longitude value object shared by matching and pricing.",
      attributes: ["latitude", "longitude", "distanceTo"],
    },
    {
      name: "Trip",
      responsibilityMD:
        "Aggregate for one ride. It stores pickup, dropoff, rider, driver, fare, current status, state object, and observers.",
      attributes: ["id", "rider", "driver", "pickup", "dropoff", "fare", "status", "state"],
    },
    {
      name: "TripStatus / TripState",
      responsibilityMD:
        "Visible enum plus behavior objects that enforce legal lifecycle transitions.",
      attributes: ["REQUESTED", "ASSIGNED", "STARTED", "COMPLETED", "CANCELLED"],
    },
    {
      name: "MatchingStrategy",
      responsibilityMD:
        "Driver-selection policy. The base implementation chooses the nearest available driver.",
      attributes: ["match"],
    },
    {
      name: "PricingStrategy",
      responsibilityMD:
        "Fare-estimation policy. The base implementation combines base fare, distance fare, and surge multiplier.",
      attributes: ["estimateFare"],
    },
    {
      name: "TripObserver",
      responsibilityMD:
        "Notification seam implemented by rider and driver. Production push or SMS adapters can implement the same interface.",
      attributes: ["onTripUpdate"],
    },
    {
      name: "RideService",
      responsibilityMD:
        "Singleton facade that registers actors, performs atomic match-and-assign, stores trips, and delegates lifecycle operations.",
      attributes: ["riders", "drivers", "trips", "matchingStrategy", "pricingStrategy"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**MatchingStrategy** and **PricingStrategy** isolate policies that vary by city, category, demand, and experiment while the service flow stays stable.",
    },
    {
      name: "State",
      whyMD:
        "**TripState** moves transition rules out of if-else chains. Requested can assign or cancel, Assigned can start or cancel, Started can complete or cancel, and terminal states reject changes.",
    },
    {
      name: "Observer",
      whyMD:
        "**TripObserver** lets rider, driver, and future notification adapters subscribe to lifecycle updates without coupling **Trip** to delivery channels.",
    },
    {
      name: "Singleton",
      whyMD:
        "**RideService.getInstance** gives the in-memory interview solution one coordinator for rider, driver, and trip maps, making the critical section easy to explain.",
    },
  ],

  designSteps: [
    {
      title: "Model the lifecycle first",
      detailMD:
        "Start from the state chain. Every request begins as Requested, must be Assigned before Started, and ends as Completed or Cancelled.",
      code: [
        "enum TripStatus {",
        "    REQUESTED, ASSIGNED, STARTED, COMPLETED, CANCELLED",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent pickup and driver positions as values",
      detailMD:
        "**Location** is immutable and owns distance calculation so matching and pricing do not duplicate coordinate math.",
      code: [
        "public double distanceTo(Location other) {",
        "    double dLat = latitude - other.latitude;",
        "    double dLon = longitude - other.longitude;",
        "    return Math.sqrt(dLat * dLat + dLon * dLon) * 111.0;",
        "}",
      ].join("\n"),
    },
    {
      title: "Select drivers through a strategy",
      detailMD:
        "The base policy is nearest available driver, but the service depends only on **MatchingStrategy**.",
      code: [
        "return drivers.stream()",
        "    .filter(Driver::isAvailable)",
        "    .min(Comparator.comparingDouble(d -> d.getCurrentLocation().distanceTo(pickup)));",
      ].join("\n"),
    },
    {
      title: "Compute surge through a strategy",
      detailMD:
        "**PricingStrategy** receives pickup, dropoff, available-driver count, and active-request count. The trip stores the quote returned by the strategy.",
    },
    {
      title: "Make match-and-assign atomic",
      detailMD:
        "The synchronized **requestTrip** method selects a driver, marks the driver unavailable, assigns the trip, and stores it before returning.",
    },
    {
      title: "Notify from state transitions",
      detailMD:
        "The service wires rider and driver as **TripObserver** instances. The trip broadcasts assignment, start, completion, and cancellation from transition methods.",
    },
  ],

  implementation: [
    {
      filename: "Location.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class Location {",
        "    private static final double KM_PER_DEGREE = 111.0;",
        "    private final double latitude;",
        "    private final double longitude;",
        "",
        "    public Location(double latitude, double longitude) {",
        "        if (latitude < -90.0 || latitude > 90.0) throw new IllegalArgumentException(\"Latitude out of range\");",
        "        if (longitude < -180.0 || longitude > 180.0) throw new IllegalArgumentException(\"Longitude out of range\");",
        "        this.latitude = latitude;",
        "        this.longitude = longitude;",
        "    }",
        "",
        "    public double getLatitude() { return latitude; }",
        "    public double getLongitude() { return longitude; }",
        "",
        "    public double distanceTo(Location other) {",
        "        Objects.requireNonNull(other, \"other\");",
        "        double avgLatitude = Math.toRadians((latitude + other.latitude) / 2.0);",
        "        double dLat = latitude - other.latitude;",
        "        double dLon = (longitude - other.longitude) * Math.cos(avgLatitude);",
        "        return Math.sqrt(dLat * dLat + dLon * dLon) * KM_PER_DEGREE;",
        "    }",
        "",
        "    @Override",
        "    public String toString() { return \"(\" + latitude + \", \" + longitude + \")\"; }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Rider.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Rider implements TripObserver {",
        "    private final String id;",
        "    private final String name;",
        "    private Location currentLocation;",
        "    private final List<String> notifications = new ArrayList<>();",
        "",
        "    public Rider(String id, String name, Location currentLocation) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.name = Objects.requireNonNull(name, \"name\");",
        "        this.currentLocation = Objects.requireNonNull(currentLocation, \"currentLocation\");",
        "    }",
        "",
        "    public String getId() { return id; }",
        "    public String getName() { return name; }",
        "",
        "    public synchronized Location getCurrentLocation() { return currentLocation; }",
        "",
        "    public synchronized void updateLocation(Location location) {",
        "        this.currentLocation = Objects.requireNonNull(location, \"location\");",
        "    }",
        "",
        "    @Override",
        "    public synchronized void onTripUpdate(Trip trip, String message) {",
        "        notifications.add(\"Rider \" + name + \" notified for \" + trip.getId() + \": \" + message);",
        "    }",
        "",
        "    public synchronized List<String> getNotifications() {",
        "        return new ArrayList<>(notifications);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Driver.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Driver implements TripObserver {",
        "    private final String id;",
        "    private final String name;",
        "    private Location currentLocation;",
        "    private boolean available = true;",
        "    private final List<String> notifications = new ArrayList<>();",
        "",
        "    public Driver(String id, String name, Location currentLocation) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.name = Objects.requireNonNull(name, \"name\");",
        "        this.currentLocation = Objects.requireNonNull(currentLocation, \"currentLocation\");",
        "    }",
        "",
        "    public String getId() { return id; }",
        "    public String getName() { return name; }",
        "    public synchronized Location getCurrentLocation() { return currentLocation; }",
        "    public synchronized boolean isAvailable() { return available; }",
        "",
        "    public synchronized void updateLocation(Location location) {",
        "        this.currentLocation = Objects.requireNonNull(location, \"location\");",
        "    }",
        "",
        "    public synchronized void setAvailable(boolean available) {",
        "        this.available = available;",
        "    }",
        "",
        "    @Override",
        "    public synchronized void onTripUpdate(Trip trip, String message) {",
        "        notifications.add(\"Driver \" + name + \" notified for \" + trip.getId() + \": \" + message);",
        "    }",
        "",
        "    public synchronized List<String> getNotifications() {",
        "        return new ArrayList<>(notifications);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Trip.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Trip {",
        "    private final String id;",
        "    private final Rider rider;",
        "    private final Location pickup;",
        "    private final Location dropoff;",
        "    private final List<TripObserver> observers = new ArrayList<>();",
        "    private Driver driver;",
        "    private BigDecimal fare = BigDecimal.ZERO;",
        "    private TripStatus status = TripStatus.REQUESTED;",
        "    private TripState state = new RequestedState();",
        "",
        "    public Trip(String id, Rider rider, Location pickup, Location dropoff) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.rider = Objects.requireNonNull(rider, \"rider\");",
        "        this.pickup = Objects.requireNonNull(pickup, \"pickup\");",
        "        this.dropoff = Objects.requireNonNull(dropoff, \"dropoff\");",
        "    }",
        "",
        "    public String getId() { return id; }",
        "    public Rider getRider() { return rider; }",
        "    public Location getPickup() { return pickup; }",
        "    public Location getDropoff() { return dropoff; }",
        "    public synchronized Driver getDriver() { return driver; }",
        "    public synchronized BigDecimal getFare() { return fare; }",
        "    public synchronized TripStatus getStatus() { return status; }",
        "",
        "    public synchronized void addObserver(TripObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public synchronized void assign(Driver driver, BigDecimal fare) { state.assign(this, driver, fare); }",
        "    public synchronized void start() { state.start(this); }",
        "    public synchronized void complete() { state.complete(this); }",
        "    public synchronized void cancel(String reason) { state.cancel(this, reason); }",
        "",
        "    void setDriver(Driver driver) { this.driver = Objects.requireNonNull(driver, \"driver\"); }",
        "    void setFare(BigDecimal fare) { this.fare = Objects.requireNonNull(fare, \"fare\"); }",
        "",
        "    void changeState(TripStatus status, TripState state, String message) {",
        "        this.status = Objects.requireNonNull(status, \"status\");",
        "        this.state = Objects.requireNonNull(state, \"state\");",
        "        for (TripObserver observer : observers) {",
        "            observer.onTripUpdate(this, message);",
        "        }",
        "    }",
        "}",
        "",
        "enum TripStatus { REQUESTED, ASSIGNED, STARTED, COMPLETED, CANCELLED }",
        "",
        "interface TripObserver {",
        "    void onTripUpdate(Trip trip, String message);",
        "}",
        "",
        "interface TripState {",
        "    default void assign(Trip trip, Driver driver, BigDecimal fare) {",
        "        throw new IllegalStateException(\"Cannot assign trip from \" + trip.getStatus());",
        "    }",
        "",
        "    default void start(Trip trip) {",
        "        throw new IllegalStateException(\"Cannot start trip from \" + trip.getStatus());",
        "    }",
        "",
        "    default void complete(Trip trip) {",
        "        throw new IllegalStateException(\"Cannot complete trip from \" + trip.getStatus());",
        "    }",
        "",
        "    default void cancel(Trip trip, String reason) {",
        "        throw new IllegalStateException(\"Cannot cancel trip from \" + trip.getStatus());",
        "    }",
        "}",
        "",
        "final class RequestedState implements TripState {",
        "    @Override",
        "    public void assign(Trip trip, Driver driver, BigDecimal fare) {",
        "        trip.setDriver(driver);",
        "        trip.setFare(fare);",
        "        trip.changeState(TripStatus.ASSIGNED, new AssignedState(), \"Assigned to driver \" + driver.getName() + \" with fare \" + fare);",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Trip trip, String reason) {",
        "        trip.changeState(TripStatus.CANCELLED, new CancelledState(), \"Cancelled before assignment: \" + reason);",
        "    }",
        "}",
        "",
        "final class AssignedState implements TripState {",
        "    @Override",
        "    public void start(Trip trip) {",
        "        trip.changeState(TripStatus.STARTED, new StartedState(), \"Trip started\");",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Trip trip, String reason) {",
        "        trip.changeState(TripStatus.CANCELLED, new CancelledState(), \"Cancelled after assignment: \" + reason);",
        "    }",
        "}",
        "",
        "final class StartedState implements TripState {",
        "    @Override",
        "    public void complete(Trip trip) {",
        "        trip.changeState(TripStatus.COMPLETED, new CompletedState(), \"Trip completed with fare \" + trip.getFare());",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Trip trip, String reason) {",
        "        trip.changeState(TripStatus.CANCELLED, new CancelledState(), \"Cancelled during ride: \" + reason);",
        "    }",
        "}",
        "",
        "final class CompletedState implements TripState { }",
        "final class CancelledState implements TripState { }",
      ].join("\n"),
    },
    {
      filename: "MatchingStrategy.java",
      language: "java",
      content: [
        "import java.util.Collection;",
        "import java.util.Comparator;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "",
        "public interface MatchingStrategy {",
        "    Optional<Driver> match(Rider rider, Location pickup, Collection<Driver> drivers);",
        "}",
        "",
        "final class NearestAvailableMatchingStrategy implements MatchingStrategy {",
        "    @Override",
        "    public Optional<Driver> match(Rider rider, Location pickup, Collection<Driver> drivers) {",
        "        Objects.requireNonNull(rider, \"rider\");",
        "        Objects.requireNonNull(pickup, \"pickup\");",
        "        Objects.requireNonNull(drivers, \"drivers\");",
        "        return drivers.stream()",
        "            .filter(Driver::isAvailable)",
        "            .min(Comparator.comparingDouble(driver -> driver.getCurrentLocation().distanceTo(pickup)));",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PricingStrategy.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.math.RoundingMode;",
        "import java.util.Objects;",
        "",
        "public interface PricingStrategy {",
        "    BigDecimal estimateFare(Location pickup, Location dropoff, int availableDrivers, int activeRequests);",
        "}",
        "",
        "final class SurgePricingStrategy implements PricingStrategy {",
        "    private final BigDecimal baseFare;",
        "    private final BigDecimal perKmRate;",
        "",
        "    public SurgePricingStrategy(BigDecimal baseFare, BigDecimal perKmRate) {",
        "        this.baseFare = Objects.requireNonNull(baseFare, \"baseFare\");",
        "        this.perKmRate = Objects.requireNonNull(perKmRate, \"perKmRate\");",
        "    }",
        "",
        "    @Override",
        "    public BigDecimal estimateFare(Location pickup, Location dropoff, int availableDrivers, int activeRequests) {",
        "        double distanceKm = Math.max(1.0, Objects.requireNonNull(pickup, \"pickup\").distanceTo(Objects.requireNonNull(dropoff, \"dropoff\")));",
        "        BigDecimal subtotal = baseFare.add(perKmRate.multiply(BigDecimal.valueOf(distanceKm)));",
        "        return subtotal.multiply(BigDecimal.valueOf(surgeMultiplier(availableDrivers, activeRequests))).setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    private double surgeMultiplier(int availableDrivers, int activeRequests) {",
        "        if (availableDrivers <= 0) return 2.0;",
        "        double pressure = (double) activeRequests / availableDrivers;",
        "        if (pressure > 2.0) return 1.8;",
        "        if (pressure > 1.0) return 1.4;",
        "        return 1.0;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "RideService.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.util.ArrayList;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.concurrent.atomic.AtomicLong;",
        "",
        "public final class RideService {",
        "    private static final RideService INSTANCE = new RideService(",
        "        new NearestAvailableMatchingStrategy(),",
        "        new SurgePricingStrategy(BigDecimal.valueOf(50), BigDecimal.valueOf(18))",
        "    );",
        "",
        "    private final MatchingStrategy matchingStrategy;",
        "    private final PricingStrategy pricingStrategy;",
        "    private final Map<String, Rider> riders = new LinkedHashMap<>();",
        "    private final Map<String, Driver> drivers = new LinkedHashMap<>();",
        "    private final Map<String, Trip> trips = new LinkedHashMap<>();",
        "    private final AtomicLong tripSequence = new AtomicLong(1);",
        "    private int activeRequests;",
        "",
        "    private RideService(MatchingStrategy matchingStrategy, PricingStrategy pricingStrategy) {",
        "        this.matchingStrategy = Objects.requireNonNull(matchingStrategy, \"matchingStrategy\");",
        "        this.pricingStrategy = Objects.requireNonNull(pricingStrategy, \"pricingStrategy\");",
        "    }",
        "",
        "    public static RideService getInstance() { return INSTANCE; }",
        "    public synchronized void registerRider(Rider rider) { riders.put(rider.getId(), rider); }",
        "    public synchronized void registerDriver(Driver driver) { drivers.put(driver.getId(), driver); }",
        "",
        "    public synchronized Trip requestTrip(String riderId, Location pickup, Location dropoff) {",
        "        Rider rider = requireRider(riderId);",
        "        int availableDrivers = countAvailableDrivers();",
        "        activeRequests++;",
        "        try {",
        "            Driver driver = matchingStrategy.match(rider, pickup, drivers.values())",
        "                .orElseThrow(() -> new IllegalStateException(\"No available driver near pickup\"));",
        "            BigDecimal fare = pricingStrategy.estimateFare(pickup, dropoff, availableDrivers, activeRequests);",
        "            Trip trip = new Trip(nextTripId(), rider, pickup, dropoff);",
        "            trip.addObserver(rider);",
        "            trip.addObserver(driver);",
        "            driver.setAvailable(false);",
        "            trip.assign(driver, fare);",
        "            trips.put(trip.getId(), trip);",
        "            return trip;",
        "        } finally {",
        "            activeRequests--;",
        "        }",
        "    }",
        "",
        "    public synchronized void startTrip(String tripId) { requireTrip(tripId).start(); }",
        "",
        "    public synchronized void completeTrip(String tripId) {",
        "        Trip trip = requireTrip(tripId);",
        "        trip.complete();",
        "        trip.getDriver().setAvailable(true);",
        "    }",
        "",
        "    public synchronized void cancelTrip(String tripId, String reason) {",
        "        Trip trip = requireTrip(tripId);",
        "        trip.cancel(reason);",
        "        if (trip.getDriver() != null) trip.getDriver().setAvailable(true);",
        "    }",
        "",
        "    public synchronized List<Trip> getTrips() { return new ArrayList<>(trips.values()); }",
        "",
        "    private Rider requireRider(String riderId) {",
        "        Rider rider = riders.get(riderId);",
        "        if (rider == null) throw new IllegalArgumentException(\"Unknown rider \" + riderId);",
        "        return rider;",
        "    }",
        "",
        "    private Trip requireTrip(String tripId) {",
        "        Trip trip = trips.get(tripId);",
        "        if (trip == null) throw new IllegalArgumentException(\"Unknown trip \" + tripId);",
        "        return trip;",
        "    }",
        "",
        "    private int countAvailableDrivers() {",
        "        int count = 0;",
        "        for (Driver driver : drivers.values()) if (driver.isAvailable()) count++;",
        "        return count;",
        "    }",
        "",
        "    private String nextTripId() { return \"TRIP-\" + tripSequence.getAndIncrement(); }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public final class Main {",
        "    public static void main(String[] args) {",
        "        RideService service = RideService.getInstance();",
        "        Rider rider = new Rider(\"R1\", \"Asha\", new Location(12.9716, 77.5946));",
        "        Driver driver1 = new Driver(\"D1\", \"Imran\", new Location(12.9720, 77.6000));",
        "        Driver driver2 = new Driver(\"D2\", \"Neha\", new Location(12.9352, 77.6245));",
        "        service.registerRider(rider);",
        "        service.registerDriver(driver1);",
        "        service.registerDriver(driver2);",
        "        Trip trip = service.requestTrip(rider.getId(), rider.getCurrentLocation(), new Location(12.9279, 77.6271));",
        "        service.startTrip(trip.getId());",
        "        service.completeTrip(trip.getId());",
        "        System.out.println(trip.getId() + \" ended as \" + trip.getStatus() + \" with fare \" + trip.getFare());",
        "        System.out.println(rider.getNotifications());",
        "        System.out.println(driver1.getNotifications());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    { className: "Location", detailMD: "Immutable value object for latitude and longitude. **distanceTo** gives matching and pricing one shared distance estimate." },
    { className: "Rider", detailMD: "Customer actor that stores current location and implements **TripObserver** for lifecycle notifications." },
    { className: "Driver", detailMD: "Supply actor with live location and availability. The service reserves and releases the driver around the trip lifecycle." },
    { className: "Trip", detailMD: "Ride aggregate and state-machine host. Concrete states in the same file enforce assignment, start, completion, and cancellation rules." },
    { className: "MatchingStrategy", detailMD: "Driver-selection seam. **NearestAvailableMatchingStrategy** chooses the available driver closest to pickup." },
    { className: "PricingStrategy", detailMD: "Fare-estimation seam. **SurgePricingStrategy** combines base fare, distance fare, and a demand-supply multiplier." },
    { className: "RideService", detailMD: "Singleton facade and critical section for registration, match-and-assign, trip storage, and driver release." },
    { className: "Main", detailMD: "Demo that registers actors, requests a trip, starts it, completes it, and prints notifications." },
  ],

  dryRun: {
    inputMD:
      "Rider R1 requests Indiranagar to Koramangala. Drivers: D1 is 0.6 km away and available; D2 is 5.2 km away and available. Base fare 50, per-km 18, one active request, two available drivers.",
    columns: ["Step", "Action", "Driver pool", "Trip status", "Notifications", "Result"],
    rows: [
      ["1", "requestTrip(R1)", "D1:0.6 km free, D2:5.2 km free", "REQUESTED", "none yet", "D1 chosen as nearest available"],
      ["2", "estimateFare", "available=2, activeRequests=1", "REQUESTED", "none yet", "base + distance fare with 1.0 surge"],
      ["3", "assign D1", "D1 marked unavailable", "ASSIGNED", "rider and D1 receive assigned", "Trip TRIP-1 stored"],
      ["4", "startTrip(TRIP-1)", "D1 busy", "STARTED", "rider and D1 receive started", "Trip moves out of pickup phase"],
      ["5", "completeTrip(TRIP-1)", "D1 released", "COMPLETED", "rider and D1 receive completed", "Trip terminal, fare retained"],
    ],
    narrativeMD:
      "Step 3 is the key invariant: D1 is selected and marked unavailable in the same service call, so another rider cannot receive the same driver.",
  },

  complexity: [
    { operation: "requestTrip with linear scan", time: "O(D)", space: "O(1)", note: "D is the number of registered drivers scanned by the nearest-available strategy." },
    { operation: "fare estimate", time: "O(1)", space: "O(1)", note: "Distance and surge multiplier are constant-time in this interview model." },
    { operation: "startTrip / completeTrip / cancelTrip", time: "O(1)", space: "O(1)", note: "Map lookup, one state transition, and a small observer broadcast." },
    { operation: "location update", time: "O(1)", space: "O(1)", note: "The actor replaces one immutable Location value." },
  ],
  complexityNotesMD:
    "The hot path is matching. Replace the O(D) scan with geohash, S2, H3, or another spatial index while keeping **MatchingStrategy** unchanged.",

  extensibility: [
    { label: "ETA-aware matching", detailMD: "Add a strategy that ranks by road ETA, rating, acceptance probability, and fairness instead of pure straight-line distance." },
    { label: "City-specific pricing", detailMD: "Add a pricing strategy that reads city rates, vehicle category, weather, events, tolls, and cancellation fees." },
    { label: "Driver acceptance", detailMD: "Insert Offered and OfferExpired states before Assigned, then retry matching when an offer times out or is rejected." },
    { label: "Notification channels", detailMD: "Attach observers for push, SMS, email, or WhatsApp without changing **Trip** transition logic." },
    { label: "Persistence", detailMD: "Replace in-memory maps with repositories and keep service methods as transaction boundaries." },
  ],

  alternativeDesigns: [
    {
      name: "Geospatial driver index",
      detailMD:
        "Maintain available drivers in cells and expand around pickup until enough candidates are found, then rank candidates with the matching strategy.",
      tradeoffsMD:
        "Fast at scale, but driver location updates must keep the index consistent and cell expansion becomes a separate algorithm.",
    },
    {
      name: "Event-sourced trip lifecycle",
      detailMD:
        "Persist events such as TripRequested, DriverAssigned, TripStarted, TripCompleted, and TripCancelled, then derive status from the stream.",
      tradeoffsMD:
        "Excellent auditability, but usually too heavy for the base LLD unless disputes or compliance are central follow-ups.",
    },
    {
      name: "Dedicated dispatch service",
      detailMD:
        "Move driver discovery and reservation into **DriverDispatchService**, leaving **RideService** focused on trip lifecycle.",
      tradeoffsMD:
        "Cleaner at large scale, but adds network failure modes and is more HLD than core LLD.",
    },
  ],

  commonMistakes: [
    "Putting matching, pricing, state transitions, and notifications inside one huge method.",
    "Using a mutable status enum without transition guards.",
    "Forgetting to mark the driver unavailable atomically with assignment.",
    "Hard-coding nearest-driver logic so ETA or vehicle-category matching requires editing the service.",
    "Hard-coding surge math in **Trip** instead of a pricing strategy.",
    "Letting notification delivery failures roll back the trip state.",
    "Allowing terminal trips to be completed or cancelled again.",
  ],

  followUps: [
    {
      question: "How would you scale nearest-driver matching?",
      answerMD:
        "Index available drivers by geospatial cells, search the pickup cell first, expand neighboring cells, and run **MatchingStrategy** on that candidate set.",
    },
    {
      question: "How do you prevent two riders from getting one driver?",
      answerMD:
        "Make reservation atomic. The sample synchronizes **requestTrip**; production would use a compare-and-set or row lock on driver availability.",
    },
    {
      question: "Where does driver acceptance fit?",
      answerMD:
        "Add Offered and OfferExpired states. Assignment happens only after the driver accepts before timeout.",
    },
    {
      question: "How would you handle cancellation after start?",
      answerMD:
        "Let **StartedState.cancel** transition to Cancelled, compute any fee through pricing, release the driver, and notify both parties.",
    },
    {
      question: "How do notifications become reliable?",
      answerMD:
        "Write lifecycle events to an outbox in the same transaction as the trip state change, then retry delivery asynchronously.",
    },
  ],

  productionConsiderations: [
    { label: "Geospatial indexing", detailMD: "Use geohash, S2, H3, or a search backend for nearby-driver lookup, with TTL for fast-changing locations." },
    { label: "Atomic reservation", detailMD: "Reserve a driver with compare-and-set or a database row lock. If it fails, retry with the next candidate." },
    { label: "Pricing audit", detailMD: "Persist fare quote, distance estimate, surge multiplier, and policy version used at assignment time." },
    { label: "Reliable notification", detailMD: "Use an outbox and idempotent workers so push provider failures do not corrupt trip state." },
    { label: "Observability", detailMD: "Track match latency, no-driver rate, driver utilization, cancellation rate, surge distribution, and transition failures." },
  ],

  interviewNotes: [
    "Did you separate matching, pricing, lifecycle, and notifications?",
    "Is nearest-driver matching a swappable strategy rather than service glue?",
    "Does the state machine reject invalid transitions clearly?",
    "Is driver reservation atomic with trip assignment?",
    "Can the design evolve to acceptance, geospatial indexing, and reliable notifications without rewriting the model?",
  ],

  quiz: [
    {
      question: "Why should nearest-driver selection live behind **MatchingStrategy**?",
      options: [
        "So the service can swap ranking policies without changing trip flow",
        "So pricing can be skipped",
        "So Java streams become mandatory",
        "So a trip can complete before assignment",
      ],
      answerIndex: 0,
      explanationMD:
        "Matching changes frequently: nearest, ETA-based, rating-aware, vehicle-specific, or fairness-aware. Strategy keeps those variants outside the service flow.",
    },
    {
      question: "What is the purpose of **TripState**?",
      options: [
        "Store latitude and longitude",
        "Enforce legal lifecycle transitions",
        "Choose the nearest driver",
        "Send SMS directly",
      ],
      answerIndex: 1,
      explanationMD:
        "Each state controls which next actions are legal and rejects the rest.",
    },
    {
      question: "When should a matched driver become unavailable?",
      options: [
        "After reaching destination",
        "Only after the driver opens the app",
        "Inside the same atomic flow that assigns the trip",
        "Never; availability is derived only from location",
      ],
      answerIndex: 2,
      explanationMD:
        "Assignment reserves supply. Doing it atomically prevents double assignment.",
    },
    {
      question: "Why use Observer for notifications?",
      options: [
        "It lets the trip publish lifecycle changes without knowing push or SMS details",
        "It calculates the surge multiplier",
        "It replaces trip ids",
        "It guarantees exactly-once delivery across networks",
      ],
      answerIndex: 0,
      explanationMD:
        "Observer decouples domain events from delivery channels. Production reliability still needs an outbox or queue.",
    },
    {
      question: "What does Singleton represent here?",
      options: [
        "One global status enum",
        "One application-level **RideService** coordinating in-memory riders, drivers, and trips",
        "One driver for all riders",
        "One fare multiplier forever",
      ],
      answerIndex: 1,
      explanationMD:
        "The singleton keeps the demo simple and gives one synchronized coordinator for critical operations.",
    },
  ],

  practiceVariants: [
    {
      title: "Add driver acceptance timeout",
      detailMD:
        "Introduce Offered and OfferExpired states, notify the driver, and retry matching when the offer times out.",
      difficulty: "Advanced",
    },
    {
      title: "Support vehicle categories",
      detailMD:
        "Add Auto, Mini, Sedan, and SUV categories to drivers and rider requests. Update matching and pricing strategies without changing trip transitions.",
      difficulty: "Intermediate",
    },
    {
      title: "Replace scan with geohash buckets",
      detailMD:
        "Maintain available drivers by geohash cell and expand around pickup while preserving the **MatchingStrategy** contract.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    { front: "What is the core cab trip lifecycle?", back: "Requested -> Assigned -> Started -> Completed, with Cancelled as a terminal alternative." },
    { front: "Which pattern makes driver ranking swappable?", back: "Strategy through **MatchingStrategy**." },
    { front: "Which pattern guards invalid trip transitions?", back: "State through **TripState** and concrete lifecycle states." },
    { front: "What is the request critical section?", back: "Find driver, mark unavailable, create and assign trip, and store it atomically." },
    { front: "Why use Observer?", back: "The trip emits lifecycle updates while delivery channels stay outside the domain." },
    { front: "How do you scale beyond O(D) matching?", back: "Index available drivers by geospatial cells and rank nearby candidates only." },
  ],

  cheatSheetMD: [
    "**Entities:** Rider, Driver, Location, Trip, TripStatus/TripState, MatchingStrategy, PricingStrategy, TripObserver, RideService.",
    "",
    "**Patterns:** Strategy for matching and pricing; State for trip lifecycle; Observer for rider/driver notifications; Singleton for the in-memory service facade.",
    "",
    "**Flow:** requestTrip = load rider -> find nearest available driver -> estimate surge fare -> create trip -> attach observers -> reserve driver -> assign trip.",
    "",
    "**Lifecycle:** Requested -> Assigned -> Started -> Completed. Cancelled is terminal and can be reached from non-terminal states in the base design.",
    "",
    "**Invariant:** one available driver can be assigned to at most one active trip; invalid state transitions throw immediately.",
    "",
    "**Complexity:** linear scan matching O(D), lifecycle transitions O(1), notification broadcast O(observers).",
    "",
    "**Scale path:** geospatial index, transactional driver reservation, persistent trip and fare quote, outbox-backed notifications.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Refactoring Guru — Strategy, State, and Observer Patterns",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns",
    },
    {
      title: "Uber Engineering — Marketplace Reliability Engineering",
      kind: "Blog",
      url: "https://www.uber.com/blog/engineering/",
      author: "Uber Engineering",
    },
  ],

  relatedProblems: [
    { slug: "food-delivery", note: "Similar marketplace matching and order lifecycle with restaurants and couriers." },
    { slug: "movie-booking", note: "Another lifecycle-heavy booking problem where concurrency protects scarce inventory." },
    { slug: "parking-lot", note: "Smaller allocation problem with pricing strategy and atomic reservation." },
  ],
};
