import type { LLDConceptContent } from "../types";

export const concurrencyAndMultithreading: LLDConceptContent = {
  slug: "concurrency-and-multithreading",

  introMD: [
    "Concurrency and multithreading are where many otherwise clean LLD answers break under real traffic. The design question is not only which classes exist, but which objects can be touched by multiple threads, which invariants must stay atomic, and which coordination primitive is the smallest safe choice.",
    "",
    "In Amazon, Google, Oracle, and Microsoft interviews, a strong Java answer explains **visibility**, **mutual exclusion**, **atomicity**, **thread ownership**, and **shutdown behavior** before naming patterns. Producer-consumer, object pools, schedulers, message queues, caches, and booking systems all depend on these ideas.",
  ].join("\n"),

  learningObjectives: [
    "Differentiate threads, runnables, tasks, and executor-managed worker pools in Java LLD designs.",
    "Use **synchronized**, intrinsic locks, **volatile**, atomic classes, and explicit locks with clear tradeoffs.",
    "Apply the Java memory model to visibility, happens-before ordering, and safe publication.",
    "Design producer-consumer flows with **BlockingQueue** and explain backpressure.",
    "Identify deadlock causes and prevent them with ordering, timeouts, and narrow critical sections.",
    "Choose safe singleton, concurrent collection, and thread pool patterns for interview designs.",
  ],

  theory: [
    {
      title: "Concurrency starts with shared mutable state",
      detailMD: [
        "A design is concurrent when multiple operations can make progress during overlapping time. It becomes thread-sensitive when those operations touch shared mutable state, such as inventory counts, wallet balances, cache entries, booking seats, or queued tasks.",
        "",
        "In LLD, first classify state ownership:",
        "- Thread-confined state is owned by one thread or one request and needs no lock.",
        "- Immutable state can be shared freely after safe construction.",
        "- Shared mutable state needs a coordination rule: lock, atomic variable, concurrent collection, queue, or ownership handoff.",
        "",
        "This framing prevents overusing locks. Do not make every method synchronized. Protect the invariant that can break, and keep the critical section small.",
      ].join("\n"),
    },
    {
      title: "Threads versus Runnables",
      detailMD: [
        "A **Thread** is an execution vehicle managed by the JVM and operating system. A **Runnable** is the work to execute. In LLD, prefer modeling work as **Runnable** or **Callable** and letting an **ExecutorService** own thread creation, reuse, naming, and shutdown.",
        "",
        "Extending **Thread** couples the task to execution policy. Implementing **Runnable** keeps the task reusable: it can run in a fixed pool, scheduled pool, test harness, or direct executor.",
      ].join("\n"),
      code: [
        "public final class EmailJob implements Runnable {",
        "    private final String recipient;",
        "    private final EmailClient emailClient;",
        "",
        "    public EmailJob(String recipient, EmailClient emailClient) {",
        "        this.recipient = recipient;",
        "        this.emailClient = emailClient;",
        "    }",
        "",
        "    @Override",
        "    public void run() {",
        "        emailClient.sendWelcomeEmail(recipient);",
        "    }",
        "}",
        "",
        "ExecutorService pool = Executors.newFixedThreadPool(4);",
        "pool.submit(new EmailJob(\"user@example.com\", emailClient));",
      ].join("\n"),
    },
    {
      title: "The synchronized keyword and intrinsic locks",
      detailMD: [
        "**synchronized** provides mutual exclusion and visibility. Every Java object has an intrinsic monitor lock. A synchronized instance method locks **this**; a synchronized static method locks the **Class** object; a synchronized block locks the object you choose.",
        "",
        "Use it when the rule is simple: only one thread may execute this critical section at a time, and the lock is always acquired and released in a structured way. It is ideal for small counters, guarded maps, and invariant-preserving mutations.",
      ].join("\n"),
      code: [
        "public final class SeatInventory {",
        "    private int availableSeats;",
        "",
        "    public SeatInventory(int availableSeats) {",
        "        this.availableSeats = availableSeats;",
        "    }",
        "",
        "    public synchronized boolean reserveOne() {",
        "        if (availableSeats == 0) {",
        "            return false;",
        "        }",
        "        availableSeats--;",
        "        return true;",
        "    }",
        "",
        "    public synchronized int availableSeats() {",
        "        return availableSeats;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "volatile and the Java memory model",
      detailMD: [
        "**volatile** solves visibility and ordering, not compound atomicity. A write to a volatile field becomes visible to later reads of that field by other threads, creating a happens-before relationship.",
        "",
        "Use volatile for simple state signals such as stop flags, readiness flags, or publishing a fully constructed immutable reference. Do not use it for read-modify-write operations such as increment, check-then-act, or balance transfer. Those need atomic classes or locks.",
      ].join("\n"),
      code: [
        "public final class StopSignal {",
        "    private volatile boolean shutdownRequested;",
        "",
        "    public void requestShutdown() {",
        "        shutdownRequested = true;",
        "    }",
        "",
        "    public void runLoop() {",
        "        while (!shutdownRequested) {",
        "            doOneUnitOfWork();",
        "        }",
        "    }",
        "",
        "    private void doOneUnitOfWork() {",
        "        // process a small unit of work",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Atomic classes for lock-free single-variable updates",
      detailMD: [
        "Atomic classes such as **AtomicInteger**, **AtomicLong**, and **AtomicReference** provide atomic read-modify-write operations using compare-and-set style CPU instructions. They are excellent for counters, sequence generators, state transitions, and one-reference swaps.",
        "",
        "The boundary is important: atomics protect one variable or one reference. If an invariant spans multiple fields, such as debiting one wallet and crediting another, use a lock or a higher-level transaction boundary.",
      ].join("\n"),
      code: [
        "public final class RequestIdGenerator {",
        "    private final AtomicLong nextId = new AtomicLong(1);",
        "",
        "    public long next() {",
        "        return nextId.getAndIncrement();",
        "    }",
        "}",
        "",
        "public final class CircuitState {",
        "    private final AtomicReference<State> state = new AtomicReference<>(State.CLOSED);",
        "",
        "    public boolean openIfClosed() {",
        "        return state.compareAndSet(State.CLOSED, State.OPEN);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "ReentrantLock and ReadWriteLock",
      detailMD: [
        "**ReentrantLock** is an explicit lock with capabilities that intrinsic locks do not expose: timed acquisition, interruptible acquisition, fairness options, multiple conditions, and try-lock based recovery. Always release it in a finally block.",
        "",
        "**ReadWriteLock** separates readers from writers. Many readers can hold the read lock together, but writers need exclusive access. It fits read-heavy structures such as configuration stores, catalog snapshots, and metadata registries. It can hurt write-heavy flows because coordination overhead grows.",
      ].join("\n"),
      code: [
        "public final class Catalog {",
        "    private final ReadWriteLock lock = new ReentrantReadWriteLock();",
        "    private final Map<String, Product> products = new HashMap<>();",
        "",
        "    public Product find(String id) {",
        "        lock.readLock().lock();",
        "        try {",
        "            return products.get(id);",
        "        } finally {",
        "            lock.readLock().unlock();",
        "        }",
        "    }",
        "",
        "    public void upsert(Product product) {",
        "        lock.writeLock().lock();",
        "        try {",
        "            products.put(product.id(), product);",
        "        } finally {",
        "            lock.writeLock().unlock();",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "ExecutorService and thread pools",
      detailMD: [
        "**ExecutorService** decouples task submission from thread management. A pool reuses a bounded number of worker threads, which avoids creating a new operating system thread per request and gives the design a clear concurrency limit.",
        "",
        "In interviews, name the pool type and why it fits: fixed pools for bounded parallelism, scheduled pools for delayed or periodic jobs, cached pools only for short-lived bursty tasks with strict safeguards, and custom **ThreadPoolExecutor** when you need queue size, rejection policy, and metrics.",
      ].join("\n"),
      code: [
        "public final class ThumbnailService implements AutoCloseable {",
        "    private final ExecutorService workers = Executors.newFixedThreadPool(8);",
        "",
        "    public Future<Thumbnail> createAsync(Image image) {",
        "        return workers.submit(() -> createThumbnail(image));",
        "    }",
        "",
        "    private Thumbnail createThumbnail(Image image) {",
        "        return new Thumbnail(image.id());",
        "    }",
        "",
        "    @Override",
        "    public void close() {",
        "        workers.shutdown();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "BlockingQueue and Producer-Consumer",
      detailMD: [
        "**BlockingQueue** is the cleanest Java building block for producer-consumer designs. Producers call **put** or **offer** to enqueue work. Consumers call **take** or **poll** to receive work. The queue owns the waiting logic and can provide backpressure when capacity is bounded.",
        "",
        "This pattern is useful in message queues, task schedulers, logging frameworks, notification systems, and object pools. The LLD goal is to keep producers unaware of consumer threads and keep consumers unaware of request threads.",
      ].join("\n"),
      code: [
        "public final class WorkQueue {",
        "    private final BlockingQueue<Task> queue = new ArrayBlockingQueue<>(100);",
        "",
        "    public void submit(Task task) throws InterruptedException {",
        "        queue.put(task);",
        "    }",
        "",
        "    public void startWorker() {",
        "        Thread worker = new Thread(() -> {",
        "            while (!Thread.currentThread().isInterrupted()) {",
        "                try {",
        "                    Task task = queue.take();",
        "                    task.run();",
        "                } catch (InterruptedException interrupted) {",
        "                    Thread.currentThread().interrupt();",
        "                }",
        "            }",
        "        });",
        "        worker.start();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Object Pool as bounded concurrent ownership",
      detailMD: [
        "The **Object Pool** pattern reuses expensive resources such as database connections, parser instances, or reusable buffers. In concurrent designs, the pool is also a capacity controller: only callers that borrow a resource can proceed.",
        "",
        "A **BlockingQueue** often represents the idle resources. Borrow with a timeout, return in a finally block, and make double release or leaked resources visible through metrics. This is more explicit than letting every request create its own expensive object.",
      ].join("\n"),
      code: [
        "public final class ConnectionPool {",
        "    private final BlockingQueue<Connection> available;",
        "",
        "    public ConnectionPool(List<Connection> connections) {",
        "        available = new ArrayBlockingQueue<>(connections.size());",
        "        available.addAll(connections);",
        "    }",
        "",
        "    public Connection borrow(Duration timeout) throws InterruptedException {",
        "        Connection connection = available.poll(timeout.toMillis(), TimeUnit.MILLISECONDS);",
        "        if (connection == null) {",
        "            throw new IllegalStateException(\"no connection available\");",
        "        }",
        "        return connection;",
        "    }",
        "",
        "    public void release(Connection connection) {",
        "        if (connection != null) {",
        "            available.offer(connection);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Deadlock causes and avoidance",
      detailMD: [
        "Deadlock appears when threads wait forever in a cycle. The classic causes are mutual exclusion, hold-and-wait, no preemption, and circular wait. In LLD, the most common bug is acquiring multiple locks in inconsistent order, such as wallet A then wallet B in one transfer and wallet B then wallet A in another.",
        "",
        "Avoidance tactics are practical: define a global lock order, avoid calling external code while holding locks, keep critical sections short, use **tryLock** with timeout for recovery, and prefer one lock per invariant rather than one lock per method.",
      ].join("\n"),
      code: [
        "public final class WalletTransferService {",
        "    public void transfer(Wallet from, Wallet to, long cents) {",
        "        Wallet first = from.id().compareTo(to.id()) < 0 ? from : to;",
        "        Wallet second = first == from ? to : from;",
        "",
        "        synchronized (first) {",
        "            synchronized (second) {",
        "                from.debit(cents);",
        "                to.credit(cents);",
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Thread-safe Singleton",
      detailMD: [
        "A singleton is thread-safe only when construction and publication are safe. The simplest Java options are an enum singleton or the initialization-on-demand holder idiom. Both rely on JVM class initialization guarantees.",
        "",
        "Avoid naive lazy initialization with a plain static field because two threads can observe null and create two instances. Double-checked locking is valid only when the instance field is volatile, but the holder idiom is usually easier to explain.",
      ].join("\n"),
      code: [
        "public final class MetricsRegistry {",
        "    private MetricsRegistry() {",
        "    }",
        "",
        "    private static final class Holder {",
        "        private static final MetricsRegistry INSTANCE = new MetricsRegistry();",
        "    }",
        "",
        "    public static MetricsRegistry instance() {",
        "        return Holder.INSTANCE;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Concurrent collections",
      detailMD: [
        "Concurrent collections are not just synchronized wrappers. They are designed for high-concurrency access with internal partitioning, lock-free reads, snapshot semantics, or blocking behavior.",
        "",
        "**ConcurrentHashMap** is the default for shared maps with concurrent reads and updates. Use atomic methods such as **computeIfAbsent**, **merge**, and **putIfAbsent** instead of check-then-act sequences.",
        "",
        "**CopyOnWriteArrayList** copies the array on mutation and gives readers stable snapshots. It is excellent for mostly-read listener lists and configuration observers, but poor for frequent writes or large lists.",
      ].join("\n"),
      code: [
        "public final class ListenerRegistry {",
        "    private final CopyOnWriteArrayList<Listener> listeners = new CopyOnWriteArrayList<>();",
        "    private final ConcurrentHashMap<String, Session> sessions = new ConcurrentHashMap<>();",
        "",
        "    public void addListener(Listener listener) {",
        "        listeners.add(listener);",
        "    }",
        "",
        "    public Session sessionFor(String userId) {",
        "        return sessions.computeIfAbsent(userId, Session::new);",
        "    }",
        "",
        "    public void publish(Event event) {",
        "        for (Listener listener : listeners) {",
        "            listener.onEvent(event);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  diagrams: [
    {
      title: "Producer-consumer with bounded queue backpressure",
      mermaid: [
        "stateDiagram-v2",
        "    [*] --> QueueEmpty",
        "    QueueEmpty --> HasWork: producer put task",
        "    HasWork --> QueueFull: producers fill capacity",
        "    QueueFull --> HasWork: consumer take task",
        "    HasWork --> QueueEmpty: consumers drain all tasks",
        "    QueueEmpty --> ConsumerWaiting: consumer take waits",
        "    ConsumerWaiting --> HasWork: producer put task",
        "    QueueFull --> ProducerWaiting: producer put waits",
        "    ProducerWaiting --> HasWork: consumer take task",
      ].join("\n"),
      captionMD:
        "A bounded BlockingQueue becomes the coordination point. Producers are slowed when capacity is full, consumers wait when no work exists, and neither side needs to manage the other side's threads directly.",
    },
  ],

  comparisons: [
    {
      title: "synchronized vs ReentrantLock",
      columns: ["Dimension", "synchronized", "ReentrantLock", "LLD guidance"],
      rows: [
        [
          "Lock ownership",
          "Uses an object's intrinsic monitor",
          "Uses an explicit lock object",
          "Prefer synchronized for simple critical sections and ReentrantLock for advanced control",
        ],
        [
          "Release behavior",
          "Automatically released when the block exits",
          "Must be released in a finally block",
          "If the candidate forgets finally, the design can freeze under exceptions",
        ],
        [
          "Timed acquisition",
          "No built-in try with timeout",
          "Supports tryLock and interruptible lock acquisition",
          "Use explicit locks when deadlock recovery or graceful cancellation matters",
        ],
        [
          "Conditions",
          "One wait set per intrinsic lock",
          "Can create multiple Condition objects",
          "Use explicit conditions for complex producer-consumer state machines",
        ],
        [
          "Fairness",
          "No fairness configuration",
          "Optional fairness constructor",
          "Fairness can reduce starvation but may lower throughput",
        ],
      ],
    },
    {
      title: "volatile vs atomic classes",
      columns: ["Dimension", "volatile", "Atomic classes", "LLD guidance"],
      rows: [
        [
          "Primary guarantee",
          "Visibility and ordering for reads and writes",
          "Atomic read-modify-write operations",
          "Use volatile for signals and atomics for counters or state transitions",
        ],
        [
          "Compound updates",
          "Does not make increment or check-then-act atomic",
          "Supports operations such as incrementAndGet and compareAndSet",
          "Never protect counters with volatile alone",
        ],
        [
          "State scope",
          "Best for one independent flag or reference",
          "Best for one independent numeric value or reference",
          "Use locks when multiple fields must change together",
        ],
        [
          "Common LLD example",
          "Shutdown flag for a worker loop",
          "Request id generator or retry counter",
          "Explain the invariant before choosing either primitive",
        ],
      ],
    },
  ],

  bestPractices: [
    "Start each LLD answer by naming which state is immutable, thread-confined, or shared mutable.",
    "Use the smallest primitive that protects the invariant: volatile for visibility, atomics for one-variable updates, locks for multi-field invariants, queues for handoff.",
    "Prefer ExecutorService over manual thread creation so concurrency limits, shutdown, and monitoring have a single owner.",
    "Use bounded queues for producer-consumer flows unless the interview explicitly accepts unbounded memory growth.",
    "Always release explicit locks in finally and restore the interrupt flag after catching InterruptedException.",
    "Use ConcurrentHashMap atomic methods instead of separate contains and put calls.",
    "Keep critical sections small and never call slow network, disk, or user callback code while holding a lock.",
    "Design shutdown paths: stop accepting work, drain or cancel queued work, interrupt workers if needed, and expose completion status.",
  ],

  commonMistakes: [
    "Assuming volatile makes increment, list updates, or check-then-act logic atomic.",
    "Synchronizing every public method without understanding which invariant is being protected.",
    "Creating raw threads per request instead of using a bounded executor or queue.",
    "Using an unbounded queue in front of a fixed thread pool and calling it scalable.",
    "Holding two locks in inconsistent order, causing rare but severe deadlocks.",
    "Catching InterruptedException and continuing without restoring the thread interrupt status.",
    "Using HashMap or ArrayList as shared state without synchronization or a concurrent alternative.",
    "Choosing CopyOnWriteArrayList for write-heavy data and paying a copy cost on every mutation.",
  ],

  quiz: [
    {
      question: "What is the best LLD distinction between a Thread and a Runnable?",
      options: [
        "A Thread is the execution vehicle, while a Runnable is the task to execute",
        "A Runnable always creates a new operating system process",
        "A Thread cannot execute Java code",
        "A Runnable is automatically faster than every Callable",
      ],
      answerIndex: 0,
      explanationMD:
        "Separating task from execution policy lets an ExecutorService manage thread reuse, capacity, shutdown, and scheduling.",
    },
    {
      question: "Which guarantee does volatile provide?",
      options: [
        "Mutual exclusion for a critical section",
        "Visibility and ordering for reads and writes of the volatile field",
        "Atomicity for a balance transfer across two objects",
        "Automatic retry when a thread is interrupted",
      ],
      answerIndex: 1,
      explanationMD:
        "volatile is about visibility and happens-before ordering. It does not make compound operations atomic.",
    },
    {
      question: "When is ReentrantLock a better fit than synchronized?",
      options: [
        "When no shared state exists",
        "When timed lock acquisition or interruptible lock acquisition is required",
        "When a field should be immutable",
        "When all work must run on the main thread",
      ],
      answerIndex: 1,
      explanationMD:
        "ReentrantLock exposes tryLock, timed waits, interruptible acquisition, fairness, and multiple conditions.",
    },
    {
      question: "Why is BlockingQueue useful in Producer-Consumer designs?",
      options: [
        "It removes the need to define tasks",
        "It makes every task execute in priority order",
        "It handles thread-safe handoff and can apply backpressure",
        "It prevents consumers from ever blocking",
      ],
      answerIndex: 2,
      explanationMD:
        "BlockingQueue owns safe handoff between producers and consumers. Bounded queues also slow producers when consumers fall behind.",
    },
    {
      question: "Which choice best avoids deadlock when two wallet locks are needed?",
      options: [
        "Acquire locks in a consistent global order",
        "Make both wallet fields public",
        "Use a larger unbounded thread pool",
        "Retry forever while holding the first lock",
      ],
      answerIndex: 0,
      explanationMD:
        "A consistent lock order breaks the circular wait condition, which is one of the necessary deadlock conditions.",
    },
    {
      question: "Which singleton implementation is naturally thread-safe in Java?",
      options: [
        "A lazy static field without synchronization",
        "The initialization-on-demand holder idiom",
        "A public mutable static field",
        "A new instance returned on every call",
      ],
      answerIndex: 1,
      explanationMD:
        "The holder idiom relies on JVM class initialization guarantees to create and publish the instance safely.",
    },
    {
      question: "When is CopyOnWriteArrayList a good fit?",
      options: [
        "A large list with frequent writes",
        "A mostly-read listener registry with rare additions or removals",
        "A queue with millions of producer events per second",
        "A map that needs atomic key insertion",
      ],
      answerIndex: 1,
      explanationMD:
        "CopyOnWriteArrayList gives readers stable snapshots but copies on writes, so it fits read-heavy listener or observer lists.",
    },
  ],

  flashcards: [
    {
      front: "What question should you ask before adding a lock?",
      back: "Which shared mutable invariant can break if two threads interleave operations?",
    },
    {
      front: "What does synchronized provide?",
      back: "Mutual exclusion through an intrinsic lock plus visibility guarantees when entering and exiting the synchronized region.",
    },
    {
      front: "What does volatile not provide?",
      back: "It does not make compound operations such as increment, check-then-act, or multi-field updates atomic.",
    },
    {
      front: "When should you use AtomicInteger or AtomicLong?",
      back: "For independent counters, ids, and single-variable state transitions that need atomic read-modify-write operations.",
    },
    {
      front: "Why use BlockingQueue in Producer-Consumer?",
      back: "It provides thread-safe handoff, optional bounded capacity, producer backpressure, and consumer waiting without manual wait-notify code.",
    },
    {
      front: "What is the main deadlock prevention rule for multiple locks?",
      back: "Acquire locks in a consistent global order and keep the locked region small.",
    },
    {
      front: "What is the safe singleton holder idiom?",
      back: "A private static nested holder class owns the instance, and JVM class initialization safely creates it on first access.",
    },
    {
      front: "When is ConcurrentHashMap preferred over HashMap?",
      back: "When a map is shared across threads and needs concurrent reads or atomic updates such as computeIfAbsent.",
    },
  ],

  cheatSheetMD: [
    "**Concurrency framing:** Identify immutable state, thread-confined state, and shared mutable state before choosing a primitive.",
    "",
    "**Thread vs Runnable:** Thread is execution. Runnable is work. Prefer Runnable or Callable submitted to ExecutorService.",
    "",
    "**synchronized:** Simple mutual exclusion using intrinsic locks. Good for small invariant-preserving critical sections.",
    "",
    "**volatile:** Visibility and ordering for a single field. Good for stop flags and readiness signals, not compound updates.",
    "",
    "**Atomic classes:** Lock-free atomic updates for one variable. Good for counters, ids, and compare-and-set state transitions.",
    "",
    "**Explicit locks:** ReentrantLock adds tryLock, timeout, interruptible acquisition, fairness, and multiple conditions. ReadWriteLock helps read-heavy data.",
    "",
    "**ExecutorService:** Owns thread reuse, bounded parallelism, task submission, shutdown, and rejection behavior.",
    "",
    "**Producer-Consumer:** Use BlockingQueue for safe handoff and bounded backpressure between producers and worker consumers.",
    "",
    "**Object Pool:** Use a bounded pool for expensive reusable resources. Borrow with timeout and always release in finally.",
    "",
    "**Deadlock avoidance:** Use global lock ordering, short critical sections, no external calls under locks, and timeouts when recovery matters.",
    "",
    "**Safe singleton:** Prefer enum singleton or initialization-on-demand holder. Use volatile only if explaining double-checked locking.",
    "",
    "**Concurrent collections:** Use ConcurrentHashMap for shared maps and CopyOnWriteArrayList for mostly-read listener lists.",
  ].join("\n"),

  references: [
    {
      title: "Java Concurrency in Practice",
      kind: "Book",
      author: "Brian Goetz, Tim Peierls, Joshua Bloch, Joseph Bowbeer, David Holmes, and Doug Lea",
    },
    {
      title: "Effective Java",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Oracle Java Documentation: java.util.concurrent",
      kind: "Docs",
      url: "https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/package-summary.html",
    },
    {
      title: "Oracle Java Tutorials: Concurrency",
      kind: "Docs",
      url: "https://docs.oracle.com/javase/tutorial/essential/concurrency/",
    },
  ],

  relatedProblems: [
    { slug: "java-collections-for-lld", note: "Concurrent collections build on core Java collection choices and their mutation semantics." },
    { slug: "message-queue", note: "Producer-consumer, blocking queues, worker pools, and backpressure are central to queue design." },
    { slug: "task-scheduler", note: "Executors, scheduled workers, cancellation, and safe task state are common scheduler building blocks." },
  ],
};
