import type { LLDProblemContent } from "../types";

export const digitalWallet: LLDProblemContent = {
  slug: "digital-wallet",

  statementMD: [
    "Design a **digital wallet** like Paytm or PayPal where users hold wallet accounts,",
    "top up money, withdraw money, and transfer money to other users. The core design",
    "must protect monetary correctness: every balance mutation is backed by a",
    "**double-entry ledger**, every client retry is guarded by an **idempotency key**,",
    "and every transaction moves through a clear state machine.",
    "",
    "The interview focus is not a payment gateway integration or a REST API. It is the",
    "domain model and service boundary that make wallet money safe under concurrency,",
    "especially when two transfers try to debit the same account at the same time.",
  ].join("\n"),

  businessContextMD: [
    "Digital Wallet is a strong mid-level LLD round because it combines familiar product",
    "flows with serious invariants. A candidate must model wallets and accounts, choose",
    "where balances live, record immutable ledger entries, prevent duplicate retries,",
    "and explain why a transfer cannot leave money half-moved. Companies like PayPal,",
    "Amazon, Flipkart, and Uber use this style of question to test whether you can move",
    "from CRUD objects to correctness-first design.",
  ].join("\n"),

  functionalRequirements: [
    "Create a wallet for a user and attach one or more currency-specific accounts.",
    "Credit an account from an external source such as bank top-up or card load.",
    "Debit an account to an external sink such as withdrawal or merchant payment.",
    "Transfer money between two accounts in the same currency.",
    "Record every successful money movement as balanced debit and credit ledger entries.",
    "Track each transaction through statuses such as INITIATED, PENDING, POSTED, FAILED, and REVERSED.",
    "Accept an idempotency key so a retried credit, debit, or transfer returns the original transaction.",
    "Expose balances, transaction status, and the immutable ledger history for audit/debugging.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Monetary correctness",
      detailMD:
        "A posted transaction must be balanced: total debits equal total credits. For transfers, the source debit and destination credit happen in one critical section.",
    },
    {
      label: "Thread safety",
      detailMD:
        "Concurrent debits and transfers on the same account must serialize. The implementation locks accounts in deterministic id order to avoid deadlocks.",
    },
    {
      label: "Idempotency",
      detailMD:
        "Network retries must not duplicate money movement. The service stores the first result for each idempotency key and returns it for repeats.",
    },
    {
      label: "Auditability",
      detailMD:
        "Balances are fast reads, but the ledger is the source of truth for explaining how a balance was reached.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Currency rules, notification behavior, and transaction commands should be replaceable without editing the transfer algorithm.",
    },
  ],

  requirementClarification: [
    {
      question: "Can one wallet hold multiple currencies?",
      answerMD:
        "Yes. Model each currency as a separate **Account** under the wallet. The base transfer only allows same-currency account pairs.",
    },
    {
      question: "Do we integrate with banks, cards, or UPI directly?",
      answerMD:
        "No. Treat outside money as an **EXTERNAL** ledger counterparty. Real payment rails become adapters around credit/debit commands.",
    },
    {
      question: "Should failed transactions appear in history?",
      answerMD:
        "Yes. They are useful for idempotent retries and support investigations, but they do not create ledger entries or mutate balances.",
    },
    {
      question: "Are balances computed from ledger entries on every read?",
      answerMD:
        "Not in the interview implementation. Accounts keep a cached balance for fast reads, and the ledger provides the immutable audit trail.",
    },
    {
      question: "What does atomic transfer mean in an in-memory LLD answer?",
      answerMD:
        "The source debit, destination credit, ledger append, and status transition are guarded by ordered account locks plus one idempotency boundary.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class WalletService {",
    "        -Map~String,Wallet~ wallets",
    "        -Map~String,Account~ accounts",
    "        -Map~String,Transaction~ transactionsByIdempotencyKey",
    "        -List~LedgerEntry~ ledger",
    "        -CurrencyPolicy currencyPolicy",
    "        +credit(String, long, String, String) Transaction",
    "        +debit(String, long, String, String) Transaction",
    "        +transfer(String, String, long, String, String) Transaction",
    "    }",
    "    class Wallet {",
    "        -String id",
    "        -String ownerId",
    "        -Map~String,Account~ accounts",
    "        +addAccount(Account) void",
    "        +account(String) Account",
    "    }",
    "    class Account {",
    "        -String id",
    "        -String walletId",
    "        -String currency",
    "        -long balanceInCents",
    "        -ReentrantLock lock",
    "        +balanceInCents() long",
    "    }",
    "    class Transaction {",
    "        -String id",
    "        -String idempotencyKey",
    "        -TransactionStatus status",
    "        -List~LedgerEntry~ ledgerEntries",
    "        +transitionTo(TransactionStatus) void",
    "    }",
    "    class TransactionStatus {",
    "        <<enumeration>>",
    "        INITIATED",
    "        PENDING",
    "        POSTED",
    "        FAILED",
    "        REVERSED",
    "    }",
    "    class LedgerEntry {",
    "        -String transactionId",
    "        -String accountId",
    "        -LedgerEntryType type",
    "        -long amountInCents",
    "    }",
    "    class TransactionCommand {",
    "        <<interface>>",
    "        +idempotencyKey() String",
    "        +execute(WalletService) Transaction",
    "    }",
    "    class CurrencyPolicy {",
    "        <<interface>>",
    "        +validateTransfer(Account, Account, String) void",
    "    }",
    "    class TransactionObserver {",
    "        <<interface>>",
    "        +onTransactionPosted(Transaction) void",
    "    }",
    "    WalletService o-- Wallet",
    "    Wallet o-- Account",
    "    WalletService --> Account",
    "    WalletService o-- Transaction",
    "    WalletService o-- LedgerEntry",
    "    Transaction o-- LedgerEntry",
    "    Transaction --> TransactionStatus",
    "    WalletService ..> TransactionCommand",
    "    WalletService ..> CurrencyPolicy",
    "    WalletService ..> TransactionObserver",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service is the aggregate boundary for money movement. Wallets own accounts, transactions own their ledger entries, and the service coordinates idempotency, locking, policy, and observers.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Client",
    "    participant Service as WalletService",
    "    participant Cmd as TransferCommand",
    "    participant Src as SourceAccount",
    "    participant Dst as DestinationAccount",
    "    participant Txn as Transaction",
    "    participant Obs as TransactionObserver",
    "    Client->>Service: transfer(source, dest, amount, currency, key)",
    "    Service->>Service: check transactionsByIdempotencyKey",
    "    alt key already seen",
    "        Service-->>Client: original Transaction",
    "    else first request",
    "        Service->>Cmd: execute(service)",
    "        Cmd->>Service: applyTransfer(...)",
    "        Service->>Txn: transition INITIATED to PENDING",
    "        Service->>Src: lock and debit",
    "        Service->>Dst: lock and credit",
    "        Service->>Txn: attach debit and credit entries",
    "        Service->>Txn: transition PENDING to POSTED",
    "        Service->>Obs: onTransactionPosted(transaction)",
    "        Service-->>Client: posted Transaction",
    "    end",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Idempotency is checked before the command mutates money. The transfer command posts only after both account balances and both ledger entries are updated under ordered locks.",

  entities: [
    {
      name: "WalletService",
      responsibilityMD:
        "Facade and transaction boundary. Owns wallets, accounts, idempotency keys, ledger storage, account locking order, policy checks, and post-commit notifications.",
      attributes: ["wallets", "accounts", "transactionsByIdempotencyKey", "ledger", "currencyPolicy", "observers"],
    },
    {
      name: "Wallet",
      responsibilityMD:
        "User-facing container that groups one user's accounts. It validates that added accounts belong to the wallet and returns defensive account maps.",
      attributes: ["id", "ownerId", "accounts"],
    },
    {
      name: "Account",
      responsibilityMD:
        "Currency-specific balance holder. It exposes a safe balance read and package-level locked credit/debit operations used only by the service.",
      attributes: ["id", "walletId", "currency", "balanceInCents", "lock"],
    },
    {
      name: "Transaction",
      responsibilityMD:
        "Lifecycle record for a credit, debit, or transfer. It stores idempotency key, type, amount, endpoints, status, timestamps, and attached ledger entries.",
      attributes: ["id", "idempotencyKey", "type", "amountInCents", "status", "ledgerEntries"],
    },
    {
      name: "TransactionStatus",
      responsibilityMD:
        "State machine for transaction lifecycle. Each enum state decides which next states are legal, so invalid jumps such as INITIATED to POSTED are rejected.",
      attributes: ["INITIATED", "PENDING", "POSTED", "FAILED", "REVERSED"],
    },
    {
      name: "LedgerEntry",
      responsibilityMD:
        "Immutable journal row. A posted wallet movement has one debit row and one credit row, tied by the same transaction id.",
      attributes: ["id", "transactionId", "accountId", "type", "amountInCents", "currency", "createdAt"],
    },
    {
      name: "TransactionCommand",
      responsibilityMD:
        "Command interface for credit, debit, and transfer requests. Each concrete command captures request parameters and calls the service apply method.",
      attributes: ["idempotencyKey", "execute(service)"],
    },
    {
      name: "CurrencyPolicy",
      responsibilityMD:
        "Strategy interface for currency compatibility. The default policy allows only same-currency transfers and exact account-currency matches.",
      attributes: ["validateSingle", "validateTransfer"],
    },
    {
      name: "TransactionObserver",
      responsibilityMD:
        "Observer seam for receipts, notifications, analytics, or fraud hooks after a transaction posts.",
      attributes: ["onTransactionPosted(transaction)"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**TransactionStatus** owns legal transitions. The transaction lifecycle is explicit and invalid jumps fail fast instead of being hidden in service conditionals.",
    },
    {
      name: "Command",
      whyMD:
        "**CreditCommand**, **DebitCommand**, and **TransferCommand** encapsulate request parameters and execution. This makes retries, logging, authorization, and queuing easier to add around the same command interface.",
    },
    {
      name: "Observer",
      whyMD:
        "**TransactionObserver** lets the service notify receipts, analytics, or fraud listeners after a posted transaction without coupling core money movement to side effects.",
    },
    {
      name: "Strategy",
      whyMD:
        "**CurrencyPolicy** makes currency compatibility pluggable. The base policy rejects cross-currency movement; a future FX policy can quote and convert without rewriting transfer locking.",
    },
  ],

  designSteps: [
    {
      title: "Start from money invariants, not screens",
      detailMD:
        "The central invariant is **no lost money**. Every posted transaction must have balanced ledger entries, and transfer must debit one account and credit the other while both accounts are locked.",
    },
    {
      title: "Represent transaction lifecycle as a state machine",
      detailMD:
        "Do not use free-form strings for status. Put legal transitions beside the status values so a transaction cannot skip from INITIATED directly to POSTED.",
      code: [
        "enum TransactionStatus {",
        "    INITIATED {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == PENDING || next == FAILED;",
        "        }",
        "    },",
        "    PENDING {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == POSTED || next == FAILED;",
        "        }",
        "    },",
        "    POSTED {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == REVERSED;",
        "        }",
        "    },",
        "    FAILED, REVERSED;",
        "",
        "    boolean canMoveTo(TransactionStatus next) {",
        "        return false;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Use double-entry ledger rows for every posted movement",
      detailMD:
        "Balances are convenient cached state; ledger entries explain the truth. A top-up debits **EXTERNAL** and credits the account. A transfer debits the source and credits the destination.",
      code: [
        "List<LedgerEntry> entries = Arrays.asList(",
        "    LedgerEntry.debit(transaction.id(), source.id(), amountInCents, currency),",
        "    LedgerEntry.credit(transaction.id(), destination.id(), amountInCents, currency)",
        ");",
        "transaction.attachLedgerEntries(entries);",
      ].join("\n"),
    },
    {
      title: "Make transfer atomic with deterministic account locks",
      detailMD:
        "Always acquire the lower account id lock first and release in reverse order. This serializes competing transfers on shared accounts and avoids deadlock when A pays B while B pays A.",
      code: [
        "private void lockInIdOrder(Account first, Account second) {",
        "    if (first.id().compareTo(second.id()) <= 0) {",
        "        first.lock();",
        "        second.lock();",
        "    } else {",
        "        second.lock();",
        "        first.lock();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Put idempotency around the whole command",
      detailMD:
        "The idempotency map is checked before any command mutates balances. A duplicate key returns the original **Transaction**, including a failed transaction, instead of running the debit again.",
      code: [
        "synchronized (transactionsByIdempotencyKey) {",
        "    Transaction existing = transactionsByIdempotencyKey.get(idempotencyKey);",
        "    if (existing != null) {",
        "        return existing;",
        "    }",
        "    Transaction created = action.get();",
        "    transactionsByIdempotencyKey.put(idempotencyKey, created);",
        "    return created;",
        "}",
      ].join("\n"),
    },
    {
      title: "Separate policy and side effects from posting",
      detailMD:
        "**CurrencyPolicy** decides whether accounts are compatible before locks mutate balances. **TransactionObserver** runs after POSTED, so notification failures do not corrupt money movement.",
    },
  ],

  implementation: [
    {
      filename: "Wallet.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class Wallet {",
        "    private final String id;",
        "    private final String ownerId;",
        "    private final Map<String, Account> accounts = new LinkedHashMap<>();",
        "",
        "    public Wallet(String id, String ownerId) {",
        "        this.id = requireText(id, \"id\");",
        "        this.ownerId = requireText(ownerId, \"ownerId\");",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String ownerId() {",
        "        return ownerId;",
        "    }",
        "",
        "    public synchronized void addAccount(Account account) {",
        "        Objects.requireNonNull(account, \"account\");",
        "        if (!id.equals(account.walletId())) {",
        "            throw new IllegalArgumentException(\"account belongs to another wallet\");",
        "        }",
        "        if (accounts.containsKey(account.id())) {",
        "            throw new IllegalArgumentException(\"duplicate account id\");",
        "        }",
        "        accounts.put(account.id(), account);",
        "    }",
        "",
        "    public synchronized Account account(String accountId) {",
        "        Account account = accounts.get(accountId);",
        "        if (account == null) {",
        "            throw new IllegalArgumentException(\"unknown account: \" + accountId);",
        "        }",
        "        return account;",
        "    }",
        "",
        "    public synchronized Map<String, Account> accounts() {",
        "        return Collections.unmodifiableMap(new LinkedHashMap<>(accounts));",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Account.java",
      language: "java",
      content: [
        "import java.util.concurrent.locks.ReentrantLock;",
        "",
        "public final class Account {",
        "    private final String id;",
        "    private final String walletId;",
        "    private final String currency;",
        "    private long balanceInCents;",
        "    private final ReentrantLock lock = new ReentrantLock();",
        "",
        "    public Account(String id, String walletId, String currency, long openingBalanceInCents) {",
        "        this.id = requireText(id, \"id\");",
        "        this.walletId = requireText(walletId, \"walletId\");",
        "        this.currency = requireText(currency, \"currency\");",
        "        if (openingBalanceInCents < 0) {",
        "            throw new IllegalArgumentException(\"opening balance cannot be negative\");",
        "        }",
        "        this.balanceInCents = openingBalanceInCents;",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String walletId() {",
        "        return walletId;",
        "    }",
        "",
        "    public String currency() {",
        "        return currency;",
        "    }",
        "",
        "    public long balanceInCents() {",
        "        lock.lock();",
        "        try {",
        "            return balanceInCents;",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    void lock() {",
        "        lock.lock();",
        "    }",
        "",
        "    void unlock() {",
        "        lock.unlock();",
        "    }",
        "",
        "    void creditLocked(long amountInCents) {",
        "        requirePositive(amountInCents);",
        "        balanceInCents += amountInCents;",
        "    }",
        "",
        "    void debitLocked(long amountInCents) {",
        "        requirePositive(amountInCents);",
        "        if (balanceInCents < amountInCents) {",
        "            throw new IllegalStateException(\"insufficient funds\");",
        "        }",
        "        balanceInCents -= amountInCents;",
        "    }",
        "",
        "    static void requirePositive(long amountInCents) {",
        "        if (amountInCents <= 0) {",
        "            throw new IllegalArgumentException(\"amount must be positive\");",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Transaction.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Transaction {",
        "    private final String id;",
        "    private final String idempotencyKey;",
        "    private final TransactionType type;",
        "    private final long amountInCents;",
        "    private final String fromAccountId;",
        "    private final String toAccountId;",
        "    private final Instant createdAt;",
        "    private final List<LedgerEntry> ledgerEntries = new ArrayList<>();",
        "    private TransactionStatus status;",
        "    private Instant updatedAt;",
        "",
        "    private Transaction(String id, String idempotencyKey, TransactionType type, long amountInCents, String fromAccountId, String toAccountId) {",
        "        this.id = requireText(id, \"id\");",
        "        this.idempotencyKey = requireText(idempotencyKey, \"idempotencyKey\");",
        "        this.type = Objects.requireNonNull(type, \"type\");",
        "        Account.requirePositive(amountInCents);",
        "        this.amountInCents = amountInCents;",
        "        this.fromAccountId = fromAccountId;",
        "        this.toAccountId = toAccountId;",
        "        this.createdAt = Instant.now();",
        "        this.updatedAt = createdAt;",
        "        this.status = TransactionStatus.INITIATED;",
        "    }",
        "",
        "    public static Transaction start(String id, String idempotencyKey, TransactionType type, long amountInCents, String fromAccountId, String toAccountId) {",
        "        return new Transaction(id, idempotencyKey, type, amountInCents, fromAccountId, toAccountId);",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String idempotencyKey() {",
        "        return idempotencyKey;",
        "    }",
        "",
        "    public TransactionType type() {",
        "        return type;",
        "    }",
        "",
        "    public long amountInCents() {",
        "        return amountInCents;",
        "    }",
        "",
        "    public String fromAccountId() {",
        "        return fromAccountId;",
        "    }",
        "",
        "    public String toAccountId() {",
        "        return toAccountId;",
        "    }",
        "",
        "    public synchronized TransactionStatus status() {",
        "        return status;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public synchronized Instant updatedAt() {",
        "        return updatedAt;",
        "    }",
        "",
        "    public synchronized void transitionTo(TransactionStatus next) {",
        "        Objects.requireNonNull(next, \"next\");",
        "        if (!status.canMoveTo(next)) {",
        "            throw new IllegalStateException(\"cannot transition from \" + status + \" to \" + next);",
        "        }",
        "        status = next;",
        "        updatedAt = Instant.now();",
        "    }",
        "",
        "    public synchronized void attachLedgerEntries(List<LedgerEntry> entries) {",
        "        if (status != TransactionStatus.PENDING) {",
        "            throw new IllegalStateException(\"ledger can be attached only while pending\");",
        "        }",
        "        ledgerEntries.addAll(entries);",
        "        updatedAt = Instant.now();",
        "    }",
        "",
        "    public synchronized List<LedgerEntry> ledgerEntries() {",
        "        return Collections.unmodifiableList(new ArrayList<>(ledgerEntries));",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
        "",
        "enum TransactionType {",
        "    CREDIT, DEBIT, TRANSFER",
        "}",
        "",
        "enum TransactionStatus {",
        "    INITIATED {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == PENDING || next == FAILED;",
        "        }",
        "    },",
        "    PENDING {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == POSTED || next == FAILED;",
        "        }",
        "    },",
        "    POSTED {",
        "        boolean canMoveTo(TransactionStatus next) {",
        "            return next == REVERSED;",
        "        }",
        "    },",
        "    FAILED,",
        "    REVERSED;",
        "",
        "    boolean canMoveTo(TransactionStatus next) {",
        "        return false;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "LedgerEntry.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "",
        "public final class LedgerEntry {",
        "    private final String id;",
        "    private final String transactionId;",
        "    private final String accountId;",
        "    private final LedgerEntryType type;",
        "    private final long amountInCents;",
        "    private final String currency;",
        "    private final Instant createdAt;",
        "",
        "    private LedgerEntry(String transactionId, String accountId, LedgerEntryType type, long amountInCents, String currency) {",
        "        this.id = UUID.randomUUID().toString();",
        "        this.transactionId = requireText(transactionId, \"transactionId\");",
        "        this.accountId = requireText(accountId, \"accountId\");",
        "        this.type = Objects.requireNonNull(type, \"type\");",
        "        Account.requirePositive(amountInCents);",
        "        this.amountInCents = amountInCents;",
        "        this.currency = requireText(currency, \"currency\");",
        "        this.createdAt = Instant.now();",
        "    }",
        "",
        "    public static LedgerEntry debit(String transactionId, String accountId, long amountInCents, String currency) {",
        "        return new LedgerEntry(transactionId, accountId, LedgerEntryType.DEBIT, amountInCents, currency);",
        "    }",
        "",
        "    public static LedgerEntry credit(String transactionId, String accountId, long amountInCents, String currency) {",
        "        return new LedgerEntry(transactionId, accountId, LedgerEntryType.CREDIT, amountInCents, currency);",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String transactionId() {",
        "        return transactionId;",
        "    }",
        "",
        "    public String accountId() {",
        "        return accountId;",
        "    }",
        "",
        "    public LedgerEntryType type() {",
        "        return type;",
        "    }",
        "",
        "    public long amountInCents() {",
        "        return amountInCents;",
        "    }",
        "",
        "    public String currency() {",
        "        return currency;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
        "",
        "enum LedgerEntryType {",
        "    DEBIT, CREDIT",
        "}",
      ].join("\n"),
    },
    {
      filename: "TransactionCommand.java",
      language: "java",
      content: [
        "public interface TransactionCommand {",
        "    String idempotencyKey();",
        "",
        "    Transaction execute(WalletService service);",
        "}",
        "",
        "final class CreditCommand implements TransactionCommand {",
        "    private final String accountId;",
        "    private final long amountInCents;",
        "    private final String currency;",
        "    private final String idempotencyKey;",
        "",
        "    CreditCommand(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        this.accountId = accountId;",
        "        this.amountInCents = amountInCents;",
        "        this.currency = currency;",
        "        this.idempotencyKey = idempotencyKey;",
        "    }",
        "",
        "    public String idempotencyKey() {",
        "        return idempotencyKey;",
        "    }",
        "",
        "    public Transaction execute(WalletService service) {",
        "        return service.applyCredit(accountId, amountInCents, currency, idempotencyKey);",
        "    }",
        "}",
        "",
        "final class DebitCommand implements TransactionCommand {",
        "    private final String accountId;",
        "    private final long amountInCents;",
        "    private final String currency;",
        "    private final String idempotencyKey;",
        "",
        "    DebitCommand(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        this.accountId = accountId;",
        "        this.amountInCents = amountInCents;",
        "        this.currency = currency;",
        "        this.idempotencyKey = idempotencyKey;",
        "    }",
        "",
        "    public String idempotencyKey() {",
        "        return idempotencyKey;",
        "    }",
        "",
        "    public Transaction execute(WalletService service) {",
        "        return service.applyDebit(accountId, amountInCents, currency, idempotencyKey);",
        "    }",
        "}",
        "",
        "final class TransferCommand implements TransactionCommand {",
        "    private final String sourceAccountId;",
        "    private final String destinationAccountId;",
        "    private final long amountInCents;",
        "    private final String currency;",
        "    private final String idempotencyKey;",
        "",
        "    TransferCommand(String sourceAccountId, String destinationAccountId, long amountInCents, String currency, String idempotencyKey) {",
        "        this.sourceAccountId = sourceAccountId;",
        "        this.destinationAccountId = destinationAccountId;",
        "        this.amountInCents = amountInCents;",
        "        this.currency = currency;",
        "        this.idempotencyKey = idempotencyKey;",
        "    }",
        "",
        "    public String idempotencyKey() {",
        "        return idempotencyKey;",
        "    }",
        "",
        "    public Transaction execute(WalletService service) {",
        "        return service.applyTransfer(sourceAccountId, destinationAccountId, amountInCents, currency, idempotencyKey);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "WalletService.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Arrays;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "import java.util.concurrent.ConcurrentHashMap;",
        "import java.util.concurrent.CopyOnWriteArrayList;",
        "import java.util.function.Supplier;",
        "",
        "public final class WalletService {",
        "    private static final String EXTERNAL_ACCOUNT = \"EXTERNAL\";",
        "",
        "    private final Map<String, Wallet> wallets = new ConcurrentHashMap<>();",
        "    private final Map<String, Account> accounts = new ConcurrentHashMap<>();",
        "    private final Map<String, Transaction> transactionsByIdempotencyKey = new ConcurrentHashMap<>();",
        "    private final List<LedgerEntry> ledger = Collections.synchronizedList(new ArrayList<>());",
        "    private final List<TransactionObserver> observers = new CopyOnWriteArrayList<>();",
        "    private final CurrencyPolicy currencyPolicy;",
        "",
        "    public WalletService(CurrencyPolicy currencyPolicy) {",
        "        this.currencyPolicy = Objects.requireNonNull(currencyPolicy, \"currencyPolicy\");",
        "    }",
        "",
        "    public void addObserver(TransactionObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public Wallet createWallet(String walletId, String ownerId) {",
        "        Wallet wallet = new Wallet(walletId, ownerId);",
        "        Wallet existing = wallets.putIfAbsent(walletId, wallet);",
        "        if (existing != null) {",
        "            return existing;",
        "        }",
        "        return wallet;",
        "    }",
        "",
        "    public Account createAccount(String walletId, String accountId, String currency, long openingBalanceInCents) {",
        "        Wallet wallet = requireWallet(walletId);",
        "        Account account = new Account(accountId, walletId, currency, openingBalanceInCents);",
        "        Account existing = accounts.putIfAbsent(accountId, account);",
        "        if (existing != null) {",
        "            throw new IllegalArgumentException(\"duplicate account id\");",
        "        }",
        "        wallet.addAccount(account);",
        "        return account;",
        "    }",
        "",
        "    public Transaction credit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return new CreditCommand(accountId, amountInCents, currency, idempotencyKey).execute(this);",
        "    }",
        "",
        "    public Transaction debit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return new DebitCommand(accountId, amountInCents, currency, idempotencyKey).execute(this);",
        "    }",
        "",
        "    public Transaction transfer(String sourceAccountId, String destinationAccountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return new TransferCommand(sourceAccountId, destinationAccountId, amountInCents, currency, idempotencyKey).execute(this);",
        "    }",
        "",
        "    Transaction applyCredit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return executeIdempotently(idempotencyKey, () -> postCredit(accountId, amountInCents, currency, idempotencyKey));",
        "    }",
        "",
        "    Transaction applyDebit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return executeIdempotently(idempotencyKey, () -> postDebit(accountId, amountInCents, currency, idempotencyKey));",
        "    }",
        "",
        "    Transaction applyTransfer(String sourceAccountId, String destinationAccountId, long amountInCents, String currency, String idempotencyKey) {",
        "        return executeIdempotently(idempotencyKey, () -> postTransfer(sourceAccountId, destinationAccountId, amountInCents, currency, idempotencyKey));",
        "    }",
        "",
        "    public long balance(String accountId) {",
        "        return requireAccount(accountId).balanceInCents();",
        "    }",
        "",
        "    public List<LedgerEntry> ledgerEntries() {",
        "        synchronized (ledger) {",
        "            return Collections.unmodifiableList(new ArrayList<>(ledger));",
        "        }",
        "    }",
        "",
        "    private Transaction executeIdempotently(String idempotencyKey, Supplier<Transaction> action) {",
        "        requireText(idempotencyKey, \"idempotencyKey\");",
        "        synchronized (transactionsByIdempotencyKey) {",
        "            Transaction existing = transactionsByIdempotencyKey.get(idempotencyKey);",
        "            if (existing != null) {",
        "                return existing;",
        "            }",
        "            Transaction created = action.get();",
        "            transactionsByIdempotencyKey.put(idempotencyKey, created);",
        "            return created;",
        "        }",
        "    }",
        "",
        "    private Transaction postCredit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        Account account = requireAccount(accountId);",
        "        currencyPolicy.validateSingle(account, currency);",
        "        Transaction transaction = newTransaction(idempotencyKey, TransactionType.CREDIT, amountInCents, EXTERNAL_ACCOUNT, account.id());",
        "        transaction.transitionTo(TransactionStatus.PENDING);",
        "        account.lock();",
        "        try {",
        "            account.creditLocked(amountInCents);",
        "            List<LedgerEntry> entries = Arrays.asList(",
        "                LedgerEntry.debit(transaction.id(), EXTERNAL_ACCOUNT, amountInCents, currency),",
        "                LedgerEntry.credit(transaction.id(), account.id(), amountInCents, currency)",
        "            );",
        "            appendLedger(transaction, entries);",
        "            transaction.transitionTo(TransactionStatus.POSTED);",
        "        } catch (RuntimeException ex) {",
        "            transaction.transitionTo(TransactionStatus.FAILED);",
        "        } finally {",
        "            account.unlock();",
        "        }",
        "        notifyIfPosted(transaction);",
        "        return transaction;",
        "    }",
        "",
        "    private Transaction postDebit(String accountId, long amountInCents, String currency, String idempotencyKey) {",
        "        Account account = requireAccount(accountId);",
        "        currencyPolicy.validateSingle(account, currency);",
        "        Transaction transaction = newTransaction(idempotencyKey, TransactionType.DEBIT, amountInCents, account.id(), EXTERNAL_ACCOUNT);",
        "        transaction.transitionTo(TransactionStatus.PENDING);",
        "        account.lock();",
        "        try {",
        "            account.debitLocked(amountInCents);",
        "            List<LedgerEntry> entries = Arrays.asList(",
        "                LedgerEntry.debit(transaction.id(), account.id(), amountInCents, currency),",
        "                LedgerEntry.credit(transaction.id(), EXTERNAL_ACCOUNT, amountInCents, currency)",
        "            );",
        "            appendLedger(transaction, entries);",
        "            transaction.transitionTo(TransactionStatus.POSTED);",
        "        } catch (RuntimeException ex) {",
        "            transaction.transitionTo(TransactionStatus.FAILED);",
        "        } finally {",
        "            account.unlock();",
        "        }",
        "        notifyIfPosted(transaction);",
        "        return transaction;",
        "    }",
        "",
        "    private Transaction postTransfer(String sourceAccountId, String destinationAccountId, long amountInCents, String currency, String idempotencyKey) {",
        "        if (Objects.equals(sourceAccountId, destinationAccountId)) {",
        "            throw new IllegalArgumentException(\"source and destination must differ\");",
        "        }",
        "        Account source = requireAccount(sourceAccountId);",
        "        Account destination = requireAccount(destinationAccountId);",
        "        currencyPolicy.validateTransfer(source, destination, currency);",
        "        Transaction transaction = newTransaction(idempotencyKey, TransactionType.TRANSFER, amountInCents, source.id(), destination.id());",
        "        transaction.transitionTo(TransactionStatus.PENDING);",
        "",
        "        lockInIdOrder(source, destination);",
        "        try {",
        "            source.debitLocked(amountInCents);",
        "            destination.creditLocked(amountInCents);",
        "            List<LedgerEntry> entries = Arrays.asList(",
        "                LedgerEntry.debit(transaction.id(), source.id(), amountInCents, currency),",
        "                LedgerEntry.credit(transaction.id(), destination.id(), amountInCents, currency)",
        "            );",
        "            appendLedger(transaction, entries);",
        "            transaction.transitionTo(TransactionStatus.POSTED);",
        "        } catch (RuntimeException ex) {",
        "            transaction.transitionTo(TransactionStatus.FAILED);",
        "        } finally {",
        "            unlockInReverseIdOrder(source, destination);",
        "        }",
        "        notifyIfPosted(transaction);",
        "        return transaction;",
        "    }",
        "",
        "    private Transaction newTransaction(String idempotencyKey, TransactionType type, long amountInCents, String fromAccountId, String toAccountId) {",
        "        return Transaction.start(UUID.randomUUID().toString(), idempotencyKey, type, amountInCents, fromAccountId, toAccountId);",
        "    }",
        "",
        "    private void appendLedger(Transaction transaction, List<LedgerEntry> entries) {",
        "        transaction.attachLedgerEntries(entries);",
        "        synchronized (ledger) {",
        "            ledger.addAll(entries);",
        "        }",
        "    }",
        "",
        "    private void lockInIdOrder(Account first, Account second) {",
        "        if (first.id().compareTo(second.id()) <= 0) {",
        "            first.lock();",
        "            second.lock();",
        "        } else {",
        "            second.lock();",
        "            first.lock();",
        "        }",
        "    }",
        "",
        "    private void unlockInReverseIdOrder(Account first, Account second) {",
        "        if (first.id().compareTo(second.id()) <= 0) {",
        "            second.unlock();",
        "            first.unlock();",
        "        } else {",
        "            first.unlock();",
        "            second.unlock();",
        "        }",
        "    }",
        "",
        "    private void notifyIfPosted(Transaction transaction) {",
        "        if (transaction.status() != TransactionStatus.POSTED) {",
        "            return;",
        "        }",
        "        for (TransactionObserver observer : observers) {",
        "            observer.onTransactionPosted(transaction);",
        "        }",
        "    }",
        "",
        "    private Wallet requireWallet(String walletId) {",
        "        Wallet wallet = wallets.get(walletId);",
        "        if (wallet == null) {",
        "            throw new IllegalArgumentException(\"unknown wallet: \" + walletId);",
        "        }",
        "        return wallet;",
        "    }",
        "",
        "    private Account requireAccount(String accountId) {",
        "        Account account = accounts.get(accountId);",
        "        if (account == null) {",
        "            throw new IllegalArgumentException(\"unknown account: \" + accountId);",
        "        }",
        "        return account;",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
        "",
        "interface TransactionObserver {",
        "    void onTransactionPosted(Transaction transaction);",
        "}",
        "",
        "interface CurrencyPolicy {",
        "    void validateSingle(Account account, String currency);",
        "",
        "    void validateTransfer(Account source, Account destination, String currency);",
        "}",
        "",
        "final class SameCurrencyPolicy implements CurrencyPolicy {",
        "    public void validateSingle(Account account, String currency) {",
        "        if (!account.currency().equals(currency)) {",
        "            throw new IllegalArgumentException(\"currency mismatch\");",
        "        }",
        "    }",
        "",
        "    public void validateTransfer(Account source, Account destination, String currency) {",
        "        validateSingle(source, currency);",
        "        validateSingle(destination, currency);",
        "        if (!source.currency().equals(destination.currency())) {",
        "            throw new IllegalArgumentException(\"cross-currency transfer requires an FX policy\");",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        WalletService service = new WalletService(new SameCurrencyPolicy());",
        "        service.addObserver(transaction -> System.out.println(\"posted: \" + transaction.id()));",
        "",
        "        Wallet alice = service.createWallet(\"wallet-alice\", \"alice\");",
        "        Wallet bob = service.createWallet(\"wallet-bob\", \"bob\");",
        "",
        "        service.createAccount(alice.id(), \"acct-alice-inr\", \"INR\", 10000);",
        "        service.createAccount(bob.id(), \"acct-bob-inr\", \"INR\", 2500);",
        "",
        "        Transaction first = service.transfer(\"acct-alice-inr\", \"acct-bob-inr\", 1500, \"INR\", \"transfer-001\");",
        "        Transaction retry = service.transfer(\"acct-alice-inr\", \"acct-bob-inr\", 1500, \"INR\", \"transfer-001\");",
        "",
        "        System.out.println(first.id().equals(retry.id()));",
        "        System.out.println(service.balance(\"acct-alice-inr\"));",
        "        System.out.println(service.balance(\"acct-bob-inr\"));",
        "        System.out.println(service.ledgerEntries().size());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Wallet",
      detailMD:
        "Groups accounts for one owner. It is intentionally small: identity, owner id, synchronized account registration, and defensive account views.",
    },
    {
      className: "Account",
      detailMD:
        "Holds one currency balance and a **ReentrantLock**. Package-level **creditLocked** and **debitLocked** keep balance mutation available only to the service transaction boundary.",
    },
    {
      className: "Transaction",
      detailMD:
        "Stores request metadata, idempotency key, endpoints, timestamps, status, and attached ledger entries. **TransactionStatus** inside the same file enforces lifecycle transitions.",
    },
    {
      className: "LedgerEntry",
      detailMD:
        "Immutable debit/credit row tied to a transaction id. The service creates entries in pairs, giving every posted movement an audit-friendly double-entry record.",
    },
    {
      className: "TransactionCommand",
      detailMD:
        "Defines the command seam and concrete **CreditCommand**, **DebitCommand**, and **TransferCommand**. Each object captures parameters and delegates execution to the service.",
    },
    {
      className: "WalletService",
      detailMD:
        "The correctness boundary. It owns idempotency, deterministic locking, double-entry ledger append, status transitions, currency policy, and observer notifications.",
    },
    {
      className: "Main",
      detailMD:
        "Small demo that creates two wallets, transfers money once, retries with the same idempotency key, and prints unchanged balances plus a two-row ledger.",
    },
  ],

  dryRun: {
    inputMD:
      "Accounts: Alice INR balance **10000**, Bob INR balance **2500**. Action: transfer **1500 INR** from Alice to Bob using idempotency key **transfer-001**, then retry the same request.",
    columns: ["Step", "Action", "Transaction status", "Alice balance", "Bob balance", "Ledger"],
    rows: [
      ["1", "Receive transfer-001", "INITIATED", "10000", "2500", "no entries"],
      ["2", "Pass idempotency check and lock Alice then Bob", "PENDING", "10000", "2500", "no entries"],
      ["3", "Debit Alice and credit Bob", "PENDING", "8500", "4000", "not appended yet"],
      ["4", "Append double-entry rows", "POSTED", "8500", "4000", "DEBIT Alice 1500, CREDIT Bob 1500"],
      ["5", "Retry transfer-001", "POSTED", "8500", "4000", "same two entries returned"],
    ],
    narrativeMD:
      "The retry in step 5 proves idempotency: the service returns the first transaction and does not debit Alice again. At no point is there a posted transfer without both ledger rows.",
  },

  complexity: [
    {
      operation: "createWallet / createAccount",
      time: "O(1)",
      space: "O(1)",
      note: "Hash map insert plus a small wallet-account association.",
    },
    {
      operation: "credit / debit",
      time: "O(1)",
      space: "O(1)",
      note: "Idempotency lookup, one account lock, two ledger entries.",
    },
    {
      operation: "transfer",
      time: "O(1)",
      space: "O(1)",
      note: "Two account locks acquired in deterministic order and two ledger entries appended.",
    },
    {
      operation: "balance",
      time: "O(1)",
      space: "O(1)",
      note: "Reads the cached account balance under the account lock.",
    },
    {
      operation: "ledgerEntries",
      time: "O(N)",
      space: "O(N)",
      note: "Returns a defensive copy of N in-memory ledger rows.",
    },
  ],
  complexityNotesMD:
    "The in-memory design optimizes the interview hot path with O(1) maps and account locks. In production, the same boundaries map to database transactions, row locks, unique idempotency keys, and append-only ledger tables.",

  extensibility: [
    {
      label: "Foreign exchange transfers",
      detailMD:
        "Replace **SameCurrencyPolicy** with an FX-aware **CurrencyPolicy** that quotes rates and creates four ledger entries: source debit, source FX credit, destination FX debit, destination credit.",
    },
    {
      label: "New transaction type",
      detailMD:
        "Add a new **TransactionCommand** implementation such as RefundCommand or HoldCommand and route it through the same idempotency and state machine boundary.",
    },
    {
      label: "Receipts and notifications",
      detailMD:
        "Attach more **TransactionObserver** implementations for email, SMS, analytics, or fraud review without modifying balance mutation logic.",
    },
    {
      label: "Persistent repositories",
      detailMD:
        "Move maps and lists behind repositories with unique indexes on idempotency key and ledger entry id. The service remains the orchestration boundary.",
    },
    {
      label: "Account holds",
      detailMD:
        "Introduce an available balance separate from posted balance and a HOLD status before debit settlement. The same state pattern scales to this lifecycle.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Ledger-derived balances only",
      detailMD:
        "Remove cached balances and compute every balance by summing ledger entries for the account.",
      tradeoffsMD:
        "Very audit-friendly and hard to corrupt, but too slow for high-frequency balance reads unless backed by projections or materialized views.",
    },
    {
      name: "Single global wallet lock",
      detailMD:
        "Synchronize every credit, debit, and transfer on one service-wide monitor.",
      tradeoffsMD:
        "Simpler to reason about, but it serializes unrelated accounts and becomes a throughput bottleneck quickly.",
    },
    {
      name: "Database-first transaction boundary",
      detailMD:
        "Use SQL rows for accounts, ledger entries, and idempotency. A transfer becomes one database transaction with account rows locked by ordered id.",
      tradeoffsMD:
        "Closer to production and durable across processes, but heavier for an LLD whiteboard unless the interviewer asks for multi-instance behavior.",
    },
  ],

  commonMistakes: [
    "Updating source and destination balances in separate methods without one atomic transfer boundary.",
    "Storing only the latest balance and skipping ledger entries, which destroys auditability.",
    "Treating idempotency as a client concern instead of enforcing it server-side.",
    "Letting transaction status be any string, so impossible lifecycle transitions sneak in.",
    "Acquiring account locks in request order, which can deadlock when two users pay each other simultaneously.",
    "Running observers before the transaction is POSTED, causing side effects for failed or partial work.",
    "Creating one ledger row for a transfer instead of balanced debit and credit rows.",
  ],

  followUps: [
    {
      question: "How do you make this safe across multiple application instances?",
      answerMD:
        "Move accounts, idempotency records, transactions, and ledger entries to a database. Use a unique constraint on idempotency key and row-level locks on account rows in deterministic order.",
    },
    {
      question: "How would you support cross-currency transfer?",
      answerMD:
        "Make **CurrencyPolicy** quote FX and create balanced ledger entries in both currencies. Persist the rate used on the transaction for audit and dispute handling.",
    },
    {
      question: "What happens if a debit fails for insufficient funds?",
      answerMD:
        "The transaction moves from PENDING to FAILED, no ledger entries are attached, and the idempotency key maps to that failed transaction so a retry returns the same result.",
    },
    {
      question: "Why not notify users inside the account lock before releasing it?",
      answerMD:
        "Notifications are slow and unreliable side effects. The service posts money first, releases locks, then notifies observers so external failures do not hold critical locks.",
    },
    {
      question: "Where would fraud checks fit?",
      answerMD:
        "Synchronous allow/deny checks can run as a policy before PENDING. Asynchronous monitoring can be an observer after POSTED or a separate review workflow for holds.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durability and atomic commit",
      detailMD:
        "Use a database transaction to update account balances, insert ledger entries, insert/update transaction state, and reserve the idempotency key together.",
    },
    {
      label: "Numeric precision",
      detailMD:
        "Store integer minor units such as cents or paise. Avoid floating point for money and persist currency on every amount.",
    },
    {
      label: "Idempotency retention",
      detailMD:
        "Keep idempotency records long enough for client retry windows. Include request fingerprinting so the same key cannot be reused for different parameters.",
    },
    {
      label: "Reconciliation",
      detailMD:
        "Run periodic jobs that sum ledger entries and compare them to cached balances. Alert on any mismatch before users see inconsistent money.",
    },
    {
      label: "Observability and compliance",
      detailMD:
        "Emit metrics for failed debits, duplicate idempotency hits, transfer latency, and ledger imbalance. Keep immutable audit logs for regulatory review.",
    },
  ],

  interviewNotes: [
    "Does the candidate state the money invariants before naming classes?",
    "Is transfer atomic and deadlock-safe under concurrent requests?",
    "Are idempotency keys enforced inside the service boundary?",
    "Is the ledger double-entry and immutable rather than an afterthought?",
    "Does transaction status follow a lifecycle instead of ad hoc booleans?",
    "Are policies and observers separated from core balance mutation?",
  ],

  quiz: [
    {
      question: "Why does the transfer acquire account locks in deterministic id order?",
      options: [
        "To avoid deadlocks when opposite-direction transfers happen concurrently",
        "To make account ids easier to print",
        "To guarantee higher interest on older accounts",
        "To avoid needing idempotency keys",
      ],
      answerIndex: 0,
      explanationMD:
        "If every transfer locks the lower id first, two transfers cannot each hold one lock while waiting forever for the other.",
    },
    {
      question: "What does the idempotency key protect against?",
      options: [
        "Duplicate execution caused by client or network retries",
        "Cross-currency exchange rate movement",
        "A user creating multiple wallets",
        "Ledger entries having timestamps",
      ],
      answerIndex: 0,
      explanationMD:
        "A retry with the same key returns the first transaction result and does not apply the balance mutation again.",
    },
    {
      question: "Which pair of ledger entries represents a wallet-to-wallet transfer?",
      options: [
        "Credit source and credit destination",
        "Debit source and credit destination",
        "Debit destination and credit source",
        "One balance snapshot row only",
      ],
      answerIndex: 1,
      explanationMD:
        "The source account gives value, so it is debited. The destination receives value, so it is credited.",
    },
    {
      question: "Why is **TransactionStatus** better than a free-form status string?",
      options: [
        "It lets the state machine reject illegal lifecycle transitions",
        "It makes the ledger append faster",
        "It removes the need for account locks",
        "It automatically sends notifications",
      ],
      answerIndex: 0,
      explanationMD:
        "The enum can own legal transitions such as INITIATED to PENDING and PENDING to POSTED or FAILED.",
    },
    {
      question: "Why should observers run after POSTED instead of before balance mutation?",
      options: [
        "Because notification failures should not corrupt core money movement",
        "Because Java lambdas require POSTED status",
        "Because observers replace ledger entries",
        "Because idempotency works only with observers",
      ],
      answerIndex: 0,
      explanationMD:
        "Observers are side effects. The service should finish the atomic money mutation first and then notify listeners.",
    },
  ],

  practiceVariants: [
    {
      title: "Add pending holds",
      detailMD:
        "Support authorization holds where available balance decreases before posted balance. Add HELD and RELEASED states and verify idempotent capture.",
      difficulty: "Advanced",
    },
    {
      title: "Cross-currency transfer",
      detailMD:
        "Implement an FX **CurrencyPolicy** that stores the quote id and creates balanced ledger rows in both currencies.",
      difficulty: "Advanced",
    },
    {
      title: "Persistent wallet repositories",
      detailMD:
        "Replace in-memory maps with repository interfaces and describe the SQL constraints needed for idempotency and ledger immutability.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "What is the most important invariant in wallet transfer?",
      back: "No lost money: source debit, destination credit, ledger append, and POSTED status must succeed together or not post.",
    },
    {
      front: "Why use a double-entry ledger?",
      back: "Every posted movement has matching debit and credit rows, making the system auditable and reconcilable.",
    },
    {
      front: "What does idempotency key map to?",
      back: "The first **Transaction** created for that key, including its final status and ledger entries.",
    },
    {
      front: "Which pattern models transaction lifecycle?",
      back: "State, implemented by **TransactionStatus** with legal transitions.",
    },
    {
      front: "Which pattern wraps credit, debit, and transfer requests?",
      back: "Command, via **TransactionCommand** and concrete command classes.",
    },
    {
      front: "How is transfer made deadlock-safe?",
      back: "Lock both accounts in deterministic account id order and release in reverse order.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** WalletService, Wallet, Account, Transaction, TransactionStatus, LedgerEntry, TransactionCommand, CurrencyPolicy, TransactionObserver.",
    "",
    "**Patterns:** State for transaction lifecycle, Command for money operations, Observer for receipts/analytics, Strategy for currency rules.",
    "",
    "**Flows:** credit = EXTERNAL debit + account credit; debit = account debit + EXTERNAL credit; transfer = source debit + destination credit.",
    "",
    "**Invariants:** positive amount, same currency, idempotency key unique, two ledger rows per posted movement, transfer locks both accounts atomically.",
    "",
    "**Concurrency:** account-level locks in sorted id order prevent lost updates and deadlocks.",
    "",
    "**Production:** enforce idempotency with a unique key, persist ledger append-only, reconcile cached balances, store integer minor units.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications — Transactions and Consistency",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Patterns of Enterprise Application Architecture — Unit of Work",
      kind: "Book",
      author: "Martin Fowler",
    },
    {
      title: "Stripe API Docs — Idempotent Requests",
      kind: "Docs",
      url: "https://docs.stripe.com/api/idempotent_requests",
    },
  ],

  relatedProblems: [
    { slug: "banking-system", note: "Closest neighbor for accounts, balances, and ledger-backed transactions." },
    { slug: "payment-gateway", note: "Adds external payment rails and provider integrations around wallet money movement." },
    { slug: "splitwise", note: "Uses balances and settlements, but with group debts instead of stored wallet money." },
  ],
};
