import type { LLDProblemContent } from "../types";

export const dropbox: LLDProblemContent = {
  slug: "dropbox",

  statementMD: [
    "Design the low-level object model for **Dropbox-style file sync and storage**.",
    "The system should represent files and folders as a tree, split file contents into chunks, keep immutable file versions, synchronize local and remote copies, resolve conflicts, manage sharing permissions, and notify connected clients when something changes.",
    "",
    "Focus on the LLD view: domain classes, responsibilities, relationships, and extension seams. You are not designing global metadata sharding, object storage internals, or the public REST API.",
  ].join("\n"),

  businessContextMD: [
    "Dropbox is a strong expert-level LLD problem because it combines several interview themes in one domain: a **Composite** file tree, **Memento** snapshots for version history, **Observer** notifications for clients, and a **Strategy** seam for conflict resolution.",
    "",
    "Interviewers use this problem to test whether you can separate storage structure from sync policy. A good answer makes versioning the source of truth, then lets the sync engine compare local and remote histories and publish changes without hard-coding a single conflict rule.",
  ].join("\n"),

  functionalRequirements: [
    "Model folders containing files and other folders using a uniform file-system item abstraction.",
    "Split each file version into fixed-size chunks so storage and transfer can happen at chunk granularity.",
    "Keep immutable file versions and allow restoring an older version as a new current version.",
    "Detect local-only, remote-only, and concurrent local-plus-remote changes during sync.",
    "Resolve sync conflicts through a pluggable strategy such as keep latest, keep local, or keep remote.",
    "Notify observers such as desktop clients or mobile clients whenever files, folders, or synced copies change.",
    "Share files or folders with collaborators using read, write, and owner permissions.",
    "Expose a small demo flow that creates a tree, writes versions, shares a file, and runs a conflict-aware sync.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Correct version history",
      detailMD:
        "A version is immutable once created. Restoring an older version appends a new version instead of mutating history, preserving auditability.",
    },
    {
      label: "Extensibility of sync policy",
      detailMD:
        "Conflict resolution must be a strategy. The sync engine detects the situation; policy decides which side wins.",
    },
    {
      label: "Efficient transfer boundary",
      detailMD:
        "File content is represented by chunks so a production implementation can deduplicate, hash, and transfer only changed chunks.",
    },
    {
      label: "Client notification",
      detailMD:
        "Changes should flow through observers so UI clients, background daemons, and audit listeners subscribe without being embedded in domain logic.",
    },
    {
      label: "Permission safety",
      detailMD:
        "Sharing state is centralized in a service so callers consistently answer read/write questions before exposing content or allowing edits.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need to design the distributed storage backend?",
      answerMD:
        "No. Model the LLD classes a client or metadata service would use. Object storage, replication, and global sharding are HLD concerns.",
    },
    {
      question: "Should deletion, move, and rename be fully implemented?",
      answerMD:
        "Rename and folder add/remove are part of the model. Full tombstone-based deletion sync can be discussed as an extension.",
    },
    {
      question: "How should conflicting edits be handled?",
      answerMD:
        "The base design detects that both local and remote changed from the last synced checksum, then delegates the winner choice to a conflict strategy.",
    },
    {
      question: "Are permissions inherited from folders?",
      answerMD:
        "The base implementation stores direct grants per item. Production inheritance is an extension that walks ancestors or materializes effective ACLs.",
    },
    {
      question: "Do observers receive every low-level chunk event?",
      answerMD:
        "No. Observers receive domain-level events such as file updated, folder changed, and conflict resolved. Chunk internals remain encapsulated.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class FileSystemItem {",
    "        <<abstract>>",
    "        -String id",
    "        -String name",
    "        -Instant modifiedAt",
    "        -List~ChangeObserver~ observers",
    "        +size() long",
    "        +path() String",
    "        +addObserver(ChangeObserver) void",
    "    }",
    "    class File {",
    "        -List~FileVersion~ history",
    "        -int chunkSize",
    "        +write(String, String) FileVersion",
    "        +restoreVersion(int, String) FileVersion",
    "        +currentVersion() Optional~FileVersion~",
    "    }",
    "    class Folder {",
    "        -List~FileSystemItem~ children",
    "        +add(FileSystemItem) void",
    "        +remove(String) boolean",
    "        +children() List~FileSystemItem~",
    "    }",
    "    class FileVersion {",
    "        -int number",
    "        -List~FileChunk~ chunks",
    "        -String checksum",
    "        +content() String",
    "    }",
    "    class FileChunk {",
    "        -int index",
    "        -byte[] bytes",
    "        +from(byte[], int) List~FileChunk~",
    "    }",
    "    class SyncEngine {",
    "        -ConflictResolutionStrategy conflictResolutionStrategy",
    "        -Map lastSyncedChecksums",
    "        +syncFile(File, File) SyncResult",
    "    }",
    "    class ConflictResolutionStrategy {",
    "        <<interface>>",
    "        +chooseWinner(File, File) File",
    "    }",
    "    class KeepLatestStrategy",
    "    class ShareService {",
    "        -Map grants",
    "        +share(FileSystemItem, String, Permission) void",
    "        +canRead(FileSystemItem, String) boolean",
    "        +canWrite(FileSystemItem, String) boolean",
    "    }",
    "    class ChangeObserver {",
    "        <<interface>>",
    "        +onChange(ChangeEvent) void",
    "    }",
    "    class Permission {",
    "        <<enumeration>>",
    "        READ",
    "        WRITE",
    "        OWNER",
    "    }",
    "    FileSystemItem <|-- File",
    "    FileSystemItem <|-- Folder",
    "    Folder o-- FileSystemItem",
    "    File o-- FileVersion",
    "    FileVersion o-- FileChunk",
    "    FileSystemItem --> ChangeObserver",
    "    SyncEngine ..> ConflictResolutionStrategy",
    "    ConflictResolutionStrategy <|.. KeepLatestStrategy",
    "    ShareService ..> FileSystemItem",
    "    ShareService --> Permission",
  ].join("\n"),
  classDiagramCaptionMD:
    "The core structure is a Composite tree. Files own immutable version mementos, versions own chunks, the sync engine depends on a conflict strategy, and observers hang off file-system items to receive change events.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Client",
    "    participant Local as LocalFile",
    "    participant Engine as SyncEngine",
    "    participant Remote as RemoteFile",
    "    participant Strategy as ConflictStrategy",
    "    participant Observer as ChangeObserver",
    "    Client->>Local: write(author, content)",
    "    Local->>Local: chunk content and create FileVersion",
    "    Local-->>Observer: file updated",
    "    Client->>Engine: syncFile(local, remote)",
    "    Engine->>Engine: compare last synced checksums",
    "    Engine->>Remote: currentVersion()",
    "    Engine->>Strategy: chooseWinner(local, remote)",
    "    Strategy-->>Engine: winning file",
    "    Engine->>Remote: write(sync author, winning content)",
    "    Remote-->>Observer: remote updated",
    "    Engine-->>Client: SyncResult",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The important flow is version-first. A write creates chunks and a version, observers are notified, and sync later compares checksums before invoking conflict policy.",

  entities: [
    {
      name: "FileSystemItem",
      responsibilityMD:
        "Abstract base for both files and folders. Carries identity, name, parent link, modified time, path calculation, and observer registration.",
      attributes: ["id", "name", "parent", "modifiedAt", "observers"],
    },
    {
      name: "File",
      responsibilityMD:
        "Leaf node in the Composite. Accepts writes, turns content into chunks, appends immutable versions, exposes the current version, and restores old versions by appending a new snapshot.",
      attributes: ["history", "chunkSize"],
    },
    {
      name: "Folder",
      responsibilityMD:
        "Composite node that owns children and computes aggregate size by summing child sizes. Folder changes also emit observer notifications.",
      attributes: ["children"],
    },
    {
      name: "FileVersion",
      responsibilityMD:
        "Memento snapshot of one file state. Stores version number, author, creation time, chunks, checksum, and reconstructs readable content.",
      attributes: ["number", "author", "createdAt", "chunks", "checksum"],
    },
    {
      name: "FileChunk",
      responsibilityMD:
        "Immutable byte range of a file version. Provides chunk splitting and defensive copies so version state cannot be mutated by callers.",
      attributes: ["index", "bytes"],
    },
    {
      name: "SyncEngine",
      responsibilityMD:
        "Compares local and remote checksums against the last synced checksum, decides whether to upload, download, no-op, or resolve a conflict, and records the new synced state.",
      attributes: ["conflictResolutionStrategy", "lastSyncedChecksumByLocalId"],
    },
    {
      name: "ShareService",
      responsibilityMD:
        "Centralizes collaborator grants and answers permission checks for read and write access.",
      attributes: ["grants", "Permission"],
    },
    {
      name: "ChangeObserver",
      responsibilityMD:
        "Observer contract used by clients and listeners. It receives a change event whenever an item updates or a child change bubbles up the tree.",
      attributes: ["onChange(event)"],
    },
  ],

  patternsUsed: [
    {
      name: "Composite",
      whyMD:
        "**FileSystemItem** is the component, **File** is the leaf, and **Folder** is the composite. Callers can compute size, paths, and observer behavior uniformly across the tree.",
    },
    {
      name: "Memento",
      whyMD:
        "**FileVersion** is an immutable snapshot of file state. Restoring a version creates a new snapshot, so history remains auditable and undo does not mutate the past.",
    },
    {
      name: "Observer",
      whyMD:
        "**FileSystemItem** maintains observers and emits **ChangeEvent** objects when files or folders change. Clients react without being hard-wired into the domain objects.",
    },
    {
      name: "Strategy",
      whyMD:
        "**SyncEngine** detects sync states but delegates conflict choice to **ConflictResolutionStrategy**. Keep-latest, keep-local, and manual-merge policies become interchangeable classes.",
    },
  ],

  designSteps: [
    {
      title: "Start with a Composite file tree",
      detailMD:
        "Make **FileSystemItem** the common abstraction. **Folder** stores children and **File** stores versions, but both expose identity, path, size, and observer behavior.",
      code: [
        "public abstract class FileSystemItem {",
        "    public abstract long size();",
        "}",
        "",
        "public class Folder extends FileSystemItem {",
        "    private final List<FileSystemItem> children = new ArrayList<>();",
        "    public long size() {",
        "        return children.stream().mapToLong(FileSystemItem::size).sum();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent every write as a version memento",
      detailMD:
        "A file write chunks the new content and appends a **FileVersion**. The old versions stay immutable, so restore and audit are natural operations.",
      code: [
        "public FileVersion write(String author, String content) {",
        "    List<FileChunk> chunks = FileChunk.from(content.getBytes(StandardCharsets.UTF_8), chunkSize);",
        "    FileVersion version = FileVersion.create(history.size() + 1, author, chunks);",
        "    history.add(version);",
        "    markUpdated(\"file-updated:v\" + version.number());",
        "    return version;",
        "}",
      ].join("\n"),
    },
    {
      title: "Keep chunks immutable and independently hashable",
      detailMD:
        "The sample keeps one checksum per version, but chunk objects are already independent immutable byte ranges. A production version can add per-chunk hashes and deduplication without changing the file tree.",
    },
    {
      title: "Make sync detection separate from conflict policy",
      detailMD:
        "**SyncEngine** compares local, remote, and last synced checksums. If both changed and differ, it calls a **ConflictResolutionStrategy** instead of embedding a policy.",
      code: [
        "if (localChanged && remoteChanged) {",
        "    File winner = conflictResolutionStrategy.chooseWinner(local, remote);",
        "    File loser = winner == local ? remote : local;",
        "    copyContent(winner, loser, \"conflict-resolution\");",
        "    return new SyncResult(SyncAction.CONFLICT_RESOLVED, \"Conflict resolved.\");",
        "}",
      ].join("\n"),
    },
    {
      title: "Notify observers from the domain boundary",
      detailMD:
        "Writes, restores, folder adds, and folder removes call **markUpdated**. The event is sent to observers and bubbles to the parent folder so a root-level client can watch the whole tree.",
    },
    {
      title: "Keep sharing outside storage objects",
      detailMD:
        "**ShareService** owns grants by item id. That avoids polluting **File** and **Folder** with collaboration rules and gives one place to enforce read/write semantics.",
    },
  ],

  implementation: [
    {
      filename: "FileSystemItem.java",
      language: "java",
      content: [
        'import java.time.Instant;',
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.List;',
        'import java.util.Objects;',
        'import java.util.UUID;',
        '',
        'public abstract class FileSystemItem {',
        '    private final String id;',
        '    private String name;',
        '    private Folder parent;',
        '    private Instant modifiedAt;',
        '    private final List<ChangeObserver> observers = new ArrayList<>();',
        '',
        '    protected FileSystemItem(String name) {',
        '        this.id = UUID.randomUUID().toString();',
        '        this.name = requireName(name);',
        '        this.modifiedAt = Instant.now();',
        '    }',
        '',
        '    public String id() {',
        '        return id;',
        '    }',
        '',
        '    public String name() {',
        '        return name;',
        '    }',
        '',
        '    public Instant modifiedAt() {',
        '        return modifiedAt;',
        '    }',
        '',
        '    public String path() {',
        '        return parent == null ? "/" + name : parent.path() + "/" + name;',
        '    }',
        '',
        '    public void rename(String newName) {',
        '        this.name = requireName(newName);',
        '        markUpdated("renamed");',
        '    }',
        '',
        '    public void addObserver(ChangeObserver observer) {',
        '        observers.add(Objects.requireNonNull(observer));',
        '    }',
        '',
        '    public void removeObserver(ChangeObserver observer) {',
        '        observers.remove(observer);',
        '    }',
        '',
        '    public List<ChangeObserver> observers() {',
        '        return Collections.unmodifiableList(new ArrayList<>(observers));',
        '    }',
        '',
        '    protected void markUpdated(String reason) {',
        '        modifiedAt = Instant.now();',
        '        notifyObservers(new ChangeEvent(id, path(), reason, modifiedAt));',
        '    }',
        '',
        '    protected void notifyObservers(ChangeEvent event) {',
        '        for (ChangeObserver observer : new ArrayList<>(observers)) {',
        '            observer.onChange(event);',
        '        }',
        '        if (parent != null) {',
        '            parent.notifyObservers(event);',
        '        }',
        '    }',
        '',
        '    void setParent(Folder parent) {',
        '        this.parent = parent;',
        '    }',
        '',
        '    private String requireName(String candidate) {',
        '        if (candidate == null || candidate.trim().isEmpty()) {',
        '            throw new IllegalArgumentException("name is required");',
        '        }',
        '        return candidate;',
        '    }',
        '',
        '    public abstract long size();',
        '',
        '    public abstract FileSystemItem copyShallow();',
        '',
        '    public interface ChangeObserver {',
        '        void onChange(ChangeEvent event);',
        '    }',
        '',
        '    public static final class ChangeEvent {',
        '        private final String itemId;',
        '        private final String path;',
        '        private final String reason;',
        '        private final Instant occurredAt;',
        '',
        '        public ChangeEvent(String itemId, String path, String reason, Instant occurredAt) {',
        '            this.itemId = itemId;',
        '            this.path = path;',
        '            this.reason = reason;',
        '            this.occurredAt = occurredAt;',
        '        }',
        '',
        '        public String itemId() {',
        '            return itemId;',
        '        }',
        '',
        '        public String path() {',
        '            return path;',
        '        }',
        '',
        '        public String reason() {',
        '            return reason;',
        '        }',
        '',
        '        public Instant occurredAt() {',
        '            return occurredAt;',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "File.java",
      language: "java",
      content: [
        'import java.nio.charset.StandardCharsets;',
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.List;',
        'import java.util.Optional;',
        '',
        'public class File extends FileSystemItem {',
        '    private final List<FileVersion> history = new ArrayList<>();',
        '    private final int chunkSize;',
        '',
        '    public File(String name, int chunkSize) {',
        '        super(name);',
        '        if (chunkSize <= 0) {',
        '            throw new IllegalArgumentException("chunkSize must be positive");',
        '        }',
        '        this.chunkSize = chunkSize;',
        '    }',
        '',
        '    public FileVersion write(String author, String content) {',
        '        List<FileChunk> chunks = FileChunk.from(content.getBytes(StandardCharsets.UTF_8), chunkSize);',
        '        FileVersion version = FileVersion.create(history.size() + 1, author, chunks);',
        '        history.add(version);',
        '        markUpdated("file-updated:v" + version.number());',
        '        return version;',
        '    }',
        '',
        '    public FileVersion restoreVersion(int versionNumber, String author) {',
        '        FileVersion target = history.stream()',
        '            .filter(version -> version.number() == versionNumber)',
        '            .findFirst()',
        '            .orElseThrow(() -> new IllegalArgumentException("version does not exist"));',
        '        FileVersion restored = target.copyAs(history.size() + 1, author);',
        '        history.add(restored);',
        '        markUpdated("file-restored:v" + versionNumber);',
        '        return restored;',
        '    }',
        '',
        '    public Optional<FileVersion> currentVersion() {',
        '        if (history.isEmpty()) {',
        '            return Optional.empty();',
        '        }',
        '        return Optional.of(history.get(history.size() - 1));',
        '    }',
        '',
        '    public String read() {',
        '        return currentVersion().map(FileVersion::content).orElse("");',
        '    }',
        '',
        '    public List<FileVersion> history() {',
        '        return Collections.unmodifiableList(new ArrayList<>(history));',
        '    }',
        '',
        '    @Override',
        '    public long size() {',
        '        return currentVersion().map(FileVersion::size).orElse(0L);',
        '    }',
        '',
        '    @Override',
        '    public FileSystemItem copyShallow() {',
        '        File copy = new File(name(), chunkSize);',
        '        copy.history.addAll(history);',
        '        return copy;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Folder.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.Iterator;',
        'import java.util.List;',
        'import java.util.Optional;',
        '',
        'public class Folder extends FileSystemItem implements Iterable<FileSystemItem> {',
        '    private final List<FileSystemItem> children = new ArrayList<>();',
        '',
        '    public Folder(String name) {',
        '        super(name);',
        '    }',
        '',
        '    public void add(FileSystemItem child) {',
        '        child.setParent(this);',
        '        children.add(child);',
        '        markUpdated("child-added:" + child.name());',
        '    }',
        '',
        '    public boolean remove(String childName) {',
        '        Optional<FileSystemItem> child = children.stream()',
        '            .filter(item -> item.name().equals(childName))',
        '            .findFirst();',
        '        if (!child.isPresent()) {',
        '            return false;',
        '        }',
        '        children.remove(child.get());',
        '        child.get().setParent(null);',
        '        markUpdated("child-removed:" + childName);',
        '        return true;',
        '    }',
        '',
        '    public List<FileSystemItem> children() {',
        '        return Collections.unmodifiableList(new ArrayList<>(children));',
        '    }',
        '',
        '    @Override',
        '    public Iterator<FileSystemItem> iterator() {',
        '        return children().iterator();',
        '    }',
        '',
        '    @Override',
        '    public long size() {',
        '        return children.stream().mapToLong(FileSystemItem::size).sum();',
        '    }',
        '',
        '    @Override',
        '    public FileSystemItem copyShallow() {',
        '        Folder copy = new Folder(name());',
        '        for (FileSystemItem child : children) {',
        '            copy.add(child.copyShallow());',
        '        }',
        '        return copy;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "FileVersion.java",
      language: "java",
      content: [
        'import java.nio.charset.StandardCharsets;',
        'import java.security.MessageDigest;',
        'import java.security.NoSuchAlgorithmException;',
        'import java.time.Instant;',
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.List;',
        '',
        'public final class FileVersion {',
        '    private final int number;',
        '    private final String author;',
        '    private final Instant createdAt;',
        '    private final List<FileChunk> chunks;',
        '    private final String checksum;',
        '',
        '    private FileVersion(int number, String author, List<FileChunk> chunks, String checksum) {',
        '        this.number = number;',
        '        this.author = author;',
        '        this.createdAt = Instant.now();',
        '        this.chunks = Collections.unmodifiableList(new ArrayList<>(chunks));',
        '        this.checksum = checksum;',
        '    }',
        '',
        '    public static FileVersion create(int number, String author, List<FileChunk> chunks) {',
        '        List<FileChunk> safeChunks = new ArrayList<>(chunks);',
        '        return new FileVersion(number, author, safeChunks, checksum(safeChunks));',
        '    }',
        '',
        '    public FileVersion copyAs(int newNumber, String author) {',
        '        return new FileVersion(newNumber, author, chunks, checksum);',
        '    }',
        '',
        '    public int number() {',
        '        return number;',
        '    }',
        '',
        '    public String author() {',
        '        return author;',
        '    }',
        '',
        '    public Instant createdAt() {',
        '        return createdAt;',
        '    }',
        '',
        '    public String checksum() {',
        '        return checksum;',
        '    }',
        '',
        '    public long size() {',
        '        return chunks.stream().mapToLong(FileChunk::size).sum();',
        '    }',
        '',
        '    public List<FileChunk> chunks() {',
        '        return chunks;',
        '    }',
        '',
        '    public String content() {',
        '        byte[] bytes = new byte[(int) size()];',
        '        int offset = 0;',
        '        for (FileChunk chunk : chunks) {',
        '            byte[] chunkBytes = chunk.bytes();',
        '            System.arraycopy(chunkBytes, 0, bytes, offset, chunkBytes.length);',
        '            offset += chunkBytes.length;',
        '        }',
        '        return new String(bytes, StandardCharsets.UTF_8);',
        '    }',
        '',
        '    private static String checksum(List<FileChunk> chunks) {',
        '        try {',
        '            MessageDigest digest = MessageDigest.getInstance("SHA-256");',
        '            for (FileChunk chunk : chunks) {',
        '                digest.update(chunk.bytes());',
        '            }',
        '            StringBuilder builder = new StringBuilder();',
        '            for (byte value : digest.digest()) {',
        '                builder.append(String.format("%02x", value));',
        '            }',
        '            return builder.toString();',
        '        } catch (NoSuchAlgorithmException exception) {',
        '            throw new IllegalStateException(exception);',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "FileChunk.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.Arrays;',
        'import java.util.List;',
        '',
        'public final class FileChunk {',
        '    private final int index;',
        '    private final byte[] bytes;',
        '',
        '    private FileChunk(int index, byte[] bytes) {',
        '        this.index = index;',
        '        this.bytes = Arrays.copyOf(bytes, bytes.length);',
        '    }',
        '',
        '    public static List<FileChunk> from(byte[] data, int chunkSize) {',
        '        if (chunkSize <= 0) {',
        '            throw new IllegalArgumentException("chunkSize must be positive");',
        '        }',
        '        List<FileChunk> result = new ArrayList<>();',
        '        for (int offset = 0, index = 0; offset < data.length; offset += chunkSize, index++) {',
        '            int end = Math.min(data.length, offset + chunkSize);',
        '            result.add(new FileChunk(index, Arrays.copyOfRange(data, offset, end)));',
        '        }',
        '        if (result.isEmpty()) {',
        '            result.add(new FileChunk(0, new byte[0]));',
        '        }',
        '        return result;',
        '    }',
        '',
        '    public int index() {',
        '        return index;',
        '    }',
        '',
        '    public int size() {',
        '        return bytes.length;',
        '    }',
        '',
        '    public byte[] bytes() {',
        '        return Arrays.copyOf(bytes, bytes.length);',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "SyncEngine.java",
      language: "java",
      content: [
        'import java.util.HashMap;',
        'import java.util.Map;',
        'import java.util.Objects;',
        '',
        'public class SyncEngine {',
        '    private final ConflictResolutionStrategy conflictResolutionStrategy;',
        '    private final Map<String, String> lastSyncedChecksumByLocalId = new HashMap<>();',
        '',
        '    public SyncEngine(ConflictResolutionStrategy conflictResolutionStrategy) {',
        '        this.conflictResolutionStrategy = Objects.requireNonNull(conflictResolutionStrategy);',
        '    }',
        '',
        '    public SyncResult syncFile(File local, File remote) {',
        '        String key = local.id();',
        '        String localChecksum = checksumOf(local);',
        '        String remoteChecksum = checksumOf(remote);',
        '        String lastSynced = lastSyncedChecksumByLocalId.get(key);',
        '',
        '        if (Objects.equals(localChecksum, remoteChecksum)) {',
        '            remember(key, localChecksum);',
        '            return new SyncResult(SyncAction.NO_OP, "Local and remote are already aligned.");',
        '        }',
        '',
        '        boolean localChanged = lastSynced == null || !Objects.equals(lastSynced, localChecksum);',
        '        boolean remoteChanged = lastSynced == null || !Objects.equals(lastSynced, remoteChecksum);',
        '',
        '        if (localChanged && remoteChanged) {',
        '            File winner = conflictResolutionStrategy.chooseWinner(local, remote);',
        '            File loser = winner == local ? remote : local;',
        '            copyContent(winner, loser, "conflict-resolution");',
        '            remember(key, checksumOf(local));',
        '            return new SyncResult(SyncAction.CONFLICT_RESOLVED, "Conflict resolved using " + winner.path() + ".");',
        '        }',
        '',
        '        if (localChanged) {',
        '            copyContent(local, remote, "upload");',
        '            remember(key, checksumOf(local));',
        '            return new SyncResult(SyncAction.UPLOAD, "Uploaded local changes to remote.");',
        '        }',
        '',
        '        if (remoteChanged) {',
        '            copyContent(remote, local, "download");',
        '            remember(key, checksumOf(local));',
        '            return new SyncResult(SyncAction.DOWNLOAD, "Downloaded remote changes to local.");',
        '        }',
        '',
        '        remember(key, checksumOf(local));',
        '        return new SyncResult(SyncAction.NO_OP, "No meaningful change detected.");',
        '    }',
        '',
        '    private String checksumOf(File file) {',
        '        return file.currentVersion().map(FileVersion::checksum).orElse("");',
        '    }',
        '',
        '    private void copyContent(File source, File target, String author) {',
        '        source.currentVersion().ifPresent(version -> target.write(author, version.content()));',
        '    }',
        '',
        '    private void remember(String key, String checksum) {',
        '        lastSyncedChecksumByLocalId.put(key, checksum);',
        '    }',
        '',
        '    public interface ConflictResolutionStrategy {',
        '        File chooseWinner(File local, File remote);',
        '    }',
        '',
        '    public static class KeepLatestStrategy implements ConflictResolutionStrategy {',
        '        @Override',
        '        public File chooseWinner(File local, File remote) {',
        '            return local.modifiedAt().isAfter(remote.modifiedAt()) ? local : remote;',
        '        }',
        '    }',
        '',
        '    public enum SyncAction {',
        '        NO_OP, UPLOAD, DOWNLOAD, CONFLICT_RESOLVED',
        '    }',
        '',
        '    public static final class SyncResult {',
        '        private final SyncAction action;',
        '        private final String detail;',
        '',
        '        public SyncResult(SyncAction action, String detail) {',
        '            this.action = action;',
        '            this.detail = detail;',
        '        }',
        '',
        '        public SyncAction action() {',
        '            return action;',
        '        }',
        '',
        '        public String detail() {',
        '            return detail;',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "ShareService.java",
      language: "java",
      content: [
        'import java.util.Collections;',
        'import java.util.HashMap;',
        'import java.util.Map;',
        'import java.util.Objects;',
        '',
        'public class ShareService {',
        '    private final Map<String, Map<String, Permission>> grants = new HashMap<>();',
        '',
        '    public void share(FileSystemItem item, String accountId, Permission permission) {',
        '        Objects.requireNonNull(item);',
        '        Objects.requireNonNull(accountId);',
        '        Objects.requireNonNull(permission);',
        '        grants.computeIfAbsent(item.id(), ignored -> new HashMap<>()).put(accountId, permission);',
        '    }',
        '',
        '    public void revoke(FileSystemItem item, String accountId) {',
        '        Map<String, Permission> itemGrants = grants.get(item.id());',
        '        if (itemGrants != null) {',
        '            itemGrants.remove(accountId);',
        '        }',
        '    }',
        '',
        '    public boolean canRead(FileSystemItem item, String accountId) {',
        '        return hasAtLeast(item, accountId, Permission.READ);',
        '    }',
        '',
        '    public boolean canWrite(FileSystemItem item, String accountId) {',
        '        return hasAtLeast(item, accountId, Permission.WRITE);',
        '    }',
        '',
        '    public Map<String, Permission> collaborators(FileSystemItem item) {',
        '        Map<String, Permission> itemGrants = grants.getOrDefault(item.id(), Collections.emptyMap());',
        '        return Collections.unmodifiableMap(new HashMap<>(itemGrants));',
        '    }',
        '',
        '    private boolean hasAtLeast(FileSystemItem item, String accountId, Permission required) {',
        '        Permission granted = grants.getOrDefault(item.id(), Collections.emptyMap()).get(accountId);',
        '        return granted != null && granted.ordinal() >= required.ordinal();',
        '    }',
        '',
        '    public enum Permission {',
        '        READ, WRITE, OWNER',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        'public class Main {',
        '    public static void main(String[] args) {',
        '        Folder root = new Folder("root");',
        '        Folder projects = new Folder("projects");',
        '        File roadmap = new File("roadmap.txt", 8);',
        '',
        '        root.addObserver(event -> System.out.println("Client notified: " + event.reason() + " at " + event.path()));',
        '        root.add(projects);',
        '        projects.add(roadmap);',
        '',
        '        roadmap.write("alice", "draft roadmap for sync");',
        '        roadmap.write("alice", "draft roadmap for sync with chunks");',
        '        roadmap.restoreVersion(1, "alice");',
        '',
        '        ShareService shareService = new ShareService();',
        '        shareService.share(roadmap, "bob", ShareService.Permission.WRITE);',
        '',
        '        File remoteRoadmap = (File) roadmap.copyShallow();',
        '        SyncEngine syncEngine = new SyncEngine(new SyncEngine.KeepLatestStrategy());',
        '',
        '        roadmap.write("alice", "local edit");',
        '        remoteRoadmap.write("bob", "remote edit");',
        '',
        '        SyncEngine.SyncResult result = syncEngine.syncFile(roadmap, remoteRoadmap);',
        '        System.out.println(result.action() + " - " + result.detail());',
        '        System.out.println("Bob can write: " + shareService.canWrite(roadmap, "bob"));',
        '    }',
        '}',
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "FileSystemItem",
      detailMD:
        "The abstract Composite component. It stores common metadata, computes paths through the parent link, owns observer registration, emits **ChangeEvent**, and bubbles child changes to parent folders.",
    },
    {
      className: "File",
      detailMD:
        "The leaf node. **write** chunks content and appends a **FileVersion**; **restoreVersion** appends a copied memento so history stays immutable.",
    },
    {
      className: "Folder",
      detailMD:
        "The composite node. It owns child items, supports add/remove, implements iteration, and computes size by summing children.",
    },
    {
      className: "FileVersion",
      detailMD:
        "The Memento. It is immutable, captures author/time/chunks/checksum, reconstructs content, and exposes checksum for sync comparisons.",
    },
    {
      className: "FileChunk",
      detailMD:
        "Immutable chunk value object. It splits byte arrays into fixed-size chunks and returns defensive byte copies.",
    },
    {
      className: "SyncEngine",
      detailMD:
        "The synchronization coordinator. It compares local and remote checksums with the last synced checksum, then uploads, downloads, no-ops, or delegates conflict selection to **ConflictResolutionStrategy**.",
    },
    {
      className: "ShareService",
      detailMD:
        "Permission facade for collaboration. It stores item grants and answers **canRead**/**canWrite** based on read, write, and owner levels.",
    },
    {
      className: "Main",
      detailMD:
        "A runnable demo that builds a tree, registers an observer, writes and restores file versions, grants write access, and triggers a conflict-aware sync.",
    },
  ],

  dryRun: {
    inputMD:
      "Folder **/root/projects** contains **roadmap.txt** with chunk size 8. Alice writes v1 and v2, restores v1, shares write access with Bob, then Alice and Bob both edit before the next sync.",
    columns: ["Step", "Action", "Version state", "Sync state", "Observer or permission result"],
    rows: [
      ["1", "Alice writes v1", "roadmap v1 has chunked content", "last synced empty", "Root observer sees file-updated:v1"],
      ["2", "Alice writes v2", "roadmap v2 becomes current", "last synced empty", "Root observer sees file-updated:v2"],
      ["3", "Alice restores v1", "roadmap v3 copies v1 content", "last synced empty", "History still keeps v1 and v2"],
      ["4", "Share with Bob", "versions unchanged", "last synced empty", "Bob canWrite is true"],
      ["5", "Alice edits local and Bob edits remote", "local v4 and remote v4 diverge", "both differ from last synced", "SyncEngine calls KeepLatestStrategy"],
      ["6", "Conflict resolved", "loser receives winning content as a new version", "last synced checksum updated", "Observers receive sync write notification"],
    ],
    narrativeMD:
      "The dry run highlights the key interview point: versions are never mutated. Even restore and conflict resolution create new versions, and observers see each domain-level change.",
  },

  complexity: [
    {
      operation: "write file",
      time: "O(N)",
      space: "O(N)",
      note: "N is content size. The write splits bytes into chunks and stores an immutable version.",
    },
    {
      operation: "restore version",
      time: "O(V)",
      space: "O(1)",
      note: "V versions are scanned by number; chunks are shared because they are immutable.",
    },
    {
      operation: "folder size",
      time: "O(T)",
      space: "O(H)",
      note: "T items in the subtree, H recursion/iterator depth conceptually. The sample uses stream traversal over children.",
    },
    {
      operation: "sync file",
      time: "O(N)",
      space: "O(N)",
      note: "Checksum lookup is O(1), but copying winning content creates a new version from N bytes when upload/download/conflict occurs.",
    },
    {
      operation: "permission check",
      time: "O(1)",
      space: "O(1)",
      note: "Direct item grants are stored in hash maps.",
    },
  ],
  complexityNotesMD:
    "The reference implementation is intentionally readable. Production Dropbox would avoid copying whole content on sync by comparing chunk hashes and transferring only missing chunks.",

  extensibility: [
    {
      label: "New conflict policy",
      detailMD:
        "Implement **ConflictResolutionStrategy** for keep-local, keep-remote, keep-latest, manual merge, or create-conflicted-copy. **SyncEngine** does not change.",
    },
    {
      label: "Chunk deduplication",
      detailMD:
        "Add per-chunk hashes and a **ChunkStore** repository. **FileVersion** can store chunk ids instead of byte arrays while keeping the same Memento shape.",
    },
    {
      label: "Permission inheritance",
      detailMD:
        "Enhance **ShareService** to evaluate ancestor folders or cache effective ACLs. Files and folders still remain storage objects, not policy engines.",
    },
    {
      label: "Deletion sync",
      detailMD:
        "Introduce tombstone versions and deletion events. Sync can then compare create/update/delete histories instead of only content checksums.",
    },
    {
      label: "Multiple client observers",
      detailMD:
        "Observers can be UI refreshers, activity feeds, audit loggers, or websocket publishers. Domain events remain stable.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Repository-backed metadata model",
      detailMD:
        "Move file, folder, version, and share state behind repositories so the sync engine works against persistent metadata rows.",
      tradeoffsMD:
        "Closer to production and easier to scale across processes, but heavier for an LLD interview and less focused on object collaboration.",
    },
    {
      name: "Event-sourced version history",
      detailMD:
        "Store every write, restore, share, rename, and conflict as an append-only event stream, then rebuild current state from events.",
      tradeoffsMD:
        "Excellent auditability and replay, but much more complex than immutable **FileVersion** mementos for the base problem.",
    },
    {
      name: "Manual conflict branch",
      detailMD:
        "Instead of choosing a winner, create a second file such as **roadmap conflicted copy** and notify the user to merge.",
      tradeoffsMD:
        "Safer for user data, but sync no longer converges automatically and clients need extra UX for conflict files.",
    },
  ],

  commonMistakes: [
    "Storing versions as mutable references to the current file content, which makes restore and audit incorrect.",
    "Putting sync conflict policy directly inside **File** or **Folder** instead of keeping it in **SyncEngine** plus a strategy.",
    "Treating folders and files as unrelated classes, causing duplicated path, size, and observer logic instead of using Composite.",
    "Notifying clients from UI code only, so background sync and programmatic writes never publish events.",
    "Over-designing distributed storage before the file tree, versioning, and sync state are clear.",
    "Mixing sharing grants into file content classes, which makes storage and authorization hard to evolve independently.",
    "Resolving concurrent local and remote edits by blindly overwriting one side without detecting a conflict.",
  ],

  followUps: [
    {
      question: "How would you sync only changed chunks?",
      answerMD:
        "Give each **FileChunk** a content hash and store versions as ordered chunk ids. Sync compares chunk manifests and uploads only missing hashes.",
    },
    {
      question: "How would you support delete and undelete?",
      answerMD:
        "Represent deletion as a tombstone version or event. Undelete appends a new version that points back to the last live content snapshot.",
    },
    {
      question: "How do folder permissions inherit to files?",
      answerMD:
        "**ShareService** can walk parent folders to compute effective permission, or maintain a denormalized ACL cache updated on share changes.",
    },
    {
      question: "What happens if both sides edit offline?",
      answerMD:
        "The engine sees local and remote checksums both differ from the last synced checksum. That is a conflict, so it delegates to the configured strategy.",
    },
    {
      question: "Where would websocket or push notifications live?",
      answerMD:
        "As observers or observer adapters. They subscribe to domain events and publish externally without changing **File** or **Folder**.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable metadata",
      detailMD:
        "Persist item ids, parent ids, version manifests, checksums, and grants in a transactional store. In-memory objects become a domain layer over repositories.",
    },
    {
      label: "Chunk storage",
      detailMD:
        "Store chunks by hash in object storage with reference counts. This enables deduplication and avoids re-uploading common blocks.",
    },
    {
      label: "Conflict safety",
      detailMD:
        "Prefer user-safe policies such as conflicted copies for real products. Automatic keep-latest is simple but can surprise users.",
    },
    {
      label: "Observer delivery",
      detailMD:
        "Use durable queues for notifications so client updates are retried and ordered. The in-process observer is the LLD seam, not the distributed transport.",
    },
    {
      label: "Security and audit",
      detailMD:
        "Check permissions on every read/write/share call, audit grant changes, encrypt file chunks at rest, and never expose raw object-store keys to clients.",
    },
  ],

  interviewNotes: [
    "Did the candidate identify **Composite** as the clean way to model folders and files uniformly?",
    "Did they make version history immutable and use restore as a new version rather than mutation?",
    "Can they explain local-only, remote-only, same, and conflict sync states clearly?",
    "Is conflict handling a **Strategy** instead of a hard-coded branch that will grow over time?",
    "Do observers notify clients from domain changes without coupling the model to UI or networking?",
    "Are permissions centralized so sharing rules do not leak into every file operation?",
  ],

  quiz: [
    {
      question: "Why is **FileVersion** modeled as immutable?",
      options: [
        "So restore and audit can rely on old snapshots never changing",
        "So folders can contain more children",
        "Because Java lists require immutable elements",
        "To make observer registration faster",
      ],
      answerIndex: 0,
      explanationMD:
        "Versioning is the source of truth. If old snapshots mutate, restore, conflict comparison, and audit all become unreliable.",
    },
    {
      question: "Which pattern best describes **Folder** containing both files and folders through **FileSystemItem**?",
      options: ["Observer", "Composite", "Strategy", "Memento"],
      answerIndex: 1,
      explanationMD:
        "Composite lets callers treat leaves and containers uniformly while folders own child components.",
    },
    {
      question: "When should **SyncEngine** invoke **ConflictResolutionStrategy**?",
      options: [
        "Whenever local and remote checksums are equal",
        "Only when the user shares a folder",
        "When both local and remote changed from the last synced checksum and differ",
        "Before any file has a version",
      ],
      answerIndex: 2,
      explanationMD:
        "That condition means both sides made independent edits, so the engine should not choose a winner by accident.",
    },
    {
      question: "What does the Observer pattern buy in this design?",
      options: [
        "It compresses chunks",
        "It lets clients react to domain changes without being embedded in file classes",
        "It replaces permission checks",
        "It guarantees network delivery across data centers",
      ],
      answerIndex: 1,
      explanationMD:
        "Observers are local notification seams. Production delivery may use queues or websockets behind an observer adapter.",
    },
    {
      question: "Why keep **ShareService** separate from **File** and **Folder**?",
      options: [
        "Because files cannot reference users in Java",
        "To centralize authorization rules and keep storage objects focused on storage behavior",
        "To avoid needing file versions",
        "Because permissions are part of chunking",
      ],
      answerIndex: 1,
      explanationMD:
        "Sharing is a collaboration policy. Keeping it in one service prevents authorization logic from leaking throughout the tree.",
    },
  ],

  practiceVariants: [
    {
      title: "Add conflicted-copy resolution",
      detailMD:
        "Implement a strategy that keeps both edits by creating a new sibling file named as a conflicted copy, then notifies observers.",
      difficulty: "Advanced",
    },
    {
      title: "Add chunk hash deduplication",
      detailMD:
        "Extend **FileChunk** with SHA-256 hashes and introduce a chunk store that reuses identical chunks across versions and files.",
      difficulty: "Expert",
    },
    {
      title: "Add inherited folder permissions",
      detailMD:
        "Make **ShareService** compute effective permissions by walking parent folders and resolving direct grants versus inherited grants.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the Composite in Dropbox LLD?",
      back: "**FileSystemItem** is the component, **File** is the leaf, and **Folder** is the composite containing other items.",
    },
    {
      front: "What is the Memento?",
      back: "**FileVersion** captures immutable file content as chunks plus checksum, author, and timestamp.",
    },
    {
      front: "When is a sync conflict detected?",
      back: "When both local and remote checksums differ from the last synced checksum and differ from each other.",
    },
    {
      front: "Which pattern makes conflict policy swappable?",
      back: "Strategy through **ConflictResolutionStrategy** inside **SyncEngine**.",
    },
    {
      front: "Why do file changes notify observers?",
      back: "Desktop clients, mobile clients, audit logs, and push adapters can react without being embedded in domain objects.",
    },
    {
      front: "Where should sharing permissions live?",
      back: "In **ShareService**, keyed by item id and collaborator id, so storage classes stay focused.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** FileSystemItem, File, Folder, FileVersion, FileChunk, SyncEngine, ShareService.",
    "",
    "**Patterns:** Composite for the tree, Memento for file versions, Observer for client notifications, Strategy for conflict resolution.",
    "",
    "**Write flow:** client writes content → File chunks bytes → FileVersion snapshot appended → observers notified.",
    "",
    "**Sync flow:** compare local checksum, remote checksum, and last synced checksum → upload, download, no-op, or resolve conflict through strategy → write winning content as a new version.",
    "",
    "**Sharing:** ShareService stores direct grants and answers canRead/canWrite. Inheritance and ACL caching are extensions.",
    "",
    "**Invariants:** old versions are immutable; restore appends; chunks are defensively copied; conflicts are detected before overwrite; observers publish domain-level events.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, Vlissides",
    },
    {
      title: "Dropbox Tech Blog",
      kind: "Blog",
      url: "https://dropbox.tech/",
      author: "Dropbox Engineering",
    },
  ],

  relatedProblems: [
    { slug: "google-drive", note: "Similar storage and sharing model with stronger search and collaboration emphasis." },
    { slug: "file-system", note: "The base Composite tree that this design extends with sync, versioning, and permissions." },
    { slug: "google-docs", note: "Useful contrast for real-time collaboration and conflict handling at document level." },
  ],
};
