import type { LLDProblemContent } from "../types";

export const foodDelivery: LLDProblemContent = {
  slug: "food-delivery",

  statementMD: [
    "Design the object model for a **food delivery system** like Swiggy or Zomato.",
    "Customers browse restaurants, add available menu items to a cart, place an order,",
    "and then track the order as the restaurant accepts it, prepares it, hands it to",
    "a delivery partner, and the partner delivers it.",
    "",
    "The interview focus is the **order lifecycle and partner matching**. A strong",
    "solution should make state transitions explicit, keep assignment policy pluggable,",
    "calculate pricing in one place, and notify customers, restaurants, and partners",
    "whenever the order status changes.",
  ].join("\n"),

  businessContextMD: [
    "Food delivery is a high-frequency intermediate LLD problem because it combines",
    "marketplace modelling with a lifecycle that is easy to get wrong. Restaurants",
    "change menus, customers edit carts, partners move across the city, and the same",
    "order must not jump from **Placed** directly to **Delivered**.",
    "",
    "Interviewers use it to test whether you can separate domain state from service",
    "orchestration: **Order** owns valid transitions, **AssignmentStrategy** owns partner",
    "choice, **OrderService** coordinates the use case, and **OrderObserver** fans out",
    "status notifications without coupling the lifecycle to SMS, push, or email.",
  ].join("\n"),

  functionalRequirements: [
    "Register restaurants with a location, availability flag, and menu items.",
    "Allow customers to build a cart for exactly one restaurant at a time.",
    "Validate item availability and quantity before adding items to the cart.",
    "Place an order from a non-empty cart and compute subtotal, delivery fee, platform fee, tax, and total.",
    "Move the order through Placed -> Accepted -> Preparing -> OutForDelivery -> Delivered, with Cancelled as a terminal failure state.",
    "Let the restaurant accept an order and mark it as preparing before dispatch.",
    "Assign a delivery partner using a pluggable nearest or least-busy strategy.",
    "Notify customers, restaurants, and delivery partners whenever the order status changes.",
    "Reject invalid lifecycle transitions such as dispatch before preparation or delivery before dispatch.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Lifecycle correctness",
      detailMD:
        "The state machine must be the source of truth for valid transitions. Service methods should ask the order to transition rather than mutate a status enum directly.",
    },
    {
      label: "Low assignment latency",
      detailMD:
        "For an interview-scale in-memory design, scanning partners is acceptable. The strategy seam lets production replace it with a geospatial index later.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New pricing plans, partner assignment policies, notification channels, and cancellation rules should be additive classes with minimal changes to the core flow.",
    },
    {
      label: "Auditability",
      detailMD:
        "Every order should keep a status timeline so support teams can explain when the restaurant accepted, when dispatch happened, and why a cancellation was allowed.",
    },
    {
      label: "Consistency under concurrency",
      detailMD:
        "Order transition and partner assignment should be performed atomically per order so two dispatch attempts do not assign two partners.",
    },
  ],

  requirementClarification: [
    {
      question: "Can a cart contain items from multiple restaurants?",
      answerMD:
        "No for the base design. One cart maps to one restaurant, which keeps pricing, preparation, and partner pickup simple. Multi-restaurant checkout is an extension.",
    },
    {
      question: "Who can cancel an order and until when?",
      answerMD:
        "Assume cancellation is allowed before delivery and becomes a terminal **Cancelled** state. Real systems can add policy checks based on payment, preparation stage, or partner arrival.",
    },
    {
      question: "Do we model payments and refunds?",
      answerMD:
        "Only pricing is in scope. Payment authorization, refunds, coupon validation, and wallet balances are boundary integrations that can be added around **OrderService**.",
    },
    {
      question: "How exact should location matching be?",
      answerMD:
        "Use a simple distance function in the LLD. The important design point is that nearest and least-busy are interchangeable **AssignmentStrategy** implementations.",
    },
    {
      question: "Should notifications be synchronous?",
      answerMD:
        "In the interview implementation observers run synchronously to show the pattern. In production they would usually publish events to a queue for retry and fanout.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Restaurant {",
    "        -String id",
    "        -String name",
    "        -Location location",
    "        -Map~String,MenuItem~ menuById",
    "        -boolean acceptingOrders",
    "        +addMenuItem(MenuItem) void",
    "        +menuItem(String) MenuItem",
    "        +isAcceptingOrders() boolean",
    "    }",
    "    class MenuItem {",
    "        -String id",
    "        -String name",
    "        -long pricePaise",
    "        -boolean available",
    "        +isAvailable() boolean",
    "        +setAvailable(boolean) void",
    "    }",
    "    class Cart {",
    "        -String customerId",
    "        -Restaurant restaurant",
    "        -Map~String,Line~ lines",
    "        +addItem(String, int) void",
    "        +subtotalPaise() long",
    "        +lines() List~Line~",
    "    }",
    "    class Order {",
    "        -String id",
    "        -OrderStatus status",
    "        -PricingQuote quote",
    "        -DeliveryPartner partner",
    "        +accept() void",
    "        +markPreparing() void",
    "        +markOutForDelivery() void",
    "        +markDelivered() void",
    "        +cancel() void",
    "    }",
    "    class OrderStatus {",
    "        <<enumeration>>",
    "        PLACED",
    "        ACCEPTED",
    "        PREPARING",
    "        OUT_FOR_DELIVERY",
    "        DELIVERED",
    "        CANCELLED",
    "    }",
    "    class OrderState {",
    "        <<interface>>",
    "        +status() OrderStatus",
    "        +accept(Order) void",
    "        +startPreparing(Order) void",
    "        +dispatch(Order) void",
    "        +deliver(Order) void",
    "        +cancel(Order) void",
    "    }",
    "    class DeliveryPartner {",
    "        -String id",
    "        -Location currentLocation",
    "        -Set~String~ activeOrderIds",
    "        +isAvailable() boolean",
    "        +assignOrder(String) void",
    "        +distanceTo(Location) double",
    "    }",
    "    class AssignmentStrategy {",
    "        <<interface>>",
    "        +assign(Order, List~DeliveryPartner~) DeliveryPartner",
    "    }",
    "    class NearestPartnerStrategy",
    "    class LeastBusyPartnerStrategy",
    "    class OrderService {",
    "        -Map~String,Restaurant~ restaurants",
    "        -Map~String,Order~ orders",
    "        -List~DeliveryPartner~ partners",
    "        -List~OrderObserver~ observers",
    "        -AssignmentStrategy assignmentStrategy",
    "        -OrderFactory orderFactory",
    "        +placeOrder(Cart) Order",
    "        +dispatchOrder(String) void",
    "    }",
    "    class OrderObserver {",
    "        <<interface>>",
    "        +onOrderUpdated(Order, String) void",
    "    }",
    "    class PricingStrategy {",
    "        <<interface>>",
    "        +price(Cart) PricingQuote",
    "    }",
    "    class OrderFactory {",
    "        <<abstract>>",
    "        +create(Cart) Order",
    "        #newOrder(Cart, PricingQuote) Order",
    "    }",
    "    Restaurant o-- MenuItem",
    "    Cart --> Restaurant",
    "    Cart o-- MenuItem",
    "    Order --> Restaurant",
    "    Order --> DeliveryPartner",
    "    Order --> OrderStatus",
    "    Order --> OrderState",
    "    OrderService o-- Order",
    "    OrderService o-- DeliveryPartner",
    "    OrderService ..> AssignmentStrategy",
    "    OrderService ..> OrderFactory",
    "    OrderService o-- OrderObserver",
    "    OrderFactory ..> PricingStrategy",
    "    AssignmentStrategy <|.. NearestPartnerStrategy",
    "    AssignmentStrategy <|.. LeastBusyPartnerStrategy",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service coordinates the use case, but the volatile decisions are behind seams: order status is a State machine, partner matching is a Strategy, pricing feeds the Factory Method, and notifications are Observers.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Customer",
    "    participant Service as OrderService",
    "    participant Factory as OrderFactory",
    "    participant OrderObj as Order",
    "    participant Strategy as AssignmentStrategy",
    "    participant Partner as DeliveryPartner",
    "    participant Observer as OrderObserver",
    "    Customer->>Service: placeOrder(cart)",
    "    Service->>Factory: create(cart)",
    "    Factory-->>Service: Order in PLACED",
    "    Service->>Observer: onOrderUpdated(PLACED)",
    "    Customer->>Service: acceptOrder(orderId)",
    "    Service->>OrderObj: accept()",
    "    Service->>Observer: onOrderUpdated(ACCEPTED)",
    "    Customer->>Service: startPreparing(orderId)",
    "    Service->>OrderObj: markPreparing()",
    "    Service->>Strategy: assign(order, partners)",
    "    Strategy-->>Service: best partner",
    "    Service->>OrderObj: markOutForDelivery()",
    "    Service->>Partner: assignOrder(orderId)",
    "    Service->>Observer: onOrderUpdated(OUT_FOR_DELIVERY)",
    "    Partner->>Service: deliverOrder(orderId)",
    "    Service->>OrderObj: markDelivered()",
    "    Service->>Observer: onOrderUpdated(DELIVERED)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The lifecycle is visible as a sequence of state transitions. Partner assignment happens only after preparation and before the out-for-delivery notification.",

  entities: [
    {
      name: "Restaurant",
      responsibilityMD:
        "Owns restaurant identity, location, menu, and whether the kitchen is currently accepting orders.",
      attributes: ["id", "name", "location", "menuById", "acceptingOrders"],
    },
    {
      name: "MenuItem",
      responsibilityMD:
        "Represents one sellable item with price and availability. The cart reads it, but availability remains controlled by the restaurant menu.",
      attributes: ["id", "name", "pricePaise", "available"],
    },
    {
      name: "Cart",
      responsibilityMD:
        "Temporary customer basket for one restaurant. It validates quantity and item availability, and exposes an immutable snapshot for order creation.",
      attributes: ["customerId", "restaurant", "lines"],
    },
    {
      name: "Order",
      responsibilityMD:
        "Aggregate root for the order lifecycle. It owns items, pricing quote, partner, status timeline, and all valid transitions.",
      attributes: ["id", "customerId", "restaurant", "items", "quote", "state", "timeline"],
    },
    {
      name: "DeliveryPartner",
      responsibilityMD:
        "Courier domain object with location, online status, capacity, and active order count used by assignment strategies.",
      attributes: ["id", "name", "currentLocation", "online", "activeOrderIds"],
    },
    {
      name: "AssignmentStrategy",
      responsibilityMD:
        "Policy interface for partner matching. Nearest and least-busy are alternative implementations with the same service contract.",
      attributes: ["assign(order, partners)"],
    },
    {
      name: "OrderService",
      responsibilityMD:
        "Application facade. Registers restaurants and partners, places orders through the factory, invokes transitions, assigns partners, and notifies observers.",
      attributes: ["restaurants", "orders", "partners", "observers", "assignmentStrategy", "orderFactory"],
    },
    {
      name: "OrderObserver",
      responsibilityMD:
        "Notification seam. Customer, restaurant, and partner channels react to order updates without being embedded inside the state machine.",
      attributes: ["onOrderUpdated(order, event)"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**Order** delegates transition behavior to status-specific state objects. Invalid jumps such as Placed to OutForDelivery fail at the domain boundary instead of relying on scattered conditionals.",
    },
    {
      name: "Strategy",
      whyMD:
        "**AssignmentStrategy** lets the service choose nearest or least-busy partner matching at runtime. The same pattern also keeps pricing rules behind **PricingStrategy**.",
    },
    {
      name: "Observer",
      whyMD:
        "**OrderObserver** decouples lifecycle changes from notification delivery. Adding WhatsApp, push, email, or restaurant dashboard alerts does not change **Order**.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**OrderFactory** defines the order creation skeleton and delegates the actual object construction to **newOrder**, so premium, scheduled, or group-order factories can vary creation without changing **OrderService**.",
    },
  ],

  designSteps: [
    {
      title: "Start with the core marketplace nouns",
      detailMD:
        "Keep the base model small: **Restaurant** owns a menu and location, **MenuItem** owns price and availability, and **Cart** is tied to one restaurant so pickup and billing stay coherent.",
      code: [
        "public final class Cart {",
        "    private final Restaurant restaurant;",
        "    private final Map<String, Line> lines = new LinkedHashMap<>();",
        "    public void addItem(String itemId, int quantity) {",
        "        MenuItem item = restaurant.menuItem(itemId);",
        "        if (!item.isAvailable()) throw new IllegalStateException();",
        "        lines.put(itemId, new Line(item, quantity));",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Make order status a real state machine",
      detailMD:
        "**Order** should expose intent methods such as **accept**, **markPreparing**, and **markDelivered**. Each method delegates to the current state so invalid transitions are impossible to ignore.",
      code: [
        "public synchronized void markOutForDelivery() {",
        "    state.dispatch(this);",
        "}",
        "",
        "private static final class PreparingState extends BaseState {",
        "    public OrderStatus status() { return OrderStatus.PREPARING; }",
        "    public void dispatch(Order order) { order.transitionTo(new OutForDeliveryState()); }",
        "}",
      ].join("\n"),
    },
    {
      title: "Snapshot price at order creation",
      detailMD:
        "The order should carry a **PricingQuote** computed from the cart. Later menu price changes should not rewrite what the customer agreed to pay.",
    },
    {
      title: "Hide partner matching behind a strategy",
      detailMD:
        "The service should not know whether matching means closest by location, least busy, highest rating, or partner preference. It asks **AssignmentStrategy** for one available partner.",
      code: [
        "public interface AssignmentStrategy {",
        "    DeliveryPartner assign(Order order, List<DeliveryPartner> partners);",
        "}",
      ].join("\n"),
    },
    {
      title: "Notify through observers, not conditionals",
      detailMD:
        "After each successful transition, **OrderService** emits an update to registered observers. Channels can be added or removed without touching lifecycle code.",
    },
    {
      title: "Keep the service as orchestration only",
      detailMD:
        "**OrderService** validates registered restaurants, invokes the factory, calls transition methods, asks the assignment strategy, and notifies observers. It should not contain status-specific branching.",
    },
  ],

  implementation: [
    {
      filename: "MenuItem.java",
      language: "java",
      content: [
        'import java.util.Objects;',
        '',
        'public final class MenuItem {',
        '    private final String id;',
        '    private final String name;',
        '    private final long pricePaise;',
        '    private boolean available;',
        '',
        '    public MenuItem(String id, String name, long pricePaise) {',
        '        if (pricePaise < 0) {',
        '            throw new IllegalArgumentException("price must be non-negative");',
        '        }',
        '        this.id = Objects.requireNonNull(id, "id");',
        '        this.name = Objects.requireNonNull(name, "name");',
        '        this.pricePaise = pricePaise;',
        '        this.available = true;',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getName() {',
        '        return name;',
        '    }',
        '',
        '    public long getPricePaise() {',
        '        return pricePaise;',
        '    }',
        '',
        '    public synchronized boolean isAvailable() {',
        '        return available;',
        '    }',
        '',
        '    public synchronized void setAvailable(boolean available) {',
        '        this.available = available;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Restaurant.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.LinkedHashMap;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        '',
        'public final class Restaurant {',
        '    private final String id;',
        '    private final String name;',
        '    private final Location location;',
        '    private final Map<String, MenuItem> menuById = new LinkedHashMap<>();',
        '    private boolean acceptingOrders = true;',
        '',
        '    public Restaurant(String id, String name, Location location) {',
        '        this.id = Objects.requireNonNull(id, "id");',
        '        this.name = Objects.requireNonNull(name, "name");',
        '        this.location = Objects.requireNonNull(location, "location");',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getName() {',
        '        return name;',
        '    }',
        '',
        '    public Location getLocation() {',
        '        return location;',
        '    }',
        '',
        '    public synchronized void addMenuItem(MenuItem item) {',
        '        menuById.put(item.getId(), Objects.requireNonNull(item, "item"));',
        '    }',
        '',
        '    public synchronized MenuItem menuItem(String itemId) {',
        '        MenuItem item = menuById.get(itemId);',
        '        if (item == null) {',
        '            throw new IllegalArgumentException("Unknown menu item " + itemId);',
        '        }',
        '        return item;',
        '    }',
        '',
        '    public synchronized List<MenuItem> menu() {',
        '        return Collections.unmodifiableList(new ArrayList<>(menuById.values()));',
        '    }',
        '',
        '    public synchronized boolean isAcceptingOrders() {',
        '        return acceptingOrders;',
        '    }',
        '',
        '    public synchronized void setAcceptingOrders(boolean acceptingOrders) {',
        '        this.acceptingOrders = acceptingOrders;',
        '    }',
        '',
        '    public static final class Location {',
        '        private final double latitude;',
        '        private final double longitude;',
        '',
        '        public Location(double latitude, double longitude) {',
        '            this.latitude = latitude;',
        '            this.longitude = longitude;',
        '        }',
        '',
        '        public double distanceTo(Location other) {',
        '            double dx = latitude - other.latitude;',
        '            double dy = longitude - other.longitude;',
        '            return Math.sqrt(dx * dx + dy * dy);',
        '        }',
        '',
        '        @Override',
        '        public String toString() {',
        '            return String.format("%.4f,%.4f", latitude, longitude);',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Cart.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.LinkedHashMap;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        '',
        'public final class Cart {',
        '    private final String customerId;',
        '    private final Restaurant restaurant;',
        '    private final Map<String, Line> lines = new LinkedHashMap<>();',
        '',
        '    public Cart(String customerId, Restaurant restaurant) {',
        '        this.customerId = Objects.requireNonNull(customerId, "customerId");',
        '        this.restaurant = Objects.requireNonNull(restaurant, "restaurant");',
        '    }',
        '',
        '    public String getCustomerId() {',
        '        return customerId;',
        '    }',
        '',
        '    public Restaurant getRestaurant() {',
        '        return restaurant;',
        '    }',
        '',
        '    public synchronized void addItem(String itemId, int quantity) {',
        '        if (quantity <= 0) {',
        '            throw new IllegalArgumentException("quantity must be positive");',
        '        }',
        '        MenuItem item = restaurant.menuItem(itemId);',
        '        if (!item.isAvailable()) {',
        '            throw new IllegalStateException(item.getName() + " is unavailable");',
        '        }',
        '        Line existing = lines.get(itemId);',
        '        if (existing == null) {',
        '            lines.put(itemId, new Line(item, quantity));',
        '        } else {',
        '            existing.increase(quantity);',
        '        }',
        '    }',
        '',
        '    public synchronized boolean isEmpty() {',
        '        return lines.isEmpty();',
        '    }',
        '',
        '    public synchronized long subtotalPaise() {',
        '        long subtotal = 0;',
        '        for (Line line : lines.values()) {',
        '            subtotal += line.lineTotalPaise();',
        '        }',
        '        return subtotal;',
        '    }',
        '',
        '    public synchronized List<Line> lines() {',
        '        List<Line> snapshot = new ArrayList<>();',
        '        for (Line line : lines.values()) {',
        '            snapshot.add(line.copy());',
        '        }',
        '        return Collections.unmodifiableList(snapshot);',
        '    }',
        '',
        '    public static final class Line {',
        '        private final MenuItem item;',
        '        private int quantity;',
        '',
        '        private Line(MenuItem item, int quantity) {',
        '            this.item = Objects.requireNonNull(item, "item");',
        '            this.quantity = quantity;',
        '        }',
        '',
        '        public MenuItem getItem() {',
        '            return item;',
        '        }',
        '',
        '        public int getQuantity() {',
        '            return quantity;',
        '        }',
        '',
        '        public long lineTotalPaise() {',
        '            return item.getPricePaise() * quantity;',
        '        }',
        '',
        '        private void increase(int delta) {',
        '            quantity += delta;',
        '        }',
        '',
        '        private Line copy() {',
        '            return new Line(item, quantity);',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Order.java",
      language: "java",
      content: [
        'import java.time.Instant;',
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.List;',
        'import java.util.Objects;',
        '',
        'public final class Order {',
        '    private final String id;',
        '    private final String customerId;',
        '    private final Restaurant restaurant;',
        '    private final List<Cart.Line> items;',
        '    private final OrderService.PricingQuote quote;',
        '    private final List<String> timeline = new ArrayList<>();',
        '    private OrderState state;',
        '    private DeliveryPartner partner;',
        '',
        '    public Order(String id, String customerId, Restaurant restaurant, List<Cart.Line> items, OrderService.PricingQuote quote) {',
        '        this.id = Objects.requireNonNull(id, "id");',
        '        this.customerId = Objects.requireNonNull(customerId, "customerId");',
        '        this.restaurant = Objects.requireNonNull(restaurant, "restaurant");',
        '        this.items = Collections.unmodifiableList(new ArrayList<>(Objects.requireNonNull(items, "items")));',
        '        this.quote = Objects.requireNonNull(quote, "quote");',
        '        this.state = new PlacedState();',
        '        recordState();',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getCustomerId() {',
        '        return customerId;',
        '    }',
        '',
        '    public Restaurant getRestaurant() {',
        '        return restaurant;',
        '    }',
        '',
        '    public List<Cart.Line> getItems() {',
        '        return items;',
        '    }',
        '',
        '    public OrderService.PricingQuote getQuote() {',
        '        return quote;',
        '    }',
        '',
        '    public synchronized OrderStatus getStatus() {',
        '        return state.status();',
        '    }',
        '',
        '    public synchronized DeliveryPartner getPartner() {',
        '        return partner;',
        '    }',
        '',
        '    public synchronized List<String> timeline() {',
        '        return Collections.unmodifiableList(new ArrayList<>(timeline));',
        '    }',
        '',
        '    public synchronized void accept() {',
        '        state.accept(this);',
        '    }',
        '',
        '    public synchronized void markPreparing() {',
        '        state.startPreparing(this);',
        '    }',
        '',
        '    public synchronized void markOutForDelivery() {',
        '        state.dispatch(this);',
        '    }',
        '',
        '    public synchronized void markDelivered() {',
        '        state.deliver(this);',
        '    }',
        '',
        '    public synchronized void cancel() {',
        '        state.cancel(this);',
        '    }',
        '',
        '    public synchronized void assignPartner(DeliveryPartner partner) {',
        '        if (getStatus() != OrderStatus.OUT_FOR_DELIVERY) {',
        '            throw new IllegalStateException("Partner can be assigned only after dispatch");',
        '        }',
        '        if (this.partner != null) {',
        '            throw new IllegalStateException("Order already has a partner");',
        '        }',
        '        this.partner = Objects.requireNonNull(partner, "partner");',
        '        this.partner.assignOrder(id);',
        '    }',
        '',
        '    private void transitionTo(OrderState next) {',
        '        this.state = next;',
        '        recordState();',
        '    }',
        '',
        '    private void cancelNow() {',
        '        transitionTo(new CancelledState());',
        '        releasePartnerIfPresent();',
        '    }',
        '',
        '    private void completeDelivery() {',
        '        transitionTo(new DeliveredState());',
        '        releasePartnerIfPresent();',
        '    }',
        '',
        '    private void releasePartnerIfPresent() {',
        '        if (partner != null) {',
        '            partner.completeOrder(id);',
        '        }',
        '    }',
        '',
        '    private void recordState() {',
        '        timeline.add(Instant.now() + " " + state.status());',
        '    }',
        '',
        '    public enum OrderStatus {',
        '        PLACED, ACCEPTED, PREPARING, OUT_FOR_DELIVERY, DELIVERED, CANCELLED',
        '    }',
        '',
        '    private interface OrderState {',
        '        OrderStatus status();',
        '        void accept(Order order);',
        '        void startPreparing(Order order);',
        '        void dispatch(Order order);',
        '        void deliver(Order order);',
        '        void cancel(Order order);',
        '    }',
        '',
        '    private abstract static class BaseState implements OrderState {',
        '        public void accept(Order order) { throw invalid("accept"); }',
        '        public void startPreparing(Order order) { throw invalid("start preparing"); }',
        '        public void dispatch(Order order) { throw invalid("dispatch"); }',
        '        public void deliver(Order order) { throw invalid("deliver"); }',
        '        public void cancel(Order order) { throw invalid("cancel"); }',
        '',
        '        protected IllegalStateException invalid(String action) {',
        '            return new IllegalStateException("Cannot " + action + " when order is " + status());',
        '        }',
        '    }',
        '',
        '    private static final class PlacedState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.PLACED; }',
        '        public void accept(Order order) { order.transitionTo(new AcceptedState()); }',
        '        public void cancel(Order order) { order.cancelNow(); }',
        '    }',
        '',
        '    private static final class AcceptedState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.ACCEPTED; }',
        '        public void startPreparing(Order order) { order.transitionTo(new PreparingState()); }',
        '        public void cancel(Order order) { order.cancelNow(); }',
        '    }',
        '',
        '    private static final class PreparingState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.PREPARING; }',
        '        public void dispatch(Order order) { order.transitionTo(new OutForDeliveryState()); }',
        '        public void cancel(Order order) { order.cancelNow(); }',
        '    }',
        '',
        '    private static final class OutForDeliveryState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.OUT_FOR_DELIVERY; }',
        '        public void deliver(Order order) { order.completeDelivery(); }',
        '        public void cancel(Order order) { order.cancelNow(); }',
        '    }',
        '',
        '    private static final class DeliveredState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.DELIVERED; }',
        '    }',
        '',
        '    private static final class CancelledState extends BaseState {',
        '        public OrderStatus status() { return OrderStatus.CANCELLED; }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "DeliveryPartner.java",
      language: "java",
      content: [
        'import java.util.LinkedHashSet;',
        'import java.util.Objects;',
        'import java.util.Set;',
        '',
        'public final class DeliveryPartner {',
        '    private final String id;',
        '    private final String name;',
        '    private final int maxActiveOrders;',
        '    private final Set<String> activeOrderIds = new LinkedHashSet<>();',
        '    private Restaurant.Location currentLocation;',
        '    private boolean online;',
        '',
        '    public DeliveryPartner(String id, String name, Restaurant.Location currentLocation, int maxActiveOrders) {',
        '        if (maxActiveOrders <= 0) {',
        '            throw new IllegalArgumentException("maxActiveOrders must be positive");',
        '        }',
        '        this.id = Objects.requireNonNull(id, "id");',
        '        this.name = Objects.requireNonNull(name, "name");',
        '        this.currentLocation = Objects.requireNonNull(currentLocation, "currentLocation");',
        '        this.maxActiveOrders = maxActiveOrders;',
        '        this.online = true;',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getName() {',
        '        return name;',
        '    }',
        '',
        '    public synchronized boolean isAvailable() {',
        '        return online && activeOrderIds.size() < maxActiveOrders;',
        '    }',
        '',
        '    public synchronized int activeOrderCount() {',
        '        return activeOrderIds.size();',
        '    }',
        '',
        '    public synchronized void setOnline(boolean online) {',
        '        this.online = online;',
        '    }',
        '',
        '    public synchronized void updateLocation(Restaurant.Location location) {',
        '        this.currentLocation = Objects.requireNonNull(location, "location");',
        '    }',
        '',
        '    public synchronized double distanceTo(Restaurant.Location pickupLocation) {',
        '        return currentLocation.distanceTo(pickupLocation);',
        '    }',
        '',
        '    public synchronized void assignOrder(String orderId) {',
        '        if (!isAvailable()) {',
        '            throw new IllegalStateException(name + " is not available");',
        '        }',
        '        activeOrderIds.add(orderId);',
        '    }',
        '',
        '    public synchronized void completeOrder(String orderId) {',
        '        activeOrderIds.remove(orderId);',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "AssignmentStrategy.java",
      language: "java",
      content: [
        'import java.util.List;',
        '',
        'public interface AssignmentStrategy {',
        '    DeliveryPartner assign(Order order, List<DeliveryPartner> partners);',
        '',
        '    final class NearestPartnerStrategy implements AssignmentStrategy {',
        '        public DeliveryPartner assign(Order order, List<DeliveryPartner> partners) {',
        '            DeliveryPartner best = null;',
        '            double bestDistance = Double.MAX_VALUE;',
        '            for (DeliveryPartner partner : partners) {',
        '                if (!partner.isAvailable()) {',
        '                    continue;',
        '                }',
        '                double distance = partner.distanceTo(order.getRestaurant().getLocation());',
        '                if (distance < bestDistance) {',
        '                    best = partner;',
        '                    bestDistance = distance;',
        '                }',
        '            }',
        '            if (best == null) {',
        '                throw new IllegalStateException("No delivery partner available");',
        '            }',
        '            return best;',
        '        }',
        '    }',
        '',
        '    final class LeastBusyPartnerStrategy implements AssignmentStrategy {',
        '        public DeliveryPartner assign(Order order, List<DeliveryPartner> partners) {',
        '            DeliveryPartner best = null;',
        '            int fewestOrders = Integer.MAX_VALUE;',
        '            double bestDistance = Double.MAX_VALUE;',
        '            for (DeliveryPartner partner : partners) {',
        '                if (!partner.isAvailable()) {',
        '                    continue;',
        '                }',
        '                int activeOrders = partner.activeOrderCount();',
        '                double distance = partner.distanceTo(order.getRestaurant().getLocation());',
        '                if (activeOrders < fewestOrders || (activeOrders == fewestOrders && distance < bestDistance)) {',
        '                    best = partner;',
        '                    fewestOrders = activeOrders;',
        '                    bestDistance = distance;',
        '                }',
        '            }',
        '            if (best == null) {',
        '                throw new IllegalStateException("No delivery partner available");',
        '            }',
        '            return best;',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "OrderService.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.LinkedHashMap;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        'import java.util.UUID;',
        '',
        'public final class OrderService {',
        '    private final Map<String, Restaurant> restaurants = new LinkedHashMap<>();',
        '    private final Map<String, Order> orders = new LinkedHashMap<>();',
        '    private final List<DeliveryPartner> partners = new ArrayList<>();',
        '    private final List<OrderObserver> observers = new ArrayList<>();',
        '    private final OrderFactory orderFactory;',
        '    private AssignmentStrategy assignmentStrategy;',
        '',
        '    public OrderService(AssignmentStrategy assignmentStrategy, OrderFactory orderFactory) {',
        '        this.assignmentStrategy = Objects.requireNonNull(assignmentStrategy, "assignmentStrategy");',
        '        this.orderFactory = Objects.requireNonNull(orderFactory, "orderFactory");',
        '    }',
        '',
        '    public synchronized void registerRestaurant(Restaurant restaurant) {',
        '        restaurants.put(restaurant.getId(), Objects.requireNonNull(restaurant, "restaurant"));',
        '    }',
        '',
        '    public synchronized void registerPartner(DeliveryPartner partner) {',
        '        partners.add(Objects.requireNonNull(partner, "partner"));',
        '    }',
        '',
        '    public synchronized void addObserver(OrderObserver observer) {',
        '        observers.add(Objects.requireNonNull(observer, "observer"));',
        '    }',
        '',
        '    public synchronized void setAssignmentStrategy(AssignmentStrategy assignmentStrategy) {',
        '        this.assignmentStrategy = Objects.requireNonNull(assignmentStrategy, "assignmentStrategy");',
        '    }',
        '',
        '    public synchronized Order placeOrder(Cart cart) {',
        '        Objects.requireNonNull(cart, "cart");',
        '        if (!restaurants.containsKey(cart.getRestaurant().getId())) {',
        '            throw new IllegalArgumentException("Restaurant is not registered");',
        '        }',
        '        Order order = orderFactory.create(cart);',
        '        orders.put(order.getId(), order);',
        '        notifyObservers(order, "Order placed");',
        '        return order;',
        '    }',
        '',
        '    public synchronized void acceptOrder(String orderId) {',
        '        Order order = order(orderId);',
        '        order.accept();',
        '        notifyObservers(order, "Restaurant accepted the order");',
        '    }',
        '',
        '    public synchronized void startPreparing(String orderId) {',
        '        Order order = order(orderId);',
        '        order.markPreparing();',
        '        notifyObservers(order, "Restaurant started preparing");',
        '    }',
        '',
        '    public synchronized void dispatchOrder(String orderId) {',
        '        Order order = order(orderId);',
        '        DeliveryPartner partner = assignmentStrategy.assign(order, partners);',
        '        order.markOutForDelivery();',
        '        order.assignPartner(partner);',
        '        notifyObservers(order, "Assigned to " + partner.getName());',
        '    }',
        '',
        '    public synchronized void deliverOrder(String orderId) {',
        '        Order order = order(orderId);',
        '        order.markDelivered();',
        '        notifyObservers(order, "Order delivered");',
        '    }',
        '',
        '    public synchronized void cancelOrder(String orderId) {',
        '        Order order = order(orderId);',
        '        order.cancel();',
        '        notifyObservers(order, "Order cancelled");',
        '    }',
        '',
        '    private Order order(String orderId) {',
        '        Order order = orders.get(orderId);',
        '        if (order == null) {',
        '            throw new IllegalArgumentException("Unknown order " + orderId);',
        '        }',
        '        return order;',
        '    }',
        '',
        '    private void notifyObservers(Order order, String event) {',
        '        for (OrderObserver observer : observers) {',
        '            observer.onOrderUpdated(order, event);',
        '        }',
        '    }',
        '',
        '    public interface OrderObserver {',
        '        void onOrderUpdated(Order order, String event);',
        '    }',
        '',
        '    public static final class CustomerNotifier implements OrderObserver {',
        '        public void onOrderUpdated(Order order, String event) {',
        '            System.out.println("Customer notification: " + order.getId() + " is " + order.getStatus() + " - " + event);',
        '        }',
        '    }',
        '',
        '    public static final class RestaurantNotifier implements OrderObserver {',
        '        public void onOrderUpdated(Order order, String event) {',
        '            System.out.println("Restaurant notification for " + order.getRestaurant().getName() + ": " + event);',
        '        }',
        '    }',
        '',
        '    public static final class PartnerNotifier implements OrderObserver {',
        '        public void onOrderUpdated(Order order, String event) {',
        '            if (order.getPartner() != null) {',
        '                System.out.println("Partner notification for " + order.getPartner().getName() + ": " + event);',
        '            }',
        '        }',
        '    }',
        '',
        '    public interface PricingStrategy {',
        '        PricingQuote price(Cart cart);',
        '    }',
        '',
        '    public static final class DefaultPricingStrategy implements PricingStrategy {',
        '        public PricingQuote price(Cart cart) {',
        '            long subtotal = cart.subtotalPaise();',
        '            long deliveryFee = subtotal >= 49900 ? 0 : 3900;',
        '            long platformFee = 600;',
        '            long tax = Math.round(subtotal * 0.05);',
        '            return new PricingQuote(subtotal, deliveryFee, platformFee, tax);',
        '        }',
        '    }',
        '',
        '    public static final class PricingQuote {',
        '        private final long subtotalPaise;',
        '        private final long deliveryFeePaise;',
        '        private final long platformFeePaise;',
        '        private final long taxPaise;',
        '',
        '        public PricingQuote(long subtotalPaise, long deliveryFeePaise, long platformFeePaise, long taxPaise) {',
        '            this.subtotalPaise = subtotalPaise;',
        '            this.deliveryFeePaise = deliveryFeePaise;',
        '            this.platformFeePaise = platformFeePaise;',
        '            this.taxPaise = taxPaise;',
        '        }',
        '',
        '        public long totalPaise() {',
        '            return subtotalPaise + deliveryFeePaise + platformFeePaise + taxPaise;',
        '        }',
        '',
        '        @Override',
        '        public String toString() {',
        '            return "subtotal=" + subtotalPaise + ", delivery=" + deliveryFeePaise + ", platform=" + platformFeePaise + ", tax=" + taxPaise + ", total=" + totalPaise();',
        '        }',
        '    }',
        '',
        '    public abstract static class OrderFactory {',
        '        private final PricingStrategy pricingStrategy;',
        '',
        '        protected OrderFactory(PricingStrategy pricingStrategy) {',
        '            this.pricingStrategy = Objects.requireNonNull(pricingStrategy, "pricingStrategy");',
        '        }',
        '',
        '        public final Order create(Cart cart) {',
        '            if (cart.isEmpty()) {',
        '                throw new IllegalStateException("Cannot place an empty cart");',
        '            }',
        '            if (!cart.getRestaurant().isAcceptingOrders()) {',
        '                throw new IllegalStateException("Restaurant is not accepting orders");',
        '            }',
        '            PricingQuote quote = pricingStrategy.price(cart);',
        '            return newOrder(cart, quote);',
        '        }',
        '',
        '        protected abstract Order newOrder(Cart cart, PricingQuote quote);',
        '    }',
        '',
        '    public static final class StandardOrderFactory extends OrderFactory {',
        '        public StandardOrderFactory(PricingStrategy pricingStrategy) {',
        '            super(pricingStrategy);',
        '        }',
        '',
        '        protected Order newOrder(Cart cart, PricingQuote quote) {',
        '            return new Order("ORD-" + UUID.randomUUID(), cart.getCustomerId(), cart.getRestaurant(), cart.lines(), quote);',
        '        }',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        'public class Main {',
        '    public static void main(String[] args) {',
        '        Restaurant restaurant = new Restaurant("rest-1", "Dosa Hub", new Restaurant.Location(12.9716, 77.5946));',
        '        restaurant.addMenuItem(new MenuItem("dosa", "Masala Dosa", 12000));',
        '        restaurant.addMenuItem(new MenuItem("coffee", "Filter Coffee", 5000));',
        '',
        '        DeliveryPartner priya = new DeliveryPartner("dp-1", "Priya", new Restaurant.Location(12.9720, 77.5950), 2);',
        '        DeliveryPartner aman = new DeliveryPartner("dp-2", "Aman", new Restaurant.Location(12.9900, 77.6000), 2);',
        '',
        '        OrderService service = new OrderService(',
        '            new AssignmentStrategy.NearestPartnerStrategy(),',
        '            new OrderService.StandardOrderFactory(new OrderService.DefaultPricingStrategy())',
        '        );',
        '        service.registerRestaurant(restaurant);',
        '        service.registerPartner(priya);',
        '        service.registerPartner(aman);',
        '        service.addObserver(new OrderService.CustomerNotifier());',
        '        service.addObserver(new OrderService.RestaurantNotifier());',
        '        service.addObserver(new OrderService.PartnerNotifier());',
        '',
        '        Cart cart = new Cart("cust-101", restaurant);',
        '        cart.addItem("dosa", 2);',
        '        cart.addItem("coffee", 1);',
        '',
        '        Order order = service.placeOrder(cart);',
        '        service.acceptOrder(order.getId());',
        '        service.startPreparing(order.getId());',
        '        service.dispatchOrder(order.getId());',
        '        service.deliverOrder(order.getId());',
        '',
        '        System.out.println("Final bill paise: " + order.getQuote().totalPaise());',
        '        System.out.println("Timeline: " + order.timeline());',
        '    }',
        '}',
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "MenuItem",
      detailMD:
        "Immutable identity, name, and price with a synchronized availability flag. The cart reads availability before adding an item, while restaurants retain control over toggling items on or off.",
    },
    {
      className: "Restaurant",
      detailMD:
        "Restaurant owns menu and location. The nested **Location** value object gives assignment strategies a simple distance function without introducing map-provider dependencies.",
    },
    {
      className: "Cart",
      detailMD:
        "Cart binds a customer to one restaurant and stores item lines. It validates quantity and availability, computes subtotal, and returns snapshots so an order is insulated from later cart edits.",
    },
    {
      className: "Order",
      detailMD:
        "Order is the lifecycle aggregate. It stores the pricing quote, selected items, optional partner, timeline, and nested state objects for Placed, Accepted, Preparing, OutForDelivery, Delivered, and Cancelled.",
    },
    {
      className: "DeliveryPartner",
      detailMD:
        "Tracks partner identity, location, online flag, capacity, and active orders. Assignment strategies use **distanceTo** and **activeOrderCount**, while the order releases capacity on delivery or cancellation.",
    },
    {
      className: "AssignmentStrategy",
      detailMD:
        "Strategy interface with two nested implementations. **NearestPartnerStrategy** minimizes pickup distance; **LeastBusyPartnerStrategy** minimizes active orders and uses distance as a tie-breaker.",
    },
    {
      className: "OrderService",
      detailMD:
        "Application facade plus nested collaborators for observers, pricing, quote, and order factory. It orchestrates placement, state transitions, partner assignment, and notification fanout.",
    },
    {
      className: "Main",
      detailMD:
        "Small executable demo wiring a restaurant, menu, partners, nearest strategy, default pricing, observers, and the complete happy path from placement to delivery.",
    },
  ],

  dryRun: {
    inputMD:
      "Restaurant **Dosa Hub** has Masala Dosa at 12000 paise and Filter Coffee at 5000 paise. Cart has 2 dosas and 1 coffee. Partners: Priya is nearest with 0 active orders, Aman is farther with 0 active orders.",
    columns: ["Step", "Action", "Order status", "Partner state", "Notification", "Result"],
    rows: [
      ["1", "placeOrder(cart)", "PLACED", "No partner", "Customer + restaurant see placed", "Quote = 29000 + 3900 + 600 + 1450 = 34950 paise"],
      ["2", "acceptOrder(orderId)", "ACCEPTED", "No partner", "Restaurant accepted", "State machine allows next step to prepare"],
      ["3", "startPreparing(orderId)", "PREPARING", "No partner", "Preparing update", "Order is now eligible for dispatch"],
      ["4", "dispatchOrder(orderId)", "OUT_FOR_DELIVERY", "Priya active orders = 1", "Assigned to Priya", "Nearest strategy chooses Priya"],
      ["5", "deliverOrder(orderId)", "DELIVERED", "Priya active orders = 0", "Delivered update", "Terminal success state"],
    ],
    narrativeMD:
      "The trace shows why state and strategy are separate. The order decides whether dispatch is legal; the strategy decides which partner receives the dispatched order.",
  },

  complexity: [
    {
      operation: "add item to cart",
      time: "O(1)",
      space: "O(1)",
      note: "Menu lookup and line merge are map operations for a single restaurant.",
    },
    {
      operation: "place order",
      time: "O(I)",
      space: "O(I)",
      note: "I cart lines are copied into an immutable order snapshot and priced.",
    },
    {
      operation: "state transition",
      time: "O(N)",
      space: "O(1)",
      note: "The transition is constant; notifying N observers dominates.",
    },
    {
      operation: "assign nearest partner",
      time: "O(P)",
      space: "O(1)",
      note: "Scans P partners and keeps the smallest distance to the restaurant.",
    },
    {
      operation: "assign least-busy partner",
      time: "O(P)",
      space: "O(1)",
      note: "Scans P partners, comparing active order count and then distance.",
    },
  ],
  complexityNotesMD:
    "For interview scale, O(P) partner scans are clear and acceptable. At city scale, replace the list with a geo-index plus availability buckets while preserving the **AssignmentStrategy** interface.",

  extensibility: [
    {
      label: "New assignment policy",
      detailMD:
        "Add a new **AssignmentStrategy** such as highest-rated, zone-aware, or partner-preferred. **OrderService.dispatchOrder** remains unchanged.",
    },
    {
      label: "New pricing rule",
      detailMD:
        "Implement **PricingStrategy** for surge fee, coupon discount, restaurant packaging charge, or subscription free delivery. Orders still receive a quote snapshot.",
    },
    {
      label: "New notification channel",
      detailMD:
        "Implement **OrderObserver** for push, SMS, WhatsApp, email, restaurant dashboard, or partner app. No lifecycle code changes are required.",
    },
    {
      label: "Scheduled or group orders",
      detailMD:
        "Subclass **OrderFactory** and override **newOrder** to create scheduled or group-order variants while keeping validation and pricing in the factory skeleton.",
    },
    {
      label: "Cancellation policy",
      detailMD:
        "Add a policy object consulted by **Order.cancel** or **OrderService.cancelOrder** to block cancellation after partner arrival or to compute a fee.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Enum status with switch statements",
      detailMD:
        "Store **OrderStatus** directly and use switch statements in **OrderService** to validate transitions.",
      tradeoffsMD:
        "Less code for a toy solution, but transition rules leak into orchestration and become harder to extend or test as cancellation, refund, and failure states grow.",
    },
    {
      name: "Dedicated dispatch service",
      detailMD:
        "Move partner assignment into a separate **DispatchService** that owns partner pools, geospatial indexing, retries, and reassignment after partner rejection.",
      tradeoffsMD:
        "Better production separation, but for an LLD interview it can distract from the core order aggregate unless the interviewer asks about scale.",
    },
    {
      name: "Event-sourced order lifecycle",
      detailMD:
        "Persist events such as OrderPlaced, RestaurantAccepted, PartnerAssigned, and OrderDelivered, then rebuild current state from the event stream.",
      tradeoffsMD:
        "Excellent auditability and replay, but more infrastructure and eventual consistency than needed for the base object model.",
    },
  ],

  commonMistakes: [
    "Treating order status as a public mutable enum and allowing any service method to set it directly.",
    "Putting nearest and least-busy partner matching in one long **if** block inside **OrderService**.",
    "Forgetting to snapshot menu prices at order creation, so later menu edits change historical orders.",
    "Not releasing a partner's active order slot after delivery or cancellation.",
    "Sending notifications from inside every state class instead of through a centralized observer fanout.",
    "Allowing dispatch before the restaurant has accepted and started preparing the order.",
    "Mixing payment, coupon, and refund workflows into the core lifecycle before clarifying scope.",
  ],

  followUps: [
    {
      question: "How would you support partner rejection after assignment?",
      answerMD:
        "Add an Assigned state or dispatch attempt object. If a partner rejects, release that partner, record the attempt, and ask the assignment strategy for the next candidate.",
    },
    {
      question: "How would you make nearest-partner lookup faster than O(P)?",
      answerMD:
        "Index online partners by geohash or grid cell, then query nearby cells first. The optimization sits behind **AssignmentStrategy** so the order flow is unchanged.",
    },
    {
      question: "How do you prevent two dispatchers from assigning two partners?",
      answerMD:
        "Synchronize or transact on the order row during dispatch. The check that the order is Preparing and the write to OutForDelivery plus partner assignment must be atomic.",
    },
    {
      question: "Where do refunds and cancellation fees fit?",
      answerMD:
        "Use a cancellation policy plus payment adapter around **OrderService.cancelOrder**. The order marks a legal terminal state; the payment workflow handles money movement.",
    },
    {
      question: "How would you notify millions of customers reliably?",
      answerMD:
        "Make observers publish domain events to a durable queue. Workers perform push, SMS, email, and retries with idempotency keys based on order id and status.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence and transactions",
      detailMD:
        "Persist orders, menu snapshots, partner assignments, and status events. Dispatch should use a transaction or compare-and-set from Preparing to OutForDelivery.",
    },
    {
      label: "Geospatial matching",
      detailMD:
        "Store partner locations in a geospatial index and update them through a streaming channel. Strategy implementations can query nearby partners instead of scanning a list.",
    },
    {
      label: "Notification reliability",
      detailMD:
        "Replace synchronous observers with durable events, retries, dead-letter queues, and idempotent notification sends.",
    },
    {
      label: "Menu and price consistency",
      detailMD:
        "Cache menus carefully, but snapshot item names, quantities, and prices into the order so support and refunds use the original customer agreement.",
    },
    {
      label: "Observability",
      detailMD:
        "Track order transition latency, restaurant acceptance time, partner assignment success rate, cancellation reason, and notification delivery failures.",
    },
  ],

  interviewNotes: [
    "Does the candidate make the order lifecycle explicit instead of scattering status checks?",
    "Can they explain why partner matching is a Strategy and when nearest versus least-busy should be used?",
    "Do they separate pricing snapshot, payment, and notification concerns?",
    "Do they preserve invariants around dispatch and terminal states?",
    "Can they describe the production upgrade path without overbuilding the base LLD?",
  ],

  quiz: [
    {
      question: "Why use the State pattern for **Order**?",
      options: [
        "To ensure each status owns the transitions allowed from that status",
        "To make menu lookup faster",
        "To avoid storing a restaurant on the order",
        "To replace the need for observers",
      ],
      answerIndex: 0,
      explanationMD:
        "State keeps lifecycle rules local to the status. Invalid jumps fail in the domain object instead of relying on service-level conditionals.",
    },
    {
      question: "What does **AssignmentStrategy** make easy to change?",
      options: [
        "The customer id format",
        "The policy for choosing a delivery partner",
        "The Java package name",
        "The cart line data structure only",
      ],
      answerIndex: 1,
      explanationMD:
        "Nearest, least-busy, zone-aware, and rating-aware matching can all implement the same interface.",
    },
    {
      question: "Why should price be snapshotted when the order is created?",
      options: [
        "So the customer agreement is stable even if the restaurant changes menu prices later",
        "So partner assignment can skip distance checks",
        "So cancelled orders can become delivered",
        "So observers do not need to run",
      ],
      answerIndex: 0,
      explanationMD:
        "An order is a commercial record. It should keep the item prices and fees accepted at checkout time.",
    },
    {
      question: "Which component should send status updates to customer, restaurant, and partner channels?",
      options: [
        "MenuItem",
        "OrderObserver implementations registered with OrderService",
        "NearestPartnerStrategy",
        "Cart.Line",
      ],
      answerIndex: 1,
      explanationMD:
        "Observer decouples notification channels from lifecycle logic and lets each channel react to the same status event.",
    },
    {
      question: "What must be atomic during dispatch?",
      options: [
        "Reading every menu in the city",
        "Checking the order can move out for delivery and assigning exactly one partner",
        "Formatting the final bill string",
        "Registering a new restaurant",
      ],
      answerIndex: 1,
      explanationMD:
        "If two dispatchers race, only one should move the order from Preparing to OutForDelivery and reserve partner capacity.",
    },
  ],

  practiceVariants: [
    {
      title: "Partner rejection and reassignment",
      detailMD:
        "Add a PartnerAssigned state and allow a partner to reject. Re-run assignment while avoiding partners who already rejected the order.",
      difficulty: "Advanced",
    },
    {
      title: "Coupon and subscription pricing",
      detailMD:
        "Add pricing strategies for coupons, free-delivery subscription, and surge fee while keeping **OrderFactory** unchanged.",
      difficulty: "Intermediate",
    },
    {
      title: "Multi-restaurant checkout",
      detailMD:
        "Split one checkout into multiple restaurant-specific orders under a parent checkout id. Decide how partner assignment and cancellation work per child order.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the core aggregate in food delivery LLD?",
      back: "**Order** — it owns item snapshot, pricing quote, lifecycle state, partner assignment, and status timeline.",
    },
    {
      front: "Which pattern protects the order lifecycle?",
      back: "State. Each order status allows only the next legal transitions.",
    },
    {
      front: "Which pattern swaps nearest and least-busy partner matching?",
      back: "Strategy through **AssignmentStrategy**.",
    },
    {
      front: "Why use observers for notifications?",
      back: "They decouple customer, restaurant, and partner channels from the domain lifecycle.",
    },
    {
      front: "When is price calculated?",
      back: "At order creation, then stored as a **PricingQuote** snapshot on the order.",
    },
    {
      front: "What is the dispatch critical section?",
      back: "Move Preparing to OutForDelivery and reserve exactly one partner capacity slot atomically.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Restaurant, MenuItem, Cart, Order, DeliveryPartner, AssignmentStrategy, OrderService, OrderObserver.",
    "",
    "**Lifecycle:** Placed -> Accepted -> Preparing -> OutForDelivery -> Delivered. Cancelled is terminal for allowed failure paths.",
    "",
    "**Patterns:** State for lifecycle, Strategy for assignment and pricing, Observer for notifications, Factory Method for order creation.",
    "",
    "**Pricing:** snapshot subtotal, delivery fee, platform fee, tax, and total at order creation.",
    "",
    "**Partner matching:** nearest minimizes pickup distance; least-busy minimizes active orders and uses distance as tie-breaker.",
    "",
    "**Invariants:** one restaurant per cart; non-empty cart to place order; no dispatch before preparation; no delivery before dispatch; release partner capacity on terminal state.",
    "",
    "**Scale path:** persist status events, use row locks or compare-and-set for dispatch, replace partner list scan with geospatial index, publish notifications through a queue.",
  ].join("\n"),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, and Vlissides",
    },
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
    {
      title: "Martin Fowler — Domain Event",
      kind: "Blog",
      url: "https://martinfowler.com/eaaDev/DomainEvent.html",
      author: "Martin Fowler",
    },
  ],

  relatedProblems: [
    { slug: "cab-booking", note: "Partner matching and trip lifecycle are analogous to courier assignment and order status." },
    { slug: "shopping-cart", note: "Cart modelling, item snapshots, and pricing rules are direct prerequisites." },
    { slug: "movie-booking", note: "Another lifecycle-heavy marketplace problem with state, strategy, and notifications." },
  ],
};
