import type { LLDProblemContent } from "../types";

/**
 * Exemplar LLD problem — Design Google Drive.
 *
 * Fresh Java implementation authored inline for the google-drive catalog entry.
 */
export const googleDrive: LLDProblemContent = {
  slug: "google-drive",

  statementMD: [
    "Design the object model for **Google Drive** at an LLD level: users create files and folders, organize them as a tree, share items with viewer/commenter/editor permissions, version file content, search accessible items, star important items, and move items to trash.",
    "",
    "The important interview axis is not storage blocks or global scale. It is the **permission model**: every read, comment, edit, share, and trash operation must pass through a Proxy/authorization layer that resolves inherited folder permissions before touching the Composite file tree.",
  ].join("\n"),

  businessContextMD: [
    "Google Drive is a strong expert-level LLD problem because it combines a familiar product surface with subtle ownership and sharing rules.",
    "Most candidates model the file/folder tree quickly; stronger candidates separate tree behavior from authorization, avoid scattering **if user can edit** checks across services, and explain how inherited ACLs interact with direct file shares.",
    "The design below keeps the hierarchy simple and puts access decisions behind **AccessProxy**, making permission correctness the center of the solution.",
  ].join("\n"),

  functionalRequirements: [
    "Create folders and files under an existing folder using a Composite tree.",
    "Read file contents only when the caller has at least **VIEWER** access through direct or inherited permission.",
    "Add comments only when the caller has at least **COMMENTER** access.",
    "Edit file contents, restore versions, create children, share items, and trash items only when the caller has **EDITOR** access.",
    "Support direct sharing at any file or folder with permission levels **VIEWER**, **COMMENTER**, and **EDITOR**.",
    "Inherit folder permissions down to descendants unless a descendant has a direct permission for that user.",
    "Maintain file version history every time content changes and allow restoring an older version as a new current version.",
    "Search by pluggable strategy over only visible, non-trashed items; support starred and trashed state.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Permission correctness",
      detailMD:
        "Every public operation must delegate to **AccessProxy** before reading or mutating an item. A missed check is a product-severity bug, not a minor edge case.",
    },
    {
      label: "Extensible authorization",
      detailMD:
        "Permission resolution should support direct ACLs today and inherited folder ACLs tomorrow without rewriting **DriveService** flows.",
    },
    {
      label: "Tree integrity",
      detailMD:
        "A folder owns unique child names, each child has one parent, and moving or deleting should preserve a valid Composite structure.",
    },
    {
      label: "Search isolation",
      detailMD:
        "Search policy should vary independently of traversal. Name search, text search, owner search, or metadata search should be strategies.",
    },
    {
      label: "Auditability",
      detailMD:
        "Version changes, shares, stars, and trash operations should be observable so a production system can emit activity feed and audit events.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need to model actual blob storage, chunking, or sync clients?",
      answerMD:
        "No. This is the LLD view of Drive objects and permissions. Blob storage, sync conflict resolution, and offline clients are production extensions or a Dropbox-style follow-up.",
    },
    {
      question: "Which permission levels are required?",
      answerMD:
        "Use exactly **VIEWER**, **COMMENTER**, and **EDITOR**. Treat the owner as having effective editor access even if no ACL row is present.",
    },
    {
      question: "Do folder permissions apply to files inside the folder?",
      answerMD:
        "Yes. **AccessProxy** walks from the target item toward ancestors and uses the nearest direct permission it finds; owners are granted effective editor access.",
    },
    {
      question: "Is starring global or per user?",
      answerMD:
        "The interview implementation stores a simple starred flag on the item to keep focus on permissions. In production it should be per-user metadata.",
    },
    {
      question: "What does trash mean in the base design?",
      answerMD:
        "Trashed items remain in the tree but are hidden from normal search and visible-tree output. A permanent purge can be added as a follow-up policy.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class DriveItem {",
    "        <<abstract>>",
    "        -String id",
    "        -String name",
    "        -String ownerId",
    "        -FolderItem parent",
    "        -Map~String,Permission~ permissions",
    "        +grantPermission(String, Permission) void",
    "        +directPermissionFor(String) Permission",
    "        +getPath() String",
    "        +size() long",
    "        +searchText() String",
    "    }",
    "    class FileItem {",
    "        -VersionHistory history",
    "        -List~String~ comments",
    "        +read() String",
    "        +updateContent(String) void",
    "        +addComment(String, String) void",
    "        +restoreVersion(String) void",
    "    }",
    "    class FolderItem {",
    "        -Map~String,DriveItem~ children",
    "        +addChild(DriveItem) void",
    "        +children() List",
    "        +findById(String) DriveItem",
    "    }",
    "    class Permission {",
    "        <<enumeration>>",
    "        VIEWER",
    "        COMMENTER",
    "        EDITOR",
    "    }",
    "    class AccessProxy {",
    "        +effectivePermission(String, DriveItem) Permission",
    "        +require(String, DriveItem, Permission, String) void",
    "        +share(String, DriveItem, String, Permission) void",
    "    }",
    "    class VersionHistory {",
    "        +addVersion(String) String",
    "        +current() String",
    "        +restore(String) String",
    "        +versionIds() List",
    "    }",
    "    class DriveService {",
    "        -FolderItem root",
    "        -AccessProxy access",
    "        +createFile(String, String, String, String) FileItem",
    "        +share(String, String, String, Permission) void",
    "        +search(String, String, SearchStrategy) List",
    "    }",
    "    class SearchStrategy {",
    "        <<interface>>",
    "        +matches(DriveItem, String) boolean",
    "    }",
    "    class DriveObserver {",
    "        <<interface>>",
    "        +onEvent(String, DriveItem) void",
    "    }",
    "    DriveItem <|-- FileItem",
    "    DriveItem <|-- FolderItem",
    "    FolderItem o-- DriveItem",
    "    FileItem o-- VersionHistory",
    "    DriveItem --> Permission",
    "    AccessProxy ..> DriveItem",
    "    AccessProxy ..> Permission",
    "    DriveService o-- FolderItem",
    "    DriveService o-- AccessProxy",
    "    DriveService ..> SearchStrategy",
    "    DriveService ..> DriveObserver",
  ].join("\n"),
  classDiagramCaptionMD:
    "The Composite tree is intentionally small: **DriveItem** is the component, **FileItem** is the leaf, and **FolderItem** is the composite. **AccessProxy** is the critical layer because it resolves effective permission before **DriveService** touches any item.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Alice",
    "    actor Bob",
    "    participant Service as DriveService",
    "    participant Proxy as AccessProxy",
    "    participant Folder as FolderItem",
    "    participant File as FileItem",
    "    Alice->>Service: share(folderId, Bob, COMMENTER)",
    "    Service->>Proxy: require(Alice, folder, EDITOR, share)",
    "    Proxy-->>Service: allowed",
    "    Service->>Proxy: share(Alice, folder, Bob, COMMENTER)",
    "    Bob->>Service: commentFile(fileId, note)",
    "    Service->>Proxy: require(Bob, file, COMMENTER, comment)",
    "    Proxy->>File: inspect direct permission",
    "    Proxy->>Folder: inspect inherited permission",
    "    Proxy-->>Service: allowed by folder COMMENTER",
    "    Service->>File: addComment(Bob, note)",
    "    Bob->>Service: updateFile(fileId, newContent)",
    "    Service->>Proxy: require(Bob, file, EDITOR, edit)",
    "    Proxy-->>Service: denied",
    "    Service-->>Bob: SecurityException",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The sequence highlights the interview crux: Bob never talks to the file directly. The service asks **AccessProxy**, and the proxy may grant access from an ancestor folder permission.",

  entities: [
    {
      name: "DriveService",
      responsibilityMD:
        "Application facade. Resolves ids, calls **AccessProxy** for every operation, mutates the Composite only after authorization, runs search strategies, and notifies observers.",
      attributes: ["root", "access", "observers"],
    },
    {
      name: "AccessProxy",
      responsibilityMD:
        "Authorization boundary. Computes effective permission from owner, direct ACL, or inherited ancestor ACL, then allows or rejects a requested action.",
      attributes: ["effectivePermission", "require", "share"],
    },
    {
      name: "DriveItem",
      responsibilityMD:
        "Abstract Component in the Composite. Owns identity, owner, parent link, starred/trash flags, direct permissions, path calculation, and the common operations files and folders implement.",
      attributes: ["id", "name", "ownerId", "parent", "permissions"],
    },
    {
      name: "FileItem",
      responsibilityMD:
        "Leaf node. Stores content versions, comments, read/update behavior, and searchable text for the file body and comments.",
      attributes: ["VersionHistory", "comments"],
    },
    {
      name: "FolderItem",
      responsibilityMD:
        "Composite node. Owns uniquely named child **DriveItem** objects, supports recursive id lookup, and aggregates descendant size.",
      attributes: ["children"],
    },
    {
      name: "Permission",
      responsibilityMD:
        "Ordered enum for **VIEWER**, **COMMENTER**, and **EDITOR**. The **allows** method expresses that editor includes commenter and viewer rights.",
      attributes: ["VIEWER", "COMMENTER", "EDITOR"],
    },
    {
      name: "VersionHistory",
      responsibilityMD:
        "Append-only version list. Each content update creates a new version id; restoring an old version appends it as the latest version for auditability.",
      attributes: ["versions", "current", "restore"],
    },
    {
      name: "SearchStrategy",
      responsibilityMD:
        "Pluggable predicate used by **DriveService.search** after authorization filtering. It keeps name search and content search out of the traversal code.",
      attributes: ["matches(item, query)"],
    },
    {
      name: "DriveObserver",
      responsibilityMD:
        "Notification seam for activity feed, audit log, and indexing. Observers receive events after successful mutations.",
      attributes: ["onEvent(event, item)"],
    },
  ],

  patternsUsed: [
    {
      name: "Composite",
      whyMD:
        "**DriveItem** is the shared component, **FileItem** is the leaf, and **FolderItem** is the composite. The service can search, size, and display a subtree through one abstraction.",
    },
    {
      name: "Proxy",
      whyMD:
        "**AccessProxy** protects the real objects. It resolves effective permission from owner, direct share, or inherited folder share before the service reads or mutates an item.",
    },
    {
      name: "Strategy",
      whyMD:
        "**SearchStrategy** lets the traversal stay fixed while matching behavior changes: by name, by content, by owner, by metadata, or by future ranking logic.",
    },
    {
      name: "Observer",
      whyMD:
        "**DriveObserver** subscribers are notified after version, share, star, and trash changes. This models activity feeds, audit trails, and async search indexing without coupling them to core mutations.",
    },
  ],

  designSteps: [
    {
      title: "Model permission levels as an ordered enum",
      detailMD:
        "Viewer, commenter, and editor form a capability ladder. Put that ladder in **Permission.allows** so authorization never relies on scattered ordinal checks or string comparisons.",
      code: [
        "public enum Permission {",
        "    VIEWER, COMMENTER, EDITOR;",
        "",
        "    public boolean allows(Permission required) {",
        "        return ordinal() >= required.ordinal();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Build the file tree as a Composite",
      detailMD:
        "Keep identity, owner, ACL, path, starred, and trash state in **DriveItem**. Files and folders implement **size** and **searchText** differently while remaining one tree type.",
      code: [
        "public abstract class DriveItem {",
        "    public abstract boolean isFolder();",
        "    public abstract long size();",
        "    public abstract String searchText();",
        "}",
      ].join("\n"),
    },
    {
      title: "Make the Proxy the only permission decision maker",
      detailMD:
        "The service never asks raw ACL maps. It calls **AccessProxy.require** with the action and required permission, and the proxy walks ancestors for inherited access.",
      code: [
        "public void require(String userId, DriveItem item, Permission required, String action) {",
        "    Permission actual = effectivePermission(userId, item);",
        "    if (actual == null || !actual.allows(required)) {",
        "        throw new SecurityException(userId + \" cannot \" + action + \" \" + item.getPath());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Keep versioning inside the file leaf",
      detailMD:
        "A folder should not know how file content changes. **FileItem.updateContent** appends to **VersionHistory**, and restore is just another version append for an auditable timeline.",
      code: [
        "public void updateContent(String newContent) {",
        "    versionHistory.addVersion(newContent == null ? \"\" : newContent);",
        "}",
      ].join("\n"),
    },
    {
      title: "Filter before matching in search",
      detailMD:
        "Search traversal visits the tree, but each candidate is checked with **AccessProxy.canView** and ignored if trashed before the **SearchStrategy** runs. A user never discovers private names through search.",
    },
    {
      title: "Publish domain events after successful mutations",
      detailMD:
        "Observers are called only after authorization and mutation succeed. That ordering keeps audit logs and search indexes consistent with the authoritative tree.",
    },
  ],

  implementation: [
    {
      filename: "DriveItem.java",
      language: "java",
      content: [
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "",
        "public abstract class DriveItem {",
        "    private final String id;",
        "    private String name;",
        "    private final String ownerId;",
        "    private FolderItem parent;",
        "    private boolean starred;",
        "    private boolean trashed;",
        "    private final Map<String, Permission> permissions = new LinkedHashMap<>();",
        "",
        "    protected DriveItem(String name, String ownerId) {",
        "        this.id = UUID.randomUUID().toString();",
        "        this.name = validateName(name);",
        "        this.ownerId = Objects.requireNonNull(ownerId, \"ownerId\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public void rename(String newName) {",
        "        this.name = validateName(newName);",
        "    }",
        "",
        "    public String getOwnerId() {",
        "        return ownerId;",
        "    }",
        "",
        "    public FolderItem getParent() {",
        "        return parent;",
        "    }",
        "",
        "    void setParent(FolderItem parent) {",
        "        this.parent = parent;",
        "    }",
        "",
        "    public boolean isStarred() {",
        "        return starred;",
        "    }",
        "",
        "    public void setStarred(boolean starred) {",
        "        this.starred = starred;",
        "    }",
        "",
        "    public boolean isTrashed() {",
        "        return trashed;",
        "    }",
        "",
        "    public void setTrashed(boolean trashed) {",
        "        this.trashed = trashed;",
        "    }",
        "",
        "    public void grantPermission(String userId, Permission permission) {",
        "        if (ownerId.equals(userId)) {",
        "            throw new IllegalArgumentException(\"Owner already has editor access\");",
        "        }",
        "        permissions.put(Objects.requireNonNull(userId, \"userId\"), Objects.requireNonNull(permission, \"permission\"));",
        "    }",
        "",
        "    public void revokePermission(String userId) {",
        "        permissions.remove(userId);",
        "    }",
        "",
        "    public Permission directPermissionFor(String userId) {",
        "        return permissions.get(userId);",
        "    }",
        "",
        "    public Map<String, Permission> permissionsSnapshot() {",
        "        return new LinkedHashMap<>(permissions);",
        "    }",
        "",
        "    public String getPath() {",
        "        if (parent == null) {",
        "            return \"/\" + name;",
        "        }",
        "        return parent.getPath() + \"/\" + name;",
        "    }",
        "",
        "    private String validateName(String candidate) {",
        "        Objects.requireNonNull(candidate, \"name\");",
        "        if (candidate.trim().isEmpty() || candidate.contains(\"/\")) {",
        "            throw new IllegalArgumentException(\"Invalid Drive item name\");",
        "        }",
        "        return candidate;",
        "    }",
        "",
        "    public abstract boolean isFolder();",
        "",
        "    public abstract long size();",
        "",
        "    public abstract String searchText();",
        "",
        "    public abstract String printTree(String indent);",
        "}",
      ].join("\n"),
    },
    {
      filename: "FileItem.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.List;",
        "",
        "public class FileItem extends DriveItem {",
        "    private final VersionHistory versionHistory = new VersionHistory();",
        "    private final List<String> comments = new ArrayList<>();",
        "",
        "    public FileItem(String name, String ownerId, String initialContent) {",
        "        super(name, ownerId);",
        "        versionHistory.addVersion(initialContent == null ? \"\" : initialContent);",
        "    }",
        "",
        "    @Override",
        "    public boolean isFolder() {",
        "        return false;",
        "    }",
        "",
        "    public String read() {",
        "        return versionHistory.current();",
        "    }",
        "",
        "    public void updateContent(String newContent) {",
        "        versionHistory.addVersion(newContent == null ? \"\" : newContent);",
        "    }",
        "",
        "    public void addComment(String userId, String comment) {",
        "        comments.add(userId + \": \" + (comment == null ? \"\" : comment));",
        "    }",
        "",
        "    public List<String> comments() {",
        "        return new ArrayList<>(comments);",
        "    }",
        "",
        "    public VersionHistory history() {",
        "        return versionHistory;",
        "    }",
        "",
        "    public void restoreVersion(String versionId) {",
        "        versionHistory.restore(versionId);",
        "    }",
        "",
        "    @Override",
        "    public long size() {",
        "        return read().length();",
        "    }",
        "",
        "    @Override",
        "    public String searchText() {",
        "        return getName() + \" \" + read() + \" \" + String.join(\" \", comments);",
        "    }",
        "",
        "    @Override",
        "    public String printTree(String indent) {",
        "        return indent + \"- \" + getName() + \" (\" + size() + \" chars)\" + (isTrashed() ? \" [trashed]\" : \"\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "FolderItem.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public class FolderItem extends DriveItem {",
        "    private final Map<String, DriveItem> children = new LinkedHashMap<>();",
        "",
        "    public FolderItem(String name, String ownerId) {",
        "        super(name, ownerId);",
        "    }",
        "",
        "    @Override",
        "    public boolean isFolder() {",
        "        return true;",
        "    }",
        "",
        "    public void addChild(DriveItem item) {",
        "        Objects.requireNonNull(item, \"item\");",
        "        if (children.containsKey(item.getName())) {",
        "            throw new IllegalArgumentException(\"Duplicate child name: \" + item.getName());",
        "        }",
        "        item.setParent(this);",
        "        children.put(item.getName(), item);",
        "    }",
        "",
        "    public DriveItem removeChild(String name) {",
        "        DriveItem removed = children.remove(name);",
        "        if (removed == null) {",
        "            throw new IllegalArgumentException(\"Missing child: \" + name);",
        "        }",
        "        removed.setParent(null);",
        "        return removed;",
        "    }",
        "",
        "    public List<DriveItem> children() {",
        "        return new ArrayList<>(children.values());",
        "    }",
        "",
        "    public DriveItem findById(String itemId) {",
        "        if (getId().equals(itemId)) {",
        "            return this;",
        "        }",
        "        for (DriveItem child : children.values()) {",
        "            if (child.getId().equals(itemId)) {",
        "                return child;",
        "            }",
        "            if (child instanceof FolderItem) {",
        "                DriveItem match = ((FolderItem) child).findById(itemId);",
        "                if (match != null) {",
        "                    return match;",
        "                }",
        "            }",
        "        }",
        "        return null;",
        "    }",
        "",
        "    @Override",
        "    public long size() {",
        "        long total = 0;",
        "        for (DriveItem child : children.values()) {",
        "            if (!child.isTrashed()) {",
        "                total += child.size();",
        "            }",
        "        }",
        "        return total;",
        "    }",
        "",
        "    @Override",
        "    public String searchText() {",
        "        return getName();",
        "    }",
        "",
        "    @Override",
        "    public String printTree(String indent) {",
        "        StringBuilder builder = new StringBuilder(indent)",
        "            .append(\"+ \")",
        "            .append(getName())",
        "            .append(isTrashed() ? \" [trashed]\" : \"\");",
        "        for (DriveItem child : children.values()) {",
        "            builder.append(System.lineSeparator()).append(child.printTree(indent + \"  \"));",
        "        }",
        "        return builder.toString();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Permission.java",
      language: "java",
      content: [
        "public enum Permission {",
        "    VIEWER,",
        "    COMMENTER,",
        "    EDITOR;",
        "",
        "    public boolean allows(Permission required) {",
        "        return ordinal() >= required.ordinal();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "AccessProxy.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public class AccessProxy {",
        "    public Permission effectivePermission(String userId, DriveItem item) {",
        "        Objects.requireNonNull(userId, \"userId\");",
        "        DriveItem current = Objects.requireNonNull(item, \"item\");",
        "        while (current != null) {",
        "            if (userId.equals(current.getOwnerId())) {",
        "                return Permission.EDITOR;",
        "            }",
        "            Permission direct = current.directPermissionFor(userId);",
        "            if (direct != null) {",
        "                return direct;",
        "            }",
        "            current = current.getParent();",
        "        }",
        "        return null;",
        "    }",
        "",
        "    public boolean canView(String userId, DriveItem item) {",
        "        return has(userId, item, Permission.VIEWER);",
        "    }",
        "",
        "    public boolean canComment(String userId, DriveItem item) {",
        "        return has(userId, item, Permission.COMMENTER);",
        "    }",
        "",
        "    public boolean canEdit(String userId, DriveItem item) {",
        "        return has(userId, item, Permission.EDITOR);",
        "    }",
        "",
        "    public void require(String userId, DriveItem item, Permission required, String action) {",
        "        Permission actual = effectivePermission(userId, item);",
        "        if (actual == null || !actual.allows(required)) {",
        "            throw new SecurityException(userId + \" cannot \" + action + \" \" + item.getPath());",
        "        }",
        "    }",
        "",
        "    public void share(String userId, DriveItem item, String targetUserId, Permission permission) {",
        "        require(userId, item, Permission.EDITOR, \"share\");",
        "        item.grantPermission(targetUserId, permission);",
        "    }",
        "",
        "    private boolean has(String userId, DriveItem item, Permission required) {",
        "        Permission actual = effectivePermission(userId, item);",
        "        return actual != null && actual.allows(required);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "VersionHistory.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "",
        "public class VersionHistory {",
        "    private final List<Version> versions = new ArrayList<>();",
        "",
        "    public String addVersion(String content) {",
        "        String id = \"v\" + (versions.size() + 1);",
        "        versions.add(new Version(id, content == null ? \"\" : content, Instant.now()));",
        "        return id;",
        "    }",
        "",
        "    public String current() {",
        "        if (versions.isEmpty()) {",
        "            return \"\";",
        "        }",
        "        return versions.get(versions.size() - 1).content;",
        "    }",
        "",
        "    public List<String> versionIds() {",
        "        List<String> ids = new ArrayList<>();",
        "        for (Version version : versions) {",
        "            ids.add(version.id + \" @ \" + version.createdAt);",
        "        }",
        "        return ids;",
        "    }",
        "",
        "    public String restore(String versionId) {",
        "        for (Version version : versions) {",
        "            if (version.id.equals(versionId)) {",
        "                return addVersion(version.content);",
        "            }",
        "        }",
        "        throw new IllegalArgumentException(\"Unknown version: \" + versionId);",
        "    }",
        "",
        "    private static class Version {",
        "        private final String id;",
        "        private final String content;",
        "        private final Instant createdAt;",
        "",
        "        private Version(String id, String content, Instant createdAt) {",
        "            this.id = id;",
        "            this.content = content;",
        "            this.createdAt = createdAt;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "DriveService.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Locale;",
        "import java.util.Objects;",
        "",
        "public class DriveService {",
        "    private final FolderItem root;",
        "    private final AccessProxy access = new AccessProxy();",
        "    private final List<DriveObserver> observers = new ArrayList<>();",
        "",
        "    public DriveService(String ownerId) {",
        "        this.root = new FolderItem(\"My Drive\", ownerId);",
        "    }",
        "",
        "    public FolderItem root() {",
        "        return root;",
        "    }",
        "",
        "    public void addObserver(DriveObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public FolderItem createFolder(String userId, String parentId, String name) {",
        "        FolderItem parent = asFolder(findRequired(parentId));",
        "        access.require(userId, parent, Permission.EDITOR, \"create folder in\");",
        "        FolderItem folder = new FolderItem(name, userId);",
        "        parent.addChild(folder);",
        "        notifyObservers(\"folder.created\", folder);",
        "        return folder;",
        "    }",
        "",
        "    public FileItem createFile(String userId, String parentId, String name, String initialContent) {",
        "        FolderItem parent = asFolder(findRequired(parentId));",
        "        access.require(userId, parent, Permission.EDITOR, \"create file in\");",
        "        FileItem file = new FileItem(name, userId, initialContent);",
        "        parent.addChild(file);",
        "        notifyObservers(\"file.created\", file);",
        "        return file;",
        "    }",
        "",
        "    public String readFile(String userId, String fileId) {",
        "        FileItem file = asFile(findRequired(fileId));",
        "        access.require(userId, file, Permission.VIEWER, \"read\");",
        "        return file.read();",
        "    }",
        "",
        "    public void updateFile(String userId, String fileId, String newContent) {",
        "        FileItem file = asFile(findRequired(fileId));",
        "        access.require(userId, file, Permission.EDITOR, \"edit\");",
        "        file.updateContent(newContent);",
        "        notifyObservers(\"file.versioned\", file);",
        "    }",
        "",
        "    public void commentFile(String userId, String fileId, String comment) {",
        "        FileItem file = asFile(findRequired(fileId));",
        "        access.require(userId, file, Permission.COMMENTER, \"comment on\");",
        "        file.addComment(userId, comment);",
        "        notifyObservers(\"file.commented\", file);",
        "    }",
        "",
        "    public void restoreVersion(String userId, String fileId, String versionId) {",
        "        FileItem file = asFile(findRequired(fileId));",
        "        access.require(userId, file, Permission.EDITOR, \"restore\");",
        "        file.restoreVersion(versionId);",
        "        notifyObservers(\"file.restored\", file);",
        "    }",
        "",
        "    public void share(String userId, String itemId, String targetUserId, Permission permission) {",
        "        DriveItem item = findRequired(itemId);",
        "        access.share(userId, item, targetUserId, permission);",
        "        notifyObservers(\"item.shared\", item);",
        "    }",
        "",
        "    public void star(String userId, String itemId) {",
        "        DriveItem item = findRequired(itemId);",
        "        access.require(userId, item, Permission.VIEWER, \"star\");",
        "        item.setStarred(true);",
        "        notifyObservers(\"item.starred\", item);",
        "    }",
        "",
        "    public void trash(String userId, String itemId) {",
        "        DriveItem item = findRequired(itemId);",
        "        access.require(userId, item, Permission.EDITOR, \"trash\");",
        "        item.setTrashed(true);",
        "        notifyObservers(\"item.trashed\", item);",
        "    }",
        "",
        "    public List<DriveItem> search(String userId, String query, SearchStrategy strategy) {",
        "        List<DriveItem> result = new ArrayList<>();",
        "        String normalized = query == null ? \"\" : query.toLowerCase(Locale.ROOT);",
        "        collectSearch(userId, root, normalized, strategy, result);",
        "        return result;",
        "    }",
        "",
        "    public List<DriveItem> starred(String userId) {",
        "        return search(userId, \"\", (item, query) -> item.isStarred());",
        "    }",
        "",
        "    public String visibleTree(String userId) {",
        "        StringBuilder builder = new StringBuilder();",
        "        appendVisible(userId, root, \"\", builder);",
        "        return builder.toString();",
        "    }",
        "",
        "    public static SearchStrategy nameContains() {",
        "        return (item, query) -> item.getName().toLowerCase(Locale.ROOT).contains(query);",
        "    }",
        "",
        "    public static SearchStrategy textContains() {",
        "        return (item, query) -> item.searchText().toLowerCase(Locale.ROOT).contains(query);",
        "    }",
        "",
        "    private void collectSearch(String userId, DriveItem item, String query, SearchStrategy strategy, List<DriveItem> result) {",
        "        if (item.isTrashed()) {",
        "            return;",
        "        }",
        "        boolean visible = access.canView(userId, item);",
        "        if (visible && strategy.matches(item, query)) {",
        "            result.add(item);",
        "        }",
        "        if (item instanceof FolderItem) {",
        "            for (DriveItem child : ((FolderItem) item).children()) {",
        "                collectSearch(userId, child, query, strategy, result);",
        "            }",
        "        }",
        "    }",
        "",
        "    private void appendVisible(String userId, DriveItem item, String indent, StringBuilder builder) {",
        "        if (item.isTrashed()) {",
        "            return;",
        "        }",
        "        boolean visible = access.canView(userId, item);",
        "        String childIndent = indent;",
        "        if (visible) {",
        "            if (builder.length() > 0) {",
        "                builder.append(System.lineSeparator());",
        "            }",
        "            builder.append(indent).append(item.isFolder() ? \"+ \" : \"- \").append(item.getName());",
        "            childIndent = indent + \"  \";",
        "        }",
        "        if (item instanceof FolderItem) {",
        "            for (DriveItem child : ((FolderItem) item).children()) {",
        "                appendVisible(userId, child, childIndent, builder);",
        "            }",
        "        }",
        "    }",
        "",
        "    private DriveItem findRequired(String itemId) {",
        "        DriveItem item = root.findById(itemId);",
        "        if (item == null) {",
        "            throw new IllegalArgumentException(\"Unknown item id: \" + itemId);",
        "        }",
        "        return item;",
        "    }",
        "",
        "    private FolderItem asFolder(DriveItem item) {",
        "        if (!(item instanceof FolderItem)) {",
        "            throw new IllegalArgumentException(\"Not a folder: \" + item.getPath());",
        "        }",
        "        return (FolderItem) item;",
        "    }",
        "",
        "    private FileItem asFile(DriveItem item) {",
        "        if (!(item instanceof FileItem)) {",
        "            throw new IllegalArgumentException(\"Not a file: \" + item.getPath());",
        "        }",
        "        return (FileItem) item;",
        "    }",
        "",
        "    private void notifyObservers(String event, DriveItem item) {",
        "        for (DriveObserver observer : observers) {",
        "            observer.onEvent(event, item);",
        "        }",
        "    }",
        "",
        "    public interface SearchStrategy {",
        "        boolean matches(DriveItem item, String query);",
        "    }",
        "",
        "    public interface DriveObserver {",
        "        void onEvent(String event, DriveItem item);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        DriveService drive = new DriveService(\"alice\");",
        "        drive.addObserver((event, item) -> System.out.println(event + \" -> \" + item.getPath()));",
        "",
        "        FolderItem specs = drive.createFolder(\"alice\", drive.root().getId(), \"Specs\");",
        "        FileItem doc = drive.createFile(\"alice\", specs.getId(), \"api-design.txt\", \"first draft\");",
        "",
        "        drive.share(\"alice\", specs.getId(), \"bob\", Permission.COMMENTER);",
        "        System.out.println(drive.readFile(\"bob\", doc.getId()));",
        "        drive.commentFile(\"bob\", doc.getId(), \"Looks good, please add Drive permissions\");",
        "",
        "        try {",
        "            drive.updateFile(\"bob\", doc.getId(), \"unauthorized edit\");",
        "        } catch (SecurityException ex) {",
        "            System.out.println(ex.getMessage());",
        "        }",
        "",
        "        drive.share(\"alice\", doc.getId(), \"bob\", Permission.EDITOR);",
        "        drive.updateFile(\"bob\", doc.getId(), \"second draft with Drive permissions\");",
        "        drive.star(\"bob\", doc.getId());",
        "",
        "        System.out.println(drive.search(\"bob\", \"permissions\", DriveService.textContains()).size());",
        "        System.out.println(drive.visibleTree(\"bob\"));",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "DriveItem",
      detailMD:
        "The abstract Component. It owns shared identity, owner, parent, starred/trash flags, direct ACL map, path calculation, and the common polymorphic methods that files and folders implement.",
    },
    {
      className: "FileItem",
      detailMD:
        "The leaf node. It delegates content snapshots to **VersionHistory**, stores comments, exposes read/update/restore operations, reports size from current content, and contributes content plus comments to search text.",
    },
    {
      className: "FolderItem",
      detailMD:
        "The Composite node. It owns a deterministic child map, rejects duplicate names, wires parent links, finds descendants recursively by id, and aggregates visible descendant size.",
    },
    {
      className: "Permission",
      detailMD:
        "The ordered permission ladder. **EDITOR** allows edit, comment, and view; **COMMENTER** allows comment and view; **VIEWER** allows only read/search visibility.",
    },
    {
      className: "AccessProxy",
      detailMD:
        "The authorization Proxy and most important class in the design. It resolves owner, direct permission, and inherited folder permission before approving or rejecting each action.",
    },
    {
      className: "VersionHistory",
      detailMD:
        "Append-only file version log. Each write adds a version id with content and timestamp; restoring an older version appends a fresh current version rather than mutating history.",
    },
    {
      className: "DriveService",
      detailMD:
        "The application facade. It resolves ids, asks **AccessProxy** before every public operation, updates files/folders only after authorization, runs **SearchStrategy**, and publishes **DriveObserver** events.",
    },
    {
      className: "Main",
      detailMD:
        "A compact demo that creates a folder and file, shares a folder as commenter, shows a denied edit, upgrades a file to editor access, versions it, stars it, and searches visible content.",
    },
  ],

  dryRun: {
    inputMD:
      "Alice owns **My Drive**. Actions: create **Specs/api-design.txt**, share **Specs** with Bob as **COMMENTER**, Bob reads and comments, Bob tries to edit, Alice shares the file with Bob as **EDITOR**, Bob edits, stars, and searches for **permissions**.",
    columns: ["Step", "Operation", "Proxy decision", "State change", "Result"],
    rows: [
      ["1", "Alice creates Specs folder", "Alice is root owner so EDITOR", "Folder added under My Drive", "Specs id returned"],
      ["2", "Alice creates api-design.txt", "Alice is Specs owner so EDITOR", "File leaf added with version v1", "File id returned"],
      ["3", "Alice shares Specs with Bob COMMENTER", "Alice has EDITOR on Specs", "ACL on Specs grants Bob COMMENTER", "Inherited access begins"],
      ["4", "Bob reads file", "File has no direct ACL, parent Specs grants COMMENTER", "No mutation", "Read succeeds"],
      ["5", "Bob comments", "COMMENTER satisfies comment requirement", "Comment appended", "Observer event emitted"],
      ["6", "Bob edits", "COMMENTER does not satisfy EDITOR", "No content change", "SecurityException"],
      ["7", "Alice shares file with Bob EDITOR", "Alice has EDITOR", "Direct file ACL grants Bob EDITOR", "Direct permission overrides need for folder edit"],
      ["8", "Bob edits and searches", "EDITOR satisfies edit; VIEWER satisfies search", "Version v2 added, item starred", "Search returns visible file"],
    ],
    narrativeMD:
      "The key transition is Step 6 to Step 7. Bob can read and comment through inherited folder access, but the Proxy blocks editing until the file receives direct **EDITOR** permission.",
  },

  complexity: [
    {
      operation: "create file or folder",
      time: "O(N)",
      space: "O(1)",
      note: "The service resolves the parent by recursive id lookup over N items, then inserts one child.",
    },
    {
      operation: "permission check",
      time: "O(H)",
      space: "O(1)",
      note: "The Proxy walks from target to root over height H until it finds owner or direct permission.",
    },
    {
      operation: "read or comment",
      time: "O(H)",
      space: "O(1)",
      note: "Authorization dominates; reading current content and appending a comment are constant in this model.",
    },
    {
      operation: "update file / restore version",
      time: "O(H + V)",
      space: "O(C)",
      note: "Update is O(H) plus storing content C. Restore scans V versions to find the requested id.",
    },
    {
      operation: "search",
      time: "O(N × H + M)",
      space: "O(R)",
      note: "For each non-trashed item, check visibility through ancestors and run strategy match cost M; keep R results.",
    },
    {
      operation: "subtree size",
      time: "O(S)",
      space: "O(D)",
      note: "Folder size recursively visits S descendants with recursion depth D.",
    },
  ],
  complexityNotesMD:
    "The intentionally simple id lookup and permission walk keep the design interview-readable. Production systems add id indexes, cached effective ACLs, and search indexes, but the same Proxy boundary remains mandatory.",

  extensibility: [
    {
      label: "Richer ACL model",
      detailMD:
        "Replace the direct permission map with ACL entries containing inherited flags, link sharing, expiration, group ids, and domain policies. **AccessProxy** remains the only caller-facing decision point.",
    },
    {
      label: "Search indexing",
      detailMD:
        "Add an observer that updates an inverted index when files are created, versioned, commented, trashed, or restored. **DriveService.search** can then delegate to the index after applying authorization filters.",
    },
    {
      label: "Per-user starred state",
      detailMD:
        "Move starred from **DriveItem** to a **UserItemMetadata** record keyed by user id and item id. The service API does not change; only metadata storage changes.",
    },
    {
      label: "Move and copy",
      detailMD:
        "Add **moveItem** requiring editor permission on source and destination parent. Guard against moving a folder into its own descendant and recompute inherited access through the Proxy.",
    },
    {
      label: "Permanent delete and retention",
      detailMD:
        "Trash can become a state machine: active, trashed, retained, purged. The Proxy still controls who can transition states.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Permission checks inside every domain object",
      detailMD:
        "Each **FileItem** and **FolderItem** method could accept a user id and check ACLs before doing work.",
      tradeoffsMD:
        "This spreads authorization across many classes and makes inherited folder rules easy to implement inconsistently. It is weaker than a dedicated Proxy for this interview.",
    },
    {
      name: "Flat item table instead of Composite",
      detailMD:
        "Store every item in a map by id with a parent id field and perform tree operations through queries rather than object ownership.",
      tradeoffsMD:
        "Closer to production persistence and faster id lookup, but it hides the Composite pattern and makes an LLD whiteboard less expressive. A repository can add this later behind the same objects.",
    },
    {
      name: "Precomputed effective permissions",
      detailMD:
        "Materialize each user item effective permission when a folder is shared so reads are O(1).",
      tradeoffsMD:
        "Fast checks, but sharing a high-level folder becomes expensive and revocation is risky. The lazy Proxy walk is safer for the base design.",
    },
  ],

  commonMistakes: [
    "Focusing only on the file/folder Composite and forgetting that permissions are the harder requirement.",
    "Checking permissions in UI/controller code and then letting services mutate items directly.",
    "Treating folder shares and file shares as unrelated, so inherited access gives different answers in read, comment, and search.",
    "Letting search return private item names before authorization filtering.",
    "Making **COMMENTER** a boolean flag instead of part of an ordered permission ladder.",
    "Overwriting old content during edit and losing version history.",
    "Modeling trash as physical deletion, which prevents restore, audit, and retention policies.",
  ],

  followUps: [
    {
      question: "How would you support link sharing?",
      answerMD:
        "Add a link token ACL entry with permission, expiration, and audience. **AccessProxy** first authenticates the token, then folds it into effective permission resolution without changing file or folder classes.",
    },
    {
      question: "How do you make permission checks faster?",
      answerMD:
        "Keep the Proxy API but cache effective permission by user and item with invalidation on share, revoke, move, and trash. For large folders, use async materialization and versioned ACL epochs.",
    },
    {
      question: "What happens when a folder is shared as viewer but a child file is shared as editor?",
      answerMD:
        "The base Proxy checks the target item first, so the child direct **EDITOR** permission wins for that child. Siblings still inherit only viewer from the folder.",
    },
    {
      question: "How would you prevent search from leaking private file names?",
      answerMD:
        "Always filter by **AccessProxy.canView** before applying a search strategy or returning any metadata. In production, the search index stores item ids and the serving layer joins with ACL filters.",
    },
    {
      question: "How would move affect inherited permissions?",
      answerMD:
        "Move changes the ancestor chain, so effective access may change. Require editor access on both source and destination, perform the move atomically, and invalidate cached permissions for the moved subtree.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence and repositories",
      detailMD:
        "Store items, parent links, ACLs, versions, and user metadata in repositories. Keep domain methods clean and make **DriveService** the transaction boundary.",
    },
    {
      label: "Authorization cache invalidation",
      detailMD:
        "Effective ACL caches must invalidate on share, revoke, ownership transfer, move, group membership change, and policy update. Incorrect stale allows are security incidents.",
    },
    {
      label: "Search infrastructure",
      detailMD:
        "Use observers or an event log to update an inverted index asynchronously. Query results must still be ACL-filtered at serving time.",
    },
    {
      label: "Version storage",
      detailMD:
        "Store content as blobs or deltas rather than full Java strings. Track checksums, creator, created time, and retention policy per version.",
    },
    {
      label: "Audit and compliance",
      detailMD:
        "Emit immutable audit events for share, revoke, download, edit, restore, trash, and purge. Enterprise Drive products need traceability for compliance reviews.",
    },
  ],

  interviewNotes: [
    "Did the candidate explicitly make **AccessProxy** the central permission gate rather than an afterthought?",
    "Can they explain direct permission, inherited folder permission, owner access, and override precedence clearly?",
    "Is the Composite tree clean without forcing file behavior into folders or folder behavior into files?",
    "Does search run after visibility filtering so it cannot leak private metadata?",
    "Are versioning, starred state, trash, and observers modeled as extensions around the core authorization boundary?",
  ],

  quiz: [
    {
      question: "Why is **AccessProxy** more important than the Composite tree in this Google Drive design?",
      options: [
        "Because authorization must be correct for every read and mutation",
        "Because folders cannot contain files without a proxy",
        "Because Java enums require a proxy class",
        "Because search cannot traverse trees",
      ],
      answerIndex: 0,
      explanationMD:
        "The tree is straightforward; the risky part is consistently enforcing viewer/commenter/editor access including inherited folder permissions.",
    },
    {
      question: "What permission does **COMMENTER** include in this design?",
      options: [
        "Comment only, but not view",
        "View and comment, but not edit",
        "Edit and share, but not comment",
        "Trash and restore only",
      ],
      answerIndex: 1,
      explanationMD:
        "Permissions are ordered: **COMMENTER** is above **VIEWER** and below **EDITOR**.",
    },
    {
      question: "A folder is shared with Bob as **VIEWER**, and a child file is shared with Bob as **EDITOR**. What should the Proxy return for that child file?",
      options: [
        "No access because inherited permissions always win",
        "VIEWER because folder permissions cannot be overridden",
        "EDITOR because the nearest direct permission on the target is checked first",
        "COMMENTER because it averages viewer and editor",
      ],
      answerIndex: 2,
      explanationMD:
        "The implementation checks the target item before walking to ancestors, so a direct child permission can be more specific than the inherited folder permission.",
    },
    {
      question: "Why should search filter with **AccessProxy.canView** before returning matches?",
      options: [
        "To avoid leaking private item names or content snippets",
        "To make string matching case-sensitive",
        "To skip version history creation",
        "To allow commenters to edit files",
      ],
      answerIndex: 0,
      explanationMD:
        "Search results themselves reveal metadata. Authorization must happen before names, snippets, or ids are exposed.",
    },
    {
      question: "What pattern does **SearchStrategy** apply?",
      options: [
        "Composite",
        "Strategy",
        "Proxy",
        "Object Pool",
      ],
      answerIndex: 1,
      explanationMD:
        "The traversal stays fixed while the matching algorithm varies by strategy.",
    },
  ],

  practiceVariants: [
    {
      title: "Add revoke and ownership transfer",
      detailMD:
        "Implement **revokePermission** through **DriveService** and add **transferOwnership**. Define how inherited access and direct ACLs behave after ownership changes.",
      difficulty: "Advanced",
    },
    {
      title: "Add link sharing with expiry",
      detailMD:
        "Create share links with permission, expiration time, and optional domain restriction. Keep token validation inside **AccessProxy**.",
      difficulty: "Expert",
    },
    {
      title: "Index search with observers",
      detailMD:
        "Attach an observer that updates an in-memory inverted index on file creation, versioning, comment, trash, and restore events. Preserve authorization filtering on query.",
      difficulty: "Advanced",
    },
    {
      title: "Support move and inherited ACL recalculation",
      detailMD:
        "Add **moveItem** and decide how to invalidate cached permissions when an item moves between folders with different shares.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "What is the central class for permission enforcement?",
      back: "**AccessProxy**. It resolves owner, direct ACL, and inherited ancestor ACL before each operation.",
    },
    {
      front: "How are files and folders modeled?",
      back: "As a Composite: **DriveItem** is the component, **FileItem** is the leaf, and **FolderItem** owns child **DriveItem** objects.",
    },
    {
      front: "What is the permission ladder?",
      back: "**VIEWER** allows read/search, **COMMENTER** allows view plus comment, and **EDITOR** allows edit/share/trash plus lower permissions.",
    },
    {
      front: "How does inherited folder permission work?",
      back: "The Proxy checks the target item first, then walks parent folders until it finds a direct permission or owner match.",
    },
    {
      front: "Why use Strategy for search?",
      back: "Traversal and ACL filtering stay fixed while matching changes by name, content, metadata, owner, or ranking policy.",
    },
    {
      front: "Why restore a version by appending a new version?",
      back: "It preserves audit history. The old snapshot becomes the new current content without deleting intermediate versions.",
    },
  ],

  cheatSheetMD: [
    "**Core objects:** DriveService, AccessProxy, DriveItem, FileItem, FolderItem, Permission, VersionHistory.",
    "",
    "**Patterns:** Composite for file/folder tree, Proxy for authorization, Strategy for search matching, Observer for activity and indexing events.",
    "",
    "**Permission rule:** owner is effective editor; direct item ACL is checked before ancestor ACL; **EDITOR** includes commenter and viewer, **COMMENTER** includes viewer.",
    "",
    "**Main flows:** create = require editor on parent then add child; read = require viewer then return content; comment = require commenter then append comment; edit = require editor then add version; share = require editor then add ACL.",
    "",
    "**Search rule:** traverse visible tree, ignore trashed items, call **AccessProxy.canView** before applying **SearchStrategy**.",
    "",
    "**Versioning:** every edit appends a version; restore appends an old snapshot as a new latest version.",
    "",
    "**Production upgrades:** repositories, ACL caches, group permissions, link sharing, per-user starred metadata, search index, audit log, retention policy.",
  ].join("\n"),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, Vlissides",
    },
    {
      title: "Refactoring Guru — Proxy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/proxy",
    },
    {
      title: "Refactoring Guru — Composite Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/composite",
    },
    {
      title: "Google Drive API — Files and Permissions",
      kind: "Docs",
      url: "https://developers.google.com/drive/api/guides/about-files",
    },
  ],

  relatedProblems: [
    { slug: "dropbox", note: "Adjacent storage problem focused more on sync, chunking, and version propagation." },
    { slug: "file-system", note: "Simpler Composite tree without sharing and authorization complexity." },
    { slug: "rbac-system", note: "Deepens the permission model behind users, roles, and allowed actions." },
  ],
};
