import type { LLDProblemContent } from "../types";

/**
 * Exemplar LLD problem — Design Google Docs.
 *
 * Fresh Java implementation focused on edit commands, version mementos,
 * observer updates, collaborator cursors, and conceptual OT-style transforms.
 */
export const googleDocs: LLDProblemContent = {
  slug: "google-docs",

  statementMD: [
    "Design the object model for a **Google Docs-like collaborative editor** where multiple collaborators can edit the same document at the same time.",
    "",
    "The LLD focus is the editing core: documents hold text and versions, insert/delete edits are modelled as **Command** objects, concurrent commands are reconciled through a pluggable conflict-resolution strategy, collaborator cursors are tracked as presence state, immutable **Memento** snapshots power version history, and observers push accepted changes to connected clients.",
  ].join("\n"),

  businessContextMD: [
    "Collaborative editors sit behind products such as Google Docs, Office Online, Notion, and Figma-like whiteboards. The visible product feels simple, but the object model has to protect a difficult invariant: every participant must converge on the same document even when edits arrive out of order.",
    "",
    "Interviewers use this problem to test whether you can separate local edit intent from accepted document state. A strong answer makes edits explicit commands, records versioned snapshots, talks about operational transform or CRDTs at the object level, and keeps network delivery, UI rendering, and persistence outside the core model.",
  ].join("\n"),

  functionalRequirements: [
    "Maintain a document id, current text, and monotonically increasing version number.",
    "Accept insert and delete operations from collaborators as command objects carrying author id, base version, position, and payload.",
    "Transform operations submitted against older versions so concurrent edits are reconciled before being applied.",
    "Persist immutable document-version snapshots after accepted edit operations for version history and restore.",
    "Track collaborator cursor positions separately from document versions as presence state.",
    "Notify subscribed observers after accepted edits and cursor moves so clients can refresh without polling.",
    "Expose read-only document text, current version, history, and collaborator cursors to application services.",
    "Reject invalid operations such as negative positions, blank collaborator ids, or edits based on versions newer than the document.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Convergence under concurrent editing",
      detailMD:
        "All accepted operations must be applied in a single total order, and operations based on older versions must be transformed against the committed operations they missed.",
    },
    {
      label: "Interactive latency",
      detailMD:
        "Submitting an edit should be fast enough for keystrokes. The interview design uses a simple buffer and a short history scan; production can swap in a rope, piece table, or indexed operation log.",
    },
    {
      label: "Version traceability",
      detailMD:
        "Every accepted edit creates an immutable **DocumentVersion** snapshot with author, operation type, position, payload, and full content so debugging and restore are straightforward.",
    },
    {
      label: "Extensible conflict policy",
      detailMD:
        "Operational transform is represented behind **ConflictResolutionStrategy**. A CRDT policy, server-authoritative policy, or domain-specific merge can replace it without changing commands.",
    },
    {
      label: "Safe observer boundaries",
      detailMD:
        "Observers receive immutable change events and cursor maps, not mutable document internals. UI, WebSocket, autosave, and metrics subscribers stay decoupled from the core document object.",
    },
  ],

  requirementClarification: [
    {
      question: "Are we implementing full Google Docs with comments, formatting, sharing, and permissions?",
      answerMD:
        "No. Scope the base design to a plain-text collaborative editing core. Rich formatting, comments, ACLs, and file storage are extensions layered around the same edit/version model.",
    },
    {
      question: "Should conflict resolution be OT or CRDT?",
      answerMD:
        "Use an operational-transform style strategy for the LLD implementation because it is easy to show with base versions and position shifts. The strategy interface is the seam where a CRDT algorithm could be substituted.",
    },
    {
      question: "Do cursor moves create document versions?",
      answerMD:
        "No. Cursor moves are presence events. They update the collaborator cursor map and notify observers, but they do not change document text or create **DocumentVersion** snapshots.",
    },
    {
      question: "Do version snapshots store full text or deltas?",
      answerMD:
        "Full-text snapshots are acceptable for the interview because they make **Memento** clear. Production systems usually combine operation logs, periodic checkpoints, compression, and retention policies.",
    },
    {
      question: "What happens if an operation arrives with a stale base version?",
      answerMD:
        "The service asks the conflict strategy to transform the operation through all committed versions after that base. The transformed command is then applied to the current document version.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class CollaborationService {",
    "        -Document document",
    "        -ConflictResolutionStrategy conflictStrategy",
    "        -Map~String,Integer~ collaboratorCursors",
    "        -List~DocumentObserver~ observers",
    "        +submit(Operation) DocumentVersion",
    "        +moveCursor(String,int) void",
    "        +subscribe(DocumentObserver) void",
    "        +history() List~DocumentVersion~",
    "    }",
    "    class Document {",
    "        -String id",
    "        -StringBuilder content",
    "        -int version",
    "        -List~DocumentVersion~ history",
    "        +apply(Operation) DocumentVersion",
    "        +insert(int,String) void",
    "        +delete(int,int) String",
    "        +save(String,String,int,String,int) DocumentVersion",
    "        +restore(DocumentVersion) void",
    "    }",
    "    class Operation {",
    "        <<interface>>",
    "        +authorId() String",
    "        +baseVersion() int",
    "        +position() int",
    "        +execute(Document) DocumentVersion",
    "        +withPosition(int) Operation",
    "    }",
    "    class InsertOperation {",
    "        -String authorId",
    "        -int baseVersion",
    "        -int position",
    "        -String text",
    "    }",
    "    class DeleteOperation {",
    "        -String authorId",
    "        -int baseVersion",
    "        -int position",
    "        -int length",
    "    }",
    "    class DocumentVersion {",
    "        -int version",
    "        -String content",
    "        -String authorId",
    "        -String operationType",
    "        -Instant createdAt",
    "    }",
    "    class ConflictResolutionStrategy {",
    "        <<interface>>",
    "        +transform(Operation,Document) Operation",
    "    }",
    "    class DocumentObserver {",
    "        <<interface>>",
    "        +onChange(ChangeEvent) void",
    "    }",
    "    class ChangeEvent {",
    "        -String documentId",
    "        -int version",
    "        -String text",
    "        -Map~String,Integer~ cursors",
    "    }",
    "    CollaborationService o-- Document",
    "    CollaborationService ..> ConflictResolutionStrategy",
    "    CollaborationService o-- DocumentObserver",
    "    CollaborationService --> ChangeEvent",
    "    Document o-- DocumentVersion",
    "    Document ..> Operation",
    "    Operation <|.. InsertOperation",
    "    Operation <|.. DeleteOperation",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service coordinates collaboration, but the text invariant stays inside **Document**. Commands express edit intent, **DocumentVersion** stores snapshots, the strategy resolves concurrency, and observers receive immutable events.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Alice",
    "    actor Bob",
    "    participant Service as CollaborationService",
    "    participant Strategy as ConflictResolutionStrategy",
    "    participant Doc as Document",
    "    participant Observer as DocumentObserver",
    "    Alice->>Service: submit Insert base v10",
    "    Service->>Strategy: transform(insert, doc v10)",
    "    Strategy-->>Service: same operation",
    "    Service->>Doc: apply(insert)",
    "    Doc-->>Service: DocumentVersion v11",
    "    Service-->>Observer: onChange(v11)",
    "    Bob->>Service: submit Delete base v10",
    "    Service->>Strategy: transform(delete, doc v11)",
    "    Strategy-->>Service: shifted delete",
    "    Service->>Doc: apply(transformed delete)",
    "    Doc-->>Service: DocumentVersion v12",
    "    Service-->>Observer: onChange(v12)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Bob edited an older version, so the delete command is transformed through Alice's committed insert before the document accepts it.",

  entities: [
    {
      name: "Document",
      responsibilityMD:
        "Aggregate root for one editable document. Owns text, current version, edit validation, snapshot creation, restore, and history queries.",
      attributes: ["id", "content", "version", "history"],
    },
    {
      name: "Operation",
      responsibilityMD:
        "Command interface for all edits. It carries the author's base version and knows how to execute itself against a **Document** after transformation.",
      attributes: ["authorId", "baseVersion", "position", "execute(document)"],
    },
    {
      name: "InsertOperation",
      responsibilityMD:
        "Concrete command for inserting text at a position. Transformation may shift its position before execution.",
      attributes: ["authorId", "baseVersion", "position", "text"],
    },
    {
      name: "DeleteOperation",
      responsibilityMD:
        "Concrete command for deleting a range from a position. The accepted snapshot records the actual text removed.",
      attributes: ["authorId", "baseVersion", "position", "length"],
    },
    {
      name: "DocumentVersion",
      responsibilityMD:
        "Memento of document state after an accepted edit. Stores full content plus metadata needed for history, restore, and later transforms.",
      attributes: ["version", "content", "authorId", "operationType", "position", "affectedLength"],
    },
    {
      name: "ConflictResolutionStrategy",
      responsibilityMD:
        "Policy seam for reconciling stale operations. The sample implementation performs a simple OT-style position transform across committed versions.",
      attributes: ["transform(operation, document)"],
    },
    {
      name: "CollaborationService",
      responsibilityMD:
        "Application-facing coordinator. Validates base versions, transforms commands, applies them atomically, updates cursors, and pushes events to observers.",
      attributes: ["document", "conflictStrategy", "collaboratorCursors", "observers"],
    },
    {
      name: "DocumentObserver / ChangeEvent",
      responsibilityMD:
        "Observer boundary for connected clients or infrastructure subscribers. Each event carries immutable text, version, operation type, and cursor state.",
      attributes: ["documentId", "version", "text", "cursors"],
    },
  ],

  patternsUsed: [
    {
      name: "Command",
      whyMD:
        "**Operation** turns every edit into an object with author, base version, position, payload, and **execute** behavior. This lets the service queue, transform, audit, and replay edits uniformly.",
    },
    {
      name: "Memento",
      whyMD:
        "**DocumentVersion** captures immutable snapshots of document state after accepted edits. The document can restore a version without exposing mutable internals.",
    },
    {
      name: "Observer",
      whyMD:
        "**DocumentObserver** subscribers are notified after edits and cursor moves. UI sessions, WebSocket gateways, autosave, and metrics can react without being hard-wired into the document.",
    },
    {
      name: "Strategy",
      whyMD:
        "**ConflictResolutionStrategy** isolates how stale operations are reconciled. The sample uses OT-style position shifting, while a CRDT or server-specific algorithm can be injected later.",
    },
  ],

  designSteps: [
    {
      title: "Separate document state from collaboration orchestration",
      detailMD:
        "The **Document** owns text and version invariants. The collaboration service owns sessions, cursors, observers, and the transform-and-apply workflow.",
      code: [
        "public synchronized DocumentVersion apply(Operation operation) {",
        "    return operation.execute(this);",
        "}",
        "",
        "public synchronized DocumentVersion save(String authorId, String operationType, int position, String payload, int affectedLength) {",
        "    version++;",
        "    DocumentVersion snapshot = new DocumentVersion(version, content.toString(), authorId, operationType, position, payload, affectedLength);",
        "    history.add(snapshot);",
        "    return snapshot;",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent insert and delete as commands",
      detailMD:
        "Each edit carries the user's intent and base version. The service can transform the command before execution without knowing whether it inserts or deletes.",
      code: [
        "public interface Operation {",
        "    String authorId();",
        "    int baseVersion();",
        "    int position();",
        "    Operation withPosition(int position);",
        "    DocumentVersion execute(Document document);",
        "}",
      ].join("\n"),
    },
    {
      title: "Record accepted versions as mementos",
      detailMD:
        "After a command mutates the document, **save** captures full text plus operation metadata. This snapshot supports history display, restore, and future transform decisions.",
    },
    {
      title: "Transform stale commands before applying them",
      detailMD:
        "If an operation was based on version 10 but the document is at version 12, transform it through versions 11 and 12. Inserts before the command shift it right; deletes before it shift it left.",
      code: [
        "for (DocumentVersion change : document.historySince(incoming.baseVersion())) {",
        "    if (change.isInsert() && transformed.position() > change.position()) {",
        "        transformed = transformed.withPosition(transformed.position() + change.affectedLength());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Track collaborator cursors as presence, not document history",
      detailMD:
        "Cursor moves are real-time collaboration state. They should be broadcast to observers, but they must not increment the document version or pollute version history.",
    },
    {
      title: "Push immutable change events to observers",
      detailMD:
        "The service publishes **ChangeEvent** objects after accepted edits and cursor moves. Subscribers get version, text, operation type, author, and a defensive cursor snapshot.",
    },
  ],

  implementation: [
    {
      filename: "Document.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public class Document {",
        "    private final String id;",
        "    private final StringBuilder content;",
        "    private int version;",
        "    private final List<DocumentVersion> history = new ArrayList<>();",
        "",
        "    public Document(String id, String initialText) {",
        "        this.id = requireText(id, \"id\");",
        "        this.content = new StringBuilder(Objects.requireNonNull(initialText, \"initialText\"));",
        "    }",
        "",
        "    public synchronized String id() {",
        "        return id;",
        "    }",
        "",
        "    public synchronized int version() {",
        "        return version;",
        "    }",
        "",
        "    public synchronized int length() {",
        "        return content.length();",
        "    }",
        "",
        "    public synchronized String text() {",
        "        return content.toString();",
        "    }",
        "",
        "    public synchronized void insert(int position, String text) {",
        "        Objects.requireNonNull(text, \"text\");",
        "        validatePosition(position);",
        "        if (!text.isEmpty()) {",
        "            content.insert(position, text);",
        "        }",
        "    }",
        "",
        "    public synchronized String delete(int position, int length) {",
        "        validatePosition(position);",
        "        if (length < 0) {",
        "            throw new IllegalArgumentException(\"length must not be negative\");",
        "        }",
        "        int end = Math.min(position + length, content.length());",
        "        String removed = content.substring(position, end);",
        "        content.delete(position, end);",
        "        return removed;",
        "    }",
        "",
        "    public synchronized DocumentVersion apply(Operation operation) {",
        "        return Objects.requireNonNull(operation, \"operation\").execute(this);",
        "    }",
        "",
        "    public synchronized DocumentVersion save(String authorId, String operationType, int position, String payload, int affectedLength) {",
        "        version++;",
        "        DocumentVersion snapshot = new DocumentVersion(version, content.toString(), authorId, operationType, position, payload, affectedLength);",
        "        history.add(snapshot);",
        "        return snapshot;",
        "    }",
        "",
        "    public synchronized void restore(DocumentVersion snapshot) {",
        "        Objects.requireNonNull(snapshot, \"snapshot\");",
        "        content.setLength(0);",
        "        content.append(snapshot.content());",
        "        version = snapshot.version();",
        "        history.removeIf(existing -> existing.version() > version);",
        "    }",
        "",
        "    public synchronized List<DocumentVersion> history() {",
        "        return Collections.unmodifiableList(new ArrayList<>(history));",
        "    }",
        "",
        "    public synchronized List<DocumentVersion> historySince(int baseVersion) {",
        "        List<DocumentVersion> result = new ArrayList<>();",
        "        for (DocumentVersion snapshot : history) {",
        "            if (snapshot.version() > baseVersion) {",
        "                result.add(snapshot);",
        "            }",
        "        }",
        "        return Collections.unmodifiableList(result);",
        "    }",
        "",
        "    private void validatePosition(int position) {",
        "        if (position < 0 || position > content.length()) {",
        "            throw new IllegalArgumentException(\"position out of bounds\");",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        String normalized = Objects.requireNonNull(value, fieldName).trim();",
        "        if (normalized.isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" must not be blank\");",
        "        }",
        "        return normalized;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Operation.java",
      language: "java",
      content: [
        "public interface Operation {",
        "    String authorId();",
        "    int baseVersion();",
        "    int position();",
        "    int length();",
        "    String text();",
        "    Operation withPosition(int position);",
        "    int cursorAfter(DocumentVersion version);",
        "    DocumentVersion execute(Document document);",
        "}",
      ].join("\n"),
    },
    {
      filename: "InsertOperation.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class InsertOperation implements Operation {",
        "    private final String authorId;",
        "    private final int baseVersion;",
        "    private final int position;",
        "    private final String text;",
        "",
        "    public InsertOperation(String authorId, int baseVersion, int position, String text) {",
        "        this.authorId = requireText(authorId, \"authorId\");",
        "        if (baseVersion < 0) {",
        "            throw new IllegalArgumentException(\"baseVersion must not be negative\");",
        "        }",
        "        if (position < 0) {",
        "            throw new IllegalArgumentException(\"position must not be negative\");",
        "        }",
        "        this.baseVersion = baseVersion;",
        "        this.position = position;",
        "        this.text = Objects.requireNonNull(text, \"text\");",
        "    }",
        "",
        "    @Override",
        "    public String authorId() {",
        "        return authorId;",
        "    }",
        "",
        "    @Override",
        "    public int baseVersion() {",
        "        return baseVersion;",
        "    }",
        "",
        "    @Override",
        "    public int position() {",
        "        return position;",
        "    }",
        "",
        "    @Override",
        "    public int length() {",
        "        return text.length();",
        "    }",
        "",
        "    @Override",
        "    public String text() {",
        "        return text;",
        "    }",
        "",
        "    @Override",
        "    public Operation withPosition(int newPosition) {",
        "        return new InsertOperation(authorId, baseVersion, newPosition, text);",
        "    }",
        "",
        "    @Override",
        "    public int cursorAfter(DocumentVersion version) {",
        "        return position + text.length();",
        "    }",
        "",
        "    @Override",
        "    public DocumentVersion execute(Document document) {",
        "        document.insert(position, text);",
        "        return document.save(authorId, \"insert\", position, text, text.length());",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        String normalized = Objects.requireNonNull(value, fieldName).trim();",
        "        if (normalized.isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" must not be blank\");",
        "        }",
        "        return normalized;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "DeleteOperation.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class DeleteOperation implements Operation {",
        "    private final String authorId;",
        "    private final int baseVersion;",
        "    private final int position;",
        "    private final int length;",
        "",
        "    public DeleteOperation(String authorId, int baseVersion, int position, int length) {",
        "        this.authorId = requireText(authorId, \"authorId\");",
        "        if (baseVersion < 0) {",
        "            throw new IllegalArgumentException(\"baseVersion must not be negative\");",
        "        }",
        "        if (position < 0) {",
        "            throw new IllegalArgumentException(\"position must not be negative\");",
        "        }",
        "        if (length < 0) {",
        "            throw new IllegalArgumentException(\"length must not be negative\");",
        "        }",
        "        this.baseVersion = baseVersion;",
        "        this.position = position;",
        "        this.length = length;",
        "    }",
        "",
        "    @Override",
        "    public String authorId() {",
        "        return authorId;",
        "    }",
        "",
        "    @Override",
        "    public int baseVersion() {",
        "        return baseVersion;",
        "    }",
        "",
        "    @Override",
        "    public int position() {",
        "        return position;",
        "    }",
        "",
        "    @Override",
        "    public int length() {",
        "        return length;",
        "    }",
        "",
        "    @Override",
        "    public String text() {",
        "        return \"\";",
        "    }",
        "",
        "    @Override",
        "    public Operation withPosition(int newPosition) {",
        "        return new DeleteOperation(authorId, baseVersion, newPosition, length);",
        "    }",
        "",
        "    @Override",
        "    public int cursorAfter(DocumentVersion version) {",
        "        return position;",
        "    }",
        "",
        "    @Override",
        "    public DocumentVersion execute(Document document) {",
        "        String removed = document.delete(position, length);",
        "        return document.save(authorId, \"delete\", position, removed, removed.length());",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        String normalized = Objects.requireNonNull(value, fieldName).trim();",
        "        if (normalized.isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" must not be blank\");",
        "        }",
        "        return normalized;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "DocumentVersion.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.Objects;",
        "",
        "public final class DocumentVersion {",
        "    private final int version;",
        "    private final String content;",
        "    private final String authorId;",
        "    private final String operationType;",
        "    private final int position;",
        "    private final String payload;",
        "    private final int affectedLength;",
        "    private final Instant createdAt;",
        "",
        "    public DocumentVersion(int version, String content, String authorId, String operationType, int position, String payload, int affectedLength) {",
        "        if (version < 0) {",
        "            throw new IllegalArgumentException(\"version must not be negative\");",
        "        }",
        "        if (position < 0) {",
        "            throw new IllegalArgumentException(\"position must not be negative\");",
        "        }",
        "        if (affectedLength < 0) {",
        "            throw new IllegalArgumentException(\"affectedLength must not be negative\");",
        "        }",
        "        this.version = version;",
        "        this.content = Objects.requireNonNull(content, \"content\");",
        "        this.authorId = requireText(authorId, \"authorId\");",
        "        this.operationType = requireText(operationType, \"operationType\");",
        "        this.position = position;",
        "        this.payload = Objects.requireNonNull(payload, \"payload\");",
        "        this.affectedLength = affectedLength;",
        "        this.createdAt = Instant.now();",
        "    }",
        "",
        "    public int version() {",
        "        return version;",
        "    }",
        "",
        "    public String content() {",
        "        return content;",
        "    }",
        "",
        "    public String authorId() {",
        "        return authorId;",
        "    }",
        "",
        "    public String operationType() {",
        "        return operationType;",
        "    }",
        "",
        "    public int position() {",
        "        return position;",
        "    }",
        "",
        "    public String payload() {",
        "        return payload;",
        "    }",
        "",
        "    public int affectedLength() {",
        "        return affectedLength;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public boolean isInsert() {",
        "        return \"insert\".equals(operationType);",
        "    }",
        "",
        "    public boolean isDelete() {",
        "        return \"delete\".equals(operationType);",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        String normalized = Objects.requireNonNull(value, fieldName).trim();",
        "        if (normalized.isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" must not be blank\");",
        "        }",
        "        return normalized;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ConflictResolutionStrategy.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public interface ConflictResolutionStrategy {",
        "    Operation transform(Operation incoming, Document document);",
        "",
        "    static ConflictResolutionStrategy operationalTransform() {",
        "        return (incoming, document) -> {",
        "            Objects.requireNonNull(incoming, \"incoming\");",
        "            Objects.requireNonNull(document, \"document\");",
        "",
        "            Operation transformed = incoming;",
        "            for (DocumentVersion change : document.historySince(incoming.baseVersion())) {",
        "                if (change.isInsert()) {",
        "                    boolean samePositionAfterOtherAuthor = transformed.position() == change.position()",
        "                        && transformed.authorId().compareTo(change.authorId()) > 0;",
        "                    if (transformed.position() > change.position() || samePositionAfterOtherAuthor) {",
        "                        transformed = transformed.withPosition(transformed.position() + change.affectedLength());",
        "                    }",
        "                } else if (change.isDelete() && transformed.position() > change.position()) {",
        "                    int removedBeforePosition = Math.min(change.affectedLength(), transformed.position() - change.position());",
        "                    transformed = transformed.withPosition(transformed.position() - removedBeforePosition);",
        "                }",
        "            }",
        "            return transformed;",
        "        };",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "CollaborationService.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public class CollaborationService {",
        "    private final Document document;",
        "    private final ConflictResolutionStrategy conflictStrategy;",
        "    private final Map<String, Integer> collaboratorCursors = new LinkedHashMap<>();",
        "    private final List<DocumentObserver> observers = new ArrayList<>();",
        "",
        "    public CollaborationService(Document document, ConflictResolutionStrategy conflictStrategy) {",
        "        this.document = Objects.requireNonNull(document, \"document\");",
        "        this.conflictStrategy = Objects.requireNonNull(conflictStrategy, \"conflictStrategy\");",
        "    }",
        "",
        "    public synchronized DocumentVersion submit(Operation operation) {",
        "        Objects.requireNonNull(operation, \"operation\");",
        "        if (operation.baseVersion() > document.version()) {",
        "            throw new IllegalArgumentException(\"operation is based on a future version\");",
        "        }",
        "",
        "        Operation transformed = conflictStrategy.transform(operation, document);",
        "        DocumentVersion accepted = document.apply(transformed);",
        "        collaboratorCursors.put(transformed.authorId(), clamp(transformed.cursorAfter(accepted)));",
        "        publish(new ChangeEvent(document.id(), accepted.version(), accepted.content(), accepted.authorId(), accepted.operationType(), cursorSnapshot()));",
        "        return accepted;",
        "    }",
        "",
        "    public synchronized void moveCursor(String collaboratorId, int position) {",
        "        String normalized = requireText(collaboratorId, \"collaboratorId\");",
        "        collaboratorCursors.put(normalized, clamp(position));",
        "        publish(new ChangeEvent(document.id(), document.version(), document.text(), normalized, \"cursor\", cursorSnapshot()));",
        "    }",
        "",
        "    public synchronized void subscribe(DocumentObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public synchronized String text() {",
        "        return document.text();",
        "    }",
        "",
        "    public synchronized int version() {",
        "        return document.version();",
        "    }",
        "",
        "    public synchronized List<DocumentVersion> history() {",
        "        return document.history();",
        "    }",
        "",
        "    public synchronized Map<String, Integer> cursors() {",
        "        return cursorSnapshot();",
        "    }",
        "",
        "    private void publish(ChangeEvent event) {",
        "        List<DocumentObserver> copy = new ArrayList<>(observers);",
        "        for (DocumentObserver observer : copy) {",
        "            observer.onChange(event);",
        "        }",
        "    }",
        "",
        "    private int clamp(int position) {",
        "        return Math.max(0, Math.min(position, document.length()));",
        "    }",
        "",
        "    private Map<String, Integer> cursorSnapshot() {",
        "        return Collections.unmodifiableMap(new LinkedHashMap<>(collaboratorCursors));",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        String normalized = Objects.requireNonNull(value, fieldName).trim();",
        "        if (normalized.isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" must not be blank\");",
        "        }",
        "        return normalized;",
        "    }",
        "",
        "    public interface DocumentObserver {",
        "        void onChange(ChangeEvent event);",
        "    }",
        "",
        "    public static final class ChangeEvent {",
        "        private final String documentId;",
        "        private final int version;",
        "        private final String text;",
        "        private final String authorId;",
        "        private final String operationType;",
        "        private final Map<String, Integer> cursors;",
        "",
        "        private ChangeEvent(String documentId, int version, String text, String authorId, String operationType, Map<String, Integer> cursors) {",
        "            this.documentId = documentId;",
        "            this.version = version;",
        "            this.text = text;",
        "            this.authorId = authorId;",
        "            this.operationType = operationType;",
        "            this.cursors = cursors;",
        "        }",
        "",
        "        public String documentId() {",
        "            return documentId;",
        "        }",
        "",
        "        public int version() {",
        "            return version;",
        "        }",
        "",
        "        public String text() {",
        "            return text;",
        "        }",
        "",
        "        public String authorId() {",
        "            return authorId;",
        "        }",
        "",
        "        public String operationType() {",
        "            return operationType;",
        "        }",
        "",
        "        public Map<String, Integer> cursors() {",
        "            return cursors;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Document document = new Document(\"doc-1\", \"Hello world\");",
        "        CollaborationService service = new CollaborationService(document, ConflictResolutionStrategy.operationalTransform());",
        "",
        "        service.subscribe(event -> System.out.println(\"v\" + event.version() + \" \" + event.operationType() + \" by \" + event.authorId() + \" -> \" + event.text() + \" cursors=\" + event.cursors()));",
        "",
        "        service.moveCursor(\"alice\", 5);",
        "        service.submit(new InsertOperation(\"alice\", 0, 5, \" brave\"));",
        "        service.submit(new DeleteOperation(\"bob\", 0, 6, 5));",
        "",
        "        DocumentVersion afterAlice = service.history().get(0);",
        "        document.restore(afterAlice);",
        "        System.out.println(\"Restored to v\" + document.version() + \" -> \" + document.text());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Document",
      detailMD:
        "Owns the mutable text buffer, current version, and list of immutable **DocumentVersion** snapshots. It validates edit positions, applies commands, saves mementos, and restores older versions without exposing its internal **StringBuilder**.",
    },
    {
      className: "Operation",
      detailMD:
        "Command interface shared by all editing operations. It exposes author, base version, position, payload length, cursor result, and **execute**, giving the service one uniform workflow for transform and apply.",
    },
    {
      className: "InsertOperation",
      detailMD:
        "Concrete command for inserting text. It validates author/base/position, can be copied to a transformed position, inserts into the document, and records an **insert** snapshot.",
    },
    {
      className: "DeleteOperation",
      detailMD:
        "Concrete command for deleting text. It records the actual removed payload in the accepted version, which is useful for audit, transform metadata, and future undo extensions.",
    },
    {
      className: "DocumentVersion",
      detailMD:
        "Immutable memento containing version number, full content, author, operation type, position, payload, affected length, and timestamp. It is the version-history unit and the restore input.",
    },
    {
      className: "ConflictResolutionStrategy",
      detailMD:
        "Strategy interface with a static factory for the sample OT implementation. It walks committed versions after the incoming operation's base version and shifts positions for prior inserts/deletes, with deterministic tie-breaking for same-position inserts.",
    },
    {
      className: "CollaborationService",
      detailMD:
        "Facade-like collaboration coordinator. It validates operation versions, transforms commands, applies them atomically, updates collaborator cursors, and notifies nested **DocumentObserver** subscribers with immutable **ChangeEvent** objects.",
    },
    {
      className: "Main",
      detailMD:
        "Small demo showing observer registration, a cursor move, two concurrent edits based on version 0, OT-style transformation of Bob's delete, and restoring the document to Alice's snapshot.",
    },
  ],

  dryRun: {
    inputMD:
      "Initial document text is **Hello world** at version 0. Alice inserts ** brave** at position 5 based on version 0. Bob concurrently deletes 5 characters at old position 6 based on version 0.",
    columns: ["Step", "Action", "Base version", "Transformed position", "Document text", "Published version"],
    rows: [
      ["1", "Alice cursor moves to 5", "0", "n/a", "Hello world", "cursor event only"],
      ["2", "Alice inserts ** brave**", "0", "5", "Hello brave world", "v1 insert"],
      ["3", "Bob deletes 5 chars at old position 6", "0", "12 after Alice insert", "Hello brave ", "v2 delete"],
      ["4", "Restore to Alice snapshot", "v1", "n/a", "Hello brave world", "document version becomes v1"],
    ],
    narrativeMD:
      "The important step is 3: Bob's command was authored against version 0, but the service transforms it through Alice's version 1 insert. His delete shifts from position 6 to position 12, so it still removes **world** instead of deleting part of Alice's inserted text.",
  },

  complexity: [
    {
      operation: "submit edit",
      time: "O(H + N + O)",
      space: "O(N)",
      note: "H committed versions since the base version, N document length for StringBuilder shift/snapshot, O observers to notify.",
    },
    {
      operation: "move cursor",
      time: "O(O + C)",
      space: "O(C)",
      note: "Updates one cursor, copies C cursor entries for an immutable event, and notifies O observers.",
    },
    {
      operation: "restore version",
      time: "O(N + V)",
      space: "O(N)",
      note: "Copies snapshot text back into the document and prunes versions after the restored version.",
    },
    {
      operation: "history lookup",
      time: "O(V)",
      space: "O(V)",
      note: "Returns a defensive copy of V accepted document versions.",
    },
  ],
  complexityNotesMD:
    "The sample intentionally favors clarity. Production editors avoid full snapshots on every keystroke by using operation logs, periodic checkpoints, compaction, and text structures such as ropes or piece tables.",

  extensibility: [
    {
      label: "Replace OT with CRDT",
      detailMD:
        "Implement a new **ConflictResolutionStrategy** that assigns stable character identifiers and merges operations commutatively. Commands and the collaboration service can remain mostly unchanged.",
    },
    {
      label: "Richer document model",
      detailMD:
        "Replace plain text with paragraphs, style ranges, comments, or embedded objects. Operations become typed commands such as apply style, add comment, or insert block.",
    },
    {
      label: "Per-user undo",
      detailMD:
        "Store author-scoped accepted operations and generate inverse commands that are transformed through later operations before being applied.",
    },
    {
      label: "Durable history",
      detailMD:
        "Persist versions and operations through a repository. Keep periodic full snapshots and compact older operations for long-lived documents.",
    },
  ],

  alternativeDesigns: [
    {
      name: "CRDT-first editor",
      detailMD:
        "Represent each character or span with a globally unique ordered id. Concurrent inserts/deletes merge without a central transform step because operations are designed to commute.",
      tradeoffsMD:
        "Excellent offline and peer-to-peer behavior, but object metadata is heavier and the LLD explanation is harder than a base-version OT strategy.",
    },
    {
      name: "Event-sourced command log",
      detailMD:
        "Store only accepted commands as an append-only log and rebuild document state by replaying from checkpoints.",
      tradeoffsMD:
        "Great auditability and replay, but restore and open-document latency require checkpointing and compaction.",
    },
    {
      name: "Single document actor",
      detailMD:
        "Route all operations for a document to one in-memory actor or queue. The actor serializes edits, transforms stale operations, and broadcasts results.",
      tradeoffsMD:
        "Simplifies locking and ordering but requires partitioning by document id and careful failover for hot documents.",
    },
  ],

  commonMistakes: [
    "Applying an edit directly to current text without carrying the operation's base version.",
    "Treating cursor moves as document versions, which pollutes history and creates unnecessary conflicts.",
    "Returning mutable history lists, cursor maps, or document buffers to observers.",
    "Using last-write-wins for text edits, which loses user content instead of reconciling intent.",
    "Creating snapshots without operation metadata, making later transform, audit, or undo logic harder.",
    "Forgetting deterministic tie-breaking when two collaborators insert at the same position.",
    "Hard-coding OT logic inside commands instead of behind a conflict-resolution strategy.",
  ],

  followUps: [
    {
      question: "How do you handle two users inserting at exactly the same position?",
      answerMD:
        "Use deterministic tie-breaking such as author id, session id, or server sequence number. Every replica must choose the same ordering so documents converge.",
    },
    {
      question: "How would you support offline editing?",
      answerMD:
        "Persist local commands with base versions, submit them when online, and transform or merge them against committed remote changes. CRDTs often simplify this compared with server-side OT.",
    },
    {
      question: "How do you implement undo in a collaborative editor?",
      answerMD:
        "Undo should usually be per-user intent, not global rollback. Generate an inverse command for the user's accepted operation and transform that inverse through later operations before applying it.",
    },
    {
      question: "Why not notify observers directly from Document?",
      answerMD:
        "The document should stay a pure domain object. The service has collaborator context, cursor state, and delivery concerns, so it is the better observer publisher.",
    },
    {
      question: "When would you choose CRDT over OT?",
      answerMD:
        "Choose CRDT when offline, peer-to-peer, or multi-region convergence is the main driver. Choose OT when a central server can order operations and the team wants a simpler mental model.",
    },
  ],

  productionConsiderations: [
    {
      label: "Text storage structure",
      detailMD:
        "A **StringBuilder** is fine for the interview. Production editors use ropes, piece tables, or gap buffers to avoid O(N) shifts on large documents.",
    },
    {
      label: "Snapshot retention",
      detailMD:
        "Full mementos per keystroke are too expensive. Batch edits, checkpoint periodically, compress old snapshots, and retain operation logs for audit.",
    },
    {
      label: "Delivery architecture",
      detailMD:
        "Observers become WebSocket or pub/sub clients. Use per-document sequence numbers, acknowledgements, reconnect replay, and backpressure for slow collaborators.",
    },
    {
      label: "Locking and scaling",
      detailMD:
        "Synchronizing one service instance is enough for LLD. At scale, shard by document id and serialize edits through a document actor, queue partition, or transactional operation table.",
    },
    {
      label: "Security and abuse control",
      detailMD:
        "Validate permissions before accepting operations, cap operation size, rate-limit clients, and audit every accepted command with collaborator identity.",
    },
  ],

  interviewNotes: [
    "Did you make insert/delete explicit command objects rather than ad hoc methods on a controller?",
    "Did you explain stale base versions and how a strategy transforms operations through committed history?",
    "Did you separate document versions from cursor presence events?",
    "Did you use immutable mementos for history and restore instead of exposing mutable document state?",
    "Can you clearly discuss the OT versus CRDT tradeoff without trying to implement a full distributed system?",
  ],

  quiz: [
    {
      question: "Why does each **Operation** carry a base version?",
      options: [
        "So the service knows which committed edits the operation has not seen",
        "So cursor moves can be saved as document versions",
        "So observers can skip notifications",
        "So deletes never need positions",
      ],
      answerIndex: 0,
      explanationMD:
        "The base version is the anchor for conflict resolution. The strategy transforms the operation through committed versions newer than that base.",
    },
    {
      question: "Which pattern best describes **DocumentVersion**?",
      options: [
        "Observer",
        "Memento",
        "Adapter",
        "Object Pool",
      ],
      answerIndex: 1,
      explanationMD:
        "A memento captures state so an object can later be restored without exposing its internals.",
    },
    {
      question: "What does **ConflictResolutionStrategy** buy the design?",
      options: [
        "It makes the document immutable",
        "It hides cursor rendering details",
        "It lets OT, CRDT, or another merge policy vary independently",
        "It stores user permissions",
      ],
      answerIndex: 2,
      explanationMD:
        "The service depends on the strategy interface, not a hard-coded algorithm, so conflict policy can evolve.",
    },
    {
      question: "Why are cursor moves not saved as **DocumentVersion** entries?",
      options: [
        "They are too hard to render",
        "They are presence state and do not change document text",
        "They cannot be observed",
        "They are handled by the Command pattern only",
      ],
      answerIndex: 1,
      explanationMD:
        "Cursors are collaborative presence. They should be broadcast, but they should not increment document versions or affect edit transforms.",
    },
    {
      question: "Two users insert text at the same position. What must the design guarantee?",
      options: [
        "The longer insert always wins",
        "One insert is discarded",
        "Every replica uses the same deterministic ordering",
        "The document creates two unrelated versions with the same number",
      ],
      answerIndex: 2,
      explanationMD:
        "Convergence requires all participants to order concurrent same-position inserts consistently, often by server sequence or author id.",
    },
    {
      question: "What is the main tradeoff of full-text snapshots on every edit?",
      options: [
        "They make restore simple but can consume large memory and storage",
        "They prevent observers from working",
        "They make conflict resolution impossible",
        "They remove the need for validation",
      ],
      answerIndex: 0,
      explanationMD:
        "Full snapshots are easy to explain and restore from, but production systems usually compact, checkpoint, or store deltas.",
    },
  ],

  practiceVariants: [
    {
      title: "Add per-user undo",
      detailMD:
        "Generate inverse commands for a user's accepted operations and transform those inverses through later history before applying them.",
      difficulty: "Advanced",
    },
    {
      title: "Replace text with styled ranges",
      detailMD:
        "Support bold/italic spans and comments while keeping inserts, deletes, and style changes as command objects.",
      difficulty: "Advanced",
    },
    {
      title: "Implement CRDT positions",
      detailMD:
        "Assign stable identifiers to characters and write a **ConflictResolutionStrategy** that merges inserts/deletes without central position shifting.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "Why model edits as commands?",
      back: "Commands preserve edit intent, author, base version, and execution behavior so the service can transform, audit, replay, and apply them uniformly.",
    },
    {
      front: "What is the memento in this design?",
      back: "**DocumentVersion**, an immutable snapshot of text plus operation metadata after an accepted edit.",
    },
    {
      front: "What does the conflict strategy transform?",
      back: "It transforms a stale operation's position through committed inserts and deletes that happened after the operation's base version.",
    },
    {
      front: "Are cursors part of version history?",
      back: "No. Cursors are presence state; they are broadcast to observers but do not change document text or version.",
    },
    {
      front: "Where are observer notifications published?",
      back: "From **CollaborationService**, because it has the accepted version, collaborator context, cursor snapshot, and delivery boundary.",
    },
    {
      front: "OT versus CRDT in one line?",
      back: "OT transforms operations against a server-ordered history; CRDT designs operations and identifiers so replicas can merge them commutatively.",
    },
  ],

  cheatSheetMD: [
    "**Core objects:** Document, Operation, InsertOperation, DeleteOperation, DocumentVersion, ConflictResolutionStrategy, CollaborationService, DocumentObserver.",
    "",
    "**Patterns:** Command for edits, Memento for version snapshots, Observer for update pushes, Strategy for conflict resolution.",
    "",
    "**Edit flow:** submit command -> validate base version -> transform through missed versions -> apply to Document -> save DocumentVersion -> update cursor -> notify observers.",
    "",
    "**Concurrency idea:** a command based on an older version is not rejected by default; it is transformed so its original user intent maps onto the current document.",
    "",
    "**Presence:** collaborator cursors are separate from text history and are published as lightweight events.",
    "",
    "**Production upgrades:** rope or piece table for text, operation log plus checkpoints for history, WebSocket/pub-sub observers, per-document actor for ordering, CRDT for offline-first editing.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Concurrency Control in Groupware Systems",
      kind: "Paper",
      author: "C. A. Ellis and S. J. Gibbs",
      url: "https://dl.acm.org/doi/10.1145/67544.66963",
    },
    {
      title: "A comprehensive study of Convergent and Commutative Replicated Data Types",
      kind: "Paper",
      author: "Marc Shapiro et al.",
      url: "https://inria.hal.science/inria-00555588/document",
    },
    {
      title: "Refactoring Guru — Command Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/command",
    },
  ],

  relatedProblems: [
    { slug: "text-editor", note: "Single-user editing core with Command and Memento before collaboration is added." },
    { slug: "dropbox", note: "File synchronization has a similar conflict and version-history conversation." },
    { slug: "google-drive", note: "Document storage, permissions, and file metadata around collaborative documents." },
  ],
};
