import type { LLDProblemContent } from "../types";

export const hotelManagement: LLDProblemContent = {
  slug: "hotel-management",

  statementMD: [
    "Design the object model for a **hotel management system** that can search",
    "available rooms over a requested stay, create reservations, move them through",
    "check-in and check-out, price the stay, and produce an invoice.",
    "",
    "The heart of the problem is not CRUD. It is the date-range invariant: a room",
    "is unavailable for a request if any active reservation for that room overlaps",
    "the requested **[check-in, check-out)** interval. The design should make that",
    "rule explicit and reusable across search, booking, cancellation, and billing.",
  ].join("\n"),

  businessContextMD: [
    "Hotel Management appears in Amazon, Airbnb, and Oracle style interviews because",
    "it combines booking, inventory, state transitions, and pricing in one familiar",
    "domain. A good answer separates room inventory from reservation lifecycle, keeps",
    "date logic deterministic, and gives the business seams for taxes, seasonal rates,",
    "housekeeping, channel managers, and no-show handling.",
    "",
    "Interviewers are looking for whether the candidate can protect a scarce resource",
    "across time. A design that only checks whether a room is currently empty misses",
    "the real problem: future reservations must block overlapping future stays too.",
  ].join("\n"),

  functionalRequirements: [
    "Maintain hotel rooms with room number, floor, type, capacity, and operational status.",
    "Support room types such as Standard, Deluxe, and Suite with base nightly rates and guest capacity.",
    "Search available rooms for a room type, guest count, and check-in/check-out date range.",
    "Create a reservation only when the chosen room has no active overlapping reservation.",
    "Move a reservation through **Reserved**, **CheckedIn**, **CheckedOut**, **Cancelled**, and **NoShow** states with valid transitions only.",
    "Allow cancellation and no-show marking before check-in so blocked inventory can be released.",
    "Generate an invoice on check-out using a pluggable pricing strategy and optional extra charges.",
    "Notify observers such as housekeeping and availability boards when room status changes.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Date-range correctness",
      detailMD:
        "Availability must use half-open intervals and the overlap rule **requestStart < existingEnd && requestEnd > existingStart**. Adjacent stays where one check-out equals the next check-in are allowed.",
    },
    {
      label: "Lifecycle safety",
      detailMD:
        "Reservation transitions must be centralized so a cancelled reservation cannot check in and a checked-out reservation cannot be billed twice through the same flow.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New pricing plans, room creation rules, and observers should be additive classes rather than edits inside the reservation flow.",
    },
    {
      label: "Low-latency search",
      detailMD:
        "The interview implementation can scan in memory, but it must make the hot path clear enough to replace with indexed inventory later.",
    },
    {
      label: "Auditability",
      detailMD:
        "Invoices should capture the reservation id, room charge, extras, tax, total, and issue time so customer disputes can be explained.",
    },
  ],

  requirementClarification: [
    {
      question: "Are check-in and check-out dates inclusive?",
      answerMD:
        "Use a half-open interval: check-in is inclusive and check-out is exclusive. A stay from Aug 1 to Aug 4 occupies the nights of Aug 1, Aug 2, and Aug 3, and another guest may check in on Aug 4.",
    },
    {
      question: "Should cancelled and no-show reservations block availability?",
      answerMD:
        "No. They remain in history but stop blocking inventory. Only **Reserved** and **CheckedIn** reservations block a room for overlap checks.",
    },
    {
      question: "Do we allocate a specific room at reservation time?",
      answerMD:
        "Yes for the base design. The service searches matching rooms and binds the first available room to the reservation. A later extension can support room-type-only inventory pools.",
    },
    {
      question: "Do we need payment gateway integration?",
      answerMD:
        "No for the core LLD. The system produces an invoice. Payment collection is a boundary adapter that can consume the invoice total.",
    },
    {
      question: "How is housekeeping represented?",
      answerMD:
        "Room status changes are observable. Check-out moves the room to **Cleaning**, an observer can dispatch housekeeping, and the room becomes searchable again only after it is marked **Available**.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class HotelService {",
    "        -Map~String,Room~ rooms",
    "        -Map~String,Reservation~ reservations",
    "        -SearchService searchService",
    "        -PricingStrategy pricingStrategy",
    "        -RoomFactory roomFactory",
    "        +addRoom(String,RoomType,int) Room",
    "        +search(RoomType,LocalDate,LocalDate,int) List~Room~",
    "        +reserve(String,RoomType,LocalDate,LocalDate,int) Reservation",
    "        +checkIn(String) void",
    "        +checkOut(String,List~Charge~) Invoice",
    "    }",
    "    class Room {",
    "        -String roomNumber",
    "        -RoomType type",
    "        -int floor",
    "        -RoomStatus status",
    "        -List~RoomObserver~ observers",
    "        +isBookable() boolean",
    "        +markOccupied() void",
    "        +markCleaning() void",
    "        +markAvailable() void",
    "    }",
    "    class RoomType {",
    "        <<enumeration>>",
    "        STANDARD",
    "        DELUXE",
    "        SUITE",
    "    }",
    "    class RoomFactory {",
    "        <<interface>>",
    "        +createRoom(String,RoomType,int) Room",
    "    }",
    "    class StandardRoomFactory",
    "    class Reservation {",
    "        -String id",
    "        -Room room",
    "        -LocalDate checkInDate",
    "        -LocalDate checkOutDate",
    "        -ReservationState state",
    "        +overlaps(LocalDate,LocalDate) boolean",
    "        +checkIn() void",
    "        +checkOut() void",
    "        +cancel() void",
    "        +markNoShow() void",
    "    }",
    "    class ReservationState {",
    "        <<interface>>",
    "        +name() String",
    "        +blocksInventory() boolean",
    "        +checkIn(Reservation) void",
    "        +checkOut(Reservation) void",
    "    }",
    "    class ReservedState",
    "    class CheckedInState",
    "    class CheckedOutState",
    "    class CancelledState",
    "    class NoShowState",
    "    class SearchService {",
    "        +findAvailableRooms(Collection~Room~,Collection~Reservation~,RoomType,LocalDate,LocalDate,int) List~Room~",
    "        +isAvailable(Room,Collection~Reservation~,LocalDate,LocalDate) boolean",
    "    }",
    "    class PricingStrategy {",
    "        <<interface>>",
    "        +createInvoice(Reservation,List~Charge~) Invoice",
    "    }",
    "    class StandardPricingStrategy",
    "    class Invoice",
    "    class RoomObserver {",
    "        <<interface>>",
    "        +onStatusChanged(Room,RoomStatus,RoomStatus) void",
    "    }",
    "    class HousekeepingObserver",
    "    class AvailabilityObserver",
    "    HotelService o-- Room",
    "    HotelService o-- Reservation",
    "    HotelService ..> SearchService",
    "    HotelService ..> PricingStrategy",
    "    HotelService ..> RoomFactory",
    "    Room --> RoomType",
    "    Room ..> RoomObserver",
    "    RoomFactory <|.. StandardRoomFactory",
    "    Reservation --> Room",
    "    Reservation --> ReservationState",
    "    ReservationState <|.. ReservedState",
    "    ReservationState <|.. CheckedInState",
    "    ReservationState <|.. CheckedOutState",
    "    ReservationState <|.. CancelledState",
    "    ReservationState <|.. NoShowState",
    "    PricingStrategy <|.. StandardPricingStrategy",
    "    RoomObserver <|.. HousekeepingObserver",
    "    RoomObserver <|.. AvailabilityObserver",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service is the aggregate boundary, but it delegates overlap checks to **Reservation**, search policy to **SearchService**, lifecycle rules to state objects, pricing to **PricingStrategy**, and room creation to **RoomFactory**.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Guest",
    "    participant Hotel as HotelService",
    "    participant Search as SearchService",
    "    participant Res as Reservation",
    "    participant Room as Room",
    "    participant Board as AvailabilityObserver",
    "    Guest->>Hotel: reserve(type, dates, guests)",
    "    Hotel->>Search: findAvailableRooms(rooms, reservations, dates)",
    "    loop rooms and active reservations",
    "        Search->>Res: overlaps(requestStart, requestEnd)",
    "        Res-->>Search: false for candidate room",
    "        Search->>Room: isBookable()",
    "    end",
    "    Search-->>Hotel: available rooms",
    "    Hotel->>Hotel: create Reservation in Reserved state",
    "    Hotel-->>Guest: reservation id",
    "    Guest->>Hotel: checkIn(id)",
    "    Hotel->>Res: checkIn()",
    "    Res->>Room: markOccupied()",
    "    Room-->>Board: onStatusChanged(AVAILABLE,OCCUPIED)",
    "    Guest->>Hotel: checkOut(id, extras)",
    "    Hotel->>Res: checkOut()",
    "    Res->>Room: markCleaning()",
    "    Hotel->>Hotel: pricingStrategy.createInvoice(reservation, extras)",
    "    Hotel-->>Guest: invoice",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Reservation creation depends on overlap search; check-in and check-out are state transitions that also drive room status observers.",

  entities: [
    {
      name: "Room",
      responsibilityMD:
        "Represents a physical room. It owns operational status, knows its room type, and notifies observers whenever status changes.",
      attributes: ["roomNumber", "type", "floor", "status", "observers"],
    },
    {
      name: "RoomType",
      responsibilityMD:
        "Defines capacity and base nightly rate for Standard, Deluxe, and Suite rooms. Search uses capacity, pricing uses the rate.",
      attributes: ["baseNightlyRateCents", "maxGuests"],
    },
    {
      name: "Reservation",
      responsibilityMD:
        "Binds a guest, room, date range, guest count, and current state. It owns the overlap predicate and delegates valid transitions to its state object.",
      attributes: ["id", "guestName", "room", "checkInDate", "checkOutDate", "state"],
    },
    {
      name: "ReservationState",
      responsibilityMD:
        "State pattern seam for reservation lifecycle. Concrete states decide whether inventory is blocked and which transitions are legal.",
      attributes: ["ReservedState", "CheckedInState", "CheckedOutState", "CancelledState", "NoShowState"],
    },
    {
      name: "SearchService",
      responsibilityMD:
        "Filters candidate rooms by type, guest capacity, room status, and active overlapping reservations using one date-range rule.",
      attributes: ["findAvailableRooms", "isAvailable"],
    },
    {
      name: "PricingStrategy",
      responsibilityMD:
        "Calculates invoice totals from nights, room type rate, extra charges, and tax. Seasonal or channel-specific pricing can replace the default strategy.",
      attributes: ["createInvoice"],
    },
    {
      name: "Invoice",
      responsibilityMD:
        "Immutable billing result produced at check-out with room charge, extras, tax, total, reservation id, and issue timestamp.",
      attributes: ["reservationId", "roomChargeCents", "extraChargeCents", "taxCents", "totalCents"],
    },
    {
      name: "HotelService",
      responsibilityMD:
        "Application service and aggregate boundary. It owns collections, creates rooms and reservations, coordinates lifecycle calls, and returns invoices.",
      attributes: ["rooms", "reservations", "searchService", "pricingStrategy", "roomFactory"],
    },
    {
      name: "RoomObserver",
      responsibilityMD:
        "Observer interface for secondary reactions to room status changes, such as dispatching housekeeping or updating an availability board.",
      attributes: ["onStatusChanged"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**ReservationState** keeps lifecycle rules out of service code. **Reserved** permits check-in, cancellation, and no-show; **CheckedIn** permits check-out; terminal states reject further transitions.",
    },
    {
      name: "Strategy",
      whyMD:
        "**PricingStrategy** isolates rate calculation and invoice creation. The check-out flow does not know whether pricing is standard, seasonal, member-discounted, or channel-specific.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**RoomFactory** centralizes room creation so validation, default status, room-number policy, and future room subclasses are not scattered across service methods.",
    },
    {
      name: "Observer",
      whyMD:
        "**RoomObserver** lets housekeeping and availability boards react to room status changes without coupling those concerns to **Room** or **HotelService**.",
    },
  ],

  designSteps: [
    {
      title: "Define the date-range invariant first",
      detailMD:
        "Use half-open stays and one overlap predicate everywhere. This allows back-to-back reservations and prevents the classic bug where checking current room status ignores future bookings.",
      code: [
        "public boolean overlaps(LocalDate start, LocalDate end) {",
        "    validateDateRange(start, end);",
        "    return blocksInventory()",
        "        && start.isBefore(checkOutDate)",
        "        && end.isAfter(checkInDate);",
        "}",
      ].join("\n"),
    },
    {
      title: "Separate room type from room status",
      detailMD:
        "**RoomType** captures stable commercial facts like rate and capacity. **RoomStatus** captures operational facts like Available, Occupied, Cleaning, and Maintenance.",
    },
    {
      title: "Put lifecycle behavior behind state objects",
      detailMD:
        "The reservation exposes **checkIn**, **checkOut**, **cancel**, and **markNoShow**, but the current state decides what each call means. Illegal transitions fail immediately.",
      code: [
        "final class ReservedState implements ReservationState {",
        "    public void checkIn(Reservation reservation) {",
        "        reservation.transitionTo(new CheckedInState());",
        "        reservation.getRoom().markOccupied();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Search by filtering rooms against active reservations",
      detailMD:
        "**SearchService** first filters by room type, capacity, and operational status. It then rejects any room with an active reservation whose date range overlaps the request.",
    },
    {
      title: "Generate invoices through a strategy",
      detailMD:
        "Check-out transitions the reservation, moves the room to Cleaning, and asks the injected pricing strategy for the invoice. The service coordinates; it does not hard-code rate math.",
      code: [
        "public Invoice checkOut(String reservationId, List<Charge> extras) {",
        "    Reservation reservation = getReservation(reservationId);",
        "    reservation.checkOut();",
        "    return pricingStrategy.createInvoice(reservation, extras);",
        "}",
      ].join("\n"),
    },
    {
      title: "Notify housekeeping and availability as observers",
      detailMD:
        "Room status changes are local events. Observers subscribe to rooms and update secondary views without the domain model knowing those consumers exist.",
    },
  ],

  implementation: [
    {
      filename: "Room.java",
      language: "java",
      content: [
        'import java.util.ArrayList;',
        'import java.util.List;',
        'import java.util.Objects;',
        '',
        'public class Room {',
        '    private final String roomNumber;',
        '    private final RoomType type;',
        '    private final int floor;',
        '    private RoomStatus status;',
        '    private final List<RoomObserver> observers = new ArrayList<>();',
        '',
        '    public Room(String roomNumber, RoomType type, int floor) {',
        '        this.roomNumber = requireNonBlank(roomNumber, "roomNumber");',
        '        this.type = Objects.requireNonNull(type, "type");',
        '        this.floor = floor;',
        '        this.status = RoomStatus.AVAILABLE;',
        '    }',
        '',
        '    public String getRoomNumber() {',
        '        return roomNumber;',
        '    }',
        '',
        '    public RoomType getType() {',
        '        return type;',
        '    }',
        '',
        '    public int getFloor() {',
        '        return floor;',
        '    }',
        '',
        '    public RoomStatus getStatus() {',
        '        return status;',
        '    }',
        '',
        '    public boolean isBookable() {',
        '        return status == RoomStatus.AVAILABLE || status == RoomStatus.OCCUPIED;',
        '    }',
        '',
        '    public void addObserver(RoomObserver observer) {',
        '        observers.add(Objects.requireNonNull(observer, "observer"));',
        '    }',
        '',
        '    public void markAvailable() {',
        '        changeStatus(RoomStatus.AVAILABLE);',
        '    }',
        '',
        '    public void markOccupied() {',
        '        changeStatus(RoomStatus.OCCUPIED);',
        '    }',
        '',
        '    public void markCleaning() {',
        '        changeStatus(RoomStatus.CLEANING);',
        '    }',
        '',
        '    public void markMaintenance() {',
        '        changeStatus(RoomStatus.MAINTENANCE);',
        '    }',
        '',
        '    private void changeStatus(RoomStatus next) {',
        '        Objects.requireNonNull(next, "next");',
        '        if (status == next) {',
        '            return;',
        '        }',
        '        RoomStatus previous = status;',
        '        status = next;',
        '        for (RoomObserver observer : observers) {',
        '            observer.onStatusChanged(this, previous, next);',
        '        }',
        '    }',
        '',
        '    private static String requireNonBlank(String value, String field) {',
        '        if (value == null || value.trim().isEmpty()) {',
        '            throw new IllegalArgumentException(field + " is required");',
        '        }',
        '        return value;',
        '    }',
        '',
        '    @Override',
        '    public boolean equals(Object other) {',
        '        if (this == other) {',
        '            return true;',
        '        }',
        '        if (!(other instanceof Room)) {',
        '            return false;',
        '        }',
        '        Room room = (Room) other;',
        '        return roomNumber.equals(room.roomNumber);',
        '    }',
        '',
        '    @Override',
        '    public int hashCode() {',
        '        return roomNumber.hashCode();',
        '    }',
        '',
        '    @Override',
        '    public String toString() {',
        '        return roomNumber + " " + type + " " + status;',
        '    }',
        '}',
        '',
        'enum RoomStatus {',
        '    AVAILABLE,',
        '    OCCUPIED,',
        '    CLEANING,',
        '    MAINTENANCE',
        '}',
        '',
        'interface RoomObserver {',
        '    void onStatusChanged(Room room, RoomStatus previous, RoomStatus next);',
        '}',
      ].join("\n"),
    },
    {
      filename: "RoomType.java",
      language: "java",
      content: [
        'public enum RoomType {',
        '    STANDARD(10_000, 2),',
        '    DELUXE(15_000, 3),',
        '    SUITE(25_000, 4);',
        '',
        '    private final long baseNightlyRateCents;',
        '    private final int maxGuests;',
        '',
        '    RoomType(long baseNightlyRateCents, int maxGuests) {',
        '        this.baseNightlyRateCents = baseNightlyRateCents;',
        '        this.maxGuests = maxGuests;',
        '    }',
        '',
        '    public long getBaseNightlyRateCents() {',
        '        return baseNightlyRateCents;',
        '    }',
        '',
        '    public int getMaxGuests() {',
        '        return maxGuests;',
        '    }',
        '',
        '    public boolean canHost(int guests) {',
        '        return guests > 0 && guests <= maxGuests;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Reservation.java",
      language: "java",
      content: [
        'import java.time.LocalDate;',
        'import java.time.temporal.ChronoUnit;',
        'import java.util.Objects;',
        '',
        'public class Reservation {',
        '    private final String id;',
        '    private final String guestName;',
        '    private final Room room;',
        '    private final LocalDate checkInDate;',
        '    private final LocalDate checkOutDate;',
        '    private final int guests;',
        '    private ReservationState state;',
        '',
        '    public Reservation(String id, String guestName, Room room, LocalDate checkInDate, LocalDate checkOutDate, int guests) {',
        '        this.id = requireNonBlank(id, "id");',
        '        this.guestName = requireNonBlank(guestName, "guestName");',
        '        this.room = Objects.requireNonNull(room, "room");',
        '        validateDateRange(checkInDate, checkOutDate);',
        '        if (!room.getType().canHost(guests)) {',
        '            throw new IllegalArgumentException("Room type cannot host guest count");',
        '        }',
        '        this.checkInDate = checkInDate;',
        '        this.checkOutDate = checkOutDate;',
        '        this.guests = guests;',
        '        this.state = new ReservedState();',
        '    }',
        '',
        '    public String getId() {',
        '        return id;',
        '    }',
        '',
        '    public String getGuestName() {',
        '        return guestName;',
        '    }',
        '',
        '    public Room getRoom() {',
        '        return room;',
        '    }',
        '',
        '    public LocalDate getCheckInDate() {',
        '        return checkInDate;',
        '    }',
        '',
        '    public LocalDate getCheckOutDate() {',
        '        return checkOutDate;',
        '    }',
        '',
        '    public int getGuests() {',
        '        return guests;',
        '    }',
        '',
        '    public String getStateName() {',
        '        return state.name();',
        '    }',
        '',
        '    public void checkIn() {',
        '        state.checkIn(this);',
        '    }',
        '',
        '    public void checkOut() {',
        '        state.checkOut(this);',
        '    }',
        '',
        '    public void cancel() {',
        '        state.cancel(this);',
        '    }',
        '',
        '    public void markNoShow() {',
        '        state.markNoShow(this);',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return state.blocksInventory();',
        '    }',
        '',
        '    public boolean overlaps(LocalDate start, LocalDate end) {',
        '        validateDateRange(start, end);',
        '        return blocksInventory()',
        '            && start.isBefore(checkOutDate)',
        '            && end.isAfter(checkInDate);',
        '    }',
        '',
        '    public long nights() {',
        '        return ChronoUnit.DAYS.between(checkInDate, checkOutDate);',
        '    }',
        '',
        '    void transitionTo(ReservationState next) {',
        '        state = Objects.requireNonNull(next, "next");',
        '    }',
        '',
        '    public static void validateDateRange(LocalDate checkInDate, LocalDate checkOutDate) {',
        '        Objects.requireNonNull(checkInDate, "checkInDate");',
        '        Objects.requireNonNull(checkOutDate, "checkOutDate");',
        '        if (!checkInDate.isBefore(checkOutDate)) {',
        '            throw new IllegalArgumentException("checkInDate must be before checkOutDate");',
        '        }',
        '    }',
        '',
        '    private static String requireNonBlank(String value, String field) {',
        '        if (value == null || value.trim().isEmpty()) {',
        '            throw new IllegalArgumentException(field + " is required");',
        '        }',
        '        return value;',
        '    }',
        '}',
        '',
        'interface ReservationState {',
        '    String name();',
        '    boolean blocksInventory();',
        '',
        '    default void checkIn(Reservation reservation) {',
        '        throw invalid("check in");',
        '    }',
        '',
        '    default void checkOut(Reservation reservation) {',
        '        throw invalid("check out");',
        '    }',
        '',
        '    default void cancel(Reservation reservation) {',
        '        throw invalid("cancel");',
        '    }',
        '',
        '    default void markNoShow(Reservation reservation) {',
        '        throw invalid("mark no-show");',
        '    }',
        '',
        '    default IllegalStateException invalid(String action) {',
        '        return new IllegalStateException("Cannot " + action + " when reservation is " + name());',
        '    }',
        '}',
        '',
        'final class ReservedState implements ReservationState {',
        '    public String name() {',
        '        return "Reserved";',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return true;',
        '    }',
        '',
        '    public void checkIn(Reservation reservation) {',
        '        reservation.transitionTo(new CheckedInState());',
        '        reservation.getRoom().markOccupied();',
        '    }',
        '',
        '    public void cancel(Reservation reservation) {',
        '        reservation.transitionTo(new CancelledState());',
        '    }',
        '',
        '    public void markNoShow(Reservation reservation) {',
        '        reservation.transitionTo(new NoShowState());',
        '    }',
        '}',
        '',
        'final class CheckedInState implements ReservationState {',
        '    public String name() {',
        '        return "CheckedIn";',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return true;',
        '    }',
        '',
        '    public void checkOut(Reservation reservation) {',
        '        reservation.transitionTo(new CheckedOutState());',
        '        reservation.getRoom().markCleaning();',
        '    }',
        '}',
        '',
        'final class CheckedOutState implements ReservationState {',
        '    public String name() {',
        '        return "CheckedOut";',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return false;',
        '    }',
        '}',
        '',
        'final class CancelledState implements ReservationState {',
        '    public String name() {',
        '        return "Cancelled";',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return false;',
        '    }',
        '}',
        '',
        'final class NoShowState implements ReservationState {',
        '    public String name() {',
        '        return "NoShow";',
        '    }',
        '',
        '    public boolean blocksInventory() {',
        '        return false;',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "PricingStrategy.java",
      language: "java",
      content: [
        'import java.time.LocalDateTime;',
        'import java.util.ArrayList;',
        'import java.util.Collections;',
        'import java.util.List;',
        'import java.util.Objects;',
        '',
        'public interface PricingStrategy {',
        '    Invoice createInvoice(Reservation reservation, List<Charge> extras);',
        '}',
        '',
        'final class StandardPricingStrategy implements PricingStrategy {',
        '    private final int taxBasisPoints;',
        '',
        '    public StandardPricingStrategy(int taxBasisPoints) {',
        '        if (taxBasisPoints < 0) {',
        '            throw new IllegalArgumentException("taxBasisPoints cannot be negative");',
        '        }',
        '        this.taxBasisPoints = taxBasisPoints;',
        '    }',
        '',
        '    public Invoice createInvoice(Reservation reservation, List<Charge> extras) {',
        '        Objects.requireNonNull(reservation, "reservation");',
        '        List<Charge> safeExtras = extras == null ? Collections.emptyList() : extras;',
        '        long roomChargeCents = reservation.nights() * reservation.getRoom().getType().getBaseNightlyRateCents();',
        '        long extraChargeCents = 0;',
        '        for (Charge charge : safeExtras) {',
        '            extraChargeCents += charge.getAmountCents();',
        '        }',
        '        long subtotal = roomChargeCents + extraChargeCents;',
        '        long taxCents = subtotal * taxBasisPoints / 10_000;',
        '        return new Invoice(',
        '            reservation.getId(),',
        '            roomChargeCents,',
        '            extraChargeCents,',
        '            taxCents,',
        '            subtotal + taxCents,',
        '            safeExtras',
        '        );',
        '    }',
        '}',
        '',
        'final class Charge {',
        '    private final String description;',
        '    private final long amountCents;',
        '',
        '    public Charge(String description, long amountCents) {',
        '        if (description == null || description.trim().isEmpty()) {',
        '            throw new IllegalArgumentException("description is required");',
        '        }',
        '        if (amountCents < 0) {',
        '            throw new IllegalArgumentException("amountCents cannot be negative");',
        '        }',
        '        this.description = description;',
        '        this.amountCents = amountCents;',
        '    }',
        '',
        '    public String getDescription() {',
        '        return description;',
        '    }',
        '',
        '    public long getAmountCents() {',
        '        return amountCents;',
        '    }',
        '}',
        '',
        'final class Invoice {',
        '    private final String reservationId;',
        '    private final long roomChargeCents;',
        '    private final long extraChargeCents;',
        '    private final long taxCents;',
        '    private final long totalCents;',
        '    private final List<Charge> extras;',
        '    private final LocalDateTime issuedAt;',
        '',
        '    Invoice(String reservationId, long roomChargeCents, long extraChargeCents, long taxCents, long totalCents, List<Charge> extras) {',
        '        this.reservationId = Objects.requireNonNull(reservationId, "reservationId");',
        '        this.roomChargeCents = roomChargeCents;',
        '        this.extraChargeCents = extraChargeCents;',
        '        this.taxCents = taxCents;',
        '        this.totalCents = totalCents;',
        '        this.extras = Collections.unmodifiableList(new ArrayList<>(extras));',
        '        this.issuedAt = LocalDateTime.now();',
        '    }',
        '',
        '    public String getReservationId() {',
        '        return reservationId;',
        '    }',
        '',
        '    public long getRoomChargeCents() {',
        '        return roomChargeCents;',
        '    }',
        '',
        '    public long getExtraChargeCents() {',
        '        return extraChargeCents;',
        '    }',
        '',
        '    public long getTaxCents() {',
        '        return taxCents;',
        '    }',
        '',
        '    public long getTotalCents() {',
        '        return totalCents;',
        '    }',
        '',
        '    public List<Charge> getExtras() {',
        '        return extras;',
        '    }',
        '',
        '    public LocalDateTime getIssuedAt() {',
        '        return issuedAt;',
        '    }',
        '',
        '    @Override',
        '    public String toString() {',
        '        return "Invoice(reservationId=" + reservationId + ", totalCents=" + totalCents + ")";',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "SearchService.java",
      language: "java",
      content: [
        'import java.time.LocalDate;',
        'import java.util.ArrayList;',
        'import java.util.Collection;',
        'import java.util.EnumMap;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        '',
        'public class SearchService {',
        '    public List<Room> findAvailableRooms(Collection<Room> rooms, Collection<Reservation> reservations, RoomType type, LocalDate checkInDate, LocalDate checkOutDate, int guests) {',
        '        Objects.requireNonNull(rooms, "rooms");',
        '        Objects.requireNonNull(reservations, "reservations");',
        '        Objects.requireNonNull(type, "type");',
        '        Reservation.validateDateRange(checkInDate, checkOutDate);',
        '        if (!type.canHost(guests)) {',
        '            return new ArrayList<>();',
        '        }',
        '',
        '        List<Room> matches = new ArrayList<>();',
        '        for (Room room : rooms) {',
        '            if (room.getType() != type || !room.isBookable()) {',
        '                continue;',
        '            }',
        '            if (isAvailable(room, reservations, checkInDate, checkOutDate)) {',
        '                matches.add(room);',
        '            }',
        '        }',
        '        return matches;',
        '    }',
        '',
        '    public boolean isAvailable(Room room, Collection<Reservation> reservations, LocalDate checkInDate, LocalDate checkOutDate) {',
        '        Objects.requireNonNull(room, "room");',
        '        Objects.requireNonNull(reservations, "reservations");',
        '        Reservation.validateDateRange(checkInDate, checkOutDate);',
        '        if (!room.isBookable()) {',
        '            return false;',
        '        }',
        '        for (Reservation reservation : reservations) {',
        '            if (reservation.getRoom().equals(room) && reservation.overlaps(checkInDate, checkOutDate)) {',
        '                return false;',
        '            }',
        '        }',
        '        return true;',
        '    }',
        '}',
        '',
        'final class HousekeepingObserver implements RoomObserver {',
        '    public void onStatusChanged(Room room, RoomStatus previous, RoomStatus next) {',
        '        if (next == RoomStatus.CLEANING) {',
        '            System.out.println("Housekeeping requested for room " + room.getRoomNumber());',
        '        }',
        '    }',
        '}',
        '',
        'final class AvailabilityObserver implements RoomObserver {',
        '    private final Map<RoomType, Integer> availableByType = new EnumMap<>(RoomType.class);',
        '',
        '    public AvailabilityObserver(Collection<Room> rooms) {',
        '        for (RoomType type : RoomType.values()) {',
        '            availableByType.put(type, 0);',
        '        }',
        '        for (Room room : rooms) {',
        '            if (room.getStatus() == RoomStatus.AVAILABLE) {',
        '                increment(room.getType());',
        '            }',
        '        }',
        '    }',
        '',
        '    public void onStatusChanged(Room room, RoomStatus previous, RoomStatus next) {',
        '        if (previous == RoomStatus.AVAILABLE) {',
        '            decrement(room.getType());',
        '        }',
        '        if (next == RoomStatus.AVAILABLE) {',
        '            increment(room.getType());',
        '        }',
        '    }',
        '',
        '    public int availableCount(RoomType type) {',
        '        return availableByType.get(type);',
        '    }',
        '',
        '    private void increment(RoomType type) {',
        '        availableByType.put(type, availableByType.get(type) + 1);',
        '    }',
        '',
        '    private void decrement(RoomType type) {',
        '        availableByType.put(type, Math.max(0, availableByType.get(type) - 1));',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "HotelService.java",
      language: "java",
      content: [
        'import java.time.LocalDate;',
        'import java.util.Collection;',
        'import java.util.Collections;',
        'import java.util.LinkedHashMap;',
        'import java.util.List;',
        'import java.util.Map;',
        'import java.util.Objects;',
        'import java.util.UUID;',
        'import java.util.ArrayList;',
        '',
        'public class HotelService {',
        '    private final Map<String, Room> rooms = new LinkedHashMap<>();',
        '    private final Map<String, Reservation> reservations = new LinkedHashMap<>();',
        '    private final List<RoomObserver> roomObservers = new ArrayList<>();',
        '    private final SearchService searchService;',
        '    private final PricingStrategy pricingStrategy;',
        '    private final RoomFactory roomFactory;',
        '',
        '    public HotelService(SearchService searchService, PricingStrategy pricingStrategy) {',
        '        this(searchService, pricingStrategy, new StandardRoomFactory());',
        '    }',
        '',
        '    public HotelService(SearchService searchService, PricingStrategy pricingStrategy, RoomFactory roomFactory) {',
        '        this.searchService = Objects.requireNonNull(searchService, "searchService");',
        '        this.pricingStrategy = Objects.requireNonNull(pricingStrategy, "pricingStrategy");',
        '        this.roomFactory = Objects.requireNonNull(roomFactory, "roomFactory");',
        '    }',
        '',
        '    public Room addRoom(String roomNumber, RoomType type, int floor) {',
        '        if (rooms.containsKey(roomNumber)) {',
        '            throw new IllegalArgumentException("Duplicate room number");',
        '        }',
        '        Room room = roomFactory.createRoom(roomNumber, type, floor);',
        '        for (RoomObserver observer : roomObservers) {',
        '            room.addObserver(observer);',
        '        }',
        '        rooms.put(roomNumber, room);',
        '        return room;',
        '    }',
        '',
        '    public void registerRoomObserver(RoomObserver observer) {',
        '        Objects.requireNonNull(observer, "observer");',
        '        roomObservers.add(observer);',
        '        for (Room room : rooms.values()) {',
        '            room.addObserver(observer);',
        '        }',
        '    }',
        '',
        '    public List<Room> search(RoomType type, LocalDate checkInDate, LocalDate checkOutDate, int guests) {',
        '        return searchService.findAvailableRooms(rooms.values(), reservations.values(), type, checkInDate, checkOutDate, guests);',
        '    }',
        '',
        '    public Reservation reserve(String guestName, RoomType type, LocalDate checkInDate, LocalDate checkOutDate, int guests) {',
        '        List<Room> candidates = search(type, checkInDate, checkOutDate, guests);',
        '        if (candidates.isEmpty()) {',
        '            throw new IllegalStateException("No available room for requested stay");',
        '        }',
        '        Room room = candidates.get(0);',
        '        Reservation reservation = new Reservation(UUID.randomUUID().toString(), guestName, room, checkInDate, checkOutDate, guests);',
        '        reservations.put(reservation.getId(), reservation);',
        '        return reservation;',
        '    }',
        '',
        '    public void checkIn(String reservationId) {',
        '        getReservation(reservationId).checkIn();',
        '    }',
        '',
        '    public Invoice checkOut(String reservationId, List<Charge> extras) {',
        '        Reservation reservation = getReservation(reservationId);',
        '        reservation.checkOut();',
        '        return pricingStrategy.createInvoice(reservation, extras == null ? Collections.emptyList() : extras);',
        '    }',
        '',
        '    public void cancel(String reservationId) {',
        '        getReservation(reservationId).cancel();',
        '    }',
        '',
        '    public void markNoShow(String reservationId) {',
        '        getReservation(reservationId).markNoShow();',
        '    }',
        '',
        '    public void markRoomAvailable(String roomNumber) {',
        '        getRoom(roomNumber).markAvailable();',
        '    }',
        '',
        '    public Collection<Room> rooms() {',
        '        return Collections.unmodifiableCollection(rooms.values());',
        '    }',
        '',
        '    private Reservation getReservation(String reservationId) {',
        '        Reservation reservation = reservations.get(reservationId);',
        '        if (reservation == null) {',
        '            throw new IllegalArgumentException("Unknown reservation id");',
        '        }',
        '        return reservation;',
        '    }',
        '',
        '    private Room getRoom(String roomNumber) {',
        '        Room room = rooms.get(roomNumber);',
        '        if (room == null) {',
        '            throw new IllegalArgumentException("Unknown room number");',
        '        }',
        '        return room;',
        '    }',
        '}',
        '',
        'interface RoomFactory {',
        '    Room createRoom(String roomNumber, RoomType type, int floor);',
        '}',
        '',
        'final class StandardRoomFactory implements RoomFactory {',
        '    public Room createRoom(String roomNumber, RoomType type, int floor) {',
        '        return new Room(roomNumber, type, floor);',
        '    }',
        '}',
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        'import java.time.LocalDate;',
        'import java.util.Arrays;',
        'import java.util.List;',
        '',
        'public class Main {',
        '    public static void main(String[] args) {',
        '        HotelService hotel = new HotelService(new SearchService(), new StandardPricingStrategy(1_800));',
        '        hotel.addRoom("201", RoomType.DELUXE, 2);',
        '        hotel.addRoom("202", RoomType.DELUXE, 2);',
        '        hotel.addRoom("501", RoomType.SUITE, 5);',
        '',
        '        AvailabilityObserver board = new AvailabilityObserver(hotel.rooms());',
        '        hotel.registerRoomObserver(board);',
        '        hotel.registerRoomObserver(new HousekeepingObserver());',
        '',
        '        LocalDate checkIn = LocalDate.of(2026, 8, 1);',
        '        LocalDate checkOut = LocalDate.of(2026, 8, 4);',
        '',
        '        List<Room> beforeBooking = hotel.search(RoomType.DELUXE, checkIn, checkOut, 2);',
        '        System.out.println("Available deluxe rooms before booking: " + beforeBooking.size());',
        '',
        '        Reservation reservation = hotel.reserve("Ava Patel", RoomType.DELUXE, checkIn, checkOut, 2);',
        '        System.out.println("Reservation " + reservation.getId() + " is " + reservation.getStateName());',
        '',
        '        List<Room> overlapping = hotel.search(RoomType.DELUXE, LocalDate.of(2026, 8, 3), LocalDate.of(2026, 8, 5), 2);',
        '        System.out.println("Available deluxe rooms for overlapping dates: " + overlapping.size());',
        '',
        '        hotel.checkIn(reservation.getId());',
        '        Invoice invoice = hotel.checkOut(reservation.getId(), Arrays.asList(new Charge("Mini bar", 2_500)));',
        '        System.out.println(invoice);',
        '        System.out.println("Board count while room is cleaning: " + board.availableCount(RoomType.DELUXE));',
        '',
        '        hotel.markRoomAvailable(reservation.getRoom().getRoomNumber());',
        '        System.out.println("Board count after housekeeping: " + board.availableCount(RoomType.DELUXE));',
        '    }',
        '}',
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Room",
      detailMD:
        "Physical inventory unit. It stores room number, type, floor, and operational status, and fires observer callbacks when status changes. Search rejects rooms that are Cleaning or under Maintenance.",
    },
    {
      className: "RoomType",
      detailMD:
        "Enum for stable commercial configuration: base nightly rate and maximum guest capacity. This avoids scattering rates and capacity checks across search and billing.",
    },
    {
      className: "Reservation",
      detailMD:
        "Reservation owns the date range, guest binding, selected room, and state. Its **overlaps** method is the single source of truth for date-range availability.",
    },
    {
      className: "PricingStrategy",
      detailMD:
        "Pricing seam plus the default implementation and invoice data model. **StandardPricingStrategy** multiplies nights by room rate, adds extras, applies tax, and returns an immutable **Invoice**.",
    },
    {
      className: "SearchService",
      detailMD:
        "Availability query service. It filters by room type, capacity, status, and active overlapping reservations. It also contains sample observers for housekeeping and availability counts.",
    },
    {
      className: "HotelService",
      detailMD:
        "Application boundary. It stores rooms and reservations, uses the factory to add rooms, delegates search to **SearchService**, delegates billing to **PricingStrategy**, and triggers reservation lifecycle methods.",
    },
    {
      className: "Main",
      detailMD:
        "Small executable scenario showing search, reservation creation, overlap behavior, check-in, check-out, invoice generation, and housekeeping-driven availability restoration.",
    },
  ],

  dryRun: {
    inputMD:
      "Rooms: 201 Deluxe, 202 Deluxe. Existing none. Guest asks for Deluxe, 2 guests, Aug 1 to Aug 4. Then another guest searches Aug 3 to Aug 5 and Aug 4 to Aug 6.",
    columns: ["Step", "Request", "Overlap check", "Room status", "Reservation state", "Outcome"],
    rows: [
      ["1", "Search Deluxe Aug 1 to Aug 4", "No active reservations", "201 Available, 202 Available", "None", "Both rooms returned"],
      ["2", "Reserve Ava in 201 Aug 1 to Aug 4", "No overlap, create R1", "201 Available", "R1 Reserved", "201 is blocked for overlapping future stays"],
      ["3", "Search Deluxe Aug 3 to Aug 5", "Aug 3 < Aug 4 and Aug 5 > Aug 1", "201 Available, 202 Available", "R1 Reserved", "201 rejected, 202 returned"],
      ["4", "Search Deluxe Aug 4 to Aug 6", "Start equals R1 check-out, so no overlap", "201 Available, 202 Available", "R1 Reserved", "201 and 202 returned"],
      ["5", "Check in and check out R1", "Historical reservation no longer blocks", "201 Cleaning", "R1 CheckedOut", "Invoice = 3 nights plus extras plus tax"],
      ["6", "Housekeeping marks 201 available", "No active overlap", "201 Available", "R1 CheckedOut", "201 can appear in future search again"],
    ],
    narrativeMD:
      "The important row is step 3: even though room 201 is operationally Available before check-in, the future reservation blocks an overlapping request. Step 4 proves adjacent stays are legal under half-open intervals.",
  },

  complexity: [
    {
      operation: "search available rooms",
      time: "O(R × B)",
      space: "O(R)",
      note: "R rooms and B reservations in the in-memory implementation. Each room may scan reservations for overlap.",
    },
    {
      operation: "reserve",
      time: "O(R × B)",
      space: "O(1)",
      note: "Delegates to search, then creates one reservation and stores it by id.",
    },
    {
      operation: "checkIn / cancel / markNoShow",
      time: "O(1)",
      space: "O(1)",
      note: "Map lookup plus a state transition; observer notifications are proportional to subscribers on room status changes.",
    },
    {
      operation: "checkOut and invoice",
      time: "O(E + O)",
      space: "O(E)",
      note: "E extra charges and O room observers. Night count is constant-time date arithmetic.",
    },
    {
      operation: "single overlap check",
      time: "O(1)",
      space: "O(1)",
      note: "Two date comparisons after validating the range.",
    },
  ],
  complexityNotesMD:
    "The scan is acceptable for an interview model. Production search would index by room type and date, or precompute nightly inventory buckets, but the same half-open overlap rule remains the correctness contract.",

  extensibility: [
    {
      label: "Seasonal and channel pricing",
      detailMD:
        "Add another **PricingStrategy** that reads rate calendars, promo codes, loyalty tiers, or OTA channel markups. **HotelService.checkOut** does not change.",
    },
    {
      label: "Room features",
      detailMD:
        "Add amenities such as ocean view, smoking preference, accessibility, or connecting rooms as filters on **Room** or as a separate **RoomFeature** set used by **SearchService**.",
    },
    {
      label: "Room-type inventory pools",
      detailMD:
        "Instead of binding a physical room at booking time, reserve capacity at room-type level and assign a room on check-in. This improves operations but shifts overlap checks to inventory counters.",
    },
    {
      label: "External integrations",
      detailMD:
        "Observers or adapters can publish availability updates to channel managers, send housekeeping tasks, or push invoices to accounting without changing the domain classes.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Nightly inventory buckets",
      detailMD:
        "Track remaining count per room type per night, decrementing all nights in the requested range when a reservation is created.",
      tradeoffsMD:
        "Search becomes fast for type-level availability, but assigning a specific room later needs a second placement step and careful rollback across multiple nights.",
    },
    {
      name: "Repository and specification pattern",
      detailMD:
        "Move room and reservation lookup into repositories, and express filters as specifications such as **RoomTypeMatches** and **NoOverlapForRange**.",
      tradeoffsMD:
        "Better for persistence-heavy systems, but verbose for a machine-coding interview unless the interviewer asks for database boundaries.",
    },
    {
      name: "Workflow engine for reservation lifecycle",
      detailMD:
        "Represent lifecycle transitions in a configurable workflow table instead of state classes.",
      tradeoffsMD:
        "Useful for enterprise policy changes, but the State pattern is clearer and safer for an interview-sized domain model.",
    },
  ],

  commonMistakes: [
    "Checking only **RoomStatus.Available** and forgetting future active reservations, which allows double booking.",
    "Using inclusive end dates so a guest checking out on Aug 4 blocks another guest checking in on Aug 4.",
    "Letting **Cancelled** or **NoShow** reservations continue to block search results.",
    "Putting lifecycle transitions in nested service conditionals instead of a State pattern, making illegal transitions easy to miss.",
    "Hard-coding room rates and tax in **HotelService** rather than a pricing strategy.",
    "Marking a room Available immediately on check-out and skipping the Cleaning state and housekeeping workflow.",
    "Creating an invoice before the reservation successfully transitions to **CheckedOut**.",
  ],

  followUps: [
    {
      question: "How would you prevent two users from reserving the last room concurrently?",
      answerMD:
        "Wrap search plus reservation creation in a transaction or a lock on the room/date inventory. In a database design, use a uniqueness constraint or row locks over room and date-range inventory rows.",
    },
    {
      question: "How would you support modifying reservation dates?",
      answerMD:
        "Validate the new range with the same overlap predicate while excluding the reservation being modified. Apply the change only if the new range has no active conflict.",
    },
    {
      question: "How do you price weekend or holiday rates?",
      answerMD:
        "Implement a pricing strategy that iterates each night, looks up a rate calendar for that date and room type, then adds extras and tax before returning an invoice.",
    },
    {
      question: "Where should payment processing live?",
      answerMD:
        "Outside the core model. The hotel domain creates invoices; a payment adapter charges the guest and records payment status against the invoice or reservation.",
    },
    {
      question: "How would you support overbooking?",
      answerMD:
        "Introduce an inventory policy per room type that allows reserved count to exceed physical count by a configured buffer. Keep this out of **Reservation.overlaps** and put it in a higher-level allocation policy.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence and transactions",
      detailMD:
        "Store rooms, reservations, invoices, and state transitions durably. Reservation creation should be transactional with conflict detection to avoid double booking under concurrency.",
    },
    {
      label: "Time zones and hotel calendars",
      detailMD:
        "Hotel stays use local property dates, not arbitrary instants. Keep property time zone and local check-in/check-out rules explicit.",
    },
    {
      label: "Audit trail",
      detailMD:
        "Record who changed a reservation, previous state, next state, invoice inputs, and pricing strategy version. Hospitality disputes often depend on historical policy.",
    },
    {
      label: "Operational reliability",
      detailMD:
        "Housekeeping, channel manager sync, email, and accounting should be asynchronous with retry and idempotency because those integrations fail independently of booking.",
    },
    {
      label: "Search performance",
      detailMD:
        "Large hotels or multi-property systems need indexes by property, room type, and date range. The in-memory scan becomes an indexed availability query or cached inventory calendar.",
    },
  ],

  interviewNotes: [
    "Did the candidate state half-open date ranges and implement the correct overlap condition?",
    "Can they explain which reservation states block inventory and which do not?",
    "Is pricing behind an interface rather than mixed into check-out orchestration?",
    "Do observers represent side effects without coupling housekeeping to the room entity?",
    "Can the design evolve from a single hotel in memory to persisted, concurrent, multi-property inventory?",
  ],

  quiz: [
    {
      question: "Which condition correctly detects overlap for half-open hotel stays?",
      options: [
        "requestStart < existingEnd && requestEnd > existingStart",
        "requestStart <= existingEnd && requestEnd >= existingStart",
        "requestStart == existingStart only",
        "requestEnd < existingStart only",
      ],
      answerIndex: 0,
      explanationMD:
        "Half-open intervals allow back-to-back stays. The strict comparisons reject only ranges that share at least one occupied night.",
    },
    {
      question: "Which reservation states should normally block inventory?",
      options: [
        "Reserved and CheckedIn",
        "Cancelled and NoShow",
        "CheckedOut only",
        "All historical states forever",
      ],
      answerIndex: 0,
      explanationMD:
        "Reserved and CheckedIn represent active commitments to the room. Cancelled, NoShow, and CheckedOut are history and should not block future availability.",
    },
    {
      question: "Why is pricing modeled as **PricingStrategy**?",
      options: [
        "To make check-out independent of the rate policy",
        "To avoid storing room type",
        "To make overlap checks faster",
        "To replace the reservation state machine",
      ],
      answerIndex: 0,
      explanationMD:
        "The Strategy pattern lets seasonal, promotional, or channel-specific pricing vary without rewriting the check-out flow.",
    },
    {
      question: "What should happen when a checked-in guest checks out?",
      options: [
        "Reservation becomes CheckedOut, room becomes Cleaning, and an invoice is produced",
        "Reservation becomes Cancelled and room stays Occupied",
        "Room immediately becomes Available before billing",
        "The date range is deleted from history",
      ],
      answerIndex: 0,
      explanationMD:
        "Check-out is a lifecycle transition plus an operational status change. The room should wait for housekeeping before returning to search.",
    },
    {
      question: "What does the Observer pattern decouple in this design?",
      options: [
        "Room status changes from housekeeping and availability-board reactions",
        "Room type from nightly rate",
        "Invoice from extra charges",
        "Guest name from reservation id",
      ],
      answerIndex: 0,
      explanationMD:
        "Observers let secondary workflows react to room status changes without those workflows being hard-coded in **Room**.",
    },
  ],

  practiceVariants: [
    {
      title: "Add rate calendars",
      detailMD:
        "Implement a pricing strategy that charges different rates per night based on weekday, weekend, holiday, and seasonal demand.",
      difficulty: "Intermediate",
    },
    {
      title: "Support reservation modification",
      detailMD:
        "Allow changing dates, room type, and guest count while preventing overlap with other active reservations for the same room.",
      difficulty: "Intermediate",
    },
    {
      title: "Multi-property search",
      detailMD:
        "Add Hotel or Property as a top-level aggregate and search availability across city, property, room type, and date range.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the date interval model for hotel stays?",
      back: "Half-open: check-in inclusive, check-out exclusive. This allows a new guest to check in on the same date another guest checks out.",
    },
    {
      front: "What is the overlap predicate?",
      back: "**requestStart < existingEnd && requestEnd > existingStart** for active reservations on the same room.",
    },
    {
      front: "Which pattern models reservation lifecycle?",
      back: "State, with **Reserved**, **CheckedIn**, **CheckedOut**, **Cancelled**, and **NoShow** concrete states.",
    },
    {
      front: "Which pattern makes pricing extensible?",
      back: "Strategy, through **PricingStrategy.createInvoice**.",
    },
    {
      front: "What should happen to room status after check-out?",
      back: "Move to **Cleaning** and notify observers; mark **Available** only after housekeeping completes.",
    },
    {
      front: "Why is a room factory useful?",
      back: "It centralizes room creation and keeps validation or future room subclasses out of service orchestration.",
    },
  ],

  cheatSheetMD: [
    "**Core entities:** Room, RoomType, Reservation, ReservationState, SearchService, PricingStrategy, Invoice, HotelService, RoomObserver.",
    "",
    "**Overlap rule:** use half-open stays. A request conflicts when **requestStart < existingEnd && requestEnd > existingStart** for the same room and an active reservation.",
    "",
    "**States:** Reserved can check in, cancel, or no-show. CheckedIn can check out. CheckedOut, Cancelled, and NoShow are terminal and do not block inventory.",
    "",
    "**Patterns:** State for reservation lifecycle, Strategy for pricing, Factory Method for room creation, Observer for housekeeping and availability updates.",
    "",
    "**Flow:** search rooms → reject overlapping active reservations → create Reserved reservation → check in marks room Occupied → check out marks room Cleaning and creates invoice → housekeeping marks Available.",
    "",
    "**Complexity:** simple search is O(R×B); overlap check is O(1); check-in and cancellation are O(1); check-out is O(extras + observers).",
  ].join("\n"),

  references: [
    {
      title: "Head First Design Patterns (State, Strategy, Observer, Factory)",
      kind: "Book",
      author: "Freeman & Robson",
    },
    {
      title: "Martin Fowler — Temporal Patterns",
      kind: "Blog",
      url: "https://martinfowler.com/eaaDev/timeNarrative.html",
      author: "Martin Fowler",
    },
    {
      title: "Oracle Java Docs — LocalDate",
      kind: "Docs",
      url: "https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html",
      author: "Oracle",
    },
  ],

  relatedProblems: [
    { slug: "movie-booking", note: "Similar scarce-inventory booking problem with stronger concurrency on seats." },
    { slug: "airline-reservation", note: "Another reservation lifecycle with inventory, pricing, and cancellation policies." },
    { slug: "library-management", note: "Shares inventory availability and lifecycle transitions, but with loans instead of room stays." },
  ],
};
