import type { LLDProblemContent } from "../types";

export const inventoryManagement: LLDProblemContent = {
  slug: "inventory-management",

  statementMD: [
    "Design the object model for an **Inventory Management System** that tracks",
    "products across warehouses, records on-hand and reserved quantities, and",
    "protects stock while orders are being checked out.",
    "",
    "The core interview challenge is the correctness boundary: two order threads",
    "must not both decrement the same available units. The design should also send",
    "low-stock notifications exactly when a product crosses its threshold and keep",
    "replenishment policy pluggable instead of hard-coded.",
  ].join("\n"),

  businessContextMD: [
    "Inventory systems sit behind shopping carts, food delivery, warehouses, and",
    "marketplaces. A small race can oversell a SKU, break fulfillment promises, and",
    "create expensive support issues. Interviewers use this problem to evaluate",
    "whether you can model domain invariants, isolate persistence with a Repository,",
    "apply Observer for threshold events, and use Strategy for reorder decisions.",
  ].join("\n"),

  functionalRequirements: [
    "Register products with SKU, name, and a low-stock threshold.",
    "Register warehouses and keep stock independently per SKU and warehouse.",
    "Add physical stock to a warehouse after receiving inventory.",
    "Reserve available stock for an order without overselling.",
    "Release previously reserved stock when an order is cancelled or payment fails.",
    "Ship reserved stock by decrementing on-hand inventory after fulfillment.",
    "Notify observers when available stock crosses below the product threshold.",
    "Generate replenishment recommendations through a pluggable strategy.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Concurrency safety",
      detailMD:
        "The check of available quantity and the reserved or shipped mutation must happen under one lock per stock item.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New reorder policies, alert sinks, and repository implementations should be additive classes, not edits to reservation flow.",
    },
    {
      label: "Consistency of invariants",
      detailMD:
        "**reserved** must never exceed **onHand**, and **available = onHand - reserved** must never be negative.",
    },
    {
      label: "Low latency hot path",
      detailMD:
        "Reserve and release should be O(1) for a known SKU and warehouse, with synchronization scoped to that stock item.",
    },
    {
      label: "Auditable operations",
      detailMD:
        "Production implementations should attach order ids, actor ids, and timestamps to stock movements for reconciliation.",
    },
  ],

  requirementClarification: [
    {
      question: "Is stock tracked globally or per warehouse?",
      answerMD:
        "Track stock per **SKU + warehouse**. A product can be available in one warehouse and low in another, so the stock item is the aggregate for that pair.",
    },
    {
      question: "What is the difference between reserve, release, and ship?",
      answerMD:
        "**Reserve** moves units from available to reserved for an order. **Release** returns reserved units to available. **Ship** consumes reserved units by decrementing physical on-hand stock.",
    },
    {
      question: "When should low-stock observers be notified?",
      answerMD:
        "Notify when available stock crosses from at or above the threshold to below it. This prevents repeated alerts for every later operation while the SKU is already low.",
    },
    {
      question: "Do we need purchase orders or supplier integration?",
      answerMD:
        "Not in the base design. The system returns a **ReorderRecommendation** from a strategy; a supplier adapter can consume that recommendation later.",
    },
    {
      question: "Is persistence required for the interview implementation?",
      answerMD:
        "Use an in-memory Repository for clarity, but keep the service dependent on the Repository interface so SQL, Redis, or event-sourced storage can replace it.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Product {",
    "        -String sku",
    "        -String name",
    "        -int lowStockThreshold",
    "        +getSku() String",
    "        +getLowStockThreshold() int",
    "    }",
    "    class Warehouse {",
    "        -String id",
    "        -String name",
    "        +getId() String",
    "    }",
    "    class StockItem {",
    "        -Product product",
    "        -Warehouse warehouse",
    "        -int onHand",
    "        -int reserved",
    "        -ReentrantLock lock",
    "        +reserve(int) ReservationResult",
    "        +release(int) StockChange",
    "        +shipReserved(int) StockChange",
    "        +addStock(int) StockChange",
    "    }",
    "    class StockSnapshot {",
    "        -int onHand",
    "        -int reserved",
    "        +getAvailable() int",
    "        +isLowStock() boolean",
    "    }",
    "    class InventoryService {",
    "        -InventoryRepository repository",
    "        -ReplenishmentStrategy replenishmentStrategy",
    "        -List~InventoryObserver~ observers",
    "        +getInstance() InventoryService",
    "        +reserveStock(String,String,String,int) ReservationResult",
    "        +releaseStock(String,String,String,int) StockSnapshot",
    "        +shipReserved(String,String,String,int) StockSnapshot",
    "    }",
    "    class InventoryRepository {",
    "        <<interface>>",
    "        +getOrCreateStockItem(Product, Warehouse) StockItem",
    "        +findStockItem(String, String) Optional~StockItem~",
    "    }",
    "    class InMemoryInventoryRepository",
    "    class InventoryObserver {",
    "        <<interface>>",
    "        +onLowStock(StockSnapshot, ReorderRecommendation) void",
    "    }",
    "    class ReplenishmentStrategy {",
    "        <<interface>>",
    "        +recommend(StockSnapshot) ReorderRecommendation",
    "    }",
    "    class FixedQuantityReplenishmentStrategy",
    "    Product <-- StockItem",
    "    Warehouse <-- StockItem",
    "    StockItem --> StockSnapshot",
    "    InventoryService --> InventoryRepository",
    "    InventoryService --> ReplenishmentStrategy",
    "    InventoryService --> InventoryObserver",
    "    InventoryRepository <|.. InMemoryInventoryRepository",
    "    ReplenishmentStrategy <|.. FixedQuantityReplenishmentStrategy",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service is the facade and Singleton entry point. It delegates persistence to the Repository, stock invariants to **StockItem**, alert delivery to observers, and reorder quantity choice to a Strategy.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor OrderSvc",
    "    participant Inv as InventoryService",
    "    participant Repo as InventoryRepository",
    "    participant Item as StockItem",
    "    participant Strat as ReplenishmentStrategy",
    "    participant Obs as InventoryObserver",
    "    OrderSvc->>Inv: reserveStock(orderId, sku, warehouseId, quantity)",
    "    Inv->>Repo: findStockItem(sku, warehouseId)",
    "    Repo-->>Inv: StockItem",
    "    Inv->>Item: reserve(quantity)",
    "    Note over Item: lock protects available check and reserved update",
    "    Item-->>Inv: ReservationResult(before, after)",
    "    alt threshold crossed",
    "        Inv->>Strat: recommend(after)",
    "        Strat-->>Inv: ReorderRecommendation",
    "        Inv->>Obs: onLowStock(after, recommendation)",
    "    end",
    "    Inv-->>OrderSvc: reservation result",
    "    OrderSvc->>Inv: shipReserved(orderId, sku, warehouseId, quantity)",
    "    Inv->>Item: shipReserved(quantity)",
    "    Note over Item: reserved and onHand are decremented together",
    "    Item-->>Inv: StockChange",
    "    Inv-->>OrderSvc: updated snapshot",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Reservation is the critical path: the item lock makes check-then-reserve atomic, and the service raises Observer notifications only after it has a before and after snapshot.",

  entities: [
    {
      name: "Product",
      responsibilityMD:
        "Immutable SKU metadata: identifier, display name, and the low-stock threshold used by alerting and replenishment.",
      attributes: ["sku", "name", "lowStockThreshold"],
    },
    {
      name: "Warehouse",
      responsibilityMD:
        "Immutable location metadata. It scopes inventory so the same SKU can have separate availability in different facilities.",
      attributes: ["id", "name"],
    },
    {
      name: "StockItem",
      responsibilityMD:
        "Aggregate for one **Product** in one **Warehouse**. Owns **onHand**, **reserved**, and the lock that protects every mutation.",
      attributes: ["product", "warehouse", "onHand", "reserved", "lock"],
    },
    {
      name: "InventoryService",
      responsibilityMD:
        "Application facade. Validates requests, loads stock items from the Repository, coordinates reserve, release, and ship operations, and triggers low-stock observers.",
      attributes: ["repository", "replenishmentStrategy", "observers"],
    },
    {
      name: "InventoryRepository",
      responsibilityMD:
        "Persistence seam for products, warehouses, and stock items. The sample uses an in-memory implementation; production can replace it with durable storage.",
      attributes: ["products", "warehouses", "stockItems"],
    },
    {
      name: "ReplenishmentStrategy",
      responsibilityMD:
        "Policy interface that decides whether and how many units to reorder when stock becomes low.",
      attributes: ["recommend(snapshot)"],
    },
    {
      name: "InventoryObserver",
      responsibilityMD:
        "Observer interface for low-stock events. Email, Slack, purchase-order creation, and metrics can subscribe independently.",
      attributes: ["onLowStock(snapshot, recommendation)"],
    },
  ],

  patternsUsed: [
    {
      name: "Observer",
      whyMD:
        "**InventoryObserver** decouples stock changes from alert delivery. The service publishes a low-stock event and does not care whether the subscriber sends email, updates metrics, or creates a purchase order.",
    },
    {
      name: "Strategy",
      whyMD:
        "**ReplenishmentStrategy** keeps reorder logic pluggable. Fixed quantity, top-up-to-target, supplier lead-time, and demand-forecast policies all implement the same method.",
    },
    {
      name: "Repository",
      whyMD:
        "**InventoryRepository** hides storage details from the service. Reservation logic depends on an interface while the demo uses **InMemoryInventoryRepository**.",
    },
    {
      name: "Singleton",
      whyMD:
        "**InventoryService.getInstance** gives small applications one shared inventory facade. The design still exposes an isolated factory for tests and demos that need fresh state.",
    },
  ],

  designSteps: [
    {
      title: "Model stock at SKU and warehouse granularity",
      detailMD:
        "Use **StockItem** as the aggregate root for one product in one warehouse. Global product state is not enough because reservations and thresholds are location-specific.",
    },
    {
      title: "Represent availability as a derived value",
      detailMD:
        "Store **onHand** and **reserved**; compute available stock instead of storing it separately. That removes a third value that can drift out of sync.",
      code: [
        "public int getAvailable() {",
        "    return onHand - reserved;",
        "}",
      ].join("\n"),
    },
    {
      title: "Make reserve an atomic check-then-update",
      detailMD:
        "The race is between checking available units and increasing reserved units. Put both operations under the same stock-item lock.",
      code: [
        "lock.lock();",
        "try {",
        "    if (availableLocked() < quantity) {",
        "        return ReservationResult.rejected(snapshotLocked(), \"Not enough stock\");",
        "    }",
        "    reserved += quantity;",
        "    return ReservationResult.accepted(before, snapshotLocked());",
        "} finally {",
        "    lock.unlock();",
        "}",
      ].join("\n"),
    },
    {
      title: "Separate reserve, release, and ship",
      detailMD:
        "**Reserve** protects stock for checkout, **release** cancels the hold, and **ship** decrements physical inventory after fulfillment. Keeping these verbs separate prevents order-state ambiguity.",
    },
    {
      title: "Notify only on threshold crossing",
      detailMD:
        "Compare before and after snapshots. Observers should hear about a transition into low stock, not every operation while already low.",
      code: [
        "if (before.getAvailable() >= after.getLowStockThreshold()",
        "        && after.getAvailable() < after.getLowStockThreshold()) {",
        "    ReorderRecommendation recommendation = replenishmentStrategy.recommend(after);",
        "    for (InventoryObserver observer : observers) {",
        "        observer.onLowStock(after, recommendation);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Keep policies and storage behind interfaces",
      detailMD:
        "The service depends on **InventoryRepository**, **InventoryObserver**, and **ReplenishmentStrategy**. This keeps persistence, notifications, and reorder math replaceable.",
    },
  ],

  implementation: [
    {
      filename: "Product.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class Product {",
        "    private final String sku;",
        "    private final String name;",
        "    private final int lowStockThreshold;",
        "",
        "    public Product(String sku, String name, int lowStockThreshold) {",
        "        if (lowStockThreshold < 0) {",
        "            throw new IllegalArgumentException(\"lowStockThreshold must be non-negative\");",
        "        }",
        "        this.sku = requireText(sku, \"sku\");",
        "        this.name = requireText(name, \"name\");",
        "        this.lowStockThreshold = lowStockThreshold;",
        "    }",
        "",
        "    public String getSku() {",
        "        return sku;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public int getLowStockThreshold() {",
        "        return lowStockThreshold;",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof Product)) {",
        "            return false;",
        "        }",
        "        Product that = (Product) other;",
        "        return sku.equals(that.sku);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return Objects.hash(sku);",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return sku + \" - \" + name;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Warehouse.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class Warehouse {",
        "    private final String id;",
        "    private final String name;",
        "",
        "    public Warehouse(String id, String name) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof Warehouse)) {",
        "            return false;",
        "        }",
        "        Warehouse that = (Warehouse) other;",
        "        return id.equals(that.id);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return Objects.hash(id);",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return id + \" - \" + name;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "StockItem.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "import java.util.concurrent.locks.ReentrantLock;",
        "",
        "public final class StockItem {",
        "    private final Product product;",
        "    private final Warehouse warehouse;",
        "    private final ReentrantLock lock = new ReentrantLock();",
        "    private int onHand;",
        "    private int reserved;",
        "",
        "    public StockItem(Product product, Warehouse warehouse, int openingStock) {",
        "        if (openingStock < 0) {",
        "            throw new IllegalArgumentException(\"openingStock must be non-negative\");",
        "        }",
        "        this.product = Objects.requireNonNull(product, \"product\");",
        "        this.warehouse = Objects.requireNonNull(warehouse, \"warehouse\");",
        "        this.onHand = openingStock;",
        "    }",
        "",
        "    public String getSku() {",
        "        return product.getSku();",
        "    }",
        "",
        "    public String getWarehouseId() {",
        "        return warehouse.getId();",
        "    }",
        "",
        "    public StockSnapshot snapshot() {",
        "        lock.lock();",
        "        try {",
        "            return snapshotLocked();",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    public StockChange addStock(int quantity) {",
        "        requirePositive(quantity, \"quantity\");",
        "        lock.lock();",
        "        try {",
        "            StockSnapshot before = snapshotLocked();",
        "            onHand += quantity;",
        "            return new StockChange(before, snapshotLocked());",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    public ReservationResult reserve(int quantity) {",
        "        requirePositive(quantity, \"quantity\");",
        "        lock.lock();",
        "        try {",
        "            StockSnapshot before = snapshotLocked();",
        "            if (before.getAvailable() < quantity) {",
        "                return ReservationResult.rejected(before, \"Only \" + before.getAvailable() + \" units are available\");",
        "            }",
        "            reserved += quantity;",
        "            return ReservationResult.accepted(before, snapshotLocked());",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    public StockChange release(int quantity) {",
        "        requirePositive(quantity, \"quantity\");",
        "        lock.lock();",
        "        try {",
        "            if (quantity > reserved) {",
        "                throw new IllegalArgumentException(\"Cannot release more than reserved stock\");",
        "            }",
        "            StockSnapshot before = snapshotLocked();",
        "            reserved -= quantity;",
        "            return new StockChange(before, snapshotLocked());",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    public StockChange shipReserved(int quantity) {",
        "        requirePositive(quantity, \"quantity\");",
        "        lock.lock();",
        "        try {",
        "            if (quantity > reserved) {",
        "                throw new IllegalArgumentException(\"Cannot ship more than reserved stock\");",
        "            }",
        "            StockSnapshot before = snapshotLocked();",
        "            reserved -= quantity;",
        "            onHand -= quantity;",
        "            return new StockChange(before, snapshotLocked());",
        "        } finally {",
        "            lock.unlock();",
        "        }",
        "    }",
        "",
        "    private int availableLocked() {",
        "        return onHand - reserved;",
        "    }",
        "",
        "    private StockSnapshot snapshotLocked() {",
        "        return new StockSnapshot(product, warehouse, onHand, reserved);",
        "    }",
        "",
        "    private static void requirePositive(int quantity, String fieldName) {",
        "        if (quantity <= 0) {",
        "            throw new IllegalArgumentException(fieldName + \" must be positive\");",
        "        }",
        "    }",
        "}",
        "",
        "final class StockSnapshot {",
        "    private final Product product;",
        "    private final Warehouse warehouse;",
        "    private final int onHand;",
        "    private final int reserved;",
        "",
        "    StockSnapshot(Product product, Warehouse warehouse, int onHand, int reserved) {",
        "        this.product = product;",
        "        this.warehouse = warehouse;",
        "        this.onHand = onHand;",
        "        this.reserved = reserved;",
        "    }",
        "",
        "    public Product getProduct() {",
        "        return product;",
        "    }",
        "",
        "    public Warehouse getWarehouse() {",
        "        return warehouse;",
        "    }",
        "",
        "    public int getOnHand() {",
        "        return onHand;",
        "    }",
        "",
        "    public int getReserved() {",
        "        return reserved;",
        "    }",
        "",
        "    public int getAvailable() {",
        "        return onHand - reserved;",
        "    }",
        "",
        "    public int getLowStockThreshold() {",
        "        return product.getLowStockThreshold();",
        "    }",
        "",
        "    public boolean isLowStock() {",
        "        return getAvailable() < getLowStockThreshold();",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return product.getSku() + \"@\" + warehouse.getId()",
        "                + \" onHand=\" + onHand",
        "                + \" reserved=\" + reserved",
        "                + \" available=\" + getAvailable();",
        "    }",
        "}",
        "",
        "final class StockChange {",
        "    private final StockSnapshot beforeSnapshot;",
        "    private final StockSnapshot afterSnapshot;",
        "",
        "    StockChange(StockSnapshot beforeSnapshot, StockSnapshot afterSnapshot) {",
        "        this.beforeSnapshot = beforeSnapshot;",
        "        this.afterSnapshot = afterSnapshot;",
        "    }",
        "",
        "    public StockSnapshot getBeforeSnapshot() {",
        "        return beforeSnapshot;",
        "    }",
        "",
        "    public StockSnapshot getAfterSnapshot() {",
        "        return afterSnapshot;",
        "    }",
        "",
        "    public boolean crossedBelowLowStockThreshold() {",
        "        return beforeSnapshot.getAvailable() >= afterSnapshot.getLowStockThreshold()",
        "                && afterSnapshot.getAvailable() < afterSnapshot.getLowStockThreshold();",
        "    }",
        "}",
        "",
        "final class ReservationResult {",
        "    private final boolean success;",
        "    private final StockSnapshot beforeSnapshot;",
        "    private final StockSnapshot afterSnapshot;",
        "    private final String message;",
        "",
        "    private ReservationResult(boolean success, StockSnapshot beforeSnapshot, StockSnapshot afterSnapshot, String message) {",
        "        this.success = success;",
        "        this.beforeSnapshot = beforeSnapshot;",
        "        this.afterSnapshot = afterSnapshot;",
        "        this.message = message;",
        "    }",
        "",
        "    static ReservationResult accepted(StockSnapshot beforeSnapshot, StockSnapshot afterSnapshot) {",
        "        return new ReservationResult(true, beforeSnapshot, afterSnapshot, \"Reserved\");",
        "    }",
        "",
        "    static ReservationResult rejected(StockSnapshot snapshot, String message) {",
        "        return new ReservationResult(false, snapshot, snapshot, message);",
        "    }",
        "",
        "    public boolean isSuccess() {",
        "        return success;",
        "    }",
        "",
        "    public StockSnapshot getBeforeSnapshot() {",
        "        return beforeSnapshot;",
        "    }",
        "",
        "    public StockSnapshot getAfterSnapshot() {",
        "        return afterSnapshot;",
        "    }",
        "",
        "    public String getMessage() {",
        "        return message;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ReplenishmentStrategy.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public interface ReplenishmentStrategy {",
        "    ReorderRecommendation recommend(StockSnapshot snapshot);",
        "",
        "    static ReplenishmentStrategy fixedOrderQuantity(int reorderQuantity) {",
        "        return new FixedQuantityReplenishmentStrategy(reorderQuantity);",
        "    }",
        "",
        "    static ReplenishmentStrategy topUpTo(int targetAvailable) {",
        "        return new TopUpToTargetStrategy(targetAvailable);",
        "    }",
        "}",
        "",
        "final class ReorderRecommendation {",
        "    private final String sku;",
        "    private final String warehouseId;",
        "    private final int quantity;",
        "    private final String reason;",
        "    private final boolean required;",
        "",
        "    private ReorderRecommendation(String sku, String warehouseId, int quantity, String reason, boolean required) {",
        "        this.sku = sku;",
        "        this.warehouseId = warehouseId;",
        "        this.quantity = quantity;",
        "        this.reason = reason;",
        "        this.required = required;",
        "    }",
        "",
        "    static ReorderRecommendation none(StockSnapshot snapshot) {",
        "        return new ReorderRecommendation(",
        "                snapshot.getProduct().getSku(),",
        "                snapshot.getWarehouse().getId(),",
        "                0,",
        "                \"Stock is healthy\",",
        "                false);",
        "    }",
        "",
        "    static ReorderRecommendation order(StockSnapshot snapshot, int quantity, String reason) {",
        "        return new ReorderRecommendation(",
        "                snapshot.getProduct().getSku(),",
        "                snapshot.getWarehouse().getId(),",
        "                quantity,",
        "                reason,",
        "                true);",
        "    }",
        "",
        "    public boolean isRequired() {",
        "        return required;",
        "    }",
        "",
        "    public int getQuantity() {",
        "        return quantity;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        if (!required) {",
        "            return reason;",
        "        }",
        "        return \"Reorder \" + quantity + \" units of \" + sku + \" for \" + warehouseId + \": \" + reason;",
        "    }",
        "}",
        "",
        "final class FixedQuantityReplenishmentStrategy implements ReplenishmentStrategy {",
        "    private final int reorderQuantity;",
        "",
        "    FixedQuantityReplenishmentStrategy(int reorderQuantity) {",
        "        if (reorderQuantity <= 0) {",
        "            throw new IllegalArgumentException(\"reorderQuantity must be positive\");",
        "        }",
        "        this.reorderQuantity = reorderQuantity;",
        "    }",
        "",
        "    @Override",
        "    public ReorderRecommendation recommend(StockSnapshot snapshot) {",
        "        Objects.requireNonNull(snapshot, \"snapshot\");",
        "        if (!snapshot.isLowStock()) {",
        "            return ReorderRecommendation.none(snapshot);",
        "        }",
        "        return ReorderRecommendation.order(snapshot, reorderQuantity, \"Available stock is below threshold\");",
        "    }",
        "}",
        "",
        "final class TopUpToTargetStrategy implements ReplenishmentStrategy {",
        "    private final int targetAvailable;",
        "",
        "    TopUpToTargetStrategy(int targetAvailable) {",
        "        if (targetAvailable <= 0) {",
        "            throw new IllegalArgumentException(\"targetAvailable must be positive\");",
        "        }",
        "        this.targetAvailable = targetAvailable;",
        "    }",
        "",
        "    @Override",
        "    public ReorderRecommendation recommend(StockSnapshot snapshot) {",
        "        Objects.requireNonNull(snapshot, \"snapshot\");",
        "        if (!snapshot.isLowStock()) {",
        "            return ReorderRecommendation.none(snapshot);",
        "        }",
        "        int quantity = Math.max(0, targetAvailable - snapshot.getAvailable());",
        "        if (quantity == 0) {",
        "            return ReorderRecommendation.none(snapshot);",
        "        }",
        "        return ReorderRecommendation.order(snapshot, quantity, \"Top up to target availability\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "InventoryObserver.java",
      language: "java",
      content: [
        "public interface InventoryObserver {",
        "    void onLowStock(StockSnapshot snapshot, ReorderRecommendation recommendation);",
        "}",
        "",
        "final class ConsoleLowStockObserver implements InventoryObserver {",
        "    @Override",
        "    public void onLowStock(StockSnapshot snapshot, ReorderRecommendation recommendation) {",
        "        System.out.println(\"LOW STOCK \" + snapshot);",
        "        System.out.println(\"ACTION \" + recommendation);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "InventoryService.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.HashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "import java.util.concurrent.CopyOnWriteArrayList;",
        "",
        "public final class InventoryService {",
        "    private static final InventoryService INSTANCE = new InventoryService(",
        "            new InMemoryInventoryRepository(),",
        "            ReplenishmentStrategy.fixedOrderQuantity(50));",
        "",
        "    private final InventoryRepository repository;",
        "    private final ReplenishmentStrategy replenishmentStrategy;",
        "    private final List<InventoryObserver> observers = new CopyOnWriteArrayList<>();",
        "",
        "    private InventoryService(InventoryRepository repository, ReplenishmentStrategy replenishmentStrategy) {",
        "        this.repository = Objects.requireNonNull(repository, \"repository\");",
        "        this.replenishmentStrategy = Objects.requireNonNull(replenishmentStrategy, \"replenishmentStrategy\");",
        "    }",
        "",
        "    public static InventoryService getInstance() {",
        "        return INSTANCE;",
        "    }",
        "",
        "    public static InventoryService createIsolated(ReplenishmentStrategy replenishmentStrategy) {",
        "        return new InventoryService(new InMemoryInventoryRepository(), replenishmentStrategy);",
        "    }",
        "",
        "    public void addObserver(InventoryObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public void removeObserver(InventoryObserver observer) {",
        "        observers.remove(observer);",
        "    }",
        "",
        "    public void registerProduct(Product product) {",
        "        repository.saveProduct(Objects.requireNonNull(product, \"product\"));",
        "    }",
        "",
        "    public void registerWarehouse(Warehouse warehouse) {",
        "        repository.saveWarehouse(Objects.requireNonNull(warehouse, \"warehouse\"));",
        "    }",
        "",
        "    public StockSnapshot addStock(String sku, String warehouseId, int quantity) {",
        "        StockItem item = itemFor(sku, warehouseId);",
        "        return item.addStock(quantity).getAfterSnapshot();",
        "    }",
        "",
        "    public ReservationResult reserveStock(String orderId, String sku, String warehouseId, int quantity) {",
        "        requireText(orderId, \"orderId\");",
        "        StockItem item = itemFor(sku, warehouseId);",
        "        ReservationResult result = item.reserve(quantity);",
        "        if (result.isSuccess()) {",
        "            notifyIfLowStock(result.getBeforeSnapshot(), result.getAfterSnapshot());",
        "        }",
        "        return result;",
        "    }",
        "",
        "    public StockSnapshot releaseStock(String orderId, String sku, String warehouseId, int quantity) {",
        "        requireText(orderId, \"orderId\");",
        "        StockItem item = itemFor(sku, warehouseId);",
        "        return item.release(quantity).getAfterSnapshot();",
        "    }",
        "",
        "    public StockSnapshot shipReserved(String orderId, String sku, String warehouseId, int quantity) {",
        "        requireText(orderId, \"orderId\");",
        "        StockItem item = itemFor(sku, warehouseId);",
        "        StockChange change = item.shipReserved(quantity);",
        "        notifyIfLowStock(change.getBeforeSnapshot(), change.getAfterSnapshot());",
        "        return change.getAfterSnapshot();",
        "    }",
        "",
        "    public Optional<StockSnapshot> findStock(String sku, String warehouseId) {",
        "        return repository.findStockItem(sku, warehouseId).map(StockItem::snapshot);",
        "    }",
        "",
        "    public List<StockSnapshot> snapshotAll() {",
        "        List<StockSnapshot> snapshots = new ArrayList<>();",
        "        for (StockItem item : repository.findAllStockItems()) {",
        "            snapshots.add(item.snapshot());",
        "        }",
        "        return snapshots;",
        "    }",
        "",
        "    private StockItem itemFor(String sku, String warehouseId) {",
        "        Product product = repository.getProduct(requireText(sku, \"sku\"));",
        "        Warehouse warehouse = repository.getWarehouse(requireText(warehouseId, \"warehouseId\"));",
        "        return repository.getOrCreateStockItem(product, warehouse);",
        "    }",
        "",
        "    private void notifyIfLowStock(StockSnapshot before, StockSnapshot after) {",
        "        if (before.getAvailable() >= after.getLowStockThreshold()",
        "                && after.getAvailable() < after.getLowStockThreshold()) {",
        "            ReorderRecommendation recommendation = replenishmentStrategy.recommend(after);",
        "            for (InventoryObserver observer : observers) {",
        "                observer.onLowStock(after, recommendation);",
        "            }",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
        "",
        "interface InventoryRepository {",
        "    void saveProduct(Product product);",
        "",
        "    Product getProduct(String sku);",
        "",
        "    void saveWarehouse(Warehouse warehouse);",
        "",
        "    Warehouse getWarehouse(String warehouseId);",
        "",
        "    StockItem getOrCreateStockItem(Product product, Warehouse warehouse);",
        "",
        "    Optional<StockItem> findStockItem(String sku, String warehouseId);",
        "",
        "    List<StockItem> findAllStockItems();",
        "}",
        "",
        "final class InMemoryInventoryRepository implements InventoryRepository {",
        "    private final Map<String, Product> products = new HashMap<>();",
        "    private final Map<String, Warehouse> warehouses = new HashMap<>();",
        "    private final Map<String, StockItem> stockItems = new HashMap<>();",
        "",
        "    @Override",
        "    public synchronized void saveProduct(Product product) {",
        "        products.put(product.getSku(), product);",
        "    }",
        "",
        "    @Override",
        "    public synchronized Product getProduct(String sku) {",
        "        Product product = products.get(sku);",
        "        if (product == null) {",
        "            throw new IllegalArgumentException(\"Unknown SKU \" + sku);",
        "        }",
        "        return product;",
        "    }",
        "",
        "    @Override",
        "    public synchronized void saveWarehouse(Warehouse warehouse) {",
        "        warehouses.put(warehouse.getId(), warehouse);",
        "    }",
        "",
        "    @Override",
        "    public synchronized Warehouse getWarehouse(String warehouseId) {",
        "        Warehouse warehouse = warehouses.get(warehouseId);",
        "        if (warehouse == null) {",
        "            throw new IllegalArgumentException(\"Unknown warehouse \" + warehouseId);",
        "        }",
        "        return warehouse;",
        "    }",
        "",
        "    @Override",
        "    public synchronized StockItem getOrCreateStockItem(Product product, Warehouse warehouse) {",
        "        saveProduct(product);",
        "        saveWarehouse(warehouse);",
        "        String key = key(product.getSku(), warehouse.getId());",
        "        StockItem item = stockItems.get(key);",
        "        if (item == null) {",
        "            item = new StockItem(product, warehouse, 0);",
        "            stockItems.put(key, item);",
        "        }",
        "        return item;",
        "    }",
        "",
        "    @Override",
        "    public synchronized Optional<StockItem> findStockItem(String sku, String warehouseId) {",
        "        return Optional.ofNullable(stockItems.get(key(sku, warehouseId)));",
        "    }",
        "",
        "    @Override",
        "    public synchronized List<StockItem> findAllStockItems() {",
        "        return new ArrayList<>(stockItems.values());",
        "    }",
        "",
        "    private static String key(String sku, String warehouseId) {",
        "        return sku + \"@\" + warehouseId;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) throws InterruptedException {",
        "        InventoryService inventory = InventoryService.createIsolated(",
        "                ReplenishmentStrategy.fixedOrderQuantity(20));",
        "        inventory.addObserver(new ConsoleLowStockObserver());",
        "",
        "        Product book = new Product(\"BOOK-001\", \"Clean Architecture\", 5);",
        "        Warehouse warehouse = new Warehouse(\"WH-BLR\", \"Bengaluru Fulfillment Center\");",
        "        inventory.registerProduct(book);",
        "        inventory.registerWarehouse(warehouse);",
        "        inventory.addStock(\"BOOK-001\", \"WH-BLR\", 10);",
        "",
        "        Runnable reserveSixUnits = () -> {",
        "            String orderId = Thread.currentThread().getName();",
        "            ReservationResult result = inventory.reserveStock(orderId, \"BOOK-001\", \"WH-BLR\", 6);",
        "            System.out.println(orderId + \" -> \" + result.getMessage() + \" | \" + result.getAfterSnapshot());",
        "            if (result.isSuccess()) {",
        "                inventory.shipReserved(orderId, \"BOOK-001\", \"WH-BLR\", 6);",
        "            }",
        "        };",
        "",
        "        Thread first = new Thread(reserveSixUnits, \"ORDER-1\");",
        "        Thread second = new Thread(reserveSixUnits, \"ORDER-2\");",
        "        first.start();",
        "        second.start();",
        "        first.join();",
        "        second.join();",
        "",
        "        System.out.println(\"Final \" + inventory.findStock(\"BOOK-001\", \"WH-BLR\").orElseThrow());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Product",
      detailMD:
        "Immutable SKU definition. Equality is based on **sku**, and **lowStockThreshold** drives alerting and replenishment decisions.",
    },
    {
      className: "Warehouse",
      detailMD:
        "Immutable facility definition. Keeping warehouse identity separate from product identity lets the same SKU have independent stock in each location.",
    },
    {
      className: "StockItem",
      detailMD:
        "The concurrency-safe aggregate. It owns **onHand**, **reserved**, **StockSnapshot**, **StockChange**, and **ReservationResult**; reserve, release, and ship all hold the same ReentrantLock while checking and mutating state.",
    },
    {
      className: "ReplenishmentStrategy",
      detailMD:
        "The reorder policy seam. The file includes fixed-quantity and top-up-to-target strategies plus **ReorderRecommendation**, so the service can ask for a recommendation without knowing the formula.",
    },
    {
      className: "InventoryObserver",
      detailMD:
        "Observer contract for threshold breaches. The console observer is deliberately simple, but email, Slack, metrics, or purchase-order adapters would implement the same method.",
    },
    {
      className: "InventoryService",
      detailMD:
        "Singleton facade and orchestration layer. It registers catalog data, loads stock through **InventoryRepository**, calls **StockItem** for atomic mutations, and notifies observers after threshold crossings.",
    },
    {
      className: "Main",
      detailMD:
        "Executable demo. Two threads each try to reserve six units from ten on-hand units; the stock-item lock allows one reservation and cleanly rejects the other, while the winner triggers a low-stock notification.",
    },
  ],

  dryRun: {
    inputMD:
      "SKU **BOOK-001** in warehouse **WH-BLR** has onHand **10**, reserved **0**, and low-stock threshold **5**. Two order threads each try to reserve **6** units.",
    columns: ["Step", "ORDER-1", "ORDER-2", "onHand", "reserved", "Outcome"],
    rows: [
      ["1", "starts reserve(6)", "starts reserve(6)", "10", "0", "Both requests target the same stock item"],
      ["2", "acquires item lock", "waits for item lock", "10", "0", "ORDER-1 checks available = 10"],
      ["3", "reserved becomes 6", "still waiting", "10", "6", "Available drops to 4, crossing threshold 5"],
      ["4", "observer notified", "acquires item lock", "10", "6", "Strategy recommends reorder before ORDER-2 checks"],
      ["5", "ships reserved 6", "reserve(6) rejected", "4", "0", "Only 4 units remain, so oversell is prevented"],
    ],
    narrativeMD:
      "The important transition is Step 3: available stock moves from 10 to 4 inside the lock, so the second order can only see the committed result and the observer fires once.",
  },

  complexity: [
    {
      operation: "register product or warehouse",
      time: "O(1)",
      space: "O(1)",
      note: "Hash-map insert in the in-memory Repository.",
    },
    {
      operation: "add stock",
      time: "O(1)",
      space: "O(1)",
      note: "Lookup the stock item and update onHand under its lock.",
    },
    {
      operation: "reserve stock",
      time: "O(1 + O)",
      space: "O(1)",
      note: "O observers are notified only when the threshold is crossed; the stock mutation itself is O(1).",
    },
    {
      operation: "release stock",
      time: "O(1)",
      space: "O(1)",
      note: "Decrease reserved quantity under the stock-item lock.",
    },
    {
      operation: "snapshot all stock",
      time: "O(N)",
      space: "O(N)",
      note: "N stock items are copied into immutable snapshots.",
    },
  ],
  complexityNotesMD:
    "The design intentionally locks only one **StockItem** for reserve, release, and ship. That keeps unrelated SKUs and warehouses independent while preserving the invariant for the hot aggregate.",

  extensibility: [
    {
      label: "New replenishment policy",
      detailMD:
        "Implement **ReplenishmentStrategy** for lead-time demand, seasonal buffers, supplier minimum order quantities, or machine-learning forecasts.",
    },
    {
      label: "New notification channel",
      detailMD:
        "Implement **InventoryObserver** for email, Slack, PagerDuty, metrics, or automatic purchase-order creation without editing stock mutation logic.",
    },
    {
      label: "Durable persistence",
      detailMD:
        "Replace **InMemoryInventoryRepository** with a SQL repository that uses row locks or optimistic version checks around the stock item.",
    },
    {
      label: "Multi-warehouse allocation",
      detailMD:
        "Add an allocation strategy that chooses the warehouse based on nearest location, shipping cost, or stock age before calling reserve.",
    },
    {
      label: "Inventory movement ledger",
      detailMD:
        "Record every add, reserve, release, and ship operation as an immutable movement event for audits and reconciliation.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Database row lock as the concurrency boundary",
      detailMD:
        "Instead of an in-memory ReentrantLock, store each stock item in a table and reserve with a transaction that locks the SKU and warehouse row.",
      tradeoffsMD:
        "Works across multiple service instances and survives restarts, but adds database latency and requires careful transaction tuning.",
    },
    {
      name: "Event-sourced inventory ledger",
      detailMD:
        "Append stock movement events and derive current availability from snapshots plus later events.",
      tradeoffsMD:
        "Excellent auditability and replay, but more complex reads and harder real-time reservation guarantees unless projections are strongly consistent.",
    },
    {
      name: "Reservation tokens with expiry",
      detailMD:
        "Create reservation records with expiration times and a sweeper that automatically releases stock after checkout timeouts.",
      tradeoffsMD:
        "Matches e-commerce checkout behavior, but introduces background processing and order-state coordination.",
    },
  ],

  commonMistakes: [
    "Checking available stock and then updating reserved stock in separate unsynchronized steps.",
    "Treating available as a stored field, which can drift from **onHand - reserved**.",
    "Sending a low-stock alert on every reserve while the item is already below threshold.",
    "Hard-coding reorder quantity inside **InventoryService** instead of using Strategy.",
    "Letting the service manipulate maps directly instead of depending on a Repository interface.",
    "Mixing reserved and shipped states so cancelled orders accidentally reduce physical stock.",
    "Using one global lock for every SKU and warehouse, which makes unrelated reservations block each other.",
  ],

  followUps: [
    {
      question: "How would you make this safe across multiple app servers?",
      answerMD:
        "Move the concurrency boundary into the Repository with a database transaction, row lock, or compare-and-swap version field on the stock item.",
    },
    {
      question: "Should low stock be based on on-hand or available stock?",
      answerMD:
        "For order promise accuracy, use **available = onHand - reserved**. A product can have high on-hand inventory but still be unavailable because most units are reserved.",
    },
    {
      question: "How do you prevent abandoned carts from holding stock forever?",
      answerMD:
        "Attach an expiry time to reservations and run a sweeper or scheduled job that releases expired holds through the same **releaseStock** path.",
    },
    {
      question: "How would you support choosing the best warehouse for an order?",
      answerMD:
        "Add a **WarehouseAllocationStrategy** before reservation. It can consider customer location, shipping cost, stock age, and warehouse load, then reserve against the chosen stock item.",
    },
    {
      question: "What happens if an observer fails?",
      answerMD:
        "In production, observer delivery should be isolated through retries or an outbox. The stock mutation should remain committed even if email or Slack delivery fails.",
    },
  ],

  productionConsiderations: [
    {
      label: "Transactions and locking",
      detailMD:
        "Use row-level locks, optimistic versions, or atomic conditional updates so multiple service instances cannot oversell the same SKU and warehouse.",
    },
    {
      label: "Outbox for notifications",
      detailMD:
        "Persist low-stock events in the same transaction as the stock change, then deliver them asynchronously to observers for reliable retries.",
    },
    {
      label: "Idempotency",
      detailMD:
        "Accept an order id and operation id so repeated reserve, release, or ship requests do not double-count after client retries.",
    },
    {
      label: "Audit and reconciliation",
      detailMD:
        "Maintain an inventory movement ledger and reconcile it against warehouse scans, supplier receipts, and shipment confirmations.",
    },
    {
      label: "Metrics",
      detailMD:
        "Track reservation failures, low-stock events, observer latency, reorder recommendation volume, and stock drift by warehouse.",
    },
  ],

  interviewNotes: [
    "Did the candidate identify **SKU + warehouse** as the stock aggregate?",
    "Is the check-then-reserve mutation protected by a single lock or transaction?",
    "Are reserve, release, and ship separate verbs with clear invariants?",
    "Does low-stock alerting fire on threshold crossing rather than every update?",
    "Are Repository, Observer, Strategy, and Singleton used for real seams rather than decoration?",
    "Can the design evolve to multi-instance persistence and reservation expiry?",
  ],

  quiz: [
    {
      question: "Why does **StockItem.reserve** lock around both the availability check and the reserved update?",
      options: [
        "To make logging easier",
        "To ensure two orders cannot both reserve the same available units",
        "To make the Repository unnecessary",
        "To notify observers before state changes",
      ],
      answerIndex: 1,
      explanationMD:
        "The race is a check-then-act race. The lock makes the read of available quantity and the reserved mutation one atomic critical section.",
    },
    {
      question: "Why is available stock computed as **onHand - reserved**?",
      options: [
        "It avoids storing a third mutable value that can become inconsistent",
        "It makes shipping impossible",
        "It removes the need for warehouses",
        "It is required by the Singleton pattern",
      ],
      answerIndex: 0,
      explanationMD:
        "Only **onHand** and **reserved** are source-of-truth values. Available stock is derived so it cannot drift independently.",
    },
    {
      question: "When should **InventoryObserver** subscribers be notified?",
      options: [
        "On every call to snapshotAll",
        "Only when available stock crosses from at or above threshold to below threshold",
        "Before the stock item lock is acquired",
        "Only when stock is added",
      ],
      answerIndex: 1,
      explanationMD:
        "A crossing rule prevents alert spam and captures the meaningful transition into a low-stock state.",
    },
    {
      question: "What does **ReplenishmentStrategy** make easy to change?",
      options: [
        "The SKU identifier format",
        "The number of units to reorder and the policy used to compute it",
        "The Java visibility of classes",
        "The fact that stock is per warehouse",
      ],
      answerIndex: 1,
      explanationMD:
        "Strategy isolates reorder policy from reservation orchestration, so fixed quantity and forecast-based policies can be swapped.",
    },
    {
      question: "What role does **InventoryRepository** play?",
      options: [
        "It sends customer notifications",
        "It hides product, warehouse, and stock storage behind an interface",
        "It computes reorder quantities",
        "It replaces the need for locking",
      ],
      answerIndex: 1,
      explanationMD:
        "The Repository abstracts persistence. The service can use in-memory storage in the demo and durable storage in production.",
    },
  ],

  practiceVariants: [
    {
      title: "Add reservation expiry",
      detailMD:
        "Create reservation records with expiry timestamps and a sweeper that releases expired holds through **releaseStock**.",
      difficulty: "Intermediate",
    },
    {
      title: "Add warehouse allocation strategy",
      detailMD:
        "Choose the best warehouse for an order based on customer location, shipping cost, and current availability before reserving stock.",
      difficulty: "Advanced",
    },
    {
      title: "Add purchase-order generation",
      detailMD:
        "Turn low-stock recommendations into purchase orders through an observer, then track supplier receipts back into **addStock**.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "What is the aggregate root for inventory quantity?",
      back: "**StockItem**, representing one SKU in one warehouse.",
    },
    {
      front: "What invariant prevents overselling?",
      back: "**reserved** must never exceed **onHand**, so **available = onHand - reserved** never goes below zero.",
    },
    {
      front: "Which pattern powers low-stock alerts?",
      back: "Observer — **InventoryObserver** subscribers are called after threshold crossing.",
    },
    {
      front: "Which pattern powers reorder policy?",
      back: "Strategy — **ReplenishmentStrategy** decides whether and how much to reorder.",
    },
    {
      front: "Where should multi-instance concurrency be enforced in production?",
      back: "In the Repository using a database transaction, row lock, or optimistic version check.",
    },
    {
      front: "Why separate reserve and ship?",
      back: "Reserve protects stock during checkout; ship consumes physical stock only after fulfillment is confirmed.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Product, Warehouse, StockItem, InventoryService, InventoryRepository, InventoryObserver, ReplenishmentStrategy.",
    "",
    "**Core invariant:** available stock is derived as **onHand - reserved**; reserve must not let available go negative.",
    "",
    "**Concurrency:** lock one **StockItem** during reserve, release, add, and ship. In production, move the lock to a durable transaction boundary.",
    "",
    "**Patterns:** Observer for low-stock notifications, Strategy for reorder policy, Repository for persistence, Singleton for the shared service facade.",
    "",
    "**Flows:** add stock = increase onHand; reserve = increase reserved; release = decrease reserved; ship = decrease reserved and onHand.",
    "",
    "**Alert rule:** notify only when available crosses from at or above threshold to below threshold, then ask the strategy for a recommendation.",
  ].join("\n"),

  references: [
    {
      title: "Patterns of Enterprise Application Architecture — Repository",
      kind: "Book",
      author: "Martin Fowler",
    },
    {
      title: "Effective Java — Synchronization and concurrency guidance",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — Observer Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/observer",
    },
    {
      title: "Refactoring Guru — Strategy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/strategy",
    },
  ],

  relatedProblems: [
    { slug: "shopping-cart", note: "Inventory reservation usually protects items during cart checkout." },
    { slug: "notification-system", note: "Low-stock alerts become a broader notification delivery problem." },
    { slug: "parking-lot", note: "Another resource-allocation design with concurrency-safe reservation." },
  ],
};
