import type { LLDProblemContent } from "../types";

export const jira: LLDProblemContent = {
  slug: "jira",

  statementMD: [
    "Design the low-level object model for **Jira**, an issue tracker used by software teams to plan work, track execution, and enforce a configurable delivery workflow.",
    "",
    "The core system should model projects, issues of different types, assignees, a backlog, sprints, allowed workflow transitions, and notifications when an issue changes state. The interview focus is the domain model and extension seams, not a full REST API, search engine, or database schema.",
  ].join("\n"),

  businessContextMD: [
    "Jira is an expert-level LLD because it combines several interview themes in one domain: a typed issue model, workflow state machine, sprint planning, assignment, notification fan-out, and policy customization per project.",
    "",
    "A strong design keeps workflow rules configurable instead of hard-coding **if current == Open and next == InProgress** across services. It also leaves room for new issue types such as Epic or Spike without editing every creation path.",
  ].join("\n"),

  functionalRequirements: [
    "Create projects that own a backlog, sprints, and a shared issue collection.",
    "Create Story, Task, and Bug issues through an extensible issue-type factory.",
    "Assign or reassign issues to users by user id.",
    "Keep issues in a backlog until they are moved into a sprint.",
    "Configure workflow states and allowed transitions, such as Open to InProgress to InReview to Done.",
    "Transition an issue only when the current workflow state allows the requested target state.",
    "Notify subscribed observers whenever a transition succeeds.",
    "Expose a ranked backlog view so planning can use a replaceable ordering policy.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Workflow correctness",
      detailMD:
        "Invalid transitions must fail atomically and leave the issue in its original state. The allowed-transition rule belongs to the current state object.",
    },
    {
      label: "Configurability",
      detailMD:
        "A project should be able to assemble states and transitions from configuration. The service should not need a switch statement for every workflow.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Adding an issue type, ranking policy, or notification channel should be additive and local, not a cascade of edits through the service layer.",
    },
    {
      label: "Auditability",
      detailMD:
        "Every transition should produce a transition record with from state, to state, actor, note, and timestamp so production systems can build an audit log.",
    },
    {
      label: "Low latency for planning",
      detailMD:
        "Core operations are in-memory map lookups and list updates. Backlog ranking should be fast enough for interactive sprint planning.",
    },
  ],

  requirementClarification: [
    {
      question: "Do projects have independent workflows?",
      answerMD:
        "For the base design, the service receives one workflow configuration per project. The same model supports many projects by constructing one **IssueService** per project or storing a workflow map per project id.",
    },
    {
      question: "Which issue types are required?",
      answerMD:
        "Support **Story**, **Task**, and **Bug**. The implementation uses **IssueType.create** as the factory method so a new type can define defaults without changing **IssueService**.",
    },
    {
      question: "Is backlog ordering fixed?",
      answerMD:
        "No. Use a **Strategy** for backlog ranking. The sample ranks by priority and last update, but the service accepts any comparator-producing policy.",
    },
    {
      question: "Do notifications need email, Slack, and webhooks?",
      answerMD:
        "The model only needs an observer seam. The sample observer prints to the console, while production observers can send email, Slack messages, webhooks, or mobile pushes.",
    },
    {
      question: "Do we need custom fields and permissions?",
      answerMD:
        "Mention them as production extensions. The core interview path should stay focused on issues, workflow transitions, sprints, assignees, and notification events.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Project {",
    "        -String key",
    "        -String name",
    "        -List~Issue~ backlog",
    "        -Map~String,Sprint~ sprints",
    "        +addToBacklog(Issue) void",
    "        +createSprint(String, String, LocalDate, LocalDate) Sprint",
    "        +moveToSprint(String, String) void",
    "    }",
    "    class Issue {",
    "        -String id",
    "        -IssueType type",
    "        -String title",
    "        -String assignee",
    "        -WorkflowState state",
    "        -Sprint sprint",
    "        +assignTo(String) void",
    "        +transitionTo(WorkflowState) void",
    "    }",
    "    class IssueType {",
    "        <<enumeration>>",
    "        STORY",
    "        TASK",
    "        BUG",
    "        +create(String, String, String, WorkflowState) Issue",
    "    }",
    "    class WorkflowState {",
    "        <<interface>>",
    "        +name() String",
    "        +allowedTargets() Set",
    "        +approveTransition(Issue, WorkflowState, String, String) Transition",
    "    }",
    "    class Transition {",
    "        -String fromState",
    "        -String toState",
    "        -String actor",
    "        -Instant occurredAt",
    "    }",
    "    class Sprint {",
    "        -String id",
    "        -String name",
    "        -List~Issue~ issues",
    "        +addIssue(Issue) void",
    "        +removeIssue(Issue) void",
    "    }",
    "    class IssueService {",
    "        -Project project",
    "        -Map~String,WorkflowState~ states",
    "        -IssueRankingStrategy rankingStrategy",
    "        -List~IssueObserver~ observers",
    "        +createIssue(IssueType, String, String, String) Issue",
    "        +transitionIssue(String, String, String, String) Transition",
    "        +rankedBacklog() List",
    "    }",
    "    class IssueObserver {",
    "        <<interface>>",
    "        +onTransition(Issue, Transition) void",
    "    }",
    "    class IssueRankingStrategy {",
    "        <<interface>>",
    "        +comparator() Comparator",
    "    }",
    "    Project o-- Issue",
    "    Project o-- Sprint",
    "    Sprint o-- Issue",
    "    Issue --> IssueType",
    "    Issue --> WorkflowState",
    "    WorkflowState ..> Transition",
    "    IssueService --> Project",
    "    IssueService --> WorkflowState",
    "    IssueService ..> IssueType",
    "    IssueService o-- IssueObserver",
    "    IssueService ..> IssueRankingStrategy",
    "    IssueObserver ..> Transition",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service orchestrates creation, assignment, planning, and transitions. The current **WorkflowState** owns the transition rule, observers receive transition events, and issue creation is delegated to **IssueType**.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Service as IssueService",
    "    participant Type as IssueType",
    "    participant Issue",
    "    participant State as WorkflowState",
    "    participant Observer as IssueObserver",
    "    User->>Service: createIssue(BUG, BUG-7)",
    "    Service->>Type: create(id, title, reporter, Open)",
    "    Type-->>Service: Issue",
    "    Service-->>User: Issue in Open backlog",
    "    User->>Service: transitionIssue(BUG-7, InProgress)",
    "    Service->>Issue: state()",
    "    Service->>State: approveTransition(issue, InProgress)",
    "    State-->>Service: Transition approved",
    "    Service->>Issue: transitionTo(InProgress)",
    "    Service->>Observer: onTransition(issue, transition)",
    "    Service-->>User: Transition record",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The transition path is deliberately small: find issue, ask the current state to approve, mutate the issue, then notify observers. No workflow rule is hard-coded in the service.",

  entities: [
    {
      name: "Project",
      responsibilityMD:
        "Owns the planning surface for one team: backlog, sprint registry, and movement of issues from backlog into a sprint.",
      attributes: ["key", "name", "backlog", "sprints"],
    },
    {
      name: "Issue",
      responsibilityMD:
        "Represents one unit of work with type, title, reporter, assignee, priority, state, optional sprint, comments, and update timestamp.",
      attributes: ["id", "type", "assignee", "priority", "state", "sprint"],
    },
    {
      name: "IssueType",
      responsibilityMD:
        "Factory enum for issue creation. Story, Task, and Bug choose their default priority while the service stays unaware of type-specific construction.",
      attributes: ["STORY", "TASK", "BUG", "create"],
    },
    {
      name: "WorkflowState",
      responsibilityMD:
        "State interface for configurable workflow steps. Each state knows the names of states it may transition to and approves or rejects a requested transition.",
      attributes: ["name", "allowedTargets", "approveTransition"],
    },
    {
      name: "Transition",
      responsibilityMD:
        "Immutable audit event produced when a workflow change is approved. Carries from state, to state, actor, note, and occurrence time.",
      attributes: ["fromState", "toState", "actor", "note", "occurredAt"],
    },
    {
      name: "Sprint",
      responsibilityMD:
        "Time-boxed planning container. It owns a list of committed issues and updates each issue's sprint pointer when membership changes.",
      attributes: ["id", "name", "startDate", "endDate", "issues"],
    },
    {
      name: "IssueService",
      responsibilityMD:
        "Application facade for the domain. It indexes issues, delegates creation to the factory, delegates transition legality to states, ranks backlog through a strategy, and notifies observers.",
      attributes: ["project", "states", "issues", "rankingStrategy", "observers"],
    },
    {
      name: "IssueObserver",
      responsibilityMD:
        "Observer seam for transition notifications. Production adapters can send email, Slack, webhooks, or analytics events from the same callback.",
      attributes: ["onTransition"],
    },
    {
      name: "IssueRankingStrategy",
      responsibilityMD:
        "Backlog ordering policy. The sample uses priority then update time; teams can inject WSJF, due-date, severity, or manual-rank strategies.",
      attributes: ["comparator"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**WorkflowState** encapsulates the allowed outgoing transitions for each workflow node. **IssueService** asks the current state to approve a target instead of owning a brittle matrix of conditional checks.",
    },
    {
      name: "Strategy",
      whyMD:
        "**IssueRankingStrategy** makes backlog ordering replaceable. Priority-first planning, manual rank, severity, due date, or WSJF can be injected without changing issue creation or transitions.",
    },
    {
      name: "Observer",
      whyMD:
        "**IssueObserver** decouples workflow transitions from notification delivery. The service emits one domain event and observers decide how to notify users or external systems.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**IssueType.create** centralizes Story, Task, and Bug construction. Type-specific defaults live with the type, while **IssueService** simply asks the selected type to create an issue.",
    },
  ],

  designSteps: [
    {
      title: "Make the workflow a set of state objects",
      detailMD:
        "Represent Open, InProgress, InReview, and Done as **WorkflowState** instances. Each state carries the names it can move to, making the workflow configurable from data.",
      code: [
        "Map<String, WorkflowState> states = new LinkedHashMap<>();",
        "states.put(\"Open\", WorkflowState.named(\"Open\", \"InProgress\"));",
        "states.put(\"InProgress\", WorkflowState.named(\"InProgress\", \"InReview\", \"Open\"));",
        "states.put(\"InReview\", WorkflowState.named(\"InReview\", \"Done\", \"InProgress\"));",
        "states.put(\"Done\", WorkflowState.named(\"Done\"));",
      ].join("\n"),
    },
    {
      title: "Keep issue creation behind the type factory",
      detailMD:
        "**IssueService** should not switch on Story, Task, and Bug. The selected **IssueType** creates the issue and applies its default priority.",
      code: [
        "public Issue createIssue(IssueType type, String id, String title, String reporter) {",
        "    WorkflowState open = states.get(\"Open\");",
        "    Issue issue = type.create(id, title, reporter, open);",
        "    issues.put(issue.id(), issue);",
        "    project.addToBacklog(issue);",
        "    return issue;",
        "}",
      ].join("\n"),
    },
    {
      title: "Let the current state approve transitions",
      detailMD:
        "The service fetches the target state, then asks the current state to approve. If the edge is missing, no mutation happens and no notification is sent.",
      code: [
        "WorkflowState target = requireState(targetState);",
        "Transition transition = issue.state().approveTransition(issue, target, actor, note);",
        "issue.transitionTo(target);",
        "notifyObservers(issue, transition);",
      ].join("\n"),
    },
    {
      title: "Model backlog and sprint membership explicitly",
      detailMD:
        "**Project** owns the backlog and the sprint registry. Moving an issue to a sprint removes it from backlog and lets the sprint own the committed issue list.",
    },
    {
      title: "Use observers for transition notifications",
      detailMD:
        "Observers receive the issue plus transition record after a successful state change. This keeps notification channels out of the workflow engine.",
    },
    {
      title: "Make planning policy injectable",
      detailMD:
        "Backlog ranking is a strategy because teams disagree on ordering. The sample strategy sorts by priority then most recently updated.",
    },
  ],

  implementation: [
    {
      filename: "Issue.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public class Issue {",
        "    private final String id;",
        "    private final IssueType type;",
        "    private final String title;",
        "    private final String reporter;",
        "    private final String priority;",
        "    private final List<String> comments = new ArrayList<>();",
        "    private String assignee;",
        "    private WorkflowState state;",
        "    private Sprint sprint;",
        "    private Instant updatedAt;",
        "",
        "    Issue(String id, IssueType type, String title, String reporter, String priority, WorkflowState initialState) {",
        "        this.id = requireText(id, \"id\");",
        "        this.type = Objects.requireNonNull(type, \"type\");",
        "        this.title = requireText(title, \"title\");",
        "        this.reporter = requireText(reporter, \"reporter\");",
        "        this.priority = requireText(priority, \"priority\");",
        "        this.state = Objects.requireNonNull(initialState, \"initialState\");",
        "        this.updatedAt = Instant.now();",
        "    }",
        "",
        "    public String id() { return id; }",
        "",
        "    public IssueType type() { return type; }",
        "",
        "    public String title() { return title; }",
        "",
        "    public String reporter() { return reporter; }",
        "",
        "    public String priority() { return priority; }",
        "",
        "    public String assignee() { return assignee; }",
        "",
        "    public WorkflowState state() { return state; }",
        "",
        "    public Sprint sprint() { return sprint; }",
        "",
        "    public Instant updatedAt() { return updatedAt; }",
        "",
        "    public List<String> comments() { return Collections.unmodifiableList(comments); }",
        "",
        "    public void assignTo(String userId) {",
        "        this.assignee = requireText(userId, \"userId\");",
        "        touch();",
        "    }",
        "",
        "    public void addComment(String comment) {",
        "        comments.add(requireText(comment, \"comment\"));",
        "        touch();",
        "    }",
        "",
        "    public void transitionTo(WorkflowState nextState) {",
        "        this.state = Objects.requireNonNull(nextState, \"nextState\");",
        "        touch();",
        "    }",
        "",
        "    void setSprint(Sprint sprint) {",
        "        this.sprint = sprint;",
        "        touch();",
        "    }",
        "",
        "    private void touch() {",
        "        updatedAt = Instant.now();",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return id + \" [\" + type + \"] \" + title + \" - \" + state.name();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "IssueType.java",
      language: "java",
      content: [
        "public enum IssueType {",
        "    STORY(\"Story\", \"P2\"),",
        "    TASK(\"Task\", \"P3\"),",
        "    BUG(\"Bug\", \"P1\");",
        "",
        "    private final String displayName;",
        "    private final String defaultPriority;",
        "",
        "    IssueType(String displayName, String defaultPriority) {",
        "        this.displayName = displayName;",
        "        this.defaultPriority = defaultPriority;",
        "    }",
        "",
        "    public Issue create(String id, String title, String reporter, WorkflowState initialState) {",
        "        return new Issue(id, this, title, reporter, defaultPriority, initialState);",
        "    }",
        "",
        "    public String displayName() {",
        "        return displayName;",
        "    }",
        "",
        "    public String defaultPriority() {",
        "        return defaultPriority;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "WorkflowState.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.LinkedHashSet;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public interface WorkflowState {",
        "    String name();",
        "",
        "    Set<String> allowedTargets();",
        "",
        "    default boolean canTransitionTo(String targetState) {",
        "        return allowedTargets().contains(targetState);",
        "    }",
        "",
        "    default Transition approveTransition(Issue issue, WorkflowState target, String actor, String note) {",
        "        Objects.requireNonNull(issue, \"issue\");",
        "        Objects.requireNonNull(target, \"target\");",
        "        if (!canTransitionTo(target.name())) {",
        "            throw new IllegalStateException(\"Cannot move \" + issue.id() + \" from \" + name() + \" to \" + target.name());",
        "        }",
        "        return new Transition(name(), target.name(), actor, note);",
        "    }",
        "",
        "    static WorkflowState named(String name, String... allowedTargets) {",
        "        Set<String> targets = new LinkedHashSet<>();",
        "        if (allowedTargets != null) {",
        "            Collections.addAll(targets, allowedTargets);",
        "        }",
        "        return new ConfigurableWorkflowState(name, targets);",
        "    }",
        "}",
        "",
        "final class ConfigurableWorkflowState implements WorkflowState {",
        "    private final String name;",
        "    private final Set<String> allowedTargets;",
        "",
        "    ConfigurableWorkflowState(String name, Set<String> allowedTargets) {",
        "        if (name == null || name.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(\"state name is required\");",
        "        }",
        "        this.name = name;",
        "        this.allowedTargets = Collections.unmodifiableSet(new LinkedHashSet<>(allowedTargets));",
        "    }",
        "",
        "    public String name() {",
        "        return name;",
        "    }",
        "",
        "    public Set<String> allowedTargets() {",
        "        return allowedTargets;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return name;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Transition.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "",
        "public class Transition {",
        "    private final String fromState;",
        "    private final String toState;",
        "    private final String actor;",
        "    private final String note;",
        "    private final Instant occurredAt;",
        "",
        "    public Transition(String fromState, String toState, String actor, String note) {",
        "        this.fromState = requireText(fromState, \"fromState\");",
        "        this.toState = requireText(toState, \"toState\");",
        "        this.actor = requireText(actor, \"actor\");",
        "        this.note = note == null ? \"\" : note;",
        "        this.occurredAt = Instant.now();",
        "    }",
        "",
        "    public String fromState() { return fromState; }",
        "",
        "    public String toState() { return toState; }",
        "",
        "    public String actor() { return actor; }",
        "",
        "    public String note() { return note; }",
        "",
        "    public Instant occurredAt() { return occurredAt; }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return fromState + \" -> \" + toState + \" by \" + actor;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Sprint.java",
      language: "java",
      content: [
        "import java.time.LocalDate;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public class Sprint {",
        "    private final String id;",
        "    private final String name;",
        "    private final LocalDate startDate;",
        "    private final LocalDate endDate;",
        "    private final List<Issue> issues = new ArrayList<>();",
        "",
        "    public Sprint(String id, String name, LocalDate startDate, LocalDate endDate) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "        this.startDate = Objects.requireNonNull(startDate, \"startDate\");",
        "        this.endDate = Objects.requireNonNull(endDate, \"endDate\");",
        "        if (endDate.isBefore(startDate)) {",
        "            throw new IllegalArgumentException(\"endDate cannot be before startDate\");",
        "        }",
        "    }",
        "",
        "    public String id() { return id; }",
        "",
        "    public String name() { return name; }",
        "",
        "    public LocalDate startDate() { return startDate; }",
        "",
        "    public LocalDate endDate() { return endDate; }",
        "",
        "    public List<Issue> issues() {",
        "        return Collections.unmodifiableList(issues);",
        "    }",
        "",
        "    public void addIssue(Issue issue) {",
        "        Objects.requireNonNull(issue, \"issue\");",
        "        if (!issues.contains(issue)) {",
        "            issues.add(issue);",
        "            issue.setSprint(this);",
        "        }",
        "    }",
        "",
        "    public void removeIssue(Issue issue) {",
        "        if (issues.remove(issue)) {",
        "            issue.setSprint(null);",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Project.java",
      language: "java",
      content: [
        "import java.time.LocalDate;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public class Project {",
        "    private final String key;",
        "    private final String name;",
        "    private final List<Issue> backlog = new ArrayList<>();",
        "    private final Map<String, Sprint> sprints = new LinkedHashMap<>();",
        "",
        "    public Project(String key, String name) {",
        "        this.key = requireText(key, \"key\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String key() { return key; }",
        "",
        "    public String name() { return name; }",
        "",
        "    public List<Issue> backlog() {",
        "        return Collections.unmodifiableList(backlog);",
        "    }",
        "",
        "    public Map<String, Sprint> sprints() {",
        "        return Collections.unmodifiableMap(sprints);",
        "    }",
        "",
        "    public void addToBacklog(Issue issue) {",
        "        Objects.requireNonNull(issue, \"issue\");",
        "        if (!backlog.contains(issue)) {",
        "            backlog.add(issue);",
        "            if (issue.sprint() != null) {",
        "                issue.sprint().removeIssue(issue);",
        "            }",
        "        }",
        "    }",
        "",
        "    public Sprint createSprint(String id, String name, LocalDate startDate, LocalDate endDate) {",
        "        if (sprints.containsKey(id)) {",
        "            throw new IllegalArgumentException(\"Sprint already exists: \" + id);",
        "        }",
        "        Sprint sprint = new Sprint(id, name, startDate, endDate);",
        "        sprints.put(id, sprint);",
        "        return sprint;",
        "    }",
        "",
        "    public void moveToSprint(Issue issue, String sprintId) {",
        "        Objects.requireNonNull(issue, \"issue\");",
        "        Sprint sprint = sprints.get(sprintId);",
        "        if (sprint == null) {",
        "            throw new IllegalArgumentException(\"Unknown sprint: \" + sprintId);",
        "        }",
        "        backlog.remove(issue);",
        "        sprint.addIssue(issue);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "IssueService.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Comparator;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public class IssueService {",
        "    private final Project project;",
        "    private final Map<String, WorkflowState> states;",
        "    private final IssueRankingStrategy rankingStrategy;",
        "    private final Map<String, Issue> issues = new LinkedHashMap<>();",
        "    private final List<IssueObserver> observers = new ArrayList<>();",
        "",
        "    public IssueService(Project project, Map<String, WorkflowState> states, IssueRankingStrategy rankingStrategy) {",
        "        this.project = Objects.requireNonNull(project, \"project\");",
        "        this.states = new LinkedHashMap<>(Objects.requireNonNull(states, \"states\"));",
        "        this.rankingStrategy = Objects.requireNonNull(rankingStrategy, \"rankingStrategy\");",
        "        if (!this.states.containsKey(\"Open\")) {",
        "            throw new IllegalArgumentException(\"Workflow must define Open\");",
        "        }",
        "    }",
        "",
        "    public Issue createIssue(IssueType type, String id, String title, String reporter) {",
        "        Objects.requireNonNull(type, \"type\");",
        "        if (issues.containsKey(id)) {",
        "            throw new IllegalArgumentException(\"Issue already exists: \" + id);",
        "        }",
        "        Issue issue = type.create(id, title, reporter, states.get(\"Open\"));",
        "        issues.put(issue.id(), issue);",
        "        project.addToBacklog(issue);",
        "        return issue;",
        "    }",
        "",
        "    public void assignIssue(String issueId, String assignee) {",
        "        requireIssue(issueId).assignTo(assignee);",
        "    }",
        "",
        "    public Transition transitionIssue(String issueId, String targetState, String actor, String note) {",
        "        Issue issue = requireIssue(issueId);",
        "        WorkflowState target = requireState(targetState);",
        "        Transition transition = issue.state().approveTransition(issue, target, actor, note);",
        "        issue.transitionTo(target);",
        "        notifyObservers(issue, transition);",
        "        return transition;",
        "    }",
        "",
        "    public void addObserver(IssueObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public List<Issue> rankedBacklog() {",
        "        List<Issue> copy = new ArrayList<>(project.backlog());",
        "        copy.sort(rankingStrategy.comparator());",
        "        return copy;",
        "    }",
        "",
        "    public Issue issue(String issueId) {",
        "        return requireIssue(issueId);",
        "    }",
        "",
        "    private Issue requireIssue(String issueId) {",
        "        Issue issue = issues.get(issueId);",
        "        if (issue == null) {",
        "            throw new IllegalArgumentException(\"Unknown issue: \" + issueId);",
        "        }",
        "        return issue;",
        "    }",
        "",
        "    private WorkflowState requireState(String stateName) {",
        "        WorkflowState state = states.get(stateName);",
        "        if (state == null) {",
        "            throw new IllegalArgumentException(\"Unknown workflow state: \" + stateName);",
        "        }",
        "        return state;",
        "    }",
        "",
        "    private void notifyObservers(Issue issue, Transition transition) {",
        "        for (IssueObserver observer : observers) {",
        "            observer.onTransition(issue, transition);",
        "        }",
        "    }",
        "",
        "    public interface IssueObserver {",
        "        void onTransition(Issue issue, Transition transition);",
        "    }",
        "",
        "    public interface IssueRankingStrategy {",
        "        Comparator<Issue> comparator();",
        "    }",
        "",
        "    public static class PriorityThenUpdatedStrategy implements IssueRankingStrategy {",
        "        public Comparator<Issue> comparator() {",
        "            return Comparator",
        "                .comparing(Issue::priority)",
        "                .thenComparing(Issue::updatedAt, Comparator.reverseOrder());",
        "        }",
        "    }",
        "",
        "    public static class ConsoleNotificationObserver implements IssueObserver {",
        "        public void onTransition(Issue issue, Transition transition) {",
        "            System.out.println(\"Notify \" + issue.assignee() + \": \" + issue.id() + \" moved \" + transition);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.time.LocalDate;",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Map<String, WorkflowState> workflow = new LinkedHashMap<>();",
        "        workflow.put(\"Open\", WorkflowState.named(\"Open\", \"InProgress\"));",
        "        workflow.put(\"InProgress\", WorkflowState.named(\"InProgress\", \"InReview\", \"Open\"));",
        "        workflow.put(\"InReview\", WorkflowState.named(\"InReview\", \"Done\", \"InProgress\"));",
        "        workflow.put(\"Done\", WorkflowState.named(\"Done\"));",
        "",
        "        Project project = new Project(\"EI\", \"ElevateIQ\");",
        "        IssueService service = new IssueService(project, workflow, new IssueService.PriorityThenUpdatedStrategy());",
        "        service.addObserver(new IssueService.ConsoleNotificationObserver());",
        "",
        "        Issue bug = service.createIssue(IssueType.BUG, \"EI-7\", \"Fix login redirect\", \"anu\");",
        "        service.assignIssue(bug.id(), \"maya\");",
        "",
        "        Sprint sprint = project.createSprint(\"S1\", \"Sprint 1\", LocalDate.now(), LocalDate.now().plusDays(14));",
        "        project.moveToSprint(bug, sprint.id());",
        "",
        "        service.transitionIssue(bug.id(), \"InProgress\", \"maya\", \"Started debugging\");",
        "        service.transitionIssue(bug.id(), \"InReview\", \"maya\", \"Patch is ready\");",
        "        service.transitionIssue(bug.id(), \"Done\", \"lead\", \"Reviewed and verified\");",
        "",
        "        System.out.println(bug);",
        "        System.out.println(\"Sprint issues: \" + sprint.issues().size());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Issue",
      detailMD:
        "The domain object for a unit of work. It stores immutable identity and type data, mutable assignment/state/sprint pointers, comments, and an update timestamp. State mutation is intentionally narrow through **transitionTo**.",
    },
    {
      className: "IssueType",
      detailMD:
        "Factory enum for Story, Task, and Bug. It owns display names and default priorities, and its **create** method hides construction details from **IssueService**.",
    },
    {
      className: "WorkflowState",
      detailMD:
        "State interface plus configurable implementation. Each state advertises allowed target state names and approves a transition only when the target is present in that set.",
    },
    {
      className: "Transition",
      detailMD:
        "Immutable transition audit record. It captures from state, to state, actor, optional note, and timestamp for notifications and future audit history.",
    },
    {
      className: "Sprint",
      detailMD:
        "Time-boxed container for committed issues. It validates dates, prevents duplicate issue membership, and updates the issue's sprint pointer.",
    },
    {
      className: "Project",
      detailMD:
        "Planning aggregate that owns backlog and sprint registry. It knows how to add an issue back to backlog, create sprints, and move an issue into a sprint.",
    },
    {
      className: "IssueService",
      detailMD:
        "Facade over the domain. It stores the issue index, creates issues via **IssueType**, validates workflow state names, delegates transition approval to **WorkflowState**, ranks backlog via strategy, and notifies observers.",
    },
    {
      className: "Main",
      detailMD:
        "Runnable demonstration that builds the Open to InProgress to InReview to Done workflow, creates a Bug, assigns it, moves it into a sprint, and performs valid transitions with notifications.",
    },
  ],

  dryRun: {
    inputMD:
      "Workflow: **Open -> InProgress -> InReview -> Done**. Create Bug **EI-7**, assign it to **maya**, move it into **Sprint 1**, then transition through the workflow.",
    columns: ["Step", "Action", "Current state", "Sprint or backlog", "Notification", "Result"],
    rows: [
      ["1", "create BUG EI-7", "Open", "Backlog", "None", "Issue created with priority P1"],
      ["2", "assign to maya", "Open", "Backlog", "None", "Assignee becomes maya"],
      ["3", "move to Sprint 1", "Open", "Sprint 1", "None", "Issue leaves backlog"],
      ["4", "transition to InProgress", "InProgress", "Sprint 1", "Observer notified", "Allowed from Open"],
      ["5", "transition to InReview", "InReview", "Sprint 1", "Observer notified", "Allowed from InProgress"],
      ["6", "transition to Done", "Done", "Sprint 1", "Observer notified", "Allowed from InReview"],
    ],
    narrativeMD:
      "The dry run shows the state machine doing the guard work. If step 4 tried **Open -> Done**, **approveTransition** would throw before the issue changed state or observers were called.",
  },

  complexity: [
    {
      operation: "createIssue",
      time: "O(1)",
      space: "O(1)",
      note: "Map insert plus backlog append; issue construction is constant time.",
    },
    {
      operation: "transitionIssue",
      time: "O(O)",
      space: "O(1)",
      note: "O is the number of observers. State lookup and allowed-target check are constant for small configured sets.",
    },
    {
      operation: "rankedBacklog",
      time: "O(B log B)",
      space: "O(B)",
      note: "Copies and sorts B backlog issues using the injected strategy comparator.",
    },
    {
      operation: "moveToSprint",
      time: "O(B + S)",
      space: "O(1)",
      note: "Removes from a backlog list and checks duplicate membership in the sprint issue list.",
    },
    {
      operation: "notify observers",
      time: "O(O)",
      space: "O(1)",
      note: "Each observer is invoked once after a successful transition.",
    },
  ],
  complexityNotesMD:
    "The sample keeps lists simple for interview clarity. A production Jira would index backlog order, sprint membership, labels, assignees, and state with repositories and query indexes.",

  extensibility: [
    {
      label: "New issue type",
      detailMD:
        "Add a new **IssueType** constant such as Epic or Spike with its default priority and creation behavior. **IssueService.createIssue** does not change.",
    },
    {
      label: "New workflow",
      detailMD:
        "Load a different state map, for example Open to Triage to InProgress to Blocked to Done. The same **WorkflowState** interface validates edges.",
    },
    {
      label: "New notification channel",
      detailMD:
        "Implement **IssueObserver** for email, Slack, webhook, analytics, or audit persistence and register it with the service.",
    },
    {
      label: "New planning order",
      detailMD:
        "Inject another **IssueRankingStrategy**, such as manual rank, due date, severity, or weighted shortest job first.",
    },
    {
      label: "Custom fields",
      detailMD:
        "Attach a typed custom-field map to **Issue** or introduce **FieldDefinition** per project. Keep validation outside the transition engine.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Central transition matrix",
      detailMD:
        "Store allowed transitions in a **Map** from source state to target states and let the service check the matrix directly.",
      tradeoffsMD:
        "Simple to load from configuration, but it weakens the State pattern because state-specific hooks and behavior are pushed back into the service.",
    },
    {
      name: "Command objects for workflow actions",
      detailMD:
        "Represent transitions as command objects such as StartProgress, SubmitReview, and ResolveIssue. Each command validates permissions and applies changes.",
      tradeoffsMD:
        "Useful when transitions have rich side effects, but heavier than a configurable state graph for the base interview design.",
    },
    {
      name: "Separate repository layer from day one",
      detailMD:
        "Introduce **IssueRepository**, **ProjectRepository**, and **SprintRepository** interfaces and keep service methods transactional.",
      tradeoffsMD:
        "More realistic for production but distracts from the core LLD question if introduced before the domain model is clear.",
    },
  ],

  commonMistakes: [
    "Hard-coding workflow transitions inside **IssueService** with nested conditionals instead of using state objects.",
    "Letting invalid transitions partially mutate the issue before throwing.",
    "Sending notifications before the transition succeeds, creating false alerts.",
    "Modelling Story, Task, and Bug as only strings, then scattering type-specific defaults through the code.",
    "Mixing sprint planning logic with workflow validation, which makes backlog and state changes hard to reason about.",
    "Returning mutable backlog or sprint lists and allowing callers to corrupt project state.",
    "Forgetting the audit event, which makes transition notifications and history impossible to reconcile.",
  ],

  followUps: [
    {
      question: "How would you support project-specific workflows?",
      answerMD:
        "Store a workflow definition per project and build a state map for each project. **IssueService** can be scoped per project, or it can resolve states by project key before validating a transition.",
    },
    {
      question: "How do permissions fit into this model?",
      answerMD:
        "Add a policy check before **approveTransition**, for example **PermissionPolicy.canTransition(actor, issue, target)**. Keep authorization separate from workflow graph validity.",
    },
    {
      question: "How would you add transition audit history?",
      answerMD:
        "Persist every **Transition** through an observer or repository after the issue state changes. The observer can append to an audit log in the same transaction in production.",
    },
    {
      question: "How would you prevent concurrent transitions from racing?",
      answerMD:
        "Use a transactional repository with optimistic versioning on **Issue**. The update checks the issue version and current state, so only one transition wins.",
    },
    {
      question: "How would you support custom fields per issue type?",
      answerMD:
        "Define project-level field definitions and validate an issue's custom-field map against its **IssueType**. Avoid hard-coding fields on the base **Issue** class.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence and transactions",
      detailMD:
        "Use repositories and database transactions so issue state, sprint membership, and transition audit records commit together.",
    },
    {
      label: "Concurrency control",
      detailMD:
        "Add optimistic locking with an issue version column. Transition updates should include current state and version in the write condition.",
    },
    {
      label: "Notification delivery",
      detailMD:
        "Observers should enqueue durable events rather than sending synchronously on the user request path. Workers can retry email, Slack, or webhook delivery.",
    },
    {
      label: "Search and reporting",
      detailMD:
        "Index issues by project, assignee, state, sprint, labels, and text fields in a search store. Keep search projections derived from the source of truth.",
    },
    {
      label: "Workflow migration",
      detailMD:
        "Changing a workflow in production needs migration rules for issues currently in states that may be removed, renamed, or split.",
    },
  ],

  interviewNotes: [
    "Did you make the workflow configurable instead of hard-coded in service conditionals?",
    "Can you explain why **WorkflowState** is the right owner for allowed transitions?",
    "Is issue-type creation extensible through a factory method rather than scattered defaults?",
    "Do notifications happen only after a successful transition?",
    "Did you separate backlog or sprint planning policy from workflow validation?",
    "Can your design evolve toward repositories, audit history, permissions, and custom fields without rewriting the core model?",
  ],

  quiz: [
    {
      question: "Why should **IssueService** ask **WorkflowState** to approve a transition?",
      options: [
        "So transition rules live with the current state instead of scattered conditionals",
        "So every transition automatically creates a new issue",
        "So backlog sorting becomes O(1)",
        "So notifications can be skipped",
      ],
      answerIndex: 0,
      explanationMD:
        "That is the State pattern in this design. The current state owns its legal outgoing edges and rejects invalid targets before mutation.",
    },
    {
      question: "Which seam makes backlog ordering replaceable?",
      options: [
        "The **Transition** audit record",
        "The **IssueRankingStrategy** comparator provider",
        "The **Sprint** date range",
        "The **IssueObserver** callback",
      ],
      answerIndex: 1,
      explanationMD:
        "The Strategy pattern lets each team inject a different planning policy without changing issue creation or workflow transitions.",
    },
    {
      question: "What should happen if a user tries **Open -> Done** in the base workflow?",
      options: [
        "The issue moves to Done and observers repair it later",
        "The service creates a hidden InProgress state",
        "The state rejects the transition before mutation and before notifications",
        "The issue is moved to backlog automatically",
      ],
      answerIndex: 2,
      explanationMD:
        "Open only allows InProgress in the configured graph, so **approveTransition** throws before the issue changes.",
    },
    {
      question: "Why is **IssueType.create** useful?",
      options: [
        "It lets issue types own construction defaults such as priority",
        "It replaces the need for a workflow",
        "It makes every issue immutable",
        "It stores sprint dates",
      ],
      answerIndex: 0,
      explanationMD:
        "The factory method keeps Story, Task, and Bug defaults local to the type and keeps **IssueService** free of type-specific switch logic.",
    },
    {
      question: "When should observers be notified?",
      options: [
        "Before validation so users get faster feedback",
        "Only after the transition has been approved and the issue state has changed",
        "Only when an issue is created, never on transitions",
        "Whenever backlog is sorted",
      ],
      answerIndex: 1,
      explanationMD:
        "Observers should see committed domain events. Notifying before success can send false alerts for rejected transitions.",
    },
  ],

  practiceVariants: [
    {
      title: "Add blocked and reopened states",
      detailMD:
        "Extend the workflow to allow InProgress to Blocked, Blocked to InProgress, and Done to Reopened. Verify invalid edges still fail.",
      difficulty: "Intermediate",
    },
    {
      title: "Add role-based transition permissions",
      detailMD:
        "Introduce a permission policy so only assignees can move to InReview and only project leads can move to Done.",
      difficulty: "Advanced",
    },
    {
      title: "Add durable audit history",
      detailMD:
        "Create an observer that appends **Transition** records to an audit repository and supports fetching history for an issue.",
      difficulty: "Intermediate",
    },
    {
      title: "Add custom issue fields",
      detailMD:
        "Define project-level field definitions and validate issue-specific field values based on **IssueType**.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "Which object owns allowed workflow transitions?",
      back: "**WorkflowState** owns allowed target names and approves or rejects transitions.",
    },
    {
      front: "Which pattern models Open, InProgress, InReview, and Done?",
      back: "State pattern, represented by configurable **WorkflowState** instances.",
    },
    {
      front: "How are transition notifications decoupled?",
      back: "Through **IssueObserver**, called after a successful transition with the issue and transition record.",
    },
    {
      front: "Where do Story, Task, and Bug construction defaults live?",
      back: "In **IssueType.create**, the factory method used by **IssueService**.",
    },
    {
      front: "What does **IssueRankingStrategy** control?",
      back: "It returns the comparator used to rank backlog issues for planning.",
    },
    {
      front: "What is the base workflow path?",
      back: "Open to InProgress to InReview to Done.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Project, Issue, IssueType, WorkflowState, Transition, Sprint, IssueService, IssueObserver, IssueRankingStrategy.",
    "",
    "**Patterns:** State for workflow transitions, Factory Method for issue creation, Observer for notifications, Strategy for backlog ranking.",
    "",
    "**Flow:** create issue in Open backlog → assign user → move to sprint → transition through allowed states → emit notification after success.",
    "",
    "**Invariant:** invalid workflow edges do not mutate state and do not notify observers.",
    "",
    "**Default workflow:** Open → InProgress → InReview → Done.",
    "",
    "**Complexity:** createIssue O(1), transitionIssue O(observers), rankedBacklog O(B log B), moveToSprint O(B + S).",
    "",
    "**Extend:** add issue types in **IssueType**, add workflows by loading different states, add channels through **IssueObserver**, add planning policies through **IssueRankingStrategy**.",
  ].join("\n"),

  references: [
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
    {
      title: "Refactoring Guru — Observer Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/observer",
    },
    {
      title: "Domain-Driven Design",
      kind: "Book",
      author: "Eric Evans",
    },
    {
      title: "Jira Cloud Platform REST API",
      kind: "Docs",
      url: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    },
  ],

  relatedProblems: [
    { slug: "trello", note: "A related planning board with cards, lists, ordering, and notifications." },
    { slug: "slack", note: "Useful comparison for notification fan-out and channel integrations." },
    { slug: "google-docs", note: "Another collaboration-heavy product where permissions, events, and auditability matter." },
  ],
};
