import type { LLDProblemContent } from "../types";

export const ludo: LLDProblemContent = {
  slug: "ludo",

  statementMD: [
    "Design the object model for a **Ludo game** with two to four players, a color-specific path for each player, four tokens per player, dice rolls, captures, safe cells, and win detection.",
    "",
    "The interview focus is not rendering the board. It is the **turn and state model**: a token needs a 6 to leave home, movement must be validated before state changes, finishing needs an exact count, captures happen only on non-safe common cells, and turn advancement must handle extra turns without corrupting the game.",
  ].join("\n"),

  businessContextMD: [
    "Ludo is a strong multiplayer LLD exercise because a small board game creates many edge cases: token state transitions, per-color coordinate systems, dice-driven randomness, legal move selection, capture rules, and winner detection.",
    "",
    "Interviewers use it to see whether you can separate **rules** from **orchestration**. A good design keeps board math in **Board**, move validation in a **MovementStrategy**, token lifecycle in **Token**, and the turn loop in **LudoGame**.",
  ].join("\n"),

  functionalRequirements: [
    "Support two to four players, each assigned a distinct color and exactly four tokens.",
    "Represent a common circular path plus a color-specific home lane and finish cell.",
    "Roll a six-sided dice at the start of every turn.",
    "Allow a token to leave home only when the dice roll is 6.",
    "Move active tokens by the dice value and reject moves that overshoot the finish cell.",
    "Finish a token only when the move lands on the finish step exactly.",
    "Capture opponent tokens that land on the same non-safe common path cell and send them home.",
    "Keep safe cells immune from capture, including color start cells.",
    "Advance turns correctly, including an extra turn after rolling 6.",
    "Detect the winner when all four tokens of a player are finished.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Rule correctness",
      detailMD:
        "Every state mutation must be preceded by a legality check. Illegal moves should leave token positions, turn order, and winner state unchanged.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Variants such as no extra turn on 6, three consecutive sixes, blockades, or custom safe cells should be added by replacing strategies or board configuration.",
    },
    {
      label: "Deterministic testing",
      detailMD:
        "The dice is injected behind an interface so tests can use scripted rolls while production uses random rolls.",
    },
    {
      label: "Encapsulation",
      detailMD:
        "Tokens expose transitions such as **leaveHome**, **moveTo**, **finish**, and **sendHome** instead of letting callers mutate raw position fields.",
    },
    {
      label: "Observable gameplay",
      detailMD:
        "The game emits events for rolls, moves, captures, skipped turns, and winners so a UI, logger, or test harness can react without being embedded in the domain.",
    },
  ],

  requirementClarification: [
    {
      question: "How many players should the base design support?",
      answerMD:
        "Assume two to four players. Each player has one color and four tokens. The constructor rejects duplicate colors and unsupported player counts.",
    },
    {
      question: "Does rolling a 6 grant another turn?",
      answerMD:
        "Yes for the base rules. The turn loop keeps the same current player after a legal or skipped turn caused by a roll of 6, unless that move wins the game.",
    },
    {
      question: "Can a token enter the finish area with a higher roll than needed?",
      answerMD:
        "No. The move is illegal unless the target step is at most the finish step, and a token finishes only when it lands exactly on that step.",
    },
    {
      question: "Can captures happen inside the home lane?",
      answerMD:
        "No. Captures are checked only while a token is on the common circular path. Home lanes and finish cells are color-specific.",
    },
    {
      question: "Do we need user input, graphics, or networking?",
      answerMD:
        "Not in the core design. **LudoGame** exposes a turn loop and events; UI and network adapters can call into it or observe it later.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Token {",
    "        -String id",
    "        -PlayerColor owner",
    "        -TokenState state",
    "        -int stepsFromStart",
    "        +leaveHome() void",
    "        +moveTo(int) void",
    "        +finish(int) void",
    "        +sendHome() void",
    "    }",
    "    class TokenState {",
    "        <<enumeration>>",
    "        HOME",
    "        ACTIVE",
    "        FINISHED",
    "    }",
    "    class Player {",
    "        -PlayerColor color",
    "        -List~Token~ tokens",
    "        +create(PlayerColor) Player",
    "        +hasWon() boolean",
    "    }",
    "    class PlayerColor {",
    "        <<enumeration>>",
    "        RED",
    "        GREEN",
    "        YELLOW",
    "        BLUE",
    "    }",
    "    class Dice {",
    "        <<interface>>",
    "        +roll() int",
    "    }",
    "    class RandomDice",
    "    class ScriptedDice",
    "    class Board {",
    "        -Map~PlayerColor,Integer~ entryIndexByColor",
    "        -Set~Integer~ safeCells",
    "        +globalPosition(Token) int",
    "        +captureOpponentsIfNeeded(Token,List~Player~) List~Token~",
    "        +positionLabel(Token) String",
    "    }",
    "    class MovementStrategy {",
    "        <<interface>>",
    "        +canMove(Board,Token,int) boolean",
    "        +move(Board,Token,int,List~Player~) MoveResult",
    "    }",
    "    class StandardLudoMovementStrategy",
    "    class MoveResult {",
    "        -boolean legal",
    "        -String message",
    "        -List~Token~ capturedTokens",
    "    }",
    "    class LudoGame {",
    "        -List~Player~ players",
    "        -Board board",
    "        -Dice dice",
    "        -MovementStrategy movementStrategy",
    "        -List~GameObserver~ observers",
    "        -int currentPlayerIndex",
    "        -GameState state",
    "        +standard(List~PlayerColor~,Dice) LudoGame",
    "        +play(int) void",
    "        +addObserver(GameObserver) void",
    "    }",
    "    class GameObserver {",
    "        <<interface>>",
    "        +onEvent(String) void",
    "    }",
    "    class ConsoleGameObserver",
    "    Token --> TokenState",
    "    Player --> PlayerColor",
    "    Player o-- Token",
    "    Dice <|.. RandomDice",
    "    Dice <|.. ScriptedDice",
    "    MovementStrategy <|.. StandardLudoMovementStrategy",
    "    StandardLudoMovementStrategy ..> Board",
    "    StandardLudoMovementStrategy ..> MoveResult",
    "    Board ..> Player",
    "    Board ..> Token",
    "    LudoGame o-- Player",
    "    LudoGame o-- Board",
    "    LudoGame ..> Dice",
    "    LudoGame ..> MovementStrategy",
    "    LudoGame o-- GameObserver",
    "    GameObserver <|.. ConsoleGameObserver",
  ].join("\n"),
  classDiagramCaptionMD:
    "The model separates **token lifecycle**, **board coordinate rules**, **movement validation**, and **turn orchestration**. The game owns the loop, while strategies and observers provide replaceable policies and outputs.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Game as LudoGame",
    "    participant Dice as Dice",
    "    participant Rules as MovementStrategy",
    "    participant Board as Board",
    "    participant Token as Token",
    "    participant Obs as GameObserver",
    "    User->>Game: play(maxTurns)",
    "    Game->>Dice: roll()",
    "    Dice-->>Game: diceValue",
    "    Game->>Rules: canMove(board, token, diceValue)",
    "    Rules-->>Game: true",
    "    Game->>Rules: move(board, token, diceValue, players)",
    "    Rules->>Token: leaveHome or moveTo or finish",
    "    Rules->>Board: captureOpponentsIfNeeded(token, players)",
    "    Board-->>Rules: captured tokens",
    "    Rules-->>Game: MoveResult",
    "    Game->>Obs: onEvent(move result)",
    "    Game->>Game: check winner and advance turn",
    "    Game->>Obs: onEvent(winner or next turn)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "A turn rolls the dice, chooses a legal token, delegates validation and mutation to the movement strategy, lets the board resolve captures, then updates game state and notifies observers.",

  entities: [
    {
      name: "LudoGame",
      responsibilityMD:
        "Aggregate root and turn manager. Holds players, board, dice, movement rules, observers, current player index, game state, and winner.",
      attributes: ["players", "board", "dice", "movementStrategy", "observers", "currentPlayerIndex", "state", "winner"],
    },
    {
      name: "Player",
      responsibilityMD:
        "Represents one participant and owns four tokens of a single color. It answers **hasWon** by checking that all tokens are finished.",
      attributes: ["color", "tokens"],
    },
    {
      name: "Token",
      responsibilityMD:
        "Owns token lifecycle state and position as steps from its color start. It is the only class that changes a token between HOME, ACTIVE, and FINISHED.",
      attributes: ["id", "owner", "state", "stepsFromStart"],
    },
    {
      name: "Board",
      responsibilityMD:
        "Encodes common path length, finish step, color entry cells, safe cells, global position conversion, and capture detection.",
      attributes: ["PATH_LENGTH", "FINISH_STEP", "entryIndexByColor", "safeCells"],
    },
    {
      name: "MovementStrategy",
      responsibilityMD:
        "Rule policy for movement validation and state mutation. The standard strategy enforces 6-to-enter, exact finish, and capture checks.",
      attributes: ["canMove", "move"],
    },
    {
      name: "Dice",
      responsibilityMD:
        "Injected source of rolls. **RandomDice** is production-like; **ScriptedDice** makes demos and tests repeatable.",
      attributes: ["roll"],
    },
    {
      name: "MoveResult",
      responsibilityMD:
        "Immutable result object returned by the movement strategy. It carries legality, a human-readable message, and captured tokens.",
      attributes: ["legal", "message", "capturedTokens"],
    },
    {
      name: "GameObserver",
      responsibilityMD:
        "Notification seam for UI, logs, analytics, or tests. Observers receive text events without influencing game rules.",
      attributes: ["onEvent"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**TokenState** and **GameState** make lifecycle transitions explicit. A token cannot jump from HOME to FINISHED; it must enter, move, and finish through controlled methods.",
    },
    {
      name: "Strategy",
      whyMD:
        "**MovementStrategy** isolates the rule set for legal movement, captures, and exact finish. **Dice** also uses the same idea so random and scripted roll policies are interchangeable.",
    },
    {
      name: "Observer",
      whyMD:
        "**GameObserver** decouples gameplay from output. A console logger, UI renderer, replay recorder, or metrics collector can subscribe without changing **LudoGame**.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**Player.create** and **LudoGame.standard** centralize object creation for players, four tokens per player, board, and default rules. Callers do not assemble an inconsistent game graph by hand.",
    },
  ],

  designSteps: [
    {
      title: "Model token state before modelling the board",
      detailMD:
        "A token has only three meaningful states: HOME, ACTIVE, and FINISHED. Store position as **stepsFromStart** only while the token is active, and expose methods that enforce legal transitions.",
      code: [
        "enum TokenState {",
        "    HOME, ACTIVE, FINISHED",
        "}",
        "",
        "public void leaveHome() {",
        "    if (state != TokenState.HOME) {",
        "        throw new IllegalStateException(\"token is not at home\");",
        "    }",
        "    state = TokenState.ACTIVE;",
        "    stepsFromStart = 0;",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent each color path with relative steps",
      detailMD:
        "Keep one common path of 52 cells and give each color an entry index. A token's common-path coordinate is derived from its owner color plus **stepsFromStart**, so each player can share the same movement code.",
      code: [
        "public int globalPosition(Token token) {",
        "    if (!isOnCommonPath(token)) {",
        "        throw new IllegalArgumentException(\"token is not on the common path\");",
        "    }",
        "    int entryIndex = entryIndexByColor.get(token.getOwner());",
        "    return (entryIndex + token.getStepsFromStart()) % PATH_LENGTH;",
        "}",
      ].join("\n"),
    },
    {
      title: "Validate movement in a replaceable strategy",
      detailMD:
        "**StandardLudoMovementStrategy** owns the rules: a home token needs 6, a finished token cannot move, and an active token cannot overshoot the finish step.",
      code: [
        "public boolean canMove(Board board, Token token, int roll) {",
        "    if (token.isFinished()) {",
        "        return false;",
        "    }",
        "    if (token.isHome()) {",
        "        return roll == 6;",
        "    }",
        "    return token.getStepsFromStart() + roll <= board.finishStep();",
        "}",
      ].join("\n"),
    },
    {
      title: "Resolve captures through the board",
      detailMD:
        "After a token moves on the common path, the board checks whether the landing cell is safe. Only non-safe common cells can capture opponent tokens; home lanes and finish cells never capture.",
    },
    {
      title: "Keep turn flow in the game aggregate",
      detailMD:
        "**LudoGame** rolls dice, selects the first legal token for the sample strategy, applies the move, checks for a winner, then either advances or grants an extra turn on 6. This keeps sequencing away from **Board** and **Token**.",
    },
    {
      title: "Publish domain events instead of printing inside rules",
      detailMD:
        "Movement and turn outcomes are sent to **GameObserver**. The implementation includes a console observer, but tests can register an observer that stores events for assertions.",
    },
  ],

  implementation: [
    {
      filename: "Token.java",
      language: "java",
      content: [
        "enum TokenState {",
        "    HOME, ACTIVE, FINISHED",
        "}",
        "",
        "public final class Token {",
        "    private final String id;",
        "    private final PlayerColor owner;",
        "    private TokenState state;",
        "    private int stepsFromStart;",
        "",
        "    public Token(String id, PlayerColor owner) {",
        "        if (id == null || id.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(\"id is required\");",
        "        }",
        "        if (owner == null) {",
        "            throw new IllegalArgumentException(\"owner is required\");",
        "        }",
        "        this.id = id;",
        "        this.owner = owner;",
        "        this.state = TokenState.HOME;",
        "        this.stepsFromStart = -1;",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public PlayerColor getOwner() {",
        "        return owner;",
        "    }",
        "",
        "    public TokenState getState() {",
        "        return state;",
        "    }",
        "",
        "    public int getStepsFromStart() {",
        "        return stepsFromStart;",
        "    }",
        "",
        "    public boolean isHome() {",
        "        return state == TokenState.HOME;",
        "    }",
        "",
        "    public boolean isActive() {",
        "        return state == TokenState.ACTIVE;",
        "    }",
        "",
        "    public boolean isFinished() {",
        "        return state == TokenState.FINISHED;",
        "    }",
        "",
        "    public void leaveHome() {",
        "        if (!isHome()) {",
        "            throw new IllegalStateException(\"token is not at home\");",
        "        }",
        "        state = TokenState.ACTIVE;",
        "        stepsFromStart = 0;",
        "    }",
        "",
        "    public void moveTo(int targetSteps) {",
        "        if (!isActive()) {",
        "            throw new IllegalStateException(\"only active tokens can move\");",
        "        }",
        "        if (targetSteps < 0) {",
        "            throw new IllegalArgumentException(\"target steps cannot be negative\");",
        "        }",
        "        stepsFromStart = targetSteps;",
        "    }",
        "",
        "    public void finish(int finishStep) {",
        "        if (!isActive()) {",
        "            throw new IllegalStateException(\"only active tokens can finish\");",
        "        }",
        "        stepsFromStart = finishStep;",
        "        state = TokenState.FINISHED;",
        "    }",
        "",
        "    public void sendHome() {",
        "        state = TokenState.HOME;",
        "        stepsFromStart = -1;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return id + \"(\" + state + \")\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Player.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "",
        "enum PlayerColor {",
        "    RED, GREEN, YELLOW, BLUE",
        "}",
        "",
        "public final class Player {",
        "    private static final int TOKENS_PER_PLAYER = 4;",
        "",
        "    private final PlayerColor color;",
        "    private final List<Token> tokens;",
        "",
        "    private Player(PlayerColor color) {",
        "        if (color == null) {",
        "            throw new IllegalArgumentException(\"color is required\");",
        "        }",
        "        this.color = color;",
        "        this.tokens = new ArrayList<>();",
        "        for (int i = 1; i <= TOKENS_PER_PLAYER; i++) {",
        "            tokens.add(new Token(color.name() + \"-\" + i, color));",
        "        }",
        "    }",
        "",
        "    public static Player create(PlayerColor color) {",
        "        return new Player(color);",
        "    }",
        "",
        "    public PlayerColor getColor() {",
        "        return color;",
        "    }",
        "",
        "    public List<Token> getTokens() {",
        "        return Collections.unmodifiableList(tokens);",
        "    }",
        "",
        "    public boolean hasWon() {",
        "        for (Token token : tokens) {",
        "            if (!token.isFinished()) {",
        "                return false;",
        "            }",
        "        }",
        "        return true;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return color.name();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Dice.java",
      language: "java",
      content: [
        "import java.util.ArrayDeque;",
        "import java.util.Queue;",
        "import java.util.Random;",
        "",
        "public interface Dice {",
        "    int roll();",
        "}",
        "",
        "final class RandomDice implements Dice {",
        "    private final Random random;",
        "",
        "    RandomDice() {",
        "        this(new Random());",
        "    }",
        "",
        "    RandomDice(Random random) {",
        "        if (random == null) {",
        "            throw new IllegalArgumentException(\"random is required\");",
        "        }",
        "        this.random = random;",
        "    }",
        "",
        "    @Override",
        "    public int roll() {",
        "        return random.nextInt(6) + 1;",
        "    }",
        "}",
        "",
        "final class ScriptedDice implements Dice {",
        "    private final Queue<Integer> rolls = new ArrayDeque<>();",
        "",
        "    ScriptedDice(int... values) {",
        "        if (values == null || values.length == 0) {",
        "            throw new IllegalArgumentException(\"at least one roll is required\");",
        "        }",
        "        for (int value : values) {",
        "            if (value < 1 || value > 6) {",
        "                throw new IllegalArgumentException(\"dice roll must be between 1 and 6\");",
        "            }",
        "            rolls.add(value);",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public int roll() {",
        "        if (rolls.isEmpty()) {",
        "            return 1;",
        "        }",
        "        return rolls.remove();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Board.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Arrays;",
        "import java.util.Collections;",
        "import java.util.EnumMap;",
        "import java.util.HashSet;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Set;",
        "",
        "public final class Board {",
        "    public static final int PATH_LENGTH = 52;",
        "    public static final int FINISH_STEP = 56;",
        "",
        "    private final Map<PlayerColor, Integer> entryIndexByColor;",
        "    private final Set<Integer> safeCells;",
        "",
        "    public Board() {",
        "        entryIndexByColor = new EnumMap<>(PlayerColor.class);",
        "        entryIndexByColor.put(PlayerColor.RED, 0);",
        "        entryIndexByColor.put(PlayerColor.GREEN, 13);",
        "        entryIndexByColor.put(PlayerColor.YELLOW, 26);",
        "        entryIndexByColor.put(PlayerColor.BLUE, 39);",
        "",
        "        safeCells = new HashSet<>(Arrays.asList(0, 8, 13, 21, 26, 34, 39, 47));",
        "    }",
        "",
        "    public int finishStep() {",
        "        return FINISH_STEP;",
        "    }",
        "",
        "    public boolean isOnCommonPath(Token token) {",
        "        return token.isActive() && token.getStepsFromStart() < PATH_LENGTH;",
        "    }",
        "",
        "    public boolean isSafeCell(int globalPosition) {",
        "        return safeCells.contains(globalPosition);",
        "    }",
        "",
        "    public int globalPosition(Token token) {",
        "        if (!isOnCommonPath(token)) {",
        "            throw new IllegalArgumentException(\"token is not on the common path\");",
        "        }",
        "        Integer entryIndex = entryIndexByColor.get(token.getOwner());",
        "        if (entryIndex == null) {",
        "            throw new IllegalArgumentException(\"unknown token color\");",
        "        }",
        "        return (entryIndex + token.getStepsFromStart()) % PATH_LENGTH;",
        "    }",
        "",
        "    public List<Token> captureOpponentsIfNeeded(Token mover, List<Player> players) {",
        "        if (!isOnCommonPath(mover)) {",
        "            return Collections.emptyList();",
        "        }",
        "",
        "        int landingCell = globalPosition(mover);",
        "        if (isSafeCell(landingCell)) {",
        "            return Collections.emptyList();",
        "        }",
        "",
        "        List<Token> captured = new ArrayList<>();",
        "        for (Player player : players) {",
        "            if (player.getColor() == mover.getOwner()) {",
        "                continue;",
        "            }",
        "            for (Token other : player.getTokens()) {",
        "                if (isOnCommonPath(other) && globalPosition(other) == landingCell) {",
        "                    other.sendHome();",
        "                    captured.add(other);",
        "                }",
        "            }",
        "        }",
        "        return captured;",
        "    }",
        "",
        "    public String positionLabel(Token token) {",
        "        if (token.isHome()) {",
        "            return \"HOME\";",
        "        }",
        "        if (token.isFinished()) {",
        "            return \"FINISHED\";",
        "        }",
        "        if (token.getStepsFromStart() >= PATH_LENGTH) {",
        "            return \"HOME_LANE_\" + (token.getStepsFromStart() - PATH_LENGTH + 1);",
        "        }",
        "        return \"CELL_\" + globalPosition(token);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "MovementStrategy.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "",
        "public interface MovementStrategy {",
        "    boolean canMove(Board board, Token token, int roll);",
        "",
        "    MoveResult move(Board board, Token token, int roll, List<Player> players);",
        "}",
        "",
        "final class StandardLudoMovementStrategy implements MovementStrategy {",
        "    @Override",
        "    public boolean canMove(Board board, Token token, int roll) {",
        "        validateRoll(roll);",
        "        if (token.isFinished()) {",
        "            return false;",
        "        }",
        "        if (token.isHome()) {",
        "            return roll == 6;",
        "        }",
        "        return token.getStepsFromStart() + roll <= board.finishStep();",
        "    }",
        "",
        "    @Override",
        "    public MoveResult move(Board board, Token token, int roll, List<Player> players) {",
        "        if (!canMove(board, token, roll)) {",
        "            return MoveResult.illegal(\"No legal move for \" + token.getId() + \" with roll \" + roll);",
        "        }",
        "",
        "        if (token.isHome()) {",
        "            token.leaveHome();",
        "        } else {",
        "            int targetSteps = token.getStepsFromStart() + roll;",
        "            token.moveTo(targetSteps);",
        "            if (targetSteps == board.finishStep()) {",
        "                token.finish(board.finishStep());",
        "                return MoveResult.legal(token.getId() + \" reached the finish\", Collections.<Token>emptyList());",
        "            }",
        "        }",
        "",
        "        List<Token> captured = board.captureOpponentsIfNeeded(token, players);",
        "        String message = token.getId() + \" moved to \" + board.positionLabel(token);",
        "        if (!captured.isEmpty()) {",
        "            message += \" and captured \" + captured.size() + \" token(s)\";",
        "        }",
        "        return MoveResult.legal(message, captured);",
        "    }",
        "",
        "    private void validateRoll(int roll) {",
        "        if (roll < 1 || roll > 6) {",
        "            throw new IllegalArgumentException(\"dice roll must be between 1 and 6\");",
        "        }",
        "    }",
        "}",
        "",
        "final class MoveResult {",
        "    private final boolean legal;",
        "    private final String message;",
        "    private final List<Token> capturedTokens;",
        "",
        "    private MoveResult(boolean legal, String message, List<Token> capturedTokens) {",
        "        this.legal = legal;",
        "        this.message = message;",
        "        this.capturedTokens = new ArrayList<>(capturedTokens);",
        "    }",
        "",
        "    static MoveResult legal(String message, List<Token> capturedTokens) {",
        "        return new MoveResult(true, message, capturedTokens);",
        "    }",
        "",
        "    static MoveResult illegal(String message) {",
        "        return new MoveResult(false, message, Collections.<Token>emptyList());",
        "    }",
        "",
        "    boolean isLegal() {",
        "        return legal;",
        "    }",
        "",
        "    String getMessage() {",
        "        return message;",
        "    }",
        "",
        "    List<Token> getCapturedTokens() {",
        "        return Collections.unmodifiableList(capturedTokens);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "LudoGame.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.EnumSet;",
        "import java.util.HashSet;",
        "import java.util.List;",
        "import java.util.Set;",
        "",
        "enum GameState {",
        "    NOT_STARTED, RUNNING, FINISHED",
        "}",
        "",
        "interface GameObserver {",
        "    void onEvent(String event);",
        "}",
        "",
        "final class ConsoleGameObserver implements GameObserver {",
        "    @Override",
        "    public void onEvent(String event) {",
        "        System.out.println(event);",
        "    }",
        "}",
        "",
        "public final class LudoGame {",
        "    private final List<Player> players;",
        "    private final Board board;",
        "    private final Dice dice;",
        "    private final MovementStrategy movementStrategy;",
        "    private final List<GameObserver> observers = new ArrayList<>();",
        "",
        "    private int currentPlayerIndex;",
        "    private GameState state;",
        "    private Player winner;",
        "",
        "    private LudoGame(List<Player> players, Board board, Dice dice, MovementStrategy movementStrategy) {",
        "        this.players = new ArrayList<>(players);",
        "        this.board = board;",
        "        this.dice = dice;",
        "        this.movementStrategy = movementStrategy;",
        "        this.currentPlayerIndex = 0;",
        "        this.state = GameState.NOT_STARTED;",
        "    }",
        "",
        "    public static LudoGame standard(List<PlayerColor> colors, Dice dice) {",
        "        return standard(colors, dice, new StandardLudoMovementStrategy());",
        "    }",
        "",
        "    public static LudoGame standard(List<PlayerColor> colors, Dice dice, MovementStrategy movementStrategy) {",
        "        if (colors == null || colors.size() < 2 || colors.size() > 4) {",
        "            throw new IllegalArgumentException(\"Ludo needs two to four players\");",
        "        }",
        "        if (dice == null) {",
        "            throw new IllegalArgumentException(\"dice is required\");",
        "        }",
        "        if (movementStrategy == null) {",
        "            throw new IllegalArgumentException(\"movement strategy is required\");",
        "        }",
        "",
        "        Set<PlayerColor> distinctColors = new HashSet<>(colors);",
        "        if (distinctColors.size() != colors.size() || !EnumSet.allOf(PlayerColor.class).containsAll(colors)) {",
        "            throw new IllegalArgumentException(\"players need distinct supported colors\");",
        "        }",
        "",
        "        List<Player> players = new ArrayList<>();",
        "        for (PlayerColor color : colors) {",
        "            players.add(Player.create(color));",
        "        }",
        "        return new LudoGame(players, new Board(), dice, movementStrategy);",
        "    }",
        "",
        "    public void addObserver(GameObserver observer) {",
        "        if (observer != null) {",
        "            observers.add(observer);",
        "        }",
        "    }",
        "",
        "    public Player getWinner() {",
        "        return winner;",
        "    }",
        "",
        "    public List<Player> getPlayers() {",
        "        return Collections.unmodifiableList(players);",
        "    }",
        "",
        "    public void play(int maxTurns) {",
        "        if (maxTurns <= 0) {",
        "            throw new IllegalArgumentException(\"maxTurns must be positive\");",
        "        }",
        "        if (state == GameState.FINISHED) {",
        "            notifyObservers(\"Game already finished. Winner: \" + winner);",
        "            return;",
        "        }",
        "",
        "        state = GameState.RUNNING;",
        "        notifyObservers(\"Game started with \" + players.size() + \" players\");",
        "",
        "        int turnsPlayed = 0;",
        "        while (state == GameState.RUNNING && turnsPlayed < maxTurns) {",
        "            takeTurn();",
        "            turnsPlayed++;",
        "        }",
        "",
        "        if (state == GameState.RUNNING) {",
        "            notifyObservers(\"Stopped after maxTurns. Snapshot: \" + snapshot());",
        "        }",
        "    }",
        "",
        "    private void takeTurn() {",
        "        Player player = players.get(currentPlayerIndex);",
        "        int roll = dice.roll();",
        "        notifyObservers(player + \" rolled \" + roll);",
        "",
        "        Token token = chooseFirstLegalToken(player, roll);",
        "        if (token == null) {",
        "            notifyObservers(player + \" has no legal move\");",
        "            advanceAfterRoll(roll);",
        "            return;",
        "        }",
        "",
        "        MoveResult result = movementStrategy.move(board, token, roll, players);",
        "        notifyObservers(result.getMessage() + \"; captured=\" + result.getCapturedTokens().size());",
        "",
        "        if (result.isLegal() && player.hasWon()) {",
        "            winner = player;",
        "            state = GameState.FINISHED;",
        "            notifyObservers(\"Winner: \" + player);",
        "            return;",
        "        }",
        "",
        "        advanceAfterRoll(roll);",
        "    }",
        "",
        "    private Token chooseFirstLegalToken(Player player, int roll) {",
        "        for (Token token : player.getTokens()) {",
        "            if (movementStrategy.canMove(board, token, roll)) {",
        "                return token;",
        "            }",
        "        }",
        "        return null;",
        "    }",
        "",
        "    private void advanceAfterRoll(int roll) {",
        "        if (roll == 6) {",
        "            notifyObservers(players.get(currentPlayerIndex) + \" gets another turn\");",
        "            return;",
        "        }",
        "        currentPlayerIndex = (currentPlayerIndex + 1) % players.size();",
        "    }",
        "",
        "    private void notifyObservers(String event) {",
        "        for (GameObserver observer : observers) {",
        "            observer.onEvent(event);",
        "        }",
        "    }",
        "",
        "    public String snapshot() {",
        "        StringBuilder builder = new StringBuilder();",
        "        for (Player player : players) {",
        "            if (builder.length() > 0) {",
        "                builder.append(\" | \");",
        "            }",
        "            builder.append(player.getColor()).append(\": \");",
        "            for (Token token : player.getTokens()) {",
        "                builder.append(token.getId()).append(\"=\").append(board.positionLabel(token)).append(\" \");",
        "            }",
        "        }",
        "        return builder.toString().trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.util.Arrays;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Dice dice = new ScriptedDice(6, 6, 2, 6, 3, 4, 1, 6, 2, 5);",
        "        LudoGame game = LudoGame.standard(Arrays.asList(PlayerColor.RED, PlayerColor.GREEN), dice);",
        "        game.addObserver(new ConsoleGameObserver());",
        "",
        "        game.play(10);",
        "        System.out.println(\"Final snapshot: \" + game.snapshot());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Token",
      detailMD:
        "Represents one movable piece. It owns the **TokenState** and **stepsFromStart**, and exposes controlled transitions for entering, moving, finishing, and being captured.",
    },
    {
      className: "Player",
      detailMD:
        "Creates and owns exactly four tokens of one **PlayerColor**. Its **hasWon** method is the winner predicate used by **LudoGame** after every legal move.",
    },
    {
      className: "Dice",
      detailMD:
        "A small strategy interface for roll generation. **RandomDice** models normal play, while **ScriptedDice** provides deterministic rolls for demos and tests.",
    },
    {
      className: "Board",
      detailMD:
        "Contains the board coordinate system: common path length, finish step, entry positions by color, safe cells, global position conversion, and capture resolution.",
    },
    {
      className: "MovementStrategy",
      detailMD:
        "Defines and implements legal movement. **StandardLudoMovementStrategy** checks 6-to-enter, exact finish, and finished-token immobility before mutating token state.",
    },
    {
      className: "LudoGame",
      detailMD:
        "Coordinates the game loop. It rolls dice, selects a legal token, delegates movement, notifies observers, grants extra turns on 6, and records the winner.",
    },
    {
      className: "Main",
      detailMD:
        "A deterministic demo that builds a two-player game through the factory method, attaches a console observer, and runs a bounded number of turns.",
    },
  ],

  dryRun: {
    inputMD:
      "Two-player game with RED and GREEN. Assume the listed token positions before each step where needed: R1 and G1 are the active tokens, safe cells are **0, 8, 13, 21, 26, 34, 39, 47**, and the finish step is **56**.",
    columns: ["Step", "Roll and state", "Movement decision", "Capture or rule", "Turn outcome"],
    rows: [
      ["1", "RED R1 is HOME, roll is 6", "R1 leaves home and lands on cell 0", "No capture because cell 0 is safe", "RED gets another turn"],
      ["2", "RED R1 is at step 8, roll is 2", "R1 moves to step 10, global cell 10", "GREEN G1 on cell 10 is captured and sent HOME", "Turn advances unless variant grants extra rules"],
      ["3", "GREEN G1 is HOME, roll is 4", "No token can leave home", "State is unchanged because move is illegal", "Turn advances to RED"],
      ["4", "RED R1 is at step 54, roll is 3", "Move is rejected because target step 57 overshoots 56", "Exact finish rule protects the state", "Turn advances"],
      ["5", "RED R1 is at step 54, roll is 2", "R1 lands exactly on step 56", "Token becomes FINISHED; no capture in home lane", "Winner check runs for RED"],
    ],
    narrativeMD:
      "The dry run shows the three highest-risk rules: a 6 is required to enter, capture is disabled on safe cells and outside the common path, and finishing requires an exact count.",
  },

  complexity: [
    {
      operation: "chooseFirstLegalToken",
      time: "O(T)",
      space: "O(1)",
      note: "T is tokens per player, fixed at 4 in normal Ludo.",
    },
    {
      operation: "move",
      time: "O(P × T)",
      space: "O(C)",
      note: "After validation, capture detection scans opponent tokens; C is captured tokens on the landing cell.",
    },
    {
      operation: "takeTurn",
      time: "O(P × T)",
      space: "O(C)",
      note: "A turn includes legal-token selection, movement, capture scan, observer notifications, and winner check.",
    },
    {
      operation: "snapshot",
      time: "O(P × T)",
      space: "O(P × T)",
      note: "Builds a display string for every token in the game.",
    },
  ],
  complexityNotesMD:
    "With standard Ludo limits, these operations are effectively constant time. The asymptotic notation matters because the same design can support variants with more players, more tokens, or team boards.",

  extensibility: [
    {
      label: "Rule variants",
      detailMD:
        "Replace **MovementStrategy** to support three consecutive sixes losing the turn, no extra turn on 6, mandatory capture, or different finish rules.",
    },
    {
      label: "Custom boards",
      detailMD:
        "Parameterize **Board** with path length, entry cells, safe cells, and finish step so regional variants do not change token or game code.",
    },
    {
      label: "Human and bot players",
      detailMD:
        "Move token selection behind a **TokenSelectionStrategy**. The sample chooses the first legal token, but a UI or bot can choose differently.",
    },
    {
      label: "Replay and audit",
      detailMD:
        "Observers can store domain events. A replay service can rebuild the game from dice rolls and selected token ids.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Explicit graph board",
      detailMD:
        "Represent every cell as a node with edges to the next common path cell or home-lane cell instead of computing positions with modular arithmetic.",
      tradeoffsMD:
        "Easier to visualize and customize, but more verbose for interviews and more error-prone to initialize by hand.",
    },
    {
      name: "Polymorphic token states",
      detailMD:
        "Replace **TokenState** enum with **HomeTokenState**, **ActiveTokenState**, and **FinishedTokenState** classes that implement transition methods.",
      tradeoffsMD:
        "Closer to the classical State pattern, but heavy for three simple states unless many state-specific behaviors are expected.",
    },
    {
      name: "Event-sourced game engine",
      detailMD:
        "Record **DiceRolled**, **TokenMoved**, **TokenCaptured**, and **TokenFinished** events and derive current state from the event log.",
      tradeoffsMD:
        "Great for multiplayer replay and debugging, but overkill for an in-memory interview implementation.",
    },
  ],

  commonMistakes: [
    "Storing one global board index on the token and forgetting that every color has a different entry cell.",
    "Moving a token first and validating exact finish or capture rules afterward.",
    "Allowing a home token to move on any roll instead of requiring a 6.",
    "Capturing tokens on safe cells or inside a home lane.",
    "Skipping winner detection after a token finishes.",
    "Embedding console input or UI rendering inside **Board** or **MovementStrategy**.",
    "Hard-coding random dice creation inside **LudoGame**, which makes tests flaky.",
    "Advancing the turn incorrectly after rolling 6 or after a player has no legal move.",
  ],

  followUps: [
    {
      question: "How would you let a human choose which token to move?",
      answerMD:
        "Add a **TokenSelectionStrategy** with inputs player, board, roll, and legal tokens. A console, UI, or bot strategy can select a token while **LudoGame** still owns turn sequencing.",
    },
    {
      question: "How do you support three consecutive sixes losing the turn?",
      answerMD:
        "Track consecutive sixes in **LudoGame** or a **TurnPolicy** strategy. When the count reaches three, skip movement, reset the count, notify observers, and advance the turn.",
    },
    {
      question: "How would you make the game safe for an online multiplayer server?",
      answerMD:
        "Make turn execution atomic per game id, persist events or snapshots, validate that the acting user owns the current player, and publish observer events to clients after commit.",
    },
    {
      question: "How do you handle blockades where two same-color tokens share a cell?",
      answerMD:
        "Represent occupancy per cell and add blockade checks to **MovementStrategy**. The board can expose occupants of a global cell while the strategy decides whether passing or landing is legal.",
    },
    {
      question: "Why not put all rules inside **Token**?",
      answerMD:
        "**Token** should protect its own lifecycle, but it does not know opponents, safe cells, or turn policy. Board-aware and player-aware rules belong in **MovementStrategy** and **Board**.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence",
      detailMD:
        "Store game snapshots or append-only events so active games survive process restarts and can be resumed across devices.",
    },
    {
      label: "Concurrency",
      detailMD:
        "Guard each game with a per-game lock or transactional compare-and-set on version. Two clients must not submit moves for the same turn concurrently.",
    },
    {
      label: "Fair dice",
      detailMD:
        "Use a server-side dice source and record roll events. Clients should never provide final dice values in competitive online play.",
    },
    {
      label: "Observability",
      detailMD:
        "Emit metrics for abandoned games, average turns, captures, illegal move attempts, and game duration. Keep enough event detail to debug disputes.",
    },
    {
      label: "Abuse prevention",
      detailMD:
        "Validate player identity, turn ownership, and token ownership on every submitted move. Rate-limit repeated illegal attempts.",
    },
  ],

  interviewNotes: [
    "Did you isolate turn management from movement validation and board math?",
    "Can you explain why a token stores relative steps instead of absolute cells?",
    "Did you preserve invariants when a move is illegal or overshoots the finish?",
    "Can you replace dice and movement policies for deterministic tests and variants?",
    "Did you make captures depend on common-path position and safe-cell checks?",
    "Is the winner detected from player token state rather than a separate counter that can drift?",
  ],

  quiz: [
    {
      question: "Why does a token store **stepsFromStart** instead of only a global board cell?",
      options: [
        "Because each color has a different entry path and home lane",
        "Because global cells cannot be represented as integers",
        "Because dice rolls are always relative to the red player",
        "Because it removes the need for a board",
      ],
      answerIndex: 0,
      explanationMD:
        "Relative steps let every color use the same movement logic while **Board** converts those steps to a global common-path cell for capture checks.",
    },
    {
      question: "Which rule should be checked before moving a token from HOME?",
      options: [
        "The dice roll must be 6",
        "The target cell must be the finish cell",
        "The player must have captured earlier",
        "The opponent must be on a safe cell",
      ],
      answerIndex: 0,
      explanationMD:
        "A home token can enter the board only on a roll of 6. Any other roll produces no legal move for that token.",
    },
    {
      question: "When should capture logic run?",
      options: [
        "Before dice rolling",
        "After every move, including home lane moves",
        "After a legal move lands on a non-safe common path cell",
        "Only when the moving player rolls 1",
      ],
      answerIndex: 2,
      explanationMD:
        "Captures depend on the landing cell. Safe cells, home lanes, and finish cells are excluded.",
    },
    {
      question: "What does **MovementStrategy** primarily buy in this design?",
      options: [
        "It makes the board draw itself",
        "It makes alternate movement rules replaceable without rewriting **LudoGame**",
        "It stores all tokens permanently",
        "It removes the need to check winner state",
      ],
      answerIndex: 1,
      explanationMD:
        "Movement rules vary across Ludo variants. A strategy keeps those rules outside the turn loop.",
    },
    {
      question: "Why inject **Dice** instead of constructing **RandomDice** inside **LudoGame**?",
      options: [
        "To make dice values globally unique",
        "To avoid creating any objects",
        "To support deterministic tests and alternate roll sources",
        "To make captures faster",
      ],
      answerIndex: 2,
      explanationMD:
        "Injected dice lets tests use **ScriptedDice** and production use **RandomDice** without changing game logic.",
    },
  ],

  practiceVariants: [
    {
      title: "Add player-selected moves",
      detailMD:
        "Replace first-legal-token selection with a **TokenSelectionStrategy** and validate user-chosen token ids before applying moves.",
      difficulty: "Beginner",
    },
    {
      title: "Support three consecutive sixes",
      detailMD:
        "Add a turn policy that tracks consecutive sixes, cancels the third move, and advances the turn with an observer event.",
      difficulty: "Intermediate",
    },
    {
      title: "Implement blockades",
      detailMD:
        "Allow same-color tokens to share a cell and block opponents from passing. Decide whether blockade checks belong in **Board**, **MovementStrategy**, or a new occupancy service.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What are the core token states in Ludo?",
      back: "HOME, ACTIVE, and FINISHED. The token transitions through controlled methods rather than raw field mutation.",
    },
    {
      front: "Why use relative steps for token position?",
      back: "Each color has a different start cell and home lane; **Board** maps relative steps to a common global cell only when capture checks need it.",
    },
    {
      front: "When can a token leave home?",
      back: "Only on a dice roll of 6.",
    },
    {
      front: "What makes a finish move legal?",
      back: "The target step must be exactly the finish step; overshooting is rejected and state remains unchanged.",
    },
    {
      front: "Which pattern isolates movement variants?",
      back: "Strategy, through **MovementStrategy** and its standard implementation.",
    },
    {
      front: "How are UI updates decoupled from the game engine?",
      back: "Through **GameObserver**, which receives events emitted by **LudoGame**.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** LudoGame, Player, Token, Board, Dice, MovementStrategy, MoveResult, GameObserver.",
    "",
    "**State:** Token is HOME, ACTIVE, or FINISHED; game is NOT_STARTED, RUNNING, or FINISHED.",
    "",
    "**Movement rules:** HOME needs roll 6; ACTIVE moves by dice; target must not exceed finish step 56; exact landing on 56 finishes.",
    "",
    "**Capture rules:** convert relative steps to global common-path cells; capture opponents only on non-safe common cells.",
    "",
    "**Turn flow:** roll dice → choose legal token → move via strategy → resolve capture → check winner → grant extra turn on 6 or advance.",
    "",
    "**Patterns:** State for lifecycle, Strategy for movement and dice, Observer for events, Factory Method for standard setup.",
    "",
    "**Complexity:** bounded constant for standard Ludo; generally O(P×T) per turn because capture checks may inspect all tokens.",
  ].join("\n"),

  references: [
    {
      title: "Head First Design Patterns",
      kind: "Book",
      author: "Freeman & Robson",
    },
    {
      title: "Effective Java — Enums and Method Design",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
    {
      title: "Refactoring Guru — Observer Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/observer",
    },
  ],

  relatedProblems: [
    { slug: "snake-and-ladder", note: "Another dice-driven board game where board transitions and turn flow matter." },
    { slug: "chess", note: "A deeper game model with legal move validation, state, and win detection." },
    { slug: "tic-tac-toe", note: "A compact turn-based game useful for comparing winner checks and board state." },
  ],
};
