import type { LLDProblemContent } from "../types";

export const minesweeper: LLDProblemContent = {
  slug: "minesweeper",

  statementMD: [
    "Design the object model for **Minesweeper**, a grid game where cells may hide mines, show adjacent-mine counts, be revealed, or be flagged by the player.",
    "The engine must generate a board, place mines without duplicates, compute the 8-neighbor counts, and reveal cells according to classic Minesweeper rules.",
    "",
    "The central interview challenge is the reveal flow: clicking a mine moves the game to **LOST**, clicking a numbered safe cell reveals only that cell, and clicking a zero-count safe cell triggers flood-fill to reveal the connected empty region plus its numbered boundary.",
    "",
    "Keep the model UI-free. A console app, web client, or bot should call the same **Game** API and receive a state transition from **IN_PROGRESS** to either **WON** or **LOST**.",
  ].join("\n"),

  businessContextMD: [
    "Minesweeper is a strong intermediate LLD problem because the class model is small but the correctness surface is non-trivial. Candidates must model cell state, board generation, a pluggable mine-placement policy, and a game state machine without mixing in rendering concerns.",
    "",
    "Interviewers use it to test whether you can combine OOP boundaries with graph traversal. The flood-fill must be iterative or carefully guarded, flags must not corrupt reveal state, and the win condition must be based on all non-mine cells being revealed rather than on flag count guesses.",
  ].join("\n"),

  functionalRequirements: [
    "Create a rectangular board with positive row and column counts and a mine count smaller than the number of cells.",
    "Place mines through a pluggable placement strategy, ensuring positions are unique and within board bounds.",
    "Compute adjacent-mine counts using all eight neighboring directions around each non-mine cell.",
    "Reveal a safe numbered cell without expanding beyond that cell.",
    "Reveal an empty zero-count cell with BFS or DFS flood-fill, expanding through zero cells and revealing bordering numbered cells.",
    "Reveal a mine as a losing move and transition the game from **IN_PROGRESS** to **LOST**.",
    "Allow players to toggle flags on hidden cells and reject reveal attempts on flagged cells.",
    "Declare **WON** when every non-mine cell has been revealed, regardless of how many flags are placed.",
    "Reject reveals and flag changes after the game reaches **WON** or **LOST**.",
    "Expose enough board state for a UI to render hidden cells, flags, revealed counts, mines after loss, and current game state.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Flood-fill correctness",
      detailMD:
        "The reveal algorithm must visit each safe cell at most a small constant number of times, must not cross mines, and must stop expansion at numbered boundary cells.",
    },
    {
      label: "Deterministic testability",
      detailMD:
        "Mine placement is injected through **MinePlacementStrategy** so tests can supply fixed positions while production can use random placement.",
    },
    {
      label: "State-machine safety",
      detailMD:
        "Only **IN_PROGRESS** accepts player actions. A mine reveal moves to **LOST** and all safe cells revealed moves to **WON**; terminal states are sticky.",
    },
    {
      label: "Encapsulation",
      detailMD:
        "Cell flags, revealed status, mine markers, and adjacent counts are changed only through Board and Cell methods, not by callers mutating raw arrays.",
    },
    {
      label: "Scalability for large boards",
      detailMD:
        "Use iterative BFS instead of recursive DFS in the reference implementation so a large empty area does not overflow the Java call stack.",
    },
  ],

  requirementClarification: [
    {
      question: "Are diagonal neighbors counted?",
      answerMD:
        "Yes. Adjacent-mine count uses all eight surrounding cells: horizontal, vertical, and diagonal neighbors within bounds.",
    },
    {
      question: "Does the first click need to be guaranteed safe?",
      answerMD:
        "Not in the base design. The Strategy seam makes it easy to add first-click-safe placement later by passing the first coordinate into a specialized strategy.",
    },
    {
      question: "Does placing all flags correctly win the game?",
      answerMD:
        "No. Flags are player annotations. The base win condition is that every non-mine cell is revealed; flags alone never change the game to **WON**.",
    },
    {
      question: "Should flood-fill use recursion?",
      answerMD:
        "Use BFS or iterative DFS for the implementation. Recursive DFS is fine to explain, but an interview-grade Java solution should avoid stack overflow on large empty boards.",
    },
    {
      question: "Do we need a GUI, timer, scoring, or persistence?",
      answerMD:
        "No for the core LLD. Keep the engine in memory and expose board state so UI, timer, leaderboard, and storage adapters can be added around it.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Game {",
    "        -Board board",
    "        -GameState state",
    "        +newGame(int,int,int,MinePlacementStrategy) Game",
    "        +reveal(int,int) List~Cell~",
    "        +toggleFlag(int,int) void",
    "        +getState() GameState",
    "        +getBoard() Board",
    "    }",
    "    class Board {",
    "        -int rows",
    "        -int cols",
    "        -CellMatrix cells",
    "        -int mineCount",
    "        +create(int,int,int,MinePlacementStrategy) Board",
    "        +reveal(int,int) List~Cell~",
    "        +toggleFlag(int,int) void",
    "        +allSafeCellsRevealed() boolean",
    "        +revealAllMines() void",
    "    }",
    "    class Cell {",
    "        -int row",
    "        -int col",
    "        -boolean mine",
    "        -boolean revealed",
    "        -boolean flagged",
    "        -int adjacentMines",
    "        +reveal() boolean",
    "        +toggleFlag() void",
    "    }",
    "    class GameState {",
    "        <<enumeration>>",
    "        IN_PROGRESS",
    "        WON",
    "        LOST",
    "        +afterSafeReveal(boolean) GameState",
    "        +afterMineReveal() GameState",
    "    }",
    "    class MinePlacementStrategy {",
    "        <<interface>>",
    "        +placeMines(int,int,int) Set~Integer~",
    "    }",
    "    class RandomMinePlacementStrategy {",
    "        -Random random",
    "        +placeMines(int,int,int) Set~Integer~",
    "    }",
    "    Game o-- Board",
    "    Game --> GameState",
    "    Board o-- Cell",
    "    Board ..> MinePlacementStrategy",
    "    MinePlacementStrategy <|.. RandomMinePlacementStrategy",
  ].join("\n"),
  classDiagramCaptionMD:
    "The engine has one aggregate root (**Game**) and one board aggregate (**Board**). Board owns the cell matrix and reveal algorithm; Game owns the state transition from **IN_PROGRESS** to **WON** or **LOST**.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Player",
    "    participant Game",
    "    participant Board",
    "    participant Cell",
    "    Player->>Game: reveal(row, col)",
    "    Game->>Game: verify state is IN_PROGRESS",
    "    Game->>Board: isMineAt(row, col)",
    "    Board-->>Game: mine or safe",
    "    Game->>Board: reveal(row, col)",
    "    alt clicked mine",
    "        Board->>Cell: reveal mine",
    "        Board-->>Game: revealed mine cell",
    "        Game->>Game: state becomes LOST",
    "        Game->>Board: revealAllMines",
    "    else clicked zero safe cell",
    "        Board->>Board: BFS flood-fill zero region",
    "        Board->>Cell: reveal zero cells and numbered boundary",
    "        Board-->>Game: revealed safe cells",
    "        Game->>Game: state becomes WON if no hidden safe cells remain",
    "    else clicked numbered safe cell",
    "        Board->>Cell: reveal single cell",
    "        Board-->>Game: revealed one cell",
    "        Game->>Game: remain IN_PROGRESS unless board is complete",
    "    end",
    "    Game-->>Player: state and revealed cells",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Reveal is the only operation that can end the game. Flagging changes cell annotations, while reveal drives the state-machine transition and delegates flood-fill to Board.",

  entities: [
    {
      name: "Game",
      responsibilityMD:
        "Aggregate root for one play session. It serializes player actions, delegates board operations, and owns the sticky state transition from **IN_PROGRESS** to **WON** or **LOST**.",
      attributes: ["board", "state"],
    },
    {
      name: "Board",
      responsibilityMD:
        "Owns the grid, validates coordinates, places mines through the strategy, computes adjacent counts, and implements iterative flood-fill reveal.",
      attributes: ["rows", "cols", "cells", "mineCount"],
    },
    {
      name: "Cell",
      responsibilityMD:
        "Represents one coordinate with mine, revealed, flagged, and adjacent-mine state. It rejects invalid local transitions such as flagging a revealed cell.",
      attributes: ["row", "col", "mine", "revealed", "flagged", "adjacentMines"],
    },
    {
      name: "GameState",
      responsibilityMD:
        "Enum-backed state machine. It exposes transition methods so terminal-state stickiness and safe-reveal behavior are centralized.",
      attributes: ["IN_PROGRESS", "WON", "LOST"],
    },
    {
      name: "MinePlacementStrategy",
      responsibilityMD:
        "Strategy interface for choosing mine positions. Random, fixed, first-click-safe, or difficulty-weighted placement can all implement the same contract.",
      attributes: ["placeMines(rows, cols, mineCount)"],
    },
    {
      name: "RandomMinePlacementStrategy",
      responsibilityMD:
        "Default production strategy. It samples unique flattened cell positions until the requested mine count is reached.",
      attributes: ["random"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**GameState** captures the state machine explicitly. **Game** asks the enum for transitions, so **WON** and **LOST** remain terminal and action validation is simple.",
    },
    {
      name: "Factory Method",
      whyMD:
        "**Board.create** and **Game.newGame** centralize construction, validation, mine placement, and adjacent-count calculation. Callers do not assemble a half-built board.",
    },
    {
      name: "Strategy",
      whyMD:
        "**MinePlacementStrategy** separates board rules from mine generation. Tests can inject fixed positions while production injects **RandomMinePlacementStrategy**.",
    },
  ],

  designSteps: [
    {
      title: "Model cell state tightly",
      detailMD:
        "A **Cell** owns only local facts: coordinate, mine flag, reveal flag, player flag, and adjacent count. It rejects invalid transitions such as flagging after reveal.",
      code: [
        "public boolean reveal() {",
        "    if (flagged) {",
        "        throw new IllegalStateException(\"Cannot reveal a flagged cell\");",
        "    }",
        "    if (revealed) {",
        "        return false;",
        "    }",
        "    revealed = true;",
        "    return true;",
        "}",
      ].join("\n"),
    },
    {
      title: "Create the board through a factory method",
      detailMD:
        "**Board.create** validates dimensions, asks the placement strategy for mine positions, sets mines, and computes all adjacent counts before returning a playable board.",
      code: [
        "public static Board create(int rows, int cols, int mineCount, MinePlacementStrategy strategy) {",
        "    Board board = new Board(rows, cols, mineCount);",
        "    Set<Integer> positions = strategy.placeMines(rows, cols, mineCount);",
        "    board.placeMines(positions);",
        "    board.computeAdjacentMineCounts();",
        "    return board;",
        "}",
      ].join("\n"),
    },
    {
      title: "Compute counts once after mine placement",
      detailMD:
        "Each safe cell scans the eight neighbors once. Counts become immutable gameplay data until a new board is created.",
      code: [
        "private int countAdjacentMines(int row, int col) {",
        "    int count = 0;",
        "    for (Cell neighbor : neighborsOf(row, col)) {",
        "        if (neighbor.isMine()) {",
        "            count++;",
        "        }",
        "    }",
        "    return count;",
        "}",
      ].join("\n"),
    },
    {
      title: "Use iterative flood-fill for zero cells",
      detailMD:
        "Reveal starts at the clicked cell. Numbered safe cells stop immediately; zero cells enter a queue, reveal connected zero cells, and reveal the numbered boundary without expanding through it.",
      code: [
        "while (!queue.isEmpty()) {",
        "    Cell current = queue.removeFirst();",
        "    current.reveal();",
        "    if (current.getAdjacentMines() != 0) {",
        "        continue;",
        "    }",
        "    for (Cell neighbor : neighborsOf(current.getRow(), current.getCol())) {",
        "        addZeroToQueueOrRevealBoundaryNumber(neighbor);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Keep game state transitions in Game",
      detailMD:
        "**Board** knows reveal mechanics, but **Game** decides what the reveal means. Mine click means **LOST**; all safe cells revealed means **WON**; otherwise remain **IN_PROGRESS**.",
      code: [
        "if (clickedMine) {",
        "    state = state.afterMineReveal();",
        "    board.revealAllMines();",
        "} else {",
        "    state = state.afterSafeReveal(board.allSafeCellsRevealed());",
        "}",
      ].join("\n"),
    },
    {
      title: "Treat flags as annotations, not truth",
      detailMD:
        "A flag prevents accidental reveal of a hidden cell, but it does not prove a mine and it never drives the win condition. This prevents false wins from lucky flag placement.",
    },
  ],

  implementation: [
    {
      filename: "GameState.java",
      language: "java",
      content: [
        "public enum GameState {",
        "    IN_PROGRESS,",
        "    WON,",
        "    LOST;",
        "",
        "    public boolean isTerminal() {",
        "        return this == WON || this == LOST;",
        "    }",
        "",
        "    public GameState afterSafeReveal(boolean allSafeCellsRevealed) {",
        "        if (this != IN_PROGRESS) {",
        "            return this;",
        "        }",
        "        return allSafeCellsRevealed ? WON : IN_PROGRESS;",
        "    }",
        "",
        "    public GameState afterMineReveal() {",
        "        if (this != IN_PROGRESS) {",
        "            return this;",
        "        }",
        "        return LOST;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Cell.java",
      language: "java",
      content: [
        "public class Cell {",
        "    private final int row;",
        "    private final int col;",
        "    private boolean mine;",
        "    private boolean revealed;",
        "    private boolean flagged;",
        "    private int adjacentMines;",
        "",
        "    public Cell(int row, int col) {",
        "        this.row = row;",
        "        this.col = col;",
        "    }",
        "",
        "    public int getRow() {",
        "        return row;",
        "    }",
        "",
        "    public int getCol() {",
        "        return col;",
        "    }",
        "",
        "    public boolean isMine() {",
        "        return mine;",
        "    }",
        "",
        "    public boolean isRevealed() {",
        "        return revealed;",
        "    }",
        "",
        "    public boolean isFlagged() {",
        "        return flagged;",
        "    }",
        "",
        "    public int getAdjacentMines() {",
        "        return adjacentMines;",
        "    }",
        "",
        "    void setMine(boolean mine) {",
        "        this.mine = mine;",
        "    }",
        "",
        "    void setAdjacentMines(int adjacentMines) {",
        "        this.adjacentMines = adjacentMines;",
        "    }",
        "",
        "    public boolean reveal() {",
        "        if (flagged) {",
        "            throw new IllegalStateException(\"Cannot reveal a flagged cell\");",
        "        }",
        "        if (revealed) {",
        "            return false;",
        "        }",
        "        revealed = true;",
        "        return true;",
        "    }",
        "",
        "    public void toggleFlag() {",
        "        if (revealed) {",
        "            throw new IllegalStateException(\"Cannot flag a revealed cell\");",
        "        }",
        "        flagged = !flagged;",
        "    }",
        "",
        "    void revealForLoss() {",
        "        flagged = false;",
        "        revealed = true;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "MinePlacementStrategy.java",
      language: "java",
      content: [
        "import java.util.Set;",
        "",
        "public interface MinePlacementStrategy {",
        "    Set<Integer> placeMines(int rows, int cols, int mineCount);",
        "}",
      ].join("\n"),
    },
    {
      filename: "RandomMinePlacementStrategy.java",
      language: "java",
      content: [
        "import java.util.HashSet;",
        "import java.util.Random;",
        "import java.util.Set;",
        "",
        "public class RandomMinePlacementStrategy implements MinePlacementStrategy {",
        "    private final Random random;",
        "",
        "    public RandomMinePlacementStrategy() {",
        "        this(new Random());",
        "    }",
        "",
        "    public RandomMinePlacementStrategy(Random random) {",
        "        if (random == null) {",
        "            throw new IllegalArgumentException(\"random must not be null\");",
        "        }",
        "        this.random = random;",
        "    }",
        "",
        "    @Override",
        "    public Set<Integer> placeMines(int rows, int cols, int mineCount) {",
        "        int totalCells = rows * cols;",
        "        Set<Integer> positions = new HashSet<>();",
        "        while (positions.size() < mineCount) {",
        "            positions.add(random.nextInt(totalCells));",
        "        }",
        "        return positions;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Board.java",
      language: "java",
      content: [
        "import java.util.ArrayDeque;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.Deque;",
        "import java.util.List;",
        "import java.util.Set;",
        "",
        "public class Board {",
        "    private static final int[] DR = {-1, -1, -1, 0, 0, 1, 1, 1};",
        "    private static final int[] DC = {-1, 0, 1, -1, 1, -1, 0, 1};",
        "",
        "    private final int rows;",
        "    private final int cols;",
        "    private final Cell[][] cells;",
        "    private final int mineCount;",
        "",
        "    private Board(int rows, int cols, int mineCount) {",
        "        this.rows = rows;",
        "        this.cols = cols;",
        "        this.mineCount = mineCount;",
        "        this.cells = new Cell[rows][cols];",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                cells[row][col] = new Cell(row, col);",
        "            }",
        "        }",
        "    }",
        "",
        "    public static Board create(int rows, int cols, int mineCount, MinePlacementStrategy strategy) {",
        "        if (rows <= 0 || cols <= 0) {",
        "            throw new IllegalArgumentException(\"Board dimensions must be positive\");",
        "        }",
        "        int totalCells = rows * cols;",
        "        if (mineCount < 0 || mineCount >= totalCells) {",
        "            throw new IllegalArgumentException(\"mineCount must be from 0 to totalCells - 1\");",
        "        }",
        "        if (strategy == null) {",
        "            throw new IllegalArgumentException(\"strategy must not be null\");",
        "        }",
        "",
        "        Board board = new Board(rows, cols, mineCount);",
        "        Set<Integer> positions = strategy.placeMines(rows, cols, mineCount);",
        "        board.placeMines(positions);",
        "        board.computeAdjacentMineCounts();",
        "        return board;",
        "    }",
        "",
        "    public List<Cell> reveal(int row, int col) {",
        "        Cell start = cellAt(row, col);",
        "        if (start.isFlagged()) {",
        "            throw new IllegalStateException(\"Cannot reveal a flagged cell\");",
        "        }",
        "        if (start.isRevealed()) {",
        "            return Collections.emptyList();",
        "        }",
        "        if (start.isMine()) {",
        "            start.reveal();",
        "            return Collections.singletonList(start);",
        "        }",
        "        return floodFillFrom(start);",
        "    }",
        "",
        "    public void toggleFlag(int row, int col) {",
        "        cellAt(row, col).toggleFlag();",
        "    }",
        "",
        "    public boolean isMineAt(int row, int col) {",
        "        return cellAt(row, col).isMine();",
        "    }",
        "",
        "    public boolean allSafeCellsRevealed() {",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                Cell cell = cells[row][col];",
        "                if (!cell.isMine() && !cell.isRevealed()) {",
        "                    return false;",
        "                }",
        "            }",
        "        }",
        "        return true;",
        "    }",
        "",
        "    public void revealAllMines() {",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                Cell cell = cells[row][col];",
        "                if (cell.isMine()) {",
        "                    cell.revealForLoss();",
        "                }",
        "            }",
        "        }",
        "    }",
        "",
        "    public Cell cellAt(int row, int col) {",
        "        validate(row, col);",
        "        return cells[row][col];",
        "    }",
        "",
        "    public int getRows() {",
        "        return rows;",
        "    }",
        "",
        "    public int getCols() {",
        "        return cols;",
        "    }",
        "",
        "    public int getMineCount() {",
        "        return mineCount;",
        "    }",
        "",
        "    public int remainingHiddenSafeCells() {",
        "        int count = 0;",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                Cell cell = cells[row][col];",
        "                if (!cell.isMine() && !cell.isRevealed()) {",
        "                    count++;",
        "                }",
        "            }",
        "        }",
        "        return count;",
        "    }",
        "",
        "    public int flagsPlaced() {",
        "        int count = 0;",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                if (cells[row][col].isFlagged()) {",
        "                    count++;",
        "                }",
        "            }",
        "        }",
        "        return count;",
        "    }",
        "",
        "    private List<Cell> floodFillFrom(Cell start) {",
        "        List<Cell> revealed = new ArrayList<>();",
        "        Deque<Cell> queue = new ArrayDeque<>();",
        "        boolean[][] queued = new boolean[rows][cols];",
        "        queue.addLast(start);",
        "        queued[start.getRow()][start.getCol()] = true;",
        "",
        "        while (!queue.isEmpty()) {",
        "            Cell current = queue.removeFirst();",
        "            if (current.isRevealed() || current.isFlagged() || current.isMine()) {",
        "                continue;",
        "            }",
        "            if (current.reveal()) {",
        "                revealed.add(current);",
        "            }",
        "            if (current.getAdjacentMines() != 0) {",
        "                continue;",
        "            }",
        "",
        "            for (Cell neighbor : neighborsOf(current.getRow(), current.getCol())) {",
        "                if (neighbor.isRevealed() || neighbor.isFlagged() || neighbor.isMine()) {",
        "                    continue;",
        "                }",
        "                if (neighbor.getAdjacentMines() == 0) {",
        "                    int row = neighbor.getRow();",
        "                    int col = neighbor.getCol();",
        "                    if (!queued[row][col]) {",
        "                        queued[row][col] = true;",
        "                        queue.addLast(neighbor);",
        "                    }",
        "                } else if (neighbor.reveal()) {",
        "                    revealed.add(neighbor);",
        "                }",
        "            }",
        "        }",
        "        return revealed;",
        "    }",
        "",
        "    private void placeMines(Set<Integer> positions) {",
        "        if (positions == null || positions.size() != mineCount) {",
        "            throw new IllegalArgumentException(\"Strategy must return exactly mineCount unique positions\");",
        "        }",
        "        int totalCells = rows * cols;",
        "        for (Integer position : positions) {",
        "            if (position == null || position < 0 || position >= totalCells) {",
        "                throw new IllegalArgumentException(\"Mine position out of bounds\");",
        "            }",
        "            int row = position / cols;",
        "            int col = position % cols;",
        "            cells[row][col].setMine(true);",
        "        }",
        "    }",
        "",
        "    private void computeAdjacentMineCounts() {",
        "        for (int row = 0; row < rows; row++) {",
        "            for (int col = 0; col < cols; col++) {",
        "                Cell cell = cells[row][col];",
        "                if (!cell.isMine()) {",
        "                    cell.setAdjacentMines(countAdjacentMines(row, col));",
        "                }",
        "            }",
        "        }",
        "    }",
        "",
        "    private int countAdjacentMines(int row, int col) {",
        "        int count = 0;",
        "        for (Cell neighbor : neighborsOf(row, col)) {",
        "            if (neighbor.isMine()) {",
        "                count++;",
        "            }",
        "        }",
        "        return count;",
        "    }",
        "",
        "    private List<Cell> neighborsOf(int row, int col) {",
        "        List<Cell> neighbors = new ArrayList<>();",
        "        for (int i = 0; i < DR.length; i++) {",
        "            int nextRow = row + DR[i];",
        "            int nextCol = col + DC[i];",
        "            if (isInside(nextRow, nextCol)) {",
        "                neighbors.add(cells[nextRow][nextCol]);",
        "            }",
        "        }",
        "        return neighbors;",
        "    }",
        "",
        "    private boolean isInside(int row, int col) {",
        "        return row >= 0 && row < rows && col >= 0 && col < cols;",
        "    }",
        "",
        "    private void validate(int row, int col) {",
        "        if (!isInside(row, col)) {",
        "            throw new IllegalArgumentException(\"Cell is outside the board\");",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        StringBuilder builder = new StringBuilder();",
        "        for (int row = 0; row < rows; row++) {",
        "            if (row > 0) {",
        "                builder.append(System.lineSeparator());",
        "            }",
        "            for (int col = 0; col < cols; col++) {",
        "                if (col > 0) {",
        "                    builder.append(' ');",
        "                }",
        "                builder.append(symbolFor(cells[row][col]));",
        "            }",
        "        }",
        "        return builder.toString();",
        "    }",
        "",
        "    private char symbolFor(Cell cell) {",
        "        if (cell.isFlagged()) {",
        "            return 'F';",
        "        }",
        "        if (!cell.isRevealed()) {",
        "            return '#';",
        "        }",
        "        if (cell.isMine()) {",
        "            return '*';",
        "        }",
        "        int adjacentMines = cell.getAdjacentMines();",
        "        return adjacentMines == 0 ? '.' : Character.forDigit(adjacentMines, 10);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Game.java",
      language: "java",
      content: [
        "import java.util.List;",
        "",
        "public class Game {",
        "    private final Board board;",
        "    private GameState state;",
        "",
        "    private Game(Board board) {",
        "        this.board = board;",
        "        this.state = GameState.IN_PROGRESS;",
        "    }",
        "",
        "    public static Game newGame(int rows, int cols, int mineCount, MinePlacementStrategy strategy) {",
        "        return new Game(Board.create(rows, cols, mineCount, strategy));",
        "    }",
        "",
        "    public synchronized List<Cell> reveal(int row, int col) {",
        "        ensureInProgress();",
        "        boolean clickedMine = board.isMineAt(row, col);",
        "        List<Cell> revealedCells = board.reveal(row, col);",
        "        if (clickedMine) {",
        "            state = state.afterMineReveal();",
        "            board.revealAllMines();",
        "        } else {",
        "            state = state.afterSafeReveal(board.allSafeCellsRevealed());",
        "        }",
        "        return revealedCells;",
        "    }",
        "",
        "    public synchronized void toggleFlag(int row, int col) {",
        "        ensureInProgress();",
        "        board.toggleFlag(row, col);",
        "    }",
        "",
        "    public synchronized GameState getState() {",
        "        return state;",
        "    }",
        "",
        "    public Board getBoard() {",
        "        return board;",
        "    }",
        "",
        "    private void ensureInProgress() {",
        "        if (state != GameState.IN_PROGRESS) {",
        "            throw new IllegalStateException(\"Game is already \" + state);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "GameState",
      detailMD:
        "Enum state machine with **IN_PROGRESS**, **WON**, and **LOST**. Transition helpers keep terminal states sticky and make **Game** read like a rule engine rather than a switch-heavy controller.",
    },
    {
      className: "Cell",
      detailMD:
        "One grid square. It stores coordinates, mine status, reveal status, flag status, and adjacent count. Local invariant checks prevent revealing flagged cells and flagging revealed cells.",
    },
    {
      className: "MinePlacementStrategy",
      detailMD:
        "Strategy interface for mine placement. Board construction depends on this abstraction, enabling deterministic tests and alternative placement policies without changing reveal logic.",
    },
    {
      className: "RandomMinePlacementStrategy",
      detailMD:
        "Default production strategy. It samples flattened cell ids into a set, which naturally prevents duplicate mines while keeping placement independent of Board internals.",
    },
    {
      className: "Board",
      detailMD:
        "Owns the matrix and all coordinate-sensitive rules: factory construction, mine validation, adjacent-count calculation, flag toggling, flood-fill reveal, win-condition support, and rendering-friendly text output.",
    },
    {
      className: "Game",
      detailMD:
        "Session facade and state owner. It serializes public actions with **synchronized**, delegates mechanics to **Board**, and updates **GameState** after every reveal.",
    },
  ],

  dryRun: {
    inputMD:
      "4×4 board with fixed mines at flattened positions **0** and **1**: mines at **(0,0)** and **(0,1)**. Actions: flag (0,0), reveal (3,3), reveal (0,1).",
    columns: ["Step", "Action", "Board operation", "Revealed cells", "State", "Why"],
    rows: [
      ["1", "create board", "place mines and compute counts", "0", "IN_PROGRESS", "Counts around the top-left mines are prepared before play."],
      ["2", "toggleFlag(0,0)", "mark hidden cell as flagged", "0", "IN_PROGRESS", "Flags are annotations and do not affect the win condition."],
      ["3", "reveal(3,3)", "BFS flood-fill from a zero cell", "safe zero region plus numbered boundary", "IN_PROGRESS", "Flood-fill reveals connected empty cells but stops at counts near mines."],
      ["4", "reveal(0,1)", "clicked mine", "mine cell, then all mines", "LOST", "Mine reveal moves the state machine to the terminal loss state."],
      ["5", "toggleFlag(2,2)", "rejected", "0", "LOST", "Terminal states reject further player actions."],
    ],
    narrativeMD:
      "The important row is step 3: a zero cell reveal does not scan the whole board blindly. It performs a bounded graph traversal over adjacent safe zero cells and reveals only the numbered border needed by the UI.",
  },

  complexity: [
    {
      operation: "Board creation",
      time: "O(R × C)",
      space: "O(R × C)",
      note: "Allocates every cell, places mines, and computes counts by checking up to eight neighbors per cell.",
    },
    {
      operation: "reveal numbered cell",
      time: "O(1)",
      space: "O(1)",
      note: "A numbered safe cell reveals itself and stops.",
    },
    {
      operation: "reveal zero cell with flood-fill",
      time: "O(R × C) worst case",
      space: "O(R × C) worst case",
      note: "An empty board can reveal every safe cell and queue a large connected component.",
    },
    {
      operation: "toggleFlag",
      time: "O(1)",
      space: "O(1)",
      note: "Coordinate validation plus one local state flip.",
    },
    {
      operation: "win check",
      time: "O(R × C)",
      space: "O(1)",
      note: "The simple implementation scans for hidden safe cells; a counter can make this O(1).",
    },
  ],
  complexityNotesMD:
    "R is row count and C is column count. Flood-fill is linear in the number of cells it reveals, which is optimal. If win checks become hot, maintain a **hiddenSafeCells** counter and decrement it by the number of newly revealed safe cells returned from Board.reveal.",

  extensibility: [
    {
      label: "First-click-safe mode",
      detailMD:
        "Delay mine placement until the first reveal and pass the first coordinate to a specialized **MinePlacementStrategy** that excludes that cell and optionally its neighbors.",
    },
    {
      label: "Difficulty presets",
      detailMD:
        "Add a small factory around **Game.newGame** that maps beginner, intermediate, and expert presets to row, column, mine-count, and placement-strategy choices.",
    },
    {
      label: "Undo or replay",
      detailMD:
        "Store reveal and flag commands as events. Because **Board.reveal** returns changed cells, replay logs can reconstruct visible state step by step.",
    },
    {
      label: "Hints and solver support",
      detailMD:
        "Add a read-only analyzer that consumes Board snapshots. It should never mutate **Cell** directly; all gameplay changes still go through **Game**.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Recursive DFS reveal",
      detailMD:
        "Implement zero-cell expansion with a recursive helper that visits neighbors until no more zero cells remain.",
      tradeoffsMD:
        "The code is short, but a large empty board can overflow the Java stack. Iterative BFS is safer for production and interviews.",
    },
    {
      name: "Counter-based win tracking",
      detailMD:
        "Keep **hiddenSafeCells** in Game or Board and decrement it by the count of newly revealed non-mine cells returned from reveal.",
      tradeoffsMD:
        "This makes win checks O(1), but the counter must stay exactly consistent with idempotent reveal calls and boundary reveals.",
    },
    {
      name: "Immutable board snapshots",
      detailMD:
        "Expose immutable DTO snapshots instead of returning mutable **Cell** references to callers.",
      tradeoffsMD:
        "Cleaner API boundaries for a service, but more object allocation for every render or poll.",
    },
  ],

  commonMistakes: [
    "Winning when all mines are flagged instead of when all safe cells are revealed.",
    "Letting flood-fill reveal mines or expand through numbered cells rather than stopping at the boundary.",
    "Using recursive DFS without discussing stack overflow on large empty boards.",
    "Forgetting to skip flagged cells during reveal, which makes flags useless as player protection.",
    "Recomputing adjacent counts on every reveal instead of once after mine placement.",
    "Allowing actions after **WON** or **LOST**, which breaks the state machine.",
    "Hard-coding random mine placement inside Board so deterministic tests become awkward.",
  ],

  followUps: [
    {
      question: "How would you guarantee the first click is safe?",
      answerMD:
        "Delay board finalization until the first reveal. Then call a placement strategy that excludes the first cell, and optionally all eight neighbors, before computing adjacent counts.",
    },
    {
      question: "How do you avoid stack overflow during reveal?",
      answerMD:
        "Use an explicit queue or stack. The reference uses BFS with **ArrayDeque**, so the heap holds traversal state instead of the call stack.",
    },
    {
      question: "Why is flagging not part of the win condition?",
      answerMD:
        "Flags are user guesses. A player can flag any hidden cell, including safe cells, so correctness must be based on revealed safe cells rather than annotations.",
    },
    {
      question: "How would you make win checking O(1)?",
      answerMD:
        "Maintain a remaining hidden safe-cell counter. Board.reveal returns the newly revealed cells, and Game subtracts the safe-cell count after each reveal.",
    },
    {
      question: "Where would a timer and leaderboard live?",
      answerMD:
        "Outside the core engine. A session service can start a timer when the first reveal succeeds and submit results after **WON** without changing Board or Cell.",
    },
  ],

  productionConsiderations: [
    {
      label: "API boundary",
      detailMD:
        "Expose immutable board snapshots to clients instead of raw **Cell** objects so external code cannot mutate game state behind **Game**.",
    },
    {
      label: "Concurrency",
      detailMD:
        "Serialize actions per game id. The Java sample synchronizes **Game.reveal** and **Game.toggleFlag**; a distributed service would use a row lock or per-game actor.",
    },
    {
      label: "Fair randomness",
      detailMD:
        "Use a seedable random source for replayable games and store the seed with the game session for audits, debugging, and cheat investigation.",
    },
    {
      label: "Persistence",
      detailMD:
        "Persist the mine layout, revealed cells, flags, state, and start time. Do not rely on recomputing a random board after restart.",
    },
    {
      label: "Abuse prevention",
      detailMD:
        "Server-authoritative games should never send hidden mine positions to the client before loss or completion; send only visible snapshots.",
    },
  ],

  interviewNotes: [
    "Did you identify flood-fill as the core algorithmic risk and implement it without revealing mines?",
    "Did you model **IN_PROGRESS**, **WON**, and **LOST** as explicit states with terminal-state guards?",
    "Did you keep mine placement pluggable so tests can be deterministic?",
    "Did you distinguish flags from reveal truth in the win condition?",
    "Did you keep UI, persistence, timer, and leaderboard concerns outside the core engine?",
  ],

  quiz: [
    {
      question: "When should Minesweeper transition to **WON**?",
      options: [
        "When every non-mine cell has been revealed",
        "When every mine has been flagged",
        "When the player reveals any zero-count cell",
        "When the number of flags equals the number of mines",
      ],
      answerIndex: 0,
      explanationMD:
        "Flags are guesses. The reliable win condition is that there are no hidden safe cells left.",
    },
    {
      question: "What should flood-fill do when it reaches a numbered safe cell?",
      options: [
        "Reveal it and stop expanding from that cell",
        "Reveal it and keep expanding through all of its neighbors",
        "Hide it until the user clicks it directly",
        "Convert it into a zero-count cell",
      ],
      answerIndex: 0,
      explanationMD:
        "Numbered cells form the boundary around empty regions. They become visible but do not continue the zero-cell traversal.",
    },
    {
      question: "Why inject **MinePlacementStrategy**?",
      options: [
        "To make mine placement deterministic in tests and swappable in production",
        "To make adjacent-count calculation unnecessary",
        "To let flags reveal nearby mines automatically",
        "To avoid storing cells in a grid",
      ],
      answerIndex: 0,
      explanationMD:
        "Strategy isolates the variable placement policy from Board rules such as count calculation and flood-fill.",
    },
    {
      question: "What happens when a player tries to reveal a flagged hidden cell in this design?",
      options: [
        "The reveal is rejected with an error",
        "The cell is revealed and the flag is removed",
        "The game immediately becomes WON",
        "The board silently ignores all future reveals",
      ],
      answerIndex: 0,
      explanationMD:
        "A flag is a player safety marker. Rejecting reveal protects the player from accidental clicks and keeps state explicit.",
    },
    {
      question: "Why prefer iterative BFS over recursive DFS for the reference implementation?",
      options: [
        "It avoids call-stack overflow on large empty boards",
        "It changes the worst-case time from O(R × C) to O(1)",
        "It removes the need for visited tracking",
        "It automatically guarantees first-click safety",
      ],
      answerIndex: 0,
      explanationMD:
        "Both BFS and DFS are linear in the revealed area, but an explicit queue is safer than deep recursion in Java.",
    },
  ],

  practiceVariants: [
    {
      title: "First-click-safe Minesweeper",
      detailMD:
        "Delay mine placement until the first reveal and ensure the first clicked cell is never a mine. For an advanced version, also keep its neighbors mine-free.",
      difficulty: "Intermediate",
    },
    {
      title: "Counter-based win detection",
      detailMD:
        "Replace the O(R × C) win scan with a remaining-safe-cells counter updated from Board.reveal results. Prove repeated reveals do not double-decrement it.",
      difficulty: "Beginner",
    },
    {
      title: "Multiplayer race mode",
      detailMD:
        "Let multiple players reveal cells on the same board. Decide how to serialize actions, score safe reveals, and handle the first player who clicks a mine.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the win condition in Minesweeper LLD?",
      back: "All non-mine cells are revealed. Correct flags alone do not win the game.",
    },
    {
      front: "What does flood-fill reveal?",
      back: "The connected zero-count safe region plus adjacent numbered safe boundary cells; it never reveals mines or flagged cells.",
    },
    {
      front: "Which object owns the state machine?",
      back: "**Game** owns **GameState** and transitions from **IN_PROGRESS** to **WON** or **LOST** after reveal calls.",
    },
    {
      front: "Which pattern makes mine placement testable?",
      back: "Strategy, via **MinePlacementStrategy** and implementations such as **RandomMinePlacementStrategy**.",
    },
    {
      front: "Why is **Board.create** a Factory Method seam?",
      back: "It centralizes validation, mine placement, and adjacent-count setup so callers receive a fully valid board.",
    },
    {
      front: "Why avoid recursive DFS in Java Minesweeper?",
      back: "A large empty component can create deep recursion and overflow the stack; iterative BFS uses heap-backed queue storage.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Game, Board, Cell, GameState, MinePlacementStrategy, RandomMinePlacementStrategy.",
    "",
    "**Patterns:** State for **IN_PROGRESS/WON/LOST**, Strategy for mine placement, Factory Method for board and game creation.",
    "",
    "**Core flow:** reveal = validate state → check clicked mine → Board.reveal → update state → reveal all mines on loss or check safe completion.",
    "",
    "**Flood-fill rule:** numbered safe cell reveals one cell; zero safe cell expands through zero neighbors and reveals numbered boundaries; flagged cells are skipped.",
    "",
    "**Win rule:** all safe cells revealed. Flag count is not a source of truth.",
    "",
    "**Complexity:** creation O(R×C), numbered reveal O(1), flood-fill O(R×C) worst case, flag O(1).",
  ].join("\n"),

  references: [
    {
      title: "Head First Design Patterns (State, Strategy, Factory Method)",
      kind: "Book",
      author: "Freeman & Robson",
    },
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
    {
      title: "CP-Algorithms — Breadth First Search",
      kind: "Docs",
      url: "https://cp-algorithms.com/graph/breadth-first-search.html",
    },
  ],

  relatedProblems: [
    { slug: "tic-tac-toe", note: "Another grid game focused on state transitions and win detection." },
    { slug: "snake-and-ladder", note: "Turn-based game engine with Strategy-driven randomness and terminal game state." },
    { slug: "ludo", note: "Richer board game state machine with player turns and movement rules." },
  ],
};
