import type { LLDProblemContent } from "../types";

export const movieBooking: LLDProblemContent = {
  slug: "movie-booking",

  statementMD: [
    "Design the object model for a **movie ticket booking system** like BookMyShow.",
    "Customers browse cinemas, screens, and shows, inspect a seat map with seat",
    "types, temporarily hold seats, pay for the booking, and then receive a",
    "confirmed ticket.",
    "",
    "The hard part is not listing movies. The hard part is preserving the invariant",
    "that **one physical seat in one show can be sold to at most one booking**, even",
    "when two users click the same seat at nearly the same time.",
  ].join("\n"),

  businessContextMD: [
    "Movie booking is a favorite intermediate LLD problem because it combines",
    "domain modelling with a real concurrency race. A candidate must model cinemas,",
    "screens, shows, seats, seat types, holds, payments, and booking lifecycle",
    "without drifting into high-level distributed systems.",
    "",
    "Interviewers expect a clean state machine for bookings, a thread-safe seat",
    "locking provider with expiry, strategy seams for pricing and seat allocation,",
    "observer hooks for seat availability updates, and a small controller facade",
    "that keeps the flow easy to reason about.",
  ].join("\n"),

  functionalRequirements: [
    "Support cinemas with screens, and screens with scheduled shows for a movie.",
    "Model seats per show because the same physical seat is available independently across different shows.",
    "Represent seat types such as SILVER, GOLD, and PLATINUM, with different prices.",
    "Let a customer select specific seats or let the system allocate seats using a strategy.",
    "Place a temporary hold on selected seats before payment, with a timeout.",
    "Prevent two customers from holding or booking the same seat for the same show concurrently.",
    "Move bookings through Created, SeatsHeld, Confirmed, Expired, and Cancelled states.",
    "Confirm a booking only after payment succeeds and the seat hold is still valid.",
    "Notify availability observers when seats are held, released, expired, or booked.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Correctness under concurrency",
      detailMD:
        "The check for seat availability and the write of the hold must be atomic. If User A and User B race for A1, exactly one hold can win.",
    },
    {
      label: "Short-lived holds",
      detailMD:
        "Seats should not remain blocked forever if a customer abandons checkout. Holds expire after a configured duration and seats return to availability.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New pricing rules, allocation policies, payment providers, and notification channels should be additive classes, not edits to the core booking flow.",
    },
    {
      label: "Low latency for seat selection",
      detailMD:
        "Seat map reads and hold attempts should be in-memory and fast for an interview design. A production system can persist the same aggregate with row locks.",
    },
    {
      label: "Auditable lifecycle",
      detailMD:
        "The booking state machine should make every transition explicit so expiry, cancellation, and confirmation can be traced and tested.",
    },
  ],

  requirementClarification: [
    {
      question: "Is a seat tied to a cinema screen or to a show?",
      answerMD:
        "The physical seat belongs to a screen, but availability belongs to a show. The same A1 can be booked for a 10 AM show and remain free for a 1 PM show.",
    },
    {
      question: "Can users hold seats without paying immediately?",
      answerMD:
        "Yes. A booking starts in **Created**, moves to **SeatsHeld** after the lock succeeds, and then becomes **Confirmed** only after successful payment.",
    },
    {
      question: "What happens when the hold timeout expires during checkout?",
      answerMD:
        "The booking becomes **Expired**, its seat locks are released, and any later payment attempt must fail or be refunded by the payment workflow.",
    },
    {
      question: "Do we need to model movie search, offers, coupons, or food ordering?",
      answerMD:
        "Not in the core design. Keep the scope to shows, seats, holds, booking lifecycle, pricing, and payment. Coupons and snacks are extensions.",
    },
    {
      question: "Should the design support manual seat choice and auto-allocation?",
      answerMD:
        "Yes. Manual choice goes through **holdSpecificSeats**; auto-allocation is a pluggable **SeatAllocationStrategy**.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Seat {",
    "        -String id",
    "        -SeatType type",
    "        -SeatStatus status",
    "        -String bookingId",
    "        +hold(String) void",
    "        +markBooked(String) void",
    "        +releaseHold(String) void",
    "    }",
    "    class Show {",
    "        -String id",
    "        -String movieTitle",
    "        -String cinemaName",
    "        -String screenName",
    "        -Map~String,Seat~ seatsById",
    "        -List~SeatAvailabilityObserver~ observers",
    "        +availableSeats(SeatType) List~Seat~",
    "        +holdSeats(List~String~, String) void",
    "        +confirmSeats(List~String~, String) void",
    "    }",
    "    class Booking {",
    "        -String id",
    "        -String customerId",
    "        -String showId",
    "        -List~String~ seatIds",
    "        -BookingState state",
    "        +markSeatsHeld() void",
    "        +confirm() void",
    "        +expire() void",
    "        +cancel() void",
    "    }",
    "    class BookingState {",
    "        <<interface>>",
    "        +status() BookingStatus",
    "        +hold(Booking) void",
    "        +confirm(Booking) void",
    "        +expire(Booking) void",
    "        +cancel(Booking) void",
    "    }",
    "    class SeatLockProvider {",
    "        -Map~String,SeatHold~ holds",
    "        -Duration holdDuration",
    "        +lockSeats(Show, List~String~, String) boolean",
    "        +validateLocks(Show, List~String~, String) boolean",
    "        +releaseLocks(Show, List~String~, String, String) void",
    "    }",
    "    class PricingStrategy {",
    "        <<interface>>",
    "        +calculatePrice(Show, List~Seat~) long",
    "    }",
    "    class SeatAllocationStrategy {",
    "        <<interface>>",
    "        +allocateSeats(Show, SeatType, int) List~String~",
    "    }",
    "    class BookingService {",
    "        -Map~String,Show~ shows",
    "        -Map~String,Booking~ bookings",
    "        -SeatLockProvider lockProvider",
    "        -PricingStrategy pricingStrategy",
    "        +getInstance() BookingService",
    "        +holdSpecificSeats(String, String, List~String~) Booking",
    "        +confirmBooking(String) Booking",
    "    }",
    "    class SeatAvailabilityObserver {",
    "        <<interface>>",
    "        +onSeatAvailabilityChanged(Show, String, List~String~, Map) void",
    "    }",
    "    class Main",
    "    Show o-- Seat",
    "    Show o-- SeatAvailabilityObserver",
    "    Booking --> BookingState",
    "    BookingService --> SeatLockProvider",
    "    BookingService --> PricingStrategy",
    "    BookingService --> SeatAllocationStrategy",
    "    BookingService --> Show",
    "    BookingService --> Booking",
    "    SeatLockProvider --> Show",
    "    PricingStrategy <|.. SeatTypePricingStrategy",
    "    SeatAllocationStrategy <|.. ContiguousSeatAllocationStrategy",
    "    BookingState <|.. CreatedState",
    "    BookingState <|.. SeatsHeldState",
    "    BookingState <|.. ConfirmedState",
    "    BookingState <|.. ExpiredState",
    "    BookingState <|.. CancelledState",
  ].join("\n"),
  classDiagramCaptionMD:
    "The aggregate is centered on **Show** availability and **Booking** lifecycle. **SeatLockProvider** owns concurrency, while pricing and allocation stay behind strategies.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor UserA",
    "    actor UserB",
    "    participant Service as BookingService",
    "    participant Allocator as SeatAllocationStrategy",
    "    participant Locks as SeatLockProvider",
    "    participant ShowObj as Show",
    "    participant Pay as PaymentGateway",
    "    UserA->>Service: holdSpecificSeats(A1)",
    "    UserB->>Service: holdSpecificSeats(A1)",
    "    Service->>Locks: lockSeats(show, A1, bookingA)",
    "    Locks->>ShowObj: holdSeats(A1, bookingA)",
    "    Locks-->>Service: true",
    "    Service-->>UserA: Booking SeatsHeld",
    "    Service->>Locks: lockSeats(show, A1, bookingB)",
    "    Locks-->>Service: false",
    "    Service-->>UserB: seat unavailable",
    "    UserA->>Service: confirmBooking(bookingA)",
    "    Service->>Pay: charge(amount)",
    "    Pay-->>Service: success",
    "    Service->>Locks: consumeLocks(show, A1, bookingA)",
    "    Service->>ShowObj: confirmSeats(A1, bookingA)",
    "    Service-->>UserA: Booking Confirmed",
    "    Note over UserA,UserB: only one user can move from SeatsHeld to Confirmed for A1",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Both users may read the same free seat, but the synchronized lock provider serializes the hold attempt. The loser never receives a valid hold.",

  entities: [
    {
      name: "Cinema",
      responsibilityMD:
        "Venue that owns screens. The implementation keeps cinema details on **Show** for brevity, but the model can split it into a first-class aggregate.",
      attributes: ["id", "name", "city", "screens"],
    },
    {
      name: "Screen",
      responsibilityMD:
        "Auditorium inside a cinema. It owns the physical seat layout; each scheduled show receives its own availability view.",
      attributes: ["id", "name", "seatLayout"],
    },
    {
      name: "Show",
      responsibilityMD:
        "A movie scheduled on a screen at a time. Owns show-specific seats, exposes availability snapshots, and notifies observers on seat changes.",
      attributes: ["id", "movieTitle", "cinemaName", "screenName", "startTime", "seatsById"],
    },
    {
      name: "Seat",
      responsibilityMD:
        "Represents one seat for one show. Guards status transitions from AVAILABLE to HELD to BOOKED, and remembers the booking that currently holds it.",
      attributes: ["id", "type", "status", "bookingId"],
    },
    {
      name: "Booking",
      responsibilityMD:
        "Customer checkout session. Holds selected seat ids, amount, payment status, and a **BookingState** object that enforces legal transitions.",
      attributes: ["id", "customerId", "showId", "seatIds", "amountInPaise", "state"],
    },
    {
      name: "SeatLockProvider",
      responsibilityMD:
        "Thread-safe lock registry keyed by show id and seat id. It atomically grants holds, validates holds before confirmation, and releases expired locks.",
      attributes: ["holdDuration", "holds", "clock"],
    },
    {
      name: "PricingStrategy",
      responsibilityMD:
        "Calculates the payable amount for selected seats. The base implementation prices by seat type; surge, weekday, coupon, and member pricing are extensions.",
      attributes: ["calculatePrice(show, seats)"],
    },
    {
      name: "SeatAllocationStrategy",
      responsibilityMD:
        "Chooses seats when the customer asks for automatic allocation. The demo picks sorted seats of a preferred type, but the interface supports better policies.",
      attributes: ["allocateSeats(show, preferredType, count)"],
    },
    {
      name: "BookingService",
      responsibilityMD:
        "Singleton controller facade for registering shows, holding seats, confirming payment, expiring holds, and cancelling bookings.",
      attributes: ["shows", "bookings", "lockProvider", "pricingStrategy", "allocationStrategy"],
    },
  ],

  patternsUsed: [
    {
      name: "State",
      whyMD:
        "**BookingState** makes lifecycle rules explicit. **Created** can hold, **SeatsHeld** can confirm, expire, or cancel, and terminal states reject invalid transitions.",
    },
    {
      name: "Strategy",
      whyMD:
        "**PricingStrategy** varies price calculation and **SeatAllocationStrategy** varies seat choice. The booking flow asks interfaces instead of hard-coding policies.",
    },
    {
      name: "Observer",
      whyMD:
        "**SeatAvailabilityObserver** lets UI boards, analytics, or notifications react when seats are held, released, expired, or booked without coupling them to **Show**.",
    },
    {
      name: "Singleton",
      whyMD:
        "**BookingService.getInstance** exposes a single in-memory controller for the demo so every thread competes against the same booking and lock maps.",
    },
  ],

  designSteps: [
    {
      title: "Make show seats independent from physical seats",
      detailMD:
        "A screen has a physical layout, but each **Show** needs its own seat availability. Model seats inside the show instance so A1 for the morning show is independent from A1 for the evening show.",
    },
    {
      title: "Guard seat status inside the seat object",
      detailMD:
        "**Seat** owns the invariant that an available seat can become held, a held seat can become booked by the same booking, and an unrelated booking cannot steal it.",
      code: [
        "public synchronized void hold(String bookingId) {",
        "    if (status != SeatStatus.AVAILABLE) {",
        "        throw new IllegalStateException(\"Seat is not available\");",
        "    }",
        "    status = SeatStatus.HELD;",
        "    this.bookingId = bookingId;",
        "}",
      ].join("\n"),
    },
    {
      title: "Put the race in one synchronized lock provider",
      detailMD:
        "The critical section is check-then-hold. **SeatLockProvider.lockSeats** synchronizes the entire operation, removes expired holds first, rejects already-held or booked seats, and only then writes the hold.",
      code: [
        "public synchronized boolean lockSeats(Show show, List<String> seatIds, String bookingId) {",
        "    cleanupExpired(show);",
        "    for (String seatId : seatIds) {",
        "        if (show.getSeat(seatId).getStatus() != SeatStatus.AVAILABLE) {",
        "            return false;",
        "        }",
        "    }",
        "    show.holdSeats(seatIds, bookingId);",
        "    return true;",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent booking lifecycle with State",
      detailMD:
        "A booking starts in **Created**. A successful lock moves it to **SeatsHeld**. Payment success confirms it; timeout expires it; user abandonment cancels it.",
      code: [
        "public synchronized void confirm() {",
        "    if (paymentStatus != PaymentStatus.SUCCESS) {",
        "        throw new IllegalStateException(\"Payment must succeed before confirmation\");",
        "    }",
        "    state.confirm(this);",
        "}",
      ].join("\n"),
    },
    {
      title: "Separate policies from the booking flow",
      detailMD:
        "**PricingStrategy** decides the amount and **SeatAllocationStrategy** decides which seats to try. The service remains focused on orchestration and concurrency.",
    },
    {
      title: "Confirm only while the hold is still valid",
      detailMD:
        "During confirmation, the service charges payment, validates the lock again, consumes the lock, marks seats booked, and then transitions the booking to **Confirmed**.",
    },
    {
      title: "Notify availability after every seat change",
      detailMD:
        "**Show** calls observers with an availability snapshot after hold, release, expiry, or booking. This keeps UI refresh concerns out of the domain flow.",
    },
  ],

  implementation: [
    {
      filename: "Seat.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class Seat {",
        "    private final String id;",
        "    private final SeatType type;",
        "    private SeatStatus status;",
        "    private String bookingId;",
        "",
        "    public Seat(String id, SeatType type) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.type = Objects.requireNonNull(type, \"type\");",
        "        this.status = SeatStatus.AVAILABLE;",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public SeatType getType() {",
        "        return type;",
        "    }",
        "",
        "    public synchronized SeatStatus getStatus() {",
        "        return status;",
        "    }",
        "",
        "    public synchronized boolean isHeldBy(String bookingId) {",
        "        return status == SeatStatus.HELD && Objects.equals(this.bookingId, bookingId);",
        "    }",
        "",
        "    public synchronized void hold(String bookingId) {",
        "        if (status != SeatStatus.AVAILABLE) {",
        "            throw new IllegalStateException(\"Seat \" + id + \" is already \" + status);",
        "        }",
        "        this.status = SeatStatus.HELD;",
        "        this.bookingId = Objects.requireNonNull(bookingId, \"bookingId\");",
        "    }",
        "",
        "    public synchronized void markBooked(String bookingId) {",
        "        if (!isHeldBy(bookingId)) {",
        "            throw new IllegalStateException(\"Seat \" + id + \" is not held by booking \" + bookingId);",
        "        }",
        "        this.status = SeatStatus.BOOKED;",
        "    }",
        "",
        "    public synchronized void releaseHold(String bookingId) {",
        "        if (isHeldBy(bookingId)) {",
        "            this.status = SeatStatus.AVAILABLE;",
        "            this.bookingId = null;",
        "        }",
        "    }",
        "",
        "    public synchronized void releaseExpiredHold() {",
        "        if (status == SeatStatus.HELD) {",
        "            this.status = SeatStatus.AVAILABLE;",
        "            this.bookingId = null;",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public synchronized String toString() {",
        "        return id + \"(\" + type + \", \" + status + \")\";",
        "    }",
        "}",
        "",
        "enum SeatType {",
        "    SILVER, GOLD, PLATINUM",
        "}",
        "",
        "enum SeatStatus {",
        "    AVAILABLE, HELD, BOOKED",
        "}",
      ].join("\n"),
    },
    {
      filename: "Show.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.EnumMap;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class Show {",
        "    private final String id;",
        "    private final String movieTitle;",
        "    private final String cinemaName;",
        "    private final String screenName;",
        "    private final Instant startTime;",
        "    private final Map<String, Seat> seatsById = new LinkedHashMap<>();",
        "    private final List<SeatAvailabilityObserver> observers = new ArrayList<>();",
        "",
        "    public Show(String id, String movieTitle, String cinemaName, String screenName, Instant startTime, List<Seat> seats) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.movieTitle = Objects.requireNonNull(movieTitle, \"movieTitle\");",
        "        this.cinemaName = Objects.requireNonNull(cinemaName, \"cinemaName\");",
        "        this.screenName = Objects.requireNonNull(screenName, \"screenName\");",
        "        this.startTime = Objects.requireNonNull(startTime, \"startTime\");",
        "        for (Seat seat : seats) {",
        "            seatsById.put(seat.getId(), seat);",
        "        }",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getMovieTitle() {",
        "        return movieTitle;",
        "    }",
        "",
        "    public String getCinemaName() {",
        "        return cinemaName;",
        "    }",
        "",
        "    public String getScreenName() {",
        "        return screenName;",
        "    }",
        "",
        "    public Instant getStartTime() {",
        "        return startTime;",
        "    }",
        "",
        "    public synchronized Seat getSeat(String seatId) {",
        "        Seat seat = seatsById.get(seatId);",
        "        if (seat == null) {",
        "            throw new IllegalArgumentException(\"Unknown seat \" + seatId);",
        "        }",
        "        return seat;",
        "    }",
        "",
        "    public synchronized List<Seat> getSeats(List<String> seatIds) {",
        "        List<Seat> seats = new ArrayList<>();",
        "        for (String seatId : seatIds) {",
        "            seats.add(getSeat(seatId));",
        "        }",
        "        return Collections.unmodifiableList(seats);",
        "    }",
        "",
        "    public synchronized List<Seat> availableSeats(SeatType type) {",
        "        List<Seat> available = new ArrayList<>();",
        "        for (Seat seat : seatsById.values()) {",
        "            if (seat.getType() == type && seat.getStatus() == SeatStatus.AVAILABLE) {",
        "                available.add(seat);",
        "            }",
        "        }",
        "        return available;",
        "    }",
        "",
        "    public synchronized void holdSeats(List<String> seatIds, String bookingId) {",
        "        for (String seatId : seatIds) {",
        "            getSeat(seatId).hold(bookingId);",
        "        }",
        "        notifyObservers(\"held\", seatIds);",
        "    }",
        "",
        "    public synchronized void confirmSeats(List<String> seatIds, String bookingId) {",
        "        for (String seatId : seatIds) {",
        "            getSeat(seatId).markBooked(bookingId);",
        "        }",
        "        notifyObservers(\"booked\", seatIds);",
        "    }",
        "",
        "    public synchronized void releaseHold(List<String> seatIds, String bookingId) {",
        "        for (String seatId : seatIds) {",
        "            getSeat(seatId).releaseHold(bookingId);",
        "        }",
        "        notifyObservers(\"released\", seatIds);",
        "    }",
        "",
        "    public synchronized void releaseExpiredHold(List<String> seatIds) {",
        "        for (String seatId : seatIds) {",
        "            getSeat(seatId).releaseExpiredHold();",
        "        }",
        "        notifyObservers(\"expired\", seatIds);",
        "    }",
        "",
        "    public synchronized void addObserver(SeatAvailabilityObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public synchronized Map<SeatType, Integer> availabilitySnapshot() {",
        "        Map<SeatType, Integer> snapshot = new EnumMap<>(SeatType.class);",
        "        for (SeatType type : SeatType.values()) {",
        "            snapshot.put(type, 0);",
        "        }",
        "        for (Seat seat : seatsById.values()) {",
        "            if (seat.getStatus() == SeatStatus.AVAILABLE) {",
        "                snapshot.put(seat.getType(), snapshot.get(seat.getType()) + 1);",
        "            }",
        "        }",
        "        return Collections.unmodifiableMap(snapshot);",
        "    }",
        "",
        "    private void notifyObservers(String event, List<String> seatIds) {",
        "        Map<SeatType, Integer> snapshot = availabilitySnapshot();",
        "        List<SeatAvailabilityObserver> copy = new ArrayList<>(observers);",
        "        for (SeatAvailabilityObserver observer : copy) {",
        "            observer.onSeatAvailabilityChanged(this, event, seatIds, snapshot);",
        "        }",
        "    }",
        "}",
        "",
        "interface SeatAvailabilityObserver {",
        "    void onSeatAvailabilityChanged(Show show, String event, List<String> seatIds, Map<SeatType, Integer> availability);",
        "}",
        "",
        "final class ConsoleSeatAvailabilityObserver implements SeatAvailabilityObserver {",
        "    @Override",
        "    public void onSeatAvailabilityChanged(Show show, String event, List<String> seatIds, Map<SeatType, Integer> availability) {",
        "        System.out.println(\"Show \" + show.getId() + \" seats \" + seatIds + \" \" + event + \". Availability \" + availability);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Booking.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Booking {",
        "    private final String id;",
        "    private final String customerId;",
        "    private final String showId;",
        "    private final List<String> seatIds;",
        "    private final long amountInPaise;",
        "    private final Instant createdAt;",
        "    private BookingState state;",
        "    private PaymentStatus paymentStatus;",
        "",
        "    public Booking(String id, String customerId, String showId, List<String> seatIds, long amountInPaise) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.customerId = Objects.requireNonNull(customerId, \"customerId\");",
        "        this.showId = Objects.requireNonNull(showId, \"showId\");",
        "        this.seatIds = Collections.unmodifiableList(new ArrayList<>(seatIds));",
        "        this.amountInPaise = amountInPaise;",
        "        this.createdAt = Instant.now();",
        "        this.state = new CreatedState();",
        "        this.paymentStatus = PaymentStatus.NOT_STARTED;",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getCustomerId() {",
        "        return customerId;",
        "    }",
        "",
        "    public String getShowId() {",
        "        return showId;",
        "    }",
        "",
        "    public List<String> getSeatIds() {",
        "        return seatIds;",
        "    }",
        "",
        "    public long getAmountInPaise() {",
        "        return amountInPaise;",
        "    }",
        "",
        "    public Instant getCreatedAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public synchronized BookingStatus getStatus() {",
        "        return state.status();",
        "    }",
        "",
        "    public synchronized PaymentStatus getPaymentStatus() {",
        "        return paymentStatus;",
        "    }",
        "",
        "    public synchronized void markSeatsHeld() {",
        "        state.hold(this);",
        "    }",
        "",
        "    public synchronized void markPaymentSuccessful() {",
        "        ensureStatus(BookingStatus.SEATS_HELD);",
        "        paymentStatus = PaymentStatus.SUCCESS;",
        "    }",
        "",
        "    public synchronized void markPaymentFailed() {",
        "        ensureStatus(BookingStatus.SEATS_HELD);",
        "        paymentStatus = PaymentStatus.FAILED;",
        "    }",
        "",
        "    public synchronized void confirm() {",
        "        if (paymentStatus != PaymentStatus.SUCCESS) {",
        "            throw new IllegalStateException(\"Payment must succeed before confirmation\");",
        "        }",
        "        state.confirm(this);",
        "    }",
        "",
        "    public synchronized void expire() {",
        "        state.expire(this);",
        "    }",
        "",
        "    public synchronized void cancel() {",
        "        state.cancel(this);",
        "    }",
        "",
        "    void transitionTo(BookingState nextState) {",
        "        this.state = nextState;",
        "    }",
        "",
        "    private void ensureStatus(BookingStatus expected) {",
        "        if (state.status() != expected) {",
        "            throw new IllegalStateException(\"Expected \" + expected + \" but was \" + state.status());",
        "        }",
        "    }",
        "}",
        "",
        "interface BookingState {",
        "    BookingStatus status();",
        "",
        "    void hold(Booking booking);",
        "",
        "    void confirm(Booking booking);",
        "",
        "    void expire(Booking booking);",
        "",
        "    void cancel(Booking booking);",
        "}",
        "",
        "abstract class AbstractBookingState implements BookingState {",
        "    @Override",
        "    public void hold(Booking booking) {",
        "        invalid(\"hold\");",
        "    }",
        "",
        "    @Override",
        "    public void confirm(Booking booking) {",
        "        invalid(\"confirm\");",
        "    }",
        "",
        "    @Override",
        "    public void expire(Booking booking) {",
        "        invalid(\"expire\");",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Booking booking) {",
        "        invalid(\"cancel\");",
        "    }",
        "",
        "    private void invalid(String action) {",
        "        throw new IllegalStateException(\"Cannot \" + action + \" booking in \" + status() + \" state\");",
        "    }",
        "}",
        "",
        "final class CreatedState extends AbstractBookingState {",
        "    @Override",
        "    public BookingStatus status() {",
        "        return BookingStatus.CREATED;",
        "    }",
        "",
        "    @Override",
        "    public void hold(Booking booking) {",
        "        booking.transitionTo(new SeatsHeldState());",
        "    }",
        "",
        "    @Override",
        "    public void expire(Booking booking) {",
        "        booking.transitionTo(new ExpiredState());",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Booking booking) {",
        "        booking.transitionTo(new CancelledState());",
        "    }",
        "}",
        "",
        "final class SeatsHeldState extends AbstractBookingState {",
        "    @Override",
        "    public BookingStatus status() {",
        "        return BookingStatus.SEATS_HELD;",
        "    }",
        "",
        "    @Override",
        "    public void confirm(Booking booking) {",
        "        booking.transitionTo(new ConfirmedState());",
        "    }",
        "",
        "    @Override",
        "    public void expire(Booking booking) {",
        "        booking.transitionTo(new ExpiredState());",
        "    }",
        "",
        "    @Override",
        "    public void cancel(Booking booking) {",
        "        booking.transitionTo(new CancelledState());",
        "    }",
        "}",
        "",
        "final class ConfirmedState extends AbstractBookingState {",
        "    @Override",
        "    public BookingStatus status() {",
        "        return BookingStatus.CONFIRMED;",
        "    }",
        "}",
        "",
        "final class ExpiredState extends AbstractBookingState {",
        "    @Override",
        "    public BookingStatus status() {",
        "        return BookingStatus.EXPIRED;",
        "    }",
        "}",
        "",
        "final class CancelledState extends AbstractBookingState {",
        "    @Override",
        "    public BookingStatus status() {",
        "        return BookingStatus.CANCELLED;",
        "    }",
        "}",
        "",
        "enum BookingStatus {",
        "    CREATED, SEATS_HELD, CONFIRMED, EXPIRED, CANCELLED",
        "}",
        "",
        "enum PaymentStatus {",
        "    NOT_STARTED, SUCCESS, FAILED",
        "}",
      ].join("\n"),
    },
    {
      filename: "SeatLockProvider.java",
      language: "java",
      content: [
        "import java.time.Clock;",
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.HashMap;",
        "import java.util.Iterator;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class SeatLockProvider {",
        "    private final Duration holdDuration;",
        "    private final Clock clock;",
        "    private final Map<String, SeatHold> holds = new HashMap<>();",
        "",
        "    public SeatLockProvider(Duration holdDuration) {",
        "        this(holdDuration, Clock.systemUTC());",
        "    }",
        "",
        "    public SeatLockProvider(Duration holdDuration, Clock clock) {",
        "        this.holdDuration = Objects.requireNonNull(holdDuration, \"holdDuration\");",
        "        this.clock = Objects.requireNonNull(clock, \"clock\");",
        "    }",
        "",
        "    public synchronized boolean lockSeats(Show show, List<String> seatIds, String bookingId) {",
        "        cleanupExpired(show);",
        "        Instant expiresAt = clock.instant().plus(holdDuration);",
        "",
        "        for (String seatId : seatIds) {",
        "            String key = key(show.getId(), seatId);",
        "            if (holds.containsKey(key)) {",
        "                return false;",
        "            }",
        "            if (show.getSeat(seatId).getStatus() != SeatStatus.AVAILABLE) {",
        "                return false;",
        "            }",
        "        }",
        "",
        "        for (String seatId : seatIds) {",
        "            holds.put(key(show.getId(), seatId), new SeatHold(show.getId(), seatId, bookingId, expiresAt));",
        "        }",
        "        show.holdSeats(seatIds, bookingId);",
        "        return true;",
        "    }",
        "",
        "    public synchronized boolean validateLocks(Show show, List<String> seatIds, String bookingId) {",
        "        cleanupExpired(show);",
        "        Instant now = clock.instant();",
        "        for (String seatId : seatIds) {",
        "            SeatHold hold = holds.get(key(show.getId(), seatId));",
        "            if (hold == null || !hold.belongsTo(bookingId) || hold.isExpired(now)) {",
        "                return false;",
        "            }",
        "        }",
        "        return true;",
        "    }",
        "",
        "    public synchronized void consumeLocks(Show show, List<String> seatIds, String bookingId) {",
        "        if (!validateLocks(show, seatIds, bookingId)) {",
        "            throw new IllegalStateException(\"Seat hold is no longer valid\");",
        "        }",
        "        for (String seatId : seatIds) {",
        "            holds.remove(key(show.getId(), seatId));",
        "        }",
        "    }",
        "",
        "    public synchronized void releaseLocks(Show show, List<String> seatIds, String bookingId) {",
        "        for (String seatId : seatIds) {",
        "            SeatHold hold = holds.get(key(show.getId(), seatId));",
        "            if (hold != null && hold.belongsTo(bookingId)) {",
        "                holds.remove(key(show.getId(), seatId));",
        "            }",
        "        }",
        "        show.releaseHold(seatIds, bookingId);",
        "    }",
        "",
        "    private void cleanupExpired(Show show) {",
        "        Instant now = clock.instant();",
        "        List<String> expiredSeatIds = new ArrayList<>();",
        "        Iterator<Map.Entry<String, SeatHold>> iterator = holds.entrySet().iterator();",
        "        while (iterator.hasNext()) {",
        "            SeatHold hold = iterator.next().getValue();",
        "            if (hold.showId.equals(show.getId()) && hold.isExpired(now)) {",
        "                expiredSeatIds.add(hold.seatId);",
        "                iterator.remove();",
        "            }",
        "        }",
        "        if (!expiredSeatIds.isEmpty()) {",
        "            show.releaseExpiredHold(expiredSeatIds);",
        "        }",
        "    }",
        "",
        "    private String key(String showId, String seatId) {",
        "        return showId + \":\" + seatId;",
        "    }",
        "",
        "    private static final class SeatHold {",
        "        private final String showId;",
        "        private final String seatId;",
        "        private final String bookingId;",
        "        private final Instant expiresAt;",
        "",
        "        private SeatHold(String showId, String seatId, String bookingId, Instant expiresAt) {",
        "            this.showId = showId;",
        "            this.seatId = seatId;",
        "            this.bookingId = bookingId;",
        "            this.expiresAt = expiresAt;",
        "        }",
        "",
        "        private boolean belongsTo(String bookingId) {",
        "            return this.bookingId.equals(bookingId);",
        "        }",
        "",
        "        private boolean isExpired(Instant now) {",
        "            return !expiresAt.isAfter(now);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PricingStrategy.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Comparator;",
        "import java.util.EnumMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "",
        "public interface PricingStrategy {",
        "    long calculatePrice(Show show, List<Seat> seats);",
        "}",
        "",
        "final class SeatTypePricingStrategy implements PricingStrategy {",
        "    private final Map<SeatType, Long> priceByType = new EnumMap<>(SeatType.class);",
        "",
        "    SeatTypePricingStrategy(Map<SeatType, Long> priceByType) {",
        "        this.priceByType.putAll(priceByType);",
        "    }",
        "",
        "    static SeatTypePricingStrategy standard() {",
        "        Map<SeatType, Long> prices = new EnumMap<>(SeatType.class);",
        "        prices.put(SeatType.SILVER, 15000L);",
        "        prices.put(SeatType.GOLD, 25000L);",
        "        prices.put(SeatType.PLATINUM, 40000L);",
        "        return new SeatTypePricingStrategy(prices);",
        "    }",
        "",
        "    @Override",
        "    public long calculatePrice(Show show, List<Seat> seats) {",
        "        long total = 0;",
        "        for (Seat seat : seats) {",
        "            Long price = priceByType.get(seat.getType());",
        "            if (price == null) {",
        "                throw new IllegalStateException(\"No price configured for \" + seat.getType());",
        "            }",
        "            total += price;",
        "        }",
        "        return total;",
        "    }",
        "}",
        "",
        "interface SeatAllocationStrategy {",
        "    List<String> allocateSeats(Show show, SeatType preferredType, int count);",
        "}",
        "",
        "final class ContiguousSeatAllocationStrategy implements SeatAllocationStrategy {",
        "    @Override",
        "    public List<String> allocateSeats(Show show, SeatType preferredType, int count) {",
        "        if (count <= 0) {",
        "            throw new IllegalArgumentException(\"Seat count must be positive\");",
        "        }",
        "        List<Seat> candidates = new ArrayList<>(show.availableSeats(preferredType));",
        "        candidates.sort(Comparator.comparing(Seat::getId));",
        "        if (candidates.size() < count) {",
        "            throw new IllegalStateException(\"Not enough seats available\");",
        "        }",
        "        List<String> allocated = new ArrayList<>();",
        "        for (int i = 0; i < count; i++) {",
        "            allocated.add(candidates.get(i).getId());",
        "        }",
        "        return allocated;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "BookingService.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "import java.util.concurrent.ConcurrentHashMap;",
        "",
        "public final class BookingService {",
        "    private static final BookingService INSTANCE = new BookingService(",
        "        new SeatLockProvider(Duration.ofMinutes(5)),",
        "        SeatTypePricingStrategy.standard(),",
        "        new ContiguousSeatAllocationStrategy(),",
        "        new AlwaysSuccessfulPaymentGateway()",
        "    );",
        "",
        "    private final Map<String, Show> shows = new ConcurrentHashMap<>();",
        "    private final Map<String, Booking> bookings = new ConcurrentHashMap<>();",
        "    private final SeatLockProvider lockProvider;",
        "    private final PricingStrategy pricingStrategy;",
        "    private final SeatAllocationStrategy allocationStrategy;",
        "    private final PaymentGateway paymentGateway;",
        "",
        "    private BookingService(",
        "        SeatLockProvider lockProvider,",
        "        PricingStrategy pricingStrategy,",
        "        SeatAllocationStrategy allocationStrategy,",
        "        PaymentGateway paymentGateway",
        "    ) {",
        "        this.lockProvider = Objects.requireNonNull(lockProvider, \"lockProvider\");",
        "        this.pricingStrategy = Objects.requireNonNull(pricingStrategy, \"pricingStrategy\");",
        "        this.allocationStrategy = Objects.requireNonNull(allocationStrategy, \"allocationStrategy\");",
        "        this.paymentGateway = Objects.requireNonNull(paymentGateway, \"paymentGateway\");",
        "    }",
        "",
        "    public static BookingService getInstance() {",
        "        return INSTANCE;",
        "    }",
        "",
        "    public void registerShow(Show show) {",
        "        shows.put(show.getId(), show);",
        "    }",
        "",
        "    public Booking createAndHoldBooking(String customerId, String showId, SeatType preferredType, int seatCount) {",
        "        Show show = getShow(showId);",
        "        List<String> seatIds = allocationStrategy.allocateSeats(show, preferredType, seatCount);",
        "        return holdSpecificSeats(customerId, showId, seatIds);",
        "    }",
        "",
        "    public Booking holdSpecificSeats(String customerId, String showId, List<String> seatIds) {",
        "        Show show = getShow(showId);",
        "        String bookingId = \"BKG-\" + UUID.randomUUID();",
        "        long amount = pricingStrategy.calculatePrice(show, show.getSeats(seatIds));",
        "        Booking booking = new Booking(bookingId, customerId, showId, seatIds, amount);",
        "",
        "        boolean locked = lockProvider.lockSeats(show, seatIds, bookingId);",
        "        if (!locked) {",
        "            throw new IllegalStateException(\"Requested seats are no longer available\");",
        "        }",
        "",
        "        booking.markSeatsHeld();",
        "        bookings.put(bookingId, booking);",
        "        return booking;",
        "    }",
        "",
        "    public Booking confirmBooking(String bookingId) {",
        "        Booking booking = getBooking(bookingId);",
        "        Show show = getShow(booking.getShowId());",
        "",
        "        if (!lockProvider.validateLocks(show, booking.getSeatIds(), booking.getId())) {",
        "            expireBooking(bookingId);",
        "            throw new IllegalStateException(\"Seat hold expired before payment\");",
        "        }",
        "",
        "        PaymentReceipt receipt = paymentGateway.charge(booking.getCustomerId(), booking.getAmountInPaise());",
        "        if (!receipt.success()) {",
        "            booking.markPaymentFailed();",
        "            lockProvider.releaseLocks(show, booking.getSeatIds(), booking.getId());",
        "            booking.cancel();",
        "            return booking;",
        "        }",
        "",
        "        if (!lockProvider.validateLocks(show, booking.getSeatIds(), booking.getId())) {",
        "            expireBooking(bookingId);",
        "            throw new IllegalStateException(\"Seat hold expired during payment\");",
        "        }",
        "",
        "        booking.markPaymentSuccessful();",
        "        lockProvider.consumeLocks(show, booking.getSeatIds(), booking.getId());",
        "        show.confirmSeats(booking.getSeatIds(), booking.getId());",
        "        booking.confirm();",
        "        return booking;",
        "    }",
        "",
        "    public Booking cancelBooking(String bookingId) {",
        "        Booking booking = getBooking(bookingId);",
        "        if (booking.getStatus() == BookingStatus.SEATS_HELD) {",
        "            Show show = getShow(booking.getShowId());",
        "            lockProvider.releaseLocks(show, booking.getSeatIds(), booking.getId());",
        "        }",
        "        booking.cancel();",
        "        return booking;",
        "    }",
        "",
        "    public Booking expireBooking(String bookingId) {",
        "        Booking booking = getBooking(bookingId);",
        "        if (booking.getStatus() == BookingStatus.SEATS_HELD) {",
        "            Show show = getShow(booking.getShowId());",
        "            lockProvider.releaseLocks(show, booking.getSeatIds(), booking.getId());",
        "        }",
        "        booking.expire();",
        "        return booking;",
        "    }",
        "",
        "    private Show getShow(String showId) {",
        "        Show show = shows.get(showId);",
        "        if (show == null) {",
        "            throw new IllegalArgumentException(\"Unknown show \" + showId);",
        "        }",
        "        return show;",
        "    }",
        "",
        "    private Booking getBooking(String bookingId) {",
        "        Booking booking = bookings.get(bookingId);",
        "        if (booking == null) {",
        "            throw new IllegalArgumentException(\"Unknown booking \" + bookingId);",
        "        }",
        "        return booking;",
        "    }",
        "}",
        "",
        "interface PaymentGateway {",
        "    PaymentReceipt charge(String customerId, long amountInPaise);",
        "}",
        "",
        "final class PaymentReceipt {",
        "    private final boolean success;",
        "    private final String transactionId;",
        "",
        "    PaymentReceipt(boolean success, String transactionId) {",
        "        this.success = success;",
        "        this.transactionId = transactionId;",
        "    }",
        "",
        "    boolean success() {",
        "        return success;",
        "    }",
        "",
        "    String transactionId() {",
        "        return transactionId;",
        "    }",
        "}",
        "",
        "final class AlwaysSuccessfulPaymentGateway implements PaymentGateway {",
        "    @Override",
        "    public PaymentReceipt charge(String customerId, long amountInPaise) {",
        "        return new PaymentReceipt(true, \"PAY-\" + UUID.randomUUID());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.Arrays;",
        "import java.util.List;",
        "import java.util.concurrent.ExecutorService;",
        "import java.util.concurrent.Executors;",
        "import java.util.concurrent.TimeUnit;",
        "",
        "public class Main {",
        "    public static void main(String[] args) throws InterruptedException {",
        "        Show show = new Show(",
        "            \"SHOW-1\",",
        "            \"Inception\",",
        "            \"PVR Orion\",",
        "            \"Audi 1\",",
        "            Instant.now().plusSeconds(3600),",
        "            Arrays.asList(",
        "                new Seat(\"A1\", SeatType.GOLD),",
        "                new Seat(\"A2\", SeatType.GOLD),",
        "                new Seat(\"B1\", SeatType.SILVER)",
        "            )",
        "        );",
        "        show.addObserver(new ConsoleSeatAvailabilityObserver());",
        "",
        "        BookingService service = BookingService.getInstance();",
        "        service.registerShow(show);",
        "",
        "        ExecutorService executor = Executors.newFixedThreadPool(2);",
        "        executor.submit(() -> tryHoldAndConfirm(service, \"user-a\", \"SHOW-1\", Arrays.asList(\"A1\")));",
        "        executor.submit(() -> tryHoldAndConfirm(service, \"user-b\", \"SHOW-1\", Arrays.asList(\"A1\")));",
        "        executor.shutdown();",
        "        executor.awaitTermination(5, TimeUnit.SECONDS);",
        "",
        "        System.out.println(\"Final availability \" + show.availabilitySnapshot());",
        "    }",
        "",
        "    private static void tryHoldAndConfirm(BookingService service, String customerId, String showId, List<String> seatIds) {",
        "        try {",
        "            Booking booking = service.holdSpecificSeats(customerId, showId, seatIds);",
        "            System.out.println(customerId + \" held \" + booking.getSeatIds() + \" as \" + booking.getStatus());",
        "            service.confirmBooking(booking.getId());",
        "            System.out.println(customerId + \" confirmed \" + booking.getId());",
        "        } catch (RuntimeException ex) {",
        "            System.out.println(customerId + \" failed: \" + ex.getMessage());",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Seat",
      detailMD:
        "Encapsulates one show-seat and its status. All status-changing methods are synchronized so HELD and BOOKED transitions cannot be corrupted by concurrent callers.",
    },
    {
      className: "Show",
      detailMD:
        "Owns show-specific seat objects, exposes availability snapshots, performs seat status changes, and notifies **SeatAvailabilityObserver** subscribers after each change.",
    },
    {
      className: "Booking",
      detailMD:
        "Carries customer, show, seat ids, amount, payment status, and the active **BookingState**. The state classes enforce Created to SeatsHeld to Confirmed, Expired, or Cancelled.",
    },
    {
      className: "SeatLockProvider",
      detailMD:
        "Thread-safe hold registry. Its synchronized methods clean expired holds, atomically check every requested seat, write holds with expiry, validate holds, and release or consume them.",
    },
    {
      className: "PricingStrategy",
      detailMD:
        "Contains the pricing and allocation seams: **PricingStrategy** with **SeatTypePricingStrategy**, plus **SeatAllocationStrategy** with **ContiguousSeatAllocationStrategy**.",
    },
    {
      className: "BookingService",
      detailMD:
        "Singleton controller facade. It registers shows, creates bookings, asks allocation and pricing strategies, delegates concurrency to **SeatLockProvider**, and coordinates payment confirmation.",
    },
    {
      className: "Main",
      detailMD:
        "Executable demo. Two threads attempt to hold the same seat A1; the synchronized lock provider lets one booking proceed and makes the other fail cleanly.",
    },
  ],

  dryRun: {
    inputMD:
      "Show **SHOW-1** has seats **A1:GOLD**, **A2:GOLD**, and **B1:SILVER**. User A and User B both try to hold **A1** at the same time, then the winner pays.",
    columns: ["Step", "User A", "User B", "Seat A1", "Booking states", "Outcome"],
    rows: [
      ["1", "Reads A1 as available", "Reads A1 as available", "AVAILABLE", "none", "Both clients can see the same snapshot"],
      ["2", "lockSeats enters first", "waits for lock provider", "HELD by A", "A: SeatsHeld", "Atomic check-then-hold succeeds for A"],
      ["3", "continues checkout", "lockSeats enters second", "HELD by A", "A: SeatsHeld", "B is rejected because A1 is no longer AVAILABLE"],
      ["4", "payment succeeds", "receives failure", "HELD by A", "A: SeatsHeld", "B has no booking to confirm"],
      ["5", "consume lock and confirm", "no-op", "BOOKED by A", "A: Confirmed", "A1 is sold exactly once"],
    ],
    narrativeMD:
      "The important row is Step 2: both users may observe the same available seat, but only one thread can execute the synchronized hold mutation at a time.",
  },

  complexity: [
    {
      operation: "holdSpecificSeats",
      time: "O(K)",
      space: "O(K)",
      note: "K selected seats are validated, priced, locked, and stored in the booking.",
    },
    {
      operation: "createAndHoldBooking",
      time: "O(S log S + K)",
      space: "O(S)",
      note: "The demo allocation strategy sorts available seats of the requested type before choosing K seats.",
    },
    {
      operation: "confirmBooking",
      time: "O(K)",
      space: "O(1)",
      note: "Validates K locks, consumes them, marks K seats booked, and transitions the booking.",
    },
    {
      operation: "availabilitySnapshot",
      time: "O(S)",
      space: "O(T)",
      note: "Scans S seats and counts them by T seat types.",
    },
    {
      operation: "cleanupExpired",
      time: "O(H)",
      space: "O(E)",
      note: "Scans H active holds for a show and releases E expired seats.",
    },
  ],
  complexityNotesMD:
    "For an interview, O(S) seat scans are acceptable for one screen. At scale, maintain per-show free-seat indexes and move hold cleanup to a scheduler or database TTL mechanism.",

  extensibility: [
    {
      label: "New pricing model",
      detailMD:
        "Add a **PricingStrategy** for weekend surge, early-bird discounts, coupon stacking, membership benefits, or movie-specific pricing.",
    },
    {
      label: "Better seat allocation",
      detailMD:
        "Replace **ContiguousSeatAllocationStrategy** with center-first, group-adjacent, aisle-preference, or accessibility-aware allocation.",
    },
    {
      label: "Payment providers",
      detailMD:
        "Swap **PaymentGateway** implementations for Razorpay, Stripe, wallet balance, or UPI. The booking lifecycle stays unchanged.",
    },
    {
      label: "Real-time UI updates",
      detailMD:
        "Attach observers that publish WebSocket events whenever **Show** emits held, released, expired, or booked events.",
    },
    {
      label: "Persistence",
      detailMD:
        "Move shows, bookings, and holds behind repositories. The same lock boundary can become a database transaction with row-level locks on show-seat rows.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Database row lock per show seat",
      detailMD:
        "Represent each show seat as a row and use a transaction with SELECT FOR UPDATE or an atomic compare-and-set update for HELD and BOOKED transitions.",
      tradeoffsMD:
        "This works across multiple app instances and survives restarts, but it introduces database contention and transaction timeout handling.",
    },
    {
      name: "Distributed lock per show-seat key",
      detailMD:
        "Use Redis or ZooKeeper style locks keyed by show id and seat id, with TTL equal to the hold timeout.",
      tradeoffsMD:
        "Good for horizontally scaled services, but lock loss, clock drift, and payment timing need careful compensating logic.",
    },
    {
      name: "Optimistic booking with version numbers",
      detailMD:
        "Let users attempt to book based on a seat version and update only if the version is unchanged.",
      tradeoffsMD:
        "Reduces lock duration and improves read throughput, but users see more payment-time failures if seats are popular.",
    },
  ],

  commonMistakes: [
    "Treating screen seats as globally booked instead of modelling show-specific availability.",
    "Checking availability in one method and writing the hold in another without a shared lock or transaction.",
    "Confirming payment before verifying that the seat hold still belongs to the same booking.",
    "Using a boolean **isBooked** flag and forgetting the important HELD state.",
    "Allowing cancellation or expiry after **Confirmed** without defining a refund state.",
    "Hard-coding prices in the controller instead of using a **PricingStrategy**.",
    "Not releasing holds when payment fails, leaving seats blocked until manual cleanup.",
  ],

  followUps: [
    {
      question: "How do you handle two users selecting the same seat at the same time?",
      answerMD:
        "Both can read the same snapshot, but only one can enter **SeatLockProvider.lockSeats** at a time. The winner writes a hold; the loser sees HELD or an existing hold and fails.",
    },
    {
      question: "What if the payment succeeds but the hold has expired?",
      answerMD:
        "The service validates the hold before confirmation. In production, the payment flow should authorize first, capture only after seat confirmation, or issue an automatic refund on late expiry.",
    },
    {
      question: "Why not directly mark seats booked when the user clicks them?",
      answerMD:
        "Checkout can be abandoned or payment can fail. A temporary HELD state blocks the seat for a short time without falsely selling it.",
    },
    {
      question: "How would this work with multiple application instances?",
      answerMD:
        "Replace the in-memory synchronized lock provider with database row locks, an atomic update on show-seat rows, or a distributed lock with TTL.",
    },
    {
      question: "Where do notifications and seat-map refreshes belong?",
      answerMD:
        "They are observers of **Show** seat changes. The domain emits availability events; WebSocket, email, and analytics adapters subscribe without polluting booking logic.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable holds",
      detailMD:
        "Store holds with expiry timestamps so a restart does not forget blocked seats. A scheduled job or database TTL can release expired holds.",
    },
    {
      label: "Payment authorization",
      detailMD:
        "Prefer authorize then capture. Capture after the seat becomes BOOKED; if confirmation fails, void the authorization instead of refunding captured money.",
    },
    {
      label: "Idempotency",
      detailMD:
        "Make confirm and payment callbacks idempotent by using booking id and payment transaction id. Duplicate callbacks must not double-confirm or double-charge.",
    },
    {
      label: "Observability",
      detailMD:
        "Track hold success rate, hold expiry rate, payment failure rate, lock contention, and seat-map latency for each show.",
    },
    {
      label: "Fairness and abuse prevention",
      detailMD:
        "Limit seats per customer, throttle repeated holds, and shorten hold duration for high-demand shows to prevent seat hoarding.",
    },
  ],

  interviewNotes: [
    "Did the candidate identify show-specific seats, not just screen seats?",
    "Did they explicitly guard the check-then-hold race for the same seat?",
    "Is the booking state machine legal and testable?",
    "Are pricing and allocation policies behind Strategy interfaces?",
    "Can observers refresh availability without coupling UI code to booking logic?",
    "Can the in-memory lock be swapped for a database or distributed lock in production?",
  ],

  quiz: [
    {
      question: "Why is the HELD state necessary before CONFIRMED?",
      options: [
        "It blocks seats temporarily while payment is pending",
        "It makes seat search faster",
        "It removes the need for payment validation",
        "It allows one seat to be sold to many users",
      ],
      answerIndex: 0,
      explanationMD:
        "HELD represents a short-lived reservation. It prevents another user from taking the seat while checkout is in progress, without permanently selling it.",
    },
    {
      question: "What is the critical concurrency section in this design?",
      options: [
        "Printing the final ticket",
        "Calculating the price for a seat type",
        "Checking that seats are available and writing the hold",
        "Sorting available seats by id",
      ],
      answerIndex: 2,
      explanationMD:
        "The race is between reading AVAILABLE and changing it to HELD. That check-then-write must be synchronized or transactional.",
    },
    {
      question: "Which pattern best describes **BookingState**?",
      options: [
        "Strategy",
        "State",
        "Observer",
        "Singleton",
      ],
      answerIndex: 1,
      explanationMD:
        "Each state object controls which transitions are legal for a booking, which is the State pattern.",
    },
    {
      question: "Why is **PricingStrategy** separated from **BookingService**?",
      options: [
        "So pricing can change without editing the booking orchestration",
        "So bookings no longer need seats",
        "So payment can be skipped",
        "So Java can compile enums faster",
      ],
      answerIndex: 0,
      explanationMD:
        "The service should orchestrate holding, payment, and confirmation. Price rules vary independently and belong behind a strategy.",
    },
    {
      question: "What should happen if a payment fails after seats are held?",
      options: [
        "Keep seats held forever",
        "Mark the booking Confirmed anyway",
        "Release the holds and cancel the booking",
        "Delete the show",
      ],
      answerIndex: 2,
      explanationMD:
        "A failed payment cannot produce a confirmed ticket, so the booking is cancelled and the seats return to availability.",
    },
  ],

  practiceVariants: [
    {
      title: "Add row-aware contiguous allocation",
      detailMD:
        "Represent row and seat number separately, then allocate K adjacent seats in the same row before falling back to nearby seats.",
      difficulty: "Intermediate",
    },
    {
      title: "Support coupons and surge pricing",
      detailMD:
        "Compose pricing strategies for base seat type price, weekend multiplier, coupon discount, and convenience fee.",
      difficulty: "Intermediate",
    },
    {
      title: "Replace in-memory locks with database locks",
      detailMD:
        "Model show-seat rows with status and version, then implement hold using an atomic update or row-level transaction.",
      difficulty: "Advanced",
    },
    {
      title: "Add waitlist notifications",
      detailMD:
        "When a hold expires or a booking is cancelled, notify waitlisted customers through an observer-driven notification adapter.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What owns seat availability?",
      back: "The **Show** owns show-specific **Seat** objects. A physical screen seat can have different availability for different shows.",
    },
    {
      front: "What prevents double booking when two users pick A1?",
      back: "A synchronized **SeatLockProvider** atomically checks and writes the hold, so only one booking can hold A1.",
    },
    {
      front: "What is the booking state flow?",
      back: "**Created** to **SeatsHeld** to **Confirmed**, or from **Created** or **SeatsHeld** to **Expired** or **Cancelled**.",
    },
    {
      front: "Which patterns are central to this design?",
      back: "State for booking lifecycle, Strategy for pricing and allocation, Observer for availability updates, and Singleton for the demo controller.",
    },
    {
      front: "When should seats become BOOKED?",
      back: "Only after payment succeeds and the hold is still valid for the same booking.",
    },
    {
      front: "How do you scale beyond one JVM?",
      back: "Replace in-memory synchronized locks with database row locks, atomic updates, or distributed locks with TTL.",
    },
  ],

  cheatSheetMD: [
    "**Core model:** Cinema → Screen → Show → Seat. Availability is show-specific, not global to the physical screen.",
    "",
    "**Booking lifecycle:** Created → SeatsHeld → Confirmed, Expired, or Cancelled. Confirmed is terminal in the base design.",
    "",
    "**Concurrency invariant:** one show-seat can have at most one active hold or confirmed booking. Guard check-then-hold with a synchronized lock provider or transaction.",
    "",
    "**Patterns:** State for booking transitions, Strategy for pricing and allocation, Observer for seat availability, Singleton for the in-memory controller.",
    "",
    "**Payment rule:** authorize or charge only while the hold is valid; mark seats BOOKED before returning a confirmed ticket.",
    "",
    "**Scale path:** persist show seats and holds, add idempotent payment callbacks, and use row locks or atomic status updates for multi-instance safety.",
  ].join("\n"),

  references: [
    {
      title: "Java Concurrency in Practice",
      kind: "Book",
      author: "Brian Goetz et al.",
    },
    {
      title: "Refactoring Guru — State Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/state",
    },
    {
      title: "Refactoring Guru — Strategy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/strategy",
    },
    {
      title: "Martin Fowler — Unit of Work",
      kind: "Blog",
      url: "https://martinfowler.com/eaaCatalog/unitOfWork.html",
      author: "Martin Fowler",
    },
  ],

  relatedProblems: [
    { slug: "hotel-management", note: "Reservation lifecycle and availability with holds across rooms." },
    { slug: "airline-reservation", note: "Seat inventory, temporary holds, and payment confirmation in a higher-stakes domain." },
    { slug: "parking-lot", note: "Another allocation and occupancy model with concurrency around scarce slots." },
  ],
};
