import type { LLDProblemContent } from "../types";

export const paymentGateway: LLDProblemContent = {
  slug: "payment-gateway",

  statementMD: [
    "Design the low-level object model for a **payment gateway** that accepts card, wallet, and UPI payments for merchants.",
    "The gateway must normalize different payment methods, route each payment to one of several downstream processors, execute authorize and capture, keep transaction state correct, make retries safe, and support refunds after a successful capture.",
    "",
    "The interview focus is the boundary between gateway orchestration and provider integrations: use **Strategy** for choosing the right processor route, **Adapter** for translating each provider API into a common interface, and an explicit **State** model for the payment lifecycle.",
  ].join("\n"),

  businessContextMD: [
    "Payment gateways sit between merchants and processors such as Stripe, PayPal, banks, wallet providers, and UPI rails.",
    "A strong LLD answer shows that money movement is not just another API call: it needs idempotency, safe retries, audit-friendly state transitions, clear provider seams, and refund behavior that cannot corrupt already captured money.",
    "Interviewers use this problem to evaluate whether a candidate can separate policy from integration details while defending critical invariants.",
  ].join("\n"),

  functionalRequirements: [
    "Accept card, wallet, and UPI payment methods with a normalized domain model.",
    "Create a payment transaction with merchant id, amount, currency, method, and idempotency key.",
    "Route payments to downstream processors based on payment method or routing policy.",
    "Integrate multiple processors behind a common **PaymentProcessor** port using adapters.",
    "Move each transaction through **Initiated → Authorized → Captured**, or into **Failed** when authorization or capture cannot complete.",
    "Return the same transaction for repeated requests with the same idempotency key.",
    "Retry retryable processor failures without creating duplicate provider charges.",
    "Refund a captured payment and move it to **Refunded** while rejecting refunds from invalid states.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Correct financial state",
      detailMD:
        "State transitions must be explicit and enforced. A payment cannot jump directly from **Initiated** to **Captured**, and a failed payment cannot later be refunded.",
    },
    {
      label: "Idempotency",
      detailMD:
        "A merchant retry with the same idempotency key must return the original transaction rather than creating another provider authorization.",
    },
    {
      label: "Provider isolation",
      detailMD:
        "Stripe, PayPal, bank, and UPI quirks must stay inside adapters. The gateway service should speak one common interface.",
    },
    {
      label: "Reliability under transient failure",
      detailMD:
        "Retry only responses that are marked retryable and preserve the same transaction identity across attempts.",
    },
    {
      label: "Auditability",
      detailMD:
        "Every status, provider reference, retry count, and refund decision should be explainable from the domain object and persisted in a real system.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Adding a new processor, method, or routing rule should be additive: new adapter or strategy class, not edits across the lifecycle code.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need to model settlement, reconciliation, and webhooks?",
      answerMD:
        "Not in the base implementation. We model synchronous authorize, capture, refund, and note that webhooks and reconciliation are production extensions.",
    },
    {
      question: "Should authorize and capture be separate operations?",
      answerMD:
        "Yes. The lifecycle explicitly separates **Authorized** from **Captured** because many gateways reserve funds before capturing them.",
    },
    {
      question: "Can the same request be retried by the merchant?",
      answerMD:
        "Yes. The merchant supplies an idempotency key. Replays return the existing payment object and do not call the processor again.",
    },
    {
      question: "How are processor failures classified?",
      answerMD:
        "The adapter returns a normalized response that marks failures as retryable or permanent. The service retries only retryable failures.",
    },
    {
      question: "Can a captured payment be refunded more than once?",
      answerMD:
        "For the base design, one full refund is supported. Partial and multi-refund workflows are covered as an extension.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class PaymentGatewayService {",
    "        -ProcessorSelectionStrategy selectionStrategy",
    "        -Map~String,Payment~ paymentsByKey",
    "        -Map~String,Payment~ paymentsById",
    "        -int maxAttempts",
    "        +processPayment(String,long,String,PaymentMethod,String) Payment",
    "        +refund(String) Payment",
    "        +findPayment(String) Optional~Payment~",
    "    }",
    "    class Payment {",
    "        -String id",
    "        -String merchantId",
    "        -long amountCents",
    "        -String currency",
    "        -PaymentMethod method",
    "        -String idempotencyKey",
    "        -PaymentStatus status",
    "        -String providerReference",
    "        -int retryCount",
    "        +markAuthorized(String) void",
    "        +markCaptured() void",
    "        +markFailed(String) void",
    "        +markRefunded() void",
    "    }",
    "    class PaymentStatus {",
    "        <<enumeration>>",
    "        INITIATED",
    "        AUTHORIZED",
    "        CAPTURED",
    "        FAILED",
    "        REFUNDED",
    "        +canTransitionTo(PaymentStatus) boolean",
    "    }",
    "    class PaymentMethod {",
    "        <<interface>>",
    "        +type() PaymentMethodType",
    "        +instrumentReference() String",
    "    }",
    "    class PaymentMethodType {",
    "        <<enumeration>>",
    "        CARD",
    "        WALLET",
    "        UPI",
    "    }",
    "    class PaymentProcessor {",
    "        <<interface>>",
    "        +authorize(Payment) ProcessorResponse",
    "        +capture(Payment) ProcessorResponse",
    "        +refund(Payment) ProcessorResponse",
    "    }",
    "    class ProcessorSelectionStrategy {",
    "        <<interface>>",
    "        +select(PaymentMethod) PaymentProcessor",
    "    }",
    "    class MethodBasedProcessorSelectionStrategy",
    "    class StripeAdapter",
    "    class PayPalAdapter",
    "    class ProcessorResponse",
    "    PaymentGatewayService o-- Payment",
    "    PaymentGatewayService ..> ProcessorSelectionStrategy",
    "    PaymentGatewayService ..> PaymentProcessor",
    "    Payment --> PaymentStatus",
    "    Payment --> PaymentMethod",
    "    PaymentMethod --> PaymentMethodType",
    "    ProcessorSelectionStrategy <|.. MethodBasedProcessorSelectionStrategy",
    "    PaymentProcessor <|.. StripeAdapter",
    "    PaymentProcessor <|.. PayPalAdapter",
    "    PaymentProcessor --> ProcessorResponse",
  ].join("\n"),
  classDiagramCaptionMD:
    "The service owns orchestration and idempotency, **PaymentStatus** owns lifecycle legality, the selection strategy chooses a route, and adapters hide provider-specific APIs.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Merchant",
    "    participant Gateway as PaymentGatewayService",
    "    participant Store as IdempotencyStore",
    "    participant Strategy as ProcessorSelectionStrategy",
    "    participant Processor as PaymentProcessorAdapter",
    "    Merchant->>Gateway: processPayment(request, key)",
    "    Gateway->>Store: lookup(key)",
    "    alt existing payment",
    "        Store-->>Gateway: Payment",
    "        Gateway-->>Merchant: same Payment",
    "    else new payment",
    "        Gateway->>Gateway: create Payment INITIATED",
    "        Gateway->>Strategy: select(method)",
    "        Strategy-->>Gateway: adapter",
    "        Gateway->>Processor: authorize(payment)",
    "        Processor-->>Gateway: success providerRef",
    "        Gateway->>Gateway: markAuthorized",
    "        Gateway->>Processor: capture(payment)",
    "        Processor-->>Gateway: success",
    "        Gateway->>Gateway: markCaptured",
    "        Gateway-->>Merchant: captured Payment",
    "    end",
    "    Note over Merchant,Gateway: later, refund by idempotency key",
    "    Merchant->>Gateway: refund(key)",
    "    Gateway->>Processor: refund(captured payment)",
    "    Processor-->>Gateway: success",
    "    Gateway->>Gateway: markRefunded",
    "    Gateway-->>Merchant: refunded Payment",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The idempotency check happens before processor routing. Only a new key creates a transaction and calls the selected adapter.",

  entities: [
    {
      name: "PaymentGatewayService",
      responsibilityMD:
        "Application service and façade for merchants. It enforces idempotency, creates payments, picks the processor route, retries retryable failures, captures funds, and refunds captured transactions.",
      attributes: ["selectionStrategy", "paymentsByKey", "paymentsById", "maxAttempts"],
    },
    {
      name: "Payment",
      responsibilityMD:
        "Aggregate root for one money movement. It stores merchant, amount, method, idempotency key, provider reference, retry count, failure reason, and current lifecycle status.",
      attributes: ["id", "merchantId", "amountCents", "currency", "method", "idempotencyKey", "status"],
    },
    {
      name: "PaymentStatus",
      responsibilityMD:
        "State model for legal transitions. It prevents invalid jumps such as **Initiated** directly to **Captured** or **Failed** to **Refunded**.",
      attributes: ["INITIATED", "AUTHORIZED", "CAPTURED", "FAILED", "REFUNDED"],
    },
    {
      name: "PaymentMethod",
      responsibilityMD:
        "Normalized representation of card, wallet, and UPI instruments. It keeps the gateway independent of provider-specific request payloads.",
      attributes: ["type", "instrumentReference"],
    },
    {
      name: "PaymentProcessor",
      responsibilityMD:
        "Common processor port. The gateway calls **authorize**, **capture**, and **refund** without knowing which provider sits behind the call.",
      attributes: ["providerName", "authorize", "capture", "refund"],
    },
    {
      name: "StripeAdapter",
      responsibilityMD:
        "Adapter that maps the common processor port to a Stripe-like card processor, including normalized response objects.",
      attributes: ["providerName", "authorize", "capture", "refund"],
    },
    {
      name: "PayPalAdapter",
      responsibilityMD:
        "Adapter that maps the common processor port to a PayPal-like wallet and UPI capable processor.",
      attributes: ["providerName", "authorize", "capture", "refund"],
    },
    {
      name: "ProcessorSelectionStrategy",
      responsibilityMD:
        "Routing policy abstraction. The base implementation maps payment method type to a configured processor, but the service only depends on the strategy interface.",
      attributes: ["select"],
    },
  ],

  patternsUsed: [
    {
      name: "Adapter",
      whyMD:
        "**StripeAdapter** and **PayPalAdapter** translate provider-specific behavior into the shared **PaymentProcessor** interface. Provider quirks never leak into **PaymentGatewayService**.",
    },
    {
      name: "Strategy",
      whyMD:
        "**ProcessorSelectionStrategy** owns routing. Today it routes by payment method; later it can route by country, cost, success rate, merchant preference, or traffic split without changing payment execution.",
    },
    {
      name: "State",
      whyMD:
        "**PaymentStatus** encodes legal lifecycle moves. The domain object must ask the current state before changing, which protects captured, failed, and refunded invariants.",
    },
    {
      name: "Factory Method",
      whyMD:
        "Static creation methods such as **Payment.create**, **PaymentMethod.card**, **PaymentMethod.wallet**, and **PaymentMethod.upi** centralize valid object construction and keep callers from assembling partial transactions.",
    },
  ],

  designSteps: [
    {
      title: "Start with the transaction lifecycle",
      detailMD:
        "Model money movement as a state machine before discussing processors. The state model is the guardrail that keeps retries, refunds, and failed captures honest.",
      code: [
        "public enum PaymentStatus {",
        "    INITIATED, AUTHORIZED, CAPTURED, FAILED, REFUNDED;",
        "",
        "    public boolean canTransitionTo(PaymentStatus next) {",
        "        return (this == INITIATED && (next == AUTHORIZED || next == FAILED))",
        "            || (this == AUTHORIZED && (next == CAPTURED || next == FAILED))",
        "            || (this == CAPTURED && next == REFUNDED);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Normalize provider calls behind one processor port",
      detailMD:
        "The gateway should not contain provider request builders or response parsing. It should call a stable interface and receive a normalized response.",
      code: [
        "public interface PaymentProcessor {",
        "    ProcessorResponse authorize(Payment payment);",
        "    ProcessorResponse capture(Payment payment);",
        "    ProcessorResponse refund(Payment payment);",
        "}",
      ].join("\n"),
    },
    {
      title: "Split routing strategy from provider adapters",
      detailMD:
        "The strategy decides **which** processor to use. The adapter decides **how** to talk to that processor. Mixing those roles creates brittle switch statements.",
      code: [
        "public interface ProcessorSelectionStrategy {",
        "    PaymentProcessor select(PaymentMethod method);",
        "}",
      ].join("\n"),
    },
    {
      title: "Apply idempotency before side effects",
      detailMD:
        "Look up the idempotency key before creating or authorizing a payment. Store the new payment under the key before processor calls so a replay observes the same transaction identity.",
    },
    {
      title: "Retry only normalized retryable failures",
      detailMD:
        "Adapters classify responses as success, retryable failure, or permanent failure. The service retries retryable failures with the same **Payment** and stops immediately on permanent failures.",
    },
    {
      title: "Refund only from the captured state",
      detailMD:
        "Refund is not a generic reversal. The service rejects refunds unless the payment is **Captured**, calls the same selected processor adapter, and moves the state to **Refunded** only after processor success.",
    },
  ],

  implementation: [
    {
      filename: "PaymentMethod.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public interface PaymentMethod {",
        "    PaymentMethodType type();",
        "",
        "    String instrumentReference();",
        "",
        "    static PaymentMethod card(String token) {",
        "        return new SimplePaymentMethod(PaymentMethodType.CARD, token);",
        "    }",
        "",
        "    static PaymentMethod wallet(String walletId) {",
        "        return new SimplePaymentMethod(PaymentMethodType.WALLET, walletId);",
        "    }",
        "",
        "    static PaymentMethod upi(String vpa) {",
        "        return new SimplePaymentMethod(PaymentMethodType.UPI, vpa);",
        "    }",
        "}",
        "",
        "enum PaymentMethodType {",
        "    CARD,",
        "    WALLET,",
        "    UPI",
        "}",
        "",
        "final class SimplePaymentMethod implements PaymentMethod {",
        "    private final PaymentMethodType type;",
        "    private final String instrumentReference;",
        "",
        "    SimplePaymentMethod(PaymentMethodType type, String instrumentReference) {",
        "        this.type = Objects.requireNonNull(type, \"type\");",
        "        if (instrumentReference == null || instrumentReference.isBlank()) {",
        "            throw new IllegalArgumentException(\"instrumentReference is required\");",
        "        }",
        "        this.instrumentReference = instrumentReference;",
        "    }",
        "",
        "    @Override",
        "    public PaymentMethodType type() {",
        "        return type;",
        "    }",
        "",
        "    @Override",
        "    public String instrumentReference() {",
        "        return instrumentReference;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Payment.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "import java.util.UUID;",
        "",
        "public class Payment {",
        "    private final String id;",
        "    private final String merchantId;",
        "    private final long amountCents;",
        "    private final String currency;",
        "    private final PaymentMethod method;",
        "    private final String idempotencyKey;",
        "    private PaymentStatus status;",
        "    private String providerReference;",
        "    private int retryCount;",
        "    private String failureReason;",
        "",
        "    private Payment(String merchantId, long amountCents, String currency, PaymentMethod method, String idempotencyKey) {",
        "        if (amountCents <= 0) {",
        "            throw new IllegalArgumentException(\"amountCents must be positive\");",
        "        }",
        "        this.id = UUID.randomUUID().toString();",
        "        this.merchantId = requireText(merchantId, \"merchantId\");",
        "        this.amountCents = amountCents;",
        "        this.currency = requireText(currency, \"currency\");",
        "        this.method = Objects.requireNonNull(method, \"method\");",
        "        this.idempotencyKey = requireText(idempotencyKey, \"idempotencyKey\");",
        "        this.status = PaymentStatus.INITIATED;",
        "    }",
        "",
        "    public static Payment create(String merchantId, long amountCents, String currency, PaymentMethod method, String idempotencyKey) {",
        "        return new Payment(merchantId, amountCents, currency, method, idempotencyKey);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "",
        "    private void transitionTo(PaymentStatus next) {",
        "        status.requireTransitionTo(next);",
        "        status = next;",
        "    }",
        "",
        "    public void markAuthorized(String providerReference) {",
        "        this.providerReference = requireText(providerReference, \"providerReference\");",
        "        transitionTo(PaymentStatus.AUTHORIZED);",
        "    }",
        "",
        "    public void markCaptured() {",
        "        transitionTo(PaymentStatus.CAPTURED);",
        "    }",
        "",
        "    public void markFailed(String reason) {",
        "        this.failureReason = requireText(reason, \"failureReason\");",
        "        transitionTo(PaymentStatus.FAILED);",
        "    }",
        "",
        "    public void markRefunded() {",
        "        transitionTo(PaymentStatus.REFUNDED);",
        "    }",
        "",
        "    public void incrementRetryCount() {",
        "        retryCount++;",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getMerchantId() {",
        "        return merchantId;",
        "    }",
        "",
        "    public long getAmountCents() {",
        "        return amountCents;",
        "    }",
        "",
        "    public String getCurrency() {",
        "        return currency;",
        "    }",
        "",
        "    public PaymentMethod getMethod() {",
        "        return method;",
        "    }",
        "",
        "    public String getIdempotencyKey() {",
        "        return idempotencyKey;",
        "    }",
        "",
        "    public PaymentStatus getStatus() {",
        "        return status;",
        "    }",
        "",
        "    public String getProviderReference() {",
        "        return providerReference;",
        "    }",
        "",
        "    public int getRetryCount() {",
        "        return retryCount;",
        "    }",
        "",
        "    public String getFailureReason() {",
        "        return failureReason;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return \"Payment{\"",
        "            + \"id=\" + id",
        "            + \", status=\" + status",
        "            + \", amountCents=\" + amountCents",
        "            + \", currency=\" + currency",
        "            + \", method=\" + method.type()",
        "            + \", providerReference=\" + providerReference",
        "            + \", retryCount=\" + retryCount",
        "            + \"}\";",
        "    }",
        "}",
        "",
        "enum PaymentStatus {",
        "    INITIATED {",
        "        @Override",
        "        public boolean canTransitionTo(PaymentStatus next) {",
        "            return next == AUTHORIZED || next == FAILED;",
        "        }",
        "    },",
        "    AUTHORIZED {",
        "        @Override",
        "        public boolean canTransitionTo(PaymentStatus next) {",
        "            return next == CAPTURED || next == FAILED;",
        "        }",
        "    },",
        "    CAPTURED {",
        "        @Override",
        "        public boolean canTransitionTo(PaymentStatus next) {",
        "            return next == REFUNDED;",
        "        }",
        "    },",
        "    FAILED {",
        "        @Override",
        "        public boolean canTransitionTo(PaymentStatus next) {",
        "            return false;",
        "        }",
        "    },",
        "    REFUNDED {",
        "        @Override",
        "        public boolean canTransitionTo(PaymentStatus next) {",
        "            return false;",
        "        }",
        "    };",
        "",
        "    public abstract boolean canTransitionTo(PaymentStatus next);",
        "",
        "    public void requireTransitionTo(PaymentStatus next) {",
        "        if (!canTransitionTo(next)) {",
        "            throw new IllegalStateException(\"Cannot move payment from \" + this + \" to \" + next);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PaymentProcessor.java",
      language: "java",
      content: [
        "public interface PaymentProcessor {",
        "    String providerName();",
        "",
        "    ProcessorResponse authorize(Payment payment);",
        "",
        "    ProcessorResponse capture(Payment payment);",
        "",
        "    ProcessorResponse refund(Payment payment);",
        "}",
        "",
        "final class ProcessorResponse {",
        "    private final boolean success;",
        "    private final boolean retryable;",
        "    private final String providerReference;",
        "    private final String message;",
        "",
        "    private ProcessorResponse(boolean success, boolean retryable, String providerReference, String message) {",
        "        this.success = success;",
        "        this.retryable = retryable;",
        "        this.providerReference = providerReference;",
        "        this.message = message;",
        "    }",
        "",
        "    static ProcessorResponse success(String providerReference) {",
        "        return new ProcessorResponse(true, false, providerReference, \"OK\");",
        "    }",
        "",
        "    static ProcessorResponse retryableFailure(String message) {",
        "        return new ProcessorResponse(false, true, null, message);",
        "    }",
        "",
        "    static ProcessorResponse permanentFailure(String message) {",
        "        return new ProcessorResponse(false, false, null, message);",
        "    }",
        "",
        "    boolean isSuccess() {",
        "        return success;",
        "    }",
        "",
        "    boolean isRetryable() {",
        "        return retryable;",
        "    }",
        "",
        "    String getProviderReference() {",
        "        return providerReference;",
        "    }",
        "",
        "    String getMessage() {",
        "        return message;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "StripeAdapter.java",
      language: "java",
      content: [
        "public class StripeAdapter implements PaymentProcessor {",
        "    @Override",
        "    public String providerName() {",
        "        return \"Stripe\";",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse authorize(Payment payment) {",
        "        ProcessorResponse validation = validate(payment);",
        "        if (validation != null) {",
        "            return validation;",
        "        }",
        "        if (payment.getMethod().type() != PaymentMethodType.CARD) {",
        "            return ProcessorResponse.permanentFailure(\"Stripe route accepts card payments only\");",
        "        }",
        "        return ProcessorResponse.success(\"stripe_auth_\" + shortId(payment));",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse capture(Payment payment) {",
        "        if (payment.getStatus() != PaymentStatus.AUTHORIZED) {",
        "            return ProcessorResponse.permanentFailure(\"Stripe capture requires authorized status\");",
        "        }",
        "        return ProcessorResponse.success(payment.getProviderReference());",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse refund(Payment payment) {",
        "        if (payment.getStatus() != PaymentStatus.CAPTURED) {",
        "            return ProcessorResponse.permanentFailure(\"Stripe refund requires captured status\");",
        "        }",
        "        return ProcessorResponse.success(\"stripe_refund_\" + shortId(payment));",
        "    }",
        "",
        "    private ProcessorResponse validate(Payment payment) {",
        "        String instrument = payment.getMethod().instrumentReference();",
        "        if (instrument.startsWith(\"fail\")) {",
        "            return ProcessorResponse.permanentFailure(\"Stripe declined the instrument\");",
        "        }",
        "        if (instrument.startsWith(\"retry\")) {",
        "            return ProcessorResponse.retryableFailure(\"Stripe timed out\");",
        "        }",
        "        return null;",
        "    }",
        "",
        "    private String shortId(Payment payment) {",
        "        return payment.getId().substring(0, 8);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PayPalAdapter.java",
      language: "java",
      content: [
        "public class PayPalAdapter implements PaymentProcessor {",
        "    @Override",
        "    public String providerName() {",
        "        return \"PayPal\";",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse authorize(Payment payment) {",
        "        ProcessorResponse validation = validate(payment);",
        "        if (validation != null) {",
        "            return validation;",
        "        }",
        "        if (payment.getMethod().type() == PaymentMethodType.CARD) {",
        "            return ProcessorResponse.permanentFailure(\"PayPal route is configured for wallet and UPI only\");",
        "        }",
        "        return ProcessorResponse.success(\"paypal_auth_\" + shortId(payment));",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse capture(Payment payment) {",
        "        if (payment.getStatus() != PaymentStatus.AUTHORIZED) {",
        "            return ProcessorResponse.permanentFailure(\"PayPal capture requires authorized status\");",
        "        }",
        "        return ProcessorResponse.success(payment.getProviderReference());",
        "    }",
        "",
        "    @Override",
        "    public ProcessorResponse refund(Payment payment) {",
        "        if (payment.getStatus() != PaymentStatus.CAPTURED) {",
        "            return ProcessorResponse.permanentFailure(\"PayPal refund requires captured status\");",
        "        }",
        "        return ProcessorResponse.success(\"paypal_refund_\" + shortId(payment));",
        "    }",
        "",
        "    private ProcessorResponse validate(Payment payment) {",
        "        String instrument = payment.getMethod().instrumentReference();",
        "        if (instrument.startsWith(\"fail\")) {",
        "            return ProcessorResponse.permanentFailure(\"PayPal declined the instrument\");",
        "        }",
        "        if (instrument.startsWith(\"retry\")) {",
        "            return ProcessorResponse.retryableFailure(\"PayPal timed out\");",
        "        }",
        "        return null;",
        "    }",
        "",
        "    private String shortId(Payment payment) {",
        "        return payment.getId().substring(0, 8);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ProcessorSelectionStrategy.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.EnumMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public interface ProcessorSelectionStrategy {",
        "    PaymentProcessor select(PaymentMethod method);",
        "}",
        "",
        "final class MethodBasedProcessorSelectionStrategy implements ProcessorSelectionStrategy {",
        "    private final Map<PaymentMethodType, PaymentProcessor> routes;",
        "",
        "    MethodBasedProcessorSelectionStrategy(Map<PaymentMethodType, PaymentProcessor> routes) {",
        "        EnumMap<PaymentMethodType, PaymentProcessor> copy = new EnumMap<>(PaymentMethodType.class);",
        "        copy.putAll(Objects.requireNonNull(routes, \"routes\"));",
        "        this.routes = Collections.unmodifiableMap(copy);",
        "    }",
        "",
        "    @Override",
        "    public PaymentProcessor select(PaymentMethod method) {",
        "        PaymentProcessor processor = routes.get(method.type());",
        "        if (processor == null) {",
        "            throw new IllegalArgumentException(\"No processor configured for \" + method.type());",
        "        }",
        "        return processor;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PaymentGatewayService.java",
      language: "java",
      content: [
        "import java.util.EnumMap;",
        "import java.util.HashMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "import java.util.function.Supplier;",
        "",
        "public class PaymentGatewayService {",
        "    private final ProcessorSelectionStrategy selectionStrategy;",
        "    private final Map<String, Payment> paymentsByKey = new HashMap<>();",
        "    private final Map<String, Payment> paymentsById = new HashMap<>();",
        "    private final int maxAttempts;",
        "",
        "    public PaymentGatewayService(ProcessorSelectionStrategy selectionStrategy, int maxAttempts) {",
        "        this.selectionStrategy = Objects.requireNonNull(selectionStrategy, \"selectionStrategy\");",
        "        if (maxAttempts < 1) {",
        "            throw new IllegalArgumentException(\"maxAttempts must be at least 1\");",
        "        }",
        "        this.maxAttempts = maxAttempts;",
        "    }",
        "",
        "    public static PaymentGatewayService defaultGateway() {",
        "        PaymentProcessor stripe = new StripeAdapter();",
        "        PaymentProcessor payPal = new PayPalAdapter();",
        "        Map<PaymentMethodType, PaymentProcessor> routes = new EnumMap<>(PaymentMethodType.class);",
        "        routes.put(PaymentMethodType.CARD, stripe);",
        "        routes.put(PaymentMethodType.WALLET, payPal);",
        "        routes.put(PaymentMethodType.UPI, payPal);",
        "        return new PaymentGatewayService(new MethodBasedProcessorSelectionStrategy(routes), 3);",
        "    }",
        "",
        "    public synchronized Payment processPayment(",
        "        String merchantId,",
        "        long amountCents,",
        "        String currency,",
        "        PaymentMethod method,",
        "        String idempotencyKey",
        "    ) {",
        "        Payment existing = paymentsByKey.get(idempotencyKey);",
        "        if (existing != null) {",
        "            return existing;",
        "        }",
        "",
        "        Payment payment = Payment.create(merchantId, amountCents, currency, method, idempotencyKey);",
        "        paymentsByKey.put(idempotencyKey, payment);",
        "        paymentsById.put(payment.getId(), payment);",
        "",
        "        PaymentProcessor processor = selectionStrategy.select(method);",
        "        ProcessorResponse authorized = callWithRetry(() -> processor.authorize(payment), payment);",
        "        if (!authorized.isSuccess()) {",
        "            payment.markFailed(authorized.getMessage());",
        "            return payment;",
        "        }",
        "",
        "        payment.markAuthorized(authorized.getProviderReference());",
        "        ProcessorResponse captured = callWithRetry(() -> processor.capture(payment), payment);",
        "        if (!captured.isSuccess()) {",
        "            payment.markFailed(captured.getMessage());",
        "            return payment;",
        "        }",
        "",
        "        payment.markCaptured();",
        "        return payment;",
        "    }",
        "",
        "    public synchronized Payment refund(String idempotencyKey) {",
        "        Payment payment = paymentsByKey.get(idempotencyKey);",
        "        if (payment == null) {",
        "            throw new IllegalArgumentException(\"Unknown idempotency key: \" + idempotencyKey);",
        "        }",
        "        if (payment.getStatus() != PaymentStatus.CAPTURED) {",
        "            throw new IllegalStateException(\"Only captured payments can be refunded\");",
        "        }",
        "",
        "        PaymentProcessor processor = selectionStrategy.select(payment.getMethod());",
        "        ProcessorResponse refunded = callWithRetry(() -> processor.refund(payment), payment);",
        "        if (!refunded.isSuccess()) {",
        "            throw new IllegalStateException(\"Refund failed: \" + refunded.getMessage());",
        "        }",
        "",
        "        payment.markRefunded();",
        "        return payment;",
        "    }",
        "",
        "    public synchronized Optional<Payment> findPayment(String paymentId) {",
        "        return Optional.ofNullable(paymentsById.get(paymentId));",
        "    }",
        "",
        "    private ProcessorResponse callWithRetry(Supplier<ProcessorResponse> operation, Payment payment) {",
        "        ProcessorResponse response = null;",
        "        for (int attempt = 1; attempt <= maxAttempts; attempt++) {",
        "            response = operation.get();",
        "            if (response.isSuccess() || !response.isRetryable() || attempt == maxAttempts) {",
        "                return response;",
        "            }",
        "            payment.incrementRetryCount();",
        "        }",
        "        return response;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        PaymentGatewayService gateway = PaymentGatewayService.defaultGateway();",
        "",
        "        Payment cardPayment = gateway.processPayment(",
        "            \"merchant-42\",",
        "            2599,",
        "            \"INR\",",
        "            PaymentMethod.card(\"tok_card_visa\"),",
        "            \"order-1001\"",
        "        );",
        "",
        "        Payment replay = gateway.processPayment(",
        "            \"merchant-42\",",
        "            2599,",
        "            \"INR\",",
        "            PaymentMethod.card(\"tok_card_visa\"),",
        "            \"order-1001\"",
        "        );",
        "",
        "        Payment upiPayment = gateway.processPayment(",
        "            \"merchant-42\",",
        "            4999,",
        "            \"INR\",",
        "            PaymentMethod.upi(\"alice@upi\"),",
        "            \"order-1002\"",
        "        );",
        "",
        "        gateway.refund(\"order-1001\");",
        "",
        "        System.out.println(cardPayment);",
        "        System.out.println(\"Idempotent replay returned same object: \" + (cardPayment == replay));",
        "        System.out.println(upiPayment);",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "PaymentMethod",
      detailMD:
        "Normalized method abstraction for card, wallet, and UPI. Static factory methods keep construction concise while hiding the simple implementation class.",
    },
    {
      className: "Payment",
      detailMD:
        "Transaction aggregate with the embedded **PaymentStatus** state machine. It stores request facts, mutable status, provider reference, retry count, and failure reason; all state changes go through lifecycle methods.",
    },
    {
      className: "PaymentProcessor",
      detailMD:
        "Common processor port plus normalized **ProcessorResponse**. It lets the gateway treat authorization, capture, and refund consistently across providers.",
    },
    {
      className: "StripeAdapter",
      detailMD:
        "Adapter for a Stripe-like card processor. It validates card routing, maps provider success to a provider reference, and classifies failures as retryable or permanent.",
    },
    {
      className: "PayPalAdapter",
      detailMD:
        "Adapter for a PayPal-like wallet and UPI processor. It exposes the same **PaymentProcessor** methods even though the downstream provider has different capabilities.",
    },
    {
      className: "ProcessorSelectionStrategy",
      detailMD:
        "Strategy interface and method-based implementation. It maps **CARD** to Stripe and **WALLET** or **UPI** to PayPal in the base design, but the gateway only depends on **select**.",
    },
    {
      className: "PaymentGatewayService",
      detailMD:
        "Orchestrates the use case. It checks idempotency first, creates and stores the payment, asks the strategy for a processor, retries safe failures, advances state, and handles refunds.",
    },
    {
      className: "Main",
      detailMD:
        "Small demo showing a card payment, an idempotent replay with the same key, a UPI payment routed to the other adapter, and a refund of the captured card payment.",
    },
  ],

  dryRun: {
    inputMD:
      "Merchant **merchant-42** submits a 2599 INR card payment with idempotency key **order-1001**, retries the same request once, then asks for a refund. A second UPI payment uses key **order-1002**.",
    columns: ["Step", "Action", "Processor", "Status", "Idempotency store", "Result"],
    rows: [
      ["1", "process card key order-1001", "StripeAdapter", "INITIATED", "{order-1001 → P1}", "new payment P1 created"],
      ["2", "authorize P1", "StripeAdapter", "AUTHORIZED", "{order-1001 → P1}", "provider reference stored"],
      ["3", "capture P1", "StripeAdapter", "CAPTURED", "{order-1001 → P1}", "merchant receives captured payment"],
      ["4", "replay key order-1001", "none", "CAPTURED", "{order-1001 → P1}", "same P1 returned, no processor call"],
      ["5", "process UPI key order-1002", "PayPalAdapter", "CAPTURED", "{order-1001 → P1, order-1002 → P2}", "UPI routed by strategy"],
      ["6", "refund order-1001", "StripeAdapter", "REFUNDED", "{order-1001 → P1, order-1002 → P2}", "P1 moves to refunded"],
    ],
    narrativeMD:
      "The dry run highlights the key interview invariant: replay happens before any adapter call, while refund is allowed only after capture.",
  },

  complexity: [
    {
      operation: "processPayment with new key",
      time: "O(A)",
      space: "O(1)",
      note: "A is the configured retry attempt count; routing and state transitions are constant time.",
    },
    {
      operation: "processPayment with existing key",
      time: "O(1)",
      space: "O(1)",
      note: "One hash-map lookup returns the already stored payment.",
    },
    {
      operation: "refund",
      time: "O(A)",
      space: "O(1)",
      note: "Lookup, state check, processor refund call, and at most A attempts.",
    },
    {
      operation: "select processor",
      time: "O(1)",
      space: "O(1)",
      note: "The method-based strategy uses an enum map.",
    },
    {
      operation: "findPayment",
      time: "O(1)",
      space: "O(1)",
      note: "Direct lookup by generated payment id.",
    },
  ],
  complexityNotesMD:
    "The interesting cost is not CPU; it is correctness under remote calls. The gateway keeps local orchestration constant-time and pushes network latency, retry policy, and provider rate limits behind adapters.",

  extensibility: [
    {
      label: "New processor",
      detailMD:
        "Implement **PaymentProcessor** in a new adapter such as **RazorpayAdapter** and add it to the routing strategy configuration.",
    },
    {
      label: "New payment method",
      detailMD:
        "Add a **PaymentMethodType** value and a factory method on **PaymentMethod**, then teach the strategy which processor supports it.",
    },
    {
      label: "Advanced routing",
      detailMD:
        "Replace method-based routing with a strategy that considers merchant, country, currency, live success rates, cost, or circuit-breaker health.",
    },
    {
      label: "Partial refunds",
      detailMD:
        "Introduce a refund aggregate with amount, status, and provider reference. Keep **Payment** captured until the total refunded amount reaches the captured amount.",
    },
    {
      label: "Webhook reconciliation",
      detailMD:
        "Add provider webhook adapters that reconcile asynchronous authorization, capture, or refund events back into the same state machine.",
    },
  ],

  alternativeDesigns: [
    {
      name: "One adapter per payment method",
      detailMD:
        "Create **CardProcessor**, **WalletProcessor**, and **UpiProcessor** interfaces instead of one **PaymentProcessor**.",
      tradeoffsMD:
        "Method-specific interfaces can expose richer capabilities, but merchants and gateway orchestration now depend on more ports and duplicate lifecycle logic.",
    },
    {
      name: "Processor enum with switch statements",
      detailMD:
        "Represent providers as enum values and switch inside **PaymentGatewayService** for routing and provider calls.",
      tradeoffsMD:
        "This is quick for a demo but violates open-closed design: every new provider edits the central service and risks breaking existing routes.",
    },
    {
      name: "Command objects for each operation",
      detailMD:
        "Represent authorize, capture, and refund as command objects that can be persisted and replayed by workers.",
      tradeoffsMD:
        "Useful for distributed production systems and outbox processing, but it adds infrastructure that can distract from the core interview model.",
    },
  ],

  commonMistakes: [
    "Putting Stripe and PayPal request details directly inside **PaymentGatewayService** instead of adapters.",
    "Using one switch for card, wallet, UPI, and provider routing, which mixes Strategy and Adapter responsibilities.",
    "Creating a new payment before checking the idempotency key, causing duplicate charges on merchant retry.",
    "Treating retry as a blind loop without distinguishing retryable and permanent failures.",
    "Allowing invalid state jumps such as **Initiated** to **Captured** or **Failed** to **Refunded**.",
    "Refunding without checking that the payment is already captured.",
    "Losing the provider reference needed to capture or refund with the downstream processor.",
  ],

  followUps: [
    {
      question: "How would you support partial refunds?",
      answerMD:
        "Add a **Refund** entity with amount, idempotency key, status, and provider reference. A payment may have many refunds, and the aggregate enforces that total refunded amount never exceeds captured amount.",
    },
    {
      question: "What changes when capture is asynchronous?",
      answerMD:
        "Introduce **CapturePending** or an operation record, persist the request, and let provider webhooks move the payment to **Captured** or **Failed**. The same state machine remains the source of truth.",
    },
    {
      question: "How do you prevent duplicate provider calls across multiple app instances?",
      answerMD:
        "Back the idempotency store with a database unique constraint on merchant id plus idempotency key and run creation plus state update in a transaction or with row-level locking.",
    },
    {
      question: "How would routing prefer the cheapest healthy processor?",
      answerMD:
        "Implement a new **ProcessorSelectionStrategy** that reads health and pricing metadata, filters unhealthy processors, and returns the lowest-cost eligible adapter.",
    },
    {
      question: "Where do webhooks belong in this design?",
      answerMD:
        "As inbound adapters that translate provider webhook payloads into domain events or service calls. They should not bypass the payment state machine.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistent idempotency store",
      detailMD:
        "Use a durable table keyed by merchant id and idempotency key with a unique constraint. Store request hash and response snapshot to detect conflicting replays.",
    },
    {
      label: "Outbox and retries",
      detailMD:
        "For real remote calls, persist operation intents and process them through an outbox worker so retries survive service restarts.",
    },
    {
      label: "Provider reconciliation",
      detailMD:
        "Regularly compare gateway state with processor reports and webhooks. Payments can be locally failed while the provider eventually succeeds unless reconciled.",
    },
    {
      label: "Security and compliance",
      detailMD:
        "Do not store raw card data. Store tokens, encrypt sensitive references, scope access tightly, and meet PCI requirements where card data is handled.",
    },
    {
      label: "Observability",
      detailMD:
        "Emit metrics for authorization success rate, capture success rate, retry count, refund failure rate, provider latency, and idempotent replay volume.",
    },
    {
      label: "Circuit breakers",
      detailMD:
        "Adapters should expose health to the routing strategy so a degraded processor is avoided before merchants see repeated failures.",
    },
  ],

  interviewNotes: [
    "Do they separate routing policy from provider translation, or do they put everything in one service?",
    "Do they explain why idempotency must be checked before external side effects?",
    "Do they use an explicit state machine instead of scattered status assignments?",
    "Do they classify failures so retries are safe and bounded?",
    "Do they preserve the provider reference needed for capture and refund?",
    "Can they evolve the design toward partial refunds, webhooks, and multi-instance consistency without rewriting the core model?",
  ],

  quiz: [
    {
      question: "Why is **ProcessorSelectionStrategy** separate from **StripeAdapter** and **PayPalAdapter**?",
      options: [
        "The strategy decides which processor to use, while adapters translate how to call each processor",
        "Adapters cannot be used with interfaces in Java",
        "It makes every payment method use the same provider",
        "It removes the need for idempotency",
      ],
      answerIndex: 0,
      explanationMD:
        "Routing policy and provider translation vary for different reasons, so they should be separate seams.",
    },
    {
      question: "What is the safest first step in **processPayment**?",
      options: [
        "Call authorize immediately",
        "Create a new provider charge id",
        "Look up the idempotency key",
        "Refund any previous payment",
      ],
      answerIndex: 2,
      explanationMD:
        "A replay must return the original payment before any new external side effect can occur.",
    },
    {
      question: "Which transition should the base state machine reject?",
      options: [
        "INITIATED to AUTHORIZED",
        "AUTHORIZED to CAPTURED",
        "CAPTURED to REFUNDED",
        "FAILED to REFUNDED",
      ],
      answerIndex: 3,
      explanationMD:
        "A failed payment did not capture funds, so refunding it is invalid.",
    },
    {
      question: "What should an adapter return for a provider timeout?",
      options: [
        "A retryable failure response",
        "A captured payment",
        "A refund response",
        "A new routing strategy",
      ],
      answerIndex: 0,
      explanationMD:
        "Timeouts may be transient, so the adapter should classify them as retryable and let the service apply bounded retry policy.",
    },
    {
      question: "What does **PaymentMethod.card** demonstrate?",
      options: [
        "Adapter pattern",
        "Factory Method style construction for valid method objects",
        "Observer pattern",
        "A database transaction",
      ],
      answerIndex: 1,
      explanationMD:
        "The caller asks a named factory method for a valid card method instead of constructing implementation details directly.",
    },
  ],

  practiceVariants: [
    {
      title: "Add partial refunds",
      detailMD:
        "Model multiple refund records per payment, each with its own idempotency key and status, and enforce that total refunded amount never exceeds captured amount.",
      difficulty: "Advanced",
    },
    {
      title: "Add processor health based routing",
      detailMD:
        "Replace method-only routing with a strategy that considers provider health, currency support, success rate, and merchant preferences.",
      difficulty: "Expert",
    },
    {
      title: "Add asynchronous webhooks",
      detailMD:
        "Introduce webhook adapters that translate provider events into safe state transitions and reconcile pending captures or refunds.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "What is the split between Strategy and Adapter in a payment gateway?",
      back: "Strategy chooses which processor route to use; Adapter translates the selected provider API into the common **PaymentProcessor** interface.",
    },
    {
      front: "Why is idempotency required for payments?",
      back: "Merchants and networks retry. The same idempotency key must return the same payment so a retry does not create a duplicate charge.",
    },
    {
      front: "What are the core states in this design?",
      back: "**Initiated**, **Authorized**, **Captured**, **Failed**, and **Refunded**.",
    },
    {
      front: "When can a payment be refunded?",
      back: "Only after it is **Captured** and the selected processor successfully completes the refund.",
    },
    {
      front: "What does a processor adapter normalize?",
      back: "Provider-specific authorization, capture, refund calls, provider references, and failure classification.",
    },
    {
      front: "What makes a retry safe in this model?",
      back: "Bounded retry of a retryable response using the same **Payment** and idempotency key, without creating another transaction.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** PaymentGatewayService, Payment, PaymentStatus, PaymentMethod, PaymentProcessor, provider adapters, ProcessorSelectionStrategy.",
    "",
    "**Lifecycle:** Initiated → Authorized → Captured; Initiated or Authorized may move to Failed; Captured may move to Refunded.",
    "",
    "**Patterns:** Adapter for providers, Strategy for routing, State for transaction lifecycle, Factory Method for safe construction.",
    "",
    "**Critical flow:** check idempotency → create payment → select processor → authorize → mark authorized → capture → mark captured.",
    "",
    "**Retries:** adapter classifies retryable vs permanent failure; service retries only retryable failures with the same payment identity.",
    "",
    "**Refund:** allowed from Captured only; call selected processor and mark Refunded only after success.",
    "",
    "**Production upgrades:** durable idempotency table, outbox retries, webhooks, reconciliation, partial refunds, circuit breakers, PCI-safe token storage.",
  ].join("\n"),

  references: [
    {
      title: "Enterprise Integration Patterns",
      kind: "Book",
      author: "Gregor Hohpe and Bobby Woolf",
    },
    {
      title: "Refactoring Guru — Adapter Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/adapter",
    },
    {
      title: "Stripe API Docs — Idempotent Requests",
      kind: "Docs",
      url: "https://docs.stripe.com/api/idempotent_requests",
    },
    {
      title: "PCI Security Standards Council — PCI DSS",
      kind: "Docs",
      url: "https://www.pcisecuritystandards.org/standards/",
    },
  ],

  relatedProblems: [
    { slug: "digital-wallet", note: "Wallet balance and money movement build on the same transaction and idempotency ideas." },
    { slug: "banking-system", note: "Extends the financial lifecycle into ledgers, accounts, and stronger consistency." },
    { slug: "api-gateway", note: "Shows routing, adapters, retries, and circuit breakers at the service boundary." },
  ],
};
