import type { LLDProblemContent } from "../types";

export const ragPipeline: LLDProblemContent = {
  slug: "rag-pipeline",

  statementMD: [
    "Design the low-level object model for a **Retrieval Augmented Generation pipeline**.",
    "The system ingests documents, chunks them, creates embeddings, stores vectors, retrieves the most relevant chunks for a user question, assembles a grounded prompt, and sends that prompt to a generator.",
    "",
    "The interview focus is not model quality or distributed indexing. It is the **class design**: clean stage boundaries, pluggable chunking and embedding strategies, swappable vector-store implementations, and a chain that can be extended without rewriting the pipeline.",
  ].join("\n"),

  businessContextMD: [
    "RAG systems are common in enterprise search, support assistants, compliance copilots, and internal knowledge bots. Teams rarely use one permanent embedding vendor or vector database; they evaluate local models, OpenAI or Azure embeddings, Pinecone, pgvector, Elasticsearch, and in-memory stores during development.",
    "",
    "A strong LLD answer keeps the retrieval path independent from those vendor decisions. The core pipeline should say **what** happens at each stage, while adapters and factories decide **how** a concrete provider or store is used.",
  ].join("\n"),

  functionalRequirements: [
    "Accept one or more source documents with id, title, text, and metadata.",
    "Split each document into ordered chunks using a pluggable chunking strategy.",
    "Embed chunks through an embedding provider interface that can adapt different vendor clients.",
    "Persist embedded chunks in a vector store interface with swappable backends.",
    "Retrieve the top K chunks for a user question using query embedding plus vector similarity.",
    "Assemble a grounded prompt from the question and retrieved chunks.",
    "Generate an answer through an injectable generator step.",
    "Wire ingestion, chunking, embedding, indexing, retrieval, prompt assembly, and generation as a chain of stages.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Provider portability",
      detailMD:
        "Embedding and vector storage must be replaceable without changing the pipeline stages or retriever.",
    },
    {
      label: "Deterministic boundaries",
      detailMD:
        "Every stage consumes and produces clear domain objects so failures are easy to isolate and retry.",
    },
    {
      label: "Low coupling",
      detailMD:
        "Vendor SDKs stay behind adapters. The domain never imports a Pinecone, pgvector, OpenAI, or Azure client type.",
    },
    {
      label: "Testability",
      detailMD:
        "Unit tests should run with a local hash embedding provider and in-memory vector store, while production uses real backends.",
    },
    {
      label: "Incremental extensibility",
      detailMD:
        "Adding reranking, filtering, caching, or moderation should mean adding a stage or strategy, not editing every existing class.",
    },
  ],

  requirementClarification: [
    {
      question: "Are we designing offline ingestion or online question answering?",
      answerMD:
        "Model both paths in one pipeline for the LLD exercise. Documents are indexed first, then the same request retrieves chunks and generates an answer.",
    },
    {
      question: "Do embeddings come from one fixed model?",
      answerMD:
        "No. Treat embeddings as a provider interface. The implementation includes a local hashing provider for demos and an adapter method for vendor clients.",
    },
    {
      question: "Which vector database should we assume?",
      answerMD:
        "Do not hard-code one. Define a **VectorStore** interface and ship an in-memory implementation; production can plug in pgvector, Pinecone, Elasticsearch, or another backend.",
    },
    {
      question: "Do we need semantic reranking, citations, or streaming tokens?",
      answerMD:
        "Not in the base design. Keep retrieval top K and prompt assembly simple, then call out reranking, citation formatting, and streaming as extensions.",
    },
    {
      question: "Should chunks be mutable once indexed?",
      answerMD:
        "No. Model **Document** and **Chunk** as immutable values. Attaching an embedding returns a new chunk so indexing cannot observe partially mutated state.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Document {",
    "        -String id",
    "        -String title",
    "        -String text",
    "        -Map~String,String~ metadata",
    "    }",
    "    class Chunk {",
    "        -String id",
    "        -String documentId",
    "        -int index",
    "        -String text",
    "        -double[] embedding",
    "        +withEmbedding(double[]) Chunk",
    "    }",
    "    class ChunkingStrategy {",
    "        <<interface>>",
    "        +chunk(Document) List~Chunk~",
    "        +fixedSize(int,int) ChunkingStrategy",
    "    }",
    "    class EmbeddingProvider {",
    "        <<interface>>",
    "        +embed(String) double[]",
    "        +fromClient(EmbeddingClient) EmbeddingProvider",
    "        +localHashing(int) EmbeddingProvider",
    "    }",
    "    class VectorStore {",
    "        <<interface>>",
    "        +upsert(List~Chunk~) void",
    "        +similaritySearch(double[],int) List~SearchResult~",
    "        +inMemory() VectorStore",
    "    }",
    "    class Retriever {",
    "        -EmbeddingProvider embeddingProvider",
    "        -VectorStore vectorStore",
    "        -int topK",
    "        +retrieve(String) List~SearchResult~",
    "    }",
    "    class RagPipeline {",
    "        -Stage firstStage",
    "        +answer(List~Document~,String) String",
    "        +builder() Builder",
    "    }",
    "    class Main",
    "    Document --> Chunk",
    "    ChunkingStrategy ..> Document",
    "    ChunkingStrategy ..> Chunk",
    "    Retriever ..> EmbeddingProvider",
    "    Retriever ..> VectorStore",
    "    VectorStore ..> Chunk",
    "    RagPipeline ..> ChunkingStrategy",
    "    RagPipeline ..> EmbeddingProvider",
    "    RagPipeline ..> VectorStore",
    "    RagPipeline o-- Retriever",
    "    Main ..> RagPipeline",
  ].join("\n"),
  classDiagramCaptionMD:
    "The pipeline depends on abstractions for chunking, embeddings, storage, retrieval, prompt assembly, and generation. Swapping a model or vector backend changes construction, not orchestration.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Pipe as RagPipeline",
    "    participant Ingest as IngestionStage",
    "    participant Chunker as ChunkingStage",
    "    participant Embed as EmbeddingStage",
    "    participant Store as VectorStore",
    "    participant Ret as Retriever",
    "    participant Prompt as PromptStage",
    "    participant Gen as GeneratorStage",
    "    User->>Pipe: answer(documents, question)",
    "    Pipe->>Ingest: handle(context)",
    "    Ingest->>Chunker: next(context)",
    "    Chunker->>Chunker: chunk documents",
    "    Chunker->>Embed: next(context)",
    "    Embed->>Embed: embed chunks",
    "    Embed->>Store: upsert(embeddedChunks)",
    "    Store-->>Embed: indexed",
    "    Embed->>Ret: retrieve(question)",
    "    Ret->>Store: similaritySearch(queryEmbedding, topK)",
    "    Store-->>Ret: ranked chunks",
    "    Ret-->>Prompt: results",
    "    Prompt->>Gen: prompt",
    "    Gen-->>Pipe: answer",
    "    Pipe-->>User: grounded answer",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Each stage mutates only the request context and forwards to the next stage. The Retriever talks to interfaces, so it does not care whether vectors live in memory, pgvector, Pinecone, or another store.",

  entities: [
    {
      name: "Document",
      responsibilityMD:
        "Immutable source text with identity and metadata. It represents the raw unit of ingestion before chunking.",
      attributes: ["id", "title", "text", "metadata"],
    },
    {
      name: "Chunk",
      responsibilityMD:
        "Immutable fragment derived from a document. It carries document lineage, order, text, and an optional embedding vector.",
      attributes: ["id", "documentId", "index", "text", "embedding"],
    },
    {
      name: "ChunkingStrategy",
      responsibilityMD:
        "Strategy interface for splitting documents. Fixed-size, sentence-aware, markdown-aware, or semantic chunkers can share the same contract.",
      attributes: ["chunk(document)"],
    },
    {
      name: "EmbeddingProvider",
      responsibilityMD:
        "Provider abstraction for turning text into vectors. The adapter factory wraps vendor clients behind the same **embed** method.",
      attributes: ["embed(text)", "fromClient(client)", "localHashing(dimensions)"],
    },
    {
      name: "VectorStore",
      responsibilityMD:
        "Storage abstraction for embedded chunks. It supports upsert and similarity search while hiding the chosen backend.",
      attributes: ["upsert(chunks)", "similaritySearch(queryEmbedding, topK)"],
    },
    {
      name: "Retriever",
      responsibilityMD:
        "Embeds the user query, asks the vector store for top K chunks, and returns ranked search results.",
      attributes: ["embeddingProvider", "vectorStore", "topK"],
    },
    {
      name: "RagPipeline",
      responsibilityMD:
        "Facade over a chain of stages: validate, chunk, embed, index, retrieve, assemble prompt, and generate answer.",
      attributes: ["firstStage", "Builder", "PromptAssembler", "Generator"],
    },
    {
      name: "StageContext",
      responsibilityMD:
        "Internal request state passed through the chain. It prevents long method signatures and keeps intermediate data scoped to one run.",
      attributes: ["documents", "question", "chunks", "retrieved", "prompt", "answer"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**ChunkingStrategy**, **EmbeddingProvider**, prompt assembly, and generation are behavior seams. The pipeline calls interfaces while concrete choices are injected.",
    },
    {
      name: "Chain of Responsibility",
      whyMD:
        "**RagPipeline** links stages so ingestion, chunking, embedding, indexing, retrieval, prompt assembly, and generation can be extended or reordered without one large method.",
    },
    {
      name: "Adapter",
      whyMD:
        "**EmbeddingProvider.fromClient** adapts any vendor-specific embedding client into the domain interface, keeping SDK classes out of the core model.",
    },
    {
      name: "Factory Method",
      whyMD:
        "Static factory methods such as **ChunkingStrategy.fixedSize**, **EmbeddingProvider.localHashing**, **EmbeddingProvider.fromClient**, and **VectorStore.inMemory** create concrete implementations behind interfaces.",
    },
  ],

  designSteps: [
    {
      title: "Start with immutable ingestion values",
      detailMD:
        "Make **Document** and **Chunk** immutable. A chunk with an embedding is a new value, so callers never observe a half-indexed chunk.",
      code: [
        "Chunk embedded = chunk.withEmbedding(embeddingProvider.embed(chunk.getText()));",
        "vectorStore.upsert(java.util.Collections.singletonList(embedded));",
      ].join("\n"),
    },
    {
      title: "Hide chunking policy behind a strategy",
      detailMD:
        "Different corpora need different splitting rules: fixed-size windows, sentence boundaries, markdown sections, or semantic windows. The pipeline only depends on **chunk(document)**.",
      code: [
        "ChunkingStrategy chunker = ChunkingStrategy.fixedSize(500, 80);",
        "List<Chunk> chunks = chunker.chunk(document);",
      ].join("\n"),
    },
    {
      title: "Adapt embedding vendors at the boundary",
      detailMD:
        "Do not let SDK clients leak into the pipeline. Wrap them once and expose a stable **EmbeddingProvider** interface to the rest of the design.",
      code: [
        "EmbeddingProvider provider = EmbeddingProvider.fromClient(text -> externalClient.embed(text));",
        "double[] vector = provider.embed(\"refund policy\");",
      ].join("\n"),
    },
    {
      title: "Make vector storage a backend-neutral contract",
      detailMD:
        "**VectorStore** exposes **upsert** and **similaritySearch** only. In-memory storage supports tests; production stores can implement the same methods with indexes and filters.",
    },
    {
      title: "Keep retrieval small and injectable",
      detailMD:
        "**Retriever** embeds the question, asks the store for nearest chunks, and returns ranked results. It does not know how chunks were generated or which database answered the query.",
      code: [
        "Retriever retriever = new Retriever(provider, vectorStore, 3);",
        "List<VectorStore.SearchResult> hits = retriever.retrieve(\"How do we deploy safely?\");",
      ].join("\n"),
    },
    {
      title: "Wire the flow as a chain of stages",
      detailMD:
        "The chain keeps orchestration readable and open for additions such as reranking, query rewriting, access filtering, caching, or moderation.",
      code: [
        "RagPipeline pipeline = new RagPipeline.Builder()",
        "    .chunkingStrategy(ChunkingStrategy.fixedSize(500, 80))",
        "    .embeddingProvider(EmbeddingProvider.localHashing(64))",
        "    .vectorStore(VectorStore.inMemory())",
        "    .topK(3)",
        "    .build();",
      ].join("\n"),
    },
    {
      title: "Assemble prompts after retrieval, not before",
      detailMD:
        "Prompt assembly should consume ranked chunks and the original question. Keeping it as a strategy makes it easy to add citations, token budgets, safety text, or model-specific formatting.",
    },
  ],

  implementation: [
    {
      filename: "Document.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class Document {",
        "    private final String id;",
        "    private final String title;",
        "    private final String text;",
        "    private final Map<String, String> metadata;",
        "",
        "    public Document(String id, String title, String text, Map<String, String> metadata) {",
        "        this.id = requireText(\"id\", id);",
        "        this.title = requireText(\"title\", title);",
        "        this.text = requireText(\"text\", text);",
        "        Objects.requireNonNull(metadata, \"metadata\");",
        "        this.metadata = Collections.unmodifiableMap(new LinkedHashMap<>(metadata));",
        "    }",
        "",
        "    public static Document of(String id, String title, String text) {",
        "        return new Document(id, title, text, Collections.emptyMap());",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getTitle() {",
        "        return title;",
        "    }",
        "",
        "    public String getText() {",
        "        return text;",
        "    }",
        "",
        "    public Map<String, String> getMetadata() {",
        "        return metadata;",
        "    }",
        "",
        "    private static String requireText(String name, String value) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(name + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Chunk.java",
      language: "java",
      content: [
        "import java.util.Arrays;",
        "",
        "public final class Chunk {",
        "    private final String id;",
        "    private final String documentId;",
        "    private final int index;",
        "    private final String text;",
        "    private final double[] embedding;",
        "",
        "    public Chunk(String id, String documentId, int index, String text) {",
        "        this(id, documentId, index, text, null);",
        "    }",
        "",
        "    private Chunk(String id, String documentId, int index, String text, double[] embedding) {",
        "        this.id = requireText(\"id\", id);",
        "        this.documentId = requireText(\"documentId\", documentId);",
        "        if (index < 0) {",
        "            throw new IllegalArgumentException(\"index must be non-negative\");",
        "        }",
        "        this.index = index;",
        "        this.text = requireText(\"text\", text);",
        "        this.embedding = embedding == null ? null : Arrays.copyOf(embedding, embedding.length);",
        "    }",
        "",
        "    public Chunk withEmbedding(double[] vector) {",
        "        if (vector == null || vector.length == 0) {",
        "            throw new IllegalArgumentException(\"embedding is required\");",
        "        }",
        "        return new Chunk(id, documentId, index, text, vector);",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getDocumentId() {",
        "        return documentId;",
        "    }",
        "",
        "    public int getIndex() {",
        "        return index;",
        "    }",
        "",
        "    public String getText() {",
        "        return text;",
        "    }",
        "",
        "    public boolean hasEmbedding() {",
        "        return embedding != null;",
        "    }",
        "",
        "    public double[] getEmbedding() {",
        "        return embedding == null ? null : Arrays.copyOf(embedding, embedding.length);",
        "    }",
        "",
        "    private static String requireText(String name, String value) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(name + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ChunkingStrategy.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public interface ChunkingStrategy {",
        "    List<Chunk> chunk(Document document);",
        "",
        "    static ChunkingStrategy fixedSize(int maxChars, int overlapChars) {",
        "        if (maxChars <= 0) {",
        "            throw new IllegalArgumentException(\"maxChars must be positive\");",
        "        }",
        "        if (overlapChars < 0 || overlapChars >= maxChars) {",
        "            throw new IllegalArgumentException(\"overlapChars must be between 0 and maxChars - 1\");",
        "        }",
        "        return document -> {",
        "            Objects.requireNonNull(document, \"document\");",
        "            List<Chunk> chunks = new ArrayList<>();",
        "            String text = document.getText();",
        "            int start = 0;",
        "            int index = 0;",
        "            while (start < text.length()) {",
        "                int end = Math.min(start + maxChars, text.length());",
        "                String piece = text.substring(start, end).trim();",
        "                if (!piece.isEmpty()) {",
        "                    String id = document.getId() + \"-chunk-\" + index;",
        "                    chunks.add(new Chunk(id, document.getId(), index, piece));",
        "                    index++;",
        "                }",
        "                if (end == text.length()) {",
        "                    break;",
        "                }",
        "                start = Math.max(end - overlapChars, start + 1);",
        "            }",
        "            return chunks;",
        "        };",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "EmbeddingProvider.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public interface EmbeddingProvider {",
        "    double[] embed(String text);",
        "",
        "    static EmbeddingProvider fromClient(EmbeddingClient client) {",
        "        Objects.requireNonNull(client, \"client\");",
        "        return text -> normalize(client.embed(text));",
        "    }",
        "",
        "    static EmbeddingProvider localHashing(int dimensions) {",
        "        if (dimensions <= 0) {",
        "            throw new IllegalArgumentException(\"dimensions must be positive\");",
        "        }",
        "        return text -> {",
        "            Objects.requireNonNull(text, \"text\");",
        "            double[] vector = new double[dimensions];",
        "            String[] tokens = text.toLowerCase().split(\"\\\\W+\");",
        "            for (String token : tokens) {",
        "                if (!token.isEmpty()) {",
        "                    int index = Math.floorMod(token.hashCode(), dimensions);",
        "                    vector[index] += 1.0;",
        "                }",
        "            }",
        "            return normalize(vector);",
        "        };",
        "    }",
        "",
        "    static double[] normalize(double[] vector) {",
        "        if (vector == null || vector.length == 0) {",
        "            throw new IllegalArgumentException(\"embedding vector is required\");",
        "        }",
        "        double norm = 0.0;",
        "        for (double value : vector) {",
        "            norm += value * value;",
        "        }",
        "        if (norm == 0.0) {",
        "            return vector.clone();",
        "        }",
        "        double scale = Math.sqrt(norm);",
        "        double[] normalized = new double[vector.length];",
        "        for (int i = 0; i < vector.length; i++) {",
        "            normalized[i] = vector[i] / scale;",
        "        }",
        "        return normalized;",
        "    }",
        "",
        "    interface EmbeddingClient {",
        "        double[] embed(String text);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "VectorStore.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Comparator;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public interface VectorStore {",
        "    void upsert(List<Chunk> chunks);",
        "",
        "    List<SearchResult> similaritySearch(double[] queryEmbedding, int topK);",
        "",
        "    static VectorStore inMemory() {",
        "        return new VectorStore() {",
        "            private final Map<String, Chunk> chunksById = new LinkedHashMap<>();",
        "",
        "            @Override",
        "            public synchronized void upsert(List<Chunk> chunks) {",
        "                Objects.requireNonNull(chunks, \"chunks\");",
        "                for (Chunk chunk : chunks) {",
        "                    if (!chunk.hasEmbedding()) {",
        "                        throw new IllegalArgumentException(\"chunk must have an embedding before indexing\");",
        "                    }",
        "                    chunksById.put(chunk.getId(), chunk);",
        "                }",
        "            }",
        "",
        "            @Override",
        "            public synchronized List<SearchResult> similaritySearch(double[] queryEmbedding, int topK) {",
        "                if (topK <= 0) {",
        "                    throw new IllegalArgumentException(\"topK must be positive\");",
        "                }",
        "                List<SearchResult> matches = new ArrayList<>();",
        "                for (Chunk chunk : chunksById.values()) {",
        "                    matches.add(new SearchResult(chunk, cosine(queryEmbedding, chunk.getEmbedding())));",
        "                }",
        "                matches.sort(Comparator.comparingDouble(SearchResult::getScore).reversed());",
        "                int end = Math.min(topK, matches.size());",
        "                return new ArrayList<>(matches.subList(0, end));",
        "            }",
        "        };",
        "    }",
        "",
        "    static double cosine(double[] left, double[] right) {",
        "        Objects.requireNonNull(left, \"left\");",
        "        Objects.requireNonNull(right, \"right\");",
        "        int length = Math.min(left.length, right.length);",
        "        double dot = 0.0;",
        "        double leftNorm = 0.0;",
        "        double rightNorm = 0.0;",
        "        for (int i = 0; i < length; i++) {",
        "            dot += left[i] * right[i];",
        "            leftNorm += left[i] * left[i];",
        "            rightNorm += right[i] * right[i];",
        "        }",
        "        if (leftNorm == 0.0 || rightNorm == 0.0) {",
        "            return 0.0;",
        "        }",
        "        return dot / (Math.sqrt(leftNorm) * Math.sqrt(rightNorm));",
        "    }",
        "",
        "    final class SearchResult {",
        "        private final Chunk chunk;",
        "        private final double score;",
        "",
        "        public SearchResult(Chunk chunk, double score) {",
        "            this.chunk = Objects.requireNonNull(chunk, \"chunk\");",
        "            this.score = score;",
        "        }",
        "",
        "        public Chunk getChunk() {",
        "            return chunk;",
        "        }",
        "",
        "        public double getScore() {",
        "            return score;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Retriever.java",
      language: "java",
      content: [
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class Retriever {",
        "    private final EmbeddingProvider embeddingProvider;",
        "    private final VectorStore vectorStore;",
        "    private final int topK;",
        "",
        "    public Retriever(EmbeddingProvider embeddingProvider, VectorStore vectorStore, int topK) {",
        "        this.embeddingProvider = Objects.requireNonNull(embeddingProvider, \"embeddingProvider\");",
        "        this.vectorStore = Objects.requireNonNull(vectorStore, \"vectorStore\");",
        "        if (topK <= 0) {",
        "            throw new IllegalArgumentException(\"topK must be positive\");",
        "        }",
        "        this.topK = topK;",
        "    }",
        "",
        "    public List<VectorStore.SearchResult> retrieve(String question) {",
        "        Objects.requireNonNull(question, \"question\");",
        "        double[] queryEmbedding = embeddingProvider.embed(question);",
        "        return vectorStore.similaritySearch(queryEmbedding, topK);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "RagPipeline.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class RagPipeline {",
        "    private final Stage firstStage;",
        "",
        "    private RagPipeline(Stage firstStage) {",
        "        this.firstStage = Objects.requireNonNull(firstStage, \"firstStage\");",
        "    }",
        "",
        "    public String answer(List<Document> documents, String question) {",
        "        StageContext context = new StageContext(documents, question);",
        "        firstStage.handle(context);",
        "        return context.answer;",
        "    }",
        "",
        "    public static Builder builder() {",
        "        return new Builder();",
        "    }",
        "",
        "    public interface PromptAssembler {",
        "        String assemble(String question, List<VectorStore.SearchResult> results);",
        "    }",
        "",
        "    public interface Generator {",
        "        String generate(String prompt);",
        "    }",
        "",
        "    public static PromptAssembler defaultPromptAssembler() {",
        "        return (question, results) -> {",
        "            String line = System.lineSeparator();",
        "            StringBuilder prompt = new StringBuilder();",
        "            prompt.append(\"Answer using only the retrieved context.\").append(line);",
        "            prompt.append(\"Question: \").append(question).append(line);",
        "            prompt.append(\"Context:\").append(line);",
        "            for (VectorStore.SearchResult result : results) {",
        "                prompt.append(\"- \").append(result.getChunk().getText()).append(line);",
        "            }",
        "            return prompt.toString();",
        "        };",
        "    }",
        "",
        "    public static Generator extractiveGenerator() {",
        "        return prompt -> \"Generated answer based on retrieved context:\"",
        "            + System.lineSeparator()",
        "            + prompt;",
        "    }",
        "",
        "    public static final class Builder {",
        "        private ChunkingStrategy chunkingStrategy = ChunkingStrategy.fixedSize(500, 80);",
        "        private EmbeddingProvider embeddingProvider = EmbeddingProvider.localHashing(64);",
        "        private VectorStore vectorStore = VectorStore.inMemory();",
        "        private int topK = 3;",
        "        private PromptAssembler promptAssembler = RagPipeline.defaultPromptAssembler();",
        "        private Generator generator = RagPipeline.extractiveGenerator();",
        "",
        "        public Builder chunkingStrategy(ChunkingStrategy chunkingStrategy) {",
        "            this.chunkingStrategy = Objects.requireNonNull(chunkingStrategy, \"chunkingStrategy\");",
        "            return this;",
        "        }",
        "",
        "        public Builder embeddingProvider(EmbeddingProvider embeddingProvider) {",
        "            this.embeddingProvider = Objects.requireNonNull(embeddingProvider, \"embeddingProvider\");",
        "            return this;",
        "        }",
        "",
        "        public Builder vectorStore(VectorStore vectorStore) {",
        "            this.vectorStore = Objects.requireNonNull(vectorStore, \"vectorStore\");",
        "            return this;",
        "        }",
        "",
        "        public Builder topK(int topK) {",
        "            if (topK <= 0) {",
        "                throw new IllegalArgumentException(\"topK must be positive\");",
        "            }",
        "            this.topK = topK;",
        "            return this;",
        "        }",
        "",
        "        public Builder promptAssembler(PromptAssembler promptAssembler) {",
        "            this.promptAssembler = Objects.requireNonNull(promptAssembler, \"promptAssembler\");",
        "            return this;",
        "        }",
        "",
        "        public Builder generator(Generator generator) {",
        "            this.generator = Objects.requireNonNull(generator, \"generator\");",
        "            return this;",
        "        }",
        "",
        "        public RagPipeline build() {",
        "            Retriever retriever = new Retriever(embeddingProvider, vectorStore, topK);",
        "            Stage ingestion = new IngestionStage();",
        "            ingestion",
        "                .linkWith(new ChunkingStage(chunkingStrategy))",
        "                .linkWith(new EmbeddingStage(embeddingProvider))",
        "                .linkWith(new IndexingStage(vectorStore))",
        "                .linkWith(new RetrievalStage(retriever))",
        "                .linkWith(new PromptStage(promptAssembler))",
        "                .linkWith(new GeneratorStage(generator));",
        "            return new RagPipeline(ingestion);",
        "        }",
        "    }",
        "",
        "    private abstract static class Stage {",
        "        private Stage next;",
        "",
        "        Stage linkWith(Stage nextStage) {",
        "            this.next = Objects.requireNonNull(nextStage, \"nextStage\");",
        "            return nextStage;",
        "        }",
        "",
        "        final void handle(StageContext context) {",
        "            execute(context);",
        "            if (next != null) {",
        "                next.handle(context);",
        "            }",
        "        }",
        "",
        "        abstract void execute(StageContext context);",
        "    }",
        "",
        "    private static final class StageContext {",
        "        private final List<Document> documents;",
        "        private final String question;",
        "        private List<Chunk> chunks = Collections.emptyList();",
        "        private List<VectorStore.SearchResult> retrieved = Collections.emptyList();",
        "        private String prompt = \"\";",
        "        private String answer = \"\";",
        "",
        "        StageContext(List<Document> documents, String question) {",
        "            Objects.requireNonNull(documents, \"documents\");",
        "            if (documents.isEmpty()) {",
        "                throw new IllegalArgumentException(\"documents must not be empty\");",
        "            }",
        "            this.documents = new ArrayList<>(documents);",
        "            this.question = requireText(\"question\", question);",
        "        }",
        "    }",
        "",
        "    private static final class IngestionStage extends Stage {",
        "        @Override",
        "        void execute(StageContext context) {",
        "            for (Document document : context.documents) {",
        "                Objects.requireNonNull(document, \"document\");",
        "            }",
        "        }",
        "    }",
        "",
        "    private static final class ChunkingStage extends Stage {",
        "        private final ChunkingStrategy chunkingStrategy;",
        "",
        "        ChunkingStage(ChunkingStrategy chunkingStrategy) {",
        "            this.chunkingStrategy = Objects.requireNonNull(chunkingStrategy, \"chunkingStrategy\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            List<Chunk> chunks = new ArrayList<>();",
        "            for (Document document : context.documents) {",
        "                chunks.addAll(chunkingStrategy.chunk(document));",
        "            }",
        "            context.chunks = chunks;",
        "        }",
        "    }",
        "",
        "    private static final class EmbeddingStage extends Stage {",
        "        private final EmbeddingProvider embeddingProvider;",
        "",
        "        EmbeddingStage(EmbeddingProvider embeddingProvider) {",
        "            this.embeddingProvider = Objects.requireNonNull(embeddingProvider, \"embeddingProvider\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            List<Chunk> embedded = new ArrayList<>();",
        "            for (Chunk chunk : context.chunks) {",
        "                embedded.add(chunk.withEmbedding(embeddingProvider.embed(chunk.getText())));",
        "            }",
        "            context.chunks = embedded;",
        "        }",
        "    }",
        "",
        "    private static final class IndexingStage extends Stage {",
        "        private final VectorStore vectorStore;",
        "",
        "        IndexingStage(VectorStore vectorStore) {",
        "            this.vectorStore = Objects.requireNonNull(vectorStore, \"vectorStore\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            vectorStore.upsert(context.chunks);",
        "        }",
        "    }",
        "",
        "    private static final class RetrievalStage extends Stage {",
        "        private final Retriever retriever;",
        "",
        "        RetrievalStage(Retriever retriever) {",
        "            this.retriever = Objects.requireNonNull(retriever, \"retriever\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            context.retrieved = retriever.retrieve(context.question);",
        "        }",
        "    }",
        "",
        "    private static final class PromptStage extends Stage {",
        "        private final PromptAssembler promptAssembler;",
        "",
        "        PromptStage(PromptAssembler promptAssembler) {",
        "            this.promptAssembler = Objects.requireNonNull(promptAssembler, \"promptAssembler\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            context.prompt = promptAssembler.assemble(context.question, context.retrieved);",
        "        }",
        "    }",
        "",
        "    private static final class GeneratorStage extends Stage {",
        "        private final Generator generator;",
        "",
        "        GeneratorStage(Generator generator) {",
        "            this.generator = Objects.requireNonNull(generator, \"generator\");",
        "        }",
        "",
        "        @Override",
        "        void execute(StageContext context) {",
        "            context.answer = generator.generate(context.prompt);",
        "        }",
        "    }",
        "",
        "    private static String requireText(String name, String value) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(name + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.util.Arrays;",
        "import java.util.Collections;",
        "import java.util.List;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Document deployment = new Document(",
        "            \"doc-1\",",
        "            \"Deployment Handbook\",",
        "            \"Deployments require a green build, canary rollout, and rollback plan before full release.\",",
        "            Collections.singletonMap(\"source\", \"handbook\")",
        "        );",
        "        Document incident = Document.of(",
        "            \"doc-2\",",
        "            \"Incident Playbook\",",
        "            \"After an incident, freeze risky releases, verify mitigation, and require approval from the incident commander.\"",
        "        );",
        "",
        "        RagPipeline pipeline = RagPipeline.builder()",
        "            .chunkingStrategy(ChunkingStrategy.fixedSize(120, 20))",
        "            .embeddingProvider(EmbeddingProvider.localHashing(32))",
        "            .vectorStore(VectorStore.inMemory())",
        "            .topK(2)",
        "            .build();",
        "",
        "        List<Document> documents = Arrays.asList(deployment, incident);",
        "        String answer = pipeline.answer(documents, \"How should we deploy after an incident?\");",
        "        System.out.println(answer);",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Document",
      detailMD:
        "Immutable ingestion record. It validates identity, title, text, and copies metadata so downstream stages cannot mutate the source while a run is in progress.",
    },
    {
      className: "Chunk",
      detailMD:
        "Immutable indexed fragment. **withEmbedding** returns a new chunk carrying a defensive copy of the vector, preserving clean stage handoff.",
    },
    {
      className: "ChunkingStrategy",
      detailMD:
        "Strategy interface for document splitting. The included **fixedSize** factory creates an overlapping window chunker; sentence-aware or markdown-aware chunkers can implement the same method.",
    },
    {
      className: "EmbeddingProvider",
      detailMD:
        "Embedding abstraction and adapter seam. **localHashing** is deterministic for tests, while **fromClient** wraps a real provider client behind the same **embed** contract.",
    },
    {
      className: "VectorStore",
      detailMD:
        "Backend-neutral vector index. **inMemory** demonstrates upsert and cosine similarity; production backends keep the same interface but delegate to specialized indexes.",
    },
    {
      className: "Retriever",
      detailMD:
        "Small query-time component. It embeds the question, asks the store for top K nearest chunks, and returns ranked search results without knowing backend details.",
    },
    {
      className: "RagPipeline",
      detailMD:
        "Builds and executes the chain of responsibility. The builder injects strategies and stores, then stages validate, chunk, embed, index, retrieve, assemble, and generate.",
    },
    {
      className: "Main",
      detailMD:
        "Demo composition root. It constructs documents, picks fixed-size chunking, local embeddings, an in-memory vector store, and runs the pipeline end to end.",
    },
  ],

  dryRun: {
    inputMD:
      "Documents: **Deployment Handbook** and **Incident Playbook**. Query: **How should we deploy after an incident?** Use fixed-size chunking, local hashing embeddings, in-memory vector store, and topK = 2.",
    columns: ["Step", "Stage", "Context change", "Pluggable seam", "Result"],
    rows: [
      [
        "1",
        "Ingestion",
        "Validate two immutable documents",
        "Document loader could change",
        "Context has 2 documents",
      ],
      [
        "2",
        "Chunking",
        "Split documents into overlapping chunks",
        "ChunkingStrategy",
        "Context has ordered chunks",
      ],
      [
        "3",
        "Embedding and indexing",
        "Attach vectors and upsert chunks",
        "EmbeddingProvider plus VectorStore",
        "Store contains embedded chunks",
      ],
      [
        "4",
        "Retrieval",
        "Embed query and run similarity search",
        "Retriever topK and VectorStore backend",
        "Top 2 incident and deployment chunks returned",
      ],
      [
        "5",
        "Prompt and generation",
        "Build grounded prompt and call generator",
        "PromptAssembler plus Generator",
        "Answer cites release freeze, canary, rollback, and approval guidance",
      ],
    ],
    narrativeMD:
      "The important observation is that the chain order stays stable while the embedding provider and vector store can be swapped at construction time.",
  },

  complexity: [
    {
      operation: "ingest and chunk N characters",
      time: "O(N)",
      space: "O(C)",
      note: "C is the number of chunks produced by the chosen chunking strategy.",
    },
    {
      operation: "embed and index C chunks",
      time: "O(C × E + storeUpsert)",
      space: "O(C × D)",
      note: "E is embedding-provider cost and D is embedding dimension.",
    },
    {
      operation: "in-memory similarity search",
      time: "O(C × D + C log C)",
      space: "O(C)",
      note: "The demo store scores every chunk and sorts. Approximate indexes improve this in production.",
    },
    {
      operation: "prompt assembly",
      time: "O(K × L)",
      space: "O(K × L)",
      note: "K retrieved chunks and L average chunk length are copied into the prompt.",
    },
  ],
  complexityNotesMD:
    "The LLD design intentionally hides backend complexity. A production vector store may use HNSW, IVF, disk-backed indexes, or metadata filters, but the retriever still calls **similaritySearch(queryEmbedding, topK)**.",

  extensibility: [
    {
      label: "Swap embedding model",
      detailMD:
        "Replace **EmbeddingProvider.localHashing** with **EmbeddingProvider.fromClient** wrapping Azure OpenAI, OpenAI, Cohere, local ONNX, or another model.",
    },
    {
      label: "Swap vector backend",
      detailMD:
        "Implement **VectorStore** for pgvector, Pinecone, Elasticsearch, Redis, or a sharded service. **Retriever** and **RagPipeline** do not change.",
    },
    {
      label: "Add reranking",
      detailMD:
        "Insert a **RerankingStage** after retrieval or decorate **Retriever**. It can call a cross-encoder and keep the same prompt assembly contract.",
    },
    {
      label: "Add access control",
      detailMD:
        "Add a metadata filter before similarity search or a stage that removes chunks the caller cannot see before prompt assembly.",
    },
    {
      label: "Add citations",
      detailMD:
        "Extend **Chunk** metadata and prompt assembly to include source title, section, and offsets. No embedding or storage contract needs to change.",
    },
  ],

  alternativeDesigns: [
    {
      name: "One service class with private helper methods",
      detailMD:
        "Put ingest, chunk, embed, retrieve, prompt, and generation methods inside one **RagService**.",
      tradeoffsMD:
        "Fast to code in an interview, but policy decisions become private methods and stage insertion requires editing the central class.",
    },
    {
      name: "Event-driven ingestion and query services",
      detailMD:
        "Split document ingestion into an asynchronous worker and keep online query answering in a separate service.",
      tradeoffsMD:
        "Better production scalability, retries, and isolation, but more infrastructure than an LLD interview usually needs.",
    },
    {
      name: "Repository-style vector store only",
      detailMD:
        "Treat vector storage as a repository and keep retrieval logic in the application service.",
      tradeoffsMD:
        "Simple for CRUD-like systems, but it mixes query embedding, nearest-neighbor policy, and prompt needs unless **Retriever** remains a separate object.",
    },
  ],

  commonMistakes: [
    "Hard-coding one embedding provider directly inside the pipeline.",
    "Letting vector database SDK types leak into **Retriever** or **RagPipeline**.",
    "Making chunks mutable and attaching embeddings in place across multiple stages.",
    "Writing one giant **answer** method instead of isolated stages with clear responsibilities.",
    "Treating prompt assembly as string concatenation hidden inside the generator, which makes citations and token limits difficult.",
    "Ignoring the duplicate-indexing problem when the same document is ingested repeatedly.",
    "Returning raw chunks from storage without score or source information for prompt assembly.",
  ],

  followUps: [
    {
      question: "How would you add Pinecone or pgvector?",
      answerMD:
        "Create a new **VectorStore** implementation. It maps **Chunk** plus embedding into backend records and maps search results back into **VectorStore.SearchResult**.",
    },
    {
      question: "How do you support multiple embedding models at once?",
      answerMD:
        "Keep model identity in index configuration or chunk metadata, and route both indexing and query embedding through a named **EmbeddingProvider**. Never compare vectors from different dimensions or models.",
    },
    {
      question: "Where should token budgeting live?",
      answerMD:
        "In prompt assembly or a dedicated **ContextPackingStage** after retrieval. It can trim chunks by score, recency, or source priority before generation.",
    },
    {
      question: "How would you make ingestion asynchronous?",
      answerMD:
        "Split the chain after document validation: publish chunking and embedding jobs to a queue, then keep online query answering as retrieval plus prompt plus generation.",
    },
    {
      question: "How do you prevent unauthorized chunks from entering the answer?",
      answerMD:
        "Carry ACL metadata on documents and chunks, filter before or during vector search, and verify again before prompt assembly as a defense-in-depth stage.",
    },
  ],

  productionConsiderations: [
    {
      label: "Idempotent indexing",
      detailMD:
        "Use stable chunk ids based on document id, version, and chunk index. Upsert should replace old chunks for the same version and delete stale chunks for superseded versions.",
    },
    {
      label: "Observability",
      detailMD:
        "Track chunk counts, embedding latency, store upsert latency, retrieval hit scores, prompt token count, generator latency, and grounded-answer feedback.",
    },
    {
      label: "Failure handling",
      detailMD:
        "Retry transient embedding and vector-store failures with backoff. Persist ingestion state so a failed document can resume without duplicating chunks.",
    },
    {
      label: "Security and privacy",
      detailMD:
        "Encrypt stored vectors and source text, avoid sending restricted data to unauthorized providers, and enforce metadata filters before prompt assembly.",
    },
    {
      label: "Evaluation",
      detailMD:
        "Maintain golden queries with expected source chunks. Measure retrieval recall, answer grounding, latency, and cost after provider or store swaps.",
    },
  ],

  interviewNotes: [
    "Did you separate ingestion, chunking, embedding, indexing, retrieval, prompt assembly, and generation responsibilities?",
    "Can the candidate swap embedding providers and vector stores without editing **Retriever** or **RagPipeline**?",
    "Is the Chain of Responsibility useful, or did it become ceremony around a simple method?",
    "Are immutable **Document** and **Chunk** values used to avoid hidden state changes between stages?",
    "Did the answer mention production concerns such as idempotent indexing, metadata filters, latency, evaluation, and provider failures?",
  ],

  quiz: [
    {
      question: "Why is **EmbeddingProvider** an interface?",
      options: [
        "So the pipeline can swap local, Azure, OpenAI, or other providers without changing stage logic",
        "So vectors no longer need dimensions",
        "So the vector store can skip similarity search",
        "So prompt assembly can run before retrieval",
      ],
      answerIndex: 0,
      explanationMD:
        "Embedding choice is a volatile external dependency. The interface keeps that volatility out of the pipeline and retriever.",
    },
    {
      question: "Which component should know how to call Pinecone or pgvector?",
      options: [
        "RagPipeline",
        "Retriever",
        "A concrete **VectorStore** implementation",
        "ChunkingStrategy",
      ],
      answerIndex: 2,
      explanationMD:
        "Backend details belong behind **VectorStore**. The retriever should only ask for similarity search.",
    },
    {
      question: "What does Chain of Responsibility buy in this design?",
      options: [
        "It makes embeddings mathematically better",
        "It lets stages be added or reordered without one giant orchestration method",
        "It guarantees zero latency",
        "It removes the need for a vector store",
      ],
      answerIndex: 1,
      explanationMD:
        "The chain isolates each transformation and forwarding step, making additions such as reranking or filtering localized.",
    },
    {
      question: "Where should prompt token budgeting most naturally live?",
      options: [
        "Inside **Document**",
        "Inside **Chunk.withEmbedding**",
        "In prompt assembly or a dedicated context-packing stage",
        "Inside the embedding adapter",
      ],
      answerIndex: 2,
      explanationMD:
        "Token budgeting is about selecting and formatting retrieved context for the model, not ingestion or embedding.",
    },
    {
      question: "Why should chunks be immutable?",
      options: [
        "To make chunking impossible",
        "To prevent stages from observing partially mutated indexing state",
        "To avoid using arrays",
        "To make vector search O(1)",
      ],
      answerIndex: 1,
      explanationMD:
        "Immutable chunks make stage handoff reliable. Attaching an embedding returns a new value with defensive copies.",
    },
  ],

  practiceVariants: [
    {
      title: "Add a reranking stage",
      detailMD:
        "Insert a stage after retrieval that reranks top 20 vector hits down to top 5 with a cross-encoder strategy.",
      difficulty: "Advanced",
    },
    {
      title: "Add metadata-aware retrieval",
      detailMD:
        "Extend **VectorStore.similaritySearch** to accept filters for tenant, document type, ACL, and freshness while keeping **Retriever** small.",
      difficulty: "Expert",
    },
    {
      title: "Support streaming generation",
      detailMD:
        "Change **Generator** to emit tokens through an observer or callback while preserving the same retrieval and prompt assembly stages.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "What are the core stages in an LLD RAG pipeline?",
      back: "Ingest documents, chunk, embed, index, retrieve, assemble prompt, and generate.",
    },
    {
      front: "Which pattern makes chunking swappable?",
      back: "Strategy — **ChunkingStrategy** can be fixed-size, sentence-aware, markdown-aware, or semantic.",
    },
    {
      front: "Which pattern wires pipeline stages?",
      back: "Chain of Responsibility — each stage handles the context and forwards to the next stage.",
    },
    {
      front: "Where do vendor embedding SDKs belong?",
      back: "Behind an Adapter that implements **EmbeddingProvider**.",
    },
    {
      front: "What is the vector-store seam?",
      back: "**VectorStore** with **upsert** and **similaritySearch**, implemented by memory, pgvector, Pinecone, Elasticsearch, or another backend.",
    },
    {
      front: "Why separate **Retriever** from **RagPipeline**?",
      back: "Retriever owns query embedding plus nearest-neighbor lookup; RagPipeline owns stage orchestration.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Document, Chunk, ChunkingStrategy, EmbeddingProvider, VectorStore, Retriever, RagPipeline.",
    "",
    "**Flow:** validate documents → chunk → embed chunks → upsert vectors → embed query → similarity search → assemble prompt → generate answer.",
    "",
    "**Patterns:** Strategy for chunking and providers; Adapter for vendor embedding clients; Factory Method for default implementations; Chain of Responsibility for stages.",
    "",
    "**Key seams:** embedding provider, vector store, retriever top K, prompt assembler, generator, optional reranker.",
    "",
    "**Invariants:** chunks retain document lineage; embeddings match the configured model dimension; vector store only indexes embedded chunks; prompt assembly uses retrieved context.",
    "",
    "**Production checks:** idempotent indexing, ACL filters, provider retries, token budgets, retrieval evaluation, observability, and data privacy.",
  ].join("\n"),

  references: [
    {
      title: "Designing Data-Intensive Applications",
      kind: "Book",
      author: "Martin Kleppmann",
    },
    {
      title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
      kind: "Paper",
      author: "Lewis et al.",
      url: "https://arxiv.org/abs/2005.11401",
    },
    {
      title: "OpenAI Embeddings Guide",
      kind: "Docs",
      url: "https://platform.openai.com/docs/guides/embeddings",
    },
    {
      title: "Pinecone Vector Database Concepts",
      kind: "Docs",
      url: "https://docs.pinecone.io/guides/get-started/concepts",
    },
  ],

  relatedProblems: [
    { slug: "ai-chat-platform", note: "RAG commonly powers grounded chat responses and tool-augmented assistants." },
    { slug: "api-gateway", note: "Provider routing, adapters, and cross-cutting stages mirror gateway design concerns." },
    { slug: "message-queue", note: "Asynchronous ingestion and embedding jobs are natural queue-based extensions." },
  ],
};
