import type { LLDProblemContent } from "../types";

export const rbacSystem: LLDProblemContent = {
  slug: "rbac-system",

  statementMD: [
    "Design a **Role-Based Access Control system** that decides whether a user may perform an action on a resource.",
    "The model must support users, roles, permissions, resource/action checks, and role hierarchy where one role inherits permissions from other roles.",
    "",
    "The core interview challenge is to keep authorization checks fast while still making role composition easy to reason about. A good design resolves inherited permissions once, caches them per user, and answers hot-path checks with hash-set membership rather than walking the hierarchy on every request.",
  ].join("\n"),

  businessContextMD: [
    "RBAC sits in the critical path of admin consoles, enterprise SaaS products, developer platforms, and internal tools. A slow or inconsistent check either blocks legitimate work or exposes protected data.",
    "",
    "Interviewers use this problem to test whether you can separate identity from authorization, model hierarchical roles without cycles, apply Composite cleanly, and explain the tradeoff between flexible policy evaluation and O(1)-ish runtime checks.",
  ].join("\n"),

  functionalRequirements: [
    "Create and store users with stable ids.",
    "Create roles with direct permissions such as read invoice or delete project.",
    "Allow a role to inherit permissions from one or more other roles through a composite hierarchy.",
    "Grant roles to users and derive the user's effective permission set from all assigned roles.",
    "Represent protected resources by type, id, and owner so checks can be expressed as action on resource.",
    "Authorize a request by user id, resource, and action.",
    "Support wildcard permissions such as all actions on invoices or a platform-wide super-user permission.",
    "Invalidate cached user permissions when roles, role inheritance, or grants change.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Low-latency authorization",
      detailMD:
        "The read path should be close to O(1): compute a Permission key from resource type and action, then check a cached hash set.",
    },
    {
      label: "Hierarchy safety",
      detailMD:
        "Composite roles must reject cycles. A role inheriting itself, directly or indirectly, would make permission resolution ambiguous and unsafe.",
    },
    {
      label: "Auditability",
      detailMD:
        "Every authorization decision should be observable at the boundary without putting logging concerns into the core engine.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New permission matching rules, owner-based rules, or deny policies should be additive through a strategy rather than a rewrite of every role and user class.",
    },
    {
      label: "Deterministic behavior",
      detailMD:
        "Given the same users, roles, permissions, and resources, the engine should return the same answer regardless of traversal order.",
    },
  ],

  requirementClarification: [
    {
      question: "Are permissions attached directly to users?",
      answerMD:
        "No for the base design. Users receive roles, and roles carry permissions. Direct user permissions can be added later, but keeping the base model role-centric makes auditing simpler.",
    },
    {
      question: "Does a child role inherit from a parent role or the other way around?",
      answerMD:
        "Use the phrasing **Admin inherits Editor**. Admin's effective permission set includes Admin's direct permissions plus Editor's effective permissions.",
    },
    {
      question: "Do we need allow and deny decisions?",
      answerMD:
        "Start with allow-only RBAC. Deny policies are an extension because they change conflict resolution and require explicit precedence rules.",
    },
    {
      question: "What counts as O(1)-ish permission checking?",
      answerMD:
        "The hot check should avoid hierarchy traversal. It may perform a constant number of hash-set lookups for exact and wildcard candidates.",
    },
    {
      question: "Is this an authentication system too?",
      answerMD:
        "No. Authentication proves who the caller is. This design assumes a trusted user id and answers what that user may do.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class User {",
    "        -String id",
    "        -String name",
    "        -Set~Role~ roles",
    "        +assignRole(Role) void",
    "        +roles() Set",
    "    }",
    "    class Role {",
    "        -String id",
    "        -String name",
    "        -Set~Permission~ permissions",
    "        -Set~Role~ inheritedRoles",
    "        +addPermission(Permission) Role",
    "        +inherit(Role) Role",
    "        +effectivePermissions() Set",
    "    }",
    "    class Permission {",
    "        -String resourceType",
    "        -String action",
    "        +of(String, String) Permission",
    "        +anyAction(String) Permission",
    "        +superUser() Permission",
    "    }",
    "    class Resource {",
    "        -String type",
    "        -String id",
    "        -String ownerUserId",
    "        +of(String, String, String) Resource",
    "    }",
    "    class PermissionStrategy {",
    "        <<interface>>",
    "        +isAllowed(Set, Resource, String) boolean",
    "    }",
    "    class ExactAndWildcardPermissionStrategy",
    "    class AccessControlService {",
    "        -Map~String,User~ users",
    "        -Map~String,Role~ roles",
    "        -Map userPermissionCache",
    "        -PermissionStrategy permissionStrategy",
    "        +getInstance() AccessControlService",
    "        +grantRoleToUser(String, String) void",
    "        +isAllowed(String, Resource, String) boolean",
    "    }",
    "    class AuthorizationProxy {",
    "        -AccessControlService delegate",
    "        +can(String, Resource, String) boolean",
    "    }",
    "    User o-- Role",
    "    Role o-- Permission",
    "    Role o-- Role : inherits",
    "    AccessControlService o-- User",
    "    AccessControlService o-- Role",
    "    AccessControlService ..> PermissionStrategy",
    "    PermissionStrategy <|.. ExactAndWildcardPermissionStrategy",
    "    AuthorizationProxy --> AccessControlService",
    "    AccessControlService ..> Resource",
  ].join("\n"),
  classDiagramCaptionMD:
    "Role is the Composite: a role contains permissions and other roles. AccessControlService owns the registry and cache, while PermissionStrategy decides how resource/action pairs map to membership checks.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Caller",
    "    participant Proxy as AuthorizationProxy",
    "    participant ACL as AccessControlService",
    "    participant Cache as UserPermissionCache",
    "    participant Role as RoleComposite",
    "    participant Strat as PermissionStrategy",
    "    Caller->>Proxy: can(userId, resource, action)",
    "    Proxy->>ACL: isAllowed(userId, resource, action)",
    "    ACL->>Cache: get(userId)",
    "    alt cache miss",
    "        ACL->>Role: effectivePermissions() for assigned roles",
    "        Role-->>ACL: flattened permission set",
    "        ACL->>Cache: put(userId, permissions)",
    "    end",
    "    ACL->>Strat: isAllowed(permissions, resource, action)",
    "    Strat-->>ACL: allow or deny",
    "    ACL-->>Proxy: decision",
    "    Proxy-->>Caller: audited decision",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The expensive part is flattening role inheritance, and it happens only on cache miss or after invalidation. The common decision path is a fixed set of hash lookups.",

  entities: [
    {
      name: "User",
      responsibilityMD:
        "Represents the subject being authorized. It stores identity fields and assigned roles, but does not decide access by itself.",
      attributes: ["id", "name", "roles"],
    },
    {
      name: "Role",
      responsibilityMD:
        "Composite permission container. A role owns direct permissions and can inherit other roles, so effective permissions are the union across a role graph.",
      attributes: ["id", "name", "permissions", "inheritedRoles"],
    },
    {
      name: "Permission",
      responsibilityMD:
        "Immutable value object for **resourceType + action**. Equality and hashing make permission checks hash-set based.",
      attributes: ["resourceType", "action"],
    },
    {
      name: "Resource",
      responsibilityMD:
        "Protected object being accessed. The engine uses its type for permission matching and keeps id plus owner for future resource-specific policies.",
      attributes: ["type", "id", "ownerUserId"],
    },
    {
      name: "PermissionStrategy",
      responsibilityMD:
        "Policy seam for evaluating a cached permission set against a resource/action request. The default strategy checks exact and wildcard permissions.",
      attributes: ["isAllowed(permissions, resource, action)"],
    },
    {
      name: "AccessControlService",
      responsibilityMD:
        "Singleton authorization engine. It creates users and roles, grants roles, invalidates caches, and answers authorization decisions.",
      attributes: ["users", "roles", "userPermissionCache", "permissionStrategy"],
    },
    {
      name: "AuthorizationProxy",
      responsibilityMD:
        "Boundary object that validates and audits authorization calls before delegating to the service. It keeps observability separate from core rules.",
      attributes: ["delegate", "can(userId, resource, action)"],
    },
  ],

  patternsUsed: [
    {
      name: "Composite",
      whyMD:
        "**Role** contains direct permissions and inherited roles. Effective permissions are resolved by recursively visiting child roles, which models role hierarchy without special-case code for leaf and composite roles.",
    },
    {
      name: "Strategy",
      whyMD:
        "**PermissionStrategy** isolates the matching algorithm. The default strategy supports exact and wildcard permissions, while future owner-aware or tenant-aware strategies can plug in without changing users or roles.",
    },
    {
      name: "Proxy",
      whyMD:
        "**AuthorizationProxy** wraps the authorization engine to perform request validation and audit logging. It controls access to the service without mixing logging into the permission model.",
    },
    {
      name: "Singleton",
      whyMD:
        "**AccessControlService.getInstance** gives the demo one canonical in-memory registry and cache. In production, the same boundary could be dependency-injected, but the singleton keeps the sample focused.",
    },
  ],

  designSteps: [
    {
      title: "Represent permissions as immutable hash keys",
      detailMD:
        "A permission should be a value object, not a mutable record. Normalize resource type and action so **INVOICE:READ** and **invoice:read** do not become different grants.",
      code: [
        "public final class Permission {",
        "    private final String resourceType;",
        "    private final String action;",
        "",
        "    public static Permission of(String resourceType, String action) {",
        "        return new Permission(resourceType, action);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Model role hierarchy with Composite",
      detailMD:
        "A role is both a permission holder and a container of other roles. Resolving a role means unioning its direct permissions with inherited roles, while cycle checks protect the graph.",
      code: [
        "public Role inherit(Role role) {",
        "    if (role == this || role.dependsOn(this, new HashSet<>())) {",
        "        throw new IllegalArgumentException(\"Role inheritance cycle\");",
        "    }",
        "    inheritedRoles.add(role);",
        "    return this;",
        "}",
      ].join("\n"),
    },
    {
      title: "Cache flattened permissions per user",
      detailMD:
        "Granting a role invalidates only that user's cache. Editing a role invalidates all user caches because many users may depend on that role through inheritance.",
    },
    {
      title: "Use a strategy for resource/action matching",
      detailMD:
        "The engine asks **PermissionStrategy** whether a set allows a request. The default strategy checks exact permission, any action on a resource type, global action, and super-user wildcard.",
      code: [
        "return permissions.contains(Permission.of(resource.type(), action))",
        "        || permissions.contains(Permission.anyAction(resource.type()))",
        "        || permissions.contains(Permission.global(action))",
        "        || permissions.contains(Permission.superUser());",
      ].join("\n"),
    },
    {
      title: "Put audit and validation behind a proxy",
      detailMD:
        "**AuthorizationProxy** measures latency and logs the decision after delegation. This keeps the domain model deterministic and easy to test.",
    },
    {
      title: "Keep the public service API small",
      detailMD:
        "Expose creation, role mutation, grants, and **isAllowed**. Avoid exposing mutable maps or sets; callers should not be able to corrupt the cache or role graph.",
    },
  ],

  implementation: [
    {
      filename: "Permission.java",
      language: "java",
      content: [
        "import java.util.Locale;",
        "import java.util.Objects;",
        "",
        "public final class Permission {",
        "    public static final String ANY = \"*\";",
        "",
        "    private final String resourceType;",
        "    private final String action;",
        "",
        "    private Permission(String resourceType, String action) {",
        "        this.resourceType = normalize(resourceType, \"resourceType\");",
        "        this.action = normalize(action, \"action\");",
        "    }",
        "",
        "    public static Permission of(String resourceType, String action) {",
        "        return new Permission(resourceType, action);",
        "    }",
        "",
        "    public static Permission anyAction(String resourceType) {",
        "        return new Permission(resourceType, ANY);",
        "    }",
        "",
        "    public static Permission global(String action) {",
        "        return new Permission(ANY, action);",
        "    }",
        "",
        "    public static Permission superUser() {",
        "        return new Permission(ANY, ANY);",
        "    }",
        "",
        "    public String resourceType() {",
        "        return resourceType;",
        "    }",
        "",
        "    public String action() {",
        "        return action;",
        "    }",
        "",
        "    private static String normalize(String value, String field) {",
        "        String trimmed = Objects.requireNonNull(value, field).trim();",
        "        if (trimmed.isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" must not be blank\");",
        "        }",
        "        if (ANY.equals(trimmed)) {",
        "            return ANY;",
        "        }",
        "        return trimmed.toLowerCase(Locale.ROOT);",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof Permission)) {",
        "            return false;",
        "        }",
        "        Permission that = (Permission) other;",
        "        return resourceType.equals(that.resourceType) && action.equals(that.action);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return Objects.hash(resourceType, action);",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return resourceType + \":\" + action;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Resource.java",
      language: "java",
      content: [
        "import java.util.Locale;",
        "import java.util.Objects;",
        "",
        "public final class Resource {",
        "    private final String type;",
        "    private final String id;",
        "    private final String ownerUserId;",
        "",
        "    private Resource(String type, String id, String ownerUserId) {",
        "        this.type = requireText(type, \"type\").toLowerCase(Locale.ROOT);",
        "        this.id = requireText(id, \"id\");",
        "        this.ownerUserId = requireText(ownerUserId, \"ownerUserId\");",
        "    }",
        "",
        "    public static Resource of(String type, String id, String ownerUserId) {",
        "        return new Resource(type, id, ownerUserId);",
        "    }",
        "",
        "    public String type() {",
        "        return type;",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String ownerUserId() {",
        "        return ownerUserId;",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        String trimmed = Objects.requireNonNull(value, field).trim();",
        "        if (trimmed.isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" must not be blank\");",
        "        }",
        "        return trimmed;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return type + \":\" + id;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Role.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.HashSet;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public final class Role {",
        "    private final String id;",
        "    private final String name;",
        "    private final Set<Permission> permissions = new HashSet<>();",
        "    private final Set<Role> inheritedRoles = new HashSet<>();",
        "",
        "    public Role(String id, String name) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String name() {",
        "        return name;",
        "    }",
        "",
        "    public Role addPermission(Permission permission) {",
        "        permissions.add(Objects.requireNonNull(permission, \"permission\"));",
        "        return this;",
        "    }",
        "",
        "    public Role inherit(Role role) {",
        "        Objects.requireNonNull(role, \"role\");",
        "        if (role == this || role.dependsOn(this, new HashSet<>())) {",
        "            throw new IllegalArgumentException(\"Role inheritance cycle involving \" + id);",
        "        }",
        "        inheritedRoles.add(role);",
        "        return this;",
        "    }",
        "",
        "    public Set<Permission> effectivePermissions() {",
        "        Set<Permission> result = new HashSet<>();",
        "        collectEffectivePermissions(result, new HashSet<>());",
        "        return Collections.unmodifiableSet(result);",
        "    }",
        "",
        "    private void collectEffectivePermissions(Set<Permission> result, Set<Role> visited) {",
        "        if (!visited.add(this)) {",
        "            return;",
        "        }",
        "        result.addAll(permissions);",
        "        for (Role inheritedRole : inheritedRoles) {",
        "            inheritedRole.collectEffectivePermissions(result, visited);",
        "        }",
        "    }",
        "",
        "    private boolean dependsOn(Role target, Set<Role> visited) {",
        "        if (!visited.add(this)) {",
        "            return false;",
        "        }",
        "        if (inheritedRoles.contains(target)) {",
        "            return true;",
        "        }",
        "        for (Role inheritedRole : inheritedRoles) {",
        "            if (inheritedRole.dependsOn(target, visited)) {",
        "                return true;",
        "            }",
        "        }",
        "        return false;",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        String trimmed = Objects.requireNonNull(value, field).trim();",
        "        if (trimmed.isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" must not be blank\");",
        "        }",
        "        return trimmed;",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof Role)) {",
        "            return false;",
        "        }",
        "        Role role = (Role) other;",
        "        return id.equals(role.id);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return id.hashCode();",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return name + \"(\" + id + \")\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "User.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.HashSet;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public final class User {",
        "    private final String id;",
        "    private final String name;",
        "    private final Set<Role> roles = new HashSet<>();",
        "",
        "    public User(String id, String name) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String name() {",
        "        return name;",
        "    }",
        "",
        "    void assignRole(Role role) {",
        "        roles.add(Objects.requireNonNull(role, \"role\"));",
        "    }",
        "",
        "    public Set<Role> roles() {",
        "        return Collections.unmodifiableSet(roles);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        String trimmed = Objects.requireNonNull(value, field).trim();",
        "        if (trimmed.isEmpty()) {",
        "            throw new IllegalArgumentException(field + \" must not be blank\");",
        "        }",
        "        return trimmed;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return name + \"(\" + id + \")\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "PermissionStrategy.java",
      language: "java",
      content: [
        "import java.util.Set;",
        "",
        "public interface PermissionStrategy {",
        "    boolean isAllowed(Set<Permission> permissions, Resource resource, String action);",
        "}",
        "",
        "final class ExactAndWildcardPermissionStrategy implements PermissionStrategy {",
        "    @Override",
        "    public boolean isAllowed(Set<Permission> permissions, Resource resource, String action) {",
        "        return permissions.contains(Permission.of(resource.type(), action))",
        "                || permissions.contains(Permission.anyAction(resource.type()))",
        "                || permissions.contains(Permission.global(action))",
        "                || permissions.contains(Permission.superUser());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "AccessControlService.java",
      language: "java",
      content: [
        "import java.util.Collections;",
        "import java.util.HashMap;",
        "import java.util.HashSet;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public final class AccessControlService {",
        "    private static final AccessControlService INSTANCE =",
        "            new AccessControlService(new ExactAndWildcardPermissionStrategy());",
        "",
        "    private final Map<String, User> users = new HashMap<>();",
        "    private final Map<String, Role> roles = new HashMap<>();",
        "    private final Map<String, Set<Permission>> userPermissionCache = new HashMap<>();",
        "    private final PermissionStrategy permissionStrategy;",
        "",
        "    private AccessControlService(PermissionStrategy permissionStrategy) {",
        "        this.permissionStrategy = Objects.requireNonNull(permissionStrategy, \"permissionStrategy\");",
        "    }",
        "",
        "    public static AccessControlService getInstance() {",
        "        return INSTANCE;",
        "    }",
        "",
        "    public synchronized User createUser(String id, String name) {",
        "        if (users.containsKey(id)) {",
        "            throw new IllegalArgumentException(\"Duplicate user \" + id);",
        "        }",
        "        User user = new User(id, name);",
        "        users.put(user.id(), user);",
        "        return user;",
        "    }",
        "",
        "    public synchronized Role createRole(String id, String name) {",
        "        if (roles.containsKey(id)) {",
        "            throw new IllegalArgumentException(\"Duplicate role \" + id);",
        "        }",
        "        Role role = new Role(id, name);",
        "        roles.put(role.id(), role);",
        "        return role;",
        "    }",
        "",
        "    public synchronized void addPermissionToRole(String roleId, Permission permission) {",
        "        requireRole(roleId).addPermission(permission);",
        "        invalidateAllUserCaches();",
        "    }",
        "",
        "    public synchronized void makeRoleInherit(String roleId, String inheritedRoleId) {",
        "        Role role = requireRole(roleId);",
        "        Role inheritedRole = requireRole(inheritedRoleId);",
        "        role.inherit(inheritedRole);",
        "        invalidateAllUserCaches();",
        "    }",
        "",
        "    public synchronized void grantRoleToUser(String userId, String roleId) {",
        "        User user = requireUser(userId);",
        "        Role role = requireRole(roleId);",
        "        user.assignRole(role);",
        "        userPermissionCache.remove(userId);",
        "    }",
        "",
        "    public synchronized boolean isAllowed(String userId, Resource resource, String action) {",
        "        Objects.requireNonNull(resource, \"resource\");",
        "        User user = requireUser(userId);",
        "        Set<Permission> permissions = permissionsFor(user);",
        "        return permissionStrategy.isAllowed(permissions, resource, action);",
        "    }",
        "",
        "    private Set<Permission> permissionsFor(User user) {",
        "        return userPermissionCache.computeIfAbsent(user.id(), id -> {",
        "            Set<Permission> effective = new HashSet<>();",
        "            for (Role role : user.roles()) {",
        "                effective.addAll(role.effectivePermissions());",
        "            }",
        "            return Collections.unmodifiableSet(effective);",
        "        });",
        "    }",
        "",
        "    private User requireUser(String userId) {",
        "        User user = users.get(userId);",
        "        if (user == null) {",
        "            throw new IllegalArgumentException(\"Unknown user \" + userId);",
        "        }",
        "        return user;",
        "    }",
        "",
        "    private Role requireRole(String roleId) {",
        "        Role role = roles.get(roleId);",
        "        if (role == null) {",
        "            throw new IllegalArgumentException(\"Unknown role \" + roleId);",
        "        }",
        "        return role;",
        "    }",
        "",
        "    private void invalidateAllUserCaches() {",
        "        userPermissionCache.clear();",
        "    }",
        "}",
        "",
        "final class AuthorizationProxy {",
        "    private final AccessControlService delegate;",
        "",
        "    AuthorizationProxy(AccessControlService delegate) {",
        "        this.delegate = Objects.requireNonNull(delegate, \"delegate\");",
        "    }",
        "",
        "    public boolean can(String userId, Resource resource, String action) {",
        "        long startedNanos = System.nanoTime();",
        "        boolean allowed = delegate.isAllowed(userId, resource, action);",
        "        long elapsedMicros = (System.nanoTime() - startedNanos) / 1_000;",
        "        System.out.println(\"authz user=\" + userId",
        "                + \" resource=\" + resource",
        "                + \" action=\" + action",
        "                + \" decision=\" + (allowed ? \"ALLOW\" : \"DENY\")",
        "                + \" latencyMicros=\" + elapsedMicros);",
        "        return allowed;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        AccessControlService acl = AccessControlService.getInstance();",
        "",
        "        acl.createUser(\"u-alice\", \"Alice\");",
        "        acl.createUser(\"u-bob\", \"Bob\");",
        "",
        "        acl.createRole(\"invoice-reader\", \"Invoice Reader\");",
        "        acl.createRole(\"invoice-editor\", \"Invoice Editor\");",
        "        acl.createRole(\"invoice-admin\", \"Invoice Admin\");",
        "",
        "        acl.addPermissionToRole(\"invoice-reader\", Permission.of(\"invoice\", \"read\"));",
        "        acl.addPermissionToRole(\"invoice-editor\", Permission.of(\"invoice\", \"write\"));",
        "        acl.makeRoleInherit(\"invoice-editor\", \"invoice-reader\");",
        "        acl.addPermissionToRole(\"invoice-admin\", Permission.anyAction(\"invoice\"));",
        "        acl.makeRoleInherit(\"invoice-admin\", \"invoice-editor\");",
        "",
        "        acl.grantRoleToUser(\"u-alice\", \"invoice-admin\");",
        "        acl.grantRoleToUser(\"u-bob\", \"invoice-reader\");",
        "",
        "        Resource invoice = Resource.of(\"invoice\", \"inv-100\", \"u-alice\");",
        "        AuthorizationProxy authorizer = new AuthorizationProxy(acl);",
        "",
        "        System.out.println(\"Alice can delete invoice: \"",
        "                + authorizer.can(\"u-alice\", invoice, \"delete\"));",
        "        System.out.println(\"Bob can write invoice: \"",
        "                + authorizer.can(\"u-bob\", invoice, \"write\"));",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Permission",
      detailMD:
        "Immutable value object for authorization keys. It normalizes resource type and action, supports exact grants and wildcard grants, and implements equality/hashCode so hash-set checks are constant time on average.",
    },
    {
      className: "Resource",
      detailMD:
        "Small descriptor for the protected object. The base strategy uses **type** for permission lookup, while **id** and **ownerUserId** leave room for instance-level and owner-aware policies.",
    },
    {
      className: "Role",
      detailMD:
        "Composite node in the role hierarchy. It stores direct permissions and inherited roles, rejects inheritance cycles, and resolves effective permissions by unioning the reachable role graph.",
    },
    {
      className: "User",
      detailMD:
        "Subject being authorized. It owns a set of assigned roles and exposes only an immutable view so callers cannot bypass the service cache invalidation rules.",
    },
    {
      className: "PermissionStrategy",
      detailMD:
        "Strategy interface for checking whether a permission set allows a resource/action request. It keeps matching rules outside User and Role.",
    },
    {
      className: "ExactAndWildcardPermissionStrategy",
      detailMD:
        "Default strategy implementation. It performs four hash-set probes: exact resource/action, any action on the resource type, global action, and super-user.",
    },
    {
      className: "AccessControlService",
      detailMD:
        "Singleton registry, cache owner, and authorization engine. It owns user and role maps, mutates role definitions through cache-safe methods, and evaluates checks through the strategy.",
    },
    {
      className: "AuthorizationProxy",
      detailMD:
        "Audited boundary around the service. It delegates the decision, measures latency, and logs the result without adding cross-cutting concerns to the domain model.",
    },
    {
      className: "Main",
      detailMD:
        "Demonstrates role inheritance: editor inherits reader, admin inherits editor and has wildcard invoice access, then Alice and Bob receive different effective permissions.",
    },
  ],

  dryRun: {
    inputMD:
      "Roles: Reader has invoice:read, Editor inherits Reader and adds invoice:write, Admin inherits Editor and adds invoice:*. Alice has Admin, Bob has Reader. Resource is invoice inv-100.",
    columns: ["Step", "Request", "Cache state", "Permission candidates", "Decision", "Reason"],
    rows: [
      [
        "1",
        "Alice delete invoice",
        "Miss then cache {invoice:read, invoice:write, invoice:*}",
        "invoice:delete, invoice:*, *:delete, *:*",
        "Allow",
        "invoice:* is present through Admin",
      ],
      [
        "2",
        "Bob write invoice",
        "Miss then cache {invoice:read}",
        "invoice:write, invoice:*, *:write, *:*",
        "Deny",
        "No candidate permission is present",
      ],
      [
        "3",
        "Alice read invoice",
        "Hit",
        "invoice:read, invoice:*, *:read, *:*",
        "Allow",
        "Exact read and wildcard invoice permission are both present",
      ],
      [
        "4",
        "Add export to Reader",
        "All user caches cleared",
        "No check yet",
        "N/A",
        "Role mutation can affect many users, so cached sets are invalidated",
      ],
      [
        "5",
        "Bob export invoice",
        "Miss then cache {invoice:read, invoice:export}",
        "invoice:export, invoice:*, *:export, *:*",
        "Allow",
        "New Reader permission is included after recomputation",
      ],
    ],
    narrativeMD:
      "The first request pays the hierarchy-resolution cost. Later checks for the same user are a fixed number of hash lookups until grants or role definitions change.",
  },

  complexity: [
    {
      operation: "isAllowed with warm user cache",
      time: "O(1)",
      space: "O(1)",
      note: "The default strategy performs four hash-set contains checks.",
    },
    {
      operation: "isAllowed with cold user cache",
      time: "O(R + E + P)",
      space: "O(P)",
      note: "R assigned/reachable roles, E inheritance edges visited, P unique permissions flattened into the user cache.",
    },
    {
      operation: "grantRoleToUser",
      time: "O(1)",
      space: "O(1)",
      note: "Adds a role reference and clears only that user's cached effective permissions.",
    },
    {
      operation: "addPermissionToRole or makeRoleInherit",
      time: "O(1) to O(E)",
      space: "O(1)",
      note: "Adding a permission is constant; inheritance checks may traverse role edges to prevent cycles, then all user caches are cleared.",
    },
    {
      operation: "effectivePermissions for a role",
      time: "O(E + P)",
      space: "O(R + P)",
      note: "DFS over inherited roles plus a set of accumulated permissions.",
    },
  ],
  complexityNotesMD:
    "The design intentionally moves work from the read path to mutation/cache-miss paths. That is usually the right RBAC tradeoff because authorization checks happen far more often than role definition changes.",

  extensibility: [
    {
      label: "Instance-level permissions",
      detailMD:
        "Extend **Permission** with an optional resource id or scope field, then update **PermissionStrategy** to check exact instance keys before type-level keys.",
    },
    {
      label: "Owner-aware access",
      detailMD:
        "Add a strategy that allows actions such as read own invoice when **resource.ownerUserId** matches the current user id. The service API may pass the user into the strategy.",
    },
    {
      label: "Explicit deny policies",
      detailMD:
        "Introduce separate allow and deny sets and define precedence clearly, usually deny wins. This belongs in a new strategy because it changes decision semantics.",
    },
    {
      label: "Persistent repositories",
      detailMD:
        "Replace in-memory maps with UserRepository, RoleRepository, and PermissionRepository while keeping the AccessControlService boundary intact.",
    },
    {
      label: "Multi-tenant authorization",
      detailMD:
        "Add tenant id to User, Role, Resource, and cache keys so one tenant's Admin role cannot authorize another tenant's resources.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Evaluate role graph on every request",
      detailMD:
        "Skip user permission caching and traverse assigned roles plus inherited roles for every authorization check.",
      tradeoffsMD:
        "Simpler invalidation, but hot checks become O(R + E + P) and latency grows with hierarchy depth.",
    },
    {
      name: "Persist a flattened user-permission table",
      detailMD:
        "Materialize user id to permission rows in a database and update them asynchronously or transactionally whenever grants and roles change.",
      tradeoffsMD:
        "Excellent read latency and cross-process consistency, but role mutations become more expensive and require careful rebuild jobs.",
    },
    {
      name: "Policy engine instead of pure RBAC",
      detailMD:
        "Use a rule language or attribute-based access control engine where permissions depend on user, resource, environment, and relationship attributes.",
      tradeoffsMD:
        "More expressive than RBAC, but harder to explain, cache, audit, and test in a short LLD interview.",
    },
  ],

  commonMistakes: [
    "Walking the entire role hierarchy on every authorization request and then claiming the check is O(1).",
    "Allowing role inheritance cycles, which can cause infinite recursion or inconsistent permission sets.",
    "Mixing authentication and authorization so login state leaks into the RBAC model.",
    "Putting audit logging inside **Role** or **Permission**, making the domain model hard to test.",
    "Returning mutable internal sets from users or roles, letting callers bypass cache invalidation.",
    "Using string comparisons everywhere instead of a normalized **Permission** value object.",
    "Forgetting that role definition changes must invalidate users who inherit that role indirectly.",
  ],

  followUps: [
    {
      question: "How do you make authorization checks O(1)?",
      answerMD:
        "Flatten inherited role permissions into a cached set per user. A check then creates a small number of candidate Permission keys and uses hash-set membership.",
    },
    {
      question: "How do you prevent cycles in role hierarchy?",
      answerMD:
        "When adding **A inherits B**, search from B to see whether A is already reachable. If yes, reject the edge because it would create a cycle.",
    },
    {
      question: "What changes when explicit deny is introduced?",
      answerMD:
        "You need conflict resolution. Most systems make deny override allow, so the strategy must check deny candidates first and document precedence.",
    },
    {
      question: "How would this work across multiple application instances?",
      answerMD:
        "Persist roles and grants, publish invalidation events on changes, and use versioned cache entries so every instance refreshes stale user permission sets.",
    },
    {
      question: "Why use a proxy instead of logging inside AccessControlService?",
      answerMD:
        "The proxy keeps cross-cutting concerns at the boundary. The service remains focused on authorization state and decisions, making it easier to unit test.",
    },
  ],

  productionConsiderations: [
    {
      label: "Cache invalidation",
      detailMD:
        "Use role version numbers or authorization policy versions in cache keys. On role changes, publish events so every service instance evicts affected users.",
    },
    {
      label: "Audit logs",
      detailMD:
        "Record user id, resource type, resource id, action, decision, policy version, and latency. Avoid logging sensitive resource payloads.",
    },
    {
      label: "Least privilege",
      detailMD:
        "Prefer narrowly scoped roles, periodic access reviews, and break-glass roles with extra approval. RBAC designs fail when every user becomes Admin.",
    },
    {
      label: "Tenant isolation",
      detailMD:
        "Include tenant id in every role, resource, and cache key. Treat cross-tenant role grants as invalid by default.",
    },
    {
      label: "Operational safety",
      detailMD:
        "Make permission changes observable and reversible. Keep a history of who changed a role and which users gained or lost permissions.",
    },
  ],

  interviewNotes: [
    "Did the candidate separate User, Role, Permission, Resource, and authorization engine responsibilities?",
    "Did they model role hierarchy with a clear Composite and cycle prevention?",
    "Did they explain why cached flattened permissions make hot checks O(1)-ish?",
    "Did they provide an invalidation story for grants and role mutations?",
    "Did they keep policy matching behind a Strategy instead of spreading if statements across the model?",
    "Did they recognize audit logging as a boundary concern suitable for a Proxy?",
  ],

  quiz: [
    {
      question: "Why is **Role** a good use of the Composite pattern in this design?",
      options: [
        "A role can contain permissions and inherited roles, and both contribute to one effective permission set",
        "A role must be created through a factory method",
        "A role stores users directly to make lookup faster",
        "A role logs every authorization decision",
      ],
      answerIndex: 0,
      explanationMD:
        "Composite fits because a role is both a permission holder and a container of other roles whose permissions are included.",
    },
    {
      question: "What makes the warm authorization path O(1)-ish?",
      options: [
        "The service scans every inherited role on each request",
        "The user has a cached hash set of effective permissions and the strategy performs a fixed number of contains checks",
        "The resource id is ignored entirely",
        "The singleton removes all synchronization costs",
      ],
      answerIndex: 1,
      explanationMD:
        "Once flattened permissions are cached, the default strategy checks exact and wildcard keys with constant-count hash lookups.",
    },
    {
      question: "What should happen when a role gains a new permission?",
      options: [
        "Nothing because cached permissions update themselves",
        "Only users directly assigned to that role should be deleted",
        "Affected user permission caches must be invalidated or recomputed",
        "All resources should be renamed",
      ],
      answerIndex: 2,
      explanationMD:
        "Role changes can affect users indirectly through inheritance, so stale effective-permission caches must be cleared or versioned.",
    },
    {
      question: "Why is **PermissionStrategy** useful?",
      options: [
        "It lets the system switch matching rules without changing User or Role",
        "It makes role cycle detection unnecessary",
        "It stores all users in a sorted list",
        "It replaces the need for permissions",
      ],
      answerIndex: 0,
      explanationMD:
        "Strategy isolates policy matching, so exact, wildcard, owner-aware, and deny-aware rules can evolve independently.",
    },
    {
      question: "Which edge should be rejected to prevent a cycle?",
      options: [
        "Admin inherits Editor when Editor already inherits Reader",
        "Reader gets invoice:read",
        "Reader inherits Admin when Admin already inherits Reader",
        "Alice receives Reader",
      ],
      answerIndex: 2,
      explanationMD:
        "If Admin already reaches Reader, making Reader inherit Admin creates a cycle and must be rejected.",
    },
  ],

  practiceVariants: [
    {
      title: "Add explicit deny rules",
      detailMD:
        "Introduce deny permissions and define precedence. Update the strategy so deny candidates are checked before allow candidates.",
      difficulty: "Advanced",
    },
    {
      title: "Add resource ownership checks",
      detailMD:
        "Support permissions like read own invoice by passing the user into the strategy and comparing it with **resource.ownerUserId**.",
      difficulty: "Intermediate",
    },
    {
      title: "Add tenant isolation",
      detailMD:
        "Require every role and resource to belong to a tenant, and ensure the cache key includes tenant id.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the core RBAC authorization question?",
      back: "Can this user perform this action on this resource, based on roles and permissions?",
    },
    {
      front: "How does role inheritance work here?",
      back: "A composite role includes its direct permissions plus all permissions from inherited roles.",
    },
    {
      front: "What makes permission checks fast after warm-up?",
      back: "A cached user set of effective Permission objects and constant-count hash-set membership checks.",
    },
    {
      front: "Which pattern isolates permission matching?",
      back: "Strategy, through **PermissionStrategy** and the default exact plus wildcard implementation.",
    },
    {
      front: "What does the Proxy do?",
      back: "It wraps AccessControlService to validate and audit authorization decisions without polluting domain classes.",
    },
    {
      front: "What must be invalidated when a role changes?",
      back: "User effective-permission caches, because users may inherit that role directly or indirectly.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** User, Role, Permission, Resource, PermissionStrategy, AccessControlService, AuthorizationProxy.",
    "",
    "**Role hierarchy:** Admin inherits Editor; Editor inherits Reader. Effective permissions are the union of all reachable roles.",
    "",
    "**Patterns:** Composite for Role inheritance, Strategy for permission matching, Proxy for audited access, Singleton for the demo service registry.",
    "",
    "**Hot path:** user id + resource + action → cached user permission set → exact and wildcard Permission candidates → hash-set contains.",
    "",
    "**Invalidation:** grant changes clear one user cache; role permission and hierarchy changes clear or version affected user caches.",
    "",
    "**Complexity:** warm check O(1), cold check O(R + E + P), role mutation includes cycle detection and cache invalidation.",
    "",
    "**Extensions:** explicit deny, resource ownership, instance-level permissions, tenant isolation, persistent repositories.",
  ].join("\n"),

  references: [
    {
      title: "NIST RBAC Model",
      kind: "Paper",
      url: "https://csrc.nist.gov/projects/role-based-access-control",
      author: "NIST",
    },
    {
      title: "Enterprise Integration Patterns — Proxy and Gateway Concepts",
      kind: "Book",
      author: "Gregor Hohpe and Bobby Woolf",
    },
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, and Vlissides",
    },
    {
      title: "OWASP Authorization Cheat Sheet",
      kind: "Docs",
      url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html",
      author: "OWASP",
    },
  ],

  relatedProblems: [
    {
      slug: "authentication-service",
      note: "Authentication establishes identity before RBAC decides authorization.",
    },
    {
      slug: "api-gateway",
      note: "Gateways often call an authorization engine before forwarding protected requests.",
    },
    {
      slug: "feature-flag-service",
      note: "Both systems evaluate user context against configured rules and benefit from cached decisions.",
    },
  ],
};
