import type { LLDProblemContent } from "../types";

export const shoppingCart: LLDProblemContent = {
  slug: "shopping-cart",

  statementMD: [
    "Design a **shopping cart** for an e-commerce application. Customers can add",
    "products, change quantities, apply a coupon or discount policy, and checkout",
    "to produce an immutable order with subtotal, discount, tax, and final total.",
    "",
    "The important design decision is separation of concerns: the cart owns item",
    "selection and quantity state, while **CheckoutService** owns price calculation.",
    "Discounts are pluggable strategies so a new coupon rule is additive rather",
    "than another conditional inside the cart.",
  ].join("\n"),

  businessContextMD: [
    "Shopping Cart appears frequently in Amazon, Flipkart, Adobe, and marketplace",
    "interviews because it looks familiar but quickly exposes design quality.",
    "Candidates must model money safely, keep cart mutation independent from",
    "pricing, support coupon variation, and create a checkout boundary that can",
    "later integrate payments, inventory reservation, tax engines, and order",
    "fulfillment.",
    "",
    "A strong solution treats the cart as a domain aggregate, not a calculator.",
    "Pricing becomes a separate service composed with Strategy, making promotions",
    "testable and replaceable without risking item-management logic.",
  ].join("\n"),

  functionalRequirements: [
    "Represent products with id, name, unit price, and tax category.",
    "Add a product to the cart with a positive quantity.",
    "Merge repeated additions of the same product by increasing the line-item quantity.",
    "Update or remove a product line by product id.",
    "Expose a read-only snapshot of current cart line items.",
    "Apply a coupon or discount policy to the cart without changing cart item state.",
    "Calculate subtotal, discount, tax, and grand total during checkout.",
    "Produce an immutable order containing the purchased items and pricing breakdown.",
    "Notify interested observers when the cart changes.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Pricing correctness",
      detailMD:
        "Use precise decimal money arithmetic and round only at clear money boundaries, never with floating-point doubles.",
    },
    {
      label: "Separation of concerns",
      detailMD:
        "**Cart** manages selection and quantities; **CheckoutService** computes totals; discount policies live behind **DiscountStrategy**.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New coupons, tax plans, cart observers, and checkout integrations should be added as classes, not by editing a giant checkout conditional.",
    },
    {
      label: "Concurrency awareness",
      detailMD:
        "Cart mutations and checkout snapshots must be atomic enough that an order is priced from one consistent item view.",
    },
    {
      label: "Auditability",
      detailMD:
        "Checkout should capture subtotal, discount, tax, total, timestamp, and item snapshot so later price changes do not rewrite historical orders.",
    },
  ],

  requirementClarification: [
    {
      question: "Can a product appear multiple times in the cart?",
      answerMD:
        "No duplicate lines in the base design. The cart stores one **CartItem** per product id and increments quantity on repeated add.",
    },
    {
      question: "Can multiple coupons stack?",
      answerMD:
        "Base design applies one active **DiscountStrategy**. Stacking can be added by a composite discount strategy or a promotion engine extension.",
    },
    {
      question: "Do we reserve inventory during add-to-cart?",
      answerMD:
        "No. Cart is customer intent, not inventory reservation. Inventory reservation belongs at checkout or payment authorization time.",
    },
    {
      question: "Is tax per product category or a flat rate?",
      answerMD:
        "Use a flat percentage tax in the reference implementation to keep focus on LLD seams. Product tax category is retained for future category-aware tax strategies.",
    },
    {
      question: "Should checkout clear the cart?",
      answerMD:
        "The base implementation returns an **Order** and leaves clearing as an application decision. Production systems usually clear after payment succeeds, not merely after price calculation.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Product {",
    "        -String id",
    "        -String name",
    "        -BigDecimal unitPrice",
    "        -String taxCategory",
    "        +of(String,String,String,String) Product",
    "    }",
    "    class CartItem {",
    "        -Product product",
    "        -int quantity",
    "        +withQuantity(int) CartItem",
    "        +lineSubtotal() BigDecimal",
    "    }",
    "    class Cart {",
    "        -Map~String,CartItem~ items",
    "        -List~CartObserver~ observers",
    "        -DiscountStrategy discountStrategy",
    "        +addProduct(Product,int) void",
    "        +updateQuantity(String,int) void",
    "        +removeProduct(String) void",
    "        +applyDiscount(DiscountStrategy) void",
    "        +items() List~CartItem~",
    "    }",
    "    class DiscountStrategy {",
    "        <<interface>>",
    "        +apply(Cart,BigDecimal) BigDecimal",
    "        +description() String",
    "    }",
    "    class NoDiscountStrategy",
    "    class PercentageDiscountStrategy",
    "    class FixedAmountCouponStrategy",
    "    class CartObserver {",
    "        <<interface>>",
    "        +onCartChanged(Cart,String) void",
    "    }",
    "    class LoggingCartObserver",
    "    class CheckoutService {",
    "        -BigDecimal taxRatePercent",
    "        +checkout(Cart) Order",
    "    }",
    "    class Order {",
    "        -String id",
    "        -List~CartItem~ items",
    "        -BigDecimal subtotal",
    "        -BigDecimal discount",
    "        -BigDecimal tax",
    "        -BigDecimal total",
    "        -Instant createdAt",
    "    }",
    "    Cart o-- CartItem",
    "    CartItem --> Product",
    "    Cart ..> DiscountStrategy",
    "    DiscountStrategy <|.. NoDiscountStrategy",
    "    DiscountStrategy <|.. PercentageDiscountStrategy",
    "    DiscountStrategy <|.. FixedAmountCouponStrategy",
    "    Cart o-- CartObserver",
    "    CartObserver <|.. LoggingCartObserver",
    "    CheckoutService ..> Cart",
    "    CheckoutService ..> DiscountStrategy",
    "    CheckoutService --> Order",
    "    Order o-- CartItem",
  ].join("\n"),
  classDiagramCaptionMD:
    "**Cart** is the composite aggregate of line items. **CheckoutService** depends on **DiscountStrategy** and reads a cart snapshot to calculate prices without owning cart mutation.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Customer",
    "    participant Cart",
    "    participant Observer as CartObserver",
    "    participant Checkout as CheckoutService",
    "    participant Strategy as DiscountStrategy",
    "    participant Order",
    "    Customer->>Cart: addProduct(product, quantity)",
    "    Cart->>Cart: merge or create CartItem",
    "    Cart-->>Observer: onCartChanged",
    "    Customer->>Cart: applyDiscount(couponStrategy)",
    "    Cart-->>Observer: onCartChanged",
    "    Customer->>Checkout: checkout(cart)",
    "    Checkout->>Cart: items and discountStrategy",
    "    Checkout->>Checkout: calculate subtotal",
    "    Checkout->>Strategy: apply(cart, subtotal)",
    "    Strategy-->>Checkout: discount amount",
    "    Checkout->>Checkout: calculate tax and total",
    "    Checkout->>Order: create immutable order",
    "    Checkout-->>Customer: order",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Mutation stays inside **Cart**; pricing happens only when **CheckoutService** asks the active strategy for a discount and then applies tax.",

  entities: [
    {
      name: "Product",
      responsibilityMD:
        "Immutable catalog value used by cart lines. It owns product identity, display name, unit price, and a tax category hook for future tax policies.",
      attributes: ["id", "name", "unitPrice", "taxCategory"],
    },
    {
      name: "CartItem",
      responsibilityMD:
        "Immutable line item combining one **Product** with a positive quantity. It can derive its own line subtotal from product price and quantity.",
      attributes: ["product", "quantity", "lineSubtotal"],
    },
    {
      name: "Cart",
      responsibilityMD:
        "Aggregate root for customer intent. It owns the product-id to **CartItem** map, selected discount strategy, and observer list, but does not finalize totals.",
      attributes: ["items", "discountStrategy", "observers"],
    },
    {
      name: "DiscountStrategy",
      responsibilityMD:
        "Coupon policy seam. Implementations compute discount amount from cart context and subtotal, while checkout clamps the result for safety.",
      attributes: ["apply(cart, subtotal)", "description"],
    },
    {
      name: "CartObserver",
      responsibilityMD:
        "Notification seam for UI badges, analytics, or persistence hooks whenever the cart changes.",
      attributes: ["onCartChanged(cart, event)"],
    },
    {
      name: "CheckoutService",
      responsibilityMD:
        "Pricing boundary. It takes a consistent cart snapshot, sums line items, applies discount strategy, computes tax, and returns an **Order**.",
      attributes: ["taxRatePercent", "checkout(cart)"],
    },
    {
      name: "Order",
      responsibilityMD:
        "Immutable checkout result containing item snapshot and money breakdown. It is safe to persist or send to payment because it no longer depends on mutable cart state.",
      attributes: ["id", "items", "subtotal", "discount", "tax", "total", "createdAt"],
    },
  ],

  patternsUsed: [
    {
      name: "Strategy",
      whyMD:
        "**DiscountStrategy** isolates coupon behavior. Percentage, fixed-amount, no-discount, and future rule-based promotions implement one method while checkout remains unchanged.",
    },
    {
      name: "Composite",
      whyMD:
        "**Cart** acts as the aggregate composite over many **CartItem** leaves. Clients treat the cart as one purchasable selection even though totals come from individual lines.",
    },
    {
      name: "Observer",
      whyMD:
        "**CartObserver** lets UI counters, analytics, and persistence hooks react to item or coupon changes without being coupled to cart mutation methods.",
    },
    {
      name: "Factory Method",
      whyMD:
        "Static factory methods such as **Product.of** and **DiscountStrategy.percentage** create validated domain objects and hide concrete coupon classes from callers.",
    },
  ],

  designSteps: [
    {
      title: "Model products as immutable catalog values",
      detailMD:
        "A product should not change because a customer modifies the cart. Keep identity and unit price immutable, and create products through a validating factory method.",
      code: [
        "public static Product of(String id, String name, String unitPrice, String taxCategory) {",
        "    return new Product(id, name, new BigDecimal(unitPrice), taxCategory);",
        "}",
      ].join("\n"),
    },
    {
      title: "Make cart lines immutable and quantity-based",
      detailMD:
        "**CartItem** represents one product plus quantity. Updating a quantity returns a new line, which avoids accidental mutation leaking through cart snapshots.",
      code: [
        "public CartItem withQuantity(int newQuantity) {",
        "    return new CartItem(product, newQuantity);",
        "}",
        "",
        "public BigDecimal lineSubtotal() {",
        "    return product.getUnitPrice().multiply(BigDecimal.valueOf(quantity));",
        "}",
      ].join("\n"),
    },
    {
      title: "Let the cart own item composition, not checkout math",
      detailMD:
        "**Cart** merges repeated product additions, updates quantities, removes lines, and exposes a safe snapshot. It stores the active discount policy but does not compute final tax or total.",
    },
    {
      title: "Represent coupons as strategies",
      detailMD:
        "Every promotion implements **DiscountStrategy**. Checkout asks the strategy for a discount amount and then normalizes it so no coupon can produce a negative total.",
      code: [
        "public interface DiscountStrategy {",
        "    BigDecimal apply(Cart cart, BigDecimal subtotal);",
        "    String description();",
        "}",
      ].join("\n"),
    },
    {
      title: "Put subtotal, discount, tax, and total in CheckoutService",
      detailMD:
        "The checkout boundary snapshots items, sums line subtotals, invokes the discount strategy, computes tax, and creates the order. This keeps pricing tests focused on one service.",
      code: [
        "BigDecimal subtotal = calculateSubtotal(snapshot);",
        "BigDecimal discount = normalizeDiscount(strategy.apply(cart, subtotal), subtotal);",
        "BigDecimal tax = taxableAmount.multiply(taxRatePercent)",
        "    .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);",
      ].join("\n"),
    },
    {
      title: "Return an immutable order snapshot",
      detailMD:
        "An **Order** stores item copies and the final money breakdown at checkout time. Later product price updates or cart edits must not rewrite the order history.",
    },
  ],

  implementation: [
    {
      filename: "Product.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.math.RoundingMode;",
        "import java.util.Objects;",
        "",
        "public final class Product {",
        "    private final String id;",
        "    private final String name;",
        "    private final BigDecimal unitPrice;",
        "    private final String taxCategory;",
        "",
        "    private Product(String id, String name, BigDecimal unitPrice, String taxCategory) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "        this.unitPrice = money(unitPrice, \"unitPrice\");",
        "        this.taxCategory = requireText(taxCategory, \"taxCategory\");",
        "    }",
        "",
        "    public static Product of(String id, String name, String unitPrice, String taxCategory) {",
        "        return new Product(id, name, new BigDecimal(requireText(unitPrice, \"unitPrice\")), taxCategory);",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public BigDecimal getUnitPrice() {",
        "        return unitPrice;",
        "    }",
        "",
        "    public String getTaxCategory() {",
        "        return taxCategory;",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "",
        "    private static BigDecimal money(BigDecimal value, String fieldName) {",
        "        Objects.requireNonNull(value, fieldName);",
        "        if (value.signum() < 0) {",
        "            throw new IllegalArgumentException(fieldName + \" cannot be negative\");",
        "        }",
        "        return value.setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "CartItem.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.math.RoundingMode;",
        "import java.util.Objects;",
        "",
        "public final class CartItem {",
        "    private final Product product;",
        "    private final int quantity;",
        "",
        "    public CartItem(Product product, int quantity) {",
        "        this.product = Objects.requireNonNull(product, \"product\");",
        "        this.quantity = requirePositive(quantity);",
        "    }",
        "",
        "    public Product getProduct() {",
        "        return product;",
        "    }",
        "",
        "    public int getQuantity() {",
        "        return quantity;",
        "    }",
        "",
        "    public CartItem withQuantity(int newQuantity) {",
        "        return new CartItem(product, newQuantity);",
        "    }",
        "",
        "    public BigDecimal lineSubtotal() {",
        "        return product.getUnitPrice()",
        "                .multiply(BigDecimal.valueOf(quantity))",
        "                .setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    private static int requirePositive(int quantity) {",
        "        if (quantity <= 0) {",
        "            throw new IllegalArgumentException(\"quantity must be positive\");",
        "        }",
        "        return quantity;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "DiscountStrategy.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.math.RoundingMode;",
        "import java.util.Objects;",
        "",
        "public interface DiscountStrategy {",
        "    BigDecimal apply(Cart cart, BigDecimal subtotal);",
        "",
        "    String description();",
        "",
        "    static DiscountStrategy none() {",
        "        return new NoDiscountStrategy();",
        "    }",
        "",
        "    static DiscountStrategy percentage(String code, BigDecimal percent) {",
        "        return new PercentageDiscountStrategy(code, percent);",
        "    }",
        "",
        "    static DiscountStrategy fixedAmount(String code, BigDecimal amount) {",
        "        return new FixedAmountCouponStrategy(code, amount);",
        "    }",
        "}",
        "",
        "final class NoDiscountStrategy implements DiscountStrategy {",
        "    @Override",
        "    public BigDecimal apply(Cart cart, BigDecimal subtotal) {",
        "        Objects.requireNonNull(cart, \"cart\");",
        "        Objects.requireNonNull(subtotal, \"subtotal\");",
        "        return BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    @Override",
        "    public String description() {",
        "        return \"No discount\";",
        "    }",
        "}",
        "",
        "final class PercentageDiscountStrategy implements DiscountStrategy {",
        "    private final String code;",
        "    private final BigDecimal percent;",
        "",
        "    PercentageDiscountStrategy(String code, BigDecimal percent) {",
        "        this.code = requireText(code, \"code\");",
        "        this.percent = requirePercent(percent);",
        "    }",
        "",
        "    @Override",
        "    public BigDecimal apply(Cart cart, BigDecimal subtotal) {",
        "        Objects.requireNonNull(cart, \"cart\");",
        "        Objects.requireNonNull(subtotal, \"subtotal\");",
        "        if (cart.itemCount() == 0) {",
        "            return BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);",
        "        }",
        "        return subtotal.multiply(percent)",
        "                .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    @Override",
        "    public String description() {",
        "        return code + \" \" + percent.stripTrailingZeros().toPlainString() + \"% off\";",
        "    }",
        "",
        "    private static BigDecimal requirePercent(BigDecimal percent) {",
        "        Objects.requireNonNull(percent, \"percent\");",
        "        if (percent.signum() <= 0 || percent.compareTo(BigDecimal.valueOf(100)) > 0) {",
        "            throw new IllegalArgumentException(\"percent must be between 0 and 100\");",
        "        }",
        "        return percent;",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
        "",
        "final class FixedAmountCouponStrategy implements DiscountStrategy {",
        "    private final String code;",
        "    private final BigDecimal amount;",
        "",
        "    FixedAmountCouponStrategy(String code, BigDecimal amount) {",
        "        this.code = requireText(code, \"code\");",
        "        this.amount = requireAmount(amount);",
        "    }",
        "",
        "    @Override",
        "    public BigDecimal apply(Cart cart, BigDecimal subtotal) {",
        "        Objects.requireNonNull(cart, \"cart\");",
        "        Objects.requireNonNull(subtotal, \"subtotal\");",
        "        return amount.min(subtotal).setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    @Override",
        "    public String description() {",
        "        return code + \" \" + amount.toPlainString() + \" off\";",
        "    }",
        "",
        "    private static BigDecimal requireAmount(BigDecimal amount) {",
        "        Objects.requireNonNull(amount, \"amount\");",
        "        if (amount.signum() <= 0) {",
        "            throw new IllegalArgumentException(\"amount must be positive\");",
        "        }",
        "        return amount.setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "CartObserver.java",
      language: "java",
      content: [
        "public interface CartObserver {",
        "    void onCartChanged(Cart cart, String event);",
        "",
        "    static CartObserver logging() {",
        "        return new LoggingCartObserver();",
        "    }",
        "}",
        "",
        "final class LoggingCartObserver implements CartObserver {",
        "    @Override",
        "    public void onCartChanged(Cart cart, String event) {",
        "        System.out.println(\"Cart event \" + event + \", itemCount=\" + cart.itemCount());",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Cart.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class Cart {",
        "    private final Map<String, CartItem> items = new LinkedHashMap<>();",
        "    private final List<CartObserver> observers = new ArrayList<>();",
        "    private DiscountStrategy discountStrategy = DiscountStrategy.none();",
        "",
        "    public synchronized void addObserver(CartObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public synchronized void addProduct(Product product, int quantity) {",
        "        Objects.requireNonNull(product, \"product\");",
        "        requirePositive(quantity);",
        "        CartItem existing = items.get(product.getId());",
        "        int newQuantity = existing == null ? quantity : existing.getQuantity() + quantity;",
        "        items.put(product.getId(), new CartItem(product, newQuantity));",
        "        notifyObservers(\"ITEM_ADDED\");",
        "    }",
        "",
        "    public synchronized void updateQuantity(String productId, int quantity) {",
        "        requireText(productId, \"productId\");",
        "        CartItem existing = items.get(productId);",
        "        if (existing == null) {",
        "            throw new IllegalArgumentException(\"product is not in the cart\");",
        "        }",
        "        if (quantity <= 0) {",
        "            items.remove(productId);",
        "        } else {",
        "            items.put(productId, existing.withQuantity(quantity));",
        "        }",
        "        notifyObservers(\"QUANTITY_CHANGED\");",
        "    }",
        "",
        "    public synchronized void removeProduct(String productId) {",
        "        requireText(productId, \"productId\");",
        "        if (items.remove(productId) != null) {",
        "            notifyObservers(\"ITEM_REMOVED\");",
        "        }",
        "    }",
        "",
        "    public synchronized void applyDiscount(DiscountStrategy strategy) {",
        "        this.discountStrategy = Objects.requireNonNull(strategy, \"strategy\");",
        "        notifyObservers(\"DISCOUNT_CHANGED\");",
        "    }",
        "",
        "    public synchronized List<CartItem> items() {",
        "        return List.copyOf(items.values());",
        "    }",
        "",
        "    public synchronized DiscountStrategy discountStrategy() {",
        "        return discountStrategy;",
        "    }",
        "",
        "    public synchronized int itemCount() {",
        "        int count = 0;",
        "        for (CartItem item : items.values()) {",
        "            count += item.getQuantity();",
        "        }",
        "        return count;",
        "    }",
        "",
        "    private void notifyObservers(String event) {",
        "        for (CartObserver observer : List.copyOf(observers)) {",
        "            observer.onCartChanged(this, event);",
        "        }",
        "    }",
        "",
        "    private static void requirePositive(int quantity) {",
        "        if (quantity <= 0) {",
        "            throw new IllegalArgumentException(\"quantity must be positive\");",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.trim().isEmpty()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "CheckoutService.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "import java.math.RoundingMode;",
        "import java.time.Instant;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "",
        "public final class CheckoutService {",
        "    private final BigDecimal taxRatePercent;",
        "",
        "    public CheckoutService(BigDecimal taxRatePercent) {",
        "        this.taxRatePercent = requireTaxRate(taxRatePercent);",
        "    }",
        "",
        "    public Order checkout(Cart cart) {",
        "        Objects.requireNonNull(cart, \"cart\");",
        "        synchronized (cart) {",
        "            List<CartItem> snapshot = cart.items();",
        "            if (snapshot.isEmpty()) {",
        "                throw new IllegalStateException(\"cannot checkout an empty cart\");",
        "            }",
        "",
        "            BigDecimal subtotal = calculateSubtotal(snapshot);",
        "            DiscountStrategy strategy = cart.discountStrategy();",
        "            BigDecimal discount = normalizeDiscount(strategy.apply(cart, subtotal), subtotal);",
        "            BigDecimal taxableAmount = subtotal.subtract(discount);",
        "            BigDecimal tax = taxableAmount.multiply(taxRatePercent)",
        "                    .divide(BigDecimal.valueOf(100), 2, RoundingMode.HALF_UP);",
        "            BigDecimal total = taxableAmount.add(tax).setScale(2, RoundingMode.HALF_UP);",
        "",
        "            return new Order(UUID.randomUUID().toString(), snapshot, subtotal, discount, tax, total, Instant.now());",
        "        }",
        "    }",
        "",
        "    private BigDecimal calculateSubtotal(List<CartItem> items) {",
        "        BigDecimal subtotal = BigDecimal.ZERO;",
        "        for (CartItem item : items) {",
        "            subtotal = subtotal.add(item.lineSubtotal());",
        "        }",
        "        return subtotal.setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    private BigDecimal normalizeDiscount(BigDecimal discount, BigDecimal subtotal) {",
        "        Objects.requireNonNull(discount, \"discount\");",
        "        if (discount.signum() < 0) {",
        "            throw new IllegalArgumentException(\"discount cannot be negative\");",
        "        }",
        "        return discount.min(subtotal).setScale(2, RoundingMode.HALF_UP);",
        "    }",
        "",
        "    private static BigDecimal requireTaxRate(BigDecimal taxRatePercent) {",
        "        Objects.requireNonNull(taxRatePercent, \"taxRatePercent\");",
        "        if (taxRatePercent.signum() < 0 || taxRatePercent.compareTo(BigDecimal.valueOf(100)) > 0) {",
        "            throw new IllegalArgumentException(\"tax rate must be between 0 and 100\");",
        "        }",
        "        return taxRatePercent;",
        "    }",
        "}",
        "",
        "final class Order {",
        "    private final String id;",
        "    private final List<CartItem> items;",
        "    private final BigDecimal subtotal;",
        "    private final BigDecimal discount;",
        "    private final BigDecimal tax;",
        "    private final BigDecimal total;",
        "    private final Instant createdAt;",
        "",
        "    Order(String id, List<CartItem> items, BigDecimal subtotal, BigDecimal discount, BigDecimal tax, BigDecimal total, Instant createdAt) {",
        "        this.id = Objects.requireNonNull(id, \"id\");",
        "        this.items = List.copyOf(items);",
        "        this.subtotal = Objects.requireNonNull(subtotal, \"subtotal\");",
        "        this.discount = Objects.requireNonNull(discount, \"discount\");",
        "        this.tax = Objects.requireNonNull(tax, \"tax\");",
        "        this.total = Objects.requireNonNull(total, \"total\");",
        "        this.createdAt = Objects.requireNonNull(createdAt, \"createdAt\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public List<CartItem> getItems() {",
        "        return items;",
        "    }",
        "",
        "    public BigDecimal getSubtotal() {",
        "        return subtotal;",
        "    }",
        "",
        "    public BigDecimal getDiscount() {",
        "        return discount;",
        "    }",
        "",
        "    public BigDecimal getTax() {",
        "        return tax;",
        "    }",
        "",
        "    public BigDecimal getTotal() {",
        "        return total;",
        "    }",
        "",
        "    public Instant getCreatedAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return \"Order \" + id + \" total=\" + total;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.math.BigDecimal;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        Product headphones = Product.of(\"SKU-100\", \"Noise-cancelling headphones\", \"100.00\", \"ELECTRONICS\");",
        "        Product mouse = Product.of(\"SKU-200\", \"Wireless mouse\", \"50.00\", \"ELECTRONICS\");",
        "",
        "        Cart cart = new Cart();",
        "        cart.addObserver(CartObserver.logging());",
        "        cart.addProduct(headphones, 2);",
        "        cart.addProduct(mouse, 1);",
        "        cart.applyDiscount(DiscountStrategy.percentage(\"SUMMER10\", new BigDecimal(\"10\")));",
        "",
        "        CheckoutService checkoutService = new CheckoutService(new BigDecimal(\"8\"));",
        "        Order order = checkoutService.checkout(cart);",
        "",
        "        System.out.println(\"Subtotal: \" + order.getSubtotal());",
        "        System.out.println(\"Discount: \" + order.getDiscount());",
        "        System.out.println(\"Tax: \" + order.getTax());",
        "        System.out.println(\"Total: \" + order.getTotal());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Product",
      detailMD:
        "Immutable catalog value with validated id, name, unit price, and tax category. **Product.of** is the factory method used by clients instead of calling a constructor directly.",
    },
    {
      className: "CartItem",
      detailMD:
        "Immutable line item. It combines a **Product** and quantity, validates positive quantity, and computes the line subtotal with precise decimal arithmetic.",
    },
    {
      className: "DiscountStrategy",
      detailMD:
        "Strategy interface for all coupon policies. Its static factory methods hide concrete discount classes and keep client code small.",
    },
    {
      className: "NoDiscountStrategy",
      detailMD:
        "Null-object style strategy that returns a zero discount. It lets the cart always hold a strategy and avoids null checks during checkout.",
    },
    {
      className: "PercentageDiscountStrategy",
      detailMD:
        "Coupon implementation for percentage discounts such as **SUMMER10**. It validates the rate and computes a rounded percentage of subtotal.",
    },
    {
      className: "FixedAmountCouponStrategy",
      detailMD:
        "Coupon implementation for fixed-value discounts. It caps the discount at subtotal so a coupon cannot make the taxable amount negative.",
    },
    {
      className: "CartObserver",
      detailMD:
        "Observer interface for cart change events. UI counters, analytics, and persistence listeners can subscribe without changing cart logic.",
    },
    {
      className: "LoggingCartObserver",
      detailMD:
        "Small observer implementation used by the demo. It prints the event and current item count whenever the cart changes.",
    },
    {
      className: "Cart",
      detailMD:
        "Composite aggregate of **CartItem** objects. It merges adds, updates quantities, removes items, stores the active discount strategy, and emits observer notifications.",
    },
    {
      className: "CheckoutService",
      detailMD:
        "Pricing boundary. It snapshots the cart, calculates subtotal, asks the strategy for a discount, computes tax, and returns an immutable order.",
    },
    {
      className: "Order",
      detailMD:
        "Immutable checkout result with item snapshot and money breakdown. It protects historical order pricing from later cart or product changes.",
    },
    {
      className: "Main",
      detailMD:
        "Runnable demonstration that creates products, mutates the cart, applies a percentage coupon, checks out with tax, and prints the totals.",
    },
  ],

  dryRun: {
    inputMD:
      "Products: headphones at 100.00 and mouse at 50.00. Actions: add headphones x2, add mouse x1, apply **SUMMER10** percentage coupon, checkout with 8% tax.",
    columns: ["Step", "Cart action", "Subtotal", "Discount", "Tax", "Order total"],
    rows: [
      ["1", "Add headphones x2", "200.00", "0.00", "0.00", "Cart updated"],
      ["2", "Add mouse x1", "250.00", "0.00", "0.00", "Cart updated"],
      ["3", "Apply SUMMER10", "250.00", "25.00", "0.00", "Policy selected"],
      ["4", "Checkout with 8% tax", "250.00", "25.00", "18.00", "243.00"],
    ],
    narrativeMD:
      "Checkout prices a single snapshot: subtotal 250.00, discount 25.00, taxable amount 225.00, tax 18.00, and final total 243.00.",
  },

  complexity: [
    {
      operation: "addProduct",
      time: "O(1)",
      space: "O(1)",
      note: "LinkedHashMap lookup by product id, then insert or replace one immutable line item.",
    },
    {
      operation: "updateQuantity / removeProduct",
      time: "O(1)",
      space: "O(1)",
      note: "Product id lookup and one map mutation.",
    },
    {
      operation: "items snapshot",
      time: "O(N)",
      space: "O(N)",
      note: "Copies N line items into an immutable list view.",
    },
    {
      operation: "checkout",
      time: "O(N)",
      space: "O(N)",
      note: "Sums N line items and stores an order snapshot. Simple discount and tax policies are O(1).",
    },
    {
      operation: "notify observers",
      time: "O(M)",
      space: "O(M)",
      note: "Copies and calls M observers for a cart event.",
    },
  ],
  complexityNotesMD:
    "The hot path is checkout over N cart lines. Coupon strategies shown here are constant-time, but a production promotion engine may depend on product categories, customer segments, or external eligibility checks.",

  extensibility: [
    {
      label: "New coupon type",
      detailMD:
        "Add a new **DiscountStrategy** implementation, such as buy-one-get-one, category percentage, loyalty points, or threshold discount.",
    },
    {
      label: "Stacked discounts",
      detailMD:
        "Introduce a composite discount strategy that owns a list of strategies and applies them in a documented order with a maximum cap.",
    },
    {
      label: "Category-based tax",
      detailMD:
        "Replace the flat tax rate with a **TaxStrategy** that reads **Product.taxCategory** and calculates tax per line item.",
    },
    {
      label: "Inventory reservation",
      detailMD:
        "Add an inventory service at checkout so selected quantities are reserved only when the customer commits to purchase.",
    },
    {
      label: "Cart persistence",
      detailMD:
        "Add a repository or event log that stores cart changes per customer while keeping the in-memory cart model unchanged.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Pricing methods directly on Cart",
      detailMD:
        "Put subtotal, discount, tax, and total methods on **Cart** so clients call one object for everything.",
      tradeoffsMD:
        "Simpler for tiny demos but mixes item mutation with pricing rules. Tax, promotions, audit, and payment integration will make **Cart** too large.",
    },
    {
      name: "Promotion engine with rules",
      detailMD:
        "Replace individual discount classes with a rule engine that evaluates eligibility predicates and reward actions.",
      tradeoffsMD:
        "More flexible for large marketplaces, but overkill for an interview base design and harder to reason about than Strategy.",
    },
    {
      name: "Mutable CartItem lines",
      detailMD:
        "Let **CartItem** expose a setter for quantity and mutate the same line object in place.",
      tradeoffsMD:
        "Uses fewer allocations, but snapshots become unsafe because external code could still hold a line reference and mutate it after checkout.",
    },
    {
      name: "Checkout as a Facade over many services",
      detailMD:
        "Model checkout as a larger orchestration layer over tax, payment, inventory, shipping, and order repositories.",
      tradeoffsMD:
        "Closer to production, but it can distract from the core LLD question unless the interviewer explicitly asks for external integrations.",
    },
  ],

  commonMistakes: [
    "Putting discount and tax calculations inside **Cart**, which makes item mutation and pricing policy change for different reasons.",
    "Using double for money and accumulating rounding errors across line items and tax.",
    "Allowing duplicate line items for the same product id, then producing inconsistent quantity updates.",
    "Letting coupon code conditionals grow inside checkout instead of using **DiscountStrategy**.",
    "Returning mutable cart internals so callers can alter items without observer events or validation.",
    "Creating an order that references the live cart instead of an immutable item and price snapshot.",
    "Applying tax before discount without clarifying the business rule.",
  ],

  followUps: [
    {
      question: "How would you support multiple coupons on one cart?",
      answerMD:
        "Create a composite discount strategy that contains ordered child strategies. It applies each child to the remaining subtotal, records the breakdown, and enforces a cap.",
    },
    {
      question: "How would you add category-specific tax?",
      answerMD:
        "Introduce a **TaxStrategy** that calculates tax per **CartItem** using **Product.taxCategory**. **CheckoutService** depends on the interface, similar to discounts.",
    },
    {
      question: "How do you prevent stale prices if the catalog changes after items are added?",
      answerMD:
        "Store a price snapshot on **CartItem** or validate prices during checkout. For orders, always persist the final item prices used at purchase time.",
    },
    {
      question: "Where should payment authorization live?",
      answerMD:
        "Outside this domain model. A payment adapter should consume the produced **Order** or a checkout quote, authorize payment, then persist and confirm the order.",
    },
    {
      question: "What happens if inventory is unavailable at checkout?",
      answerMD:
        "Checkout should call an inventory reservation service before payment capture. If reservation fails, return a recoverable error and keep the cart editable.",
    },
  ],

  productionConsiderations: [
    {
      label: "Money and currency",
      detailMD:
        "Use a money type with currency instead of bare **BigDecimal**. The sample focuses on decimal correctness but omits multi-currency conversion rules.",
    },
    {
      label: "Promotion audit trail",
      detailMD:
        "Record coupon code, strategy name, eligibility result, and discount amount on the order for customer support and finance reconciliation.",
    },
    {
      label: "Concurrency and sessions",
      detailMD:
        "Persist cart state with versioning so two browser tabs cannot overwrite each other silently. Use optimistic locking on cart updates.",
    },
    {
      label: "External tax engines",
      detailMD:
        "Real commerce systems often call external tax services by address, product category, and jurisdiction. Keep that behind a tax strategy or adapter.",
    },
    {
      label: "Observability",
      detailMD:
        "Track coupon usage, checkout failures, abandoned carts, tax-service latency, and average order value to detect business and reliability issues.",
    },
  ],

  interviewNotes: [
    "Did the candidate keep **Cart** focused on items and quantity state?",
    "Is discount behavior represented by Strategy rather than coupon conditionals?",
    "Are money values precise and rounded intentionally?",
    "Does checkout produce an immutable order snapshot rather than referencing live cart state?",
    "Can the design extend to tax engines, inventory reservation, and payment without rewriting core cart logic?",
    "Does the candidate name tradeoffs around coupon stacking and price snapshots?",
  ],

  quiz: [
    {
      question: "Why should **CheckoutService** calculate totals instead of **Cart**?",
      options: [
        "It keeps cart mutation separate from pricing policy and tax rules",
        "It makes adding products faster than O(1)",
        "It removes the need for line items",
        "It prevents orders from needing ids",
      ],
      answerIndex: 0,
      explanationMD:
        "The cart changes for item-selection reasons; checkout changes for pricing, tax, and order creation reasons. Splitting them keeps each class cohesive.",
    },
    {
      question: "Which pattern best fits coupons like 10% off or 50.00 off?",
      options: [
        "Observer",
        "Strategy",
        "Composite",
        "Prototype",
      ],
      answerIndex: 1,
      explanationMD:
        "Each coupon is an interchangeable algorithm that computes discount amount from the same checkout context.",
    },
    {
      question: "What does **Cart** model in the Composite pattern?",
      options: [
        "A single product price",
        "A collection aggregate made of many **CartItem** leaves",
        "A payment gateway response",
        "A database transaction",
      ],
      answerIndex: 1,
      explanationMD:
        "Clients treat the cart as one purchasable selection, while internally it is composed from line items.",
    },
    {
      question: "Why does **Order** copy the item list?",
      options: [
        "To make checkout O(1)",
        "To avoid needing tax",
        "To preserve the purchased snapshot even if the cart changes later",
        "To make coupons mutable",
      ],
      answerIndex: 2,
      explanationMD:
        "An order is history. It must not depend on a live cart object that the customer can still edit.",
    },
    {
      question: "What is the role of **CartObserver**?",
      options: [
        "It calculates tax for each product category",
        "It lets listeners react to cart changes without coupling to cart methods",
        "It stores all orders in the repository",
        "It converts a product to a coupon",
      ],
      answerIndex: 1,
      explanationMD:
        "Observer is useful for UI counts, analytics, or persistence hooks that react to cart changes without changing cart logic.",
    },
  ],

  practiceVariants: [
    {
      title: "Add category coupons",
      detailMD:
        "Implement a **DiscountStrategy** that gives 15% off only for products in a specified tax or catalog category.",
      difficulty: "Intermediate",
    },
    {
      title: "Stack discounts safely",
      detailMD:
        "Build a composite discount strategy that applies multiple coupons in order and returns a detailed discount breakdown.",
      difficulty: "Advanced",
    },
    {
      title: "Reserve inventory at checkout",
      detailMD:
        "Add an inventory reservation collaborator to **CheckoutService** so checkout fails gracefully when requested quantity is unavailable.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "What does **Cart** own?",
      back: "The product-id to **CartItem** map, active discount strategy, and cart observers. It owns selection state, not final pricing.",
    },
    {
      front: "Which class computes tax and total?",
      back: "**CheckoutService** computes subtotal, discount, tax, and total from a consistent cart snapshot.",
    },
    {
      front: "Which pattern makes coupons pluggable?",
      back: "Strategy — **DiscountStrategy** lets each coupon implement discount calculation independently.",
    },
    {
      front: "Why is **Order** immutable?",
      back: "It preserves purchased items and prices after checkout, even if the cart or catalog changes later.",
    },
    {
      front: "Where does Observer fit?",
      back: "**CartObserver** receives cart change events for UI, analytics, or persistence hooks.",
    },
    {
      front: "How do you add coupon stacking?",
      back: "Use a composite discount strategy that applies child strategies in order and caps the final discount.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Product, CartItem, Cart, DiscountStrategy, CartObserver, CheckoutService, Order.",
    "",
    "**Patterns:** Strategy for discounts, Composite for cart lines, Observer for cart events, Factory Method for validated object creation.",
    "",
    "**Flow:** add/update/remove items in Cart → apply a DiscountStrategy → CheckoutService snapshots items → subtotal → discount → tax → immutable Order.",
    "",
    "**Boundaries:** Cart owns item state. CheckoutService owns pricing. Order owns history.",
    "",
    "**Invariants:** one line per product id; positive quantities; non-negative money; discount never exceeds subtotal; order never references mutable cart state.",
    "",
    "**Complexity:** cart mutations O(1), checkout O(N), observer notification O(M).",
    "",
    "**Extend:** new coupon = new strategy; tax rules = tax strategy; stacked coupons = composite strategy; inventory/payment = checkout collaborators.",
  ].join("\n"),

  references: [
    {
      title: "Head First Design Patterns (Strategy and Observer)",
      kind: "Book",
      author: "Freeman & Robson",
    },
    {
      title: "Effective Java — Static factories and BigDecimal guidance",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — Strategy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/strategy",
    },
  ],

  relatedProblems: [
    { slug: "inventory-management", note: "Checkout usually reserves stock before payment capture." },
    { slug: "digital-wallet", note: "A natural payment extension once an order total is produced." },
    { slug: "parking-lot", note: "Another aggregate design where Strategy keeps pricing separate from state mutation." },
  ],
};
