import type { LLDProblemContent } from "../types";

const joinLines = (lines: string[]) => lines.join("\n");

export const slack: LLDProblemContent = {
  slug: "slack",

  statementMD: joinLines([
    "Design the object model for **Slack** from an LLD and OOD viewpoint. A workspace owns users, channels, and messages; channels may be public, private, or direct messages; users can post root messages, reply in threads, mention teammates, and receive notifications based on their preferences.",
    "",
    "The focus is the in-memory domain model and interaction boundaries: membership rules, message routing, threaded conversations, and notification fan-out. Storage, search indexing, file uploads, reactions, and external integrations are production extensions rather than the core interview surface.",
  ]),

  businessContextMD: joinLines([
    "Slack is a strong expert-level LLD problem because it combines collaboration, access control, nested content, and event delivery in one familiar product. Interviewers use it to see whether a candidate can separate a **Workspace** aggregate from **Channel** membership, keep message routing inside a mediator, and model notifications without scattering conditionals through the posting flow.",
    "",
    "A good answer emphasizes that public channels, private channels, and direct messages share most behavior but differ in discovery and membership rules. Threads should be represented as a message tree, and notification preferences should be pluggable so product rules evolve without changing channel posting code.",
  ]),

  functionalRequirements: [
    "Support multiple workspaces, each with its own users and channels.",
    "Support public channels that any workspace member may join.",
    "Support private channels that require invitation before membership.",
    "Support direct messages between exactly two users.",
    "Allow a channel member to post a root message with zero or more mentioned users.",
    "Allow a channel member to reply to any message in the same channel thread.",
    "Route messages only to users who are members of the target channel.",
    "Notify members according to preferences such as all messages, mentions plus DMs, or mute.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Membership correctness",
      detailMD:
        "A user who is not in a channel must not post, read through the channel object, or receive channel notifications. The invariant belongs to **Channel**, not to the caller.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New channel types, notification preferences, and delivery targets should be additive. The posting flow should not grow a switch for every product feature.",
    },
    {
      label: "Low latency fan-out",
      detailMD:
        "Posting should do bounded in-memory work proportional to channel members and mentions. Expensive delivery, persistence, and indexing can later move behind queues.",
    },
    {
      label: "Thread integrity",
      detailMD:
        "Replies must attach only to messages that already belong to the same channel. A thread should be traversable without a separate thread service in the base design.",
    },
    {
      label: "Clear ownership",
      detailMD:
        "Workspace owns users and channels; Channel owns membership and root messages; Message owns its replies. This keeps lifecycle decisions local.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need to model organizations with multiple workspaces?",
      answerMD:
        "No. Treat **Workspace** as the top-level aggregate. Enterprise grid, shared channels, and cross-workspace identity are production extensions.",
    },
    {
      question: "Can anyone join a public channel?",
      answerMD:
        "Any user already in the workspace can join a public channel. Private channels and direct messages are restricted by their channel type.",
    },
    {
      question: "Are threads separate entities or part of messages?",
      answerMD:
        "For the base design, a **Message** can contain replies, making a thread a message tree. This cleanly demonstrates the Composite pattern.",
    },
    {
      question: "Should notifications be sent to the author?",
      answerMD:
        "No. The author sees their own message immediately, so the notification service skips the author and evaluates preferences for the other members.",
    },
    {
      question: "Do mentions override mute?",
      answerMD:
        "Not in the base policy. A muted strategy returns false for every message. A product-specific urgent mention strategy can be added later.",
    },
  ],

  classDiagramMermaid: joinLines([
    "classDiagram",
    "    class Workspace {",
    "        -String id",
    "        -Map~String,User~ users",
    "        -Map~String,Channel~ channels",
    "        -NotificationService notificationService",
    "        +addUser(String,String) User",
    "        +createPublicChannel(String,String) PublicChannel",
    "        +createPrivateChannel(String,String,User) PrivateChannel",
    "        +openDirectMessage(String,User,User) DirectMessage",
    "        +postMessage(String,String,String,Set~String~) Message",
    "    }",
    "    class Channel {",
    "        <<abstract>>",
    "        -String id",
    "        -String name",
    "        -Set~User~ members",
    "        -List~Message~ messages",
    "        +addMember(User) void",
    "        +post(String,User,String,Set~User~) Message",
    "        +reply(String,User,Message,String,Set~User~) Message",
    "        +isDirectMessage() boolean",
    "    }",
    "    class PublicChannel",
    "    class PrivateChannel {",
    "        -Set~User~ invited",
    "        +invite(User) void",
    "    }",
    "    class DirectMessage {",
    "        -User first",
    "        -User second",
    "    }",
    "    class Message {",
    "        -String id",
    "        -User author",
    "        -String text",
    "        -Message parent",
    "        -List~Message~ replies",
    "        -Set~User~ mentions",
    "        +reply(String,User,String,Set~User~) Message",
    "        +threadSummary() String",
    "    }",
    "    class User {",
    "        -String id",
    "        -String displayName",
    "        -Map~String,NotificationPreference~ preferences",
    "        +setPreference(String,NotificationPreference) void",
    "        +receiveNotification(Notification) void",
    "    }",
    "    class NotificationService {",
    "        -List~User~ observers",
    "        +register(User) void",
    "        +notify(Channel,Message) void",
    "    }",
    "    class NotificationPreference {",
    "        <<interface>>",
    "        +shouldNotify(User,Channel,Message) boolean",
    "    }",
    "    class AllMessagesPreference",
    "    class MentionAndDirectMessagePreference",
    "    class MutedPreference",
    "    Workspace o-- Channel",
    "    Workspace o-- User",
    "    Workspace ..> NotificationService",
    "    Channel o-- Message",
    "    Channel o-- User",
    "    Channel ..> NotificationService",
    "    Channel <|-- PublicChannel",
    "    Channel <|-- PrivateChannel",
    "    PrivateChannel <|-- DirectMessage",
    "    Message o-- Message",
    "    Message --> User",
    "    NotificationService ..> NotificationPreference",
    "    NotificationPreference <|.. AllMessagesPreference",
    "    NotificationPreference <|.. MentionAndDirectMessagePreference",
    "    NotificationPreference <|.. MutedPreference",
  ]),
  classDiagramCaptionMD:
    "Workspace is the aggregate root, Channel is the mediator for membership and posting, Message is a composite tree for threads, and NotificationPreference is the strategy seam used by the observer service.",

  sequenceDiagramMermaid: joinLines([
    "sequenceDiagram",
    "    actor Alice",
    "    participant Workspace",
    "    participant Channel",
    "    participant Message",
    "    participant Notify as NotificationService",
    "    participant Bob",
    "    Alice->>Workspace: postMessage(channelId, aliceId, text, mentions)",
    "    Workspace->>Workspace: resolve channel, author, mentioned users",
    "    Workspace->>Channel: post(messageId, Alice, text, mentions)",
    "    Channel->>Channel: verify Alice is a member",
    "    Channel->>Message: create root message",
    "    Channel->>Notify: notify(channel, message)",
    "    Notify->>Notify: iterate observers who are channel members",
    "    Notify->>Bob: receiveNotification when preference allows",
    "    Channel-->>Workspace: Message",
    "    Workspace-->>Alice: Message",
    "    Alice->>Workspace: reply(channelId, aliceId, parentMessage, replyText)",
    "    Workspace->>Channel: reply(replyId, Alice, parent, replyText, mentions)",
    "    Channel->>Message: parent.reply(replyId, Alice, replyText, mentions)",
    "    Channel->>Notify: notify(channel, reply)",
  ]),
  sequenceDiagramCaptionMD:
    "Posting is mediated twice: Workspace resolves ids and owns the catalog, while Channel enforces membership, creates messages, attaches replies, and triggers observers.",

  entities: [
    {
      name: "Workspace",
      responsibilityMD:
        "Top-level aggregate for one Slack workspace. Owns registered users, channels, id generation for messages, and convenience methods that resolve ids before delegating to channels.",
      attributes: ["id", "name", "users", "channels", "notificationService", "nextMessageNumber"],
    },
    {
      name: "Channel",
      responsibilityMD:
        "Abstract mediator for channel conversations. Owns members and root messages, validates posting access, attaches replies only inside the same channel, and notifies observers after a message is accepted.",
      attributes: ["id", "name", "members", "messages", "notificationService"],
    },
    {
      name: "PublicChannel",
      responsibilityMD:
        "Concrete channel that is discoverable and joinable by any workspace user. It changes discovery and membership policy without duplicating posting behavior.",
      attributes: ["allowsDiscovery", "isDirectMessage"],
    },
    {
      name: "PrivateChannel",
      responsibilityMD:
        "Concrete channel that requires invitation before membership. It keeps the invited set local to the private channel policy.",
      attributes: ["invited", "invite(user)"],
    },
    {
      name: "DirectMessage",
      responsibilityMD:
        "Specialized private channel between exactly two users. It reuses private-channel posting and notification behavior while enforcing the two-member invariant.",
      attributes: ["first", "second", "isDirectMessage"],
    },
    {
      name: "Message",
      responsibilityMD:
        "Immutable message payload plus mutable child replies. A root message and all nested replies form one thread tree using the Composite pattern.",
      attributes: ["id", "author", "text", "createdAt", "parent", "replies", "mentions"],
    },
    {
      name: "User",
      responsibilityMD:
        "Workspace participant with channel memberships and per-channel notification preferences. Receives notifications from the observer service.",
      attributes: ["id", "displayName", "channels", "preferences"],
    },
    {
      name: "NotificationService",
      responsibilityMD:
        "Observer hub. Maintains subscribed users, filters them by channel membership and author exclusion, then delegates the final decision to each user's notification strategy.",
      attributes: ["observers", "register", "notify"],
    },
    {
      name: "NotificationPreference",
      responsibilityMD:
        "Strategy interface for notification rules. All messages, mentions plus DMs, and muted preferences implement the same method.",
      attributes: ["shouldNotify(recipient, channel, message)"],
    },
  ],

  patternsUsed: [
    {
      name: "Mediator",
      whyMD:
        "**Workspace** and **Channel** coordinate interactions so users do not send messages directly to one another. Workspace resolves ids and channel type, while Channel enforces membership and routes accepted messages to observers.",
    },
    {
      name: "Observer",
      whyMD:
        "**NotificationService** keeps observers and is notified after channel state changes. Users receive notifications without **Channel** knowing delivery devices, push gateways, or email adapters.",
    },
    {
      name: "Strategy",
      whyMD:
        "**NotificationPreference** lets each user choose all messages, mentions plus DMs, or mute. Notification rules change by swapping strategies, not editing the posting flow.",
    },
    {
      name: "Composite",
      whyMD:
        "**Message** owns child replies, so a thread is a tree of messages. Root messages and replies can be traversed with the same recursive behavior.",
    },
  ],

  designSteps: [
    {
      title: "Start with the workspace boundary",
      detailMD:
        "Make **Workspace** the aggregate root for users and channels. It should resolve ids, create channel types, and then delegate posting to the selected **Channel** rather than owning channel-specific rules.",
    },
    {
      title: "Use channels as the message mediator",
      detailMD:
        "All posting flows enter **Channel.post** or **Channel.reply**. The channel checks membership before creating a message, which prevents callers from bypassing access control.",
      code: joinLines([
        "public Message post(String messageId, User author, String text, Set<User> mentions) {",
        "    ensureCanPost(author);",
        "    Message message = new Message(messageId, author, text, mentions, null);",
        "    messages.add(message);",
        "    notificationService.notify(this, message);",
        "    return message;",
        "}",
      ]),
    },
    {
      title: "Separate public, private, and DM membership policy",
      detailMD:
        "Put shared behavior in abstract **Channel** and keep only the policy differences in **PublicChannel**, **PrivateChannel**, and **DirectMessage**. This avoids duplicate posting and notification code.",
      code: joinLines([
        "class PrivateChannel extends Channel {",
        "    private final Set<User> invited = new HashSet<>();",
        "",
        "    public void invite(User user) {",
        "        invited.add(user);",
        "        super.addMember(user);",
        "    }",
        "",
        "    protected boolean canJoin(User user) {",
        "        return invited.contains(user);",
        "    }",
        "}",
      ]),
    },
    {
      title: "Model threads as a message tree",
      detailMD:
        "A reply is another **Message** attached under a parent message. This keeps the thread close to the data it organizes and lets rendering traverse recursively.",
      code: joinLines([
        "public Message reply(String replyId, User replier, String text, Set<User> mentions) {",
        "    Message reply = new Message(replyId, replier, text, mentions, this);",
        "    replies.add(reply);",
        "    return reply;",
        "}",
      ]),
    },
    {
      title: "Notify through observers and strategies",
      detailMD:
        "After a channel accepts a message, it calls **NotificationService**. The service filters candidates to channel members, skips the author, and then asks each recipient's **NotificationPreference** whether to deliver.",
      code: joinLines([
        "if (channel.hasMember(recipient)",
        "        && !recipient.equals(message.author())",
        "        && recipient.preferenceFor(channel).shouldNotify(recipient, channel, message)) {",
        "    recipient.receiveNotification(notification);",
        "}",
      ]),
    },
    {
      title: "Keep production concerns behind seams",
      detailMD:
        "Persistence, push providers, unread counters, search indexing, and audit logs should subscribe to the same accepted-message event later. The base model stays focused on correctness and extensibility.",
    },
  ],

  implementation: [
    {
      filename: "User.java",
      language: "java",
      content: joinLines([
        "import java.util.HashMap;",
        "import java.util.HashSet;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public class User {",
        "    private final String id;",
        "    private final String displayName;",
        "    private final Set<Channel> channels = new HashSet<>();",
        "    private final Map<String, NotificationPreference> preferences = new HashMap<>();",
        "",
        "    public User(String id, String displayName) {",
        "        if (id == null || id.isBlank()) {",
        "            throw new IllegalArgumentException(\"id required\");",
        "        }",
        "        if (displayName == null || displayName.isBlank()) {",
        "            throw new IllegalArgumentException(\"display name required\");",
        "        }",
        "        this.id = id;",
        "        this.displayName = displayName;",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String displayName() {",
        "        return displayName;",
        "    }",
        "",
        "    void join(Channel channel) {",
        "        channels.add(Objects.requireNonNull(channel));",
        "    }",
        "",
        "    void leave(Channel channel) {",
        "        channels.remove(channel);",
        "    }",
        "",
        "    public boolean isMemberOf(Channel channel) {",
        "        return channels.contains(channel);",
        "    }",
        "",
        "    public void setPreference(String channelId, NotificationPreference preference) {",
        "        preferences.put(Objects.requireNonNull(channelId), Objects.requireNonNull(preference));",
        "    }",
        "",
        "    NotificationPreference preferenceFor(Channel channel) {",
        "        return preferences.getOrDefault(channel.id(), NotificationPreference.mentionsAndDirectMessages());",
        "    }",
        "",
        "    public void receiveNotification(Notification notification) {",
        "        System.out.println(displayName + \" <- \" + notification.text());",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof User)) {",
        "            return false;",
        "        }",
        "        User user = (User) other;",
        "        return id.equals(user.id);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return id.hashCode();",
        "    }",
        "}",
      ]),
    },
    {
      filename: "Message.java",
      language: "java",
      content: joinLines([
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.HashSet;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public class Message {",
        "    private final String id;",
        "    private final User author;",
        "    private final String text;",
        "    private final Instant createdAt;",
        "    private final Message parent;",
        "    private final List<Message> replies = new ArrayList<>();",
        "    private final Set<User> mentions = new HashSet<>();",
        "",
        "    public Message(String id, User author, String text, Set<User> mentions, Message parent) {",
        "        if (id == null || id.isBlank()) {",
        "            throw new IllegalArgumentException(\"message id required\");",
        "        }",
        "        this.id = id;",
        "        this.author = Objects.requireNonNull(author);",
        "        this.text = Objects.requireNonNull(text);",
        "        this.createdAt = Instant.now();",
        "        this.parent = parent;",
        "        if (mentions != null) {",
        "            this.mentions.addAll(mentions);",
        "        }",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public User author() {",
        "        return author;",
        "    }",
        "",
        "    public String text() {",
        "        return text;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public Message parent() {",
        "        return parent;",
        "    }",
        "",
        "    public Message reply(String replyId, User replier, String text, Set<User> mentions) {",
        "        Message reply = new Message(replyId, replier, text, mentions, this);",
        "        replies.add(reply);",
        "        return reply;",
        "    }",
        "",
        "    public boolean mentions(User user) {",
        "        return mentions.contains(user);",
        "    }",
        "",
        "    public List<Message> replies() {",
        "        return Collections.unmodifiableList(replies);",
        "    }",
        "",
        "    public String threadSummary() {",
        "        StringBuilder builder = new StringBuilder();",
        "        appendTo(builder, 0);",
        "        return builder.toString();",
        "    }",
        "",
        "    private void appendTo(StringBuilder builder, int depth) {",
        "        for (int i = 0; i < depth; i++) {",
        "            builder.append(\"  \");",
        "        }",
        "        builder.append(author.displayName()).append(\": \").append(text).append(System.lineSeparator());",
        "        for (Message reply : replies) {",
        "            reply.appendTo(builder, depth + 1);",
        "        }",
        "    }",
        "}",
      ]),
    },
    {
      filename: "NotificationService.java",
      language: "java",
      content: joinLines([
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "class Notification {",
        "    private final String channelId;",
        "    private final String messageId;",
        "    private final String text;",
        "",
        "    Notification(String channelId, String messageId, String text) {",
        "        this.channelId = channelId;",
        "        this.messageId = messageId;",
        "        this.text = text;",
        "    }",
        "",
        "    public String channelId() {",
        "        return channelId;",
        "    }",
        "",
        "    public String messageId() {",
        "        return messageId;",
        "    }",
        "",
        "    public String text() {",
        "        return text;",
        "    }",
        "}",
        "",
        "interface NotificationPreference {",
        "    boolean shouldNotify(User recipient, Channel channel, Message message);",
        "",
        "    static NotificationPreference allMessages() {",
        "        return new AllMessagesPreference();",
        "    }",
        "",
        "    static NotificationPreference mentionsAndDirectMessages() {",
        "        return new MentionAndDirectMessagePreference();",
        "    }",
        "",
        "    static NotificationPreference mute() {",
        "        return new MutedPreference();",
        "    }",
        "}",
        "",
        "class AllMessagesPreference implements NotificationPreference {",
        "    @Override",
        "    public boolean shouldNotify(User recipient, Channel channel, Message message) {",
        "        return true;",
        "    }",
        "}",
        "",
        "class MentionAndDirectMessagePreference implements NotificationPreference {",
        "    @Override",
        "    public boolean shouldNotify(User recipient, Channel channel, Message message) {",
        "        return channel.isDirectMessage() || message.mentions(recipient);",
        "    }",
        "}",
        "",
        "class MutedPreference implements NotificationPreference {",
        "    @Override",
        "    public boolean shouldNotify(User recipient, Channel channel, Message message) {",
        "        return false;",
        "    }",
        "}",
        "",
        "public class NotificationService {",
        "    private final List<User> observers = new ArrayList<>();",
        "",
        "    public void register(User user) {",
        "        Objects.requireNonNull(user);",
        "        if (!observers.contains(user)) {",
        "            observers.add(user);",
        "        }",
        "    }",
        "",
        "    public void unregister(User user) {",
        "        observers.remove(user);",
        "    }",
        "",
        "    public void notify(Channel channel, Message message) {",
        "        Notification notification = new Notification(",
        "                channel.id(),",
        "                message.id(),",
        "                channel.name() + \" message from \" + message.author().displayName() + \": \" + message.text());",
        "        for (User recipient : observers) {",
        "            if (recipient.equals(message.author())) {",
        "                continue;",
        "            }",
        "            if (!channel.hasMember(recipient)) {",
        "                continue;",
        "            }",
        "            if (recipient.preferenceFor(channel).shouldNotify(recipient, channel, message)) {",
        "                recipient.receiveNotification(notification);",
        "            }",
        "        }",
        "    }",
        "}",
      ]),
    },
    {
      filename: "Channel.java",
      language: "java",
      content: joinLines([
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.HashSet;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public abstract class Channel {",
        "    private final String id;",
        "    private final String name;",
        "    private final Set<User> members = new HashSet<>();",
        "    private final List<Message> messages = new ArrayList<>();",
        "    private final NotificationService notificationService;",
        "",
        "    protected Channel(String id, String name, NotificationService notificationService) {",
        "        if (id == null || id.isBlank()) {",
        "            throw new IllegalArgumentException(\"channel id required\");",
        "        }",
        "        this.id = id;",
        "        this.name = Objects.requireNonNull(name);",
        "        this.notificationService = Objects.requireNonNull(notificationService);",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String name() {",
        "        return name;",
        "    }",
        "",
        "    public void addMember(User user) {",
        "        Objects.requireNonNull(user);",
        "        if (!canJoin(user)) {",
        "            throw new IllegalArgumentException(\"user cannot join channel\");",
        "        }",
        "        members.add(user);",
        "        user.join(this);",
        "    }",
        "",
        "    public void removeMember(User user) {",
        "        members.remove(user);",
        "        user.leave(this);",
        "    }",
        "",
        "    public boolean hasMember(User user) {",
        "        return members.contains(user);",
        "    }",
        "",
        "    public Set<User> members() {",
        "        return Collections.unmodifiableSet(members);",
        "    }",
        "",
        "    public List<Message> messages() {",
        "        return Collections.unmodifiableList(messages);",
        "    }",
        "",
        "    public Message post(String messageId, User author, String text, Set<User> mentions) {",
        "        ensureCanPost(author);",
        "        Message message = new Message(messageId, author, text, mentions, null);",
        "        messages.add(message);",
        "        notificationService.notify(this, message);",
        "        return message;",
        "    }",
        "",
        "    public Message reply(String replyId, User author, Message parent, String text, Set<User> mentions) {",
        "        ensureCanPost(author);",
        "        if (!containsMessage(parent)) {",
        "            throw new IllegalArgumentException(\"parent message is not in this channel\");",
        "        }",
        "        Message reply = parent.reply(replyId, author, text, mentions);",
        "        notificationService.notify(this, reply);",
        "        return reply;",
        "    }",
        "",
        "    protected void ensureCanPost(User author) {",
        "        if (!hasMember(author)) {",
        "            throw new IllegalArgumentException(\"author must be a channel member\");",
        "        }",
        "    }",
        "",
        "    protected boolean canJoin(User user) {",
        "        return true;",
        "    }",
        "",
        "    protected abstract boolean allowsDiscovery();",
        "",
        "    public abstract boolean isDirectMessage();",
        "",
        "    private boolean containsMessage(Message target) {",
        "        for (Message message : messages) {",
        "            if (containsMessage(message, target)) {",
        "                return true;",
        "            }",
        "        }",
        "        return false;",
        "    }",
        "",
        "    private boolean containsMessage(Message current, Message target) {",
        "        if (current == target) {",
        "            return true;",
        "        }",
        "        for (Message reply : current.replies()) {",
        "            if (containsMessage(reply, target)) {",
        "                return true;",
        "            }",
        "        }",
        "        return false;",
        "    }",
        "}",
        "",
        "class PublicChannel extends Channel {",
        "    PublicChannel(String id, String name, NotificationService notificationService) {",
        "        super(id, name, notificationService);",
        "    }",
        "",
        "    @Override",
        "    protected boolean allowsDiscovery() {",
        "        return true;",
        "    }",
        "",
        "    @Override",
        "    public boolean isDirectMessage() {",
        "        return false;",
        "    }",
        "}",
        "",
        "class PrivateChannel extends Channel {",
        "    private final Set<User> invited = new HashSet<>();",
        "",
        "    PrivateChannel(String id, String name, NotificationService notificationService, User owner) {",
        "        super(id, name, notificationService);",
        "        invite(owner);",
        "    }",
        "",
        "    public void invite(User user) {",
        "        Objects.requireNonNull(user);",
        "        invited.add(user);",
        "        super.addMember(user);",
        "    }",
        "",
        "    @Override",
        "    protected boolean canJoin(User user) {",
        "        return invited.contains(user);",
        "    }",
        "",
        "    @Override",
        "    protected boolean allowsDiscovery() {",
        "        return false;",
        "    }",
        "",
        "    @Override",
        "    public boolean isDirectMessage() {",
        "        return false;",
        "    }",
        "}",
        "",
        "class DirectMessage extends PrivateChannel {",
        "    private User first;",
        "    private User second;",
        "",
        "    DirectMessage(String id, User first, User second, NotificationService notificationService) {",
        "        super(id, \"dm-\" + first.id() + \"-\" + second.id(), notificationService, first);",
        "        this.first = first;",
        "        this.second = second;",
        "        invite(second);",
        "    }",
        "",
        "    @Override",
        "    public void invite(User user) {",
        "        if (first != null && second != null && !user.equals(first) && !user.equals(second)) {",
        "            throw new IllegalArgumentException(\"direct message allows exactly two users\");",
        "        }",
        "        super.invite(user);",
        "    }",
        "",
        "    @Override",
        "    public boolean isDirectMessage() {",
        "        return true;",
        "    }",
        "}",
      ]),
    },
    {
      filename: "Workspace.java",
      language: "java",
      content: joinLines([
        "import java.util.ArrayList;",
        "import java.util.HashMap;",
        "import java.util.HashSet;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public class Workspace {",
        "    private final String id;",
        "    private final String name;",
        "    private final Map<String, User> users = new HashMap<>();",
        "    private final Map<String, Channel> channels = new HashMap<>();",
        "    private final NotificationService notificationService;",
        "    private int nextMessageNumber = 1;",
        "",
        "    public Workspace(String id, String name, NotificationService notificationService) {",
        "        this.id = Objects.requireNonNull(id);",
        "        this.name = Objects.requireNonNull(name);",
        "        this.notificationService = Objects.requireNonNull(notificationService);",
        "    }",
        "",
        "    public User addUser(String userId, String displayName) {",
        "        User user = new User(userId, displayName);",
        "        users.put(userId, user);",
        "        notificationService.register(user);",
        "        return user;",
        "    }",
        "",
        "    public PublicChannel createPublicChannel(String channelId, String channelName) {",
        "        PublicChannel channel = new PublicChannel(channelId, channelName, notificationService);",
        "        channels.put(channelId, channel);",
        "        return channel;",
        "    }",
        "",
        "    public PrivateChannel createPrivateChannel(String channelId, String channelName, User owner) {",
        "        requireUser(owner.id());",
        "        PrivateChannel channel = new PrivateChannel(channelId, channelName, notificationService, owner);",
        "        channels.put(channelId, channel);",
        "        return channel;",
        "    }",
        "",
        "    public DirectMessage openDirectMessage(String channelId, User first, User second) {",
        "        requireUser(first.id());",
        "        requireUser(second.id());",
        "        DirectMessage channel = new DirectMessage(channelId, first, second, notificationService);",
        "        channels.put(channelId, channel);",
        "        return channel;",
        "    }",
        "",
        "    public Message postMessage(String channelId, String authorId, String text, Set<String> mentionedUserIds) {",
        "        Channel channel = requireChannel(channelId);",
        "        User author = requireUser(authorId);",
        "        return channel.post(nextMessageId(), author, text, resolveMentions(mentionedUserIds));",
        "    }",
        "",
        "    public Message reply(String channelId, String authorId, Message parent, String text, Set<String> mentionedUserIds) {",
        "        Channel channel = requireChannel(channelId);",
        "        User author = requireUser(authorId);",
        "        return channel.reply(nextMessageId(), author, parent, text, resolveMentions(mentionedUserIds));",
        "    }",
        "",
        "    public List<Channel> discoverableChannels() {",
        "        List<Channel> result = new ArrayList<>();",
        "        for (Channel channel : channels.values()) {",
        "            if (channel.allowsDiscovery()) {",
        "                result.add(channel);",
        "            }",
        "        }",
        "        return result;",
        "    }",
        "",
        "    private Set<User> resolveMentions(Set<String> mentionedUserIds) {",
        "        Set<User> result = new HashSet<>();",
        "        if (mentionedUserIds == null) {",
        "            return result;",
        "        }",
        "        for (String userId : mentionedUserIds) {",
        "            result.add(requireUser(userId));",
        "        }",
        "        return result;",
        "    }",
        "",
        "    private Channel requireChannel(String channelId) {",
        "        Channel channel = channels.get(channelId);",
        "        if (channel == null) {",
        "            throw new IllegalArgumentException(\"unknown channel \" + channelId);",
        "        }",
        "        return channel;",
        "    }",
        "",
        "    private User requireUser(String userId) {",
        "        User user = users.get(userId);",
        "        if (user == null) {",
        "            throw new IllegalArgumentException(\"unknown user \" + userId);",
        "        }",
        "        return user;",
        "    }",
        "",
        "    private String nextMessageId() {",
        "        return \"m\" + nextMessageNumber++;",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String name() {",
        "        return name;",
        "    }",
        "}",
      ]),
    },
    {
      filename: "Main.java",
      language: "java",
      content: joinLines([
        "import java.util.Set;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        NotificationService notifications = new NotificationService();",
        "        Workspace workspace = new Workspace(\"w1\", \"ElevateIQ\", notifications);",
        "",
        "        User alice = workspace.addUser(\"u1\", \"Alice\");",
        "        User bob = workspace.addUser(\"u2\", \"Bob\");",
        "        User chen = workspace.addUser(\"u3\", \"Chen\");",
        "",
        "        PublicChannel general = workspace.createPublicChannel(\"general\", \"general\");",
        "        general.addMember(alice);",
        "        general.addMember(bob);",
        "        general.addMember(chen);",
        "",
        "        bob.setPreference(\"general\", NotificationPreference.allMessages());",
        "        chen.setPreference(\"general\", NotificationPreference.mentionsAndDirectMessages());",
        "",
        "        Message launch = workspace.postMessage(",
        "                \"general\",",
        "                \"u1\",",
        "                \"Can you review the launch plan?\",",
        "                Set.of(\"u2\"));",
        "",
        "        workspace.reply(\"general\", \"u2\", launch, \"Review started\", Set.of(\"u1\"));",
        "",
        "        DirectMessage dm = workspace.openDirectMessage(\"dm-a-c\", alice, chen);",
        "        workspace.postMessage(dm.id(), \"u3\", \"Private follow up\", Set.of(\"u1\"));",
        "",
        "        System.out.println(launch.threadSummary());",
        "    }",
        "}",
      ]),
    },
  ],

  classExplanations: [
    {
      className: "User",
      detailMD:
        "Represents a workspace member. It stores membership references and per-channel **NotificationPreference** values, and exposes **receiveNotification** as the observer callback.",
    },
    {
      className: "Message",
      detailMD:
        "Represents both root posts and replies. Each message owns a list of child replies, so a thread can be rendered recursively using the Composite pattern.",
    },
    {
      className: "NotificationService",
      detailMD:
        "Observer coordinator. It registers workspace users, skips authors, filters by channel membership, and delegates the final send decision to the recipient's strategy.",
    },
    {
      className: "NotificationPreference",
      detailMD:
        "Strategy interface implemented by **AllMessagesPreference**, **MentionAndDirectMessagePreference**, and **MutedPreference**. It keeps product notification rules out of **Channel**.",
    },
    {
      className: "Channel",
      detailMD:
        "Abstract mediator for conversations. It centralizes membership checks, root-message creation, reply attachment, and notification triggering for every channel type.",
    },
    {
      className: "PublicChannel",
      detailMD:
        "Concrete channel with open membership and discoverability. It inherits all routing behavior from **Channel** and only supplies policy differences.",
    },
    {
      className: "PrivateChannel",
      detailMD:
        "Concrete channel with invite-only membership. Its invited set is the single source of truth for who may join.",
    },
    {
      className: "DirectMessage",
      detailMD:
        "Two-person private channel. It reuses private-channel behavior but prevents extra users from being invited and marks itself as a direct message for notification strategy decisions.",
    },
    {
      className: "Workspace",
      detailMD:
        "Aggregate root and outer mediator. It owns users and channels, creates concrete channel objects, resolves mentions by user id, and delegates posting to **Channel**.",
    },
    {
      className: "Main",
      detailMD:
        "Small executable scenario that creates users, joins a public channel, posts a mentioned message, replies in a thread, opens a direct message, and prints the thread tree.",
    },
  ],

  dryRun: {
    inputMD:
      "Workspace with Alice, Bob, and Chen. Channel **general** has all three members. Bob uses all-message notifications, Chen uses mentions plus DMs. Alice posts in **general** mentioning Bob, Bob replies mentioning Alice, and Chen sends Alice a DM.",
    columns: ["Step", "Action", "Mediator decision", "Observers considered", "Outcome"],
    rows: [
      [
        "1",
        "Alice posts in general mentioning Bob",
        "Workspace resolves ids, Channel accepts Alice as member",
        "Bob and Chen, author Alice skipped",
        "Bob notified; Chen not notified because no mention",
      ],
      [
        "2",
        "Bob replies in the thread mentioning Alice",
        "Channel verifies parent belongs to general",
        "Alice and Chen, author Bob skipped",
        "Alice notified by mention; Chen not notified",
      ],
      [
        "3",
        "Chen opens DM with Alice",
        "Workspace creates DirectMessage with two members",
        "No message yet",
        "Private two-user channel exists",
      ],
      [
        "4",
        "Chen sends DM to Alice",
        "DirectMessage accepts Chen as member",
        "Alice only, author Chen skipped",
        "Alice notified because DMs pass default strategy",
      ],
      [
        "5",
        "Render launch thread",
        "Message tree is traversed recursively",
        "No notification fan-out",
        "Root message prints with Bob's nested reply",
      ],
    ],
    narrativeMD:
      "The dry run separates routing from delivery. Workspace and Channel decide whether a message is valid; NotificationService and each user's strategy decide whether a valid message becomes a notification.",
  },

  complexity: [
    {
      operation: "create channel",
      time: "O(1)",
      space: "O(1)",
      note: "Insert one channel object into the workspace map; initial owner membership for private channels is constant work.",
    },
    {
      operation: "join public channel",
      time: "O(1)",
      space: "O(1)",
      note: "Hash-set insertion into the channel members set and user's channel set.",
    },
    {
      operation: "post root message",
      time: "O(M + U)",
      space: "O(K)",
      note: "M observers are scanned, U mentioned user ids are resolved, and K mentioned users are stored on the message.",
    },
    {
      operation: "reply to message",
      time: "O(T + M + U)",
      space: "O(K)",
      note: "T messages in the channel thread tree may be searched to validate the parent before the same notification fan-out runs.",
    },
    {
      operation: "render a thread",
      time: "O(T)",
      space: "O(H)",
      note: "Traverse T messages in the thread; recursion depth is the thread height H.",
    },
  ],
  complexityNotesMD:
    "The hot path is notification fan-out. The base design scans registered observers and filters by channel membership; production systems usually maintain per-channel subscriber lists and enqueue delivery jobs so posting latency is not tied to push-provider latency.",

  extensibility: [
    {
      label: "New notification rule",
      detailMD:
        "Implement **NotificationPreference** for keywords, urgent mentions, quiet hours, or mobile-only preferences. **Channel.post** and **NotificationService.notify** stay unchanged.",
    },
    {
      label: "New channel type",
      detailMD:
        "Subclass **Channel** or **PrivateChannel** for shared channels, announcement-only channels, or archived channels. Override membership/discovery rules while reusing posting and threading.",
    },
    {
      label: "Async delivery",
      detailMD:
        "Replace direct **receiveNotification** calls with a queue-backed delivery adapter. The observer decision remains the same, but delivery becomes retriable and non-blocking.",
    },
    {
      label: "Unread counters and read receipts",
      detailMD:
        "Add a per-user channel state object that listens to accepted messages and read events. This avoids polluting **Message** with viewer-specific state.",
    },
    {
      label: "Search and retention",
      detailMD:
        "Publish accepted-message events to an indexer and retention policy service. The domain model does not need to know how messages are searched or expired.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Separate Thread class",
      detailMD:
        "Create an explicit **Thread** aggregate with a root message and replies instead of storing replies directly on **Message**.",
      tradeoffsMD:
        "This can help with thread-level metadata such as subscribers and resolved status, but it adds another lifecycle object and makes simple recursive rendering less direct.",
    },
    {
      name: "Notification rules on Channel",
      detailMD:
        "Let each channel decide whether each member should be notified instead of using **NotificationPreference** strategies on users.",
      tradeoffsMD:
        "Channel-centric policy is simple for global channel settings, but it handles personal preferences poorly and tends to accumulate conditional logic.",
    },
    {
      name: "Event bus instead of direct observer service",
      detailMD:
        "Publish a **MessagePosted** event to an application event bus, with notification, search, audit, and unread-counter consumers subscribing independently.",
      tradeoffsMD:
        "Better production decoupling and reliability, but too much infrastructure for the core interview model unless the interviewer asks about scale.",
    },
  ],

  commonMistakes: [
    "Letting **User** send messages directly to other users, which bypasses channel membership and loses the Mediator boundary.",
    "Treating public, private, and DM channels as unrelated classes with duplicated post and reply logic.",
    "Storing thread replies in a global list without validating that the parent belongs to the channel.",
    "Hard-coding notification behavior in **Channel.post** instead of delegating to strategies.",
    "Not skipping the author during notification fan-out.",
    "Allowing direct messages to grow beyond two members, which turns them into private channels with a misleading type.",
    "Mixing persistence, push gateway calls, and domain validation in one class during the interview design.",
  ],

  followUps: [
    {
      question: "How would you scale notification fan-out for a channel with thousands of members?",
      answerMD:
        "Keep the domain decision synchronous but enqueue delivery jobs after the message is accepted. Maintain a per-channel subscriber index so the notification service scans channel members instead of all workspace users.",
    },
    {
      question: "How would you add unread counts?",
      answerMD:
        "Introduce **UserChannelState** with last-read message id or timestamp per user and channel. It listens to accepted messages and read events rather than changing **Message** itself.",
    },
    {
      question: "How do you support channel admins and posting restrictions?",
      answerMD:
        "Add a role map on **Channel** and move **ensureCanPost** to a policy method. Announcement-only channels can override the policy or inject a posting strategy.",
    },
    {
      question: "How would mentions work for user groups such as engineering?",
      answerMD:
        "Resolve mention tokens through a **MentionResolver** before calling **Channel.post**. It can expand a group to users while keeping **Message** as a set of mentioned recipients.",
    },
    {
      question: "Where do external integrations and bots fit?",
      answerMD:
        "Model bots as users or apps with scoped permissions. They post through the same channel mediator so membership, threading, and notifications stay consistent.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable storage",
      detailMD:
        "Persist workspaces, channels, memberships, messages, and user preferences in separate repositories. Channel posting becomes a transaction that writes the message and emits an event.",
    },
    {
      label: "Authorization and audit",
      detailMD:
        "Enforce workspace membership, channel role, retention, and compliance policies at the service boundary. Audit membership changes, private-channel invites, and deletion events.",
    },
    {
      label: "Delivery reliability",
      detailMD:
        "Use a queue for push, email, and desktop notifications with retries, idempotency keys, and dead-letter handling. Do not block message posting on a mobile push provider.",
    },
    {
      label: "Eventual consistency",
      detailMD:
        "Search indexing, unread counters, and analytics can lag accepted messages by a few seconds. The primary invariant is that channel storage and membership checks remain strongly consistent.",
    },
    {
      label: "Privacy and retention",
      detailMD:
        "Private channels and DMs need strict access checks, retention policies, export controls, and deletion workflows. Those policies should live at service/repository boundaries, not inside UI code.",
    },
  ],

  interviewNotes: [
    "Did you identify **Workspace** and **Channel** as mediators instead of making users talk directly?",
    "Did you keep membership checks inside the channel boundary for public, private, and DM types?",
    "Did you model threads explicitly rather than flattening all replies into one message list?",
    "Did you separate notification preferences with a Strategy interface?",
    "Did you use Observer for notifications without coupling channel code to device delivery?",
    "Can you describe how the simple model evolves to queues, repositories, and search without rewriting the domain?",
  ],

  quiz: [
    {
      question: "Why should **Channel** mediate posting instead of allowing **User** to call another user directly?",
      options: [
        "Channel owns membership and can reject unauthorized authors before a message exists",
        "User objects cannot hold references in Java",
        "It makes every notification synchronous",
        "It removes the need for a workspace",
      ],
      answerIndex: 0,
      explanationMD:
        "The mediator boundary centralizes channel membership, message creation, thread validation, and notification triggering.",
    },
    {
      question: "Which design choice demonstrates the Composite pattern?",
      options: [
        "A **Message** containing child reply messages",
        "A **Workspace** map from id to user",
        "A **NotificationService** list of observers",
        "A **PublicChannel** being discoverable",
      ],
      answerIndex: 0,
      explanationMD:
        "A thread is a tree where root messages and replies are both **Message** objects, so recursive traversal treats them uniformly.",
    },
    {
      question: "What is the main benefit of **NotificationPreference** as a Strategy?",
      options: [
        "Notification rules can vary per user and channel without editing **Channel.post**",
        "Messages no longer need authors",
        "Private channels become public automatically",
        "Thread traversal becomes O(1)",
      ],
      answerIndex: 0,
      explanationMD:
        "Strategy isolates the rule that decides whether a recipient should be notified from the routing code that accepts messages.",
    },
    {
      question: "Why does **DirectMessage** extend private-channel behavior but restrict invites?",
      options: [
        "Because a DM shares private routing but must preserve exactly two participants",
        "Because DMs are always public",
        "Because direct messages cannot have notifications",
        "Because Java requires all subclasses to override every method",
      ],
      answerIndex: 0,
      explanationMD:
        "DMs reuse the private membership and posting flow while adding a stricter invariant around participant count.",
    },
    {
      question: "When Bob replies to Alice's root message, what should the channel validate first?",
      options: [
        "Bob is a channel member and the parent message belongs to that channel",
        "Bob has all-message notifications enabled",
        "The workspace has at least one private channel",
        "The thread has no existing replies",
      ],
      answerIndex: 0,
      explanationMD:
        "Replying is valid only if the author can post and the target parent is already part of the channel conversation tree.",
    },
  ],

  practiceVariants: [
    {
      title: "Add unread counters",
      detailMD:
        "Create **UserChannelState** and update unread counts when messages are accepted. Keep the message tree independent of per-user read state.",
      difficulty: "Intermediate",
    },
    {
      title: "Add announcement-only channels",
      detailMD:
        "Introduce channel roles and a posting policy so only admins can post while every member can read. Decide whether this belongs in a Strategy or a subclass.",
      difficulty: "Advanced",
    },
    {
      title: "Add async notification delivery",
      detailMD:
        "Replace direct observer callbacks with a queue-backed delivery adapter that supports retries and per-device channels.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the mediator in the Slack LLD model?",
      back: "**Workspace** resolves users and channels, and **Channel** enforces membership plus routes accepted messages to notifications.",
    },
    {
      front: "Where should public/private/DM membership rules live?",
      back: "In concrete channel types: **PublicChannel**, **PrivateChannel**, and **DirectMessage**, while shared posting remains in **Channel**.",
    },
    {
      front: "How are threads represented?",
      back: "A **Message** owns child reply messages, forming a recursive tree that demonstrates Composite.",
    },
    {
      front: "Why use Observer for notifications?",
      back: "Channels announce accepted messages to **NotificationService** without knowing delivery devices or external providers.",
    },
    {
      front: "Why use Strategy for notification preferences?",
      back: "Each recipient can choose all messages, mentions plus DMs, or mute without changing message routing code.",
    },
    {
      front: "What is the most important DM invariant?",
      back: "A direct message has exactly two participants and should not silently become a private group channel.",
    },
  ],

  cheatSheetMD: joinLines([
    "**Entities:** Workspace owns Users and Channels; Channel owns members and root Messages; Message owns replies; NotificationService owns observers; NotificationPreference owns delivery rules.",
    "",
    "**Channel types:** PublicChannel is discoverable and open to workspace users. PrivateChannel requires invite. DirectMessage reuses private behavior but allows exactly two users.",
    "",
    "**Patterns:** Mediator for Workspace/Channel routing, Observer for notifications, Strategy for preferences, Composite for message threads.",
    "",
    "**Post flow:** resolve ids in Workspace → validate membership in Channel → create Message → store as root or reply → notify observers according to preferences.",
    "",
    "**Invariants:** non-members cannot post; replies must target a message in the same channel; the author is not notified; DMs have two participants; muted users receive no notifications.",
    "",
    "**Scale path:** replace direct callbacks with queues, add repositories for persistence, add subscriber indexes for fan-out, and publish accepted-message events to search and unread-counter consumers.",
  ]),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, and Vlissides",
    },
    {
      title: "Head First Design Patterns (Observer, Strategy, Composite)",
      kind: "Book",
      author: "Freeman and Robson",
    },
    {
      title: "Slack API Conversations API",
      kind: "Docs",
      url: "https://api.slack.com/methods?filter=conversations",
      author: "Slack",
    },
    {
      title: "Refactoring Guru — Mediator Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/mediator",
    },
  ],

  relatedProblems: [
    { slug: "whatsapp", note: "Another messaging model with users, chats, delivery state, and notification tradeoffs." },
    { slug: "notification-system", note: "Deep dive on observer-style fan-out, preferences, and delivery channels." },
    { slug: "trello", note: "Collaboration workspace model with membership, nested content, and activity notifications." },
  ],
};
