import type { LLDProblemContent } from "../types";

export const taskScheduler: LLDProblemContent = {
  slug: "task-scheduler",

  statementMD: [
    "Design an in-memory **task scheduler** that accepts one-time and recurring tasks, orders them by next-run time, and executes due work using a pool of worker threads.",
    "",
    "The scheduler must support cancellation, retry-on-failure with backoff, and safe concurrent calls from many producers while workers are consuming due tasks. The interview focus is the object model and concurrency boundary: a thread-safe time priority queue, blocking workers, retry policy, and cancellation races.",
  ].join("\n"),

  businessContextMD: [
    "Task schedulers appear behind reminders, email campaigns, billing jobs, cache refreshes, and workflow engines. Interviewers use this problem to test whether you can combine clean LLD with practical concurrency: producers publish work, consumers block until work is due, and failures are rescheduled without corrupting shared state.",
    "",
    "Cron parsing and distributed execution are useful extensions, but the core design is a single-process scheduler with a reliable worker model, explicit lifecycle, and small seams for retry strategy and future persistence.",
  ].join("\n"),

  functionalRequirements: [
    "Schedule one-time tasks to run after a delay or at a specific future time.",
    "Schedule recurring tasks with an initial delay and a fixed interval between successful runs.",
    "Maintain tasks in next-run-time order so the earliest due task is executed first.",
    "Run due tasks through a configurable pool of worker threads.",
    "Retry failed executions using a pluggable backoff policy.",
    "Cancel a task by id, including recurring tasks that would otherwise be requeued.",
    "Start and shut down the scheduler safely without leaking worker threads.",
    "Expose the current pending task ids for debugging and operations.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Thread safety",
      detailMD:
        "Multiple producer threads may schedule or cancel while worker threads take due tasks. Shared state must be protected by a thread-safe **BlockingQueue**, a concurrent map, and short lifecycle or scheduling locks.",
    },
    {
      label: "No busy waiting",
      detailMD:
        "Workers should block until the next task is due instead of polling in a loop. **DelayQueue** gives priority-queue ordering plus blocking semantics.",
    },
    {
      label: "Execution isolation",
      detailMD:
        "A failing task must not kill the worker thread or block unrelated tasks forever. The worker catches exceptions and delegates retry or removal.",
    },
    {
      label: "Extensibility",
      detailMD:
        "Retry rules, future cron schedules, persistence, and task categories should be additive. The scheduler should depend on interfaces where policy changes.",
    },
    {
      label: "Graceful lifecycle",
      detailMD:
        "Start should be idempotent, shutdown should interrupt blocking workers, and cancellation should be safe even if the task is already executing.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need full cron expression support?",
      answerMD:
        "Not in the base design. Model one-time and fixed-interval recurring tasks first; cron can be added later as another schedule calculation strategy.",
    },
    {
      question: "What happens if a recurring task takes longer than its interval?",
      answerMD:
        "The base design reschedules after a successful execution using **now plus interval**. That prevents overlapping executions of the same task in this simple scheduler.",
    },
    {
      question: "Can cancellation interrupt a task that is already running?",
      answerMD:
        "The scheduler marks the task cancelled and prevents future retries or recurring runs. It does not forcibly stop arbitrary user code unless that code cooperates with interruption.",
    },
    {
      question: "How many times should a failed task retry?",
      answerMD:
        "Retry count and delay are owned by **RetryPolicy**. The sample includes no-retry, fixed-delay, and exponential-backoff policies.",
    },
    {
      question: "Does the scheduler need durable storage?",
      answerMD:
        "In-memory is enough for the core LLD. Production can add a repository so pending tasks survive process restarts and multiple scheduler instances can coordinate.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Task {",
    "        <<interface>>",
    "        +execute() void",
    "    }",
    "    class ScheduledTask {",
    "        -String id",
    "        -Task command",
    "        -Instant nextRunAt",
    "        -Duration interval",
    "        -RetryPolicy retryPolicy",
    "        -AtomicBoolean cancelled",
    "        +getDelay(TimeUnit) long",
    "        +compareTo(Delayed) int",
    "        +execute() void",
    "        +markSuccess(Instant) void",
    "        +markFailure(Instant, Exception) boolean",
    "        +cancel() void",
    "    }",
    "    class RetryPolicy {",
    "        <<interface>>",
    "        +nextDelay(int, Exception) Optional~Duration~",
    "    }",
    "    class TaskScheduler {",
    "        -DelayQueue~ScheduledTask~ queue",
    "        -ConcurrentHashMap~String,ScheduledTask~ tasks",
    "        -List~Worker~ workers",
    "        -ReentrantLock schedulingLock",
    "        +getInstance() TaskScheduler",
    "        +start(int) void",
    "        +scheduleOnce(String, Task, Duration, RetryPolicy) ScheduledTask",
    "        +scheduleRecurring(String, Task, Duration, Duration, RetryPolicy) ScheduledTask",
    "        +cancel(String) boolean",
    "        +shutdown() void",
    "    }",
    "    class Worker {",
    "        -TaskScheduler scheduler",
    "        -Thread thread",
    "        -AtomicBoolean accepting",
    "        +run() void",
    "        +requestStop() void",
    "    }",
    "    class Main {",
    "        +main(String[]) void",
    "    }",
    "    TaskScheduler o-- ScheduledTask",
    "    TaskScheduler o-- Worker",
    "    ScheduledTask --> Task",
    "    ScheduledTask --> RetryPolicy",
    "    Worker --> TaskScheduler",
    "    Main ..> TaskScheduler",
    "    Main ..> RetryPolicy",
  ].join("\n"),
  classDiagramCaptionMD:
    "**Task** is the command, **ScheduledTask** is the queue item ordered by next run time, **RetryPolicy** is the backoff strategy, and **TaskScheduler** is the singleton facade that owns the BlockingQueue plus workers.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Client",
    "    participant Scheduler as TaskScheduler",
    "    participant Queue as DelayQueue",
    "    participant Worker",
    "    participant Policy as RetryPolicy",
    "    Client->>Scheduler: scheduleRecurring(task, interval)",
    "    Scheduler->>Queue: offer ScheduledTask",
    "    Worker->>Queue: take blocks until due",
    "    Queue-->>Worker: due ScheduledTask",
    "    Worker->>Worker: execute command",
    "    alt success and recurring",
    "        Worker->>Scheduler: complete task",
    "        Scheduler->>Queue: offer with next interval",
    "    else failure with retry left",
    "        Worker->>Policy: nextDelay(failureCount, error)",
    "        Policy-->>Worker: backoff delay",
    "        Worker->>Scheduler: fail task",
    "        Scheduler->>Queue: offer with retry time",
    "    else cancellation",
    "        Client->>Scheduler: cancel(taskId)",
    "        Scheduler->>Queue: remove and mark cancelled",
    "    end",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Clients are producers and workers are consumers. The queue blocks workers until a task is due, while the scheduler lock makes cancel, retry, and requeue decisions atomic.",

  entities: [
    {
      name: "Task",
      responsibilityMD:
        "Command interface for user work. The scheduler stores and executes a **Task** without knowing whether it sends email, refreshes a cache, or runs billing.",
      attributes: ["execute()"],
    },
    {
      name: "ScheduledTask",
      responsibilityMD:
        "Thread-safe queue item. It wraps a command, id, next-run time, optional interval, retry policy, failure count, and cancellation flag. It implements **Delayed** so the queue can order it by due time.",
      attributes: ["id", "command", "nextRunAt", "interval", "retryPolicy", "cancelled"],
    },
    {
      name: "RetryPolicy",
      responsibilityMD:
        "Backoff strategy. It receives the current failure count and exception, then returns the next retry delay or empty when retries are exhausted.",
      attributes: ["nextDelay(failureCount, error)"],
    },
    {
      name: "TaskScheduler",
      responsibilityMD:
        "Singleton facade and aggregate root. It owns the **DelayQueue**, active-task map, worker lifecycle, scheduling lock, and public methods for schedule, cancel, start, and shutdown.",
      attributes: ["queue", "tasks", "workers", "schedulingLock", "lifecycleLock"],
    },
    {
      name: "Worker",
      responsibilityMD:
        "Consumer loop. A worker blocks on the queue, skips cancelled tasks, executes due commands, and reports success or failure back to the scheduler for requeue decisions.",
      attributes: ["scheduler", "thread", "accepting"],
    },
    {
      name: "DelayQueue",
      responsibilityMD:
        "Thread-safe priority blocking queue from the JDK. It releases a **ScheduledTask** only when its delay reaches zero, removing the need for manual polling.",
      attributes: ["offer", "take", "remove"],
    },
  ],

  patternsUsed: [
    {
      name: "Command",
      whyMD:
        "**Task** is a command object. The scheduler can queue, execute, retry, and cancel work uniformly without depending on concrete business logic.",
    },
    {
      name: "Strategy",
      whyMD:
        "**RetryPolicy** is a strategy. Fixed delay, exponential backoff, and no-retry policies are interchangeable without changing the worker loop.",
    },
    {
      name: "Producer-Consumer",
      whyMD:
        "Client threads produce **ScheduledTask** instances into a **BlockingQueue**; worker threads consume due tasks with **take**. This naturally handles backpressure and avoids busy waiting.",
    },
    {
      name: "Singleton",
      whyMD:
        "**TaskScheduler.getInstance** provides one process-wide scheduler that owns the worker pool and queue. In a real service, dependency injection can wrap or replace this singleton for tests.",
    },
  ],

  designSteps: [
    {
      title: "Represent executable work as a command",
      detailMD:
        "Start with a tiny **Task** interface. Everything scheduled by the system is just a command with an **execute** method, so the scheduler never needs a switch on task type.",
      code: [
        "public interface Task {",
        "    void execute() throws Exception;",
        "}",
      ].join("\n"),
    },
    {
      title: "Make scheduled work comparable by due time",
      detailMD:
        "**ScheduledTask** implements **Delayed**, so Java's **DelayQueue** can order items by **nextRunAt** and block consumers until the head is due.",
      code: [
        "@Override",
        "public long getDelay(TimeUnit unit) {",
        "    long nanos = Duration.between(Instant.now(), nextRunAt).toNanos();",
        "    return unit.convert(nanos, TimeUnit.NANOSECONDS);",
        "}",
        "",
        "@Override",
        "public int compareTo(Delayed other) {",
        "    ScheduledTask task = (ScheduledTask) other;",
        "    return nextRunAt.compareTo(task.nextRunAt);",
        "}",
      ].join("\n"),
    },
    {
      title: "Separate retry policy from worker logic",
      detailMD:
        "The worker should not know exponential math or retry limits. It asks **RetryPolicy** for the next delay, then the scheduler requeues or removes the task.",
      code: [
        "public interface RetryPolicy {",
        "    Optional<Duration> nextDelay(int failureCount, Exception error);",
        "}",
      ].join("\n"),
    },
    {
      title: "Use DelayQueue as the producer-consumer boundary",
      detailMD:
        "Scheduling is a producer operation: validate the task, put it in the active map, then offer it to the **DelayQueue**. Workers are consumers blocked on **take**, so no thread spins while waiting for time to pass.",
    },
    {
      title: "Keep requeue and cancellation atomic",
      detailMD:
        "A task can finish at the same time another thread calls **cancel**. Guard map updates, queue removal, and requeue decisions with a short **schedulingLock** so cancelled tasks cannot be reintroduced as active work.",
    },
    {
      title: "Let workers report outcomes, not own policy",
      detailMD:
        "The worker loop executes due commands and reports **complete** or **fail** to the scheduler. The scheduler owns whether to reschedule recurring work, retry after backoff, or remove exhausted tasks.",
      code: [
        "while (accepting.get() && scheduler.isRunning()) {",
        "    ScheduledTask task = scheduler.takeDueTask();",
        "    if (!task.isCancelled()) {",
        "        task.execute();",
        "        scheduler.complete(task);",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  implementation: [
    {
      filename: "Task.java",
      language: "java",
      content: [
        "public interface Task {",
        "    void execute() throws Exception;",
        "}",
      ].join("\n"),
    },
    {
      filename: "ScheduledTask.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "import java.util.concurrent.Delayed;",
        "import java.util.concurrent.TimeUnit;",
        "import java.util.concurrent.atomic.AtomicBoolean;",
        "import java.util.concurrent.atomic.AtomicInteger;",
        "",
        "public final class ScheduledTask implements Delayed {",
        "    private final String id;",
        "    private final Task command;",
        "    private final RetryPolicy retryPolicy;",
        "    private final Duration interval;",
        "    private final AtomicInteger failureCount = new AtomicInteger(0);",
        "    private final AtomicBoolean cancelled = new AtomicBoolean(false);",
        "    private volatile Instant nextRunAt;",
        "",
        "    private ScheduledTask(String id, Task command, Instant nextRunAt, Duration interval, RetryPolicy retryPolicy) {",
        "        this.id = requireText(id, \"id\");",
        "        this.command = Objects.requireNonNull(command, \"command\");",
        "        this.nextRunAt = Objects.requireNonNull(nextRunAt, \"nextRunAt\");",
        "        this.interval = interval;",
        "        this.retryPolicy = Objects.requireNonNull(retryPolicy, \"retryPolicy\");",
        "        if (interval != null && (interval.isZero() || interval.isNegative())) {",
        "            throw new IllegalArgumentException(\"interval must be positive\");",
        "        }",
        "    }",
        "",
        "    public static ScheduledTask oneTime(String id, Task command, Instant runAt, RetryPolicy retryPolicy) {",
        "        return new ScheduledTask(id, command, runAt, null, retryPolicy);",
        "    }",
        "",
        "    public static ScheduledTask recurring(String id, Task command, Instant firstRunAt, Duration interval, RetryPolicy retryPolicy) {",
        "        return new ScheduledTask(id, command, firstRunAt, interval, retryPolicy);",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public Instant getNextRunAt() {",
        "        return nextRunAt;",
        "    }",
        "",
        "    public boolean isRecurring() {",
        "        return interval != null;",
        "    }",
        "",
        "    public boolean isCancelled() {",
        "        return cancelled.get();",
        "    }",
        "",
        "    public void cancel() {",
        "        cancelled.set(true);",
        "    }",
        "",
        "    public void execute() throws Exception {",
        "        if (!isCancelled()) {",
        "            command.execute();",
        "        }",
        "    }",
        "",
        "    public void markSuccess(Instant now) {",
        "        Objects.requireNonNull(now, \"now\");",
        "        failureCount.set(0);",
        "        if (isRecurring()) {",
        "            nextRunAt = now.plus(interval);",
        "        } else {",
        "            cancel();",
        "        }",
        "    }",
        "",
        "    public boolean markFailure(Instant now, Exception error) {",
        "        Objects.requireNonNull(now, \"now\");",
        "        Objects.requireNonNull(error, \"error\");",
        "        Optional<Duration> retryDelay = retryPolicy.nextDelay(failureCount.incrementAndGet(), error);",
        "        if (retryDelay.isEmpty()) {",
        "            cancel();",
        "            return false;",
        "        }",
        "        nextRunAt = now.plus(retryDelay.get());",
        "        return true;",
        "    }",
        "",
        "    @Override",
        "    public long getDelay(TimeUnit unit) {",
        "        long nanos = Duration.between(Instant.now(), nextRunAt).toNanos();",
        "        return unit.convert(nanos, TimeUnit.NANOSECONDS);",
        "    }",
        "",
        "    @Override",
        "    public int compareTo(Delayed other) {",
        "        if (this == other) {",
        "            return 0;",
        "        }",
        "        if (other instanceof ScheduledTask scheduledTask) {",
        "            return nextRunAt.compareTo(scheduledTask.nextRunAt);",
        "        }",
        "        return Long.compare(getDelay(TimeUnit.NANOSECONDS), other.getDelay(TimeUnit.NANOSECONDS));",
        "    }",
        "",
        "    private static String requireText(String value, String fieldName) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(fieldName + \" is required\");",
        "        }",
        "        return value.trim();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "RetryPolicy.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "",
        "public interface RetryPolicy {",
        "    Optional<Duration> nextDelay(int failureCount, Exception error);",
        "",
        "    static RetryPolicy noRetries() {",
        "        return new NoRetryPolicy();",
        "    }",
        "",
        "    static RetryPolicy fixedDelay(int maxRetries, Duration delay) {",
        "        return new FixedDelayRetryPolicy(maxRetries, delay);",
        "    }",
        "",
        "    static RetryPolicy exponentialBackoff(int maxRetries, Duration initialDelay, double multiplier, Duration maxDelay) {",
        "        return new ExponentialBackoffRetryPolicy(maxRetries, initialDelay, multiplier, maxDelay);",
        "    }",
        "}",
        "",
        "final class NoRetryPolicy implements RetryPolicy {",
        "    @Override",
        "    public Optional<Duration> nextDelay(int failureCount, Exception error) {",
        "        return Optional.empty();",
        "    }",
        "}",
        "",
        "final class FixedDelayRetryPolicy implements RetryPolicy {",
        "    private final int maxRetries;",
        "    private final Duration delay;",
        "",
        "    FixedDelayRetryPolicy(int maxRetries, Duration delay) {",
        "        this.maxRetries = requireMaxRetries(maxRetries);",
        "        this.delay = requireNonNegative(delay, \"delay\");",
        "    }",
        "",
        "    @Override",
        "    public Optional<Duration> nextDelay(int failureCount, Exception error) {",
        "        if (failureCount > maxRetries) {",
        "            return Optional.empty();",
        "        }",
        "        return Optional.of(delay);",
        "    }",
        "",
        "    private static int requireMaxRetries(int maxRetries) {",
        "        if (maxRetries < 0) {",
        "            throw new IllegalArgumentException(\"maxRetries cannot be negative\");",
        "        }",
        "        return maxRetries;",
        "    }",
        "",
        "    private static Duration requireNonNegative(Duration duration, String fieldName) {",
        "        Objects.requireNonNull(duration, fieldName);",
        "        if (duration.isNegative()) {",
        "            throw new IllegalArgumentException(fieldName + \" cannot be negative\");",
        "        }",
        "        return duration;",
        "    }",
        "}",
        "",
        "final class ExponentialBackoffRetryPolicy implements RetryPolicy {",
        "    private final int maxRetries;",
        "    private final Duration initialDelay;",
        "    private final double multiplier;",
        "    private final Duration maxDelay;",
        "",
        "    ExponentialBackoffRetryPolicy(int maxRetries, Duration initialDelay, double multiplier, Duration maxDelay) {",
        "        if (maxRetries < 0) {",
        "            throw new IllegalArgumentException(\"maxRetries cannot be negative\");",
        "        }",
        "        if (multiplier < 1.0) {",
        "            throw new IllegalArgumentException(\"multiplier must be at least 1.0\");",
        "        }",
        "        this.maxRetries = maxRetries;",
        "        this.initialDelay = requireNonNegative(initialDelay, \"initialDelay\");",
        "        this.multiplier = multiplier;",
        "        this.maxDelay = requireNonNegative(maxDelay, \"maxDelay\");",
        "    }",
        "",
        "    @Override",
        "    public Optional<Duration> nextDelay(int failureCount, Exception error) {",
        "        if (failureCount > maxRetries) {",
        "            return Optional.empty();",
        "        }",
        "        double rawMillis = initialDelay.toMillis() * Math.pow(multiplier, failureCount - 1);",
        "        long cappedMillis = Math.min(maxDelay.toMillis(), Math.round(rawMillis));",
        "        return Optional.of(Duration.ofMillis(cappedMillis));",
        "    }",
        "",
        "    private static Duration requireNonNegative(Duration duration, String fieldName) {",
        "        Objects.requireNonNull(duration, fieldName);",
        "        if (duration.isNegative()) {",
        "            throw new IllegalArgumentException(fieldName + \" cannot be negative\");",
        "        }",
        "        return duration;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "TaskScheduler.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.concurrent.ConcurrentHashMap;",
        "import java.util.concurrent.DelayQueue;",
        "import java.util.concurrent.atomic.AtomicBoolean;",
        "import java.util.concurrent.locks.ReentrantLock;",
        "",
        "public final class TaskScheduler {",
        "    private static final TaskScheduler INSTANCE = new TaskScheduler();",
        "",
        "    private final DelayQueue<ScheduledTask> queue = new DelayQueue<>();",
        "    private final ConcurrentHashMap<String, ScheduledTask> tasks = new ConcurrentHashMap<>();",
        "    private final List<Worker> workers = new ArrayList<>();",
        "    private final ReentrantLock lifecycleLock = new ReentrantLock();",
        "    private final ReentrantLock schedulingLock = new ReentrantLock();",
        "    private final AtomicBoolean running = new AtomicBoolean(false);",
        "",
        "    private TaskScheduler() {",
        "    }",
        "",
        "    public static TaskScheduler getInstance() {",
        "        return INSTANCE;",
        "    }",
        "",
        "    public void start(int workerCount) {",
        "        if (workerCount <= 0) {",
        "            throw new IllegalArgumentException(\"workerCount must be positive\");",
        "        }",
        "        lifecycleLock.lock();",
        "        try {",
        "            if (running.get()) {",
        "                return;",
        "            }",
        "            running.set(true);",
        "            for (int i = 0; i < workerCount; i++) {",
        "                Worker worker = new Worker(\"task-scheduler-worker-\" + (i + 1), this);",
        "                workers.add(worker);",
        "                worker.start();",
        "            }",
        "        } finally {",
        "            lifecycleLock.unlock();",
        "        }",
        "    }",
        "",
        "    public ScheduledTask scheduleOnce(String id, Task command, Duration delay, RetryPolicy retryPolicy) {",
        "        Duration safeDelay = requireNonNegative(delay, \"delay\");",
        "        return scheduleAt(id, command, Instant.now().plus(safeDelay), retryPolicy);",
        "    }",
        "",
        "    public ScheduledTask scheduleAt(String id, Task command, Instant runAt, RetryPolicy retryPolicy) {",
        "        return add(ScheduledTask.oneTime(id, command, Objects.requireNonNull(runAt, \"runAt\"), retryPolicy));",
        "    }",
        "",
        "    public ScheduledTask scheduleRecurring(String id, Task command, Duration initialDelay, Duration interval, RetryPolicy retryPolicy) {",
        "        Duration safeInitialDelay = requireNonNegative(initialDelay, \"initialDelay\");",
        "        Duration safeInterval = requirePositive(interval, \"interval\");",
        "        return add(ScheduledTask.recurring(id, command, Instant.now().plus(safeInitialDelay), safeInterval, retryPolicy));",
        "    }",
        "",
        "    public boolean cancel(String id) {",
        "        Objects.requireNonNull(id, \"id\");",
        "        schedulingLock.lock();",
        "        try {",
        "            ScheduledTask task = tasks.remove(id);",
        "            if (task == null) {",
        "                return false;",
        "            }",
        "            task.cancel();",
        "            queue.remove(task);",
        "            return true;",
        "        } finally {",
        "            schedulingLock.unlock();",
        "        }",
        "    }",
        "",
        "    public List<String> pendingTaskIds() {",
        "        return List.copyOf(tasks.keySet());",
        "    }",
        "",
        "    public void shutdown() {",
        "        List<Worker> snapshot;",
        "        lifecycleLock.lock();",
        "        try {",
        "            if (!running.get()) {",
        "                return;",
        "            }",
        "            running.set(false);",
        "            snapshot = List.copyOf(workers);",
        "            workers.clear();",
        "        } finally {",
        "            lifecycleLock.unlock();",
        "        }",
        "",
        "        for (Worker worker : snapshot) {",
        "            worker.requestStop();",
        "        }",
        "        for (Worker worker : snapshot) {",
        "            try {",
        "                worker.awaitStop(Duration.ofSeconds(2));",
        "            } catch (InterruptedException interrupted) {",
        "                Thread.currentThread().interrupt();",
        "                break;",
        "            }",
        "        }",
        "",
        "        schedulingLock.lock();",
        "        try {",
        "            queue.clear();",
        "            tasks.clear();",
        "        } finally {",
        "            schedulingLock.unlock();",
        "        }",
        "    }",
        "",
        "    ScheduledTask takeDueTask() throws InterruptedException {",
        "        return queue.take();",
        "    }",
        "",
        "    boolean isRunning() {",
        "        return running.get();",
        "    }",
        "",
        "    void complete(ScheduledTask task) {",
        "        schedulingLock.lock();",
        "        try {",
        "            if (task.isCancelled() || tasks.get(task.getId()) != task) {",
        "                tasks.remove(task.getId(), task);",
        "                return;",
        "            }",
        "            task.markSuccess(Instant.now());",
        "            if (task.isRecurring() && !task.isCancelled()) {",
        "                queue.offer(task);",
        "            } else {",
        "                tasks.remove(task.getId(), task);",
        "            }",
        "        } finally {",
        "            schedulingLock.unlock();",
        "        }",
        "    }",
        "",
        "    void fail(ScheduledTask task, Exception error) {",
        "        schedulingLock.lock();",
        "        try {",
        "            if (task.isCancelled() || tasks.get(task.getId()) != task) {",
        "                tasks.remove(task.getId(), task);",
        "                return;",
        "            }",
        "            boolean retry = task.markFailure(Instant.now(), error);",
        "            if (retry && !task.isCancelled()) {",
        "                queue.offer(task);",
        "            } else {",
        "                tasks.remove(task.getId(), task);",
        "            }",
        "        } finally {",
        "            schedulingLock.unlock();",
        "        }",
        "    }",
        "",
        "    private ScheduledTask add(ScheduledTask task) {",
        "        schedulingLock.lock();",
        "        try {",
        "            if (!running.get()) {",
        "                throw new IllegalStateException(\"scheduler is not running\");",
        "            }",
        "            ScheduledTask existing = tasks.putIfAbsent(task.getId(), task);",
        "            if (existing != null) {",
        "                throw new IllegalArgumentException(\"task id already exists: \" + task.getId());",
        "            }",
        "            queue.offer(task);",
        "            return task;",
        "        } finally {",
        "            schedulingLock.unlock();",
        "        }",
        "    }",
        "",
        "    private static Duration requireNonNegative(Duration duration, String fieldName) {",
        "        Objects.requireNonNull(duration, fieldName);",
        "        if (duration.isNegative()) {",
        "            throw new IllegalArgumentException(fieldName + \" cannot be negative\");",
        "        }",
        "        return duration;",
        "    }",
        "",
        "    private static Duration requirePositive(Duration duration, String fieldName) {",
        "        Objects.requireNonNull(duration, fieldName);",
        "        if (duration.isZero() || duration.isNegative()) {",
        "            throw new IllegalArgumentException(fieldName + \" must be positive\");",
        "        }",
        "        return duration;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Worker.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.util.Objects;",
        "import java.util.concurrent.atomic.AtomicBoolean;",
        "",
        "public final class Worker implements Runnable {",
        "    private final TaskScheduler scheduler;",
        "    private final AtomicBoolean accepting = new AtomicBoolean(true);",
        "    private final Thread thread;",
        "",
        "    Worker(String name, TaskScheduler scheduler) {",
        "        this.scheduler = Objects.requireNonNull(scheduler, \"scheduler\");",
        "        this.thread = new Thread(this, Objects.requireNonNull(name, \"name\"));",
        "        this.thread.setDaemon(true);",
        "    }",
        "",
        "    void start() {",
        "        thread.start();",
        "    }",
        "",
        "    void requestStop() {",
        "        accepting.set(false);",
        "        thread.interrupt();",
        "    }",
        "",
        "    void awaitStop(Duration timeout) throws InterruptedException {",
        "        thread.join(timeout.toMillis());",
        "    }",
        "",
        "    @Override",
        "    public void run() {",
        "        while (accepting.get() && scheduler.isRunning()) {",
        "            try {",
        "                ScheduledTask task = scheduler.takeDueTask();",
        "                if (task.isCancelled()) {",
        "                    continue;",
        "                }",
        "                try {",
        "                    task.execute();",
        "                    scheduler.complete(task);",
        "                } catch (Exception error) {",
        "                    scheduler.fail(task, error);",
        "                }",
        "            } catch (InterruptedException interrupted) {",
        "                Thread.currentThread().interrupt();",
        "                break;",
        "            }",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.time.Duration;",
        "import java.time.Instant;",
        "import java.util.concurrent.atomic.AtomicInteger;",
        "",
        "public final class Main {",
        "    public static void main(String[] args) throws Exception {",
        "        TaskScheduler scheduler = TaskScheduler.getInstance();",
        "        scheduler.start(2);",
        "",
        "        RetryPolicy retryPolicy = RetryPolicy.exponentialBackoff(3, Duration.ofMillis(100), 2.0, Duration.ofSeconds(1));",
        "        AtomicInteger invoiceAttempts = new AtomicInteger(0);",
        "",
        "        scheduler.scheduleOnce(\"send-invoice\", () -> {",
        "            int attempt = invoiceAttempts.incrementAndGet();",
        "            System.out.println(\"send-invoice attempt \" + attempt);",
        "            if (attempt < 2) {",
        "                throw new RuntimeException(\"temporary email outage\");",
        "            }",
        "        }, Duration.ofMillis(100), retryPolicy);",
        "",
        "        scheduler.scheduleRecurring(\"heartbeat\", () -> {",
        "            System.out.println(\"heartbeat at \" + Instant.now());",
        "        }, Duration.ofMillis(50), Duration.ofMillis(250), RetryPolicy.noRetries());",
        "",
        "        Thread.sleep(900);",
        "        scheduler.cancel(\"heartbeat\");",
        "        Thread.sleep(300);",
        "        scheduler.shutdown();",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Task",
      detailMD:
        "Minimal command interface. Any business action can be represented as **execute**, which keeps the scheduler independent of concrete task types.",
    },
    {
      className: "ScheduledTask",
      detailMD:
        "Queue element and task state holder. It implements **Delayed** for priority ordering, tracks failure attempts atomically, stores optional recurrence interval, and exposes cancellation as an atomic flag.",
    },
    {
      className: "RetryPolicy",
      detailMD:
        "Strategy interface plus three concrete policies: no retry, fixed delay, and exponential backoff. It returns an optional delay, which makes retry exhaustion explicit.",
    },
    {
      className: "TaskScheduler",
      detailMD:
        "Singleton aggregate root. It owns the **DelayQueue**, active task map, worker list, lifecycle lock, and scheduling lock. Public methods schedule, cancel, start, and shut down safely.",
    },
    {
      className: "Worker",
      detailMD:
        "Consumer runnable. It blocks on **take**, executes due tasks, catches failures, and delegates completion or failure handling back to the scheduler.",
    },
    {
      className: "Main",
      detailMD:
        "Small demo that starts two workers, schedules a retryable one-time task, schedules a recurring heartbeat, cancels it, and shuts the scheduler down.",
    },
  ],

  dryRun: {
    inputMD:
      "Workers: 2. Tasks: **email** one-time at T+100ms with exponential backoff and one planned failure; **heartbeat** recurring first at T+50ms then every 250ms; cancel **heartbeat** at about T+900ms.",
    columns: ["Step", "Actor", "Queue head", "Task state", "Result"],
    rows: [
      ["1", "Client schedules heartbeat", "heartbeat @ T+50ms", "active", "Worker blocks until delay reaches zero"],
      ["2", "Worker runs heartbeat", "email @ T+100ms", "heartbeat success", "Heartbeat requeued for T+300ms"],
      ["3", "Worker runs email", "heartbeat @ T+300ms", "email failure count 1", "RetryPolicy returns 100ms backoff"],
      ["4", "Worker retries email", "heartbeat @ T+300ms", "email success", "One-time email is removed from active map"],
      ["5", "Client cancels heartbeat", "none", "heartbeat cancelled", "Queue entry removed and future recurring runs stop"],
    ],
    narrativeMD:
      "The important state transition is step 3: failure does not escape the worker thread. The scheduler asks the strategy for a delay, updates the same **ScheduledTask** next-run time, and reoffers it under the scheduling lock.",
  },

  complexity: [
    {
      operation: "scheduleOnce / scheduleRecurring",
      time: "O(log n)",
      space: "O(1)",
      note: "DelayQueue insertion is backed by a priority heap, and the active map insert is expected O(1).",
    },
    {
      operation: "worker take due task",
      time: "O(log n) plus task runtime",
      space: "O(1)",
      note: "The queue blocks until the earliest item is due, then removes it from the heap.",
    },
    {
      operation: "retry or recurring requeue",
      time: "O(log n)",
      space: "O(1)",
      note: "The worker updates next-run time and offers the same task back to the DelayQueue.",
    },
    {
      operation: "cancel",
      time: "O(n)",
      space: "O(1)",
      note: "Map removal is expected O(1), but removing an arbitrary item from DelayQueue scans the heap.",
    },
    {
      operation: "pendingTaskIds",
      time: "O(n)",
      space: "O(n)",
      note: "Creates a stable copy of active ids for callers.",
    },
  ],
  complexityNotesMD:
    "The hot path is queue insertion and removal, both O(log n). Cancellation is the tradeoff: arbitrary heap removal is O(n), which is acceptable for interview scale but can be optimized with tombstones or an indexed heap.",

  extensibility: [
    {
      label: "Cron schedules",
      detailMD:
        "Introduce a **SchedulePolicy** that computes the next run time after each success. Fixed interval and cron become strategies instead of fields on **ScheduledTask**.",
    },
    {
      label: "Persistent tasks",
      detailMD:
        "Add a **TaskRepository** to persist id, payload, next-run time, retry state, and cancellation status. Scheduler startup reloads due and future tasks.",
    },
    {
      label: "Task categories",
      detailMD:
        "Use multiple queues or worker pools per category such as email, billing, and reports. This prevents slow report work from starving urgent notifications.",
    },
    {
      label: "Distributed execution",
      detailMD:
        "Move ownership to a database lease or distributed lock so only one scheduler instance claims a due task. The local worker model stays the same after claiming.",
    },
  ],

  alternativeDesigns: [
    {
      name: "ExecutorService plus ScheduledExecutorService",
      detailMD:
        "Use JDK executors directly: a scheduled executor triggers tasks and a separate executor handles actual work.",
      tradeoffsMD:
        "Fast to build and production-tested, but it hides the priority queue, retry, and cancellation internals that the interview wants you to model.",
    },
    {
      name: "Database-backed polling scheduler",
      detailMD:
        "Store tasks in a database table ordered by next-run time, and have workers claim rows with leases.",
      tradeoffsMD:
        "Survives restarts and scales across nodes, but introduces polling interval tradeoffs, transaction isolation, and operational complexity.",
    },
    {
      name: "Hashed wheel timer",
      detailMD:
        "Bucket tasks by time slots rather than maintaining a strict heap. Workers scan the current slot as time advances.",
      tradeoffsMD:
        "Excellent for very large timer counts and coarse precision, but harder to explain and less exact for arbitrary run times.",
    },
  ],

  commonMistakes: [
    "Using a normal **PriorityQueue** without synchronization, causing producers and workers to corrupt heap state.",
    "Polling the queue every few milliseconds instead of using a blocking queue that wakes only when work is due.",
    "Letting an exception escape the worker loop, silently killing a worker thread after one bad task.",
    "Requeueing a recurring task without checking whether it was cancelled while executing.",
    "Hard-coding exponential backoff in the worker instead of isolating it behind **RetryPolicy**.",
    "Rescheduling recurring work before execution finishes, which can overlap the same task with itself.",
    "Forgetting that arbitrary cancellation from a heap-backed queue is not O(log n) unless an index is maintained.",
  ],

  followUps: [
    {
      question: "How would you add cron expressions?",
      answerMD:
        "Replace the fixed **interval** field with a **SchedulePolicy** interface. After each success, the scheduler asks the policy for the next run time. Cron, fixed interval, and one-time schedules become separate strategies.",
    },
    {
      question: "How do you prevent one slow task type from starving others?",
      answerMD:
        "Partition by task category with separate queues and worker pools, or add priority classes. The core producer-consumer loop remains the same but capacity is isolated.",
    },
    {
      question: "How would cancellation work for a task currently executing?",
      answerMD:
        "The scheduler marks it cancelled and removes it from the active map. The running command may finish, but completion handling sees the cancelled flag and will not retry or requeue it.",
    },
    {
      question: "How do you make this scheduler durable?",
      answerMD:
        "Persist task state and next-run time in a repository. On startup, reload active tasks into the DelayQueue; on complete, retry, cancel, and requeue, update the repository in the same transaction boundary.",
    },
    {
      question: "What if two scheduler instances run at the same time?",
      answerMD:
        "Use a lease or row-level claim in a shared store. A worker first atomically claims the due task, then executes it. If the worker dies, the lease expires and another instance can retry.",
    },
  ],

  productionConsiderations: [
    {
      label: "Clock control",
      detailMD:
        "Inject a clock instead of calling **Instant.now** directly. This makes tests deterministic and allows time skew handling in production.",
    },
    {
      label: "Task payloads and idempotency",
      detailMD:
        "Real tasks need payloads, idempotency keys, and deduplication so retrying after a crash does not double-charge or double-send.",
    },
    {
      label: "Observability",
      detailMD:
        "Track scheduled count, due lag, execution latency, failure count, retry count, queue size, worker utilization, and cancellation rate.",
    },
    {
      label: "Graceful shutdown",
      detailMD:
        "Stop accepting new tasks, interrupt blocked workers, allow in-flight tasks a deadline, then persist or requeue unfinished work.",
    },
    {
      label: "Poison tasks",
      detailMD:
        "After retry exhaustion, move failed tasks to a dead-letter store with error details instead of simply dropping them.",
    },
  ],

  interviewNotes: [
    "Did the candidate choose a thread-safe priority blocking queue instead of hand-rolled sleep loops?",
    "Can they explain the producer-consumer relationship between clients, queue, and workers?",
    "Did they isolate retry policy from worker orchestration using Strategy?",
    "Can they reason about cancellation racing with task completion and requeue?",
    "Did they discuss one-time versus recurring semantics clearly, especially no overlap for the same recurring task?",
    "Can they extend the design toward durability and distributed leases without rewriting the core worker model?",
  ],

  quiz: [
    {
      question: "Why is **DelayQueue** a good fit for this design?",
      options: [
        "It is a thread-safe blocking queue that releases the earliest due task first",
        "It guarantees exactly-once execution across multiple machines",
        "It makes every cancellation O(log n)",
        "It automatically retries failed tasks",
      ],
      answerIndex: 0,
      explanationMD:
        "**DelayQueue** combines priority ordering by delay with blocking **take**, so workers sleep efficiently until a task is due.",
    },
    {
      question: "Which pattern is represented by the **Task** interface?",
      options: [
        "Observer",
        "Command",
        "Adapter",
        "Composite",
      ],
      answerIndex: 1,
      explanationMD:
        "A task is an executable command object. The scheduler treats all concrete work uniformly through **execute**.",
    },
    {
      question: "What should happen when a one-time task succeeds?",
      options: [
        "It should be requeued with the same delay",
        "It should remain in the active map forever",
        "It should be removed from active tracking",
        "It should retry once to confirm success",
      ],
      answerIndex: 2,
      explanationMD:
        "A one-time task is complete after success, so the scheduler removes it. Only recurring tasks are requeued.",
    },
    {
      question: "Why does cancellation need to coordinate with requeue logic?",
      options: [
        "Because Java cannot remove objects from a queue",
        "Because a task may finish while another thread cancels it",
        "Because retries require a new worker thread",
        "Because recurring tasks cannot have ids",
      ],
      answerIndex: 1,
      explanationMD:
        "Without coordination, a worker could reoffer a task just after another producer cancelled it. The scheduling lock makes that decision atomic.",
    },
    {
      question: "What is the main benefit of **RetryPolicy**?",
      options: [
        "It makes task execution faster",
        "It removes the need for worker threads",
        "It lets retry behavior vary without changing the worker loop",
        "It guarantees that all failed tasks eventually succeed",
      ],
      answerIndex: 2,
      explanationMD:
        "Retry is policy, not orchestration. Strategy keeps fixed delay, exponential backoff, and no-retry decisions out of the worker.",
    },
  ],

  practiceVariants: [
    {
      title: "Add cron-based scheduling",
      detailMD:
        "Introduce a schedule strategy that computes the next fire time from a cron expression, then reuse the existing worker and retry flow.",
      difficulty: "Advanced",
    },
    {
      title: "Persist tasks across restart",
      detailMD:
        "Add a repository for active tasks and retry state. On startup, reload tasks into the queue and ensure cancellation updates are durable.",
      difficulty: "Advanced",
    },
    {
      title: "Add task priorities within the same due time",
      detailMD:
        "Extend **ScheduledTask.compareTo** so tasks due at the same instant are ordered by priority, then creation sequence for stability.",
      difficulty: "Intermediate",
    },
  ],

  flashcards: [
    {
      front: "What is the producer-consumer boundary in this scheduler?",
      back: "Clients produce **ScheduledTask** objects into the **DelayQueue**; workers consume due tasks with blocking **take**.",
    },
    {
      front: "Which class owns retry decisions?",
      back: "**RetryPolicy** decides the next delay or retry exhaustion; **TaskScheduler** applies that decision by requeueing or removing the task.",
    },
    {
      front: "Why does **ScheduledTask** implement **Delayed**?",
      back: "So **DelayQueue** can order tasks by next-run time and release only tasks whose delay has expired.",
    },
    {
      front: "What happens when a recurring task succeeds?",
      back: "Its failure count resets and its **nextRunAt** becomes **now plus interval**, then it is requeued.",
    },
    {
      front: "What is the cancellation invariant?",
      back: "Once a task is cancelled, it must not be retried or requeued, even if cancellation races with execution completion.",
    },
    {
      front: "Why use a Singleton in the sample?",
      back: "The process should have one owner for the queue and worker pool; **TaskScheduler.getInstance** makes that ownership explicit for the interview model.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Task command; ScheduledTask queue item; RetryPolicy strategy; TaskScheduler singleton facade; Worker consumer.",
    "",
    "**Queue:** DelayQueue is a thread-safe BlockingQueue ordered by ScheduledTask.getDelay, so workers block until the earliest task is due.",
    "",
    "**Flows:** schedule = validate and offer; execute = worker take then run; success = remove or requeue interval; failure = ask RetryPolicy then retry or remove; cancel = mark cancelled and remove.",
    "",
    "**Patterns:** Command for Task, Strategy for RetryPolicy, Producer-Consumer for clients and workers, Singleton for the scheduler owner.",
    "",
    "**Concurrency:** DelayQueue handles blocking priority order; ConcurrentHashMap tracks active ids; schedulingLock protects cancel versus retry or recurring requeue.",
    "",
    "**Complexity:** schedule O(log n), take O(log n) plus task runtime, requeue O(log n), cancel O(n), pending ids O(n).",
    "",
    "**Extensions:** cron schedule strategy, persistence repository, category-specific worker pools, distributed leases, dead-letter failed tasks.",
  ].join("\n"),

  references: [
    {
      title: "Java Platform Docs — DelayQueue",
      kind: "Docs",
      url: "https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/DelayQueue.html",
      author: "Oracle",
    },
    {
      title: "Java Concurrency in Practice",
      kind: "Book",
      author: "Brian Goetz et al.",
    },
    {
      title: "Refactoring Guru — Command Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/command",
    },
    {
      title: "Refactoring Guru — Strategy Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/strategy",
    },
  ],

  relatedProblems: [
    { slug: "message-queue", note: "Shared producer-consumer thinking, blocking queues, and worker delivery semantics." },
    { slug: "concurrency-and-multithreading", note: "Thread safety, locks, blocking queues, and worker lifecycle fundamentals." },
    { slug: "notification-system", note: "Notifications often need delayed delivery, retries, cancellation, and dead-letter handling." },
  ],
};
