import type { LLDProblemContent } from "../types";

/**
 * Exemplar LLD problem — Design a Text Editor.
 *
 * Fresh Java implementation focused on Command + Memento undo/redo, clipboard
 * operations, observer notifications, and flyweight character formatting.
 */
export const textEditor: LLDProblemContent = {
  slug: "text-editor",

  statementMD: [
    "Design the object model for a **single-user text editor** that supports a mutable document buffer, a cursor, insert/delete operations, clipboard commands, and undo/redo.",
    "",
    "The core interview challenge is not drawing pixels. It is designing a safe editing core where every mutating user action is encapsulated as a command, the document can restore a previous snapshot, and undo/redo stacks remain correct even as users type, delete, cut, paste, and format text.",
  ].join("\n"),

  businessContextMD: [
    "Text editors power IDEs, note apps, ticket systems, and collaborative documents. A small editor exposes a surprisingly rich LLD surface: mutation history, cursor semantics, clipboard behavior, formatting metadata, and change notifications.",
    "",
    "Interviewers use this problem to see whether you can separate the document model from the application shell, choose the right behavioral patterns, and protect undo/redo invariants. A strong answer makes each edit reversible, clears redo on new edits, and keeps memory growth under control.",
  ].join("\n"),

  functionalRequirements: [
    "Maintain a mutable document buffer and a cursor position between 0 and the document length.",
    "Support inserting text at the cursor and advancing the cursor after the inserted text.",
    "Support deleting text from the cursor and keeping the cursor at the deletion point.",
    "Support cursor movement by absolute position with bounds validation.",
    "Support undo and redo for mutating operations using two stacks.",
    "Support clipboard operations: copy a range, cut from the cursor, and paste at the cursor.",
    "Allow character formatting metadata to be attached without duplicating repeated style objects.",
    "Notify interested listeners after document changes so UI widgets, autosave, or metrics can react.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Correct undo/redo semantics",
      detailMD:
        "Every mutating command must capture enough state to undo itself. A new user edit after undo must clear the redo stack so history stays linear and predictable.",
    },
    {
      label: "Fast interactive editing",
      detailMD:
        "Small documents can use a simple buffer, but the design should admit a gap buffer, rope, or piece table for production-scale documents without changing command APIs.",
    },
    {
      label: "Memory discipline",
      detailMD:
        "Snapshots and style metadata can grow quickly. The base design snapshots the document for clarity and uses flyweight styles to avoid repeated formatting objects.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New commands such as replace, move line, indent, or apply format should implement the same **Command** interface and plug into the same history manager.",
    },
    {
      label: "Separation of concerns",
      detailMD:
        "The document owns text and cursor invariants; commands own reversible operations; the editor orchestrates stacks and clipboard; observers are boundary notifications.",
    },
  ],

  requirementClarification: [
    {
      question: "Is this a single-user or collaborative editor?",
      answerMD:
        "Assume single-user for the base design. Collaboration is a major extension that needs operational transforms or CRDTs and a different conflict model.",
    },
    {
      question: "Do undo and redo cover cursor movement and copy?",
      answerMD:
        "Only mutating operations are recorded in the base design: insert, delete, cut, and paste. Cursor movement and copy update local state but do not enter the undo stack.",
    },
    {
      question: "Should cut and paste be first-class commands?",
      answerMD:
        "Cut is modelled as clipboard assignment followed by a delete command; paste is an insert command using clipboard content. The mutating document part remains command-driven.",
    },
    {
      question: "How rich is formatting?",
      answerMD:
        "Use a lightweight **CharacterStyle** object for font, size, bold, and italic. The editor can later add paragraph styles or ranges without changing the undo/redo contract.",
    },
    {
      question: "Do snapshots need to be full copies?",
      answerMD:
        "Full snapshots are acceptable for the interview because they make Memento easy to reason about. Production editors often switch to inverse operations, piece tables, or compressed history.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class TextEditor {",
    "        -Document document",
    "        -Deque~Command~ undoStack",
    "        -Deque~Command~ redoStack",
    "        -String clipboard",
    "        -List~EditorListener~ listeners",
    "        +type(String) void",
    "        +delete(int) void",
    "        +cut(int) void",
    "        +copy(int, int) String",
    "        +paste() void",
    "        +undo() boolean",
    "        +redo() boolean",
    "    }",
    "    class Document {",
    "        -StringBuilder buffer",
    "        -int cursor",
    "        -List~StyleSpan~ styleSpans",
    "        +insert(String, CharacterStyle) void",
    "        +delete(int) String",
    "        +moveCursor(int) void",
    "        +save() DocumentMemento",
    "        +restore(DocumentMemento) void",
    "    }",
    "    class Command {",
    "        <<interface>>",
    "        +execute() void",
    "        +undo() void",
    "        +name() String",
    "    }",
    "    class InsertCommand {",
    "        -Document document",
    "        -String text",
    "        -CharacterStyle style",
    "        -DocumentMemento before",
    "    }",
    "    class DeleteCommand {",
    "        -Document document",
    "        -int length",
    "        -String removedText",
    "        -DocumentMemento before",
    "    }",
    "    class DocumentMemento {",
    "        -String text",
    "        -int cursor",
    "        -List~StyleSpan~ styleSpans",
    "    }",
    "    class CharacterStyle {",
    "        -Map~String,CharacterStyle~ CACHE",
    "        -String font",
    "        -int size",
    "        -boolean bold",
    "        -boolean italic",
    "        +of(String, int, boolean, boolean) CharacterStyle",
    "    }",
    "    class EditorListener {",
    "        <<interface>>",
    "        +onChange(String, String, int) void",
    "    }",
    "    TextEditor o-- Document",
    "    TextEditor o-- Command",
    "    TextEditor ..> EditorListener",
    "    Document ..> DocumentMemento",
    "    Document o-- CharacterStyle",
    "    Command <|.. InsertCommand",
    "    Command <|.. DeleteCommand",
  ].join("\n"),
  classDiagramCaptionMD:
    "The editor shell owns orchestration: execute command, push undo stack, clear redo stack, and notify observers. The document owns the buffer, cursor, and memento snapshots.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Editor as TextEditor",
    "    participant Cmd as InsertCommand",
    "    participant Doc as Document",
    "    participant UI as EditorListener",
    "    User->>Editor: type(text)",
    "    Editor->>Cmd: new InsertCommand(document, text, style)",
    "    Editor->>Cmd: execute()",
    "    Cmd->>Doc: save()",
    "    Doc-->>Cmd: memento",
    "    Cmd->>Doc: insert(text, style)",
    "    Editor->>Editor: push undo, clear redo",
    "    Editor->>UI: onChange(action, text, cursor)",
    "    Note over User,Editor: later",
    "    User->>Editor: undo()",
    "    Editor->>Cmd: undo()",
    "    Cmd->>Doc: restore(memento)",
    "    Editor->>Editor: move command to redo",
    "    Editor->>UI: onChange(undo, text, cursor)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "Undo is command-driven but state restoration is document-driven. The command asks the document for a memento before executing, then restores that memento when undone.",

  entities: [
    {
      name: "Document",
      responsibilityMD:
        "The editable aggregate. Owns the text buffer, cursor bounds, range operations, formatting spans, and the private memento used to restore a previous state.",
      attributes: ["buffer", "cursor", "styleSpans"],
    },
    {
      name: "TextEditor",
      responsibilityMD:
        "Application facade over the editing core. Converts user actions into commands, manages undo/redo stacks, stores clipboard text, and notifies observers after changes.",
      attributes: ["document", "undoStack", "redoStack", "clipboard", "listeners"],
    },
    {
      name: "Command",
      responsibilityMD:
        "Common interface for reversible mutations. Every edit supports **execute**, **undo**, and a human-readable **name** for history displays.",
      attributes: ["execute", "undo", "name"],
    },
    {
      name: "InsertCommand",
      responsibilityMD:
        "Encapsulates inserting text at the current cursor with a style. It saves a document memento before the mutation and restores it on undo.",
      attributes: ["document", "text", "style", "before"],
    },
    {
      name: "DeleteCommand",
      responsibilityMD:
        "Encapsulates deleting text from the current cursor. It captures the pre-delete memento and remembers the removed text for diagnostics or command history.",
      attributes: ["document", "length", "removedText", "before"],
    },
    {
      name: "CharacterStyle",
      responsibilityMD:
        "Immutable flyweight for repeated formatting attributes. Identical font, size, bold, and italic combinations are shared through a cache.",
      attributes: ["font", "size", "bold", "italic", "cache"],
    },
    {
      name: "EditorListener",
      responsibilityMD:
        "Observer interface for UI, autosave, status bar, or telemetry subscribers that need to react whenever editor-visible state changes.",
      attributes: ["onChange(action, text, cursor)"],
    },
    {
      name: "Clipboard",
      responsibilityMD:
        "A small editor-owned text slot. Copy updates it without history; cut updates it and performs a delete command; paste inserts its content through an insert command.",
      attributes: ["clipboard"],
    },
  ],

  patternsUsed: [
    {
      name: "Command",
      whyMD:
        "Every mutating operation is a **Command** object with **execute** and **undo**. The editor history stores command objects, not ad hoc lambdas or switch cases.",
    },
    {
      name: "Memento",
      whyMD:
        "**Document.save** returns an opaque snapshot of text, cursor, and styles. Commands keep the snapshot but cannot mutate its internals, preserving document encapsulation.",
    },
    {
      name: "Flyweight",
      whyMD:
        "**CharacterStyle.of** shares immutable formatting objects for repeated style combinations, so thousands of characters can reference the same style instance.",
    },
    {
      name: "Observer",
      whyMD:
        "**EditorListener** decouples the editing core from UI refresh, autosave, analytics, or status-bar updates. Subscribers react to changes without becoming part of command execution.",
    },
  ],

  designSteps: [
    {
      title: "Define the document as the owner of text and cursor invariants",
      detailMD:
        "Keep buffer mutation in **Document**. It validates cursor positions, slices ranges, inserts at the cursor, deletes from the cursor, and never exposes the mutable buffer directly.",
      code: [
        "public void moveCursor(int position) {",
        "    if (position < 0 || position > buffer.length()) {",
        "        throw new IllegalArgumentException(\"cursor out of bounds\");",
        "    }",
        "    cursor = position;",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent each mutation as a command",
      detailMD:
        "A command object captures the target document and the operation parameters. The editor does not need to know whether the command inserts, deletes, formats, or replaces text.",
      code: [
        "public interface Command {",
        "    void execute();",
        "    void undo();",
        "    String name();",
        "}",
      ].join("\n"),
    },
    {
      title: "Use mementos for simple and reliable undo",
      detailMD:
        "Before executing, each command asks **Document** for a memento. Undo restores that snapshot. This is easy to explain and keeps command code small.",
      code: [
        "public void execute() {",
        "    before = document.save();",
        "    document.insert(text, style);",
        "}",
        "",
        "public void undo() {",
        "    document.restore(before);",
        "}",
      ].join("\n"),
    },
    {
      title: "Centralize history updates in the editor",
      detailMD:
        "**TextEditor** is the only class that pushes undo, pushes redo, or clears redo. This prevents each command from duplicating fragile stack logic.",
    },
    {
      title: "Make clipboard operations reuse commands",
      detailMD:
        "**copy** only stores text. **cut** stores text then executes a delete command. **paste** executes an insert command. This keeps history behavior consistent with typing and deleting.",
    },
    {
      title: "Share repeated style metadata with a flyweight",
      detailMD:
        "Formatting metadata is immutable and cacheable. Multiple spans can point at the same **CharacterStyle** instance instead of storing repeated font and weight fields per character.",
      code: [
        "public static CharacterStyle of(String font, int size, boolean bold, boolean italic) {",
        "    String key = font + \"|\" + size + \"|\" + bold + \"|\" + italic;",
        "    return CACHE.computeIfAbsent(key, ignored -> new CharacterStyle(font, size, bold, italic));",
        "}",
      ].join("\n"),
    },
    {
      title: "Notify observers after visible state changes",
      detailMD:
        "Observers are called after successful mutations, undo, redo, cursor movement, copy, and cut. The editor sends action, text, and cursor so UI components can refresh without querying internals.",
    },
  ],

  implementation: [
    {
      filename: "CharacterStyle.java",
      language: "java",
      content: [
        "import java.util.Map;",
        "import java.util.Objects;",
        "import java.util.concurrent.ConcurrentHashMap;",
        "",
        "public final class CharacterStyle {",
        "    private static final Map<String, CharacterStyle> CACHE = new ConcurrentHashMap<>();",
        "    public static final CharacterStyle PLAIN = of(\"Inter\", 14, false, false);",
        "",
        "    private final String font;",
        "    private final int size;",
        "    private final boolean bold;",
        "    private final boolean italic;",
        "",
        "    private CharacterStyle(String font, int size, boolean bold, boolean italic) {",
        "        this.font = font;",
        "        this.size = size;",
        "        this.bold = bold;",
        "        this.italic = italic;",
        "    }",
        "",
        "    public static CharacterStyle of(String font, int size, boolean bold, boolean italic) {",
        "        String normalizedFont = Objects.requireNonNull(font, \"font\").trim();",
        "        if (normalizedFont.isEmpty()) {",
        "            throw new IllegalArgumentException(\"font must not be blank\");",
        "        }",
        "        if (size <= 0) {",
        "            throw new IllegalArgumentException(\"size must be positive\");",
        "        }",
        "",
        "        String key = normalizedFont + \"|\" + size + \"|\" + bold + \"|\" + italic;",
        "        return CACHE.computeIfAbsent(key, ignored -> new CharacterStyle(normalizedFont, size, bold, italic));",
        "    }",
        "",
        "    public String font() {",
        "        return font;",
        "    }",
        "",
        "    public int size() {",
        "        return size;",
        "    }",
        "",
        "    public boolean bold() {",
        "        return bold;",
        "    }",
        "",
        "    public boolean italic() {",
        "        return italic;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return font + \" \" + size + (bold ? \" bold\" : \"\") + (italic ? \" italic\" : \"\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Document.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public class Document {",
        "    private final StringBuilder buffer = new StringBuilder();",
        "    private final List<StyleSpan> styleSpans = new ArrayList<>();",
        "    private int cursor;",
        "",
        "    public int length() {",
        "        return buffer.length();",
        "    }",
        "",
        "    public int getCursor() {",
        "        return cursor;",
        "    }",
        "",
        "    public String getText() {",
        "        return buffer.toString();",
        "    }",
        "",
        "    public void moveCursor(int position) {",
        "        if (position < 0 || position > buffer.length()) {",
        "            throw new IllegalArgumentException(\"cursor out of bounds\");",
        "        }",
        "        cursor = position;",
        "    }",
        "",
        "    public void insert(String text) {",
        "        insert(text, CharacterStyle.PLAIN);",
        "    }",
        "",
        "    public void insert(String text, CharacterStyle style) {",
        "        Objects.requireNonNull(text, \"text\");",
        "        Objects.requireNonNull(style, \"style\");",
        "        if (text.isEmpty()) {",
        "            return;",
        "        }",
        "",
        "        int start = cursor;",
        "        buffer.insert(cursor, text);",
        "        shiftSpans(start, text.length());",
        "        styleSpans.add(new StyleSpan(start, start + text.length(), style));",
        "        cursor += text.length();",
        "    }",
        "",
        "    public String previewDelete(int length) {",
        "        validateLength(length);",
        "        int end = Math.min(cursor + length, buffer.length());",
        "        return buffer.substring(cursor, end);",
        "    }",
        "",
        "    public String delete(int length) {",
        "        String removed = previewDelete(length);",
        "        if (removed.isEmpty()) {",
        "            return removed;",
        "        }",
        "",
        "        buffer.delete(cursor, cursor + removed.length());",
        "        shrinkSpans(cursor, removed.length());",
        "        return removed;",
        "    }",
        "",
        "    public String slice(int start, int length) {",
        "        if (start < 0 || start > buffer.length()) {",
        "            throw new IllegalArgumentException(\"start out of bounds\");",
        "        }",
        "        validateLength(length);",
        "        int end = Math.min(start + length, buffer.length());",
        "        return buffer.substring(start, end);",
        "    }",
        "",
        "    public CharacterStyle styleAt(int index) {",
        "        if (index < 0 || index >= buffer.length()) {",
        "            throw new IllegalArgumentException(\"index out of bounds\");",
        "        }",
        "        for (StyleSpan span : styleSpans) {",
        "            if (span.contains(index)) {",
        "                return span.style;",
        "            }",
        "        }",
        "        return CharacterStyle.PLAIN;",
        "    }",
        "",
        "    public Memento save() {",
        "        return new Memento(buffer.toString(), cursor, copySpans(styleSpans));",
        "    }",
        "",
        "    public void restore(Memento memento) {",
        "        Objects.requireNonNull(memento, \"memento\");",
        "        buffer.setLength(0);",
        "        buffer.append(memento.text);",
        "        cursor = memento.cursor;",
        "        styleSpans.clear();",
        "        styleSpans.addAll(copySpans(memento.styleSpans));",
        "    }",
        "",
        "    private void validateLength(int length) {",
        "        if (length < 0) {",
        "            throw new IllegalArgumentException(\"length must not be negative\");",
        "        }",
        "    }",
        "",
        "    private void shiftSpans(int from, int delta) {",
        "        for (StyleSpan span : styleSpans) {",
        "            if (span.start >= from) {",
        "                span.start += delta;",
        "                span.end += delta;",
        "            } else if (span.end > from) {",
        "                span.end += delta;",
        "            }",
        "        }",
        "    }",
        "",
        "    private void shrinkSpans(int start, int length) {",
        "        int end = start + length;",
        "        List<StyleSpan> updated = new ArrayList<>();",
        "        for (StyleSpan span : styleSpans) {",
        "            if (span.end <= start) {",
        "                updated.add(span.copy());",
        "            } else if (span.start >= end) {",
        "                updated.add(new StyleSpan(span.start - length, span.end - length, span.style));",
        "            } else {",
        "                if (span.start < start) {",
        "                    updated.add(new StyleSpan(span.start, start, span.style));",
        "                }",
        "                if (span.end > end) {",
        "                    updated.add(new StyleSpan(start, span.end - length, span.style));",
        "                }",
        "            }",
        "        }",
        "",
        "        styleSpans.clear();",
        "        for (StyleSpan span : updated) {",
        "            if (span.start < span.end) {",
        "                styleSpans.add(span);",
        "            }",
        "        }",
        "    }",
        "",
        "    private static List<StyleSpan> copySpans(List<StyleSpan> spans) {",
        "        List<StyleSpan> copy = new ArrayList<>();",
        "        for (StyleSpan span : spans) {",
        "            copy.add(span.copy());",
        "        }",
        "        return copy;",
        "    }",
        "",
        "    public static final class Memento {",
        "        private final String text;",
        "        private final int cursor;",
        "        private final List<StyleSpan> styleSpans;",
        "",
        "        private Memento(String text, int cursor, List<StyleSpan> styleSpans) {",
        "            this.text = text;",
        "            this.cursor = cursor;",
        "            this.styleSpans = Collections.unmodifiableList(styleSpans);",
        "        }",
        "    }",
        "",
        "    private static final class StyleSpan {",
        "        private int start;",
        "        private int end;",
        "        private final CharacterStyle style;",
        "",
        "        private StyleSpan(int start, int end, CharacterStyle style) {",
        "            this.start = start;",
        "            this.end = end;",
        "            this.style = style;",
        "        }",
        "",
        "        private boolean contains(int index) {",
        "            return index >= start && index < end;",
        "        }",
        "",
        "        private StyleSpan copy() {",
        "            return new StyleSpan(start, end, style);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Command.java",
      language: "java",
      content: [
        "public interface Command {",
        "    void execute();",
        "    void undo();",
        "    String name();",
        "}",
      ].join("\n"),
    },
    {
      filename: "InsertCommand.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public class InsertCommand implements Command {",
        "    private final Document document;",
        "    private final String text;",
        "    private final CharacterStyle style;",
        "    private Document.Memento before;",
        "",
        "    public InsertCommand(Document document, String text, CharacterStyle style) {",
        "        this.document = Objects.requireNonNull(document, \"document\");",
        "        this.text = Objects.requireNonNull(text, \"text\");",
        "        this.style = Objects.requireNonNull(style, \"style\");",
        "    }",
        "",
        "    @Override",
        "    public void execute() {",
        "        before = document.save();",
        "        document.insert(text, style);",
        "    }",
        "",
        "    @Override",
        "    public void undo() {",
        "        if (before == null) {",
        "            throw new IllegalStateException(\"command was not executed\");",
        "        }",
        "        document.restore(before);",
        "    }",
        "",
        "    @Override",
        "    public String name() {",
        "        return \"insert \" + text.length() + \" chars\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "DeleteCommand.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public class DeleteCommand implements Command {",
        "    private final Document document;",
        "    private final int length;",
        "    private Document.Memento before;",
        "    private String removedText = \"\";",
        "",
        "    public DeleteCommand(Document document, int length) {",
        "        this.document = Objects.requireNonNull(document, \"document\");",
        "        if (length < 0) {",
        "            throw new IllegalArgumentException(\"length must not be negative\");",
        "        }",
        "        this.length = length;",
        "    }",
        "",
        "    @Override",
        "    public void execute() {",
        "        before = document.save();",
        "        removedText = document.delete(length);",
        "    }",
        "",
        "    @Override",
        "    public void undo() {",
        "        if (before == null) {",
        "            throw new IllegalStateException(\"command was not executed\");",
        "        }",
        "        document.restore(before);",
        "    }",
        "",
        "    public String removedText() {",
        "        return removedText;",
        "    }",
        "",
        "    @Override",
        "    public String name() {",
        "        return \"delete \" + length + \" chars\";",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "TextEditor.java",
      language: "java",
      content: [
        "import java.util.ArrayDeque;",
        "import java.util.ArrayList;",
        "import java.util.Deque;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public class TextEditor {",
        "    private final Document document;",
        "    private final Deque<Command> undoStack = new ArrayDeque<>();",
        "    private final Deque<Command> redoStack = new ArrayDeque<>();",
        "    private final List<EditorListener> listeners = new ArrayList<>();",
        "    private String clipboard = \"\";",
        "",
        "    public TextEditor() {",
        "        this(new Document());",
        "    }",
        "",
        "    public TextEditor(Document document) {",
        "        this.document = Objects.requireNonNull(document, \"document\");",
        "    }",
        "",
        "    public void type(String text) {",
        "        type(text, CharacterStyle.PLAIN);",
        "    }",
        "",
        "    public void type(String text, CharacterStyle style) {",
        "        apply(new InsertCommand(document, text, style), \"type\");",
        "    }",
        "",
        "    public void delete(int length) {",
        "        apply(new DeleteCommand(document, length), \"delete\");",
        "    }",
        "",
        "    public void moveCursor(int position) {",
        "        document.moveCursor(position);",
        "        notifyListeners(\"moveCursor\");",
        "    }",
        "",
        "    public String copy(int start, int length) {",
        "        clipboard = document.slice(start, length);",
        "        notifyListeners(\"copy\");",
        "        return clipboard;",
        "    }",
        "",
        "    public void cut(int length) {",
        "        clipboard = document.previewDelete(length);",
        "        apply(new DeleteCommand(document, length), \"cut\");",
        "    }",
        "",
        "    public void paste() {",
        "        if (!clipboard.isEmpty()) {",
        "            apply(new InsertCommand(document, clipboard, CharacterStyle.PLAIN), \"paste\");",
        "        }",
        "    }",
        "",
        "    public boolean undo() {",
        "        if (undoStack.isEmpty()) {",
        "            return false;",
        "        }",
        "        Command command = undoStack.pop();",
        "        command.undo();",
        "        redoStack.push(command);",
        "        notifyListeners(\"undo \" + command.name());",
        "        return true;",
        "    }",
        "",
        "    public boolean redo() {",
        "        if (redoStack.isEmpty()) {",
        "            return false;",
        "        }",
        "        Command command = redoStack.pop();",
        "        command.execute();",
        "        undoStack.push(command);",
        "        notifyListeners(\"redo \" + command.name());",
        "        return true;",
        "    }",
        "",
        "    public String text() {",
        "        return document.getText();",
        "    }",
        "",
        "    public int cursor() {",
        "        return document.getCursor();",
        "    }",
        "",
        "    public void addListener(EditorListener listener) {",
        "        listeners.add(Objects.requireNonNull(listener, \"listener\"));",
        "    }",
        "",
        "    public void removeListener(EditorListener listener) {",
        "        listeners.remove(listener);",
        "    }",
        "",
        "    private void apply(Command command, String action) {",
        "        command.execute();",
        "        undoStack.push(command);",
        "        redoStack.clear();",
        "        notifyListeners(action);",
        "    }",
        "",
        "    private void notifyListeners(String action) {",
        "        String text = document.getText();",
        "        int cursor = document.getCursor();",
        "        for (EditorListener listener : new ArrayList<>(listeners)) {",
        "            listener.onChange(action, text, cursor);",
        "        }",
        "    }",
        "",
        "    @FunctionalInterface",
        "    public interface EditorListener {",
        "        void onChange(String action, String text, int cursor);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        TextEditor editor = new TextEditor();",
        "        editor.addListener((action, text, cursor) ->",
        "                System.out.println(action + \" -> [\" + text + \"] cursor=\" + cursor));",
        "",
        "        editor.type(\"Hello\");",
        "        editor.type(\" world\", CharacterStyle.of(\"Inter\", 14, false, false));",
        "        editor.moveCursor(6);",
        "        editor.delete(5);",
        "        editor.undo();",
        "        editor.copy(6, 5);",
        "        editor.moveCursor(editor.text().length());",
        "        editor.paste();",
        "        editor.undo();",
        "        editor.redo();",
        "",
        "        System.out.println(\"Final: \" + editor.text());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "CharacterStyle",
      detailMD:
        "Immutable flyweight for formatting. The static **of** method normalizes inputs, builds a cache key, and returns a shared instance for repeated font, size, bold, and italic combinations.",
    },
    {
      className: "Document",
      detailMD:
        "Owns the text buffer, cursor, style spans, and nested **Memento**. It exposes safe operations for insert, delete, slice, save, and restore while hiding mutable internals from commands.",
    },
    {
      className: "Command",
      detailMD:
        "The reversible mutation contract. The editor can execute, undo, redo, and label commands without knowing their concrete operation type.",
    },
    {
      className: "InsertCommand",
      detailMD:
        "Stores target document, inserted text, chosen style, and the pre-execution memento. **execute** inserts at the current cursor; **undo** restores the saved snapshot.",
    },
    {
      className: "DeleteCommand",
      detailMD:
        "Stores target document and delete length. It saves the document memento before deletion, removes text from the cursor, and restores the memento on undo.",
    },
    {
      className: "TextEditor",
      detailMD:
        "Facade and history manager. It translates user actions to commands, maintains undo/redo stacks, clears redo after new edits, manages clipboard text, and notifies listeners.",
    },
    {
      className: "Main",
      detailMD:
        "Runnable demo that types text, deletes a word, undoes, copies, pastes, undoes again, and redoes. The listener output makes command flow and cursor movement visible.",
    },
  ],

  dryRun: {
    inputMD:
      "Initial document is empty. Actions: type **Hello**, type ** world**, move cursor to 6, delete 5 characters, undo, copy **world**, move to end, paste, undo, redo.",
    columns: ["Step", "Action", "Buffer", "Cursor", "Undo stack", "Redo stack"],
    rows: [
      ["1", "type Hello", "Hello", "5", "[Insert Hello]", "[]"],
      ["2", "type space plus world", "Hello world", "11", "[Insert world, Insert Hello]", "[]"],
      ["3", "move cursor to 6", "Hello world", "6", "[Insert world, Insert Hello]", "[]"],
      ["4", "delete 5", "Hello ", "6", "[Delete world, Insert world, Insert Hello]", "[]"],
      ["5", "undo", "Hello world", "6", "[Insert world, Insert Hello]", "[Delete world]"],
      ["6", "copy world and paste at end", "Hello worldworld", "16", "[Paste world, Insert world, Insert Hello]", "[]"],
      ["7", "undo then redo paste", "Hello worldworld", "16", "[Paste world, Insert world, Insert Hello]", "[]"],
    ],
    narrativeMD:
      "Step 5 moves the delete command from undo to redo after restoring the document memento. Step 6 clears redo because paste is a new edit, then records paste as another insert command.",
  },

  complexity: [
    {
      operation: "insert",
      time: "O(n + s)",
      space: "O(n)",
      note: "StringBuilder may shift text after the cursor; the memento stores a document snapshot. s is the number of style spans adjusted.",
    },
    {
      operation: "delete",
      time: "O(n + s)",
      space: "O(n)",
      note: "Deletion shifts remaining text and stores the pre-delete memento for undo.",
    },
    {
      operation: "copy",
      time: "O(k)",
      space: "O(k)",
      note: "Copies k characters into the clipboard and does not affect undo history.",
    },
    {
      operation: "cut",
      time: "O(n + k + s)",
      space: "O(n + k)",
      note: "Copies k characters to the clipboard and executes a delete command with a memento.",
    },
    {
      operation: "paste",
      time: "O(n + k + s)",
      space: "O(n)",
      note: "Executes an insert command for k clipboard characters and clears redo.",
    },
    {
      operation: "undo / redo",
      time: "O(n + s)",
      space: "O(1) extra",
      note: "Restores a saved memento or re-executes a command; the command objects already hold history state.",
    },
  ],
  complexityNotesMD:
    "The reference implementation favors clarity over optimal text editing data structures. In production, the **Document** internals can change to a gap buffer, rope, or piece table while **Command** and **TextEditor** remain stable.",

  extensibility: [
    {
      label: "Replace command",
      detailMD:
        "Implement **ReplaceCommand** as delete plus insert behind one memento so undo restores the exact prior state in a single history step.",
    },
    {
      label: "Format command",
      detailMD:
        "Add **ApplyStyleCommand** that changes style spans over a range. It can reuse **CharacterStyle** flyweights and the same document memento mechanism.",
    },
    {
      label: "Macro command",
      detailMD:
        "Introduce a composite command that groups multiple commands and exposes one **execute** and one **undo** operation for recorded macros.",
    },
    {
      label: "Alternative buffer",
      detailMD:
        "Replace **StringBuilder** with a gap buffer, piece table, or rope. Commands target **Document** methods, so callers do not change.",
    },
    {
      label: "Persistent history",
      detailMD:
        "Serialize command metadata or memento deltas so an editor session can recover unsaved history after a crash.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Inverse-operation commands",
      detailMD:
        "Instead of full document mementos, each command records the exact inverse: inserted range for insert, removed text for delete, and old styles for formatting.",
      tradeoffsMD:
        "Uses less memory for large documents but makes each command harder to implement and easier to get wrong around cursor and style edge cases.",
    },
    {
      name: "Piece table document",
      detailMD:
        "Store original text and append-only added text, then represent the document as a list of pieces. Inserts and deletes adjust piece descriptors rather than moving a large array.",
      tradeoffsMD:
        "Excellent for editors and undo, but more complex than a StringBuilder model and harder to explain quickly in an LLD interview.",
    },
    {
      name: "Event-sourced history",
      detailMD:
        "Persist every command as an event and rebuild document state by replaying events from an initial snapshot.",
      tradeoffsMD:
        "Great for audit and crash recovery, but replay cost and event versioning add production complexity.",
    },
    {
      name: "UI-driven undo manager",
      detailMD:
        "Let the UI controller manage undo and redo stacks directly while document methods mutate text.",
      tradeoffsMD:
        "Simple at first, but stack rules spread across UI code and domain commands become harder to test in isolation.",
    },
  ],

  commonMistakes: [
    "Letting each button handler mutate the document directly instead of routing mutations through **Command** objects.",
    "Forgetting to clear the redo stack after a new edit following undo.",
    "Recording copy or pure cursor movement in undo history, causing surprising undo behavior.",
    "Exposing the mutable **StringBuilder** or mutable style span list to callers.",
    "Implementing undo as string reinsert/delete only and losing cursor position or formatting state.",
    "Creating a separate formatting object for every character instead of sharing immutable styles.",
    "Not validating cursor and range bounds, leading to hidden index errors in command execution.",
  ],

  followUps: [
    {
      question: "Why use both Command and Memento instead of only one pattern?",
      answerMD:
        "Command captures the user action and history entry. Memento captures document state without exposing internals. Together they keep stack management clean and undo restoration safe.",
    },
    {
      question: "How do you reduce memory usage for very large files?",
      answerMD:
        "Move from full snapshots to inverse operations, deltas, checkpointed mementos, or a piece table. Keep the public **Command** and **Document** APIs stable.",
    },
    {
      question: "What happens to redo after undo followed by typing?",
      answerMD:
        "Redo is cleared. Typing creates a new branch in history, and the simple editor maintains a linear history instead of a branching timeline.",
    },
    {
      question: "How would you support grouped undo for typing a whole word?",
      answerMD:
        "Coalesce adjacent insert commands by time window, cursor adjacency, and style match, or wrap them in a macro command that appears as one undo entry.",
    },
    {
      question: "How would collaborative editing change this design?",
      answerMD:
        "Local command history is no longer enough. You need operation transformation or CRDTs, remote cursors, conflict handling, and per-client undo semantics.",
    },
    {
      question: "Where should autosave live?",
      answerMD:
        "As an observer or subscriber to editor changes. It should not be embedded inside **Command** or **Document**, because persistence is a boundary concern.",
    },
  ],

  productionConsiderations: [
    {
      label: "Large document data structure",
      detailMD:
        "Use a gap buffer for simple local editing, a piece table for persistent undo-friendly storage, or a rope for very large text and fast concatenation.",
    },
    {
      label: "History compaction",
      detailMD:
        "Merge repeated typing, cap history by memory budget, and checkpoint snapshots so undo is responsive without unbounded memory growth.",
    },
    {
      label: "Crash recovery",
      detailMD:
        "Persist dirty buffers and recent commands or deltas periodically. Recovery should restore text, cursor, selection, and enough history for user trust.",
    },
    {
      label: "Threading model",
      detailMD:
        "Keep document mutations on a single editor thread or guard them with a lock. Notify observers carefully so slow subscribers do not block typing.",
    },
    {
      label: "International text",
      detailMD:
        "Java **char** counts UTF-16 code units, not user-visible characters. Production editors need grapheme-aware cursor movement and deletion.",
    },
    {
      label: "Observability",
      detailMD:
        "Measure edit latency, undo depth, autosave failures, and memory usage. These signals catch history leaks and slow document operations early.",
    },
  ],

  interviewNotes: [
    "Does the candidate clearly separate **Document**, **Command**, and **TextEditor** responsibilities?",
    "Do undo and redo stack transitions handle execute, undo, redo, and new edit after undo correctly?",
    "Does the memento restore cursor and formatting as well as text?",
    "Are clipboard actions mapped to commands where they mutate the document?",
    "Can the design evolve to a better buffer structure without rewriting the command layer?",
    "Are pattern names used for real design seams rather than decorative labels?",
  ],

  quiz: [
    {
      question: "Why does **TextEditor** clear the redo stack after a new edit?",
      options: [
        "Because the old redo commands belong to a different future branch",
        "Because redo commands are always invalid Java objects",
        "Because copy must be undone before typing",
        "Because the document buffer cannot contain formatted text",
      ],
      answerIndex: 0,
      explanationMD:
        "After undo, a new edit creates a different linear history. Keeping old redo entries would replay commands against the wrong state.",
    },
    {
      question: "Which responsibility belongs in **Document**?",
      options: [
        "Rendering toolbar buttons",
        "Owning cursor bounds and text mutation invariants",
        "Choosing when to clear redo",
        "Persisting analytics events",
      ],
      answerIndex: 1,
      explanationMD:
        "Document is the domain object for text and cursor state. The editor shell handles history and observers.",
    },
    {
      question: "What does the Memento pattern protect in this design?",
      options: [
        "It lets commands restore document state without exposing mutable internals",
        "It makes all inserts O(1)",
        "It prevents users from copying text",
        "It replaces the need for command objects",
      ],
      answerIndex: 0,
      explanationMD:
        "The command holds an opaque snapshot and asks the document to restore it. It does not inspect or modify the snapshot fields directly.",
    },
    {
      question: "Why is **CharacterStyle** a good flyweight candidate?",
      options: [
        "It is immutable and many characters can share the same formatting values",
        "It changes on every cursor movement",
        "It owns the undo stack",
        "It has to call every observer",
      ],
      answerIndex: 0,
      explanationMD:
        "Flyweight works best for immutable, repeated intrinsic state. Formatting combinations are reused heavily across a document.",
    },
    {
      question: "Which action should normally be recorded in undo history?",
      options: [
        "copy",
        "move cursor",
        "type text",
        "register listener",
      ],
      answerIndex: 2,
      explanationMD:
        "Typing mutates the document. Copy and cursor movement are visible state changes, but they typically should not consume undo history slots.",
    },
  ],

  practiceVariants: [
    {
      title: "Grouped typing undo",
      detailMD:
        "Coalesce repeated character inserts into one undoable command when they happen close together and at adjacent cursor positions.",
      difficulty: "Intermediate",
    },
    {
      title: "Apply formatting command",
      detailMD:
        "Add a command that applies bold or italic to a selected range using **CharacterStyle** flyweights and restores prior style spans on undo.",
      difficulty: "Advanced",
    },
    {
      title: "Piece table implementation",
      detailMD:
        "Replace **StringBuilder** internals with a piece table while preserving **Document**, **Command**, and **TextEditor** public APIs.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What does the undo stack store?",
      back: "Executed **Command** objects. Each command knows how to undo itself, usually by restoring a document memento.",
    },
    {
      front: "When is the redo stack cleared?",
      back: "Immediately after any new mutating edit is executed through **TextEditor.apply**.",
    },
    {
      front: "What does the memento contain?",
      back: "A snapshot of document text, cursor position, and style spans. It is opaque to clients.",
    },
    {
      front: "Why is paste implemented as an insert command?",
      back: "Pasting mutates the document exactly like typing clipboard text, so it should share the same history behavior.",
    },
    {
      front: "What is shared by the Flyweight pattern here?",
      back: "Immutable **CharacterStyle** instances for repeated font, size, bold, and italic combinations.",
    },
    {
      front: "What do observers receive?",
      back: "An action label, the current text, and the cursor position after the editor-visible state changes.",
    },
  ],

  cheatSheetMD: [
    "**Core objects:** Document owns buffer + cursor; TextEditor owns undo/redo + clipboard; Command represents reversible edits; CharacterStyle shares formatting; EditorListener observes changes.",
    "",
    "**Undo flow:** execute command → command saves memento → command mutates document → editor pushes undo → editor clears redo.",
    "",
    "**Redo flow:** pop redo → execute command again → push undo → notify observers.",
    "",
    "**Clipboard:** copy = store range only; cut = store range + delete command; paste = insert command with clipboard text.",
    "",
    "**Patterns:** Command for edit actions; Memento for snapshots; Flyweight for styles; Observer for UI/autosave notifications.",
    "",
    "**Key invariant:** only TextEditor mutates history stacks, and only Document mutates text/cursor internals.",
    "",
    "**Production upgrade:** replace StringBuilder with gap buffer, piece table, or rope without changing command APIs.",
  ].join("\n"),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, and Vlissides",
    },
    {
      title: "Refactoring Guru — Command Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/command",
    },
    {
      title: "Refactoring Guru — Memento Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/memento",
    },
    {
      title: "The Craft of Text Editing",
      kind: "Book",
      author: "Craig A. Finseth",
    },
  ],

  relatedProblems: [
    { slug: "google-docs", note: "Extends editor concepts into collaboration, remote cursors, and conflict resolution." },
    { slug: "file-system", note: "Complements the editor with persistence, hierarchical storage, and file operations." },
    { slug: "jira", note: "Shows how rich text editing appears inside real product workflows such as ticket descriptions and comments." },
  ],
};
