import type { LLDProblemContent } from "../types";

/**
 * Exemplar LLD problem — Design Trello.
 *
 * Authors fresh inline Java focused on Board → List → Card composition,
 * reversible card moves, and activity feed notifications.
 */
export const trello: LLDProblemContent = {
  slug: "trello",

  statementMD: [
    "Design the object model for **Trello**, a Kanban-style collaboration tool.",
    "Users create boards, add ordered lists such as To Do or Done, create cards",
    "inside those lists, attach labels, assign members, add checklist items, and",
    "move cards between lists through drag-drop operations.",
    "",
    "The LLD focus is the **Board → List → Card** ownership chain, how a move is",
    "represented as a reversible command, and how board activity is broadcast to",
    "an activity feed without coupling the domain model to UI code.",
  ].join("\n"),

  businessContextMD: [
    "Trello-style design problems are common at Atlassian and other product",
    "companies because they test practical object modelling. The domain looks",
    "simple, but it forces decisions around aggregate ownership, ordered",
    "collections, card metadata, undoable operations, and collaboration events.",
    "A strong answer keeps cards inside lists, lists inside boards, uses a",
    "Command for move/undo, exposes an Observer seam for feeds and notifications,",
    "and leaves ordering policy pluggable through Strategy.",
  ].join("\n"),

  functionalRequirements: [
    "Create a board with multiple ordered lists or columns.",
    "Create cards inside a list with title, description, labels, assigned members, and checklist items.",
    "Move a card from one list to another at a requested target position.",
    "Undo the last move operation by restoring the card to its original list and position.",
    "Publish activity events when cards are created, moved, or move operations are undone.",
    "Allow observers such as an activity feed, notification service, or audit sink to subscribe to a board.",
    "Keep card insertion policy configurable, for example append by default or prioritize urgent labels.",
    "Expose read-only board, list, and card views so callers cannot corrupt ordering directly.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Consistency of ordered lists",
      detailMD:
        "A card must exist in exactly one list on a board at a time, and move/undo must preserve list order without duplicate card ids.",
    },
    {
      label: "Extensibility",
      detailMD:
        "New card metadata, activity sinks, ordering rules, and future workflow rules should be additive classes or strategies, not edits to every domain object.",
    },
    {
      label: "Low-latency interactions",
      detailMD:
        "Move card should be fast enough for drag-drop UI feedback. The in-memory baseline uses list scans; indexed maps can be added if board size grows.",
    },
    {
      label: "Encapsulation",
      detailMD:
        "Only BoardService and MoveCardCommand mutate list membership. Callers receive unmodifiable views of lists, cards, labels, and checklists.",
    },
    {
      label: "Auditable actions",
      detailMD:
        "Every user-visible mutation should produce an activity event that can later be persisted, indexed, or pushed to subscribers.",
    },
  ],

  requirementClarification: [
    {
      question: "Do we need real-time multi-user collaboration and conflict resolution?",
      answerMD:
        "Not in the base LLD. We model a single process domain with clean events. Real-time synchronization can subscribe to the activity stream later.",
    },
    {
      question: "Should cards have comments, attachments, due dates, and custom fields?",
      answerMD:
        "Represent labels, members, and checklists in the core design. Treat comments, attachments, due dates, and custom fields as extensions on Card.",
    },
    {
      question: "How precise must card ordering be?",
      answerMD:
        "Use integer positions for the interview baseline. Production can switch to fractional ranks or sparse ordering without changing the command boundary.",
    },
    {
      question: "Does undo apply to all operations or only moving cards?",
      answerMD:
        "Implement undo for move because it is the highest-value drag-drop operation. The same Command interface can be generalized for create, archive, and update.",
    },
    {
      question: "Are permissions and board visibility in scope?",
      answerMD:
        "Keep permissions out of the core model. A production BoardService would check access before executing commands, but ownership and movement remain the same.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class Board {",
    "        -String id",
    "        -String name",
    "        -List~BoardList~ lists",
    "        -List~ActivityObserver~ observers",
    "        +addList(BoardList) void",
    "        +findList(String) Optional~BoardList~",
    "        +notifyActivity(ActivityEvent) void",
    "    }",
    "    class BoardList {",
    "        -String id",
    "        -String name",
    "        -List~Card~ cards",
    "        +insertCardAt(Card, int) void",
    "        +removeCard(String) Card",
    "        +indexOf(String) int",
    "    }",
    "    class Card {",
    "        -String id",
    "        -String title",
    "        -List~Label~ labels",
    "        -Set~String~ members",
    "        -List~ChecklistItem~ checklist",
    "        +addLabel(Label) Card",
    "        +assignMember(String) Card",
    "        +addChecklistItem(String) Card",
    "    }",
    "    class Label {",
    "        -String id",
    "        -String name",
    "        -String color",
    "    }",
    "    class MoveCardCommand {",
    "        -Board board",
    "        -String sourceListId",
    "        -String targetListId",
    "        -String cardId",
    "        +execute() void",
    "        +undo() void",
    "    }",
    "    class ActivityObserver {",
    "        <<interface>>",
    "        +onActivity(ActivityEvent) void",
    "    }",
    "    class BoardService {",
    "        -Map~String,Board~ boards",
    "        -CardOrderingStrategy orderingStrategy",
    "        +createBoard(String, String) Board",
    "        +createCard(String, String, Card) Card",
    "        +moveCard(String, String, String, String, int) MoveCardCommand",
    "    }",
    "    class CardOrderingStrategy {",
    "        <<interface>>",
    "        +positionForNewCard(BoardList, Card) int",
    "    }",
    "    Board o-- BoardList",
    "    BoardList o-- Card",
    "    Card o-- Label",
    "    MoveCardCommand --> Board",
    "    Board --> ActivityObserver",
    "    BoardService --> Board",
    "    BoardService ..> CardOrderingStrategy",
  ].join("\n"),
  classDiagramCaptionMD:
    "The aggregate is deliberately simple: Board owns Lists, Lists own Cards, and Cards own metadata. Command, Observer, and Strategy sit around that composition instead of replacing it.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor User",
    "    participant Service as BoardService",
    "    participant Command as MoveCardCommand",
    "    participant Board",
    "    participant Source as BoardList",
    "    participant Target as BoardList",
    "    participant Feed as ActivityObserver",
    "    User->>Service: moveCard(boardId, fromListId, cardId, toListId, position)",
    "    Service->>Command: new command",
    "    Service->>Command: execute()",
    "    Command->>Board: findList(fromListId)",
    "    Command->>Board: findList(toListId)",
    "    Command->>Source: indexOf(cardId)",
    "    Command->>Source: removeCard(cardId)",
    "    Command->>Target: insertCardAt(card, position)",
    "    Command->>Board: notifyActivity(cardMoved)",
    "    Board-->>Feed: onActivity(event)",
    "    Service-->>User: command",
    "    Note over User,Command: user selects undo",
    "    User->>Command: undo()",
    "    Command->>Target: removeCard(cardId)",
    "    Command->>Source: insertCardAt(card, originalPosition)",
    "    Command->>Board: notifyActivity(cardMoveUndone)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The service creates the command, the command owns the move state needed for undo, and observers receive feed entries after the board mutation succeeds.",

  entities: [
    {
      name: "Board",
      responsibilityMD:
        "Aggregate root for a Kanban workspace. Owns ordered lists and board-level observers, and provides list lookup for commands.",
      attributes: ["id", "name", "lists", "observers"],
    },
    {
      name: "BoardList",
      responsibilityMD:
        "A column such as To Do, Doing, or Done. Owns ordered cards and guards card insertion, removal, and duplicate id invariants.",
      attributes: ["id", "name", "cards"],
    },
    {
      name: "Card",
      responsibilityMD:
        "Work item inside exactly one list. Carries title, description, labels, assigned members, and checklist items.",
      attributes: ["id", "title", "description", "labels", "members", "checklist"],
    },
    {
      name: "Label",
      responsibilityMD:
        "Small immutable value object used to tag cards by category, priority, team, or risk.",
      attributes: ["id", "name", "color"],
    },
    {
      name: "MoveCardCommand",
      responsibilityMD:
        "Captures a requested move plus the original list and index. It can execute once and undo by replaying the inverse mutation.",
      attributes: ["board", "sourceListId", "targetListId", "cardId", "originalPosition"],
    },
    {
      name: "ActivityObserver",
      responsibilityMD:
        "Observer seam for activity feed, notifications, audit logs, and websocket broadcasters. The board only calls **onActivity**.",
      attributes: ["onActivity(event)"],
    },
    {
      name: "BoardService",
      responsibilityMD:
        "Application facade around the domain. Creates boards, lists, and cards; builds move commands; and injects the card ordering strategy.",
      attributes: ["boards", "orderingStrategy"],
    },
    {
      name: "CardOrderingStrategy",
      responsibilityMD:
        "Policy interface that decides where newly created cards should be inserted. The default appends; alternatives can prioritize labels.",
      attributes: ["positionForNewCard(list, card)"],
    },
  ],

  patternsUsed: [
    {
      name: "Command",
      whyMD:
        "**MoveCardCommand** turns drag-drop into an object with **execute** and **undo**. It stores the original list and index so reversal is deterministic.",
    },
    {
      name: "Observer",
      whyMD:
        "**ActivityObserver** decouples board mutations from activity feed rendering, notification delivery, and audit persistence.",
    },
    {
      name: "Composite",
      whyMD:
        "The domain is a whole-part hierarchy: **Board** owns **BoardList** children, and each **BoardList** owns **Card** children with metadata. Operations traverse this composition rather than using global card state.",
    },
    {
      name: "Strategy",
      whyMD:
        "**CardOrderingStrategy** lets the service vary card insertion policy. Append, urgent-first, or rank-based ordering can change without rewriting card creation.",
    },
  ],

  designSteps: [
    {
      title: "Start with the ownership chain",
      detailMD:
        "Model the aggregate as **Board → BoardList → Card**. The parent owns child lifetime and exposes read-only views so external callers cannot reorder lists or cards directly.",
      code: [
        "public class Board {",
        "    private final List<BoardList> lists = new ArrayList<>();",
        "",
        "    public void addList(BoardList list) {",
        "        lists.add(Objects.requireNonNull(list));",
        "    }",
        "",
        "    public List<BoardList> getLists() {",
        "        return Collections.unmodifiableList(lists);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Let a list guard card ordering",
      detailMD:
        "**BoardList** owns the ordered card collection. It validates insertion positions, blocks duplicate card ids, and returns a removed card to the command.",
      code: [
        "public void insertCardAt(Card card, int position) {",
        "    if (position < 0 || position > cards.size()) {",
        "        throw new IllegalArgumentException(\"Invalid position\");",
        "    }",
        "    if (findCard(card.getId()).isPresent()) {",
        "        throw new IllegalStateException(\"Duplicate card id\");",
        "    }",
        "    cards.add(position, card);",
        "}",
      ].join("\n"),
    },
    {
      title: "Represent move as a reversible command",
      detailMD:
        "A drag-drop action needs both current intent and prior state. Store source list, target list, card id, target position, original index, and moved card inside **MoveCardCommand**.",
      code: [
        "public void undo() {",
        "    if (!executed) {",
        "        throw new IllegalStateException(\"Command was not executed\");",
        "    }",
        "    targetList.removeCard(cardId);",
        "    sourceList.insertCardAt(movedCard, originalPosition);",
        "    executed = false;",
        "}",
      ].join("\n"),
    },
    {
      title: "Broadcast successful mutations through observers",
      detailMD:
        "Board maintains subscribers and emits an activity event after create, move, or undo succeeds. Feed and notification concerns stay outside the domain mutation.",
    },
    {
      title: "Inject ordering policy",
      detailMD:
        "Card creation asks **CardOrderingStrategy** for the insertion index. The default is append, but an urgent-first strategy can place high-priority cards at the top.",
    },
    {
      title: "Keep service orchestration thin",
      detailMD:
        "**BoardService** checks ids, creates commands, and delegates mutation to domain objects. It does not manually edit raw card arrays outside list methods.",
    },
  ],

  implementation: [
    {
      filename: "Board.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "",
        "public class Board {",
        "    private final String id;",
        "    private final String name;",
        "    private final List<BoardList> lists = new ArrayList<>();",
        "    private final List<ActivityObserver> observers = new ArrayList<>();",
        "",
        "    public Board(String id, String name) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public void addList(BoardList list) {",
        "        Objects.requireNonNull(list, \"list\");",
        "        if (findList(list.getId()).isPresent()) {",
        "            throw new IllegalArgumentException(\"Duplicate list id: \" + list.getId());",
        "        }",
        "        lists.add(list);",
        "    }",
        "",
        "    public List<BoardList> getLists() {",
        "        return Collections.unmodifiableList(lists);",
        "    }",
        "",
        "    public Optional<BoardList> findList(String listId) {",
        "        return lists.stream().filter(list -> list.getId().equals(listId)).findFirst();",
        "    }",
        "",
        "    public void addObserver(ActivityObserver observer) {",
        "        observers.add(Objects.requireNonNull(observer, \"observer\"));",
        "    }",
        "",
        "    public void removeObserver(ActivityObserver observer) {",
        "        observers.remove(observer);",
        "    }",
        "",
        "    public void notifyActivity(ActivityObserver.ActivityEvent event) {",
        "        for (ActivityObserver observer : observers) {",
        "            observer.onActivity(event);",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "BoardList.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.Optional;",
        "",
        "public class BoardList {",
        "    private final String id;",
        "    private final String name;",
        "    private final List<Card> cards = new ArrayList<>();",
        "",
        "    public BoardList(String id, String name) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public List<Card> getCards() {",
        "        return Collections.unmodifiableList(cards);",
        "    }",
        "",
        "    public Optional<Card> findCard(String cardId) {",
        "        return cards.stream().filter(card -> card.getId().equals(cardId)).findFirst();",
        "    }",
        "",
        "    public int indexOf(String cardId) {",
        "        for (int i = 0; i < cards.size(); i++) {",
        "            if (cards.get(i).getId().equals(cardId)) {",
        "                return i;",
        "            }",
        "        }",
        "        throw new IllegalArgumentException(\"Card not found: \" + cardId);",
        "    }",
        "",
        "    public void insertCardAt(Card card, int position) {",
        "        Objects.requireNonNull(card, \"card\");",
        "        if (position < 0 || position > cards.size()) {",
        "            throw new IllegalArgumentException(\"Invalid position: \" + position);",
        "        }",
        "        if (findCard(card.getId()).isPresent()) {",
        "            throw new IllegalStateException(\"Card already exists in this list: \" + card.getId());",
        "        }",
        "        cards.add(position, card);",
        "    }",
        "",
        "    public Card removeCard(String cardId) {",
        "        int index = indexOf(cardId);",
        "        return cards.remove(index);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Card.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.LinkedHashSet;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.Set;",
        "",
        "public class Card {",
        "    private final String id;",
        "    private final String title;",
        "    private String description;",
        "    private final List<Label> labels = new ArrayList<>();",
        "    private final Set<String> members = new LinkedHashSet<>();",
        "    private final List<ChecklistItem> checklist = new ArrayList<>();",
        "",
        "    public Card(String id, String title, String description) {",
        "        this.id = requireText(id, \"id\");",
        "        this.title = requireText(title, \"title\");",
        "        this.description = description == null ? \"\" : description;",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getTitle() {",
        "        return title;",
        "    }",
        "",
        "    public String getDescription() {",
        "        return description;",
        "    }",
        "",
        "    public void setDescription(String description) {",
        "        this.description = description == null ? \"\" : description;",
        "    }",
        "",
        "    public Card addLabel(Label label) {",
        "        labels.add(Objects.requireNonNull(label, \"label\"));",
        "        return this;",
        "    }",
        "",
        "    public Card assignMember(String memberId) {",
        "        members.add(requireText(memberId, \"memberId\"));",
        "        return this;",
        "    }",
        "",
        "    public Card addChecklistItem(String title) {",
        "        checklist.add(new ChecklistItem(title));",
        "        return this;",
        "    }",
        "",
        "    public void completeChecklistItem(int index) {",
        "        checklist.get(index).complete();",
        "    }",
        "",
        "    public List<Label> getLabels() {",
        "        return Collections.unmodifiableList(labels);",
        "    }",
        "",
        "    public Set<String> getMembers() {",
        "        return Collections.unmodifiableSet(members);",
        "    }",
        "",
        "    public List<ChecklistItem> getChecklist() {",
        "        return Collections.unmodifiableList(checklist);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "",
        "    public static final class ChecklistItem {",
        "        private final String title;",
        "        private boolean done;",
        "",
        "        private ChecklistItem(String title) {",
        "            this.title = requireText(title, \"checklist title\");",
        "        }",
        "",
        "        public String getTitle() {",
        "            return title;",
        "        }",
        "",
        "        public boolean isDone() {",
        "            return done;",
        "        }",
        "",
        "        public void complete() {",
        "            done = true;",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Label.java",
      language: "java",
      content: [
        "import java.util.Objects;",
        "",
        "public final class Label {",
        "    private final String id;",
        "    private final String name;",
        "    private final String color;",
        "",
        "    public Label(String id, String name, String color) {",
        "        this.id = requireText(id, \"id\");",
        "        this.name = requireText(name, \"name\");",
        "        this.color = requireText(color, \"color\");",
        "    }",
        "",
        "    public String getId() {",
        "        return id;",
        "    }",
        "",
        "    public String getName() {",
        "        return name;",
        "    }",
        "",
        "    public String getColor() {",
        "        return color;",
        "    }",
        "",
        "    @Override",
        "    public boolean equals(Object other) {",
        "        if (this == other) {",
        "            return true;",
        "        }",
        "        if (!(other instanceof Label)) {",
        "            return false;",
        "        }",
        "        Label label = (Label) other;",
        "        return id.equals(label.id);",
        "    }",
        "",
        "    @Override",
        "    public int hashCode() {",
        "        return Objects.hash(id);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "MoveCardCommand.java",
      language: "java",
      content: [
        "public class MoveCardCommand {",
        "    private final Board board;",
        "    private final String sourceListId;",
        "    private final String targetListId;",
        "    private final String cardId;",
        "    private final int targetPosition;",
        "",
        "    private BoardList sourceList;",
        "    private BoardList targetList;",
        "    private Card movedCard;",
        "    private int originalPosition;",
        "    private boolean executed;",
        "",
        "    public MoveCardCommand(Board board, String sourceListId, String cardId, String targetListId, int targetPosition) {",
        "        this.board = board;",
        "        this.sourceListId = sourceListId;",
        "        this.cardId = cardId;",
        "        this.targetListId = targetListId;",
        "        this.targetPosition = targetPosition;",
        "    }",
        "",
        "    public void execute() {",
        "        if (executed) {",
        "            throw new IllegalStateException(\"Command already executed\");",
        "        }",
        "        sourceList = requireList(sourceListId);",
        "        targetList = requireList(targetListId);",
        "        originalPosition = sourceList.indexOf(cardId);",
        "        movedCard = sourceList.removeCard(cardId);",
        "        try {",
        "            targetList.insertCardAt(movedCard, targetPosition);",
        "        } catch (RuntimeException failure) {",
        "            sourceList.insertCardAt(movedCard, originalPosition);",
        "            throw failure;",
        "        }",
        "        executed = true;",
        "        board.notifyActivity(ActivityObserver.ActivityEvent.cardMoved(",
        "            board.getName(), movedCard.getTitle(), sourceList.getName(), targetList.getName()",
        "        ));",
        "    }",
        "",
        "    public void undo() {",
        "        if (!executed) {",
        "            throw new IllegalStateException(\"Command was not executed\");",
        "        }",
        "        targetList.removeCard(cardId);",
        "        sourceList.insertCardAt(movedCard, originalPosition);",
        "        executed = false;",
        "        board.notifyActivity(ActivityObserver.ActivityEvent.cardMoveUndone(",
        "            board.getName(), movedCard.getTitle(), sourceList.getName(), targetList.getName()",
        "        ));",
        "    }",
        "",
        "    private BoardList requireList(String listId) {",
        "        return board.findList(listId).orElseThrow(() -> new IllegalArgumentException(\"List not found: \" + listId));",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ActivityObserver.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.Objects;",
        "",
        "public interface ActivityObserver {",
        "    void onActivity(ActivityEvent event);",
        "",
        "    final class ActivityEvent {",
        "        private final Instant occurredAt;",
        "        private final String type;",
        "        private final String message;",
        "",
        "        private ActivityEvent(String type, String message) {",
        "            this.occurredAt = Instant.now();",
        "            this.type = Objects.requireNonNull(type, \"type\");",
        "            this.message = Objects.requireNonNull(message, \"message\");",
        "        }",
        "",
        "        public static ActivityEvent cardCreated(String boardName, String listName, String cardTitle) {",
        "            return new ActivityEvent(\"CARD_CREATED\", \"Created card '\" + cardTitle + \"' in \" + listName + \" on \" + boardName);",
        "        }",
        "",
        "        public static ActivityEvent cardMoved(String boardName, String cardTitle, String fromList, String toList) {",
        "            return new ActivityEvent(\"CARD_MOVED\", \"Moved card '\" + cardTitle + \"' from \" + fromList + \" to \" + toList + \" on \" + boardName);",
        "        }",
        "",
        "        public static ActivityEvent cardMoveUndone(String boardName, String cardTitle, String fromList, String toList) {",
        "            return new ActivityEvent(\"CARD_MOVE_UNDONE\", \"Restored card '\" + cardTitle + \"' from \" + toList + \" to \" + fromList + \" on \" + boardName);",
        "        }",
        "",
        "        public Instant getOccurredAt() {",
        "            return occurredAt;",
        "        }",
        "",
        "        public String getType() {",
        "            return type;",
        "        }",
        "",
        "        public String getMessage() {",
        "            return message;",
        "        }",
        "",
        "        @Override",
        "        public String toString() {",
        "            return occurredAt + \" [\" + type + \"] \" + message;",
        "        }",
        "    }",
        "",
        "    final class ConsoleActivityObserver implements ActivityObserver {",
        "        @Override",
        "        public void onActivity(ActivityEvent event) {",
        "            System.out.println(event);",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "BoardService.java",
      language: "java",
      content: [
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public class BoardService {",
        "    private final Map<String, Board> boards = new LinkedHashMap<>();",
        "    private final CardOrderingStrategy orderingStrategy;",
        "",
        "    public BoardService(CardOrderingStrategy orderingStrategy) {",
        "        this.orderingStrategy = Objects.requireNonNull(orderingStrategy, \"orderingStrategy\");",
        "    }",
        "",
        "    public Board createBoard(String id, String name) {",
        "        Board board = new Board(id, name);",
        "        if (boards.putIfAbsent(id, board) != null) {",
        "            throw new IllegalArgumentException(\"Duplicate board id: \" + id);",
        "        }",
        "        return board;",
        "    }",
        "",
        "    public BoardList addList(String boardId, String listId, String name) {",
        "        Board board = requireBoard(boardId);",
        "        BoardList list = new BoardList(listId, name);",
        "        board.addList(list);",
        "        return list;",
        "    }",
        "",
        "    public Card createCard(String boardId, String listId, Card card) {",
        "        Board board = requireBoard(boardId);",
        "        BoardList list = requireList(board, listId);",
        "        int position = orderingStrategy.positionForNewCard(list, card);",
        "        list.insertCardAt(card, position);",
        "        board.notifyActivity(ActivityObserver.ActivityEvent.cardCreated(board.getName(), list.getName(), card.getTitle()));",
        "        return card;",
        "    }",
        "",
        "    public MoveCardCommand moveCard(String boardId, String sourceListId, String cardId, String targetListId, int targetPosition) {",
        "        MoveCardCommand command = new MoveCardCommand(requireBoard(boardId), sourceListId, cardId, targetListId, targetPosition);",
        "        command.execute();",
        "        return command;",
        "    }",
        "",
        "    private Board requireBoard(String boardId) {",
        "        Board board = boards.get(boardId);",
        "        if (board == null) {",
        "            throw new IllegalArgumentException(\"Board not found: \" + boardId);",
        "        }",
        "        return board;",
        "    }",
        "",
        "    private BoardList requireList(Board board, String listId) {",
        "        return board.findList(listId).orElseThrow(() -> new IllegalArgumentException(\"List not found: \" + listId));",
        "    }",
        "",
        "    public interface CardOrderingStrategy {",
        "        int positionForNewCard(BoardList list, Card card);",
        "    }",
        "",
        "    public static final class AppendCardOrderingStrategy implements CardOrderingStrategy {",
        "        @Override",
        "        public int positionForNewCard(BoardList list, Card card) {",
        "            return list.getCards().size();",
        "        }",
        "    }",
        "",
        "    public static final class PriorityLabelOrderingStrategy implements CardOrderingStrategy {",
        "        @Override",
        "        public int positionForNewCard(BoardList list, Card card) {",
        "            boolean highPriority = card.getLabels().stream().anyMatch(label -> label.getName().equalsIgnoreCase(\"High\"));",
        "            return highPriority ? 0 : list.getCards().size();",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "public class Main {",
        "    public static void main(String[] args) {",
        "        BoardService service = new BoardService(new BoardService.AppendCardOrderingStrategy());",
        "        Board board = service.createBoard(\"board-1\", \"Launch Plan\");",
        "        board.addObserver(new ActivityObserver.ConsoleActivityObserver());",
        "",
        "        service.addList(\"board-1\", \"todo\", \"To Do\");",
        "        service.addList(\"board-1\", \"doing\", \"Doing\");",
        "        service.addList(\"board-1\", \"done\", \"Done\");",
        "",
        "        Card landingPage = new Card(\"card-1\", \"Build landing page\", \"Create hero section and pricing cards\")",
        "            .addLabel(new Label(\"label-1\", \"High\", \"red\"))",
        "            .assignMember(\"alice\")",
        "            .assignMember(\"bob\")",
        "            .addChecklistItem(\"Draft copy\")",
        "            .addChecklistItem(\"Publish assets\");",
        "",
        "        service.createCard(\"board-1\", \"todo\", landingPage);",
        "        MoveCardCommand move = service.moveCard(\"board-1\", \"todo\", \"card-1\", \"doing\", 0);",
        "        move.undo();",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "Board",
      detailMD:
        "The aggregate root. It owns board lists and observers, exposes read-only list views, validates duplicate list ids, and publishes activity events to subscribers.",
    },
    {
      className: "BoardList",
      detailMD:
        "Represents one Kanban column. It owns the ordered list of cards and centralizes insert, remove, lookup, and index operations so card order stays consistent.",
    },
    {
      className: "Card",
      detailMD:
        "Represents a work item with title, description, labels, members, and checklist items. Mutators return the card for clean construction, while getters expose unmodifiable views.",
    },
    {
      className: "Label",
      detailMD:
        "Immutable value object for visual card classification. Equality is id-based, so the same label can be reused across cards safely.",
    },
    {
      className: "MoveCardCommand",
      detailMD:
        "Command object for drag-drop. It removes a card from the source list, inserts it into the target list, records original position, rolls back on failed insert, and supports undo.",
    },
    {
      className: "ActivityObserver",
      detailMD:
        "Observer contract plus nested event and console observer demo. Production observers can write activity feed rows, send notifications, or publish websocket messages.",
    },
    {
      className: "BoardService",
      detailMD:
        "Thin application service that stores boards, creates lists and cards, delegates move behavior to commands, and injects nested ordering strategies.",
    },
    {
      className: "Main",
      detailMD:
        "Small executable demo that creates a board, subscribes a console feed, creates a card with label/member/checklist metadata, moves it, and undoes the move.",
    },
  ],

  dryRun: {
    inputMD:
      "Board **Launch Plan** with lists **To Do**, **Doing**, **Done**. Card **Build landing page** has label **High**, members **alice** and **bob**, and two checklist items. Actions: create in To Do, move to Doing position 0, undo.",
    columns: ["Step", "Action", "To Do", "Doing", "Done", "Activity"],
    rows: [
      ["1", "createCard(card-1, To Do)", "[card-1]", "[]", "[]", "CARD_CREATED"],
      ["2", "moveCard(To Do → Doing, position 0)", "[]", "[card-1]", "[]", "CARD_MOVED"],
      ["3", "undo()", "[card-1]", "[]", "[]", "CARD_MOVE_UNDONE"],
      ["4", "read board", "[card-1 with labels/members/checklist]", "[]", "[]", "No mutation event"],
    ],
    narrativeMD:
      "The command captures the original To Do index before removing the card. Undo therefore restores both membership and order, not merely the list name.",
  },

  complexity: [
    {
      operation: "createBoard",
      time: "O(1)",
      space: "O(1)",
      note: "One map insertion plus a new Board object.",
    },
    {
      operation: "createCard",
      time: "O(C)",
      space: "O(1)",
      note: "C is cards in the target list; duplicate id check scans the list before insertion.",
    },
    {
      operation: "moveCard",
      time: "O(S + T)",
      space: "O(1)",
      note: "S and T are source and target list sizes; lookup/removal/insertion are list operations.",
    },
    {
      operation: "undo move",
      time: "O(S + T)",
      space: "O(1)",
      note: "Inverse remove and insert across the same lists.",
    },
    {
      operation: "publish activity",
      time: "O(O)",
      space: "O(1)",
      note: "O observers are invoked synchronously in the baseline.",
    },
  ],
  complexityNotesMD:
    "For interview clarity the implementation stores ordered cards in arrays. Large boards can add a card id index per board and a sparse rank field per card to reduce scans and avoid shifting many cards.",

  extensibility: [
    {
      label: "Comments, attachments, and due dates",
      detailMD:
        "Add fields or child value objects to **Card**. The Board → List → Card ownership and move command stay unchanged.",
    },
    {
      label: "Persistent activity feed",
      detailMD:
        "Implement **ActivityObserver** with a repository-backed feed writer. Board mutation code still only publishes events.",
    },
    {
      label: "Different ordering models",
      detailMD:
        "Replace integer insertion with a rank object or another **CardOrderingStrategy**. Existing service methods can keep the same shape.",
    },
    {
      label: "Permissions and workspace roles",
      detailMD:
        "Add an authorization decorator around **BoardService** to verify board membership before creating cards or executing commands.",
    },
    {
      label: "Additional undoable operations",
      detailMD:
        "Extract a small command interface and implement create-card, archive-card, update-description, and checklist commands with the same execute/undo contract.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Global card repository with list ids",
      detailMD:
        "Store all cards in a board-level map and put only card ids in lists. Moving a card updates ids and possibly the card's current list field.",
      tradeoffsMD:
        "Faster lookup and persistence mapping, but weaker object ownership. The clean Board → List → Card composition becomes less explicit.",
    },
    {
      name: "Event-sourced board",
      detailMD:
        "Represent create, move, label, assign, and checklist changes as immutable events. Board state is rebuilt by replaying the event stream.",
      tradeoffsMD:
        "Great auditability and collaboration history, but more complex snapshots, replay, and consistency rules for an LLD interview.",
    },
    {
      name: "Rank-based ordering",
      detailMD:
        "Give each card a sparse rank such as 1000, 2000, 3000. Moving between cards assigns a rank between neighbors instead of shifting arrays.",
      tradeoffsMD:
        "Excellent for large lists and concurrent edits, but rank compaction and collision handling add production concerns.",
    },
  ],

  commonMistakes: [
    "Treating cards as global objects and letting multiple lists point to the same mutable card without a clear owner.",
    "Moving a card by only changing a status string, which loses list order and makes undo ambiguous.",
    "Implementing undo by guessing the previous list instead of storing original list and original index in the command.",
    "Publishing feed messages directly from UI code rather than using an Observer seam on board mutations.",
    "Exposing mutable card lists to callers, allowing them to bypass duplicate checks and activity events.",
    "Hard-coding append-only insertion so future priority or rank-based ordering requires rewriting service logic.",
    "Forgetting to handle rollback if insertion into the target list fails after removal from the source list.",
  ],

  followUps: [
    {
      question: "How would you support concurrent users moving the same card?",
      answerMD:
        "Add optimistic versioning on cards or lists. A command includes the expected version; if another move already changed it, reject or rebase and publish a conflict event.",
    },
    {
      question: "How do you make card lookup O(1)?",
      answerMD:
        "Maintain a board-level index from card id to list id and position. BoardList remains the owner of order, while the index accelerates lookup and is updated in move/undo.",
    },
    {
      question: "Where should comments and attachments live?",
      answerMD:
        "As child collections on **Card** or as separate entities keyed by card id if they are large. The move command should not care because it moves the whole card.",
    },
    {
      question: "How would an activity feed persist reliably?",
      answerMD:
        "Use an observer that writes feed rows in the same transaction as the command, or use an outbox table so feed delivery can retry without duplicating domain logic.",
    },
    {
      question: "How would you support WIP limits on a list?",
      answerMD:
        "Add a policy check to **BoardList.insertCardAt** or a validation strategy used by **MoveCardCommand** before insertion. The command boundary remains reusable.",
    },
  ],

  productionConsiderations: [
    {
      label: "Persistence model",
      detailMD:
        "Persist boards, lists, cards, labels, checklist items, and card ranks with foreign keys that mirror the aggregate. Move card should be transactional.",
    },
    {
      label: "Concurrency control",
      detailMD:
        "Use list or card version columns to prevent lost updates when two users drag the same card or reorder the same list simultaneously.",
    },
    {
      label: "Activity feed delivery",
      detailMD:
        "Feed writes, notifications, and websocket pushes should be idempotent. An outbox pattern keeps observers reliable across process crashes.",
    },
    {
      label: "Ordering at scale",
      detailMD:
        "Integer positions are easy but expensive to shift. Production Trello-like systems often use sparse ranks and periodic compaction.",
    },
    {
      label: "Permissions and audit",
      detailMD:
        "Every command should carry actor identity. The service validates board access and writes actor, timestamp, and before/after metadata for audit.",
    },
  ],

  interviewNotes: [
    "Did the candidate preserve the Board → List → Card composition instead of flattening everything into service maps?",
    "Is moving a card a Command with enough state to undo precisely?",
    "Are feed and notification concerns decoupled through Observer?",
    "Is ordering policy represented by Strategy rather than hard-coded conditionals?",
    "Do list methods guard invariants such as no duplicate card ids and valid insertion positions?",
    "Can the candidate explain how this baseline evolves toward persistence, concurrency, and rank-based ordering?",
  ],

  quiz: [
    {
      question: "Why is **MoveCardCommand** a good fit for drag-drop card movement?",
      options: [
        "It stores both the requested move and the prior state needed for undo",
        "It removes the need for a Board class",
        "It makes all list operations constant time",
        "It replaces Observer for activity feed events",
      ],
      answerIndex: 0,
      explanationMD:
        "Command encapsulates the operation and its inverse state. That is exactly what drag-drop undo needs.",
    },
    {
      question: "Which object should own the ordered collection of cards?",
      options: [
        "ActivityObserver",
        "BoardList",
        "Label",
        "Main",
      ],
      answerIndex: 1,
      explanationMD:
        "A list or column defines card order, so **BoardList** should own and protect that ordered collection.",
    },
    {
      question: "What does the Observer pattern decouple in this design?",
      options: [
        "Board creation from id generation",
        "List insertion from duplicate validation",
        "Board mutations from feed, notification, and audit subscribers",
        "Labels from card descriptions",
      ],
      answerIndex: 2,
      explanationMD:
        "The board publishes activity events without knowing which subscribers render feeds, send alerts, or persist audit rows.",
    },
    {
      question: "Why inject **CardOrderingStrategy** into **BoardService**?",
      options: [
        "To avoid storing cards in lists",
        "To vary insertion policy without changing card creation flow",
        "To make observers asynchronous",
        "To guarantee cards never move",
      ],
      answerIndex: 1,
      explanationMD:
        "Strategy isolates the policy of where a new card should be placed from the service operation that creates it.",
    },
    {
      question: "What invariant must hold after every successful move or undo?",
      options: [
        "The card has no labels",
        "The card exists in exactly one board list and list order is valid",
        "Every observer must store the event in a database",
        "All cards must be in the Done list",
      ],
      answerIndex: 1,
      explanationMD:
        "The core correctness rule is single ownership by one list plus a valid position in that list.",
    },
  ],

  practiceVariants: [
    {
      title: "Add comments and mentions",
      detailMD:
        "Add a comment collection to **Card**, include actor and timestamp, and emit activity events when comments mention assigned members.",
      difficulty: "Intermediate",
    },
    {
      title: "Implement WIP limits",
      detailMD:
        "Give **BoardList** an optional maximum active-card count and reject move commands that would exceed it.",
      difficulty: "Intermediate",
    },
    {
      title: "Rank-based drag ordering",
      detailMD:
        "Replace integer positions with sparse rank strings so cards can move between neighbors without shifting an entire list.",
      difficulty: "Advanced",
    },
  ],

  flashcards: [
    {
      front: "What is the core composition hierarchy in Trello LLD?",
      back: "**Board** owns **BoardList** objects; each **BoardList** owns ordered **Card** objects; each **Card** owns metadata such as labels and checklist items.",
    },
    {
      front: "Which pattern makes card movement undoable?",
      back: "Command — **MoveCardCommand** stores the source list, target list, card id, original index, and moved card.",
    },
    {
      front: "Which pattern powers the activity feed?",
      back: "Observer — **Board** publishes **ActivityEvent** objects to **ActivityObserver** subscribers.",
    },
    {
      front: "Why avoid exposing mutable card lists?",
      back: "External callers could reorder or duplicate cards without validation, command history, or activity events.",
    },
    {
      front: "How can Trello handle very large list ordering?",
      back: "Use sparse ranks or fractional ordering instead of shifting integer positions for every move.",
    },
    {
      front: "Where does new-card placement policy live?",
      back: "In **CardOrderingStrategy**, injected into **BoardService**.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** Board, BoardList, Card, Label, MoveCardCommand, ActivityObserver, BoardService, CardOrderingStrategy.",
    "",
    "**Composition:** Board → BoardList → Card → labels/members/checklist. Keep ownership local and expose read-only views.",
    "",
    "**Patterns:** Command for move/undo, Observer for activity feed, Composite for whole-part hierarchy, Strategy for card ordering.",
    "",
    "**Move flow:** find source and target lists → record original index → remove card → insert at target position → publish activity.",
    "",
    "**Undo flow:** remove from target → insert back into source at original index → publish undo activity.",
    "",
    "**Invariants:** one card belongs to one list; positions are valid; duplicate card ids are rejected; feed is emitted after successful mutation.",
    "",
    "**Scale path:** add board-level card index, sparse ranks, optimistic versions, persistence, outbox-backed observers, and permission checks.",
  ].join("\n"),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    },
    {
      title: "Effective Java",
      kind: "Book",
      author: "Joshua Bloch",
    },
    {
      title: "Refactoring Guru — Command Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/command",
    },
    {
      title: "Refactoring Guru — Observer Pattern",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/observer",
    },
  ],

  relatedProblems: [
    { slug: "jira", note: "Jira extends boards with workflow states, sprints, issue types, and richer audit trails." },
    { slug: "slack", note: "Slack also needs observer-style fanout for feed and notification events." },
    { slug: "google-docs", note: "Google Docs explores command history and collaborative updates in a more real-time setting." },
  ],
};
