import type { LLDConceptContent } from "../types";

export const umlDiagrams: LLDConceptContent = {
  slug: "uml-diagrams",

  introMD: [
    "UML is a compact interview language for explaining object structure, runtime collaboration, and state transitions before you write Java. You do not need every notation from the UML standard. You need the subset that lets a Microsoft, Oracle, or Adobe interviewer see your classes, ownership boundaries, APIs, and object interactions quickly.",
    "",
    "This lesson focuses on **class diagrams**, the six relationship types, multiplicity, **sequence diagrams**, **state diagrams**, **activity diagrams**, and a fast whiteboard method for drawing a class diagram under time pressure.",
  ].join("\n"),

  learningObjectives: [
    "Draw a class diagram with class names, attributes, methods, and visibility markers.",
    "Explain association, aggregation, composition, inheritance, realization, and dependency with correct Mermaid arrows.",
    "Use multiplicity to show one-to-one, one-to-many, optional, and many-to-many object links.",
    "Choose sequence, state, or activity diagrams when structure alone is not enough.",
    "Build a useful class diagram quickly from requirements in an interview setting.",
    "Avoid common UML mistakes that make a design look more coupled or less precise than intended.",
  ],

  theory: [
    {
      title: "UML in interviews is a communication tool, not a paperwork exercise",
      detailMD: [
        "Interviewers use UML to test whether you can make design decisions visible. A good diagram answers three questions:",
        "",
        "- What are the main responsibilities?",
        "- Who owns or depends on whom?",
        "- What changes over time during important flows?",
        "",
        "Use only enough notation to remove ambiguity. If you spend ten minutes perfecting arrowheads and miss the core objects, the diagram has failed. If the diagram makes class ownership, APIs, and request flow clear, it has done its job.",
      ].join("\n"),
    },
    {
      title: "Class diagrams show static structure",
      detailMD: [
        "A class diagram captures the types in your design and how they relate. Each class box usually has three compartments: **class name**, **attributes**, and **methods**.",
        "",
        "Visibility markers matter because they show encapsulation:",
        "- **plus** means public.",
        "- **minus** means private.",
        "- **hash** means protected.",
        "- **tilde** means package-private.",
        "",
        "In an interview, show only attributes that affect the design. Do not list every getter, setter, or simple DTO field. Focus on state that drives rules and methods that represent domain behavior.",
      ].join("\n"),
      code: [
        "public final class Order {",
        "    private final String orderId;",
        "    private final List<OrderItem> items = new ArrayList<>();",
        "    private OrderStatus status = OrderStatus.CREATED;",
        "",
        "    public void addItem(Product product, int quantity) {",
        "        items.add(new OrderItem(product, quantity));",
        "    }",
        "",
        "    public Money total() {",
        "        return items.stream()",
        "                .map(OrderItem::subtotal)",
        "                .reduce(Money.zero(), Money::add);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Association is a structural link between objects",
      detailMD: [
        "Association means one object knows or is linked to another in the domain. It is a broad relationship and does not imply ownership by itself.",
        "",
        "Use association when the relationship is stable enough to appear in the object model, such as **Customer places Order** or **Driver is assigned Ride**. Add multiplicity near each end so the reader knows cardinality: **1**, **0..1**, **0..***, **1..***, or **many** when the whiteboard is informal.",
        "",
        "Association is stronger than a temporary method call. If an object merely receives another object as a parameter during one operation, that is usually dependency, not association.",
      ].join("\n"),
    },
    {
      title: "Aggregation models weak whole-part ownership",
      detailMD: [
        "Aggregation is a has-a relationship where the part can outlive the whole. The whole groups or references parts, but destroying the whole does not destroy the parts.",
        "",
        "Use aggregation for examples like **Team has Players**, **Catalog has Products**, or **Playlist has Songs** when those parts can exist independently. In Mermaid class diagrams, aggregation uses a hollow diamond at the whole side.",
        "",
        "In interviews, be conservative with aggregation. If the lifetime rule is not important, plain association is often enough.",
      ].join("\n"),
    },
    {
      title: "Composition models strong ownership and lifetime control",
      detailMD: [
        "Composition is a whole-part relationship where the whole owns the part. The part is created, managed, and usually deleted with the whole.",
        "",
        "Use composition for **Order owns OrderItems**, **ParkingLot owns Levels**, or **Level owns ParkingSpots**. It communicates strong invariants: an OrderItem should not float around without its Order.",
        "",
        "Composition is useful in LLD because it tells the interviewer where lifecycle rules and consistency checks belong.",
      ].join("\n"),
      code: [
        "public final class Order {",
        "    private final List<OrderItem> items = new ArrayList<>();",
        "",
        "    public void addItem(Product product, int quantity) {",
        "        if (quantity <= 0) {",
        "            throw new IllegalArgumentException(\"quantity must be positive\");",
        "        }",
        "        items.add(new OrderItem(product, quantity));",
        "    }",
        "",
        "    public List<OrderItem> items() {",
        "        return List.copyOf(items);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Inheritance and realization show type substitution",
      detailMD: [
        "Inheritance, also called generalization, means a child class is a true subtype of a parent class. Use it for stable is-a relationships such as **CardPayment is a Payment** or **Car is a Vehicle**.",
        "",
        "Realization means a class implements an interface contract. Use it when a concrete class provides a capability, such as **StripePaymentProcessor implements PaymentProcessor**.",
        "",
        "In class diagrams, inheritance uses a solid line with a hollow triangle toward the parent. Realization uses a dashed line with a hollow triangle toward the interface. Both imply substitutability, so do not use them for ownership or service calls.",
      ].join("\n"),
      code: [
        "public interface PaymentProcessor {",
        "    PaymentReceipt charge(Money amount);",
        "}",
        "",
        "public final class StripePaymentProcessor implements PaymentProcessor {",
        "    @Override",
        "    public PaymentReceipt charge(Money amount) {",
        "        return new PaymentReceipt(\"stripe\", amount);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      title: "Dependency is a temporary uses relationship",
      detailMD: [
        "Dependency means one class uses another but does not own it as part of its long-term state. Examples include a service calling a gateway, a method accepting a formatter, or a controller invoking a validator.",
        "",
        "Use dependency when a class needs another type to complete work but the target is not a domain part. The dashed arrow keeps the diagram honest: **CheckoutService depends on PaymentGateway** does not mean the gateway is contained inside checkout.",
        "",
        "Dependencies should usually point from high-level behavior toward small abstractions, not concrete infrastructure classes.",
      ].join("\n"),
    },
    {
      title: "Multiplicity makes relationship meaning precise",
      detailMD: [
        "Multiplicity shows how many objects can participate in a relationship. It is often the difference between an acceptable diagram and an ambiguous one.",
        "",
        "Common values are:",
        "- **1** exactly one.",
        "- **0..1** optional, at most one.",
        "- **0..*** zero or many.",
        "- **1..*** at least one.",
        "- **m..n** bounded range.",
        "",
        "Always ask whether the requirement allows zero, one, or many. For example, a Customer can place **0..*** Orders, while each Order belongs to **1** Customer. That single detail drives storage, validation, and API choices.",
      ].join("\n"),
    },
    {
      title: "Sequence diagrams show one important runtime flow",
      detailMD: [
        "A sequence diagram shows how participants collaborate over time. It is best for flows such as checkout, reservation, payment, login, notification delivery, or ride matching.",
        "",
        "Read it top to bottom. Participants are vertical lifelines. Messages are arrows. Responses can be dashed. Use **alt** branches when success and failure paths matter. Do not show every internal helper call; show the calls that explain the design.",
        "",
        "In interviews, a sequence diagram is strongest after the class diagram. It proves that your classes can actually satisfy a functional requirement.",
      ].join("\n"),
    },
    {
      title: "State diagrams show lifecycle rules",
      detailMD: [
        "A state diagram models how one object changes state in response to events. It is useful when lifecycle rules are central: tickets, orders, payments, documents, reservations, games, elevators, and workflows.",
        "",
        "A good state diagram names allowed transitions and makes invalid transitions obvious. For example, an Order can move from **Created** to **Paid**, then **Packed**, then **Shipped**, then **Delivered**. Cancellation may be allowed early but not after delivery.",
        "",
        "Use it when enum values alone are not enough. The diagram should answer which event moves the object and which transitions are forbidden.",
      ].join("\n"),
      code: [
        "public enum OrderStatus {",
        "    CREATED,",
        "    PAID,",
        "    PACKED,",
        "    SHIPPED,",
        "    DELIVERED,",
        "    CANCELLED",
        "}",
      ].join("\n"),
    },
    {
      title: "Activity diagrams show workflow and branching",
      detailMD: [
        "An activity diagram shows the steps of a process, including decisions, parallel work, and loops. It is useful when the interviewer cares more about workflow than object ownership.",
        "",
        "Use activity diagrams for flows such as **process return**, **approve expense**, **fulfill order**, or **retry notification**. They are less common than class and sequence diagrams in LLD, but they help when the problem is a business process with many branches.",
        "",
        "If time is limited, describe the activity flow in bullets instead of drawing it. Save diagram time for class structure and one critical sequence.",
      ].join("\n"),
    },
    {
      title: "Fast method to draw a class diagram under time pressure",
      detailMD: [
        "Use this five-minute loop:",
        "",
        "1. **Box the nouns:** list the main domain objects from requirements.",
        "2. **Assign responsibilities:** write one sentence per class before adding fields.",
        "3. **Add public behavior:** include the methods interviewers need to see, not boilerplate accessors.",
        "4. **Connect relationships:** choose association, aggregation, composition, inheritance, realization, or dependency deliberately.",
        "5. **Add multiplicity:** mark 1, 0..1, 0..*, or 1..* on important links.",
        "6. **Walk one flow:** use a sequence diagram mentally or visibly to catch missing services and methods.",
        "",
        "If stuck, start with composition and dependency. Add inheritance or realization only when substitution is clearly useful.",
      ].join("\n"),
    },
  ],

  diagrams: [
    {
      title: "Class diagram relationships and multiplicity",
      mermaid: [
        "classDiagram",
        "    class Customer {",
        "        -String customerId",
        "        -String name",
        "        +placeOrder() Order",
        "    }",
        "    class Order {",
        "        -String orderId",
        "        -OrderStatus status",
        "        +addItem(Product, int) void",
        "        +total() Money",
        "        #validateTransition(OrderStatus) boolean",
        "    }",
        "    class OrderItem {",
        "        -int quantity",
        "        +subtotal() Money",
        "    }",
        "    class Catalog {",
        "        +findProduct(String) Product",
        "    }",
        "    class Product {",
        "        -String sku",
        "        -Money price",
        "    }",
        "    class Payment {",
        "        <<abstract>>",
        "        -String paymentId",
        "        +authorize(Money) PaymentReceipt",
        "    }",
        "    class CardPayment {",
        "        +authorize(Money) PaymentReceipt",
        "    }",
        "    class PaymentProcessor {",
        "        <<interface>>",
        "        +charge(Money) PaymentReceipt",
        "    }",
        "    class StripePaymentProcessor {",
        "        +charge(Money) PaymentReceipt",
        "    }",
        "    class CheckoutService {",
        "        ~validate(Order) boolean",
        "        +checkout(Order, PaymentProcessor) PaymentReceipt",
        "    }",
        "    class PaymentGateway {",
        "        +capture(Money) PaymentReceipt",
        "    }",
        "    Customer \"1\" --> \"0..*\" Order : places",
        "    Order \"1\" *-- \"1..*\" OrderItem : owns",
        "    Catalog \"1\" o-- \"0..*\" Product : lists",
        "    OrderItem \"1\" --> \"1\" Product : references",
        "    Payment <|-- CardPayment",
        "    PaymentProcessor <|.. StripePaymentProcessor",
        "    CheckoutService ..> PaymentProcessor : uses",
        "    CheckoutService ..> PaymentGateway : calls",
      ].join("\n"),
      captionMD:
        "The diagram shows all six core relationships: association, aggregation, composition, inheritance, realization, and dependency. Multiplicity clarifies that one Customer can place many Orders and each Order owns one or more OrderItems.",
    },
    {
      title: "Checkout sequence diagram",
      mermaid: [
        "sequenceDiagram",
        "    participant Customer",
        "    participant CheckoutService",
        "    participant Inventory",
        "    participant PaymentGateway",
        "    participant OrderRepository",
        "    Customer->>CheckoutService: checkout",
        "    CheckoutService->>Inventory: reserveItems",
        "    alt itemsAvailable",
        "        Inventory-->>CheckoutService: reservationConfirmed",
        "        CheckoutService->>PaymentGateway: charge",
        "        PaymentGateway-->>CheckoutService: paymentReceipt",
        "        CheckoutService->>OrderRepository: saveOrder",
        "        OrderRepository-->>CheckoutService: orderId",
        "        CheckoutService-->>Customer: orderConfirmed",
        "    else itemsMissing",
        "        Inventory-->>CheckoutService: reservationRejected",
        "        CheckoutService-->>Customer: outOfStock",
        "    end",
      ].join("\n"),
      captionMD:
        "The sequence diagram validates that the static classes can support a real checkout flow, including the failure branch when inventory cannot be reserved.",
    },
    {
      title: "Order state diagram",
      mermaid: [
        "stateDiagram-v2",
        "    [*] --> Created",
        "    Created --> Paid: paymentAuthorized",
        "    Created --> Cancelled: cancel",
        "    Paid --> Packed: pack",
        "    Paid --> Cancelled: cancelBeforePacking",
        "    Packed --> Shipped: ship",
        "    Shipped --> Delivered: deliver",
        "    Cancelled --> [*]",
        "    Delivered --> [*]",
      ].join("\n"),
      captionMD:
        "The state diagram makes lifecycle rules explicit. Cancellation is allowed before packing, but there is no transition from Delivered back to an earlier state.",
    },
  ],

  comparisons: [
    {
      title: "Aggregation vs Composition",
      columns: ["Dimension", "Aggregation", "Composition", "Interview guidance"],
      rows: [
        [
          "Ownership strength",
          "Weak whole-part relationship",
          "Strong whole-part relationship",
          "Use composition when the whole controls the part lifecycle",
        ],
        [
          "Part lifetime",
          "Part can outlive the whole",
          "Part usually dies with the whole",
          "Ask whether the child object makes sense independently",
        ],
        [
          "Mermaid arrow",
          "Hollow diamond at the whole",
          "Filled diamond at the whole",
          "Draw the diamond near the owner or grouping object",
        ],
        [
          "Example",
          "Catalog has Products",
          "Order owns OrderItems",
          "Prefer association if lifetime ownership does not matter",
        ],
      ],
    },
    {
      title: "Association vs Dependency",
      columns: ["Dimension", "Association", "Dependency", "Interview guidance"],
      rows: [
        [
          "Meaning",
          "A stable structural link between objects",
          "A temporary uses relationship",
          "Use association for domain relationships and dependency for service calls",
        ],
        [
          "Typical implementation",
          "Field, collection, or persistent reference",
          "Method parameter, local variable, injected collaborator, or call target",
          "Do not turn every helper call into a structural link",
        ],
        [
          "Mermaid arrow",
          "Solid line arrow",
          "Dashed line arrow",
          "Dashed arrows reduce visual overstatement of ownership",
        ],
        [
          "Example",
          "Customer places Orders",
          "CheckoutService calls PaymentGateway",
          "If the target is not part of the domain model, dependency is often cleaner",
        ],
      ],
    },
  ],

  bestPractices: [
    "Start diagrams from responsibilities and flows, not from database tables.",
    "Use class diagrams for structure, sequence diagrams for one runtime scenario, and state diagrams for lifecycle-heavy objects.",
    "Put multiplicity on relationships that affect validation, storage, or API design.",
    "Use composition for owned parts and dependency for temporary service usage.",
    "Show interfaces only where variation or testability matters.",
    "Keep Mermaid class names and participant names simple and alphanumeric.",
    "Prefer one clear diagram over several crowded diagrams with tiny labels.",
    "After drawing, walk one requirement through the diagram to find missing methods or collaborators.",
  ],

  commonMistakes: [
    "Using inheritance arrows for has-a relationships such as Order and OrderItem.",
    "Drawing composition when the part can exist independently and is not lifecycle-owned by the whole.",
    "Leaving multiplicity out of relationships where optionality or many-to-many behavior matters.",
    "Listing every getter and setter instead of domain methods that reveal behavior.",
    "Confusing dependency with association and making temporary calls look like permanent ownership.",
    "Putting too many controllers, repositories, and infrastructure details in the first class diagram.",
    "Drawing sequence diagrams with every private helper call instead of major participant interactions.",
    "Using a state diagram for stateless services rather than lifecycle-driven domain objects.",
  ],

  quiz: [
    {
      question: "What is the main purpose of a class diagram in an LLD interview?",
      options: [
        "To show static structure, responsibilities, and relationships",
        "To show server CPU usage over time",
        "To replace all Java implementation details",
        "To prove that every class has getters and setters",
      ],
      answerIndex: 0,
      explanationMD:
        "A class diagram communicates the main types, their public behavior, important state, and relationships.",
    },
    {
      question: "Which relationship should you use when Order strongly owns OrderItem objects?",
      options: [
        "Aggregation",
        "Composition",
        "Dependency",
        "Realization",
      ],
      answerIndex: 1,
      explanationMD:
        "Composition shows strong whole-part ownership and lifetime control by the whole.",
    },
    {
      question: "What does realization mean in a UML class diagram?",
      options: [
        "A class implements an interface contract",
        "A class stores another class in a list",
        "A method temporarily calls another service",
        "Two objects are always created in the same package",
      ],
      answerIndex: 0,
      explanationMD:
        "Realization is the dashed hollow-triangle relationship from an implementing class to an interface.",
    },
    {
      question: "When should you add multiplicity to a relationship?",
      options: [
        "Only after writing production code",
        "When cardinality affects validation, ownership, or storage choices",
        "Only for inheritance relationships",
        "Never, because it makes diagrams less precise",
      ],
      answerIndex: 1,
      explanationMD:
        "Multiplicity makes cardinality explicit, such as one customer to many orders or optional assignment.",
    },
    {
      question: "Which diagram best explains the checkout request flow across services?",
      options: [
        "State diagram",
        "Class diagram",
        "Sequence diagram",
        "Package diagram",
      ],
      answerIndex: 2,
      explanationMD:
        "A sequence diagram shows participants and messages over time for a specific scenario.",
    },
    {
      question: "Which diagram is most useful when an object has strict lifecycle transitions?",
      options: [
        "State diagram",
        "Deployment diagram",
        "Component diagram",
        "Object diagram only",
      ],
      answerIndex: 0,
      explanationMD:
        "A state diagram makes allowed and forbidden transitions visible for lifecycle-heavy domain objects.",
    },
    {
      question: "What is a good fast first step when drawing a class diagram under time pressure?",
      options: [
        "Write all database indexes",
        "Box the main nouns from the requirements",
        "Draw every private helper method",
        "Start with inheritance for all shared fields",
      ],
      answerIndex: 1,
      explanationMD:
        "Boxing the domain nouns quickly gives you candidate classes that can then receive responsibilities and relationships.",
    },
  ],

  flashcards: [
    {
      front: "What does a class diagram show?",
      back: "Static structure: classes, important attributes, methods, visibility, and relationships.",
    },
    {
      front: "What does association mean?",
      back: "A stable structural link between objects, without implying ownership by itself.",
    },
    {
      front: "What does aggregation mean?",
      back: "A weak whole-part relationship where the part can outlive the whole.",
    },
    {
      front: "What does composition mean?",
      back: "A strong whole-part relationship where the whole owns the part lifecycle.",
    },
    {
      front: "What does realization mean?",
      back: "A concrete class implements an interface contract and can be used through that interface.",
    },
    {
      front: "When should you use a dependency arrow?",
      back: "When one class temporarily uses another type through a call, parameter, local variable, or injected collaborator.",
    },
    {
      front: "What does multiplicity express?",
      back: "How many objects can participate in a relationship, such as 1, 0..1, 0..*, or 1..*.",
    },
    {
      front: "When is a sequence diagram useful?",
      back: "When you need to explain one important runtime scenario across participants.",
    },
    {
      front: "When is a state diagram useful?",
      back: "When a domain object has important lifecycle transitions and invalid states to prevent.",
    },
  ],

  cheatSheetMD: [
    "**Class diagrams:** Show class name, key attributes, public behavior, visibility, and relationships. Skip boilerplate getters and setters.",
    "",
    "**Visibility:** plus is public, minus is private, hash is protected, tilde is package-private.",
    "",
    "**Association:** Stable structural link. Example: Customer places Orders.",
    "",
    "**Aggregation:** Weak whole-part. The part can outlive the whole. Example: Catalog has Products.",
    "",
    "**Composition:** Strong whole-part. The whole owns the part lifecycle. Example: Order owns OrderItems.",
    "",
    "**Inheritance or generalization:** Child is a true subtype of parent. Example: CardPayment extends Payment.",
    "",
    "**Realization:** Class implements interface. Example: StripePaymentProcessor implements PaymentProcessor.",
    "",
    "**Dependency:** Temporary uses relationship. Example: CheckoutService calls PaymentGateway.",
    "",
    "**Multiplicity:** Add 1, 0..1, 0..*, or 1..* when cardinality affects rules.",
    "",
    "**Sequence diagrams:** Use for one flow over time, such as checkout, payment, reservation, or login.",
    "",
    "**State diagrams:** Use for lifecycle objects with allowed transitions, such as Order, Ticket, Reservation, or Payment.",
    "",
    "**Activity diagrams:** Use for branching business workflows. If time is short, describe the workflow in bullets.",
    "",
    "**Fast class diagram method:** Box nouns, assign responsibilities, add public behavior, connect relationships, add multiplicity, then walk one flow.",
  ].join("\n"),

  references: [
    {
      title: "UML Distilled",
      kind: "Book",
      author: "Martin Fowler",
    },
    {
      title: "The Unified Modeling Language Reference Manual",
      kind: "Book",
      author: "James Rumbaugh, Ivar Jacobson, and Grady Booch",
    },
    {
      title: "Mermaid Class diagrams",
      kind: "Docs",
      url: "https://mermaid.js.org/syntax/classDiagram.html",
    },
    {
      title: "Mermaid Sequence diagrams",
      kind: "Docs",
      url: "https://mermaid.js.org/syntax/sequenceDiagram.html",
    },
  ],

  relatedProblems: [
    { slug: "oop-fundamentals", note: "OOP fundamentals explain the classes, visibility, encapsulation, inheritance, and polymorphism that UML visualizes." },
    { slug: "solid-principles", note: "SOLID principles help decide when UML relationships should become interfaces, abstractions, or dependencies." },
    { slug: "parking-lot", note: "Parking Lot is a strong practice problem for drawing composition, inheritance, multiplicity, and sequence flows." },
  ],
};
