import type { LLDProblemContent } from "../types";

export const whatsapp: LLDProblemContent = {
  slug: "whatsapp",

  statementMD: [
    "Design the object model for **WhatsApp** from an LLD/OOD perspective.",
    "The system supports registered users, one-to-one chats, group chats, text messages, group membership, and message receipts that move through **Sent -> Delivered -> Read**.",
    "",
    "The core interview challenge is not mobile networking or storage scale. It is placing coordination in a **Mediator** (**ChatServer**), keeping chat objects responsible for membership, and modelling the delivery lifecycle so invalid transitions are impossible.",
  ].join("\n"),

  businessContextMD: [
    "Messaging systems are a favorite Meta, Google, and Amazon LLD topic because they combine familiar product behavior with subtle object boundaries.",
    "A strong solution separates user identity, chat membership, routing, message state, and notification concerns.",
    "",
    "Interviewers want to see whether the candidate avoids turning **User** into a god object, whether **ChatServer** coordinates without owning every policy, and whether receipts are represented as a lifecycle rather than a set of loose booleans.",
  ].join("\n"),

  functionalRequirements: [
    "Register users with stable ids and display names.",
    "Create one-to-one chats between exactly two distinct users.",
    "Create group chats with multiple users and allow membership changes.",
    "Send text messages from a chat member to the other participants.",
    "Route each message through a mediator instead of direct user-to-user calls.",
    "Track message status through **Sent -> Delivered -> Read** and reject invalid transitions.",
    "Notify interested observers when a message status changes.",
    "Allow a recipient to mark a delivered message as read.",
  ],

  nonFunctionalRequirements: [
    {
      label: "Correct lifecycle semantics",
      detailMD:
        "A message must not jump from **Sent** to **Read** without first becoming **Delivered**. The state object owns that rule.",
    },
    {
      label: "Loose coupling between users",
      detailMD:
        "**User** objects should not call each other directly. **ChatServer** is the mediator that validates membership and routes messages.",
    },
    {
      label: "Extensible delivery policy",
      detailMD:
        "Online-only delivery is the default, but retry queues, device fanout, or priority rules should be replaceable as strategies.",
    },
    {
      label: "Notification fanout",
      detailMD:
        "Receipt updates should be pushed through observers so the message lifecycle does not depend on a specific UI, socket, or analytics sink.",
    },
    {
      label: "Encapsulation of group rules",
      detailMD:
        "Group membership checks and membership mutations belong in **GroupChat**, not scattered across every send path.",
    },
  ],

  requirementClarification: [
    {
      question: "Are we designing encryption, media upload, and mobile sync?",
      answerMD:
        "No. Focus on the LLD object model for users, chats, messages, routing, membership, and receipt state. Encryption and media storage are boundary services.",
    },
    {
      question: "Is message status per chat or per recipient?",
      answerMD:
        "The base design uses an aggregate status for clarity. In production, store per-recipient receipts and derive aggregate **Delivered** and **Read** from them.",
    },
    {
      question: "Can a sender message a chat they do not belong to?",
      answerMD:
        "No. The mediator resolves the chat and asks the chat to validate membership before creating or routing the message.",
    },
    {
      question: "What happens when a recipient is offline?",
      answerMD:
        "The delivery strategy decides. The default strategy delivers only to online users; an offline recipient remains a production extension through queues and device fanout.",
    },
    {
      question: "Do group admins and roles matter in the core design?",
      answerMD:
        "Not for the first pass. Model add/remove membership on **GroupChat**, then mention roles as an extension.",
    },
  ],

  classDiagramMermaid: [
    "classDiagram",
    "    class User {",
    "        -String id",
    "        -String displayName",
    "        -boolean online",
    "        +receive(Message) void",
    "        +onStatusChanged(Message, MessageStatus, MessageStatus) void",
    "    }",
    "    class StatusObserver {",
    "        <<interface>>",
    "        +onStatusChanged(Message, MessageStatus, MessageStatus) void",
    "    }",
    "    class Message {",
    "        -String id",
    "        -String chatId",
    "        -User sender",
    "        -MessageState state",
    "        +markDelivered() void",
    "        +markRead() void",
    "        +status() MessageStatus",
    "    }",
    "    class MessageStatus {",
    "        <<enumeration>>",
    "        SENT",
    "        DELIVERED",
    "        READ",
    "    }",
    "    class MessageState {",
    "        <<interface>>",
    "        +status() MessageStatus",
    "        +deliver() MessageState",
    "        +read() MessageState",
    "    }",
    "    class Chat {",
    "        <<abstract>>",
    "        -String id",
    "        -List~Message~ messages",
    "        +recipientsFor(String) List~User~",
    "        +record(Message) void",
    "    }",
    "    class OneToOneChat",
    "    class GroupChat {",
    "        -Map~String,User~ members",
    "        +addMember(User) void",
    "        +removeMember(String) void",
    "    }",
    "    class ChatServer {",
    "        -Map~String,User~ users",
    "        -Map~String,Chat~ chats",
    "        -Map~String,Message~ messages",
    "        -DeliveryPolicy deliveryPolicy",
    "        +sendMessage(String, String, String) Message",
    "        +markRead(String, String) void",
    "    }",
    "    class DeliveryPolicy {",
    "        <<interface>>",
    "        +shouldDeliver(User) boolean",
    "    }",
    "    StatusObserver <|.. User",
    "    Message --> User",
    "    Message --> MessageStatus",
    "    Message --> MessageState",
    "    Message o-- StatusObserver",
    "    Chat o-- Message",
    "    Chat <|-- OneToOneChat",
    "    Chat <|-- GroupChat",
    "    GroupChat o-- User",
    "    ChatServer o-- User",
    "    ChatServer o-- Chat",
    "    ChatServer ..> DeliveryPolicy",
    "    ChatServer ..> Message",
  ].join("\n"),
  classDiagramCaptionMD:
    "**ChatServer** is the mediator boundary. **Chat** variants own participant rules, **Message** owns the receipt lifecycle, and **User** observes status changes instead of driving routing.",

  sequenceDiagramMermaid: [
    "sequenceDiagram",
    "    actor Sender",
    "    participant Server as ChatServer",
    "    participant Chat",
    "    participant Msg as Message",
    "    participant Recipient",
    "    participant Obs as StatusObserver",
    "    Sender->>Server: sendMessage(chatId, senderId, text)",
    "    Server->>Chat: requireMember(senderId)",
    "    Server->>Msg: new Message(status Sent)",
    "    Server->>Chat: record(message)",
    "    Server->>Chat: recipientsFor(senderId)",
    "    Server->>Recipient: receive(message)",
    "    Server->>Msg: markDelivered()",
    "    Msg-->>Obs: onStatusChanged(Sent, Delivered)",
    "    Recipient->>Server: markRead(messageId, recipientId)",
    "    Server->>Chat: requireMember(recipientId)",
    "    Server->>Msg: markRead()",
    "    Msg-->>Obs: onStatusChanged(Delivered, Read)",
  ].join("\n"),
  sequenceDiagramCaptionMD:
    "The sender never calls the recipient directly. The mediator validates the sender, asks the chat for recipients, applies a delivery strategy, and lets the message state machine publish receipt changes.",

  entities: [
    {
      name: "User",
      responsibilityMD:
        "Represents an account participating in chats. It can receive routed messages and observe status updates, but it does not locate or contact other users directly.",
      attributes: ["id", "displayName", "online", "inbox"],
    },
    {
      name: "Message",
      responsibilityMD:
        "Immutable message identity, chat id, sender, text, timestamp, and mutable delivery state. It notifies observers after successful lifecycle transitions.",
      attributes: ["id", "chatId", "sender", "text", "createdAt", "state"],
    },
    {
      name: "MessageStatus / MessageState",
      responsibilityMD:
        "Encodes the **Sent -> Delivered -> Read** lifecycle. State objects decide whether a transition is allowed, avoiding scattered if-else checks.",
      attributes: ["SENT", "DELIVERED", "READ", "deliver", "read"],
    },
    {
      name: "StatusObserver",
      responsibilityMD:
        "Observer contract for receipt updates. Users, mobile sessions, analytics, or notification adapters can subscribe without changing **Message**.",
      attributes: ["onStatusChanged"],
    },
    {
      name: "Chat",
      responsibilityMD:
        "Abstract conversation boundary. It stores message history and exposes membership-aware recipient lookup while subclasses enforce participant rules.",
      attributes: ["id", "messages", "participants", "recipientsFor"],
    },
    {
      name: "OneToOneChat",
      responsibilityMD:
        "A chat with exactly two distinct users. It rejects non-members and computes the single recipient for a sender.",
      attributes: ["first", "second"],
    },
    {
      name: "GroupChat",
      responsibilityMD:
        "A chat with a mutable set of members. It centralizes add, remove, and membership validation for group conversations.",
      attributes: ["members", "addMember", "removeMember"],
    },
    {
      name: "ChatServer",
      responsibilityMD:
        "Mediator and aggregate service. It registers users, creates chats, routes messages, records messages, applies delivery policy, and handles read receipts.",
      attributes: ["users", "chats", "messages", "deliveryPolicy"],
    },
    {
      name: "DeliveryPolicy",
      responsibilityMD:
        "Strategy for deciding whether a recipient should receive a message immediately. The demo uses online-only delivery.",
      attributes: ["shouldDeliver"],
    },
  ],

  patternsUsed: [
    {
      name: "Mediator",
      whyMD:
        "**ChatServer** coordinates user lookup, chat lookup, membership validation, routing, storage of message references, and receipt actions. Users remain independent participants rather than directly depending on each other.",
    },
    {
      name: "Observer",
      whyMD:
        "**Message** publishes status transitions to **StatusObserver** instances. UI sessions, sender devices, analytics, and notifications can react without being hard-coded into the message state machine.",
    },
    {
      name: "State",
      whyMD:
        "**MessageState** implementations encode which transition is legal from **Sent**, **Delivered**, and **Read**. This makes the lifecycle explicit and prevents invalid boolean combinations.",
    },
    {
      name: "Strategy",
      whyMD:
        "**DeliveryPolicy** decides whether to deliver now. Online-only delivery, durable queues, priority fanout, or retry-aware delivery can be swapped without editing **ChatServer.sendMessage**.",
    },
  ],

  designSteps: [
    {
      title: "Put routing behind a mediator",
      detailMD:
        "Make **ChatServer** the only object that resolves users and chats. A sender asks the server to send; the server validates membership, creates the message, records it, and routes to recipients.",
      code: [
        "public Message sendMessage(String chatId, String senderId, String text) {",
        "    Chat chat = chat(chatId);",
        "    User sender = user(senderId);",
        "    chat.requireMember(senderId);",
        "    Message message = new Message(nextMessageId(), chatId, sender, text);",
        "    chat.record(message);",
        "    return message;",
        "}",
      ].join("\n"),
    },
    {
      title: "Make chats own participant rules",
      detailMD:
        "**OneToOneChat** enforces exactly two users. **GroupChat** owns its member map and exposes add/remove operations. The server asks the chat for recipients instead of duplicating rules.",
    },
    {
      title: "Represent receipts as a state machine",
      detailMD:
        "The lifecycle is **Sent -> Delivered -> Read**. A **SentState** can deliver, a **DeliveredState** can read, and **ReadState** is terminal.",
      code: [
        "interface MessageState {",
        "    MessageStatus status();",
        "    MessageState deliver();",
        "    MessageState read();",
        "}",
      ].join("\n"),
    },
    {
      title: "Notify observers after successful transitions",
      detailMD:
        "**Message.transition** captures the previous status, installs the next state, and notifies observers. Failed transitions throw before any observer sees a false update.",
      code: [
        "private void transition(MessageState next) {",
        "    MessageStatus oldStatus = status();",
        "    if (oldStatus == next.status()) {",
        "        return;",
        "    }",
        "    state = next;",
        "    notifyObservers(oldStatus, status());",
        "}",
      ].join("\n"),
    },
    {
      title: "Keep delivery decisions swappable",
      detailMD:
        "The first policy is simple: deliver only to online recipients. In a real system this policy can enqueue offline delivery, fan out to multiple devices, or apply priority without changing chat membership logic.",
    },
    {
      title: "Store enough references for read receipts",
      detailMD:
        "**ChatServer** keeps a message map so **markRead** can find the message, validate the reader against the owning chat, and ask **Message** to move from **Delivered** to **Read**.",
    },
  ],

  implementation: [
    {
      filename: "User.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class User implements StatusObserver {",
        "    private final String id;",
        "    private final String displayName;",
        "    private boolean online = true;",
        "    private final List<String> inbox = new ArrayList<>();",
        "",
        "    public User(String id, String displayName) {",
        "        this.id = requireText(id, \"id\");",
        "        this.displayName = requireText(displayName, \"displayName\");",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String displayName() {",
        "        return displayName;",
        "    }",
        "",
        "    public boolean isOnline() {",
        "        return online;",
        "    }",
        "",
        "    public void setOnline(boolean online) {",
        "        this.online = online;",
        "    }",
        "",
        "    public void receive(Message message) {",
        "        Objects.requireNonNull(message, \"message\");",
        "        inbox.add(\"Message \" + message.id() + \" from \" + message.sender().displayName() + \": \" + message.text());",
        "    }",
        "",
        "    @Override",
        "    public void onStatusChanged(Message message, MessageStatus oldStatus, MessageStatus newStatus) {",
        "        inbox.add(\"Message \" + message.id() + \" moved from \" + oldStatus + \" to \" + newStatus);",
        "    }",
        "",
        "    public List<String> inbox() {",
        "        return Collections.unmodifiableList(inbox);",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Message.java",
      language: "java",
      content: [
        "import java.time.Instant;",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.Objects;",
        "import java.util.UUID;",
        "",
        "public final class Message {",
        "    private final String id;",
        "    private final String chatId;",
        "    private final User sender;",
        "    private final String text;",
        "    private final Instant createdAt;",
        "    private final List<StatusObserver> observers = new ArrayList<>();",
        "    private MessageState state = new SentState();",
        "",
        "    public Message(String id, String chatId, User sender, String text) {",
        "        this.id = id == null || id.isBlank() ? UUID.randomUUID().toString() : id;",
        "        this.chatId = requireText(chatId, \"chatId\");",
        "        this.sender = Objects.requireNonNull(sender, \"sender\");",
        "        this.text = requireText(text, \"text\");",
        "        this.createdAt = Instant.now();",
        "    }",
        "",
        "    public String id() {",
        "        return id;",
        "    }",
        "",
        "    public String chatId() {",
        "        return chatId;",
        "    }",
        "",
        "    public User sender() {",
        "        return sender;",
        "    }",
        "",
        "    public String text() {",
        "        return text;",
        "    }",
        "",
        "    public Instant createdAt() {",
        "        return createdAt;",
        "    }",
        "",
        "    public MessageStatus status() {",
        "        return state.status();",
        "    }",
        "",
        "    public void addObserver(StatusObserver observer) {",
        "        Objects.requireNonNull(observer, \"observer\");",
        "        if (!observers.contains(observer)) {",
        "            observers.add(observer);",
        "        }",
        "    }",
        "",
        "    public void markDelivered() {",
        "        transition(state.deliver());",
        "    }",
        "",
        "    public void markRead() {",
        "        transition(state.read());",
        "    }",
        "",
        "    private void transition(MessageState next) {",
        "        MessageStatus oldStatus = status();",
        "        if (oldStatus == next.status()) {",
        "            return;",
        "        }",
        "        state = next;",
        "        notifyObservers(oldStatus, status());",
        "    }",
        "",
        "    private void notifyObservers(MessageStatus oldStatus, MessageStatus newStatus) {",
        "        for (StatusObserver observer : new ArrayList<>(observers)) {",
        "            observer.onStatusChanged(this, oldStatus, newStatus);",
        "        }",
        "    }",
        "",
        "    private static String requireText(String value, String field) {",
        "        if (value == null || value.isBlank()) {",
        "            throw new IllegalArgumentException(field + \" is required\");",
        "        }",
        "        return value;",
        "    }",
        "",
        "    @Override",
        "    public String toString() {",
        "        return \"Message{id='\" + id + \"', chatId='\" + chatId + \"', status=\" + status() + \"}\";",
        "    }",
        "}",
        "",
        "enum MessageStatus {",
        "    SENT, DELIVERED, READ",
        "}",
        "",
        "interface MessageState {",
        "    MessageStatus status();",
        "",
        "    MessageState deliver();",
        "",
        "    MessageState read();",
        "}",
        "",
        "final class SentState implements MessageState {",
        "    @Override",
        "    public MessageStatus status() {",
        "        return MessageStatus.SENT;",
        "    }",
        "",
        "    @Override",
        "    public MessageState deliver() {",
        "        return new DeliveredState();",
        "    }",
        "",
        "    @Override",
        "    public MessageState read() {",
        "        throw new IllegalStateException(\"message must be delivered before it can be read\");",
        "    }",
        "}",
        "",
        "final class DeliveredState implements MessageState {",
        "    @Override",
        "    public MessageStatus status() {",
        "        return MessageStatus.DELIVERED;",
        "    }",
        "",
        "    @Override",
        "    public MessageState deliver() {",
        "        return this;",
        "    }",
        "",
        "    @Override",
        "    public MessageState read() {",
        "        return new ReadState();",
        "    }",
        "}",
        "",
        "final class ReadState implements MessageState {",
        "    @Override",
        "    public MessageStatus status() {",
        "        return MessageStatus.READ;",
        "    }",
        "",
        "    @Override",
        "    public MessageState deliver() {",
        "        return this;",
        "    }",
        "",
        "    @Override",
        "    public MessageState read() {",
        "        return this;",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "StatusObserver.java",
      language: "java",
      content: [
        "public interface StatusObserver {",
        "    void onStatusChanged(Message message, MessageStatus oldStatus, MessageStatus newStatus);",
        "}",
      ].join("\n"),
    },
    {
      filename: "Chat.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collections;",
        "import java.util.List;",
        "",
        "public abstract class Chat {",
        "    private final String id;",
        "    private final List<Message> messages = new ArrayList<>();",
        "",
        "    protected Chat(String id) {",
        "        if (id == null || id.isBlank()) {",
        "            throw new IllegalArgumentException(\"chat id is required\");",
        "        }",
        "        this.id = id;",
        "    }",
        "",
        "    public final String id() {",
        "        return id;",
        "    }",
        "",
        "    public final void record(Message message) {",
        "        if (!id.equals(message.chatId())) {",
        "            throw new IllegalArgumentException(\"message belongs to another chat\");",
        "        }",
        "        messages.add(message);",
        "    }",
        "",
        "    public final List<Message> history() {",
        "        return Collections.unmodifiableList(messages);",
        "    }",
        "",
        "    public final List<User> recipientsFor(String senderId) {",
        "        requireMember(senderId);",
        "        List<User> recipients = new ArrayList<>();",
        "        for (User participant : participants()) {",
        "            if (!participant.id().equals(senderId)) {",
        "                recipients.add(participant);",
        "            }",
        "        }",
        "        return recipients;",
        "    }",
        "",
        "    public abstract List<User> participants();",
        "",
        "    public abstract void requireMember(String userId);",
        "",
        "    public void addMember(User user) {",
        "        throw new UnsupportedOperationException(\"chat type does not support adding members\");",
        "    }",
        "",
        "    public void removeMember(String userId) {",
        "        throw new UnsupportedOperationException(\"chat type does not support removing members\");",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "OneToOneChat.java",
      language: "java",
      content: [
        "import java.util.List;",
        "import java.util.Objects;",
        "",
        "public final class OneToOneChat extends Chat {",
        "    private final User first;",
        "    private final User second;",
        "",
        "    public OneToOneChat(String id, User first, User second) {",
        "        super(id);",
        "        this.first = Objects.requireNonNull(first, \"first\");",
        "        this.second = Objects.requireNonNull(second, \"second\");",
        "        if (first.id().equals(second.id())) {",
        "            throw new IllegalArgumentException(\"one-to-one chat needs two distinct users\");",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public List<User> participants() {",
        "        return List.of(first, second);",
        "    }",
        "",
        "    @Override",
        "    public void requireMember(String userId) {",
        "        if (!first.id().equals(userId) && !second.id().equals(userId)) {",
        "            throw new IllegalArgumentException(\"user is not a member of this chat\");",
        "        }",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "GroupChat.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collection;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class GroupChat extends Chat {",
        "    private final Map<String, User> members = new LinkedHashMap<>();",
        "",
        "    public GroupChat(String id, Collection<User> initialMembers) {",
        "        super(id);",
        "        if (initialMembers == null || initialMembers.size() < 2) {",
        "            throw new IllegalArgumentException(\"group chat needs at least two users\");",
        "        }",
        "        for (User user : initialMembers) {",
        "            addMember(user);",
        "        }",
        "        if (members.size() < 2) {",
        "            throw new IllegalArgumentException(\"group chat needs at least two distinct users\");",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public List<User> participants() {",
        "        return new ArrayList<>(members.values());",
        "    }",
        "",
        "    @Override",
        "    public void requireMember(String userId) {",
        "        if (!members.containsKey(userId)) {",
        "            throw new IllegalArgumentException(\"user is not a member of this group\");",
        "        }",
        "    }",
        "",
        "    @Override",
        "    public void addMember(User user) {",
        "        Objects.requireNonNull(user, \"user\");",
        "        members.putIfAbsent(user.id(), user);",
        "    }",
        "",
        "    @Override",
        "    public void removeMember(String userId) {",
        "        requireMember(userId);",
        "        if (members.size() <= 2) {",
        "            throw new IllegalStateException(\"cannot reduce a group below two members\");",
        "        }",
        "        members.remove(userId);",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "ChatServer.java",
      language: "java",
      content: [
        "import java.util.ArrayList;",
        "import java.util.Collection;",
        "import java.util.LinkedHashMap;",
        "import java.util.List;",
        "import java.util.Map;",
        "import java.util.Objects;",
        "",
        "public final class ChatServer {",
        "    private final Map<String, User> users = new LinkedHashMap<>();",
        "    private final Map<String, Chat> chats = new LinkedHashMap<>();",
        "    private final Map<String, Message> messages = new LinkedHashMap<>();",
        "    private final DeliveryPolicy deliveryPolicy;",
        "    private int messageSequence = 1;",
        "",
        "    public ChatServer(DeliveryPolicy deliveryPolicy) {",
        "        this.deliveryPolicy = Objects.requireNonNull(deliveryPolicy, \"deliveryPolicy\");",
        "    }",
        "",
        "    public void registerUser(User user) {",
        "        Objects.requireNonNull(user, \"user\");",
        "        users.putIfAbsent(user.id(), user);",
        "    }",
        "",
        "    public Chat createOneToOneChat(String chatId, String firstUserId, String secondUserId) {",
        "        Chat chat = new OneToOneChat(chatId, user(firstUserId), user(secondUserId));",
        "        chats.put(chatId, chat);",
        "        return chat;",
        "    }",
        "",
        "    public Chat createGroupChat(String chatId, Collection<String> memberIds) {",
        "        List<User> members = new ArrayList<>();",
        "        for (String memberId : memberIds) {",
        "            members.add(user(memberId));",
        "        }",
        "        Chat chat = new GroupChat(chatId, members);",
        "        chats.put(chatId, chat);",
        "        return chat;",
        "    }",
        "",
        "    public void addUserToGroup(String chatId, String userId) {",
        "        chat(chatId).addMember(user(userId));",
        "    }",
        "",
        "    public Message sendMessage(String chatId, String senderId, String text) {",
        "        Chat chat = chat(chatId);",
        "        User sender = user(senderId);",
        "        chat.requireMember(senderId);",
        "",
        "        Message message = new Message(nextMessageId(), chatId, sender, text);",
        "        message.addObserver(sender);",
        "        for (User participant : chat.participants()) {",
        "            message.addObserver(participant);",
        "        }",
        "",
        "        chat.record(message);",
        "        messages.put(message.id(), message);",
        "",
        "        boolean delivered = false;",
        "        for (User recipient : chat.recipientsFor(senderId)) {",
        "            if (deliveryPolicy.shouldDeliver(recipient)) {",
        "                recipient.receive(message);",
        "                delivered = true;",
        "            }",
        "        }",
        "        if (delivered) {",
        "            message.markDelivered();",
        "        }",
        "        return message;",
        "    }",
        "",
        "    public void markRead(String messageId, String readerId) {",
        "        Message message = message(messageId);",
        "        Chat chat = chat(message.chatId());",
        "        chat.requireMember(readerId);",
        "        if (message.sender().id().equals(readerId)) {",
        "            throw new IllegalArgumentException(\"sender cannot mark the message as read\");",
        "        }",
        "        message.markRead();",
        "    }",
        "",
        "    private String nextMessageId() {",
        "        return \"m-\" + messageSequence++;",
        "    }",
        "",
        "    private User user(String userId) {",
        "        User user = users.get(userId);",
        "        if (user == null) {",
        "            throw new IllegalArgumentException(\"unknown user: \" + userId);",
        "        }",
        "        return user;",
        "    }",
        "",
        "    private Chat chat(String chatId) {",
        "        Chat chat = chats.get(chatId);",
        "        if (chat == null) {",
        "            throw new IllegalArgumentException(\"unknown chat: \" + chatId);",
        "        }",
        "        return chat;",
        "    }",
        "",
        "    private Message message(String messageId) {",
        "        Message message = messages.get(messageId);",
        "        if (message == null) {",
        "            throw new IllegalArgumentException(\"unknown message: \" + messageId);",
        "        }",
        "        return message;",
        "    }",
        "}",
        "",
        "interface DeliveryPolicy {",
        "    boolean shouldDeliver(User recipient);",
        "}",
        "",
        "final class OnlineDeliveryPolicy implements DeliveryPolicy {",
        "    @Override",
        "    public boolean shouldDeliver(User recipient) {",
        "        return recipient.isOnline();",
        "    }",
        "}",
      ].join("\n"),
    },
    {
      filename: "Main.java",
      language: "java",
      content: [
        "import java.util.List;",
        "",
        "public class Main {",
        "    public static void main(String[] args) {",
        "        ChatServer server = new ChatServer(new OnlineDeliveryPolicy());",
        "",
        "        User alice = new User(\"u1\", \"Alice\");",
        "        User bob = new User(\"u2\", \"Bob\");",
        "        User charlie = new User(\"u3\", \"Charlie\");",
        "",
        "        server.registerUser(alice);",
        "        server.registerUser(bob);",
        "        server.registerUser(charlie);",
        "",
        "        server.createOneToOneChat(\"c1\", \"u1\", \"u2\");",
        "        Message hello = server.sendMessage(\"c1\", \"u1\", \"Hi Bob\");",
        "        server.markRead(hello.id(), \"u2\");",
        "",
        "        server.createGroupChat(\"g1\", List.of(\"u1\", \"u2\", \"u3\"));",
        "        Message groupMessage = server.sendMessage(\"g1\", \"u2\", \"Dinner at 8\");",
        "",
        "        System.out.println(hello);",
        "        System.out.println(groupMessage);",
        "        System.out.println(alice.inbox());",
        "    }",
        "}",
      ].join("\n"),
    },
  ],

  classExplanations: [
    {
      className: "User",
      detailMD:
        "Represents a participant and implements **StatusObserver**. It receives routed messages and receipt updates, but it never finds recipients or writes to another user directly.",
    },
    {
      className: "Message",
      detailMD:
        "Carries message identity, chat id, sender, text, creation time, observers, and the current **MessageState**. It exposes **markDelivered** and **markRead** as the only lifecycle mutation methods.",
    },
    {
      className: "MessageStatus / MessageState",
      detailMD:
        "**MessageStatus** names the visible states. **SentState**, **DeliveredState**, and **ReadState** encode allowed transitions so **Read** cannot happen before **Delivered**.",
    },
    {
      className: "StatusObserver",
      detailMD:
        "Small observer interface used by **Message** to publish status transitions. The demo uses users as observers; production can attach sessions, web sockets, metrics, or notifications.",
    },
    {
      className: "Chat",
      detailMD:
        "Abstract conversation base. It stores message history and provides **recipientsFor**, while forcing subclasses to define participant lookup and membership validation.",
    },
    {
      className: "OneToOneChat",
      detailMD:
        "Concrete chat with exactly two distinct users. It keeps the one-to-one invariant local and rejects any operation from a non-member.",
    },
    {
      className: "GroupChat",
      detailMD:
        "Concrete chat backed by a member map. It centralizes group add, remove, participant listing, and membership validation.",
    },
    {
      className: "ChatServer",
      detailMD:
        "The mediator. It owns registries of users, chats, and messages; creates chats; validates senders and readers; routes messages; and triggers delivery/read status transitions.",
    },
    {
      className: "DeliveryPolicy / OnlineDeliveryPolicy",
      detailMD:
        "Strategy seam for delivery decisions. **OnlineDeliveryPolicy** is the simple demo implementation; queue-backed or device-aware policies can replace it.",
    },
    {
      className: "Main",
      detailMD:
        "Executable walkthrough that registers users, creates one-to-one and group chats, sends messages, marks one as read, and prints resulting state.",
    },
  ],

  dryRun: {
    inputMD:
      "Users **Alice**, **Bob**, and **Charlie** are registered. Chat **c1** is Alice/Bob. Group **g1** contains all three. All users are online.",
    columns: ["Step", "Action", "Mediator decision", "Recipients", "Message status", "Observer update"],
    rows: [
      [
        "1",
        "Alice sends 'Hi Bob' in c1",
        "Validate Alice belongs to c1 and create m-1",
        "Bob",
        "Sent -> Delivered",
        "Alice and Bob receive Delivered receipt",
      ],
      [
        "2",
        "Bob marks m-1 as read",
        "Validate Bob belongs to c1 and is not sender",
        "None",
        "Delivered -> Read",
        "Alice and Bob receive Read receipt",
      ],
      [
        "3",
        "Bob sends 'Dinner at 8' in g1",
        "Validate Bob belongs to g1 and record m-2",
        "Alice, Charlie",
        "Sent -> Delivered",
        "All group observers receive Delivered receipt",
      ],
      [
        "4",
        "Charlie goes offline, Alice sends again",
        "DeliveryPolicy skips Charlie and delivers to Bob",
        "Bob",
        "Sent -> Delivered",
        "Observers see aggregate Delivered; per-user pending is an extension",
      ],
    ],
    narrativeMD:
      "The dry run shows the mediator doing validation and routing, while **Message** alone changes status. Step 4 highlights the simplification in this LLD: aggregate status is easy to explain, and per-recipient receipt rows are the production extension.",
  },

  complexity: [
    {
      operation: "registerUser",
      time: "O(1)",
      space: "O(1)",
      note: "Hash-map insertion by user id.",
    },
    {
      operation: "createOneToOneChat",
      time: "O(1)",
      space: "O(1)",
      note: "Lookup two users and store one chat object.",
    },
    {
      operation: "createGroupChat",
      time: "O(M)",
      space: "O(M)",
      note: "M initial members are resolved and copied into the group member map.",
    },
    {
      operation: "sendMessage",
      time: "O(P)",
      space: "O(P)",
      note: "P participants are scanned for observers and recipients. Message creation and maps are constant time.",
    },
    {
      operation: "markRead",
      time: "O(1)",
      space: "O(1)",
      note: "Lookup message and chat, validate membership by map for groups, then transition state.",
    },
    {
      operation: "history",
      time: "O(1)",
      space: "O(1)",
      note: "The sample returns an unmodifiable view. A defensive copy would be O(H).",
    },
  ],
  complexityNotesMD:
    "For interview LLD, **P** is participants in a chat and **M** is group members at creation. At WhatsApp scale, routing becomes asynchronous fanout and receipt updates become per-recipient records, but the same object seams remain useful.",

  extensibility: [
    {
      label: "Per-recipient receipts",
      detailMD:
        "Replace the aggregate **MessageState** with a map from user id to receipt state, then derive chat-level status as all delivered or all read.",
    },
    {
      label: "Offline delivery queue",
      detailMD:
        "Add a queue-backed **DeliveryPolicy** or **DeliveryStrategy** that stores pending deliveries and retries when a user reconnects.",
    },
    {
      label: "Group roles",
      detailMD:
        "Extend **GroupChat** membership values from **User** to **GroupMember** with role and joinedAt fields. Add admin checks inside add/remove operations.",
    },
    {
      label: "Media messages",
      detailMD:
        "Introduce a **MessageContent** strategy or hierarchy for text, image, audio, and document payloads while keeping routing unchanged.",
    },
    {
      label: "Multiple devices per user",
      detailMD:
        "Let **User** own devices or sessions, and make delivery fan out to active devices through observers or adapters.",
    },
  ],

  alternativeDesigns: [
    {
      name: "Direct user-to-user messaging",
      detailMD:
        "Let **User.sendTo(User, text)** call the recipient directly and update receipts locally.",
      tradeoffsMD:
        "Simple demo code, but it couples users, duplicates membership checks, makes group routing awkward, and hides the mediator boundary interviewers expect.",
    },
    {
      name: "Event bus instead of direct observers",
      detailMD:
        "Publish **MessageStatusChanged** events to a bus and let UI, notification, and analytics consumers subscribe independently.",
      tradeoffsMD:
        "Closer to production and easier to scale, but more infrastructure than necessary for a focused LLD unless the interviewer asks for async processing.",
    },
    {
      name: "Per-recipient receipt aggregate",
      detailMD:
        "Model **MessageReceipt** objects for every recipient and store status, deliveredAt, and readAt per user.",
      tradeoffsMD:
        "More accurate for groups and offline users, but adds storage and aggregation complexity. Use it as a follow-up after the base state machine is clear.",
    },
  ],

  commonMistakes: [
    "Letting **User** directly call other **User** objects, which removes the mediator and spreads routing rules everywhere.",
    "Representing status with booleans such as **isSent**, **isDelivered**, and **isRead**, which permits impossible combinations.",
    "Skipping membership validation before sending or marking a message read.",
    "Putting group add/remove logic in **ChatServer** instead of inside **GroupChat**.",
    "Hard-coding online-only delivery inside message state rather than behind a strategy.",
    "Notifying observers before the state transition succeeds.",
    "Treating group read receipts as a single boolean without explaining per-recipient receipt extension.",
  ],

  followUps: [
    {
      question: "How would you support per-recipient delivery and read receipts in groups?",
      answerMD:
        "Create **MessageReceipt** per recipient with status, deliveredAt, and readAt. The message can derive aggregate state from the receipt collection while individual users see precise receipt status.",
    },
    {
      question: "How do offline users eventually receive messages?",
      answerMD:
        "Replace **OnlineDeliveryPolicy** with a queue-backed strategy. The mediator writes pending deliveries, and reconnect logic drains the queue through the same receive path.",
    },
    {
      question: "Where would end-to-end encryption fit?",
      answerMD:
        "As a boundary service before message creation and after delivery. The mediator should route encrypted payloads without needing to inspect clear text.",
    },
    {
      question: "How do you prevent non-members from reading group history?",
      answerMD:
        "Keep **Chat.requireMember** on all read paths, not only send paths. For historical access after removal, add membership intervals and check whether the user was a member at message time.",
    },
    {
      question: "How would you make status notifications reliable?",
      answerMD:
        "Persist status changes and publish them through an event bus or outbox. Observers become adapters consuming durable events instead of in-memory callbacks.",
    },
  ],

  productionConsiderations: [
    {
      label: "Durable message store",
      detailMD:
        "Persist messages, chat membership, and receipts. The in-memory maps become repositories or DAO interfaces behind **ChatServer**.",
    },
    {
      label: "Per-device fanout",
      detailMD:
        "A user may have phone, desktop, and web sessions. Delivery policy should fan out to devices and aggregate acknowledgements carefully.",
    },
    {
      label: "Ordering and idempotency",
      detailMD:
        "Assign monotonic sequence numbers per chat and make send/read operations idempotent so retries do not duplicate messages or regress status.",
    },
    {
      label: "Privacy and encryption",
      detailMD:
        "Keep encryption outside the domain routing model, but ensure the server never needs plaintext to validate membership or route messages.",
    },
    {
      label: "Observability",
      detailMD:
        "Track send latency, delivery lag, read lag, observer failures, and queue depth. Receipt lifecycle metrics are essential for debugging user-visible delays.",
    },
  ],

  interviewNotes: [
    "Did the candidate make **ChatServer** a mediator instead of direct user coupling?",
    "Is the **Sent -> Delivered -> Read** lifecycle explicit and protected from invalid transitions?",
    "Are one-to-one and group membership rules owned by the chat classes?",
    "Can delivery policy change without rewriting the message or chat models?",
    "Are observers used for status updates without mixing UI concerns into **Message**?",
    "Does the candidate acknowledge per-recipient receipts as the realistic group-chat extension?",
  ],

  quiz: [
    {
      question: "Why is **ChatServer** modelled as a Mediator?",
      options: [
        "It centralizes user lookup, membership validation, and routing so users do not call each other directly",
        "It makes every operation O(1) regardless of group size",
        "It replaces the need for chat objects",
        "It is required only when messages are encrypted",
      ],
      answerIndex: 0,
      explanationMD:
        "The mediator keeps participants loosely coupled and gives one place to coordinate routing rules.",
    },
    {
      question: "What problem does the State pattern solve for message receipts?",
      options: [
        "It stores messages in sorted order",
        "It prevents invalid lifecycle transitions such as **Sent** directly to **Read**",
        "It chooses which recipient is online",
        "It compresses message text",
      ],
      answerIndex: 1,
      explanationMD:
        "State objects encode what transition is legal from the current status, so invalid combinations cannot appear.",
    },
    {
      question: "Which class should own group add/remove membership rules?",
      options: [
        "User",
        "Message",
        "GroupChat",
        "StatusObserver",
      ],
      answerIndex: 2,
      explanationMD:
        "**GroupChat** owns its member map, so membership invariants stay local to the group conversation.",
    },
    {
      question: "Why is **DeliveryPolicy** a Strategy?",
      options: [
        "It lets the system swap online-only delivery for queued or device-aware delivery without changing send flow",
        "It notifies observers after status changes",
        "It makes **Message** immutable",
        "It creates one-to-one chats automatically",
      ],
      answerIndex: 0,
      explanationMD:
        "Strategy isolates delivery decisions from mediator orchestration.",
    },
    {
      question: "In a production group chat, what is the usual improvement over one aggregate message status?",
      options: [
        "Remove read receipts entirely",
        "Store one **MessageReceipt** per recipient and derive aggregate status",
        "Put all receipt fields on **User**",
        "Use direct user-to-user callbacks",
      ],
      answerIndex: 1,
      explanationMD:
        "Groups need per-recipient precision because one member can read while another remains offline.",
    },
  ],

  practiceVariants: [
    {
      title: "Add per-recipient receipts",
      detailMD:
        "Introduce **MessageReceipt** with recipient, status, deliveredAt, and readAt. Update the mediator to transition a single recipient receipt at a time.",
      difficulty: "Advanced",
    },
    {
      title: "Support group admins",
      detailMD:
        "Change group membership from user map to member-role map. Enforce that only admins can add or remove members.",
      difficulty: "Intermediate",
    },
    {
      title: "Queue offline delivery",
      detailMD:
        "Replace **OnlineDeliveryPolicy** with a strategy that enqueues undelivered messages and drains them when **User.setOnline(true)** is observed.",
      difficulty: "Expert",
    },
  ],

  flashcards: [
    {
      front: "What is the mediator in this WhatsApp LLD?",
      back: "**ChatServer**. It coordinates users, chats, message creation, routing, delivery policy, and read receipts.",
    },
    {
      front: "What lifecycle should message status follow?",
      back: "**Sent -> Delivered -> Read**. The state machine prevents skipping **Delivered**.",
    },
    {
      front: "Why should **User** not call another **User** directly?",
      back: "Direct calls couple participants and duplicate membership/routing logic. The mediator keeps the model clean.",
    },
    {
      front: "Where do group membership rules live?",
      back: "**GroupChat** owns the member map and validates add, remove, and membership checks.",
    },
    {
      front: "What does Observer do in this design?",
      back: "**Message** notifies observers when status changes so UI, users, or adapters react without changing lifecycle code.",
    },
    {
      front: "What is the production extension for group read receipts?",
      back: "Store **MessageReceipt** per recipient and derive aggregate delivered/read state from those receipts.",
    },
  ],

  cheatSheetMD: [
    "**Entities:** User, Message, MessageStatus/MessageState, StatusObserver, Chat, OneToOneChat, GroupChat, ChatServer, DeliveryPolicy.",
    "",
    "**Patterns:** Mediator for routing, Observer for status updates, State for **Sent -> Delivered -> Read**, Strategy for delivery policy.",
    "",
    "**Core flow:** sender calls **ChatServer.sendMessage** → server validates membership → creates **Message** in **Sent** → records in **Chat** → routes recipients through **DeliveryPolicy** → marks **Delivered** → observer notifications fire.",
    "",
    "**Read flow:** recipient calls **markRead** → server validates membership and non-sender → **MessageState** moves **Delivered** to **Read** → observers receive update.",
    "",
    "**Invariants:** no direct user-to-user routing; sender must be chat member; read cannot precede delivered; group membership rules stay in **GroupChat**.",
    "",
    "**Complexity:** send is O(P) for participants, group creation is O(M), read is O(1) in the in-memory model.",
    "",
    "**Extend:** per-recipient receipts, offline queues, group roles, media content, multi-device fanout.",
  ].join("\n"),

  references: [
    {
      title: "Design Patterns: Elements of Reusable Object-Oriented Software",
      kind: "Book",
      author: "Gamma, Helm, Johnson, Vlissides",
    },
    {
      title: "Enterprise Integration Patterns",
      kind: "Book",
      author: "Gregor Hohpe and Bobby Woolf",
    },
    {
      title: "Refactoring Guru — Mediator",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/mediator",
    },
    {
      title: "Refactoring Guru — Observer",
      kind: "Docs",
      url: "https://refactoring.guru/design-patterns/observer",
    },
  ],

  relatedProblems: [
    { slug: "slack", note: "Another collaboration messaging design with channels and notification concerns." },
    { slug: "notification-system", note: "Observer and delivery fanout appear again as a dedicated notification problem." },
    { slug: "ai-chat-platform", note: "Conversation modelling and message lifecycle extend into AI chat products." },
  ],
};
