import type {
  SDCategory,
  SDCompany,
  SDDifficulty,
  SDQuestionMeta,
  SDTierMeta,
} from "./types";

/**
 * The System Design (HLD) registry — the single source of truth for the
 * dashboard. Adding a question to the catalog makes it appear on the dashboard
 * and in the learning path automatically; authoring its content file (and
 * flipping `status` to "published") makes its page render. No UI/route changes.
 */

// ---- Learning-path tiers ---------------------------------------------------

export const SD_TIERS: SDTierMeta[] = [
  {
    id: "foundations",
    label: "Foundations",
    emoji: "🟢",
    accent: "emerald",
    description:
      "Building-block systems every senior engineer must be able to design cold — caches, rate limiters, gateways, and stores.",
    order: 1,
  },
  {
    id: "common",
    label: "Common Interview Questions",
    emoji: "🔵",
    accent: "blue",
    description:
      "The product-scale designs asked most often at top companies — feeds, chat, storage, streaming, and marketplaces.",
    order: 2,
  },
  {
    id: "advanced",
    label: "Advanced Distributed Systems",
    emoji: "🟣",
    accent: "violet",
    description:
      "The distributed-systems primitives behind everything else — queues, locks, consensus, and multi-region data.",
    order: 3,
  },
  {
    id: "staff",
    label: "Staff / Principal",
    emoji: "🟠",
    accent: "orange",
    description:
      "Platform- and org-scale systems: control planes, schedulers, global routing, and multi-tenant SaaS.",
    order: 4,
  },
  {
    id: "ai",
    label: "AI System Design",
    emoji: "🔴",
    accent: "rose",
    description:
      "Designing the systems behind modern AI products — inference serving, retrieval, embeddings, and agents.",
    order: 5,
  },
];

// ---- Filter vocabularies ---------------------------------------------------

export const SD_DIFFICULTIES: SDDifficulty[] = [
  "Beginner",
  "Intermediate",
  "Advanced",
];

export const SD_CATEGORIES: SDCategory[] = [
  "Storage",
  "Messaging",
  "Social Media",
  "AI",
  "Distributed Systems",
  "Infrastructure",
  "Video",
  "Search",
  "E-Commerce",
  "Maps",
  "Monitoring",
  "Payments",
  "Scheduling",
];

export const SD_COMPANIES: SDCompany[] = [
  "Google",
  "Meta",
  "Amazon",
  "Microsoft",
  "Netflix",
  "Uber",
  "Airbnb",
  "Stripe",
  "Databricks",
  "OpenAI",
  "Snowflake",
  "LinkedIn",
];

// ---- Catalog ---------------------------------------------------------------

/**
 * Raw catalog in reading order (Foundations → AI). `addedOrder` is derived
 * below so items listed earlier are treated as "newer" for the Newest sort;
 * the three published exemplars sit at the top and therefore sort first.
 */
type RawMeta = Omit<SDQuestionMeta, "addedOrder">;

const RAW_CATALOG: RawMeta[] = [
  // 🟢 Foundations
  {
    slug: "url-shortener",
    title: "URL Shortener",
    summary:
      "Design a TinyURL-style service that maps billions of long URLs to short, unique, low-latency redirects.",
    tier: "foundations",
    difficulty: "Beginner",
    categories: ["Storage", "Distributed Systems"],
    companies: ["Amazon", "Microsoft", "Google", "Uber"],
    tags: ["Hashing", "Key Generation", "Caching", "Redirects", "Read-Heavy"],
    popularity: 98,
    frequency: "Very High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "rate-limiter",
    title: "Rate Limiter",
    summary:
      "Design a distributed rate limiter that throttles requests per client with predictable latency and accuracy.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Stripe", "Amazon", "Google", "Microsoft"],
    tags: ["Token Bucket", "Sliding Window", "Redis", "Throttling", "Concurrency"],
    popularity: 95,
    frequency: "Very High",
    estimatedMinutes: 45,
    status: "published",
  },
  {
    slug: "distributed-cache",
    title: "Distributed Cache",
    summary:
      "Design a horizontally-scalable cache like Redis/Memcached with sharding, eviction, and high hit rates.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Storage", "Distributed Systems"],
    companies: ["Amazon", "Meta", "Netflix", "Microsoft"],
    tags: ["Consistent Hashing", "Eviction", "Replication", "LRU", "Sharding"],
    popularity: 92,
    frequency: "Very High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "key-value-store",
    title: "Key-Value Store",
    summary:
      "Design a Dynamo-style distributed key-value store with tunable consistency and fault tolerance.",
    tier: "foundations",
    difficulty: "Advanced",
    categories: ["Storage", "Distributed Systems"],
    companies: ["Amazon", "Databricks", "Snowflake"],
    tags: ["Consistent Hashing", "Quorum", "Replication", "LSM Tree", "Gossip"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "logging-system",
    title: "Logging System",
    summary:
      "Design a high-throughput, searchable logging pipeline that ingests terabytes of logs per day.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Monitoring", "Infrastructure"],
    companies: ["Amazon", "Netflix", "Databricks"],
    tags: ["Ingestion", "Elasticsearch", "Kafka", "Retention", "Indexing"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "metrics-collection",
    title: "Metrics Collection",
    summary:
      "Design a time-series metrics system that collects, aggregates, and stores millions of data points per second.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Monitoring", "Infrastructure"],
    companies: ["Amazon", "Microsoft", "Databricks"],
    tags: ["Time Series", "Aggregation", "Downsampling", "Push vs Pull"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "monitoring-system",
    title: "Monitoring System",
    summary:
      "Design an end-to-end monitoring and alerting platform with dashboards, thresholds, and on-call routing.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Monitoring", "Infrastructure"],
    companies: ["Amazon", "Microsoft", "Netflix"],
    tags: ["Alerting", "Dashboards", "SLO", "Anomaly Detection"],
    popularity: 79,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "api-gateway",
    title: "API Gateway",
    summary:
      "Design an API gateway handling routing, auth, rate limiting, and observability for hundreds of services.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Amazon", "Netflix", "Stripe", "Microsoft"],
    tags: ["Routing", "Auth", "Rate Limiting", "Reverse Proxy"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "notification-service",
    title: "Notification Service",
    summary:
      "Design a multi-channel (push, SMS, email) notification service delivering billions of messages reliably.",
    tier: "foundations",
    difficulty: "Intermediate",
    categories: ["Messaging", "Infrastructure"],
    companies: ["Amazon", "Uber", "LinkedIn", "Airbnb"],
    tags: ["Fan-out", "Queues", "Idempotency", "Retries", "Templates"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "pastebin",
    title: "Pastebin",
    summary:
      "Design a Pastebin-style service for storing and sharing text snippets with expiry and access control.",
    tier: "foundations",
    difficulty: "Beginner",
    categories: ["Storage"],
    companies: ["Amazon", "Microsoft"],
    tags: ["Blob Storage", "Expiry", "Key Generation", "CDN"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 40,
    status: "published",
  },

  // 🔵 Common Interview Questions
  {
    slug: "twitter",
    title: "Twitter",
    summary:
      "Design a Twitter-scale microblogging platform: tweets, timelines, fan-out, and trending topics.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Social Media", "Distributed Systems"],
    companies: ["Meta", "Amazon", "LinkedIn", "Google"],
    tags: ["Fan-out", "Timeline", "Feed", "Caching", "Sharding"],
    popularity: 96,
    frequency: "Very High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "instagram",
    title: "Instagram",
    summary:
      "Design a photo-sharing social network with feeds, stories, media storage, and social graph.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Social Media", "Storage"],
    companies: ["Meta", "Google", "Amazon"],
    tags: ["Media Storage", "Feed", "CDN", "Social Graph"],
    popularity: 94,
    frequency: "Very High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "facebook-feed",
    title: "Facebook Feed",
    summary:
      "Design a news feed with ranking, fan-out, and real-time updates for billions of users.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Social Media"],
    companies: ["Meta", "LinkedIn", "Google"],
    tags: ["Feed Ranking", "Fan-out", "EdgeRank", "Caching"],
    popularity: 93,
    frequency: "Very High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "linkedin-feed",
    title: "LinkedIn Feed",
    summary:
      "Design a professional-network feed with relevance ranking, connections, and activity fan-out.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Social Media"],
    companies: ["LinkedIn", "Meta", "Microsoft"],
    tags: ["Feed", "Ranking", "Graph", "Fan-out"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "reddit",
    title: "Reddit",
    summary:
      "Design a community platform with subreddits, nested comments, voting, and hot/ranking algorithms.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Social Media"],
    companies: ["Amazon", "Meta", "Google"],
    tags: ["Voting", "Ranking", "Comments Tree", "Caching"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "tiktok",
    title: "TikTok",
    summary:
      "Design a short-video platform with a recommendation feed, upload pipeline, and global CDN delivery.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Video", "Social Media"],
    companies: ["Meta", "Google", "Netflix"],
    tags: ["Recommendation", "Video Pipeline", "CDN", "Feed"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "whatsapp",
    title: "WhatsApp",
    summary:
      "Design a real-time messaging system with delivery receipts, group chat, and end-to-end encryption.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Messaging", "Distributed Systems"],
    companies: ["Meta", "Amazon", "Microsoft"],
    tags: ["WebSockets", "Delivery", "E2E Encryption", "Presence"],
    popularity: 95,
    frequency: "Very High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "slack",
    title: "Slack",
    summary:
      "Design a team-messaging platform with channels, threads, presence, search, and integrations.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Messaging"],
    companies: ["Amazon", "Microsoft", "Meta"],
    tags: ["Channels", "WebSockets", "Search", "Presence"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "discord",
    title: "Discord",
    summary:
      "Design a chat + voice platform with servers, channels, low-latency voice, and presence at scale.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Messaging", "Video"],
    companies: ["Meta", "Amazon", "Netflix"],
    tags: ["Voice", "WebRTC", "Presence", "Sharding"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "dropbox",
    title: "Dropbox",
    summary:
      "Design a file-sync and storage service with chunking, deduplication, and conflict resolution.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Storage"],
    companies: ["Amazon", "Microsoft", "Google"],
    tags: ["Chunking", "Dedup", "Sync", "Metadata"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "google-drive",
    title: "Google Drive",
    summary:
      "Design a collaborative cloud-storage platform with sharing, versioning, and real-time collaboration.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Storage"],
    companies: ["Google", "Microsoft", "Amazon"],
    tags: ["Storage", "Versioning", "Sharing", "Collaboration"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "youtube",
    title: "YouTube",
    summary:
      "Design a video-sharing platform: upload/transcoding pipeline, storage, CDN, and view counting.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Video", "Storage"],
    companies: ["Google", "Netflix", "Amazon"],
    tags: ["Transcoding", "CDN", "Streaming", "View Count"],
    popularity: 92,
    frequency: "Very High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "netflix",
    title: "Netflix",
    summary:
      "Design a video-streaming platform with adaptive bitrate, global CDN, and personalized recommendations.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Video"],
    companies: ["Netflix", "Amazon", "Google"],
    tags: ["ABR Streaming", "CDN", "Recommendation", "Encoding"],
    popularity: 91,
    frequency: "High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "uber",
    title: "Uber",
    summary:
      "Design a ride-hailing system with real-time matching, geospatial indexing, and surge pricing.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Maps", "Distributed Systems"],
    companies: ["Uber", "Amazon", "Google"],
    tags: ["Geohash", "Matching", "Dispatch", "Surge Pricing"],
    popularity: 93,
    frequency: "Very High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "amazon",
    title: "Amazon",
    summary:
      "Design an e-commerce platform with catalog, cart, inventory, and order fulfillment at scale.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["E-Commerce", "Storage"],
    companies: ["Amazon", "Microsoft"],
    tags: ["Catalog", "Inventory", "Orders", "Search"],
    popularity: 87,
    frequency: "High",
    estimatedMinutes: 65,
    status: "published",
  },
  {
    slug: "payment-gateway",
    title: "Payment Gateway",
    summary:
      "Design a payment gateway with idempotent charges, ledgers, reconciliation, and PCI compliance.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Payments", "Distributed Systems"],
    companies: ["Stripe", "Amazon", "Uber"],
    tags: ["Idempotency", "Ledger", "Double-Entry", "PCI"],
    popularity: 89,
    frequency: "High",
    estimatedMinutes: 60,
    status: "published",
  },
  {
    slug: "shopping-cart",
    title: "Shopping Cart",
    summary:
      "Design a shopping-cart service with session persistence, inventory holds, and checkout consistency.",
    tier: "common",
    difficulty: "Intermediate",
    categories: ["E-Commerce"],
    companies: ["Amazon", "Stripe"],
    tags: ["Sessions", "Inventory", "Consistency", "Checkout"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "google-calendar",
    title: "Google Calendar",
    summary:
      "Design a calendar system with events, recurrence, invitations, reminders, and timezone handling.",
    tier: "common",
    difficulty: "Intermediate",
    categories: ["Scheduling", "Storage"],
    companies: ["Google", "Microsoft"],
    tags: ["Recurrence", "Timezones", "Reminders", "Invites"],
    popularity: 77,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "published",
  },
  {
    slug: "autocomplete",
    title: "Autocomplete",
    summary:
      "Design a typeahead/autocomplete system with tries, ranking, and sub-50ms suggestions at scale.",
    tier: "common",
    difficulty: "Intermediate",
    categories: ["Search"],
    companies: ["Google", "Amazon", "LinkedIn"],
    tags: ["Trie", "Ranking", "Prefix Search", "Caching"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 50,
    status: "published",
  },
  {
    slug: "google-search",
    title: "Google Search",
    summary:
      "Design a web-search engine: crawling, inverted index, ranking, and low-latency query serving.",
    tier: "common",
    difficulty: "Advanced",
    categories: ["Search", "Distributed Systems"],
    companies: ["Google", "Microsoft"],
    tags: ["Crawling", "Inverted Index", "Ranking", "Sharding"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 70,
    status: "published",
  },

  // 🟣 Advanced Distributed Systems
  {
    slug: "kafka",
    title: "Kafka",
    summary:
      "Design a distributed event-streaming log with partitions, replication, and consumer groups.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Messaging", "Distributed Systems"],
    companies: ["Databricks", "Amazon", "LinkedIn", "Netflix"],
    tags: ["Log", "Partitions", "Replication", "Consumer Groups"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "rabbitmq",
    title: "RabbitMQ",
    summary:
      "Design a message broker with exchanges, queues, routing, acknowledgements, and delivery guarantees.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Messaging", "Distributed Systems"],
    companies: ["Amazon", "Microsoft"],
    tags: ["Broker", "Routing", "Acks", "Delivery"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "distributed-queue",
    title: "Distributed Queue",
    summary:
      "Design an SQS-style distributed queue with at-least-once delivery, visibility timeouts, and DLQs.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Messaging", "Distributed Systems"],
    companies: ["Amazon", "Uber", "Stripe"],
    tags: ["Queue", "Visibility Timeout", "DLQ", "Idempotency"],
    popularity: 82,
    frequency: "High",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "distributed-lock",
    title: "Distributed Lock",
    summary:
      "Design a distributed lock with fencing tokens, TTLs, and safe failover using Redis or ZooKeeper.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Distributed Systems", "Infrastructure"],
    companies: ["Amazon", "Google", "Databricks"],
    tags: ["Locking", "Fencing Token", "Lease", "Consensus"],
    popularity: 83,
    frequency: "High",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "service-discovery",
    title: "Service Discovery",
    summary:
      "Design a service-discovery system with health checks, registration, and client-side load balancing.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Amazon", "Netflix", "Microsoft"],
    tags: ["Registry", "Health Checks", "DNS", "Gossip"],
    popularity: 75,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "feature-flag-platform",
    title: "Feature Flag Platform",
    summary:
      "Design a feature-flag platform with targeting rules, gradual rollouts, and low-latency evaluation.",
    tier: "advanced",
    difficulty: "Intermediate",
    categories: ["Infrastructure"],
    companies: ["Amazon", "Microsoft", "Stripe"],
    tags: ["Flags", "Targeting", "Rollout", "SDK"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "configuration-service",
    title: "Configuration Service",
    summary:
      "Design a dynamic configuration service with versioning, propagation, and safe rollbacks.",
    tier: "advanced",
    difficulty: "Intermediate",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Amazon", "Microsoft", "Databricks"],
    tags: ["Config", "Versioning", "Watch", "Propagation"],
    popularity: 70,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "leader-election",
    title: "Leader Election",
    summary:
      "Design a leader-election mechanism using consensus, leases, and automatic failover.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Distributed Systems"],
    companies: ["Google", "Amazon", "Databricks"],
    tags: ["Raft", "Lease", "Failover", "Quorum"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "consensus",
    title: "Consensus",
    summary:
      "Design a consensus system (Raft/Paxos) providing a replicated, linearizable state machine.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Distributed Systems"],
    companies: ["Google", "Databricks", "Snowflake"],
    tags: ["Raft", "Paxos", "Replicated Log", "Linearizability"],
    popularity: 81,
    frequency: "Medium",
    estimatedMinutes: 70,
    status: "coming-soon",
  },
  {
    slug: "multi-region-database",
    title: "Multi-Region Database",
    summary:
      "Design a globally-distributed database with multi-region replication and conflict resolution.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Storage", "Distributed Systems"],
    companies: ["Google", "Amazon", "Snowflake", "Databricks"],
    tags: ["Replication", "Consistency", "Conflict Resolution", "Geo"],
    popularity: 84,
    frequency: "High",
    estimatedMinutes: 70,
    status: "coming-soon",
  },
  {
    slug: "service-mesh",
    title: "Service Mesh",
    summary:
      "Design a service mesh with sidecar proxies, mTLS, traffic shaping, and observability.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Google", "Amazon", "Microsoft"],
    tags: ["Sidecar", "mTLS", "Traffic Shaping", "Envoy"],
    popularity: 73,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "distributed-transaction",
    title: "Distributed Transaction",
    summary:
      "Design distributed transactions with sagas, two-phase commit, and eventual consistency tradeoffs.",
    tier: "advanced",
    difficulty: "Advanced",
    categories: ["Distributed Systems", "Payments"],
    companies: ["Stripe", "Amazon", "Uber"],
    tags: ["Saga", "2PC", "Outbox", "Idempotency"],
    popularity: 80,
    frequency: "High",
    estimatedMinutes: 60,
    status: "coming-soon",
  },

  // 🟠 Staff / Principal
  {
    slug: "ci-cd",
    title: "CI/CD",
    summary:
      "Design a CI/CD platform with build pipelines, artifact storage, and safe progressive deployments.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure"],
    companies: ["Microsoft", "Amazon", "Databricks"],
    tags: ["Pipelines", "Artifacts", "Runners", "Deployments"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "terraform-cloud",
    title: "Terraform Cloud",
    summary:
      "Design an infrastructure-as-code control plane with state management, locking, and plan/apply runs.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure"],
    companies: ["Microsoft", "Amazon"],
    tags: ["IaC", "State", "Locking", "Runs"],
    popularity: 68,
    frequency: "Low",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "github",
    title: "GitHub",
    summary:
      "Design a code-hosting platform with Git storage, pull requests, CI hooks, and search.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Storage", "Infrastructure"],
    companies: ["Microsoft", "Amazon", "Google"],
    tags: ["Git", "Storage", "Webhooks", "Search"],
    popularity: 82,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "jira",
    title: "Jira",
    summary:
      "Design an issue-tracking platform with flexible workflows, permissions, and cross-project search.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["E-Commerce", "Storage"],
    companies: ["Microsoft", "Amazon"],
    tags: ["Workflows", "Permissions", "Search", "Multi-tenant"],
    popularity: 65,
    frequency: "Low",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "cloud-monitoring",
    title: "Cloud Monitoring",
    summary:
      "Design a cloud-scale monitoring platform ingesting metrics, logs, and traces with alerting.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Monitoring", "Infrastructure"],
    companies: ["Amazon", "Microsoft", "Databricks"],
    tags: ["Metrics", "Traces", "Alerting", "Multi-tenant"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "cloud-storage",
    title: "Cloud Storage",
    summary:
      "Design an S3-style object store with durability, erasure coding, and multi-region replication.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Storage", "Distributed Systems"],
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["Object Store", "Erasure Coding", "Durability", "Replication"],
    popularity: 85,
    frequency: "High",
    estimatedMinutes: 70,
    status: "coming-soon",
  },
  {
    slug: "azure-resource-manager",
    title: "Azure Resource Manager",
    summary:
      "Design a cloud resource-management control plane with declarative templates and reconciliation.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Microsoft", "Amazon"],
    tags: ["Control Plane", "Templates", "Reconciliation", "RBAC"],
    popularity: 66,
    frequency: "Low",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "kubernetes-scheduler",
    title: "Kubernetes Scheduler",
    summary:
      "Design a container scheduler with bin-packing, constraints, priorities, and preemption.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Google", "Amazon", "Microsoft"],
    tags: ["Scheduling", "Bin Packing", "Affinity", "Preemption"],
    popularity: 80,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "control-plane",
    title: "Control Plane",
    summary:
      "Design a generic control plane with declarative desired state, reconciliation loops, and drift detection.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Google", "Amazon", "Microsoft"],
    tags: ["Reconciliation", "Desired State", "Operators", "Drift"],
    popularity: 71,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "event-bus",
    title: "Event Bus",
    summary:
      "Design an org-wide event bus with schema registry, routing, replay, and exactly-once semantics.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Messaging", "Distributed Systems"],
    companies: ["Amazon", "Netflix", "Databricks"],
    tags: ["Pub/Sub", "Schema Registry", "Replay", "Routing"],
    popularity: 72,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "global-load-balancer",
    title: "Global Load Balancer",
    summary:
      "Design a global load balancer with geo-DNS, anycast, health-aware routing, and failover.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Google", "Amazon", "Netflix"],
    tags: ["Geo-DNS", "Anycast", "Health Routing", "Failover"],
    popularity: 78,
    frequency: "Medium",
    estimatedMinutes: 60,
    status: "coming-soon",
  },
  {
    slug: "multi-tenant-saas",
    title: "Multi-Tenant SaaS",
    summary:
      "Design a multi-tenant SaaS platform with isolation, per-tenant scaling, and noisy-neighbor control.",
    tier: "staff",
    difficulty: "Advanced",
    categories: ["Infrastructure", "Distributed Systems"],
    companies: ["Microsoft", "Amazon", "Snowflake", "Databricks"],
    tags: ["Isolation", "Tenancy", "Sharding", "Quotas"],
    popularity: 79,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },

  // 🔴 AI System Design
  {
    slug: "chatgpt",
    title: "ChatGPT",
    summary:
      "Design a conversational-AI product: inference serving, streaming, context, and safety at scale.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI", "Distributed Systems"],
    companies: ["OpenAI", "Microsoft", "Google"],
    tags: ["LLM Serving", "Streaming", "Context Window", "Safety"],
    popularity: 94,
    frequency: "High",
    estimatedMinutes: 70,
    status: "coming-soon",
  },
  {
    slug: "ai-copilot",
    title: "AI Copilot",
    summary:
      "Design an AI coding copilot with low-latency completions, context retrieval, and telemetry.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI"],
    companies: ["Microsoft", "OpenAI", "Google"],
    tags: ["Completions", "Context", "Latency", "Ranking"],
    popularity: 88,
    frequency: "High",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "rag",
    title: "RAG",
    summary:
      "Design a retrieval-augmented generation system with chunking, embeddings, retrieval, and grounding.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI", "Search"],
    companies: ["OpenAI", "Databricks", "Microsoft"],
    tags: ["Retrieval", "Embeddings", "Chunking", "Grounding"],
    popularity: 90,
    frequency: "High",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "vector-database",
    title: "Vector Database",
    summary:
      "Design a vector database with ANN indexing (HNSW/IVF), filtering, and horizontal scaling.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI", "Storage"],
    companies: ["Databricks", "OpenAI", "Snowflake"],
    tags: ["ANN", "HNSW", "Embeddings", "Sharding"],
    popularity: 86,
    frequency: "High",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "prompt-cache",
    title: "Prompt Cache",
    summary:
      "Design a prompt/response cache for LLMs with semantic keys, TTLs, and cost-aware eviction.",
    tier: "ai",
    difficulty: "Intermediate",
    categories: ["AI", "Storage"],
    companies: ["OpenAI", "Databricks", "Microsoft"],
    tags: ["Semantic Cache", "Embeddings", "Eviction", "Cost"],
    popularity: 74,
    frequency: "Medium",
    estimatedMinutes: 50,
    status: "coming-soon",
  },
  {
    slug: "ai-agent",
    title: "AI Agent",
    summary:
      "Design an autonomous AI agent platform with tool calling, memory, planning, and guardrails.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI", "Distributed Systems"],
    companies: ["OpenAI", "Microsoft", "Databricks"],
    tags: ["Tool Calling", "Memory", "Planning", "Orchestration"],
    popularity: 85,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
  {
    slug: "embedding-service",
    title: "Embedding Service",
    summary:
      "Design an embedding service with batching, GPU pooling, versioning, and a downstream vector store.",
    tier: "ai",
    difficulty: "Intermediate",
    categories: ["AI", "Infrastructure"],
    companies: ["OpenAI", "Databricks", "Snowflake"],
    tags: ["Batching", "GPU", "Versioning", "Throughput"],
    popularity: 76,
    frequency: "Medium",
    estimatedMinutes: 55,
    status: "coming-soon",
  },
  {
    slug: "model-serving-platform",
    title: "Model Serving Platform",
    summary:
      "Design an ML model-serving platform with autoscaling, GPU scheduling, canaries, and A/B routing.",
    tier: "ai",
    difficulty: "Advanced",
    categories: ["AI", "Infrastructure"],
    companies: ["Databricks", "OpenAI", "Amazon", "Netflix"],
    tags: ["Inference", "Autoscaling", "GPU", "Canary"],
    popularity: 83,
    frequency: "Medium",
    estimatedMinutes: 65,
    status: "coming-soon",
  },
];

/** The full question catalog, with `addedOrder` derived (earlier = newer). */
export const SD_CATALOG: SDQuestionMeta[] = RAW_CATALOG.map((q, i) => ({
  ...q,
  addedOrder: RAW_CATALOG.length - i,
}));
